### PR TITLE
Fix/7402 path connection different entrance z

### LINKED ISSUE #7402: Non-mowing handyman can leave the path if there is a ride exit immediately above that path.
**OS:**  Windows 8
**Version:** e.g. 0.1.3
**Commit/Build:** 69bb1cd

I kept randomly having this handyman wandering around in the grass, rather than being on the path he was assigned to be on, so I watched him for a while to find out where he's leaving the path.

It turns out, he can leave the path directly under a ride exit that _would_ connect to that path ... if it was 2 squares lower. Yet the path is actually rendering as if it has a connection there, even though there is nothing for it to connect to. (No previous path was built on the spot it's trying to connect to.)

No guests try to leave the path at that spot (thank goodness), but it is problematic that the handyman keeps leaving.

I tried to re-create this glitch in a blank Forest Frontiers, but I couldn't get it to happen again. I'll include the save game where it did happen. This seems like it's an extremely rare glitch that may only show up during certain circumstances, but something to do with the way ride exits connect to paths.

- [Unknown] Reproducible in RCT2 (vanilla)?
- [no] Specific to multiplayer?

**Steps to reproduce:** (This is how I produced it in the first place. It's proving difficult to reproduce.)
1. Build a path along the ground.
2. Build a ride exit where it would connect to that path, except 2 spaces higher.
3. Connect that ride exit to a different path (this new path will overlap the first one).
4. Place a handyman on the lower path.

**Screenshots / Video:**
The situation:
giggle downs 2018-04-11 03-37-13e

Without the red circle, in case that makes it easier to see:
giggle downs 2018-04-11 03-37-13

Ride exit visible (but now blocking view of the broken path):
giggle downs 2018-04-11 03-37-21

In 'highlight path issues mode' for best visibility -- I just caught him leaving the path!
giggle downs 2018-04-11 03-37-51

**Save game:**
[Giggle Downs.zip](https://github.com/OpenRCT2/OpenRCT2/files/1898474/Giggle.Downs.zip)

### PR DESCRIPTION
**Pull request by Broxzier**
This fixes #7402 by checking the height of the entrance or exit, and adds some tests for it.

I'd like someone with more experience with CMake to check if the `CMakeLists.txt` file is correct. I don't know how to test that one.

### CODE REVIEW

**Comment by IntelOrca** [comment]
It is good practice to separate each test scenario into a new test case. So for each block of asserts you have so far, you should separate into a new test case. You can call a common function for the setup or use gtest test fixture setup infrastructure to do the common initialisation.

**Comment by Broxzier** [comment]
I wanted to avoid loading `tile-element-tests.sv6` for every test case, as that takes the most amount of time here.

**Comment by IntelOrca** [comment]
Yeah the fixture setup is good. It shouldn't take very long to initialise in release mode, at least if you look at AppVeyors test list, the durations are < 5ms altogether for your fixture.

https://ci.appveyor.com/project/IntelOrca/openrct2-ject9/build/0.1.3.13752/job/1yyirafwyeiqxmyh/tests

**Comment by Broxzier** [comment]
gtest seems to start measuring after `SetUpTestCase` has been called. Before the tests were split it would only load the park once, yet the total time was > 300ms.

**Pull request merged**
