### PR TITLE
Prevent access to invalid banner in game command

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by janisozaur** [comment]
Should this get new network version?

**Comment by Gymnasiast** [comment]
Well, the criterion for me is when we _think_ it might cause desyncs, so I'd raise it.

**Comment by janisozaur** [comment]
This grew in scope to cover some more edge cases and it now carries network version 19

**Comment by janisozaur** [comment]
This PR has been on for a while, the only debatable thing is #3136 which @duncanspumpkin commented on in the issue already, so I'm going to merge it.

**Pull request merged**
