### PR TITLE
Fix  #22353: Water Only Ride Build Fails

### LINKED ISSUE #22353: Water Only Ride Build Fails
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.12 (1b5ff88) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

A ride build for a water only ride fails when it should be allowed.  Playing Haunted Harbor park.

Error screen:

No Water Build

Park save is attached:

[Haunted Harbor.zip](https://github.com/user-attachments/files/16338431/Haunted.Harbor.zip)

Ride is attached:

[Babel catboat kty.zip](https://github.com/user-attachments/files/16338590/Babel.catboat.kty.zip)

### Steps to reproduce

1.  Start a game with Haunted Harbor park
2.  Attempt to build water rude Babel catboat kty ride in harbor
3. Get error message that must be built on water

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by chrislikescisco**
For [#22353](https://github.com/OpenRCT2/OpenRCT2/issues/22353). Made a minor change to the track placement code so the incorrect error message no longer appeared. Specifics are included in the commit message for 493b49b. 493b49b and 44eb2bf are the only relevant commits, the others are because I originally pushed changes to the develop branch, and realized we are not supposed to do this after reading the contribution instructions more carefully.

### CODE REVIEW

**Comment by 733737** [comment]
This change makes no sense. You are making it so that building a water ride on the water is blocked.

**Comment by chrislikescisco** [comment]
I built the repository and it still allowed me to build the ride on water, see below:
Screenshot 2024-10-02 212503
Whereas the message shown in the original image is now correct:
Screenshot 2024-10-02 212601

**Comment by 733737** [comment]
This is not the right way to fix the issue

**Comment by chrislikescisco** [comment]
Gotcha, do you have any idea what else could be causing it then? I'm pretty sure this is the check that's triggering the original message, other references to STR_CAN_ONLY_BUILD_THIS_ON_WATER within the file did not affect it when changed.

**Comment by 733737** [comment]
@Gymnasiast we need one of the main developers to analyze exactly what's going on. Just from a readability perspective, this doesn't seem right to me.

**Comment by spacek531** [comment]
With the change as it is, I am allowed to build boat rides above water.
image
This is because with the change flips it so that boat rides *cannot* be built at the same height as water - the code in the conditional returns an error message.

**Comment by Gymnasiast** [comment]
@733737 Thanks for trying to help out, but we prefer doing the code review ourselves.

**Comment by Gymnasiast** [comment]
Closing this, as we received no answer.

**Comment by chrislikescisco** [comment]
@Gymnasiast Sorry about that, I got caught up with other work. I think this is probably best handled by somebody with more knowledge of the repository

**Pull request closed without merging**
