### PR TITLE
Allow building level crossings without cheats

### PR DESCRIPTION
**Pull request by Gymnasiast**
forest frontiers 2017-12-14 20-12-30

### CODE REVIEW

**Comment by Patrik356b** [comment]
As cool as this is, will peeps and staff wait for the train to pass, and will this only work with straight track pieces?

**Comment by IntelOrca** [comment]
I tried to do this a few weeks ago but hit this issue which you have as well. That was when I decided this was more work than expected. Although I did try to do it without altering the clear func signature - it will be easier when everything is C++ and we can use lambdas.

image

**Comment by IntelOrca** [comment]
It should be probably be disabled for non-ground.

image

**Comment by Gymnasiast** [comment]
@IntelOrca Fixed that as well.

**Comment by briancappello** [comment]
Awesome feature! I don't have any say in how it would affect the code, but as a player, I wonder if it wouldn't be more consistent if it worked on any flat crossing (whether on the ground or elevated)? Either way I'd be very happy to see this land; much thanks for all the sweet improvements you guys have been working on!

**Comment by Patrik356b** [comment]
@briancappello the problem with elevated paths is the railings though. especially for custom paths

**Comment by briancappello** [comment]
Certainly, I don't doubt that it might require some new sprites and probably add some complexity. Perhaps a crossing gate that's "open" when there's no train (visually blocking peds from walking perpendicularly on the tracks) and "closed" when the train is passing (visually blocking peds from crossing the tracks). Perhaps said gate could share the same styles as the path railings? Like I said I don't have any understanding of the code or how the sprites work so I don't know if it would be possible/worth the effort. Suppose I was just sharing a personal opinion from a random dude on the internet :)

**Comment by Gymnasiast** [comment]
@briancappello @Patrik356b Well, it would require appropriate graphics, but there is also this to consider: level crossings IRL are never elevated. If the path or rail is already elevated, building a bridge is far easier and safer.

**Pull request merged**
