### PR TITLE
Brightness Slider in Display Options

### PR DESCRIPTION
**Pull request by 733737**
does not add a function for brightness to the code yet
211969373-00bdb4d1-8a24-4c79-90a3-eeed4c2f2d77

### CODE REVIEW

**Comment by ocalhoun6** [comment]
Wouldn't this normally just be handled by the user adjusting their monitor's brightness?

Unless for some weird reason, they want OpenRCT2 to run more/less bright than everything else on their system?

**Comment by 733737** [comment]
not all users know how to adjust their monitors' brightness. Also, hardware versus software brightness are two different things. I see the main use being power saving, or if the user has trouble seeing certain details in a park they can bump up the brightness.

**Comment by Gymnasiast** [comment]
> not all users know how to adjust their monitors' brightness.

That is not a good reason to implement a feature. If people want to adjust brightness, they should learn how that works on their monitor (or even their graphics card software) - that enables them to adjust for _everything_ they do and not just OpenRCT2.

> I see the main use being power saving, or if the user has trouble seeing certain details in a park they can bump up the brightness.

Both of these goals are much more efficiently achieved if the users adjusts their actual monitor’s brightness.

For these reasons, I unfortunately have to reject this PR.

**Comment by karst** [comment]
For people who want to adjust their screen brightness n windows I recommend getting [Twinkle Tray](https://github.com/xanderfrangos/twinkle-tray).

**Pull request closed without merging**
