### PR TITLE
Bug Fix: Mechanics can fix/service closed rides

### LINKED ISSUE #18739: Mechanics can Repair Rides That are Closed
### Operating System

WIndows 10

### OpenRCT2 build

v0.4.2 (8ceea45)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

_No response_

### Describe the issue

Mechanics can repair closed rides, even if the ride has never been tested or opened. This does not occur in the base game, meaning it has to be a bug. It also feels incredibly unfair, as the reliability can be increased back to 100% by leaving a ride closed, and letting mechanics inspect it repeatedly.

### Steps to reproduce

1. Build or have a ride in the park. I used a classic wooden coaster, but it seems to work with all other rides as well.
2. Connect the exit to a path, so mechanics can access the ride.
3. Wait for a mechanic to inspect it. Any inspection time works.
4. This should not happen. This does not happen in RCT2 either. I do not know if it occurs in RCTC.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by kurbus**
fixes #18739 
some of these fixes might not work, so if any of you veterans of this repo want to fix my code in staff.cpp you're welcome to
can't build this atm but will asap

### CODE REVIEW

**Comment by Gymnasiast** [comment]
That "bug report" is riddled with vagaries, I highly doubt it is valid. Let’s first find out how much of it is actually a bug and not unfounded assumptions on OP’s part.

**Comment by kurbus** [comment]
that's alright. still though, i'd like to contribute to this project somehow, so you may see me in some other issues

**Comment by Gymnasiast** [comment]
Ok great. You can look for issues with the "good first issue" label here: https://github.com/OpenRCT2/OpenRCT2/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

These issues should generally be doable without having too much in-depth knowledge of our codebase. Do note that you will need to find out how to build the game for yourself and test your changes. This should be documented in our readme and wiki, and you can ask additional questions about it on Discord.

**Comment by kurbus** [comment]
it build fine under cMake and Make right? (i use macOS)

**Comment by Gymnasiast** [comment]
Yep.

**Pull request closed without merging**
