### PR TITLE
Pass SDL_WINDOW_ALLOW_HIGHDPI to SDL_CreateWindow

### PR DESCRIPTION
**Pull request by tomlankhorst**
Per @AaronVanGeffen 's request, the hi-dpi handling split of #10118

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Cheers! I think this deserves a mention in the changelog, too.

**Comment by IntelOrca** [comment]
I think this only applies to macOS? Maybe say that in the changelog.

**Comment by tomlankhorst** [comment]
@IntelOrca I have no HiDPI non-macOS device to test, but the SDL documentation does not mention any MacOS specifics here.

**Comment by IntelOrca** [comment]
@tomlankhorst I think I only found it out by checking the source code. Although it was awhile aback now, but I doubt it has changed.

**Pull request merged**
