### PR TITLE
Fix game advancing too fast when game was paused/frozen.

### PR DESCRIPTION
**Pull request by ZehM4tt**
Regression from #5848, Issue https://github.com/OpenRCT2/OpenRCT2/issues/5810#issuecomment-314435049. Sorry I somehow missed this.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Could you put braces around the if?

**Comment by ZehM4tt** [comment]
Sure thing, will do.

**Comment by IntelOrca** [comment]
Your commit does not follow our guidelines: https://github.com/OpenRCT2/OpenRCT2/wiki/Commit-Messages

It needs to be `Fixed #000: Your text`

**Comment by ZehM4tt** [comment]
Its not directly a fix for #5810, that is already another PR. I just referenced this in the PR as someone posted a video showing the current issue. I'm not quite sure what to say in the commit message other than what I actually fixed.

**Comment by janisozaur** [comment]
@IntelOrca there's no open issue to be fixed by this PR.

**Pull request merged**
