### PR TITLE
Fix #11043: Null banner object had method called on itself

### LINKED ISSUE #11043: BACKTRACE 9d0ea9
<table>
    <tr>
        <td></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/9d0ea96b2f3efb72e887604c770b71a03441f4bffd07bac3e88b7981a4114cea?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Wed Mar 25 2020 20:13:32)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.com</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6.gz:</strong> D:\\Games\\OpenRCT2\\userdata\\89b5caa7-dff4-422e-ba36-25ecd5703011.sv6.gz: <em>1</em><br><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> D:\\Games\\OpenRCT2\\userdata\\89b5caa7-dff4-422e-ba36-25ecd5703011.ini: <em>1</em><br><strong>assert_failure:</strong> *: <em>1</em><br><strong>attachment_screenshot.png:</strong> D:\\Games\\OpenRCT2\\userdata\\screenshot\\Six Flags Great Adventure 2020-03-25 21-13-33.png: <em>1</em><br><strong>commit:</strong> 8373fe6: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>openrct2.com -> openrct2.com -> openrct2.com -> openrct2.com -> openrct2.com -> openrct2.com -> openrct2.com -> openrct2.com -> openrct2.com -> openrct2.com -> openrct2.com -> openrct2.com -> openrct2.com -> openrct2.com -> openrct2.com -> openrct2.com -> openrct2.com -> openrct2.com -> openrct2.com -> openrct2.com -> openrct2.com -> ntdll.dll -> openrct2.com -> openrct2.com -> openrct2.com -> openrct2.com -> openrct2.com -> ntdll.dll -> ntdll.dll -> openrct2.com -> openrct2.com -> openrct2.com -> openrct2.com -> ntdll.dll -> openrct2.com -> openrct2.com -> kernel32.dll -> ntdll.dll</code></td></tr>
</table>

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by janisozaur** [comment]
The  same check was applied just a bit earlier:
https://github.com/OpenRCT2/OpenRCT2/blob/ace0288f0940c98477fd88fb943f75059762afcc/src/openrct2/paint/tile_element/Paint.LargeScenery.cpp#L312-L314

**Comment by Gymnasiast** [comment]
LGTM. Is this something to put in the changelog?

**Comment by janisozaur** [comment]
@Gymnasiast you tell me.

BTW, offending file: 
[park_11043.sv6.gz](https://github.com/OpenRCT2/OpenRCT2/files/4383649/park_11043.sv6.gz)

**Comment by duncanspumpkin** [comment]
This was triggered due to the mistake on import. So no need to changelog it imho

**Pull request merged**
