### PR TITLE
Split up misc list access to be type specific

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Took the opertunity to use a fold expression to simplify the code

Might break replays.
Note this decreases performance for now.

### CODE REVIEW

**Review by tupaschoal — APPROVED** [review]
First I had to understand fold expressions (which I was unaware of and if anyone wants to, here's a [link](https://www.youtube.com/watch?v=nhk8pF_SlTk)).

After that, I think it looks fine :D

**Comment by Broxzier** [comment]
Sure looks better, but now it iterates the list for each type if I understand this correctly, right?

**Comment by duncanspumpkin** [comment]
It does for now but I'll be adding extra type specific lists in a couple PRs time. Do note also that there is not a lot of misc entries at any time.

**Comment by Broxzier** [comment]
Just saw your message on Discord, splitting them up into separate lists will make this a lot better indeed. :)

**Pull request merged**
