### PR TITLE
Change Xcode dependencies bundle to download

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
This ties in with a new release of the [macOS dependencies](https://github.com/OpenRCT2/Dependencies/releases/tag/v22):

jansson 2.9.0 -> 2.12.0
libfreetype 2.9.1 -> 2.10.1
libicu 61.1 -> 64.2
libpng 1.6.25 -> 1.6.37
libsdl2 2.0.9 -> 2.0.10
libzip 1.1.3 -> 1.6.1
openssl 1.0.2j -> 1.1.1d
speexdsp 1.2.

I will release a version that includes duktape after this, as that shouldn't be in v0.2.5 yet.

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
@tomlankhorst Does this fix #10520, by any chance?

**Comment by AaronVanGeffen** [comment]
@Gymnasiast Thanks for reviewing this. Were you able to test a build on a Mac, by any chance? I'd like to verify it works properly on a computer that isn't mine.

**Comment by Gymnasiast** [comment]
@AaronVanGeffen Yup, works correctly on my macOS 10.14 (Mojave) VM, compiling with Xcode 10.1.

**Comment by janisozaur** [comment]
You just missed sdl2 2.0.12 release: https://discourse.libsdl.org/t/sdl-2-0-12-released/27318

**Comment by AaronVanGeffen** [comment]
Oh no. :joy: Going by the changelog, it looks like it's mostly new features rather than bugfixes, though, fortunately.

**Comment by tomlankhorst** [comment]
I did not even use xcode, as I build with cmake typically, but still, the issue seems fixed in master somewhere between my observation and now. 

Also, the xcode build works fine. 

Thanks anyway!

**Pull request merged**
