### PR TITLE
Cheat to tell all guests to leave the park

### PR DESCRIPTION
**Pull request by Hris7**
Same as #6472, but in the cheat-window

### CODE REVIEW

**Comment by mrtnptrs** [comment]
This is really similar to the cheat to delete all guests at once or make them explode one by one. This cheat will likely just make the cheats window more complicated, while adding almost nothing to the game. I liked #6472 much better, but it seems to just need a confirmation message box and not be a cheat.

**Comment by ccoors** [comment]
I prefer this version over #6472.

**Comment by mrtnptrs** [comment]
@ccoors what do you think of the #6472 approach, but then with a confirmation window after double clicking on the close-park-button?

**Comment by ccoors** [comment]
I don't know about that. Maybe because I dislike the in-game confirmation windows with their waaaaay too small buttons. A cheat is okay for this feature I guess.

**Comment by Nubbie** [comment]
I think it doesnt add much, instead just makes a fourth way of removing guests from the park, especilly if its in the cheat window which already have 3 options for that (remove all guests, explode, close park)

**Comment by rwjuk** [comment]
I'm also not entirely sure what problem this is intended to solve, or what use-case there would be for it. @Hris7 could you enlighten me?

**Comment by Gymnasiast** [comment]
I think this is just for immersion purposes. After all, it feels more "real" when guests actually leave the park, rather than just disappear on the click of a button. Son of Beast had a feature like this, called "Home time".

A feature like this is all nice and dandy, but should be a plug-in. So should the Explode! cheat, by the way.

**Pull request closed without merging**
