### PR TITLE
Add /usr/local/share to search path for data files

### PR DESCRIPTION
**Pull request by oslerw**
Addresses issue #2630

### CODE REVIEW

**Comment by fbourigault** [comment]
If cmake works like autotools, /usr and /usr/local are just build prefix. The right path should be set at build time.

**Comment by janisozaur** [comment]
Yes, you can set build prefix at configure time, and this one seems to be default. I'm not sure why it doesn't get picked up and haven't looked into that yet.

The explanation given in #2630 is quite convincing, though, and I'm leaning to +1 for this change.

**Comment by fbourigault** [comment]
The path L131 should not be hardcoded and use build prefix

**Comment by janisozaur** [comment]
This should already be covered by https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/platform/linux.c#L128

**Comment by oslerw** [comment]
I took a second look stepping through with gdb, and it looks like `ORCT2_RESOURCE_DIR` resolves to `"/share/openrct2/"`, so it looks like for me CMAKE_INSTALL_PREFIX might be unset.

**Comment by janisozaur** [comment]
@oslerw I have almost never ran this script and only use it for travis builds. Instead I run `cmake` & `make` manually.

I'll see if I can figure out why it gets changed.

I also admit I have never really tried doing `make install` without explicitly setting prefix to some local directory beforehand.

Given that it might be the best option to merge this. Any other opinions?

**Comment by AaronVanGeffen** [comment]
I'm all for it. `/usr/local/share` is *the* place to dump shared assets if you're not using the package manager.

**Comment by janisozaur** [comment]
Is there any particular order we should be using for searching these dirs?

I think it may be worth putting `/usr/local` higher up, as with local version you may want to overwrite what came in the package, which wouldn't be possible the other way round (at least not without modifying package-provided files and upsetting the package manager).

**Comment by AaronVanGeffen** [comment]
For what it's worth, I agree.

**Comment by oslerw** [comment]
Oops! That last commit was a bad one. Give me one moment to roll it back, I made a bit of a mistake. I agree that local should be much higher up on that list.

**Comment by oslerw** [comment]
Sorry about that, I'm a little new to pull requests on GitHub. I can squash these and submit a new PR if necessary.

This commit should address things. I assume that a user would want things in order from "most local" to "least local" in which case the relative path should still take priority over /usr/local, then the system paths that are likely used by the package manager.

**Comment by AaronVanGeffen** [comment]
The change looks good, but you might want to squash the commits through an interactive rebase (`git rebase -i`).

**Comment by janisozaur** [comment]
:+1:

**Pull request merged**
