### PR TITLE
Fixed issue #17221

### PR DESCRIPTION
**Pull request by guljam**
Fixed Land tool cursor position (issue #17221)

### CODE REVIEW

**Review by Broxzier — CHANGES_REQUESTED** [review]
Change works as expected. Please add a changelog entry for this fix.

**Comment by guljam** [comment]
Updated code to fix all issues for #17221

**Comment by guljam** [comment]
The code works fine. I also updated the changelog.
I hope this will be merge :P

**Comment by Broxzier** [comment]
You've now added a lot more changes that weren't part of this PR before. Please keep PRs to just one feature change per item. Revert this back to just the land tool cursor changes, and create a new PR for the tooltip changes. Then things can be discussed individually without getting other changes in the way.

The linked issue should also be split into independent issues, even if they are somewhat related to each other.

**Comment by karst** [comment]
I highly recommend to not work from develop. Create a seperate branch per feature change. 
It will save you alot of issues in the future aswell.

**Comment by guljam** [comment]
@Broxzier @karst Thanks for the review. I will try PR with another branch soon.

**Pull request closed without merging**
