### PR TITLE
Remove use of 'using namespace' from headers

### PR DESCRIPTION
**Pull request by Broxzier**

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Could you at least explain _why_?

**Comment by Broxzier** [comment]
To avoid conflicts in the future. Source files that include these headers will be using the namespaces as well, which may be undesired. Right now, for example, `src/world/Park.cpp` includes `ParkSetNameAction.hpp`, which uses namespace OpenRCT2. If in the future a function gets created that shares their name with a function not in the namespace, Park.cpp will have a conflict not knowing which function it should use.

https://stackoverflow.com/questions/5849457/using-namespace-in-c-headers

**Comment by Gymnasiast** [comment]
Ok. Leaving it to @janisozaur and @IntelOrca then.

**Comment by IntelOrca** [comment]
Yeah, its because these files get mistaken for source files, but they are actually header files for convenience. Header files should not use namespaces unless they are scoped to their own class or method, I can't remember if that is possible or not.

**Pull request merged**
