### PR TITLE
Clang format cpp and hpp

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by IntelOrca** [comment]
Can you do all the files? Certainly a lot of .h files are still C++

**Comment by janisozaur** [comment]
Sure, I'll do this in a moment.

**Comment by IntelOrca** [comment]
Most of it seems okay, and it does align arrays but the following is annoying:

* Modifying the pragmas
* Not indenting extern "C" blocks (although i could live with it)
* Putting opening switch braces on their own lines
* Not aligning the member names in interfaces or classes which are together.

**Comment by janisozaur** [comment]
Out of these, I think only the third leaves a room for possible improvement.

Check http://zed0.co.uk/clang-format-configurator/ if you can make it do what you want (do select clang-format 3.9.0).

**Comment by janisozaur** [comment]
Can you show an exhibit of this:

> Not aligning the member names in interfaces or classes which are together.

**Comment by IntelOrca** [comment]
You need `NamespaceIndentation: All`

**Comment by IntelOrca** [comment]
I also notice its putting while clauses after a do end brace

**Comment by janisozaur** [comment]
> You need NamespaceIndentation: All

done

**Comment by IntelOrca** [comment]
Its completely broken all the formatting of all the window widget arrays so that they are not in columns anymore.

**Comment by janisozaur** [comment]
This got rejected by @IntelOrca as not meeting all of his requirements.

**Pull request closed without merging**
