### PR TITLE
New title sequence

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by janisozaur** [comment]
Have you forgotten to add `.sv6`s?

**Comment by IntelOrca** [comment]
> Also: [ci skip]

Why?

**Comment by janisozaur** [comment]
why waste cycles when it's not producing anything?

**Comment by IntelOrca** [comment]
@janisozaur to test the build with the new sequence?

**Comment by janisozaur** [comment]
but we merged the dont-push-unless-on-develop commit. CIs have nothing to do here, they just copy whatever is in those dirs and package it and don't even expose anywhere. You can just fetch this change into your local clone with `git fetch origin refs/pull/3310/head && git checkout FETCH_HEAD` and there is really no need to build it, as we have no checks for it anyway.

**Comment by Gymnasiast** [comment]
The SV6 files are now included.

**Comment by janisozaur** [comment]
:+1: I like it.

One comment though: should we remove old sequence? We could simply move it to `openrct2-0.0.3`

**Comment by IntelOrca** [comment]
Or just append the old title sequence to the new one, like RCT1+AA did.

**Comment by janisozaur** [comment]
I would find it better to have distinct title sequences for each version that has them. I think they loop nicer and let their designer set their tone, which I believe was there with this one.

**Comment by janisozaur** [comment]
The old parks are 11MB in total, it may not be worth keeping them packaged in each and every zip.

Let's just merge this then and we can publish the 0.0.3 title sequence elsewhere or point them to the old files.

Perhaps we would get the feed for title sequence for 0.0.5 ready.

**Pull request merged**
