### PR TITLE
Add Steam install location

### PR DESCRIPTION
**Pull request by CraigCraig**

### CODE REVIEW

**Comment by Phyxion** [comment]
Not everyone has it installed on C

**Comment by fromthere** [comment]
@Phyxion It's just **common** install location. if users installed in other path, user can input themselves.

**Comment by CraigCraig** [comment]
@Phyxion, Yes what @fromthere said, it's a common install location.
I could use the argument that not everyone has GOG installed on C:/
Yet this helps the common people who do.
If they have it installed somewhere else, they're probably savvy enough to find the install location themselves :)

**Comment by Phyxion** [comment]
You can also find the Steam installation folder and go from there (e.g., http://stackoverflow.com/questions/34090258/find-steam-games-folder). Then at least it works for everyone. I don't have Steam installed on C drive and I know that most (active) people in my friendlist don't have it on C either.

**Pull request merged**
