### PR TITLE
Make boosters on Twister and Giga Coaster more practical (#5350)

### PR DESCRIPTION
**Pull request by rwjuk**
As detailed in #5350, the booster acceleration on Twister and Giga coasters is extremely low when compared to both ~~RCT1~~ RCTC and the real-world performance of such LIMs/LSMs.

This PR fixes that; to do so it was necessary to split `rct_ride_properties->acceleration` into `powered_lift_acceleration` and `booster_acceleration`. The acceleration values were copied across for all rides except the two mentioned, which were multiplied by 8.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
The title is not correct. RCT1 only had boosters on the Looping RC and the Steel Corkscrew RC. Those boosters were quite weak.

Boosters for the Giga Coaster, Steel Twister and Junior RC were introduced by RCT Classic. These were a lot more powerful than the RCT1 boosters.

**Comment by rwjuk** [comment]
@Gymnasiast Apologies, it's been a while since I played RCT1, I must have been thinking of RCTC.

**Comment by Gymnasiast** [comment]
A thing that needs to be changed: the vertical drop roller coaster needs to have the same value as the Steel Twister - OpenRCT2 more or less unified the two types.

Also, how did you determine the booster values for the Steel Twister and Giga Coaster?

**Comment by rwjuk** [comment]
@Gymnasiast Will make the Vertical RC change. I tested by replicating the design in the original Reddit post, and a few other Twister RC designs with boosters, and experimenting with the value until the designs worked.

However, I've just acquired RCTC and done a direct comparison, and it seems the values here are far too high compared to the ones there. In RCTC, 10 sections of booster are required to accelerate a 7-car Twister train to 67 mph from stationary. I'll tweak my values to replicate this, and test against RCTC in other circumstances too.

**Comment by Gymnasiast** [comment]
Thanks! There are also the often-overlooked Junior RC boosters in RCTC. So basically, could you make sure that the Steel Twister, Giga Coaster and Junior RC boosters all behave the same as they do in RCTC?
(There are no Vertical Drop RC boosters in RCTC, nor are there Corkscrew RC or Looping RC boosters in RCTC. OpenRCT2 added them to the Vertical Drop RC for parity with the Steel Twister.)

**Comment by rwjuk** [comment]
Will do!

**Comment by Gymnasiast** [comment]
Could you also check if the set launch speed of the boosters in RCTC and OpenRCT2 match?
And what the minimum and maximum values are, and the step size?

**Comment by rwjuk** [comment]
I know they're not, for example the Giga coaster goes far above 67 mph, and the Junior caps out at 31. I'll get the exact figures in a bit.

**Comment by Gymnasiast** [comment]
What I want is that one can import an RCTC game and the booster behave the same. They don't need to have the same min and max values or step size, as long as the speeds import correctly and the acceleration matches.

**Comment by rwjuk** [comment]
Got it - will test just that. I'll create some test rides in RCTC and import them.

**Comment by Gymnasiast** [comment]
Have you been able to test that already?

**Comment by rwjuk** [comment]
95% done, just need to write it up - will do later today.

**Comment by Gymnasiast** [comment]
Having studied two RCTC saves, I have determined that the Giga Coaster multiplies the booster speed by 2. In other words: the value that comes out at 107 km/h in order types comes out at 214 km/h in the Giga Coaster. I'm going to push a commit to your branch to address that.

**Comment by rwjuk** [comment]
You beat me to it! :) I was just looking at that myself. All the others seem okay, but the Giga needed tweaking. Other types transfer okay, even though the top values aren't the same, there's cross-compatibility.

**Comment by Gymnasiast** [comment]
The commit I just pushed makes the booster speeds match RCTC. It needs adjusting of the build window, as it will still display half the speed.

**Comment by rwjuk** [comment]
Wouldn't it be better to multiply the values in `RideProperties` by two rather than having a special case in that function?

**Comment by Gymnasiast** [comment]
No, as booster speed and booster acceleration are two different things entirely.

**Comment by rwjuk** [comment]
Duh. I'm being thick, ignore me, I misread your previous comment. Trying to do too many things at once!!

**Comment by Gymnasiast** [comment]
_Just_ as I finished my implementation of the same thing!

**Comment by rwjuk** [comment]
Ah! Sorry! I'll leave it to your judgement as to which implementation is better!

**Comment by Gymnasiast** [comment]
I initially tried to do the same as you, but I noticed that if I entered construction by right-clicking a booster piece, it would display the wrong speed. It seems that the stringId does not always get set.

This version always seems to work.

**Comment by rwjuk** [comment]
Hmm, interesting. Noted for future reference though!

**Comment by Gymnasiast** [comment]
Well, the Giga Coaster now works spot on!

But it looked as if the Junior Roller Coaster might need its speed halved. Could you create a junior RC in RCTC, set its booster to something and then test it in OpenRCT2?

**Comment by rwjuk** [comment]
Doing it now.

**Comment by rwjuk** [comment]
Yup, needs halving. I'll make the change (sorry - somehow forgot to test the Junior RC before - I keep forgetting that one has boosters now).

**Pull request merged**
