### PR TITLE
Fix #5077 - Giga Coaster design name display wrong

### LINKED ISSUE #5077: Giga Coaster design name display wrong
**OS:** Arch Linux
**Version:** 0.0.6
**Commit/Build:** 307745dd868ddad49dc4d03443870511b89e78c0

When building a Giga Coaster, the name of a prebuilt coaster is displayed as "Goliath.1" instead of as "Goliath". I'm pretty sure this was correct once.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Open a park with the Giga Coaster available (like Wacky Worlds ⇒ North America - Rollercoaster Heaven)
2. Build a new Giga Coaster

**Screenshots / Video:**
design_name

### PR DESCRIPTION
**Pull request by luisfrdr**
I followed the conversation on issue [#5077](https://github.com/OpenRCT2/OpenRCT2/issues/5077) where [Gymnasiast](https://github.com/Gymnasiast) mentioned how RCT2 ignores everything after the first period and the same behavior should be replicated.

Assuming the intention was to maintain the addition to the warning log that no extension was found, I added a while-loop inside the original if-statement that kept checking for the last '.' character in the string until it couldn't find any more, and for every '.' found, the character on the original string is replaced by a null character to effectively remove it from the string passed in.

Tested it on another machine and it worked as expected.

### CODE REVIEW

**Comment by rwjuk** [comment]
This doesn't actually fix #5077 - it does give the 'ignore everything after the first period' behaviour to save game path handling, but not track names.

You'd need to edit GetPathNameWithoutExtension in openrct2/core/Path.cpp for that.

**Comment by Gymnasiast** [comment]
@luisfrdr @rwjuk Only track design naming should be changed. Currently, both @luisfrdr 's and @rwjuk 's versions affect everything.

**Comment by luisfrdr** [comment]
I'm currently looking for what is the best solution for this problem by looking at the impact set of both functions @rwjuk and I have proposed. I'll come back soon (later today, probably) with a new proposed solution.

**Comment by luisfrdr** [comment]
I'll make a new branch to have a clean commit.

**Pull request closed without merging**
