### PR TITLE
Add Mine Train RC flat-to-steep pieces

### PR DESCRIPTION
**Pull request by mixiate**
This adds flat-to-steep pieces to the Mine Train Coaster.

final

### CODE REVIEW

**Comment by SpartanFrederic104** [comment]
Fred's Workbench 2024-09-22 20-46-04
Fred's Workbench 2024-09-22 20-46-12
Works beautifully. No glitching so far.

Only issue here, and a very minor one at that, is that if you do a downward steep-to-flat piece immediately followed by an upward flat-to-steep piece, there is a little gap in the rails and crossties between the two steep-to-flat pieces. It's more noticeable when the pieces are in a certain direction (shown in the first screenshot).

Other than that, the new flat-to-steep pieces for the Mine Train Coaster look great!

**Comment by astraylife1** [comment]
I’m the first screenshot, it appears that there is a kink in the transition from the flat to steep to the steep to gentle slope piece.

**Comment by mixiate** [comment]
Thanks for trying it out. I've updated it and hopefully i've fixed all the remaining issues with this.

**Comment by Gymnasiast** [comment]
Are you able to add import fixing code as well? It will work the same as the code I added to your previous PR. If not, I’ll push the required bits to your branch.

**Comment by Gymnasiast** [comment]
That may cause problems with parks saved between the addition of the wooden pieces and this one. Though as there hasn’t been a release and the expected fallout is exceedingly low with the Mine Train, I will consider it.

I’ll add the bits if my testing does not reveal any glitches or stuff like that.

**Review by Gymnasiast — APPROVED** [review]

**Pull request merged**
