### PR TITLE
Place tree underwater tooltip bug

### PR DESCRIPTION
**Pull request by joshtucker132**
Removed code incorrectly increasing `gSceneryPlaceZ` and added comment for clarification.

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
The commit message really needs adjusting to reference the issue that this closes. If you are struggling with git I'll just fix it during merging.

**Comment by joshtucker132** [comment]
Is it possible to edit the commit message without redoing the commit?

**Comment by IntelOrca** [comment]
@joshtucker132 yep, from the command line you can do `git --amend -m "new message"` or leave out the `-m` to launch your default editor.

**Comment by AaronVanGeffen** [comment]
Note that you'll have to force-push your branch once after changing a commit that's already been pushed.

**Pull request merged**
