### PR TITLE
refactor entrance hut finding function

### PR DESCRIPTION
**Pull request by spacek531**
https://github.com/OpenRCT2/OpenRCT2/pull/15327

### CODE REVIEW

**Comment by spacek531** [comment]
You may notice a lot of console spam relating to removing entrance huts. This is not a regression.

**Review by duncanspumpkin — APPROVED** [review]
Code looks good. Have you tested this?

**Comment by spacek531** [comment]
Everything seems to work as normal

**Comment by Broxzier** [comment]
This seems to have caused #15375.

**Pull request merged**
