### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by mrtnptrs** [comment]
Do these fixes also fix some open bug reports? Then we can close them after this gets merged :)

**Comment by gDanix** [comment]
@mrtnptrs This can be achieved by a [specially formatted commit message](https://help.github.com/articles/closing-issues-via-commit-messages/). However, I haven't do this before, and don't know if the title of the PR currently being merged is enough to auto-close issues.

**Comment by ThePsionic** [comment]
You can also put the same text in the OP of the PR, and it would work the same way. If @janisozaur puts things like "fixes #x, fixes #y" etc. in his post then GitHub would also auto-close.

**Comment by AaronVanGeffen** [comment]
As he's pointed this out to people in the past, I'm quite sure he's aware. @janisozaur has been preventively hardening the code through PRs recently; this is probably one such a PR.

**Pull request merged**
