### PR TITLE
fixed lang name, added czech currency

### PR DESCRIPTION
**Pull request by Killermannvs**
fixed lang name, added czech currency

### CODE REVIEW

**Comment by Gymnasiast** [comment]
There is a good reason I didn't use the localised Czech names and actual Czech crown symbol: they don't work with the bitmap font that most languages use, and will therefore break those.

**Comment by IntelOrca** [comment]
Like with #2262, the currency definition structure needs to be improved so that there is an additional ASCII fallback field (in case the sprite font or TTF font doesn't support it).

**Comment by Killermannvs** [comment]
I see but I use czech language in-game and it does work well.

**Comment by Gymnasiast** [comment]
That's not the point. The point is that it's broken when the game is set to languages that use the bitmaps font, like English.

**Comment by IntelOrca** [comment]
@Killermannvs currency is not tied to a language, so we need the currency to show in an acceptable manor for every language.

**Comment by Killermannvs** [comment]
Yeah, I know and I expected your answers, unfortunately I'm not C guy so probably I can't help with larger coding, but I can help you with sprite drawing of czech glyphs, for example? Or do you have another idea? I don't like how ARIAL font looks in-game, that "bold" sprites are better.

**Comment by IntelOrca** [comment]
This is now implemented.

**Pull request closed without merging**
