### PR TITLE
Prevent space from being classed as a valid name for an object.

### LINKED ISSUE #1533: Fallback language system for .DAT files
Anyone with a sizeable collection of custom .DAT files will probably have a few where the author only put a description in the fields for his/her own language, leaving all the others blank.
It would be nice if OpenRCT2 could try other translations if it can't find one in the user's language (falling back to UK English, US English and then all other languages, for example).

If someone needs an offending file, I have one (which has only US English filled in).

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Not sure if anyone can think of a better way to handle this.

Fixes #1533

### CODE REVIEW

**Comment by IntelOrca** [comment]
Perhaps it would be better to trim the string and then check length. We the assume whitespace is the same as undefined.

**Comment by duncanspumpkin** [comment]
I don't think trim would be a good idea. I expect control characters would be stripped if you did that.

**Comment by IntelOrca** [comment]
Just trim spaces, no other character.

**Comment by IntelOrca** [comment]
I have copied this to my utf8 branch, so I will close this now.

**Pull request closed without merging**
