### PR TITLE
[WIP] Leverage `constexpr` for compile-time evaluation and improved performance

### PR DESCRIPTION
**Pull request by tomlankhorst**
I've run `callgrind` on `develop` and listed the called methods from most frequently called to least. 
Much time is spent on getter methods of tiles, so I started there. 

These are some early experiments that I wanted to run on CI ;).

### CODE REVIEW

**Comment by ZehMatt** [comment]
I think half of the things marked constexpr will never be compile time since it has to still read dynamic memory in most cases. While there is no downside given that you still get a runtime version if it can't be evaluated compile time I'm not sure its actually worth doing it.

**Comment by ZehMatt** [comment]
I think the only thing you could benefit from is inline optimizations which you managed by moving all the getters/setters into the header which is good, been meaning to do that for a while, so you could perhaps still go on and focus less on constexpr as you probably won't be that lucky with those, but as for interlining methods, go for it.

**Comment by janisozaur** [comment]
I'm not in favour of that. This is LTO's job, not developer's.

**Comment by ZehMatt** [comment]
> I'm not in favour of that. This is LTO's job, not developer's.

Sorry but I strongly disagree here. Its the typical "Leave it to the optimization pass" which usually brings bad code out there only because there is too much hope in it. Also LTO is not a standard thing either, optimization is usually per compilation unit, whole program optimization only works if you have LTCG. 

I mean strictly speaking why even bother introducing inline keyword or have it inlined if implemented in a header if you could always leave that to the optimizer?

**Comment by tomlankhorst** [comment]
With some _back of the envelope_ calculations, Valgrind showed that putting the simple getters in headers and mark them implicitly as `inline` through `constexpr` results in each game `update` call requiring about 10% fewer CPU cycles when building `RelWithDebInfo` on GCC. Sure, this metric is hardly trustworthy due to between-run differences in the state but I think there's still quite a bit to gain here.

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/pull/8458 adds benchmark (read: both the library and code using it). We already have `simulate` command via https://github.com/OpenRCT2/OpenRCT2/pull/8321 it sounds like another benchmark is needed.

**Pull request closed without merging**
