### PR TITLE
Implement SmallSceneryObject for getObject plugin API

### PR DESCRIPTION
**Pull request by IntelOrca**
```
openrct2 $ context.getObject("small_scenery", 0)
{ flags: 268435457,
  height: 80,
  price: 18,
  removalPrice: 10,
  type: 'small_scenery',
  index: 0,
  identifier: 'TAP     ',
  name: 'Aleppo Pine Tree' }
```

### CODE REVIEW

**Comment by Gymnasiast** [comment]
This uses the old .DAT identifier, even for JSON objects. It would be preferable to use our own (JSON) identifier here, I think.

**Comment by IntelOrca** [comment]
What about custom objects?

**Comment by Gymnasiast** [comment]
Not sure. Perhaps they should be `custom.<OLDDATIDENTIER>`. Or perhaps we should specify both identifiers, where current JSON objects fill both fields, old .DAT objects fill only the old one and new JSON objects that don't have a .DAT header only fill the new one.

Or perhaps we should just use the JSON identifier, falling back to the .DAT identifier if it isn't a JSON object.

**Comment by IntelOrca** [comment]
Okay, will add `legacyIdentifier` and `identifier` in another PR.

**Pull request merged**
