### PR TITLE
Advertise without any ride

### PR DESCRIPTION
**Pull request by MaikelS11**
Advertisements gives a empty dropdown box in the marketing window. This commit prevents displaying a dropdown box. #1510

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Is all this code necessary? It must iterate over something already currently?

**Comment by MaikelS11** [comment]
There is only a method that gives the number of all available 'rides' (rides, shop, toilets)
In new_camaign.c is something like this iteration used inside of the mousedown method, but not declared as seperated methodes. It will be possible to refactor the new_campaign file, but is that something you wanna do right now or at a later phase? (When all the code of RCT is converted)

**Comment by IntelOrca** [comment]
@MaikelS11 Always refactor, I regularly do it after after implementing code or when I wish to take a break. It will make it easier when we are able to start our 0.1 refactor.

**Comment by MaikelS11** [comment]
Ok. I changed some code.. 
- Fixed some small bugs (Shop items & Rides are now responding the same way on (de)selecting the dropdown box)
- Removed my previous created method.
- Split up some methodes 
- And other things..

I hope it's better now! :)

**Comment by IntelOrca** [comment]
Could you rebase this?

**Pull request closed without merging**
