### PR TITLE
Use `git describe` to express version in terms of closest tag

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
As of v0.2.0, we have changed the way we assign a version number to OpenRCT2. Instead of incrementing the version number directly after a release, we will now change it directly *before* a release. This PR introduces the use of `git describe` to express the version number in terms of the last tag by appending the number of commits since the release was tagged.

Before:
screenshot_20180612_002433

After:
screenshot_20180612_002349

The provider notice (e.g. "provided by AppVeyor") will still be appended as before.

I decided to leave the branch information in, as it may be useful for PRs that take longer to develop (e.g. objects branch, plugin system). Perhaps we should drop the detailed information for release versions (i.e. master branch), however. Thoughts?

Note: the Visual Studio and Xcode projects still need to be changed accordingly.

### CODE REVIEW

**Comment by IntelOrca** [comment]
Branch shouldn't be specified for releases, I think this works for AppVeyor on tagged builds.

**Comment by IntelOrca** [comment]
```
PS openrct2 .\openrct2 --version
OpenRCT2, v0.2.0-63 (b1e8b90 on develop) provided by AppVeyor
Windows (x86-64)
```

**Comment by AaronVanGeffen** [comment]
Thanks, I try and get Xcode sorted soon, too.

**Comment by AaronVanGeffen** [comment]
Now hiding branch info on tagged releases on `master`, too. Tested as follows:
```
aaron@izumo ~/Repositories/OpenRCT2/build (git_describe_version) $ ./openrct2 --version
OpenRCT2, v0.2.0-39 (fd74c6c9 on git_describe_version, DEBUG)
Linux (x86-64)
aaron@izumo ~/Repositories/OpenRCT2/build (git_describe_version) $ git checkout -B master
Switched to and reset branch 'master'
Your branch is ahead of 'upstream/master' by 39 commits.
  (use "git push" to publish your local commits)
aaron@izumo ~/Repositories/OpenRCT2/build (master) $ git tag -a 'test'
aaron@izumo ~/Repositories/OpenRCT2/build (master) $ cmake .. && ninja
[...]
aaron@izumo ~/Repositories/OpenRCT2/build (master) $ ./openrct2 --version
OpenRCT2, test (fd74c6c93, DEBUG)
```

**Pull request merged**
