### PR TITLE
warn user if unsupported vehicle or element used

### PR DESCRIPTION
**Pull request by spacek531**
This will allow OpenRCT2 to merge new track elements.

image

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
Could you add a note stating that this should be removed in the new track design format.

**Comment by spacek531** [comment]
Done.

**Review by duncanspumpkin — APPROVED** [review]

**Comment by Gymnasiast** [comment]
@tupaschoal that’s the wrong milestone, v0.4.1 has already been released. ;-)

**Comment by tupaschoal** [comment]
Whoops

**Pull request merged**
