### PR TITLE
Add medium and large half loops to the Wooden Roller Coaster 

### PR DESCRIPTION
**Pull request by mixiate**
This adds medium and large half loops to the normal and classic wooden roller coaster.

woodenrollercoastermediumandlargehalfloops

I made both of them available normally to both types of wooden roller coaster as the small loop is already available and the larger loops are probably more "realistic", but i'm happy to go with whatever your decision is on that.

All pieces have been tested with the RCT 1 and 2 trains, the six seat trains and the articulated trains. There is some minor glitching in one section of one angle but this is present on all larger loops. I think that the train bounding boxes are too small and I can't find a workaround.

I bumped the park version to the same number as I did with the corkscrew pieces in order to make the existing pieces invisible, so you may need/want to change that eventually.

### CODE REVIEW

**Comment by SpartanFrederic104** [comment]
Tested these just now. Once again, these new bigger loops are fantastic (minor glitching from the trains aside) and especially useful for taller, faster designs. Couple these with the large steep pieces and I can now make even taller wooden coasters without needing to be so worried about the intensity overshooting 9.99 intensity due to strong vertical Gs, especially from vertical loops. Nice work as always.
Fred's Workbench 2024-10-11 23-12-37
Fred's Workbench 2024-10-11 23-13-35

**Comment by Gymnasiast** [comment]
Code looks good, could you rebase?

**Comment by mixiate** [comment]
I've rebased this.

**Review by Gymnasiast — APPROVED** [review]

**Comment by duncanspumpkin** [comment]
This should have bumped the network version.

**Pull request merged**
