### PR TITLE
Name RIDE_TYPE_FLAG_21

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by IntelOrca** [comment]
Does this flag work for shops?

**Comment by Gymnasiast** [comment]
As I says in the comment, this flag is used to mark that the guest should go _inside_ the building, rather than 'buying' at the counter (like food/drink/souvenir stalls), and is used by toilets and first aid rooms.

**Comment by IntelOrca** [comment]
@Gymnasiast Sure, but if you were to turn this flag on for the burger stall, would people buy burgers by going inside the building?

**Comment by Gymnasiast** [comment]
Very likely, yes. If you look at the code in peep.c you'll see that guests walk into the centre of the tile if the flag is set.

**Comment by Gymnasiast** [comment]
scr52

This is what happens when you set the flag on a shop. They treat it more a less like a toilet or first aid room.

**Comment by IntelOrca** [comment]
Cool, it just means that flag behaviour isn't specific to facilities (even though those are the only things that use the flag). So perhaps the flag shouldn't have facility in the name.

**Comment by Gymnasiast** [comment]
I have to say they use it _as_ a toilet though.
Personally I prefer this name. But if you want another, do you have suggestion?

**Pull request merged**
