### PR TITLE
Resources compression

### PR DESCRIPTION
**Pull request by ppamorim**
This PR applies a bunch of non lossy compression to the sprites inside the `/resources` folder. The script applied is based on the `oxipng` inside the `ImageOptim` application (By running `oxipng` standalone didn't compress much more, less than 10 bytes of difference). With this setup I was able to reduce the folder from 3073kb to 1708kb:

Screenshot 2020-10-11 at 12 46 38

You should not be able to see any difference between the old sprites and the new ones because the compression applied is not lossy.

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Are you sure there aren't any differences? Given #13147

I am not sure it's worth compressing these images at this stage. It's worth doing when a PR hasn't been merged yet, but at this point, the objects are already in the repository. Worse yet, recompressing would just increasing the repo size further, as new objects are needed for the recompressed objects.

**Comment by ppamorim** [comment]
@AaronVanGeffen The sprites are using 8-bit colormap. I think there is a way to replace these files in older commits.

**Comment by AaronVanGeffen** [comment]
Yes, but force pushing is not an option for our repository. All commit hashes would change, which is quite destructive for historical cross-references.

**Comment by X123M3-256** [comment]
@AaronVanGeffen It wouldn't decrease the repo size but it would decrease the download size, no? I think most users aren't building from source.

**Comment by AaronVanGeffen** [comment]
@X123M3-256 It wouldn't matter for download size, as the PNGs are RLE compressed instead (iirc) when processed into `g2.dat`.

**Comment by X123M3-256** [comment]
@AaronVanGeffen Oh yeah, they are. I am an idiot.

**Comment by Gymnasiast** [comment]
Given that this:
- Increases the repo size
- Does not reduce the download size\*

I won't merge it.

But I do think it does provide good insight on the different PNG optimisers, and it will be useful when deciding on which optimiser to use when the next PR that adds PNGs comes around. Last time, we tried `optipng` and `zopflipng` - the latter compressed better, but in a way that was incompatible with our PNG handling code. Next time, we can also compare `oxipng`, as it appears to compress better than optipng while still being compatible with our PNG handling code.

**Comment by Gymnasiast** [comment]
I have used `oxipng` on https://github.com/OpenRCT2/objects/pull/135 . It reduced the size of the images from 3.5 MB to 1.1 MB. (Small caveat: I have not yet tested if they get imported correctly.)

**Pull request closed without merging**
