### PR TITLE
Add missing braces

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by Gymnasiast** [comment]
```
/home/travis/build/OpenRCT2/OpenRCT2/src/platform/windows.c:306:1: error: missing braces around initializer [-Werror=missing-braces]

 static enumerate_file_info _enumerateFileInfoList[8] = { 0 };

 ^

/home/travis/build/OpenRCT2/OpenRCT2/src/platform/windows.c:306:1: error: (near initialization for ‘_enumerateFileInfoList[0]’) [-Werror=missing-braces]

cc1: all warnings being treated as errors
```

**Comment by janisozaur** [comment]
You must have taken old version, I fixed it in  	446fa78

**Comment by marijnvdwerf** [comment]
My main gripe with this is the mess it makes of `rct_xy8`s. A quick search shows that the `xy` property is mostly used for comparisons. Can't we add a helper function for that use case and get rid of the union/nested struct?

**Comment by duncanspumpkin** [comment]
My main gripe with this is it adds unnecessary braces. Are there any actual examples where this has fixed a bug or made it easier to understand? All I see is just extra braces for the sake of it.

**Comment by marijnvdwerf** [comment]
@duncanspumpkin I think `RiverRaftsLeftQuarterTurn5_Top` does make more sense with the other braces, but otherwise I agree with you. 

Though Clion also gives warnings on the options table, so it might make sense there?
image

**Comment by IntelOrca** [comment]
I think the main issue is unions. We use unions a lot for convenience and the braces are removing that convenience.

**Comment by janisozaur** [comment]
Is this rejected then?

**Comment by IntelOrca** [comment]
I think it might better to wait until we move to C++ where the number of missing braces will go down.

**Pull request closed without merging**
