### PR TITLE
Chat window based on work by Wirlie and Pizza2004

### PR DESCRIPTION
**Pull request by delebota**
This should be a working version of the chat window that Wirlie and Pizza2004 worked on a few months ago. This is pretty much a copy and paste of the code with a little bit of organizing, let me know if there are mistakes that should be fixed.

For those wondering what it changes, it adds a grey opaque background when chat is open and breaks long messages into multiple lines.

### CODE REVIEW

**Comment by pizza2004** [comment]
I actually still have an open pull request, and I don't believe it's considered good etiquette to just copy somebody else's code.  I'll gladly remove the last couple of commits that attempted to make it into a full on window and then rebase and fix any merge issues if it would be liked.

**Comment by IntelOrca** [comment]
> I actually still have an open pull request, and I don't believe it's considered good etiquette to just copy somebody else's code.

He credited you, why is that bad etiquette?

**Comment by pizza2004** [comment]
@IntelOrca I wasn't sure, I was just saying I think you're not supposed to just copy code over like that.  I actually didn't end up making any changes myself, since I couldn't really make any sense of what was happening in the windowing code for the game.  I figure I might need to wait until everything is reversed and some of the code is rebuilt to be easier to understand.

**Comment by delebota** [comment]
Sorry, I was already working on it before I saw your message earlier that it was still open Pizza2004. Whatever is easier for you guys, just a feature I wanted to get in and it looked to be abandoned.

**Comment by pizza2004** [comment]
It's fine, I'd partly forgotten about it, but mostly I just didn't know how to proceed and I wanted to have the jump to it being a full on window at the same time.  Anyway, I cleaned up my original pull request and rebased so it's ready to be merged.

**Pull request closed without merging**
