### PR TITLE
Add more object source filters

### PR DESCRIPTION
**Pull request by Gymnasiast**
This adds filters for RCT1, AA, LL and official OpenRCT2 objects.
Currently, it uses hard coded lists, but these can be moved to the `objects` tool and json-objects.

Implements #2893.
I hope I got all RCT1 assignments right. I think @Horsti12 might be able to confirm it.

### CODE REVIEW

**Comment by Horsti12** [comment]
Where can I find the list?

**Comment by AaronVanGeffen** [comment]
@Horsti12 In this PR. They list has been added to `src/openrct2/object/Object.cpp`

**Comment by Gymnasiast** [comment]
Or just try it running it.

**Comment by IntelOrca** [comment]
Can you move the arrays to inside the functions that use them and have those functions at the bottom of the file?

**Comment by Gymnasiast** [comment]
@IntelOrca Done.

**Comment by Horsti12** [comment]
Thanks for the merge.
I'm a little bit busy, but I already checked the following things:

Rides list:
Transport Rides: ✔
Gentle Rides: ✔
Roller Coasters: x
Thrill Rides: ✔
Water Rides: ✔
Shop and Stalls:  Iced Tea Stall (ICETST.DAT) was added in RCT2, not RCT1

I will check the rest in the next few days.

**Comment by Gymnasiast** [comment]
Pushed a fix for the Iced Tea Stall. (I know it's not in RCT1, by the way, but I created the list from a list of RCT2 objects and simply deleting everything that wasn't in RCT1.)

**Comment by Horsti12** [comment]
btw what about another filter for the Offical stuff for the game by chris sawyer (panda trains, panda themeing)

**Comment by Gymnasiast** [comment]
There are so few of those, that stuff has also been put under 'OpenRCT2 official'.

**Comment by Horsti12** [comment]
Another check:
Paths ✔
Park Entrance ✔
Water✔

**Pull request merged**
