### PR TITLE
[WIP] Defined flag as enum replacing hard coded hexadecimal value (#5173)

### PR DESCRIPTION
**Pull request by rlewicki**
Replaced hard coded hexadecimal flag that was used to determine the rotation based on curvation of placed track.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
`& 3` and `% 4` are just used to make sure one of the four orthogonal directions (N, E, S, W) are taken and are used a lot throughout the codebase. I'm sure there is already a constant defined somewhere.

**Comment by IntelOrca** [comment]
Ultimately there should be a `FixRotation(...)` constexpr function.

**Comment by Gymnasiast** [comment]
If you think that is better, wouldn't it be better to do that immediately?

**Comment by IntelOrca** [comment]
Sure, I am not sure what depth this PR is going, currently it just tackles one single file.

**Comment by Gymnasiast** [comment]
Well, adding a function and replacing the occurrences in this PR should not be difficult, and I can take it over if needed.

How should the constexpr look?

**Comment by IntelOrca** [comment]
`constexpr int8_t FixRotation(uint8_t x)`

**Comment by Broxzier** [comment]
I already prepared a class like that like 8 months ago: https://gist.github.com/Broxzier/3d986be6117e03dd6298cb4affdf707a

**Comment by Gymnasiast** [comment]
@Broxzier So shall we close this one and have you prepare your class for merging?

**Comment by Broxzier** [comment]
Sure, I'll try to. Using it everywhere is a big task, however.

This PR does clean up some hardcoded numbers and could be merged beforehand. I cannot find a fitting define for this purpose either (like your first comment).

**Pull request closed without merging**
