### PR TITLE
Add cheat to force park rating

### PR DESCRIPTION
**Pull request by ThomasdenH**
Add a spinner to force the park rating to be at a certain value to the cheats. I think all the cheats from #436 are implemented now!

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Yeah, pretty much. The idea behind auto-purchasing (speed) has been implemented more precise with the land rights tool. I'd say #436 could be closed.

**Comment by ThomasdenH** [comment]
I was thinking the same. If anything the possibilities are greater now.

**Comment by IntelOrca** [comment]
This currently has a merge conflict.

**Comment by duncanspumpkin** [comment]
It will be because of the string 5442 I asked @trigger-death to leave it free for this PR and it is marked now as reserved but this will need a rebase to stop the merge conflict.

**Comment by duncanspumpkin** [comment]
Can you also change `int forcedParkRating` to  `gCheatsForcedParkRating`. I think  `set_forced_park_rating(int rating)` should also invalidate the park window since that has the park rating.

**Pull request closed without merging**
