### PR TITLE
Changed Icon for openrct2.exe to OpenRCT2 Logo

### PR DESCRIPTION
**Pull request by LRFLEW**
This required a lot of work to get working.

### CODE REVIEW

**Comment by janisozaur** [comment]
While I agree this would be nice addition, is it really still worth it when we're nearing self-hosted builds? I mean this would add around 7MiB to the repository size.

**Comment by LRFLEW** [comment]
I mean, it's not my call whether or not this gets merged. Personally, I don't think 7MiB of change is a huge one, but because the file is **very** similar to the old one, git should be able to store it as a diff, drastically decreasing the commit size (so adding only about the 57 KiB size of the source ico file).

**Comment by AaronVanGeffen** [comment]
>  git should be able to store it as a diff,

Sadly, it won't, because it's a binary file.

**Comment by IntelOrca** [comment]
I worried about this to, but I think its okay because when we drop it altogether, we can use https://rtyley.github.io/bfg-repo-cleaner/ to remove it from the history to reduce repository size.

**Comment by janisozaur** [comment]
I'd rather avoid using BFG. It's unfortunate we have this binary now, but it's very low traffic (only 2 or 3 changes over entire history so far) and we can live with that, while BFG would invalidate all our past commit hashes, and thus invalidating much of information gathered across the reported issues.

A middle ground solution would be extracting .exe to dependencies repo.

**Comment by IntelOrca** [comment]
@janisozaur and everything else? like the title sequence? the graphics?

**Comment by janisozaur** [comment]
Graphics (so far) are very low traffic and very small, but for title sequences we've had https://github.com/OpenRCT2/OpenRCT2/issues/2408 for a while now.

**Comment by IntelOrca** [comment]
@LRFLEW DSOUND should be removed.

What I will do for this is upload it somewhere and make the install script download it which will replace current one. Should be good enough for CI.

**Comment by LRFLEW** [comment]
@IntelOrca Done. If you want me to remove any other imports, let me know.

About having the install script download it, I'm not sure that's a good idea. The exe is needed for all builds (Linux and OS X extracts the data from the exe), so that would mean that either both of those systems would need to be updated to grab the exe, or you would need to leave the old exe in the repository (why should we be distributing two versions of the exe?).

**Comment by IntelOrca** [comment]
@LRFLEW it doesn't matter for MacOS or Linux as they don't have the icon problem. But for Windows, the CI could replace the exe that is currently in the repo as part of its install script. I can't think of another way to do this otherwise without increasing the repository size permanently.

**Comment by janisozaur** [comment]
I like that plan. Replace the exe only for windows and leave other builds untouched.

**Comment by LRFLEW** [comment]
To clarify, the modified exe here should not be a problem if used for Linux and macOS builds. The modified code is almost entirely outside of the .text, .rdata, and .data sections that their build scripts read from (the only change there is a change in the pointer in WinMain).

As for the install script solution, I'm not a fan, but if that's what y'all want to do, then fine by me. It's not like the exe file will be used for that much longer.

**Comment by IntelOrca** [comment]
@LRFLEW what else are you suggesting?

**Comment by LRFLEW** [comment]
I guess I just don't see the problem with just merging it. It's not like this will make a major impact on the repository size (given all the other stuff in there). But again, it's not my call to make, so just do whatever you think is best.

**Comment by Nubbie** [comment]
Fixes #1168

**Comment by Gymnasiast** [comment]
Since the discussion got stuck and there has to be taken *a* decision, I figured I take it.

Since we're relatively close to full implementation, and because the problem at hand is more a papercut than a bug, I think it would be better to do this once the implementation is finished. At that point we have to replace the .exe anyway.

**Pull request closed without merging**
