### PR TITLE
Store the rotation in viewports

### LINKED ISSUE #910: Extra viewport does not preserve center on map rotate.
Extra viewport does not preserve its center on map rotate.
Probably original bug.

### LINKED ISSUE #21422: Store the rotation in viewports
A lot of code currently relies on `gCurrentRotation` which doesn't allow multiple viewports with their own rotation, instead of having a single global variable all viewports should store the rotation and pass it down to when it comes to rendering the viewport.

### PR DESCRIPTION
**Pull request by ZehMatt**
Now everything seems to be working, fixes the extra viewport and adds a button which allows for independent rotations. This PR also now allows plugins to have more control over the viewport rotation.

openrct2_2024-03-02_11-23-41

Closes #910, Closes #21422

### CODE REVIEW

**Comment by Gymnasiast** [comment]
What is the status of this?

**Comment by ZehMatt** [comment]
> What is the status of this?

It's mostly functional but there are some issues with changing the rotation on the primary viewport not syncing all the other viewports, ideally each window could rotate the viewport and always starts out with using the rotation of the primary viewport. So more work needs to be done, maybe someone could take it over as I'm also a bit busy with working on my main income projects.

**Review by janisozaur — APPROVED** [review]

**Review by Gymnasiast — APPROVED** [review]
Seems to work correctly.

@Basssiiie expressed an interest in testing the plug-in part, so deferring that to him.

**Comment by Basssiiie** [comment]
In busy parks I'm getting the following warning in stdout now:
> WARNING[D:\a\OpenRCT2\OpenRCT2\src\openrct2\entity\EntityRegistry.cpp:439 (EntitySpatialRemove)]: Bad sprite spatial index. Rebuilding the spatial index...

**Comment by Basssiiie** [comment]
Getting another error in stdout when having the Extra Viewport open and then loading another scenario or save file:

> ERROR[D:\a\OpenRCT2\OpenRCT2\src\openrct2\interface\Viewport.cpp:2157 (GetCurrentRotation)]: No viewport found! Will return 0.

Other than that it seems to work perfect for plugins. Can't find any further issues! 😄 

image

<details>
  <summary>Plugin code for reference</summary>

```js
/// <reference path="../bin/openrct2.d.ts" />
// @ts-check

registerPlugin({
	name: "Test for viewport rotation",
	version: "1",
	authors: ['Basssiiie'],
	targetApiVersion: 82,
	type: "local",
	licence: "MIT",
	main() {
		ui.registerMenuItem("Test viewport rotation", function() {
			var min = 200, max = 1000;
			function layout(width, height, view, world, lock, rotation, zoom, target) {
				view.x = 5;
				view.y = 20,
				view.width = width - 10;
				view.height = height - (20 + 120 + 5);
				world.x = 5;
				world.y = height - 100;
				world.width = width - 10;
				world.height = 15;
				lock.x = 5;
				lock.y = height - 80;
				lock.width = width - 10;
				lock.height = 15;
				rotation.x = 5;
				rotation.y = height - 60 ;
				rotation.width = width - 10;
				rotation.height = 15;
				zoom.x = 5;
				zoom.y = height - 40;
				zoom.width = width - 10;
				zoom.height = 15;
				target.x = 5;
				target.y = height - 20;
				target.width = width - 10;
				target.height = 15;
			}
			var viewDesc = {
				type: "viewport",
				name: "vp-view"
			};
			var lockDesc = {
				type: "checkbox",
				name: "vp-lock",
				text: "Lock viewport",
				onChange: function (check) {
					var vp = window.findWidget("vp-view");
					if (check) {
						vp.viewport.visibilityFlags |= (1 << 30);
					}
					else {
						vp.viewport.visibilityFlags &= ~(1 << 30);
					}
				}
			};
			var worldDesc = {
				type: "label",
				name: "vp-world"
			};
			var rotationDesc = {
				type: "dropdown",
				name: "vp-rotation",
				items: [ "0", "1", "2", "3" ],
				onChange: function (idx) {
					var vp = window.findWidget("vp-view");
					vp.viewport.rotation = idx;
				}
			};
			var zoomDesc = {
				type: "dropdown",
				name: "vp-zoom",
				items: [ "-2", "-1", "0", "1", "2", "3" ],
				onChange: function (idx) {
					var vp = window.findWidget("vp-view");
					vp.viewport.zoom = idx - 2;
				}
			};
			var targetDesc = {
				type: "button",
				name: "vp-target",
				text: "Set target",
				onClick: function (idx) {
					ui.activateTool({
						id: "vp-tool",
						onDown: function(args) {
							if (args.mapCoords) {
								var vp = window.findWidget("vp-view");
								vp.viewport.moveTo(args.mapCoords);
							}
							ui.tool.cancel();
						}
					})
				}
			};
			layout(min, min, viewDesc, worldDesc, lockDesc,rotationDesc, zoomDesc, targetDesc);

			var window = ui.openWindow({
				classification: "test-viewport-rotation",
				title: "Viewport rotation",
				width: min,
				height: min,
				minWidth: min,
				minHeight: min,
				maxWidth: max,
				maxHeight: max,
				widgets: [ viewDesc, worldDesc, lockDesc, rotationDesc, zoomDesc, targetDesc ],
				onUpdate: function() {
					var view = window.findWidget("vp-view");
					var world = window.findWidget("vp-world");
					var lock = window.findWidget("vp-lock");
					var rotation = window.findWidget("vp-rotation");
					var zoom = window.findWidget("vp-zoom");
					var target = window.findWidget("vp-target");

					world.text = ("World rotation: " + ui.mainViewport.rotation + ", zoom: " + ui.mainViewport.zoom);
					rotation.selectedIndex = view.viewport.rotation;
					zoom.selectedIndex = view.viewport.zoom + 2;

					layout(window.width, window.height, view, world, lock, rotation, zoom, target);
				}
			})
		})
	}
});
```

</details>

**Comment by Gymnasiast** [comment]
Oh, forgot to say, but we’ll also want a changelog entry for fixing the Extra Viewport, and for extending its functionality.

**Comment by ZehMatt** [comment]
> In busy parks I'm getting the following warning in stdout a lot now when rotating with the Extra Viewport open:
> 
> > WARNING[D:\a\OpenRCT2\OpenRCT2\src\openrct2\entity\EntityRegistry.cpp:439 (EntitySpatialRemove)]: Bad sprite spatial index. Rebuilding the spatial index...
> 
> The latest develop does not seem to have this issue.

I can't reproduce this on my end, I've tried serval bigger parks including the EverythingPark and the typical bpb.

> Getting another error in stdout when having the Extra Viewport open and then loading another scenario or save file:
> 
> > ERROR[D:\a\OpenRCT2\OpenRCT2\src\openrct2\interface\Viewport.cpp:2157 (GetCurrentRotation)]: No viewport found! Will return 0.
> 
> Other than that it seems to work perfect for plugins. Can't find any further issues! 😄
> 
> image
> 
> Plugin code for reference

That error isn't an actual error, the window seems to remain open for a few frames despite no park being loaded, I think its safe to just remove this or at least make it a verbose message.

**Comment by ZehMatt** [comment]
Hm actually I do see the warning show up, I see why this is happening and it's actually pointless to do that.

**Review by Gymnasiast — APPROVED** [review]

**Pull request merged**
