### PR TITLE
Ensure ccache's expected dirs exist

### PR DESCRIPTION
**Pull request by janisozaur**
This should address the intermittent issue where builds fail because of missing this file.

### CODE REVIEW

**Comment by janisozaur** [comment]
Hmm, maybe it would be better to set `OPENRCT2_USE_CCACHE` to off instead.

**Comment by AaronVanGeffen** [comment]
> Hmm, maybe it would be better to set `OPENRCT2_USE_CCACHE` to off instead.

Probably, yes. I don't think we have any persistent ccache storage on GitHub Actions.

**Review by tupaschoal — APPROVED** [review]
I wouldn't expect ccache to work on GH actions at all (it doesn't make sense, so I think we're really better off with disabling it)

**Comment by janisozaur** [comment]
Why not? It's perfectly sound expectation and we used it with Travis to great results.

**Comment by tupaschoal** [comment]
Presumably GitHub would have to be storing the cache somewhere, which I haven't seen yet.

I have tried porting a cached ruby setup from Travis to ghactions and there was no way, so I'm just assuming it isn't there (yet?)

**Comment by janisozaur** [comment]
Oh it's just a matter of using https://github.com/actions/cache and configuring the restore keys and paths correctly.

**Comment by janisozaur** [comment]
There's also https://cristianadam.eu/20200113/speeding-up-c-plus-plus-github-actions-using-ccache/ to be used for reference

**Comment by tupaschoal** [comment]
Nice! I don't think it greatly benefit us all, as we have other setups that don't accept `ccache`, so it would just speed up a few.
But if you think it's worth trying and implementing it, maybe we can open an issue for the community to tackle, what do you say?

**Comment by janisozaur** [comment]
Oh yes, you should always use ccache, I find it hard to think of scenario that wouldn't benefit from it.

Especially in CI, where most builds are incremental. Cf. https://github.com/scummvm/scummvm/pull/2243 or https://github.com/RPCS3/rpcs3/pull/2448 for some stats

**Pull request merged**
