### PR TITLE
Re-dump glassy_recolourable.png for libpng12 compatibility

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
This re-dumps the `glassy_recolourable.png` g2 asset in the hope of addressing problems with libpng12 compatibility, as previously reported in #7075.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Why did you add `quarter_turn_3_tiles_sw_se_part_3.png` as well?

**Comment by AaronVanGeffen** [comment]
Because it's the next file libpng12 chokes on — have a look at Travis' build logs.

Just using the unoptimised equivalent doesn't seem to have done it though, unfortunately. And when I do optimise it, I get a binary identical file… Perhaps I should be looking at the previous or next file in the log instead…

**Comment by Gymnasiast** [comment]
No, it does not choke on `quarter_turn_3_tiles_sw_se_part_3.png`.

```
Added: /home/travis/build/OpenRCT2/OpenRCT2/reImage is not palletted, it has bit depth of 4
Could not import image file: /home/travis/build/OpenRCT2/OpenRCT2/resources/g2/surface/glassy_recolourable.png
Canceling
sources/g2/track/railway/quarter_turn_3_tiles_sw_se_part_3.png
```
Basically, it says "Added: /home/travis/build/OpenRCT2/OpenRCT2/resources/g2/track/railway/quarter_turn_3_tiles_sw_se_part_3.png", but halfway through, the message is split to report
```
Image is not palletted, it has bit depth of 4
Could not import image file: /home/travis/build/OpenRCT2/OpenRCT2/resources/g2/surface/glassy_recolourable.png
Canceling
```
This error only lies with `glassy_recolourable.png`. `quarter_turn_3_tiles_sw_se_part_3.png` is not affected.

**Comment by AaronVanGeffen** [comment]
Ah, cheers. I was looking at a different build log — it seems only the first build over at Travis has the error you're quoting.

I'll try a few more configurations, but it seems this approach isn't working. Other ideas are most welcome.

**Pull request merged**
