### PR TITLE
Add console option to set window scale, fixes #2356

### LINKED ISSUE #2356: "Window scale factor" slider usability
The ability to adjust the DPI of the window is fantastic. I adjust it, usually between 1.00 and 2.00, on a fairly regular basis. But as it is, it's a pain in the ass to adjust when the window moves away from the cursor whenever you click on it. Of course this is inevitable for the way the options window is set up. I have some ideas on how it could be solved.

1. Add a simple console command (set dpiscale x). This might already be in the game but I'm too much of an end-user to know that ;)
2. When adjusting the DPI via the slider, the window moves accordingly, placing itself under the cursor such that the cursor can immediately click again to continue adjust the scale appropriately. This could add the issue of (draggable parts of) the window getting nudged offscreen.
3. Like in Windows, when the slider is focused, pressing arrow keys adjusts the value.
4. Bindable hotkeys for adjusting it.
5. Just add an apply button!

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by IntelOrca** [comment]
Might be worth rounding the value to the nearest 0.01 or something. Otherwise a user might type 0.94, but what gets stored is 0.9999993. I think the config allows 3 decimal places.

**Comment by Gymnasiast** [comment]
How would 0.94 be changed to 0.99999993? Or do you mean 0.9399999?

**Comment by IntelOrca** [comment]
I mean 0.9399999

**Comment by Gymnasiast** [comment]
Well, I just entered `set window_scale 0.94`, which got saved as `0.940`.

**Comment by IntelOrca** [comment]
It will get rounded when it saves, but during that session it might have a very precise fraction.

**Comment by Gymnasiast** [comment]
If this level of accuracy matters, why don't we change the representation to double? With float, it's never precisely 0.94 anyway.

**Comment by IntelOrca** [comment]
It means the value will change when you next load the game... because the config doesn't have the same value as in memory. Thus you need to round to 3dp.

**Comment by Gymnasiast** [comment]
Fine. How would I do that?

**Comment by IntelOrca** [comment]
Divide by 0.01, truncate, multiply by 0.01.

**Comment by janisozaur** [comment]
Don't change to double, these are very expensive.

**Comment by IntelOrca** [comment]
@janisozaur I think now days only expensive in... memory.

**Comment by janisozaur** [comment]
I wouldn't be so sure. The accumulated cost might not be this big for now,
but say if we move to arm it may increase and there really is no point in
having a double here.

On GPU you can have `half`/`float16` not without a reason.

**Comment by IntelOrca** [comment]
@janisozaur yes... anyway we are keeping it as float - and pretty much all the game logic is integer.

**Comment by Gymnasiast** [comment]
Is it okay like this?

**Comment by IntelOrca** [comment]
:+1:

**Comment by janisozaur** [comment]
there should be a limit to how low you can go. `set window_scale 0.1` crashes the game.

**Comment by Gymnasiast** [comment]
There _is_ a limit, and it's 0.1, actually. And it doesn't crash the game on my system.

**Comment by janisozaur** [comment]
Yeah, I see there is a `clamp`, but I vote to raise the lower limit to `0.5`

**Comment by janisozaur** [comment]
See #2460

**Pull request merged**
