### PR TITLE
Refactor window to class: Ride #13795

### PR DESCRIPTION
**Pull request by leoleotte**

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Could you please create a separate PR for the "scroll select" renaming?

**Comment by tupaschoal** [comment]
This has merge conflicts now, please rebase and solve them.

**Comment by Gymnasiast** [comment]
Scroll select changes spun off into https://github.com/OpenRCT2/OpenRCT2/pull/18198.

**Comment by duncanspumpkin** [comment]
Drop WindowRide from all the private functions we already know its part of window ride as its in the ride window class.

**Comment by duncanspumpkin** [comment]
Unfortunately inline comments aren't working. So this will just have to be a series of comments here. Pass rct_drawpixelinfo by reference in all functions that aren't doing a nullptr check on it (thats all of them).

**Comment by duncanspumpkin** [comment]
Remove all of the rct2: address comments. They are no longer required.

**Comment by duncanspumpkin** [comment]
WindowRideDrawTabCustomer needs some ImageId refactoring. Leave a big `TODO: Use ImageId` on it if you don't know how to fix it.

**Comment by duncanspumpkin** [comment]
OnWindowRideOpen should be moved into OnOpen. The other open functions should be moved as much as possible into public member functions that the free functions call. I.e. it creates a window like normal then you call a FocuseOnVehicle, FocusOnRide or some such that changes the page of the opened window.

**Comment by duncanspumpkin** [comment]
You are repeating a lot of code in these open functions. Just expose the SetPage function as a public member and as mentioned add some focusOn functions and they will mostly disapear.

**Comment by duncanspumpkin** [comment]
Replace the `window_event_resize_call` and `window_event_invalidate_call` with OnResize and OnPrepareDraw

**Comment by duncanspumpkin** [comment]
Use the member functions `InitScrollWidgets`, `DrawWidgets`

**Comment by duncanspumpkin** [comment]
Remove all access to the raw widgets i.e. `window_ride_main_widgets` outside of SetPage. All access is through `widgets` which has been set to `window_ride_xxx_widgets` by the SetPage function.

**Comment by duncanspumpkin** [comment]
Rename all the invalidate functions as `OnPrepareDraw` likewise the paint functions should be `OnDraw`. I.e. there should be a `OperatingOnPrepareDraw` and a `OperatingDraw`

**Comment by duncanspumpkin** [comment]
`GetColourButtonImage` also needs `ImageId` work. Put a TODO on it.

**Comment by duncanspumpkin** [comment]
window_ride_current_music_style_order move it up with the other private vars.

**Comment by duncanspumpkin** [comment]
`window_ride_current_music_style_order` looks to be really broken before this refactor so you could probably have a check to see if there are any issues open about the fact that two rides with music tabs open might have glitches. And if there are ask them to recheck after this PR is merged.

**Comment by duncanspumpkin** [comment]
`WindowRideMeasurementsDesignCancel` why is that `extern`???

**Comment by duncanspumpkin** [comment]
`_moneyInputText` should be a variable inside of `IncomeOnMouseUp` and not a member variable.

**Comment by duncanspumpkin** [comment]
There are a good few more functions that should be private.

**Comment by duncanspumpkin** [comment]
As this is a large window I've not been quite as stringent there are still lots of other issues with this window so the above comments are just to bring it into alignment with the other windows. The key ones are relook at the Open functions, drop all the `WindowRide`, use the member functions. The others if you don't understand what to do I can fix them later.

**Comment by tupaschoal** [comment]
Hi @leoleotte,

Dropping by to ask whether you want to resume the PR based on Duncan's comments.

**Comment by Gymnasiast** [comment]
Closing this as it has been ~6 weeks. Can be reopened if OP returns.

**Pull request closed without merging**
