### PR TITLE
Fix #8079: Crash when unloading buggy custom rides

### LINKED ISSUE #8079: Custom ride The ZAP! crashes when unloading passengers
**OS:** [e.g. Windows 10]
**Version:**  0.2.1
**Commit/Build:** 426e106

https://openrct2.org/forums/topic/3415-game-crashes-when-there-are-over-2000-guests-in-park/ If you download the save "Mystic Timbers" in the last post of this thread and open it up, it crashes within 1 second when the custom ride The ZAP! unloads. This isn't specific to the save, if you try and create it in a different map the same happens. I *assume* this ride worked for someone at sometime as otherwise it wouldn't have been uploaded (although maybe i'm wrong - I don't have vanilla around to test)

Stack trace:
 	openrct2.dll!std::vector<signed char,std::allocator<signed char> >::operator[](const unsigned __int64 _Pos) Line 1733	C++
	openrct2.dll!rct_peep::UpdateRideLeaveVehicle() Line 4092	C++
 	openrct2.dll!rct_peep::UpdateRide() Line 5065	C++
 	openrct2.dll!rct_peep::Update() Line 1267	C++
 	openrct2.dll!peep_update_all() Line 442	C++
 	openrct2.dll!OpenRCT2::GameState::UpdateLogic() Line 247	C++
 	openrct2.dll!OpenRCT2::GameState::Update() Line 141	C++
 	openrct2.dll!OpenRCT2::Context::Update() Line 940	C++
 	openrct2.dll!OpenRCT2::Context::RunFixedFrame() Line 858	C++
 	openrct2.dll!OpenRCT2::Context::RunFrame() Line 832	C++
 	openrct2.dll!OpenRCT2::Context::RunGameLoop() Line 802	C++
 	openrct2.dll!OpenRCT2::Context::Launch() Line 774	C++
 	openrct2.dll!OpenRCT2::Context::RunOpenRCT2(int argc, const char * * argv) Line 215	C++
 	openrct2.dll!NormalisedMain(int argc, const char * * argv) Line 60	C++
 	openrct2.dll!LaunchOpenRCT2(int argc, wchar_t * * argvW) Line 46	C++
 	openrct2.exe!wmain(int argc, wchar_t * * argvW, wchar_t * envp) Line 28	C++
 	[External Code]	

The problem is `vehicle_entry->peep_loading_position`s is empty so `vehicle_entry->peep_loading_positions[current_seat]` throws an out of range error. I'm not sure how this happened as I don't understand structure of rides enough.

- [] Reproducible in RCT2 (vanilla)?
- [] Specific to multiplayer?

**Steps to reproduce:**
1. Open attached save

2. Crashes within 1 second, which is exactly when The ZAP! is unloading

**Save game:**

[Mystic Timbers.zip](https://github.com/OpenRCT2/OpenRCT2/files/2466135/Mystic.Timbers.zip)

### PR DESCRIPTION
**Pull request by Gymnasiast**
Also fixes https://github.com/OpenRCT2/OpenRCT2/issues/8969, #7700 and https://openrct2.org/forums/topic/3642-crashing-when-playing-files/ .

Possibly also https://github.com/OpenRCT2/OpenRCT2/issues/8958 -- but that has missing objects that NE does not have.

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Would it be possible to instead fix these rides in the S6 importer?

**Comment by Broxzier** [comment]
Do you know how these indices or seat positions were set incorrectly? The thing with these checks is that, while fixing the issue, they bloat the codebase one by one.

I agree with Aaron that fixing them on load is preferable.

**Comment by duncanspumpkin** [comment]
You could mess it up by changing the ride entry whilst there are peeps on the ride. I'm not sure if that is possible though.

**Comment by duncanspumpkin** [comment]
Current seat is a field that is used for a few different things so i expect it might be possible that this is because of incorrectly clearing the variable.

**Comment by Gymnasiast** [comment]
@broxzier I don't know what causes them. What all parks I investigated have in common is that the crash always happens when peeps exit a custom flat ride. It does not seem to be the result of changing the ride entry while the ride is open. I also have a scenario (LOTR - The Shire) that crashes very soon after opening, so it seems it's really down to badly made custom ride entries.

**Comment by duncanspumpkin** [comment]
SEFLIGHT.dat is an example of a bugged object. I want to have a look to see how it is handled in vanilla.

**Comment by duncanspumpkin** [comment]
In vanilla this would have returned 0. Assuming `current_seat` is `0` and `peep_loading_positions` is a zero sized array. This is because it would have accessed the next memory location which would be the size of `vehicle_entry->peep_loading_positions[1];` which is `0`.

`int8_t loadPosition = vehicle_entry->peep_loading_positions[current_seat];`

I'm not sure what would be the best solution as the object file is definitely at fault here. Could we perhaps add a verbose warning stating that the object is broken just in case we come up with a better solution one day.

**Comment by Gymnasiast** [comment]
> Could we perhaps add a verbose warning stating that the object is broken just in case we come up with a better solution one day.

OK, I went with that.

**Comment by duncanspumpkin** [comment]
Even though this is a logic mod and would normally need a network increment there is no need this time as the game would crash without this change so I'm merging it as is.

**Pull request merged**
