### PR TITLE
Fix #12741: Unstuck a queue for ride station

### LINKED ISSUE #12741: [000000] openrct2.exe:
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/0000000000000000000000000000000000000000000000000000000000000000">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>
<tr>
    <td><strong>Attributes</strong></td>
    <td>
<strong>dummy</strong> &mdash; 1
        <ul>
                <li><code>0</code> &mdash; 1</li></ul><br>
<strong>attachment_replay.sv6r</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_park.sv6</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_config.ini</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>assert_failure</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_park.sv6.gz</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_screenshot.png</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>commit</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br></td>
    </tr></table>

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by ZehMatt** [comment]
Doesn't this hide the actual issue?

**Comment by janisozaur** [comment]
It kind of does. I can come up with something better (breaking up the cycle?) later. For now I asked the user on reddit to confirm this fixes their issue, but I suspect it might just be pushed to a later part of code. That's as much as I can do without access to such park and I don't have the time to construct such one now.

**Comment by duncanspumpkin** [comment]
I want to add validation of linked lists like this on load.

**Comment by janisozaur** [comment]
That'd be preferred way, but still bugs could occur. But then this should be an assert instead.

**Comment by IntelOrca** [comment]
asserts don't help here because it is too late. The assert is best done after every time the queue list is modified, which you could do if everything only modifies it by a common method. They also don't have any effect in non-debug builds.

We do tortoise and hare in a lot of places, yet I can't figure how how best to make some clever template helper for it. We sort of need something like `std::tortoise` similar to `std::find_if`.

**Comment by janisozaur** [comment]
If we load processed park without loops and hit an assert I hope to get a replay.

Yeah, I can agree the modification should be guarded, but that would take more effort and I haven't got enough time now.

I also came to the same conclusion regarding template, especially looking at the code already in Sprite.cpp. I have some idea: the template could take two lambdas, one to advance the cursor, other to consume it.

**Comment by rik-smeets** [comment]
I'm closing this PR due to inactivity and the referenced issue already being closed.

**Pull request closed without merging**
