### PR TITLE
Update language.c

### PR DESCRIPTION
**Pull request by telk5093**
Uncomment about korean.
Please notice me if somethings are wrong.
I did not tested this modified code.

### CODE REVIEW

**Comment by IntelOrca** [comment]
You also need to add a **RCT2_LANGUAGE_ID_** to the enum.
Also you will need to change the language display name back to Korean as it won't render properly when other languages are selected. I am also not sure how C will store that UTF-8 string.

**Comment by IntelOrca** [comment]
I don't have gulim.ttc suggesting it is not distributed with Windows so I don't think that is a good font to use. How about malgun.ttf?

You will also need to play around with the font sizes until it looks right.

**Comment by telk5093** [comment]
RCT1 and 2 in korean uses the Gulim as its font since it is a bitmap font, not a vector.
I think malgun(Malgun Gothic) is not good since it needs cleartypes.
If you want I can offer you a gulim.ttc: http://file.telk.kr/font/gulim.ttc (12.9MiB)

**Comment by IntelOrca** [comment]
It needs to be a font that is distributed with the operating system. We can't distribute gulim with the game.

**Comment by telk5093** [comment]
gulim.ttc is distributed font in windows in korea as well as malgun.ttf.
malgun is not offered in old os such as win98 or winXP. (It is distributed from vista)
Do you think I change it to malgun, nevertheless?

**Comment by IntelOrca** [comment]
I think it should be the most likely font people will have pre-installed. I don't seem to have gulim.ttc but I do have malgun.ttf. Are there any alternatives?

**Comment by telk5093** [comment]
Malgun is the default font for WinVista, 7, 8, 10
and Gulim is the default font for Win95, 98, Me, XP in windows os in korean.
And gulim is also contained Vista, 7, 8, 10.
There is no alternatives except for malgun and gulim.

As now, I want to check OpenRCT2 runs as my own language.
It would be nice whatever font is.

**Comment by IntelOrca** [comment]
OK - I have used malgun and picked font size and offsets that looked reasonable.

**Comment by telk5093** [comment]
Thanks :)

**Pull request closed without merging**
