### PR TITLE
Validate parameters passed to game commands

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by janisozaur** [comment]
ping

**Comment by IntelOrca** [comment]
does it work?

**Comment by janisozaur** [comment]
Yeah… it changes the control flow so it's harder to make server hit an `assert()` or access invalid memory with some malformed packet and makes `game_do_command` return `MONEY32_UNDEFINED` in such cases, no other changes.

**Comment by IntelOrca** [comment]
merge it

**Pull request merged**
