### PR TITLE
Add ratings modifier for reversed trains

### PR DESCRIPTION
**Pull request by kyphii**
Part one of reversed trains follow up.

This PR adds a ratings modifier for the reversed trains option. Each ride type which can use the option by default has the new bonus added. For the ride types with an existing reversed train type, I've copied the values from that train type's bonus. The resulting stats aren't a perfect match (probably due to a difference in ordering), but it's very close. For the other ride types, I've given them arbitrary values in about the same range, with less intensity and nausea for gentle coaster types, and more for extreme coaster types.

I didn't add the bonus to any rides which can only run backwards with cheats, as I figured the stats don't matter as much if the player is using cheats. That could certainly be added if it's wanted though.

### CODE REVIEW

**Comment by ZeeMaji** [comment]
Would it be wise to show these numbers in the vehicle tab somewhere? I'm not sure honestly.
On one hand RCT1 does not show these numbers and has two reversed trains but on the other hand RCT2 shows these numbers but only has one reversed train.
Personally kind of leaning more towards leaving them hidden as i feel like it might start to clutter the vehicle tab if you show them as that'd be six different numbers on the window including the ones for the train's ratingmultipliers, plus with it being bound by the ride type it seems less important to include as it's not something that can change between different train types.

**Comment by kyphii** [comment]
> Would it be wise to show these numbers in the vehicle tab somewhere? I'm not sure honestly.

I'm not sure how useful it would be given the effort required. Unlike with vehicle types, the reversed trains option has a consistent rule for all applicable ride types - it gives a small boost to excitement and larger boosts to intensity and nausea. The actual values probably aren't that important to the average player.

If there was a desire for such a thing, maybe exposing a detailed ride stat breakdown to the plugin API would be an option. It sounds potentially complex for limited utility though.

**Comment by ZehMatt** [comment]
We should cover this for the tests, we either create a new single small park with one of the rides having reversed vehicles or modify one of the existing test parks to include this case. Could you look into doing that?

**Comment by ZeeMaji** [comment]
> I'm not sure how useful it would be given the effort required. Unlike with vehicle types, the reversed trains option has a consistent rule for all applicable ride types - it gives a small boost to excitement and larger boosts to intensity and nausea. That's easy enough to understand through observation alone, the actual values probably aren't that important to the average player.

Good points, probably best to just leave it excluded from the UI then for those reasons and the clutter reason i mentioned last night.

**Review by ZehMatt — APPROVED** [review]
LGTM, thanks.

**Comment by kyphii** [comment]
Does this need a changelog entry?

**Comment by ZehMatt** [comment]
> Does this need a changelog entry?

Actually good point didn't quite think about that, yeah please do.

**Comment by duncanspumpkin** [comment]
> > Does this need a changelog entry?
> 
> Actually good point didn't quite think about that, yeah please do.
> 
> Edit: Also needs a network bump.

I don't think it should have a changelog this is just an enhancement of a feature we are adding in this release. It would have a changelog entry if it was to be merged in 0.4.6.

**Comment by ZehMatt** [comment]
> > > Does this need a changelog entry?
> > 
> > 
> > Actually good point didn't quite think about that, yeah please do.
> > Edit: Also needs a network bump.
> 
> I don't think it should have a changelog this is just an enhancement of a feature we are adding in this release. It would have a changelog entry if it was to be merged in 0.4.6.

It does alter the game mechanics so I think its a reasonable change log entry unless we like to keep it hidden from the user? It was previously not stated that it would affect the rating in any way.

**Comment by duncanspumpkin** [comment]
> > > > Does this need a changelog entry?
> > > 
> > > 
> > > Actually good point didn't quite think about that, yeah please do.
> > > Edit: Also needs a network bump.
> > 
> > 
> > I don't think it should have a changelog this is just an enhancement of a feature we are adding in this release. It would have a changelog entry if it was to be merged in 0.4.6.
> 
> It does alter the game mechanics so I think its a reasonable change log entry unless we like to keep it hidden from the user? It was previously not stated that it would affect the rating in any way.

Hmm i would have it all under the one entry but now i look at it we already have two entries for it due to the plugin feature so meh. Don't really mind what is done.

**Comment by ZehMatt** [comment]
> > > > > Does this need a changelog entry?
> > > > 
> > > > 
> > > > Actually good point didn't quite think about that, yeah please do.
> > > > Edit: Also needs a network bump.
> > > 
> > > 
> > > I don't think it should have a changelog this is just an enhancement of a feature we are adding in this release. It would have a changelog entry if it was to be merged in 0.4.6.
> > 
> > 
> > It does alter the game mechanics so I think its a reasonable change log entry unless we like to keep it hidden from the user? It was previously not stated that it would affect the rating in any way.
> 
> Hmm i would have it all under the one entry but now i look at it we already have two entries for it due to the plugin feature so meh. Don't really mind what is done.

We can still change it, I was thinking we already had this in the last release but I was wrong so it makes actually sense to put up as one feature, the plugin entry can probably stay separate but I don't have a strong opinion about it either.

**Comment by ZehMatt** [comment]
> Want me to remove the changelog entry for this PR?

Maybe its best, the other entry should also include the rating bonus so its clear its not just a visual change anymore.

**Review by Broxzier — APPROVED** [review]

**Pull request merged**
