### PR TITLE
Fix #4453: path separators being mishandled

### LINKED ISSUE #4453: [Regression] Paths from get_file_path are returning strings with backslashes on macOS and Linux
**OS:** macOS and Linux
**Version:** 0.0.5
**Commit/Build:** 23b5af6 (exact commit with regression)

`get_file_path` is returning strings with backslashes on the posix platforms, with is incorrect behavior. This is because the strings in `RCT2FilePaths` all use backslashes, and the commit 23b5af6 removed the code that was performing the slash conversion in favor of `safe_strcat_path`, which doesn't have the slash conversion.

I see two solutions: Either we modify `safe_strcat_path` to change backslashes into `platform_get_path_separator()`, or we use macro guards to have `RCT2FilePaths` use forward slashes on posix systems. (that, or we have all platforms use forward slashes in `RCT2FilePaths`, because all supported versions of Windows support that 😜)

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Load the game on macOS or Linux
2. ...
3. `FATAL[.../src/rct2.c:414 (check_file_path)]: Could not find file .../rct2/Data\g1.dat`

### PR DESCRIPTION
**Pull request by janisozaur**
Since Windows I/O API converts all slashes to backslashes, just use
slashes.

### CODE REVIEW

**Comment by janisozaur** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx

> Note  File I/O functions in the Windows API convert "/" to "\" as part of converting the name to an NT-style name, except when using the "\\?\" prefix as detailed in the following sections.

**Comment by IntelOrca** [comment]
Can you instead concatenate a compile time constant of the path separator?

**Comment by janisozaur** [comment]
Going slashes-only would simplify a bit our platform code. I'd rather want it this way.

**Comment by IntelOrca** [comment]
@janisozaur I disagree, it should be using the correct OS slash.

**Comment by LRFLEW** [comment]
I'd say no to the macro solution. To really make it work, it should be able to accept any number of components, but the only way to really do that is to either make it variadic (which is a nightmare to work with, and I still don't get), or abuse the preprocessor with something like Boost.PreProcessor. Using the string in the way I described in the issue is probably preferable.

**Comment by Broxzier** [comment]
Strings are automatically concatenated if placed next to each other, having something like this will work too: `"Path" SLASH "to" SLASH "file"`. It does look ugly though.

**Comment by janisozaur** [comment]
Updated

**Pull request merged**
