### PR TITLE
Spiral slide paint setup

### PR DESCRIPTION
**Pull request by marijnvdwerf**
image

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
We need to split out the ground drawing code (and fence) and make that a separate function that is common across all flat rides.

**Comment by IntelOrca** [comment]
I think it would also be good to put each case on consecutive lines to reduce the code bloat.

**Comment by marijnvdwerf** [comment]
I'd also like the parameter order of `int sub_98199C()` (and related methods) changed.

`al` and `cl` should be after each other.
`length_x` and `length_y` should be swapped
`ah` should be after those four.

Would make it easier to decompile, as all code I've come across assigns them in this order.

Something like
```c
int sub_98199C(
    int image_id,
    sint8 al,
    sint8 cl,
    sint16 length_x,
    sint16 length_y,
    sint8 ah,
    int height,
    uint32 rotation
) {
```

**Comment by duncanspumpkin** [comment]
the length_x and length_y being backtofront was due to a mistake i made a while back and then that was the easiest way to fix it. I'm all for changing it but i think it might be best if we just labelled al, cl, ah as well.

**Comment by duncanspumpkin** [comment]
@marijnvdwerf see #3174

**Pull request merged**
