### PR TITLE
Add GitHub Actions problem matchers

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Review by tupaschoal — COMMENTED** [review]
What does this do, paste the error on the PR?

Can you add a link to the GH action? (I can Google, but for the sake of documenting it would be nice to have those here)

**Comment by janisozaur** [comment]
Marketing material had this: https://raw.githubusercontent.com/ammaraskar/gcc-problem-matcher/master/images/example-pull-request.png but I'm waiting to see if it actually picks up anything in this obviously faulty build.

**Comment by janisozaur** [comment]
Ah, the build is done, but no error reports came back. I'm going to close that PR.

**Comment by tupaschoal** [comment]
> Marketing material had this: [ammaraskar/gcc-problem-matcher@`master`/images/example-pull-request.png (raw)](https://raw.githubusercontent.com/ammaraskar/gcc-problem-matcher/master/images/example-pull-request.png) but I'm waiting to see if it actually picks up anything in this obviously faulty build.

It sounds nice, though, I hope you can make it work

**Comment by janisozaur** [comment]
Not sure why it didn't show up the first time, but re-running it yielded expected results:
Screen Shot 2022-04-01 at 08 19 23


MSVC matcher did not provide feedback for some reason, even though it reported the error as expected:
```
  Cheats.cpp
  CmdlineSprite.cpp
D:\a\OpenRCT2\OpenRCT2\src\openrct2\Cheats.cpp(227,13): error C2561: 'CheatsGetName': function must return a value [D:\a\OpenRCT2\OpenRCT2\src\openrct2\libopenrct2.vcxproj]
D:\a\OpenRCT2\OpenRCT2\src\openrct2\Cheats.cpp(222): message : see declaration of 'CheatsGetName' [D:\a\OpenRCT2\OpenRCT2\src\openrct2\libopenrct2.vcxproj]
```

**Comment by janisozaur** [comment]
Oh I know why MSVC is absent - the matcher is only installed after build is done. Let me fix that.

**Comment by janisozaur** [comment]
Indeed, it reports back correctly now:
Screen Shot 2022-04-01 at 08 42 01

**Review by IntelOrca — APPROVED** [review]

**Comment by tupaschoal** [comment]
Nice improvement!

**Pull request merged**
