### PR TITLE
Fix #5636: Pausing game no longer affects mute button

### LINKED ISSUE #5636: Pausing the game shows mute button as active
**OS:** ArchLinux
**Version:** 0.0.8
**Commit/Build:** 9e1711c345d549ecea2d9046bd9ae7f81d12305d

When pausing the game, the mute button shows the game as muted. While one could argue that this makes some sense, clicking the mute button during pause mode doesn't and you are mixing pause mute state with playing mute state.

### PR DESCRIPTION
**Pull request by Keatzee**
Fix #5636: The mute button state is no longer affected by pausing the game. 

In my opinion, changing the configuration to mute the game is a somewhat confusing way to do it, but that would best be addressed once the GameState refactoring is finished.

I also fixed a very minor issue about the ride music not being disabled properly. This lead to the ride music being resumed without the game sounds when muting, pausing, then unpausing the game.

### CODE REVIEW

**Comment by IntelOrca** [comment]
Could you format your first commit message to match our [our guidelines](https://github.com/OpenRCT2/OpenRCT2/wiki/Commit-Messages)?

**Comment by Keatzee** [comment]
How's this?

**Comment by AaronVanGeffen** [comment]
He's referring to the actual commit message, not the title of your pull request.

**Comment by Keatzee** [comment]
I'm a bit confused as to what I need to change. Do you mean the commit in my branch?

**Comment by ZehMatt** [comment]
chrome_2017-08-17_23-58-39

**Comment by AaronVanGeffen** [comment]
> I'm a bit confused as to what I need to change. Do you mean the commit in my branch? I can't find any way to change that.

Yes, the commits themselves. You'll have to amend the commits through git. Look up how to do an interactive rebase using `git` if you're set on doing it. Otherwise, your PR can be merged and amended by a maintainer, as I suggested earlier.

Either way, just follow the conventions next time you enter a commit message, and you'll be fine. :)

**Comment by Keatzee** [comment]
@AaronVanGeffen The latter option sounds easier, I'll stick with that :stuck_out_tongue: Sorry everyone.

**Comment by Keatzee** [comment]
Resolved conflicts

**Comment by slonermike** [comment]
is this PR still active? I have a PR open for #6293 that may be irrelevant if this goes in.

**Comment by Keatzee** [comment]
@slonermike I've been far too busy to work on the game lately, but I'm pretty sure this PR is ready to merge (besides the changelog conflict) and has been for a long time. I have no idea if this affects #6293, so I can't really help you there, sorry

**Comment by IntelOrca** [comment]
Superseded by aca70483778f615fa57d1c245879aa789bea1612 and a98c936316f078e43419794ff9d1dadeec0a5c48.

**Pull request closed without merging**
