### PR TITLE
Tile Inspector: remove hardcoded surface/edge style names

### PR DESCRIPTION
**Pull request by Gymnasiast**
When the surface styles were moved into objects, the tile inspector was not modified to use these. This is causing problems on the new save format branch, so this PR tackles that.

### CODE REVIEW

**Comment by Umdlye** [comment]
The RCT1 edge style strings are still there after this update, are they still needed for something?

**Comment by Gymnasiast** [comment]
@Umdlye Well spotted! I have now removed those as well.

**Comment by Umdlye** [comment]
Working on copying translations from these strings to the object files and noticed some of the removed strings don't have matching object files (blue grid, inverted checkerboard, underground view). Removing those strings might cause issues.

**Comment by Gymnasiast** [comment]
@Umdlye They won't, as those are only used for rendering. The blue grid of the Track Designer, for example, is grass in disguise. That's also what the TI will say.

@Broxzier The descriptions of the objects can be fixed in https://github.com/OpenRCT2/objects/tree/master/objects/rct2/terrain_surface

**Comment by Gymnasiast** [comment]
@Broxzier Addressed here: https://github.com/OpenRCT2/objects/commit/ca912583fe20dca53289abdd0b40c2144f12b086

**Pull request merged**
