### PR TITLE
use std:: functions instead of Math::

### PR DESCRIPTION
**Pull request by LinusU**
This uses the builtin C++ functions instead of defining our own.

### CODE REVIEW

**Comment by janisozaur** [comment]
This of course fails on appveyor, otherwise I would've included this myself. Feel free to find a proper solution.

**Comment by LinusU** [comment]
Hehe, of course it does :laughing: 

We actually had the same problem in node-canvas, what do you think of this solution: Automattic/node-canvas#660?

**Comment by IntelOrca** [comment]
I am find with using std::min and std::max within in our own wrappers, but please use the Math wrappers everywhere... then its consistent (particularly as there is no std::clamp).

**Comment by LinusU** [comment]
@IntelOrca sounds good, I'll update this pr

**Comment by janisozaur** [comment]
who defines the macro?

**Comment by IntelOrca** [comment]
@janisozaur Some windows header I think.

**Comment by LinusU** [comment]
`windows.h`

**Pull request merged**
