### PR TITLE
Improve quoted strings in console

### PR DESCRIPTION
**Pull request by KernelDeimos**
This PR
- Fixes a problem with quoted strings
- Adds support for backslash-escaping quotes inside strings.

The console currently supports the use of quotes so that tokens may contain spaces. In the current implementation, this produces unexpected behavior for consecutive tokens, which are interpreted as if surrounded by quotes.

For example:
- `echo hello there` outputs `hello` as expected
- `echo "hello there"` outputs `hello there` as expected
- `echo "hello" there` also outputs `hello there`
- `"echo" hello there` outputs ` hello there` (note the leading space)

This happens because, after a quoted token, the console believes the next token(s) is/are also quoted, and doesn't stop until observing another quote.

This PR fixes the issue above, producing the following behavior:
For example:
- `echo "hello" there`outputs `hello`
- `"echo" hello there` outputs `hello`

I believe this behavior is more correct because the `echo` command takes only one parameter and ignores the rest.

This PR also adds quote escaping so that parameters to commands may contain quotes. This could be useful if, for example, there's a command to set the text on a sign or the title of a ride (something I may try to tackle later if it's a welcome addition).

For example:
- `echo "why \"hello\" there"` outputs `why "hello" there`
- `echo why\ hello\ there` outputs `why hello there`
- `echo why\ hello\ there "\` outputs `[console] trailing slash on token is not allowed`
- `echo c:\\windows` outputs `c:\windows`

Additionally, this change does not create a new buffer, and does not do byte-by-byte copying. Instead, it intelligently copies text between escape characters. This is, I believe, the most optimal solution, and wasn't very complicated to implement either.

### CODE REVIEW

**Comment by KernelDeimos** [comment]
Oh, I believe it wants me to cast to `size_t` before passing `countEscapeChars` to malloc. I remembered to do it elsewhere but I guess I forgot about it here - I'll have that fixed in a jiffy. CI is amazing.
```
../src/openrct2/interface/InteractiveConsole.cpp:1572:38: error: argument 1 range [18446744069414584323, 18446744073709551615] exceeds maximum object size 9223372036854775807 [-Werror=alloc-size-larger-than=]
             utf8* arg = (utf8*)malloc(length - countEscapeChars + 1);
```

**Comment by KernelDeimos** [comment]
Well, same problem again. I'm at a complete loss for what that could even mean.

**Comment by KernelDeimos** [comment]
Oh, I think I know what I need to do now. I didn't realise it did checks *that* fancy. Is it easy to run this locally or should I just push commits on my branch until it works? (I'm not super familiar with Travis yet)

**Comment by janisozaur** [comment]
> Is it easy to run this locally

Just compile with GCC8

**Comment by janisozaur** [comment]
ping

**Comment by KernelDeimos** [comment]
I still intend to figure this out but it'll be a while before I have time to

**Comment by janisozaur** [comment]
@KernelDeimos still working on that?

**Comment by KernelDeimos** [comment]
If it's easier I can just submit a new PR later XD I'm an engineering student so I'll probably figure it out in like 3 months

**Comment by AaronVanGeffen** [comment]
It doesn't help that a recent refactor operation has introduced a merge conflict:

```
<<<<<<< feature/quoteescape
            utf8* arg = (utf8*)malloc(length - (size_t)countEscapeChars + 1);

            size_t escapeOffset = 0;

            const utf8* nextSegment = start;
            for (const utf8* cur = start; cur <= end; cur++) {
                if (cur == end || (*cur == '\\' && !inEscape)) {
                    inEscape = true;
                    // if (cur != end) continue;
                    // Copy section of memory at interval [last escape, here-1]
                    size_t cpyStart = (nextSegment - start) - escapeOffset;
                    size_t cpyLen  = cur - nextSegment;
                    memcpy(arg + cpyStart, nextSegment, cpyLen);
                    escapeOffset++;
                    nextSegment = cur+1;
                } else {
                    inEscape = false;
                }
            }
            arg[length] = 0;

            if (argc >= argvCapacity)
            {
                argvCapacity *= 2;
                argv = (utf8**)realloc(argv, argvCapacity * sizeof(utf8*));
            }
            argv[argc] = arg;
            argc++;
=======
            argv.emplace_back(start, length);
>>>>>>> develop
```

On the bright side, that means you can now operate on `std::string` rather than reallocate everything manually.

If you are short on time, though, then perhaps it would be best to close this for now.

**Comment by KernelDeimos** [comment]
OMG really? Okay as proud as I was about how efficiently I did the reallocation that will make this a lot easier, I might take a crack at it this week.

but yeah, close this one - I'll re-implement it on an updated branch

**Pull request closed without merging**
