### PR TITLE
Allow skipping of OpenMusic download if prepopulated

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by karst** [comment]
My only concern is if it doesn't skip it now whenever a new version is available?

**Comment by janisozaur** [comment]
It will. We could do a more thorough checking by inspecting json in the zip (parkap) file, but it is something I don't think I can implement without losing sanity. The main purpose of this is to address issues we see in launchpad which creates deb packages for PPA on builders that have no internet access and we need to prepopulate the assets. Sometimes they _do_ get desynced, as it is manual effort.

The pre-populated packs come from repository such as https://github.com/janisozaur/openrct2-unpacked-data, which (mostly) I maintain.

**Comment by janisozaur** [comment]
A better (IMO) way would be to have all relevant subprojects upload the assets to the unpacked one. Doesn't necessarily exclude the suggestion you provided.

Regardless if any of those options do get implemented, let's deal with the issue at hand using the means we have to get the release done.

**Review by ZehMatt — APPROVED** [review]

**Comment by Thaodan** [comment]
Thank you for the fix, I faced the exact same issue when building on the OBS.

**Pull request merged**
