### PR TITLE
Actually toggle vsync instead of re-initializing the entire thing again

### PR DESCRIPTION
**Pull request by ZehMatt**
I'm not sure why we did it this way but I'm fairly confident we don't have to.

### CODE REVIEW

**Review by AaronVanGeffen — APPROVED** [review]

**Comment by Gymnasiast** [comment]
Would like to check this out - I have some glitches with VSync on `develop`.

**Comment by ZehMatt** [comment]
One of the CI runs failed, SDL documents that this function has been there since 2.0.8 which is quite old, I wonder what ancient version this distro has.

**Comment by Gymnasiast** [comment]
Debian Bullseye has 2.0.14: https://packages.debian.org/bullseye/libsdl2-2.0-0
Not sure why it doesn’t work on the CI.

**Comment by AaronVanGeffen** [comment]
> Debian Bullseye has 2.0.14: https://packages.debian.org/bullseye/libsdl2-2.0-0

Our Debian CI reports this as well, in the cmake phase. Not sure why it's not working then 😕

**Comment by ZehMatt** [comment]
Looks like I made a little mistake reading the docs, it requires 2.0.18 and not 2.0.8 which dates to Nov 30, 2021 which is still quite old, I think i have to rely on checking the SDL version via the macro.

**Comment by AaronVanGeffen** [comment]
Debian Bullseye (v11, oldstable) itself is also quite old, released in 2021. We should probably transition to having Bookworm (v12, stable) on the CI roster instead. (cc @janisozaur)

**Comment by Gymnasiast** [comment]
I’d still like an ifdef, even if we end up switching the CI.

**Review by Gymnasiast — COMMENTED** [review]
Code LGTM, testing it as we speak.

**Review by Gymnasiast — APPROVED** [review]
Works correctly on my Ubuntu 24.04. 

It has even solved a glitch. Previously, when I enabled VSync on Software w/ hardware display, the screen was not invalidated correctly. But after this patch, that glitch’s gone.

Nice work! May even warrant a changelog entry.

**Pull request merged**
