### PR TITLE
Fix Ride.cpp compilation issues

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Compilation issues? On which system/compiler?

**Comment by janisozaur** [comment]
c++ (Raspbian 6.3.0-18+rpi1) 6.3.0 20170516

**Comment by janisozaur** [comment]
Ah, fsck. It's still wrong. https://travis-ci.org/OpenRCT2/OpenRCT2/jobs/323937136

I merged it because Travis has an outage and didn't launch a build. Working on it.

**Comment by Gymnasiast** [comment]
It did launch a build eventually. I cancelled it since you had already merged it.
(Also, all CIs were green when I merged Ride.cpp)

**Pull request merged**
