### PR TITLE
Improve scrolling behaviour in object selection window

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
Earlier this week, we made the invention list window resizeable (#7562). This PR applies the same anchoring principles to the already resizeable object selection window.

Fixes text overflowing between columns, as described in #6359.

Before:
before

After:
screenshot_20180602_150430

### CODE REVIEW

**Comment by Broxzier** [comment]
Could you move up the text in the lower-right corner so that it doesn't overlap with the resize control corner thing? (not sure what it's called)

**Comment by AaronVanGeffen** [comment]
That's a good point. I've moved it up a little.

**Comment by AaronVanGeffen** [comment]
@Broxzier How are you getting that? That is exactly the kind of glitch this PR should fix... In fact, it looks like this for me: 
untitled

This is both in the scenario editor and in-game. Are you opening the window elsewhere?

**Comment by AaronVanGeffen** [comment]
Thanks for the video, that helps. Really curious threshold bug there.

**Comment by AaronVanGeffen** [comment]
Turns out I wasn't compensating for the checkbox offset in the scrollpaint function. Should be fixed now?

**Pull request merged**
