### PR TITLE
Condense common wooden support code

### PR DESCRIPTION
**Pull request by Gymnasiast**
Most of the code between the three wooden support drawing methods is functionally the same, with only a few small exceptions. As such, condense the code, passing the exceptions as template parameters.

### CODE REVIEW

**Review by AaronVanGeffen — APPROVED** [review]
Code looks fine on cursory review, but I have not had an opportunity to test it thoroughly. I trust you've done your due diligence, though.

**Comment by ZeeMaji** [comment]
Tested multiple parks with different wooden coasters, everything is displaying correctly.

**Comment by Gymnasiast** [comment]
@ZeeMaji Did you also test some paths that have box supports?

**Comment by ZeeMaji** [comment]
Box path supports seem to be okay as well, i went ahead and tested both the built in wooden supports, some custom conversions of legacy footpath supports, and some legacy footpaths with box supports and all seem to work fine.

**Pull request merged**
