### PR TITLE
[Issue #9568] Replace RRC lift sounds LiftWood to match SFRC

### PR DESCRIPTION
**Pull request by iking96**
### Description

Proposed solution to https://github.com/OpenRCT2/OpenRCT2/issues/9568. Updates Reverser RC to have same lift sound [as the Side Friction RC](https://github.com/OpenRCT2/OpenRCT2/blob/d33ddaba2cd3626e9279cb0659960c942ccd8c76/src/openrct2/ride/coaster/meta/SideFrictionRollerCoaster.h#L39). Updates Compact Inverted Coaster to have the classic lift sound.

Ride | Current sound | Proposal
-- | -- | --
SLC | Friction wheels | Classic chain sound or Arrow sound
Reverser RC | Classic chain sound | Side-friction RC sound

### CODE REVIEW

**Comment by iking96** [comment]
Hey @Gymnasiast,

I am a having a bit of trouble debugging this failure: https://github.com/OpenRCT2/OpenRCT2/runs/1200743771
```
...
WARNING[../src/openrct2/ReplayManager.cpp:736 (Serialise)]: Replay network version mismatch: '0.2.6-25', expected: '0.3.1-0'
WARNING[../src/openrct2/ReplayManager.cpp:806 (CheckState)]: Different sprite checksum at tick 84547 (Replay Tick: 633) ; Saved: 33608acac467a02c8df21673c6a6a09eb22cc93d, Current: 814ea9f3f6130fc2c85b6c70de4aba46df8c4a33
For security reasons, it is not recommended to run OpenRCT2 with elevated permissions.
../test/tests/ReplayTests.cpp:101: Failure
Value of: replayManager->IsPlaybackStateMismatching() == false
  Actual: false
Expected: true
[  FAILED  ] Replay/ReplayTests.RunReplay/bpb1000Ticks, where GetParam() = testdata/replays/bpb1000Ticks.sv6r (3104 ms)
...
```

I believe the failure is saying this method returned `false`: https://github.com/OpenRCT2/OpenRCT2/blob/d33ddaba2cd3626e9279cb0659960c942ccd8c76/src/openrct2/ReplayManager.cpp#L451-L458

Judging by the warning proceeding the failure I believe I am hitting this branch: https://github.com/OpenRCT2/OpenRCT2/blob/d33ddaba2cd3626e9279cb0659960c942ccd8c76/src/openrct2/ReplayManager.cpp#L799-L809

I think this test is re-running game scenarios and ensuring sprites are unchanged vs some golden file. I suppose the "LiftData" counts as part of the sprite and could throw its checksum off; is that your understanding as well?

What is the best way to move forward here, would I need to update something in this repo: https://github.com/OpenRCT2/replays

**Comment by duncanspumpkin** [comment]
Replays just need to be rerecorded. I'm normally the one who does that but I won't do that until it's confirmed this fix is good to go

**Comment by Gymnasiast** [comment]
I'll try to review this this weekend.

**Review by Gymnasiast — APPROVED** [review]
Code is good.

Could you add a changelog entry?
`Change: [#9568] Change lift sounds of Reverser Roller Coaster and Compact Inverted Coaster to better fitting ones.
Put it between the `Feature` and `Fix` entries.

Replays will need to be rerecorded. @duncanspumpkin could you handle that?

**Comment by tupaschoal** [comment]
Just needs replay rerecording now

**Comment by duncanspumpkin** [comment]
Replay has been rerecorded. You'll need to correct the conflict in the changelog.

**Comment by Gymnasiast** [comment]
@iking96 Could you rebase, rather than merge?

**Comment by iking96** [comment]
> @iking96 Could you rebase, rather than merge?

@Gymnasiast Sorry about that, done!

**Pull request merged**
