### PR TITLE
Platform, memory fixes

### PR DESCRIPTION
**Pull request by janisozaur**
The length decoded does not always equal 24572, sometimes the buffer only has 19072 left available, that's a case at least for:
```
Tracks/Crazy Cabs.TD6
Tracks/Crazy Castle.TD6
Tracks/Crazy Knights.TD6
Tracks/Danglefeet.TD6
Tracks/Demon Drop.TD6
Tracks/Dizzymouse.TD6
Tracks/Evil Vultures.TD6
Tracks/Exterminator.TD6
Tracks/Fright Flight.TD6
Tracks/Fungicide.TD6
Tracks/Garden Golf.TD6
Tracks/Gold Rush.TD6
Tracks/Golden Eagle.TD6
Tracks/Hedgehog.TD6
Tracks/Helixius.TD6
Tracks/Icicle Bob.TD6
Tracks/Ionizer.TD6
Tracks/Jellycopters.TD6
Tracks/Jellyfish.TD6
Tracks/Krypton Dips.TD6
Tracks/Liberty Loop.TD6
Tracks/Lobotomizer.TD6
Tracks/Lunar Launcher.TD6
Tracks/Manic Miner.TD6
Tracks/Mine Mania.TD6
Tracks/Mini Maze.TD6
Tracks/Minidiver.TD6
Tracks/Mummy's Curse.TD6
Tracks/Mystic Flight.TD6
Tracks/Octivator.TD6
Tracks/Pendulator.TD6
Tracks/Pony Tales.TD6
Tracks/Rat Race.TD6
Tracks/Rattlesnake.TD6
Tracks/Raven Racer.TD6
Tracks/Raving Rockets.TD6
Tracks/Red Baron.TD6
Tracks/Roman Racers.TD6
Tracks/Silvertwist.TD6
Tracks/Spiral Hedges.TD6
Tracks/Splashtastic.TD6
Tracks/Steel Squeak.TD6
Tracks/Swither.TD6
Tracks/Toxic Toboggan.TD6
Tracks/Triple Corkscrew.TD6
Tracks/Twicky Twister.TD6
Tracks/Velocerator.TD6
Tracks/Venomous.TD6
Tracks/Wheely Reel.TD6
Tracks/Wicked Whizzer.TD6
Tracks/Wings of Apollo.TD6
```

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
Do these load correctly at present? I didn't just pick that number from the top of my head it is how RCT2 loaded it. I will merge the changes but just wanting to know for interest.

**Comment by janisozaur** [comment]
I will do some more verification of these track designs with the change and report back here, just to be sure.
If 24572 is hardcoded, then perhaps the buffer needs to be larger.

**Comment by duncanspumpkin** [comment]
Did you find any thing weeks out?

**Comment by janisozaur** [comment]
I tested it by loading `Octivator` (of corkscrew type) and saw no defects. Do you think that's enough verification?

Sorry it took so long.

**Comment by janisozaur** [comment]
I can split the commit in two and create another pull req for the fixes only, so this can be tested better, if you want to.

**Pull request merged**
