### PR TITLE
Enable more windows

### PR DESCRIPTION
**Pull request by kmdreko**
3 main changes:
1) Decompiled function at 0x006E7FF3 which subdivides the viewport into sections separated by windows and then updates render blocks accordingly when viewport moves. There's yet another function that is called but has not been decompiled yet.
2) Detached the viewport and window arrays from the static block so that the number of windows could be flexible. (I personally disliked the limit, so i increased the number to ~20) This was only make possible by step 1
3) Not sure if this is filed anywhere. But there was a bug where the park window is not invalidated when its size is changed by switching pages from the bottom banner (guests and park value). In cases where the awards page is relatively long, it would cause a graphical glitch after switching pages

### CODE REVIEW

**Comment by kmdreko** [comment]
There are a few issues with moving the viewport and window arrays out of the static block. A few obscure rendering glitches have occurred. Most likely due to undecomiled references. The world is not ready for this yet.

I'll make a separate pull request just for the decompiled function.

**Comment by kmdreko** [comment]
Also made a mess of my repo/pull request

**Comment by IntelOrca** [comment]
As long as the refs still point to the original memory, there shouldn't any issues, perhaps there was a small mistake with one?

**Comment by kmdreko** [comment]
Indeed, the commit 'revert to old mapping' makes it point back to the original memory instead of being malloc'd. Because, after some testing with, there were some obscure graphical glitches which I assume to stem from still undecompiled references. 

This pull request is ok, but doesn't really do anything beyond change some variables. (But the 'fix park window invalidation ...' commit is a real fix)

**Comment by IntelOrca** [comment]
I see what you mean now, yes we can't use dynamic memory yet for the windows because some of the game logic still calls window invalidate functions (unless we try to hook all the left over calls) - but probably not worth it.

The removals of the RCT2_GLOBALs to the pointers should be safe and are welcome.

**Pull request closed without merging**
