### PR TITLE
Fix: don't show " (DEBUG)" if DEBUG is set but is 0.

### PR DESCRIPTION
**Pull request by jansegre**
Fixes issue #5924.

I've tested it on my Linux x86_64, although it is fairly trivial I'm not familiar with other build systems (Windows) and if the `#if` directive will work the same way there too.

### CODE REVIEW

**Comment by rwjuk** [comment]
Looks good, and doesn't affect compilation on Windows (the issue wasn't present there, but the addition doesn't introduce any issues).

One thing, if you're fixing a specific issue (in this case #5924), your commit message should reflect that, so in this case it should be `Fix #5924: DEBUG suffix on the title screen is always shown`.

**Comment by rwjuk** [comment]
@Gymnasiast Now that is bizarre, and didn't happen for me (on Linux or Windows). I must have been doing something crazy - will retest.

**Comment by rwjuk** [comment]
A better solution here would probably be to change L221 of `CMakeLists.txt` to

```
if(NOT CMAKE_BUILD_TYPE MATCHES RELWITHDEBINFO AND NOT CMAKE_BUILD_TYPE MATCHES RELEASE)
    set(COMMON_COMPILE_OPTIONS "${COMMON_COMPILE_OPTIONS} -DDEBUG=${DEBUG_LEVEL}")
endif()
```

**Comment by Gymnasiast** [comment]
That sounds a bit dirty to me. I'd like to hear @janisozaur 's opinion on this.

**Comment by janisozaur** [comment]
Yep, dirty indeed.

My view on the whole version display thing is it should be limited to `Version.cpp` and only that file. Otherwise whenever you re-run cmake (either explicitly or implicitly) you will end up invalidating caches because you will have changed some define.

**Comment by Gymnasiast** [comment]
@janisozaur Any idea what the OP should do to fix this?

**Comment by IntelOrca** [comment]
I am with @rwjuk on this one, `DEBUG` should not be defined or be set to 0 for release builds.

**Comment by IntelOrca** [comment]
The following seems to work:
```
#if !defined(NDEBUG)
    " (DEBUG)"
#endif
```

**Comment by jansegre** [comment]
Yes, that's strange, I tested it with `DEBUG_LEVEL` set to 0 and then 1,
and then 0 again just to be sure, and it only showed when set to 1. Is it
maybe possible to be the compiler version? I don't trust preprocessor
cross-compatibility too much. I'm using gcc 5 by the way.

I'll amend to include the issue number on the commit message when I get
home.

**Comment by jansegre** [comment]
I went with @IntelOrca's suggestion to use `NDEBUG`, there is [this precedent](https://github.com/OpenRCT2/OpenRCT2/blob/v0.1.0/src/openrct2-ui/drawing/engines/opengl/OpenGLDrawingEngine.cpp#L1064-L1066), so I think it's more OK than an `#if`, though that's the only other place `NDEBUG` was used. This also works for me, the difference is instead of changing the `DEBUG_LEVEL` I have to change the `CMAKE_BUILD_TYPE`.

**Pull request merged**
