### PR TITLE
Update CI images

### PR DESCRIPTION
**Pull request by janisozaur**
I expect failure due to functions deprecated in latest OpenSSL available in Jammy, need to fix that.

### CODE REVIEW

**Comment by janisozaur** [comment]
Eventually need to drop the bionic image as well.

**Comment by janisozaur** [comment]
It depends on https://github.com/OpenRCT2/OpenRCT2/pull/15914 - the CI images will probably get changed there

**Comment by janisozaur** [comment]
As much as I'd love to continue supporting NT5.1 mingw job as something that could potentially run on ReactOS, I think it's time for it to go. The sad truth is those builds were not able to run on such systems for a while, no matter how much we tried to keep our project not polluted with modern symbols, our dependencies haven't been so pristine. The latest bug with those relates to how the static executable gets created and even after solving that issue, there comes another one that isn't ours but a play between freetype and GCC which I'm not interested in solving. NT5.1 is no more.

**Review by IntelOrca — APPROVED** [review]

**Comment by IntelOrca** [comment]
I think it also makes sense to use vcpkg where possible so we don't rely on packages being available in repos and can compile the latest version we need.

**Comment by janisozaur** [comment]
> vcpkg

That's a different story and setting it up with mingw would be another effort. I have to say I actually like being able to compile openrct2 with mingw and pretty much the default packages - I would rather want to upstream libzip than switch to vcpkg, but feel free to provide a separate image to test that way.

**Comment by janisozaur** [comment]
Don't merge just yet. I still need to check something and possibly update names of uploaded binaries

**Comment by IntelOrca** [comment]
> I would rather want to upstream libzip than switch to vcpkg

Why?

**Comment by janisozaur** [comment]
I've gone ahead and changed setting so it doesn't require removed jobs anymore. Once this is in, I will add new jobs as required.

The new builds should be distributed to .org

**Pull request merged**
