### PR TITLE
Implement #1260: Transparent Giant Screenshots

### PR DESCRIPTION
**Pull request by Broxzier**
Evergreen Gardens 2019-05-30 16-42-41
Evergreen Gardens 2019-05-30 16-42-10

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Do we need to make this optional, really?

**Comment by Broxzier** [comment]
Could've phrased it differently if you just want to say you think this should always be enabled. There are two reasons why I chose to make this an option: To give players the ability to keep using how it was with the black background, and to make it easier to extend this further in the future to something like in this PR: https://github.com/OpenRCT2/OpenRCT2/pull/7349

**Comment by Gymnasiast** [comment]
> Could've phrased it differently if you just want to say you think this should always be enabled. 

I'm not sure how else one would interpret my words. If I had something against the feature/enhancement itself, I would have said that.

> To give players the ability to keep using how it was with the black background,

Not a very compelling argument. That could justify making _bug fixes_ optional.

>  and to make it easier to extend this further in the future to something like in this PR: #7349

YAGNI. Though that is at least a case where one might at least want to have some control over what background gets rendered  in giant screenshot.

**Comment by Broxzier** [comment]
This is not a bug fix, but an alteration. The previous behaviour was not considered bad, hence having an option to keep using that seems useful to me. I get that clustering the user interface is not desirable. Would you be okay with this being a hidden option then?

**Comment by Gymnasiast** [comment]
I still think it doesn't really need to be optional.

Hidden options are not that much better - they still clutter the codebase itself. I would leave the option in for now - we can always reconsider it later.

**Comment by janisozaur** [comment]
Having that an option seems a bit weird to me. I like the feature though. How about having another menu entry like 'giant screenshot with transparent background', rather than option? Ideally though, letting the user just select background colour would the best way to approach this issue - with one of the options there explicitly being named "transparent in screenshots".

Btw, do we still have any way of doing BMP screenshots?

**Comment by AaronVanGeffen** [comment]
> How about having another menu entry like 'giant screenshot with transparent background', rather than option?

I think that's a little overkill. More intrusive than having the option as-is, tbh.

> Ideally though, letting the user just select background colour would the best way to approach this issue - with one of the options there explicitly being named "transparent in screenshots".

Agreed. This is what @Broxier was doing in #7349 — something we may yet see in a future PR.

> Btw, do we still have any way of doing BMP screenshots?

I don't think we do.

**Comment by Gymnasiast** [comment]
> Btw, do we still have any way of doing BMP screenshots?

I took out that code a few years ago.

**Pull request merged**
