### PR TITLE
Lua scripting test

### PR DESCRIPTION
**Pull request by frutiemax**
I first tested ride painting scripting with DukTape but couldn't get good performance. In this PR, I'm now testing LuaJit for the ride painting. I can get the 60 FPS with many ride instances. There is some performance overhead when comparing to C++ code, but it seems to be maintainable.

image

The script looks like this for now:
```
--[[
 * Copyright (c) 2014-2022 OpenRCT2 developers
 *
 * For a complete list of all authors, please refer to contributors.md
 * Interested in contributing? Visit https://github.com/OpenRCT2/OpenRCT2
 *
 * OpenRCT2 is licensed under the GNU General Public License version 3.
--]]

 TrackMap3x3 = {
	[0]={ [0] = 0, 1, 2, 3, 4, 5, 6, 7, 8 },
		{ [0] = 0, 3, 5, 7, 2, 8, 1, 6, 4 },
		{ [0] = 0, 7, 8, 6, 5, 4, 3, 1, 2 },
		{ [0] = 0, 6, 4, 1, 8, 2, 7, 3, 5 }
}

EDGE_NE = 1
EDGE_SE = 2
EDGE_SW = 4
EDGE_NW = 8
EDGE_BOTTOMLEFT = EDGE_SW
EDGE_BOTTOMRIGHT = EDGE_SE
EDGE_TOPLEFT = EDGE_NW
EDGE_TOPRIGHT = EDGE_NE

Edges3x3 = {
	[0] = 0,
	bit32.bor(EDGE_NE, EDGE_NW),
	EDGE_NE,
	bit32.bor(EDGE_NE, EDGE_SE),
	EDGE_NW,
	EDGE_SE,
	bit32.bor(EDGE_SW, EDGE_NW),
	bit32.bor(EDGE_SW, EDGE_SE),
	EDGE_SW
}

SCHEME_TRACK = 0
SCHEME_SUPPORTS = 1
SCHEME_MISC = 2
SCHEME_3 = 3

SPR_FLOOR_CORK_SE_SW = 22134
SPR_FLOOR_CORK_SW = 22135
SPR_FLOOR_CORK_SE = 22136
SPR_FLOOR_CORK = 22137

FloorSpritesCork = {
	[0] = SPR_FLOOR_CORK_SE_SW,
	SPR_FLOOR_CORK_SW,
	SPR_FLOOR_CORK_SE,
	SPR_FLOOR_CORK
}

SPR_FENCE_ROPE_NE = 22138
SPR_FENCE_ROPE_SE = 22139
SPR_FENCE_ROPE_SW = 22140
SPR_FENCE_ROPE_NW = 22141

FenceSpritesRope = {
	[0] = SPR_FENCE_ROPE_NE,
	SPR_FENCE_ROPE_SE,
	SPR_FENCE_ROPE_SW,
	SPR_FENCE_ROPE_NW
}

RIDE_LIFECYCLE_ON_TRACK = 1

SEGMENT_B4 = bit32.lshift(1, 0)
SEGMENT_CC = bit32.lshift(1, 1)
SEGMENT_BC = bit32.lshift(1, 2)
SEGMENT_D4 = bit32.lshift(1, 3)
SEGMENT_C0 = bit32.lshift(1, 4)
SEGMENT_D0 = bit32.lshift(1, 5)
SEGMENT_B8 = bit32.lshift(1, 6)
SEGMENT_C8 = bit32.lshift(1, 7)
SEGMENT_C4 = bit32.lshift(1, 8)

SEGMENTS_ALL = bit32.bor(SEGMENT_B4, SEGMENT_CC, SEGMENT_BC, SEGMENT_D4, SEGMENT_C0, SEGMENT_D0, SEGMENT_B8, SEGMENT_C8, SEGMENT_C4)

function PaintCircusTent(session, ride, direction, al, cl, height)
	local rideEntry = ride:GetRideEntry()
	local vehicle = ride:GetVehicle(0)
	local lifecycleFlags = ride:GetLifecyleFlags()
	local flags = bit32.band(lifecycleFlags, RIDE_LIFECYCLE_ON_TRACK)
	if (flags ~= 0) then
		session:SetAsActiveEntity(vehicle)
	end

	local imageTemplate = ImageId.new(0, ride:GetVehicleBodyColour(0), ride:GetVehicleTrimColour(0))
	local imageFlags = session:GetTrackColour(SCHEME_MISC)
	if (imageFlags:IsRemap() == false) then
		imageTemplate = imageFlags
	end

	local car = rideEntry:GetCarEntry(0)
	local imageIndex = car:GetBaseImageId() + direction

	local imageTemplateIndex = imageTemplate:WithIndex(imageIndex)
	local offset = CoordsXYZ.new(al, cl, height)
	local bbOffset = CoordsXYZ.new(al + 16, cl + 16, height + 3)
	local bbLength = CoordsXYZ.new(24, 24, 47)
	local bb = BoundBoxXYZ.new(bbOffset, bbLength)

	PaintAddImageAsParent(session, imageTemplateIndex, offset, bb)
	session:SetInteractionTypeToRide()
end

function PaintCircus()
	local session = Paint.Session
	local height = Paint.Height
	local direction = Paint.Direction
	local ride = Paint.Ride
	local trackSequence = Paint.TrackSequence
	local trackElement = Paint.TrackElement

	trackSequence = TrackMap3x3[direction][trackSequence]
	local edges = Edges3x3[trackSequence]

	local imageId = session:GetTrackColour(SCHEME_MISC)
	WoodenASupportsPaintSetup(session, bit32.band(direction, 1), 0, height, imageId);

	stationObject = ride:GetStationObject()
	imageId = session:GetTrackColour(SCHEME_TRACK)

	TrackPaintUtilPaintFloor(session, edges, session:GetTrackColour(SCHEME_TRACK), height, FloorSpritesCork, stationObject)
	TrackPaintUtilPaintFences(session, edges, session.MapPosition, trackElement, ride, session:GetTrackColour(SCHEME_SUPPORTS),
		height, FenceSpritesRope, session.CurrentRotation)

	local coords = {
		[1] = {32, 32},
		[3] = {32, -32},
		[5] = {0, -32},
		[6] = {-32, 32},
		[7] = {-32, -32},
		[8] = {-32, 0},
	}
	local myCoords = coords[trackSequence]

	if (myCoords ~= nil) then
		PaintCircusTent(session, ride, direction, myCoords[1], myCoords[2], height)
	end

	local cornerSegments = nil
	local sequenceSegment = {
		[1] = bit32.bor(SEGMENT_B4, SEGMENT_C8, SEGMENT_CC),
		[3] = bit32.bor(SEGMENT_CC, SEGMENT_BC, SEGMENT_D4),
		[6] = bit32.bor(SEGMENT_C8, SEGMENT_B8, SEGMENT_D0),
		[7] = bit32.bor(SEGMENT_D0, SEGMENT_C0, SEGMENT_D4)
	}
	cornerSegments = sequenceSegment[trackSequence]
	if (cornerSegments == nil) then
		cornerSegments = 0
	end

	PaintUtilSetSegmentSupportHeight(session, cornerSegments, height + 2, 0x20)
	PaintUtilSetSegmentSupportHeight(session, bit32.band(SEGMENTS_ALL, bit32.bnot(cornerSegments)), 0xFFFF, 0)
	PaintUtilSetGeneralSupportHeight(session, height + 128, 0x20)
end

PaintCircus()
```
[circus_paint_2.zip](https://github.com/OpenRCT2/OpenRCT2/files/10326391/circus_paint_2.zip)

### CODE REVIEW

**Comment by Gymnasiast** [comment]
We have discussed this in the team chat. The outcome is that we don’t want to use scripting to draw rides, certainly not simple ones like the circus. Rather, we want to make this kind of thing possible via the object system. Besides performance and maintainability, it is also a matter of portability: we want objects to always work and be bundled with saves, which is not something we can properly pull off if plugins are needed to draw.

So sadly, I’ll have to close this.

**Comment by frutiemax** [comment]
The painting script is not a plugin, it is bundled inside a Paint object and is portable across systems. The argument of the always working save file is the same with a badly generated json file. The only thing I agree with is performance and maintability, it will always be faster to read a json, generate a Paint object in C++ and using it instead of using a scripting system. The scripting API also introduces a lot of code on its own that might not follow up the code base changes. The whole PR was also just an experiment just to test out the performance overhead of a scripting system when compared to native code.

**Comment by IntelOrca** [comment]
Currently your script is 1:1 with the original paint code. Even if you were to still script the paint code, the API should be much simpler. A Circus ride could be done with just some JSON like:
```json
    "cols": "3",
    "rows": "3",
    "base": "cork",
    "structures": [
        {
            "imageId": 0,
            "x": 32,
            "y": 32,
            "bbWidth": 24,
            "bbHeight": 24,
            "bbX": 16
            "bbY": 16
            "bbZ": 3
        }
    ]
```

Things to think about are how it can do most of those paint calls from just the most minimal JSON like the example above and whether extra JSON is needed to provide more control over different rotations and remapping.

But something like the floor and supports are going to be almost the same across all flat rides. We already have got common utility methods for paint those things, but ideally even the calls to those should not be necessary.

**Comment by IntelOrca** [comment]
The other thing that came to mind is how you would script ride logic. Take haunted house for example. That needs to play an animation and scream sound effect every so often. Any state kept by the script needs to be simple enough so that it can be stored in the save file. So if we a very small subset of commands that could perform this logic and read/write simple state bytes or flags, this would work - and could be written in the form of JSON. But the JSON could be generated from something else, such as a script.

**Comment by spacek531** [comment]
> Any state kept by the script needs to be simple enough so that it can be stored in the save file. So if we have a very small subset of commands that could perform this logic and read/write simple state bytes or flags, this would work - and could be written in the form of JSON. But the JSON could be generated from something else, such as a script.

Flat rides use the sub_state (uint8_t) and current_time (uint16_t) to store state values. They use pitch and roll to send data to paint code.

**Comment by IntelOrca** [comment]
> Flat rides use the sub_state (uint8_t) and current_time (uint16_t) to store state values. They use pitch and roll to send data to paint code.

This could be changed to lets say 32 (or however much we allow) available bytes for flat ride logic to use as state storage.

**Comment by spacek531** [comment]
32 bytes per vehicle seems like a lot. Regarding behavior-in-config, this discussion has a path forward: https://github.com/OpenRCT2/OpenRCT2/discussions/18967

**Comment by IntelOrca** [comment]
> 32 bytes per vehicle seems like a lot. Regarding behavior-in-config, this discussion has a path forward: #18967

I am not talking about vehicles, I am talking about rides, flat rides in particular.

**Comment by spacek531** [comment]
> > 32 bytes per vehicle seems like a lot. Regarding behavior-in-config, this discussion has a path forward: #18967
> 
> I am not talking about vehicles, I am talking about rides, flat rides in particular.

Ok so the bytes would be part of ride it sounds like. The flat ride state vars I mentioned earlier are all vehicle propeties.

**Pull request closed without merging**
