### PR TITLE
update spacek531 contributions

### PR DESCRIPTION
**Pull request by spacek531**

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Didn't you do the title sequences for 0.0.6 and 0.0.7 as well?

**Comment by spacek531** [comment]
0.0.6 and 0.0.7 do not have unique title sequences, they use the 0.0.5 sequence.

**Comment by Gymnasiast** [comment]
Which still means you made them.

```
title sequences for 0.0.4, 0.0.5/0.0.6/0.0.7 and 0.1.0; title sequences using milliseconds
```

**Comment by spacek531** [comment]
I suppose that works

**Pull request merged**
