### PR TITLE
Fix #3749: Block Brake Issue when Run on Continous Non-block

### LINKED ISSUE #3749: Block Brake Issue when Run on Continous Non-block
https://openrct2.org/forums/topic/1306-block-brake-issue-when-run-on-continous-non-block/

giraty

> I recently notice something strange within OpenRCT2. I sometimes use block brakes on a continous circuit non-block brakes mode to "defy" the brakes failure. On the vanilla RCT2, the block brakes will simply brakes the train as normal with target 4 mph. But on my OpenRCT2 v0.0.4 I notice on continous non-block brakes mode, the block brakes will stop a train when there's a train located after the block brakes.
> 
> As you see in the picture, the next trains are held up by the block brakes even on the continous circuit which should only happened when continous with block sectioned is selected.
> 
> Regards.

### PR DESCRIPTION
**Pull request by gDanix**
Fix bug causing block brakes blocking vehicles in non-block mode

### CODE REVIEW

**Comment by gDanix** [comment]
I'd like, after this solution is validated, to refactor sub_6DAB4C_chunk_2() to make it more readable.

**Comment by IntelOrca** [comment]
@gDanix I'd do the refactor separately from the bug fix.

**Comment by gDanix** [comment]
@IntelOrca Ok

Well, then I'll be removing WIP because, if the solution is correct, this can be merged.

**Comment by duncanspumpkin** [comment]
Solution is correct. I had a slightly different solution but this is more elegant. Mistake was made by assuming the continuous circuit code branched to the same location as block mode.

**Pull request merged**
