### PR TITLE
Correct typos and American English

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by wolfblake** [comment]
I don't think that we should use anticlockwise for american english.

**Comment by Gymnasiast** [comment]
And how exactly is english_uk.txt supposed to be American English?

**Comment by wolfblake** [comment]
Sorry, I read the commit and saw american english

**Comment by Gymnasiast** [comment]
The problem is that someone used American English in the UK English file. That's what's fixed here.

**Comment by duncanspumpkin** [comment]
Can you rebase to develop so I can merge without any effort.

**Pull request closed without merging**
