### PR TITLE
Park validation

### PR DESCRIPTION
**Pull request by janisozaur**
Since we have so many invalid parks popping up here and there, I thought we could use some validation.

This is work-in-progress which I submit for discussion before I go to far with design of that.

To use:

```
$ ./openrct2 validate-only data/title/openrct2/achilleshiel.sv6
ERROR[/home/janisozaur/workspace/OpenRCT2/src/peep/peep.c:9517 (validate_peep)]: unknown peep item_extra_flags: 0xffff00ef for peep 0x10ed0bc
ERROR[/home/janisozaur/workspace/OpenRCT2/src/peep/peep.c:9517 (validate_peep)]: unknown peep item_extra_flags: 0xffffffff for peep 0x10eccbc
ERROR[/home/janisozaur/workspace/OpenRCT2/src/peep/peep.c:9517 (validate_peep)]: unknown peep item_extra_flags: 0xffffffff for peep 0x10eb9bc
$ ./openrct2 validate-only data/title/openrct2/mci.sv6
<no errors reported so far>
```

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
What would be super useful would be to check all track tiles making sure the track type is a valid type for that ride type.

**Comment by janisozaur** [comment]
I wish to add more check/fixers in here, but do you like the looks of it so far?

If you have ideas what else can I check and give me some pointers to code, please do leave a comment.

**Comment by duncanspumpkin** [comment]
I've never personally come accross a peep with invalid flags and I really doubt it would cause any issues but no real harm in checking that. I like the idea it would certainly help with the corrupted maps people manage to produce. The suggestion I have about track types is needed as there is a multiplayer bug right now that sometimes occurs where the host ends up with a different ride type to the client which causes a crash when viewing invalid tracks.

**Comment by Gymnasiast** [comment]
@janisozaur : Are you still working on this?

**Comment by janisozaur** [comment]
I think it is still valuable and I will try to work on it, time allowing.

Main reason for this change, is to have one function that could do all the sanity checks instead of having to go through all the options manually and hoping everything was covered.

**Comment by mrtnptrs** [comment]
Is this still needed as we now have implemented several options to fix some broken maps? @janisozaur And are you planning to work on this? :)

**Comment by janisozaur** [comment]
This will be nice to have, but it's not gonna happen in foreseeable future, so closing.

**Pull request closed without merging**
