### PR TITLE
Fix #18911: Update mini golf fencing to draw correctly from all angles

### LINKED ISSUE #18911: Visibility of mini golf's station railings depends on view direction
### Operating System

Ubuntu 20.04

### OpenRCT2 build

Uknown #12909

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

Normally, the station platform of the mini golf draws railings on both sides. But, of course, you need a gap in the railings where the entrance and exit are.

But this isn't working quite right. When viewed from two angles, *both* sides of the station platform are missing the railings. When viewed from the other two angles, both sides do have the railings.

Like this:
Octagon Park 2022-12-21 19-22-00
Octagon Park 2022-12-21 19-21-58
Octagon Park 2022-12-21 19-21-57
Octagon Park 2022-12-21 19-21-54

The issue becomes more obvious if you use the 'no entrance' station type:
Octagon Park 2022-12-21 19-22-14
Octagon Park 2022-12-21 19-22-13
Octagon Park 2022-12-21 19-22-12
Octagon Park 2022-12-21 19-22-11

To be done correctly, it should *always* omit the railing on the side the entrance or exit is on, and *never* omit the railing on the side across from the entrance/exit.

I think this is a pretty old bug, because I remember having seen oddities in the mini golf station railings for quite a while ... but only recently realized that it actually depends on the view direction, which means it's *definitely* a drawing bug.

### Steps to reproduce

1: Build a mini golf station platform at least 3 tiles long, and place the entrance and exit on the same side of it (not across from each other).
2: (Optional) set the station to 'no entrance' style for better visibility.
3: Rotate the view and pay attention to the railings on the station platform.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by mdbckrtn**
SW and SE facing fences were not being drawn correctly due to (seemingly) a typo that caused the game to only check for NW and NE facing fencing when setting up fences for drawing. Ensuring `PaintMiniGolfStation` checks all four angles resolves the issue.

This PR resolves issue #18911 

angle1
angle2
angle3
angle4

### CODE REVIEW

**Review by tupaschoal — COMMENTED** [review]
Code changes look ok and tests show the behavior is correct now. Can you please add a changelog entry for this fix?

**Comment by mdbckrtn** [comment]
> Code changes look ok and tests show the behavior is correct now. Can you please add a changelog entry for this fix?

Good to go 👍

**Review by tupaschoal — COMMENTED** [review]
Seems like there is still a leftover change on `.vscode/launch.json`, can you revert that, please?

**Comment by mdbckrtn** [comment]
> Seems like there is still a leftover change on `.vscode/launch.json`, can you revert that, please?

Ah, right. Addressed.

**Review by tupaschoal — APPROVED** [review]

**Comment by tupaschoal** [comment]
Thanks!

**Pull request merged**
