### PR TITLE
Fix crash when switching ride types with construct window open

### PR DESCRIPTION
**Pull request by duncanspumpkin**

### CODE REVIEW

**Comment by tupaschoal** [comment]
Should this be on the changelog @duncanspumpkin ?

**Comment by duncanspumpkin** [comment]
yeah probably. I'm thinking that maybe this isn't the best fix. It stops the crash but its not great.

**Comment by tupaschoal** [comment]
Should we hold it for now?

**Comment by duncanspumpkin** [comment]
I think it's probably fine

**Pull request merged**
