### PR TITLE
Handle touch drag on viewports, fixes #2091

### LINKED ISSUE #2091: Touch screen compatibility
Could a checkbox be added to the options menu that changes the drag function to left click? I'm playing rct2 on a touchscreen (it's a lot of fun) and the only drawback right now is I need the map to move around effectively.

### PR DESCRIPTION
**Pull request by samdroid-apps**
This commit makes it possible to drag a viewport around with touch.
The user can drag if they start without a ride, shop, etc under
their touch.  This reuses the code of the right mouse button viewport
movement, although adding a new flag to indicate touch behavious
(as well as not relying on moving the cursor).

### CODE REVIEW

**Comment by IntelOrca** [comment]
Wouldn't this be more suited for when you move two fingers around?

**Comment by samdroid-apps** [comment]
Yep, I tested that.  The result conflicted very much with the zoom, resulting in a unusable experience.  It probably needs more testing and investigating to get it working nice with the zoom.

In my view, panning with one finger is quite natural, eg. most mapping applications.  This patch also makes sure not to start a drag when the touch could be interacting with something on the map, so it only works if you start in a non clickable section.

**Comment by marijnvdwerf** [comment]
Wouldn't it make more sense to only interact with something on `touchend`? And only if the cursor hasn't moved `x` pixels (after which panning starts). Would be in line with Android, iOS and OS X behavior.

**Comment by samdroid-apps** [comment]
That's an awsome idea mate!  I'll play around with implementing it.  Any suggestions for the vue of `x`?

**Comment by marijnvdwerf** [comment]
[Android uses 8 points/density independent pixels](http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/5.1.1_r1/android/view/ViewConfiguration.java#line-129). Might be a good start?

**Pull request closed without merging**
