### PR TITLE
Fix #14710: Preview not shown without enough money

### LINKED ISSUE #14710: Ride/Track designs preview not shown without enough money
**Version:** 0.2.2+

Ride/Track design previews are not visible when the player has not enough money to build.

Prior to version 0.2.2 it was doing this:
openrct2_2021-05-21_20-09-4906d31e5b9df778f08

Now it does this:
openrct2_2021-05-21_20-10-370b4903f07f793200e

### PR DESCRIPTION
**Pull request by ZehMatt**
Closes #14710

### CODE REVIEW

**Review by tupaschoal — APPROVED** [review]
I'm wondering if the network bump was really needed, but since erring on the conservative side is not a problem, I'm alright with this.

**Comment by ZehMatt** [comment]
> I'm wondering if the network bump was really needed, but since erring on the conservative side is not a problem, I'm alright with this.

Its potentially not needed but I'm not too confident that this wont diverge on the server somehow, a network bump is free.

**Comment by tupaschoal** [comment]
Yeah, that's what I though too

**Review by Gymnasiast — APPROVED** [review]
Needs rebase.

**Pull request merged**
