### PR TITLE
Split TileElement and RCT12TileElement

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Hmm. I realise the TileElement implementation might change, but preferably, `RCT12TileElement` should inherit its methods from `TileElement` and only redefine the ones that should have a different implementation, I think. Right now, you're seeing loads of code duplication.

**Comment by Gymnasiast** [comment]
This is in preparation for changing the tile elements over to the new save format. I was specifically asked to backport it to avoid a gigadiff. So no, the elements should be completely independent, even though their implementation is currently the same.

**Comment by IntelOrca** [comment]
Yes inherit wouldn't work later when we change the OpenRCT2 struct completely. What you could do though is have RCT1 and RCT2 sub classes for a common RCT1/2 base.

**Comment by IntelOrca** [comment]
I think all the fields in the struct should be private since you have getter methods for everything.

**Comment by Gymnasiast** [comment]
Does that really matter, though? They'll be used only for importing RCT1/RCT2 saves.
(I will change it if you really want me to.)

**Comment by Gymnasiast** [comment]
I tried loading a few saves. Besides a hacked park that used another iteration of 8 cars' corrupt element, there seemed to be no issues (or at least none introduced by this PR).

I have also modified the fields of RCT12TileElement to make them private.

**Pull request merged**
