### PR TITLE
Cheat window updates (weather dropdown, a UI gap removed)

### PR DESCRIPTION
**Pull request by octaroot**
> Note: Because of the mess I made when merging instead of rebasing (#2829), I cloned this repo again, created a new branch, cherrypicked my commits and well, here we are :-) Thanks for the help guys!

Original PR:
I wanted to contribute not just by translating, but also coding. So I looked around the wiki and I found a page named [Features to implement](../wiki/Features-to-implement), that mentioned the weather cheats should be refactored to use a dropdown menu. And I did exactly that.

I also fixed the gap that was present on the financial cheats tab.

### CODE REVIEW

**Comment by janisozaur** [comment]
@octaroot you don't have to create another PR, just use `push --force` to replace contents of remote branch with non-mergeable commits.

Can you please update your commit message so that it displays correctly in oneline format? See http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html.

**Comment by octaroot** [comment]
@janisozaur I see. Creating another PR was advised in the comments. Messages updated.

**Comment by janisozaur** [comment]
Tested, :+1:.

**Comment by duncanspumpkin** [comment]
@janisozaur in this case since it was on a different branch it is much easier to make it a new or. Either way thanks for testing.

**Pull request merged**
