### PR TITLE
Remove support for BMP screenshots

### PR DESCRIPTION
**Pull request by Gymnasiast**
It has been a hidden setting for some time. Since PNG is way more useful and support has been readily available since the early 2000s, time to clean up a bit.

### CODE REVIEW

**Comment by IntelOrca** [comment]
What about `image_io_bmp_write`?

**Comment by Gymnasiast** [comment]
Removed that as well.

**Comment by IntelOrca** [comment]
I'd probably update the changelog.

**Comment by Gymnasiast** [comment]
Done.

**Pull request merged**
