### PR TITLE
Remove Duplicated Preprocessor Macro Definition

### PR DESCRIPTION
**Pull request by ACGNnsj**
Compiler warning C4005 occurred when compiling the project by cl from VS2022 (MSVC v14.34.31933).
And it worked after removing the duplicated preprocessor macro definition of _USE_MATH_DEFINES which already defined in src/openrct2/common.h and SDL2/SDL_stdinc.h

image

image

### CODE REVIEW

**Review by duncanspumpkin — APPROVED** [review]

**Comment by duncanspumpkin** [comment]
Could you check see if we can just remove it from common.h as well. I'm not convinced we even use it.

**Comment by Broxzier** [comment]
Sounds like a good idea to move away from using the math defines if we use them anyway, and move over to constexpr constants.

**Comment by duncanspumpkin** [comment]
> Sounds like a good idea to move away from using the math defines if we use them anyway, and move over to constexpr constants.

Annoyingly the C++ ones are C++20. But can just define our own set if we are even using them (which I'm not convinced we are)

**Comment by ACGNnsj** [comment]
> Could you check see if we can just remove it from common.h as well. I'm not convinced we even use it.

Yeah, it seems to work quite well so.

image

**Comment by duncanspumpkin** [comment]
> > Could you check see if we can just remove it from common.h as well. I'm not convinced we even use it.
> 
> Yeah, it seems to work quite well so.
> 
> image

Remove it from common then as well.

**Comment by ACGNnsj** [comment]
> > > Could you check see if we can just remove it from common.h as well. I'm not convinced we even use it.
> > 
> > 
> > Yeah, it seems to work quite well so.
> > image
> 
> Remove it from common then as well.

No problem. And I've finished it now. 🙂

**Review by duncanspumpkin — APPROVED** [review]

**Pull request merged**
