### PR TITLE
Remove buffer size limit of assert messages

### PR DESCRIPTION
**Pull request by Broxzier**

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Any background/clarification on this?

**Comment by Broxzier** [comment]
Just more flexibility with what can be inside the message, instead of it being cut off at 512 characters. When the message contains full version information and absolute paths to objects, the limit could be reached.

**Review by Gymnasiast — APPROVED** [review]

**Comment by CookiePLMonster** [comment]
Can `formattedMessage` contain an UTF-8/localized string?

**Comment by Gymnasiast** [comment]
Yes, for example in the path names. I just noticed we’re using the ANSI variant of the call without properly setting the code page to UTF-8 (65001).

**Comment by CookiePLMonster** [comment]
That codepage is Windows 10 only, so in this case it's better to just go the traditional "convert to wide char" route.

**Pull request merged**
