### PR TITLE
Move gExpenditureTable to GameState_t

### PR DESCRIPTION
**Pull request by Harry-Hopkinson**
Move gExpenditureTable to GameState_t for https://github.com/OpenRCT2/OpenRCT2/issues/21193

### CODE REVIEW

**Review by duncanspumpkin — APPROVED** [review]

**Review by Gymnasiast — APPROVED** [review]

**Comment by Gymnasiast** [comment]
@Harry-Hopkinson Could you rebase this?

**Comment by Gymnasiast** [comment]
Looks like you have some trouble rebasing? We can help you via Discord, if needed.

**Comment by Harry-Hopkinson** [comment]
@Gymnasiast Thanks for the offer - I will take another crack at it.

**Comment by Harry-Hopkinson** [comment]
Should I just close this? There are too many conflicts due to the cheats being moved into the GameState file.

**Comment by Harry-Hopkinson** [comment]
Thanks.

**Comment by Harry-Hopkinson** [comment]
Thank you for doing that, I just could not figure out how to do it.

**Comment by Gymnasiast** [comment]
Next time, just go onto Discord and ask us. I’m sure you can learn it without too much difficulty.

**Pull request merged**
