### PR TITLE
Raise max number of park entrance objects to 255

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
Per request. Useful for making workbenches, apparently.

### CODE REVIEW

**Comment by ZeeMaji** [comment]
The window for placing park entrances only seems to support four entries.
Screenshot at 2024-12-15 13-48-00

**Comment by ZeeMaji** [comment]
I can still select the fifth entrance style by clicking the very edge of the list, so perhaps it just needs a scroll wheel added to it.

**Comment by AaronVanGeffen** [comment]
Oh, heh, looks like the window doesn't have a ScrollGetSize event. I'll implement it.

**Comment by AaronVanGeffen** [comment]
There, all better:
Screenshot 2024-12-15 at 20 13 00

I'll make the window resizeable as well.

**Comment by ZeeMaji** [comment]
Seems to be working as expected, i also just to be sure tested exporting & importing the park and all the park entrance objects imported as expected.
Screenshot at 2024-12-15 16-28-14
ZeeMaji Workbench 2024 2024-12-15 16-28-26

**Comment by ZeeMaji** [comment]
You will probably want to raise the park versions and such? Trying to load a park with more than 4 entrance objects on older versions of the game will make all of the entrances beyond 4 invisible.

**Comment by AaronVanGeffen** [comment]
While that technically would warrant a park version bump, it's such an edge case that I'm not sure it's worth it. Especially considering we'll be bumping it for other reasons soon, anyway.

**Comment by ZeeMaji** [comment]
Well, if you insist.

**Review by ZeeMaji — APPROVED** [review]

**Comment by AaronVanGeffen** [comment]
> It works on older versions but some things will be missing. That in my opinion warrants a soft-bump, so it can give a proper warning.

Alright, I guess a soft bump is warranted indeed. Bumped the version number in the latest commit.

**Review by Gymnasiast — APPROVED** [review]

**Pull request merged**
