### PR TITLE
Fix: #13292: Impossible excitement rating requirements...

### PR DESCRIPTION
**Pull request by evilclownattack**
Incorrect argument was used when drawing the minimum excitement rating in the Objective Selection window. Appears to have been a typo.

### CODE REVIEW

**Review by tupaschoal — APPROVED** [review]
This looks ok to me, though I think using the default instead of naming the type is something we should tend to later on.

**Comment by tupaschoal** [comment]
Please add a changelog entry.

@Gymnasiast , can you please review it? Seems to have been caused by https://github.com/OpenRCT2/OpenRCT2/commit/6e22eade675117e19f4c905af9800568d460673b

**Comment by evilclownattack** [comment]
Should I add any fixes to the changelog when first submitting a pull request in the future?

**Comment by tupaschoal** [comment]
It depends, we only add stuff to changelog if it changes the behavior from what was seen in the last release (fix a bug, enhancement, feature, etc...)

**Review by Gymnasiast — CHANGES_REQUESTED** [review]
Could you create a new case label for the "finish 5 coasters" objective and revert the default label to what it was?

**Review by Gymnasiast — APPROVED** [review]

**Pull request merged**
