### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by janisozaur**
A bunch of small fixes

### CODE REVIEW

**Comment by IntelOrca** [comment]
What is the point in setting buffer to NULL before it returns? There is also a macro for that anyway called SafeFree (although that also checks if its NULL first before freeing it)

**Comment by janisozaur** [comment]
To make sure if ever leak the pointer elsewhere (by forgetting to free it or returning from function or returning said pointer…), it will a) not cause double free b) possibly be caught in next reference to that pointer. There is no point in checking if pointer is null prior to freeing it, as free() [handles that case as no-op](http://www.cplusplus.com/reference/cstdlib/free/).

**Comment by janisozaur** [comment]
Would you rather like me to use `SafeFree`?

**Comment by IntelOrca** [comment]
Yea, use SafeFree and you can also remove the NULL check from SafeFree.

**Comment by janisozaur** [comment]
done

**Pull request merged**
