### PR TITLE
Fix #8142: Freeze reliability of unbreakable rides to 100%

### LINKED ISSUE #8142: Reliabiility of mazes and crooked houses can go below 100%
**OS:** GNU/Linux
**Version:** 0.2.1

The displayed reliabiility (not the real reliability) of mazes and crooked houses can go below 100% although these attractions never break.

- [ ] Reproducible in RCT2 (vanilla)? I don't know. Maybe.
- [ ] Specific to multiplayer? No.

**Steps to reproduce:**
1. Build a maze and a crooked house
2. Open them and let guests in
3. Play for a long time

Effect: The reliability level will slowly decline (down to 0%, eventually) although these attractions never break.

Expected effect: Since these attractions can't break down, I expect the reliability to stay at 100% forever. It's as if they have an “intrinsic” 100% reliability.

Fun fact: Refurbishing is disabled for these attractions. So to bring up reliability back to 100%, you have to bulldoze the attraction and rebuild it. xD

### PR DESCRIPTION
**Pull request by felixpelletier**
#8142 
It is my understanding that the "RIDE_ENTRY_FLAG_CANNOT_BREAK_DOWN" flag is not the sole "unbreakable" indicator (it doesn't seem to be set for mazes for example). 
We need to check that there are no breakdowns available.

I don't know the "legacy data" part of the game. Whould it be sufficient to only check for RideAvailableBreakdowns?

### CODE REVIEW

**Comment by jensj12** [comment]
Wouldn’t it be a better idea to set the flag properly in the objects? Or even auto-set it if there are no available breakdowns?

**Comment by Gymnasiast** [comment]
@jensj12 There is no need for that. There are only two places to check. And if you need to check multiple times, it should be spun off into a function.

**Comment by felixpelletier** [comment]
First: So it is, sorry for that. Will run the check on my side before committing next time. Correcting it right away. (btw, is there a list of things to run before committing somewhere that I didn't catch?)
Second: The first iteration of the fix did just that, never allowing it to drop. But then if the player loads an old save with some ride's reliability set at a value below 100, it will just stay at that value. Is that generally acceptable?

"...on the ride type (for the maze)...": You mean that it is generally known that a maze doesn't break, or that there is a special flag somewhere? Is the "ride_can_break" function correct?

**Comment by Gymnasiast** [comment]
1. Aside from `git clang-format` and testing it yourself, there isn't much you can do here.
2. It's even acceptable if it doesn't get fixed at all, really. Calling it a bug is even a stretch.
2. The function looks correct. While we're add it, can you change it into a struct method? (`CanBreakDown()`)

**Comment by felixpelletier** [comment]
3. On the Ride class you mean? I could do that, but it seems inconsistant with the rest of the code... I guess that's one step forward towards a more C++-esque codebase.

**Comment by Gymnasiast** [comment]
The format_string stuff should indeed be spun off. PR (and preferably commits, but that's ok here) should address one thing.

**Comment by felixpelletier** [comment]
Made PR #8196 for format_string. Will rebase when it's merged.

**Comment by jensj12** [comment]
Maybe use RideCanBreakdown for deciding whether a ride can be refurbished? Prevents one line of duplicate code for checking the available breakdowns.

**Comment by Gymnasiast** [comment]
@jensj12 That's for another PR.

**Comment by felixpelletier** [comment]
Done!

**Pull request merged**
