### PR TITLE
Refactor sprite_flags

### PR DESCRIPTION
**Pull request by duncanspumpkin**
I think var_0C of the sprite structure is sprite_flags. This refactors the peep list_flags into this new sprite_flags. The only minor issue is vehicle entries also have a sprite_flags. Any suggestions of a better name?

### CODE REVIEW

**Comment by IntelOrca** [comment]
If sprite was renamed to object, this would be object flags. But for vehicle entry, would it stay as sprite_flags? is the sprite_flags on vehicle entry actually related to the images or just the vehicle objects?

**Comment by duncanspumpkin** [comment]
The vehicle entry ones are about which sprites are available `VEHICLE_SPRITE_FLAG_FLAT_BANKED` and such.

**Comment by IntelOrca** [comment]
what is the difference between flags and sprite_flags then?

**Comment by duncanspumpkin** [comment]
there are flags for litter and flags for peeps that would cause a conflict if i renamed it flags. I could rename them to litter_flags and peep_flags.

**Comment by IntelOrca** [comment]
Yeah I guess just do that or something for now. Either is better than what it currently is.

**Comment by duncanspumpkin** [comment]
Okay I've relabelled it so that sprite flags is now just flags and the peep and jumping fountain flags are peep_flags and fountain_flags.

**Comment by IntelOrca** [comment]
So is flags (var_0C) used for some common flags between different sprite types?

**Comment by duncanspumpkin** [comment]
@IntelOrca I don't think so but I think it must have been designed like that. All of the common sprite variables are in that first set.

**Pull request merged**
