### PR TITLE
Fixed #1948

### LINKED ISSUE #1948: Non-host can't change ride fees
[MULTIPLAYER]

When in multiplayer a non-host player attempts to change a ride's admission fee, the game spits out a ~~"Can't rename ride/attraction"~~ error based on the last action and for the host it displays ~~"Can't open"~~ also just an error based on last action.

### PR DESCRIPTION
**Pull request by nightroan**
There's a 'enum' collision of GAME_COMMAND_FLAG_NETWORKED and MONEY32_UNDEFINED. Was this on purpose? Both of these flags have the same value and are stored in the same variable (ebx).

There may be other unreported multiplayer issues related to this.

### CODE REVIEW

**Comment by nightroan** [comment]
Oh wow, that's much simpler than what I came up with. Does anything else down the line use ebx? I'm going to try this out tomorrow.

**Comment by zsilencer** [comment]
the game commands receive the flags in ebx and must return the price in ebx, this one was just missing that, probably when it was decompiled someone just forgot it.

**Comment by duncanspumpkin** [comment]
Agreed with zsilencer its a mistake in the decompilation. In the original it always returned 0 on ebx for this game command. Change it to set ebx to 0 and remove the comments as they aren't needed.

**Comment by pizza2004** [comment]
Would there be any merit to his thoughts about them sharing the same value causing multiplayer issues?

**Comment by zsilencer** [comment]
i don't think so because the flags and game command cost are completely different, it is just a case of using the same register as an input and output.

**Comment by nightroan** [comment]
I've updated the code to set ebx to 0. It's much simpler than what I came up with. Thanks for the input everyone!

**Pull request merged**
