### PR TITLE
Optimize readentirefile

### PR DESCRIPTION
**Pull request by Dandandan**
About 4 % of CPU time was spent in `readentirefile`. Now it uses `SDL_RWsize` to get info without seeking on supported platforms.

### CODE REVIEW

**Comment by janisozaur** [comment]
Surely not "4% of CPU time", you mean wall clock, right?

If 4% CPU is indeed spent just on `seek`/`tell`, I think there's something seriously wrong here.

**Comment by Dandandan** [comment]
No, I really mean CPU time. This is wile playing the sixflags scene great adventure mode in Release mode.
The profiling info is collected using the CPU sampling in VS 2015.

This is the info it gives:
profiling

**Comment by janisozaur** [comment]
> No, I really mean CPU time.

No, you don't. As you just mentioned, this is sampling profiling, it does not indicate CPU time at all. It only shows in which function was the instruction pointer at time of sample, but not whether the code was executing or not.

The CPU was likely stalled waiting for I/O, which is a valid state, albeit suboptimal, so not doing anything, but samples were taken when in `readentirefile`.

Here are some links to help you understand how CPU time is counted:
https://stackoverflow.com/questions/556405/what-do-real-user-and-sys-mean-in-the-output-of-time1
https://en.wikipedia.org/wiki/Profiling_%28computer_programming%29
https://perf.wiki.kernel.org/index.php/Tutorial#Counting_with_perf_stat

On a side note: I think your history is a bit broken, can you rebase your commits (and only these for this PR) on top of `origin/develop`, please?

**Comment by HaasJona** [comment]
Sampling gives you wall clock as far as I know.

**Comment by Dandandan** [comment]
I think you are right.

**Comment by IntelOrca** [comment]
I think @janisozaur is right, the sampling will not take into account blocking IO operations. However readentirefile is not called frequently like the other functions you have optimised... so its only 4% CPU time only at the time of loading... unless its calling it during the game? In that case why?

**Comment by Dandandan** [comment]
Thanks!
Actually, I don't know. The metrics include the loading, so it includes also the main menu and the loading of the scene, so maybe that's it.
If it's only the loading part it should decrease load time, I didn't measure wether that's the case.

**Pull request merged**
