### PR TITLE
Reorganise src/

### PR DESCRIPTION
**Pull request by IntelOrca**
Move all files under `src/` to `src/openrct2`.

This is to conform with src and test directories containing a sub directory that represents a project to produce a single output (executable or library).

Other directories within src/ will be, an android project, a Windows console shim project and possibly the rest of the game broken down into individual static library components. E.g. UI as its own component so that it can be optionally compiled separately from the main game logic.

As per usual the cmake and xcode projects need updating.

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
We should consider postponing the merger of this until the number of outstanding PRs has been dealt with — they're all likely to break with this change, aren't they?

**Comment by janisozaur** [comment]
@AaronVanGeffen I'd love to see that happen but we've never reached a point of 0 PRs.

I agree this is a fairly invasive change, but there is a lot of much needed refactoring and reorganisation to do around the project which was postponed for long time and now that .5 is out the door, it's finally time to do it. Even though the change is invasive, it is also fairly easy to rebase on top of, so I'm in favour of this going in regardless of other open PRs.

**Comment by janisozaur** [comment]
@IntelOrca will tests (currently `test/`) now live under `src/test/`?

**Comment by IntelOrca** [comment]
@janisozaur no

**Comment by janisozaur** [comment]
CMake is updated, but you need to account for https://github.com/OpenRCT2/OpenRCT2/pull/4935 which I merged as it fixed building.

**Comment by wolfreak99** [comment]
Sure its not gonna be possible to get the number to 0, but at the least try to get as much in as possible before this. Alot have been waiting for months now, such as my kick reason, and whatshisnames optional expanded peep behaviour and lighting (which if I'm right, with all due respect, you guys tried to recreate but got annoyed that he left indefinitely when you finally did something with it)

**Comment by AaronVanGeffen** [comment]
> Sure its not gonna be possible to get the number to 0, but at the least try to get as much in as possible before this.

It looks like some are being merged, fortunately.

> and whatshisnames optional expanded peep behaviour and lighting (which if I'm right, with all due respect, you guys tried to recreate but got annoyed that he left indefinitely when you finally did something with it)

@JeroenDStout 's lightning effects were actually merged, not re-created. @IntelOrca just rebased the code.

**Pull request merged**
