### PR TITLE
Fix #11126: Cannot place Frightmare track design

### LINKED ISSUE #11126: Cannot place Frightmare (stock track design)
**OS:** Ubuntu 20.04
**Version:** 0.2.5+
**Commit/Build:** 3613c660a0b4d2bc7d81329424f525eac7e3c7e3

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Pick the Steel Twister.
2. Try placing the "Frightmare" track design
3. Game will show the error "Can't construct this here... in the way" (sic)

Funtopia 2020-03-28 22-51-59

### PR DESCRIPTION
**Pull request by Gymnasiast**
Was this one ever tedious to fix...

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
So what was the issue?

**Comment by Gymnasiast** [comment]
In the old situation, it converted from big to small Z, did the addition, then converted it back. This basically meant it truncated the Z value to whole small Z increments. I changed the code to use big Z throughout, which also meant it no longer truncated the values in question.

**Comment by duncanspumpkin** [comment]
Which field is the bad Z coming from there might be other code we need to consider that this impacts. This has always been a little worry of mine when we increased the field sizes like with the pathfinding of the boat hire.

**Comment by Gymnasiast** [comment]
@duncanspumpkin I don't know what you mean. I `floor2`ed two variables (baseZ and clearanceZ) and that appeared to fix the problem.

**Comment by Gymnasiast** [comment]
I have bumped the network version. Is this good to go?

**Comment by duncanspumpkin** [comment]
Its good but do we know which field is the one that has the z values that are not good.

**Comment by Gymnasiast** [comment]
@duncanspumpkin I'll investigate. It's either baseZ, clearanceZ or one of the fields that feeds those.

**Pull request merged**
