### PR TITLE
Separate Chat Window

### PR DESCRIPTION
**Pull request by pizza2004**
I've done some progress on creating a standalone chat window, like requested in #3023, but I don't know what to do next really, and help would be appreciated.

I will look at the current functioning of the chat to see if I can figure out how to keep the entire history of the current play session, as I think it would be nice to have it in the window, and I also need help figuring out how to make the chat window actually show the chat and allow you to chat from within it.

### CODE REVIEW

**Comment by IntelOrca** [comment]
Write some code in window_chat_scrollpaint perhaps?

**Comment by pizza2004** [comment]
So with this latest commit, I'm just wondering why it isn't sending the text you type into the box to the server.

Also, the window appears way up in the corner and when you try to click the save button it always grabs the window like you're clicking the title bar, and when you hit enter in the text box it rotates the view in addition to removing the text from the text box.  Any help with why that's happening would be great.

**Comment by Gymnasiast** [comment]
@pizza2004 Are you still working on this?

**Comment by pizza2004** [comment]
*perks up* Oh hey there.  I haven't looked at this in a while with school and work and stuff.  I guess I could look into getting this to work again, unless there's someone else more interested in it, now that I'll have a little extra free time.

**Pull request closed without merging**
