### PR TITLE
Breakpad – WIP, discussion

### PR DESCRIPTION
**Pull request by janisozaur**
Tech-preview quality only at the moment, but I'd like to hear your thoughts.

Provide your own breakpad and point cmake at it.

```
git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
mkdir breakpad && cd breakpad
../depot_tools/fetch breakpad # edit the script to use python2
cd src
LDFLAGS="-m32" CXXFLAGS="-m32" CFLAGS="-m32" CPPFLAGS="-m32" ./configure
LDFLAGS="-m32" CXXFLAGS="-m32" CFLAGS="-m32" CPPFLAGS="-m32" make -j 8
```

Run cmake on openrct2:
```
cd openrct2
vim CMakeLists.txt # provide your path to breakpad
mkdir build && cd build
cmake ../ -DWITH_BREAKPAD=ON
make -j 8
./openrct2 # open a game, select "about openrct2", crash
```

This is for Linux only at the moment, I'll try working on Windows support as well, but OS X is out of my reach, should be fairly simple though.

This will produce the dumps only for now, I have yet to check if everything fits properly and if we can actually use the dumps.

A possible option, that I'd like to include is crash reporter, a tool to automatically upload the dumps.

**TODO**
- [x] Rename to crash.cpp and crash.h (add to OSX project)
- [x] Move breakpad guard into crash.cpp, openrct2.cpp should just be crash_init or something.
- [x] ~~Create directory and lock file or just save dump files to root user directory.~~ Agreed not to do that
- [x] Notify the user of dump file and tell them to send it to developers.
- [x] Update AppVeyor script to send .pdb to OpenRCT2.org.

### CODE REVIEW

**Comment by janisozaur** [comment]
Breakpad's docs: https://chromium.googlesource.com/breakpad/breakpad/+/master/docs/

**Comment by PFCKrutonium** [comment]
If this can be made to work well, I would be all for this - it could catch so many crashes that don't get reported and increase the code quality by a tonne.

**Comment by janisozaur** [comment]
| binary size of openrct2 (bytes) | stripped   | non-stripped |
|---------------------|------------|--------------|
| with breakpad       | 18,788,896 | 26,128,048   |
| without breakpad    | 18,524,360 | 25,709,232   |

timed `./configure`, `make` for breakpad (i7 4790k, gcc 5.3.0):
```
LDFLAGS="-m32" CXXFLAGS="-m32" CFLAGS="-m32" CPPFLAGS="-m32" ./configure  0,33s user 0,06s system 33% cpu 1,179 total
LDFLAGS="-m32" CXXFLAGS="-m32" CFLAGS="-m32" CPPFLAGS="-m32" make  25,45s user 1,98s system 96% cpu 28,505 total
```

**Comment by Joshwoo69** [comment]
"A possible option, that I'd like to include is crash reporter, a tool to automatically upload the dumps."
snooper options. like in minecraft with openeye
turn snooper off : no report sent.

**Comment by janisozaur** [comment]
@Joshwoo69 I have no idea what your comment is about.

**Comment by Joshwoo69** [comment]
add and option to turn on an off automatic crash reporting and probable put a notice as well that this app connects to the interwebz @janisozaur .

**Comment by Broxzier** [comment]
@Joshwoo69: I think janisozaur means that when a crash occurs, a tool gets launched that uploads the dump file for us to inspect. This could be as simple as a confirmation box that lets the user know data will be sent.

**Comment by Joshwoo69** [comment]
perfectly know that... add a option to disable it too...

**Comment by janisozaur** [comment]
All done now. Please review & test.

**Comment by Broxzier** [comment]
Wouldn't it be nice to have the commit hash in the filename of the dump, so that we don't have to ask which build the player was running every time they fail to mention it?

**Comment by janisozaur** [comment]
By the time we reach crash handler, the dump will already have been created. There are not enough technical solutions to overcome user stupidity.

**Comment by Broxzier** [comment]
Can the crash handler not rename the files to include the build number?

**Comment by Broxzier** [comment]
#3476

**Pull request merged**
