### PR TITLE
fix - disabled resolution dropdown for "Windowed" mode.

### PR DESCRIPTION
**Pull request by Aroidzap**
Since we have resizable window and changing resolution in Windowed mode does nothing, leaving it editable makes no sense.

### CODE REVIEW

**Comment by IntelOrca** [comment]
It is controversial to disable an option just because it isn't valid for the current mode. The option represents fullscreen resolution, and the user might want to set the resolution first before going to fullscreen. Otherwise they would have to go fullscreen to a resolution they didn't want and then change it.

**Comment by Aroidzap** [comment]
Ok then, but I think it's misleading. If someone really needs to set resolution before going to fullscreen (it's an exceptional case), he usualy changes it in config file.

**Comment by Gymnasiast** [comment]
Actually, it normal to disable an option that isn't valid for the configuration. Except that in this case, setting the resolution before entering full screen can indeed prevent monitor and video card from acting up, so I think we should keep it.

As for the dropdown being misleading as @Aroidzap pointed out: that's easily solved by changing the label to `Fullscreen resolution`.

**Comment by HaasJona** [comment]
I agree with changing the Label and leaving it enabled. Switching to an incorrect fullscreen resolution is annoying at least.

**Comment by Aroidzap** [comment]
Shouldn't it be then enabled for "Fullscreen (desktop)" too?

**Comment by Gymnasiast** [comment]
Yes, as the point is that it should always be enabled for the reasons we mentioned, just labelled more clearly than is currently the case.

**Pull request closed without merging**
