### PR TITLE
Change autosave system to use wall-clock time based frequencies (#1960)

### PR DESCRIPTION
**Pull request by Overv**
The autosave system will now use frequencies based on wall-clock time rather than in-game time, for example every 15 minutes. This frequency is not affected by pausing the game or changing the game
speed. The default frequency is every 5 minutes.

The translations are based on strings 1879 to 1885.

(See #1960)

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
Don't make language file changes in thus repository. They should be done inhttps://github.com/OpenRCT2/Localisation

**Comment by Gymnasiast** [comment]
Still, I have to applaud you for making such an effort on the translations. English and Dutch are correct; German as well, by the look of it. If you open a PR on Localisation with the Dutch translation and all the languages that use English strings (Spanish, etc.), the other translators will take care of the rest.

You will have to take the translations out of this PR, though, with the exception of UK English, which _is_ maintained here (being the main language).

**Comment by Overv** [comment]
I've removed the localisation changes from the commit and removed the unused variables.

**Comment by Gymnasiast** [comment]
Yes, they will fall back on UK English if they haven't got their own strings, and the string number is lower than 5120.
Also, if you add or change a string, opening an Issue on Localisation to notify the translators one has been added is very much welcomed. The translators will then take care of translating it. A PR to add the translated strings is welcome, provided the translations are good and not from Google Translate, but not required.

**Comment by Overv** [comment]
Fair enough. I just thought it was messy to have the feature and the translations separate, because of the UI inconsistency.

**Comment by Gymnasiast** [comment]
I understand, but nobody will be able to translate into all the languages OpenRCT2 supports on his/her own. And the idea of localisation is not running the strings through Google Translate, even if that means English strings will show up. We have set the bar higher than that. Also, some languages are checked and discussed quite heavily, which would slow down PRs if they contained translations.

**Pull request merged**
