### PR TITLE
Add a console option to fix the banner count, fixes #667

### LINKED ISSUE #667: Banner limit calculation bug?
I had a few times that I got a warning about I reached the banner limit. Now once again and I only build something around 5 banners. On some sites they say the limit is 250, but nobody knows it exactly and it also seems nobody knows if only the placable banner are counted into this limit or also the ones from the queues etc. 

But after building 5 banners in a not so large park and then getting this message about I reached the Banner limit?! There seems to be a bug in the calculation in the number of the Banner limit. This bug occurs in OpenRCT2, but also in vanilla RCT2.

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
I'd prefer we found the cause of the bug rather than fix the symptom.

**Comment by IntelOrca** [comment]
Indeed, this isn't actually fixing #667. But I am fine for this to be merged as it would be useful for fixing corrupting saved games.

**Comment by mrtnptrs** [comment]
@duncanspumpkin Is the code regarding the banner limit now fully decompiled since January? :) If you can fix it, it would mean that I can finally block more paths in my park, so my naughty guests can't walk there and vomit in front of an exit or something.. :P @IntelOrca But when you fix this limit (REALLY fixing it codewise,) then the OpenRCT2 save would get corrupted for RCT2?

**Comment by duncanspumpkin** [comment]
Banner limit code is complete but we wouldn't be able to increase it without completely breaking all save compatibility as it would require changes to the map_element structure. There is some code that is reserving banner entries and not freeing them that is the bug that this is trying to fix. (I think)

**Comment by IntelOrca** [comment]
I think @mrtnptrs means that any saved game played in RCT2 would have a corrupt banner count and therefore would need this PR.

**Comment by mrtnptrs** [comment]
@duncanspumpkin @IntelOrca I actually mean what you both say :)

**Comment by Gymnasiast** [comment]
It isn't about increasing the limit actually. The problem was that in the save included in #667, there were 5 banners in the park. Attempting to build an extra one would give show an error that there were too many banners in the park, even though the limit should be in the region of 250. That's what Maarten was talking about.

This behaviour was caused by a corrupted save, that had several entries that had a NULL map_object (= no banner) but hadn't had their type set to BANNER_NULL. As the code only checks the latter, it would the issues described above.

Now, I don't know _how_ the save got corrupted. Maarten hasn't said whether he created that save in RCT2 or OpenRCT2. If the behaviour was caused by RCT2, we can't really do much about it except having fixes like this.

**Comment by mrtnptrs** [comment]
@Gymnasiast I almost know for sure I created that save in Vanilla RCT2. And I had this a few times more a few years ago with other saves. Isn't it possible to read from a save file if it was created with OpenRCT2 or vanilla RCT2? So, I think this is an original bug...

**Comment by Gymnasiast** [comment]
@IntelOrca or @duncanspumpkin : Considering this is useful for solving corruption caused by vanilla RCT2, would you merge this?

**Pull request merged**
