### PR TITLE
Create Derivative Category For Scenarios

### PR DESCRIPTION
**Pull request by 733737**
I am creating this so the plugin API can be used to posit user created scenarios into a sub divider of the "Other" category. The derivative section will allow users to call a hook in the plugin to write their own name for sub dividers which will be added above the "Other" "Other" subcategory

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Could you clarify a bit what this PR should achieve?

**Comment by 733737** [comment]
I believe that when making a custom scenario you should not only be able to have your own "Campaign" tab, but also be able to sort individual scenarios in the Other scenario category. I want the user to be able to input the title of their divisor in the scenario editor, so that scenarios in the "Other" category can be sorted with subdividers by the user. This way the user can choose whether they want their own tab, or if they haven't finished an entire "Scenario Pack" they could put it in "Other" under "My Scenarios" "Scenario Test Group A" or "Misc Scenarios" or anything else they come up with.

**Comment by Gymnasiast** [comment]
That’s not what your code does, unfortunately.

Support for creating extra tabs and dividers is planned, though.

**Comment by 733737** [comment]
I had actually made a bunch of erroneous code, which I removed from this PR...

**Pull request closed without merging**
