### PR TITLE
Fixes issue 2726 'Add rotating banner text when zoomed out'

### PR DESCRIPTION
**Pull request by PretentiousPotatoPeeler**
Increased maximum zoom level for displaying scrolling_text to 1.

### CODE REVIEW

**Comment by janisozaur** [comment]
Prefix issue number with `#` in your commit message.

**Comment by IntelOrca** [comment]
@janisozaur don't encourage that format. I prefer the online to contain the issue number and text. Details about the fix can go on the following lines.

**Comment by janisozaur** [comment]
@IntelOrca OK, sure. I mostly care about oneline format as it makes browsing commits so much easier. I removed the blurb from my previous comment.

**Comment by IntelOrca** [comment]
@janisozaur yes, so why would you not want issue number in the commit line - the most important part?

**Comment by janisozaur** [comment]
@IntelOrca because it holds no information when you use local git client only (without cross-referencing with github) and takes quite a bit of valuable space in the first line. Ideally, a commit would be self-explanatory in the longer description section, so that you don't have to rely on github, with the original issue only holding information like steps to reproduce or park that triggered it. Github would still link it properly, regardless of where in the body of commitmsg the blurb exists – and this is the only use case for these mentions.

But I'm fine with your suggestions, that's not really an issue.

**Comment by IntelOrca** [comment]
I don't think this should be merged, it doesn't look very good because all the scrolling banners look like they are flashing.

**Comment by Gymnasiast** [comment]
Closing this because of the disadvantages IntelOrca mentioned.

**Pull request closed without merging**
