### PR TITLE
Refactor object loading

### PR DESCRIPTION
**Pull request by IntelOrca**
Re-write of the most of the object reading, loading, importing and exporting.

### CODE REVIEW

**Comment by janisozaur** [comment]
With #4030 I loaded [`Fred's Ultimate Coaster Kingdom`](http://www.nedesigns.com/park/3550/freds-ultimate-coaster-kingdom) park before and after this refactor, there are still some minor changes (you may need to use image manipulation program to see these differences, created by doing an overlay layer of new on top of old, then selecting "difference" as a blending option):

Exhibit 1:

diff1
visible1

Exhibit 2:

diff2
visible2

**Comment by IntelOrca** [comment]
can you also upload the other source image used for the diff?

**Comment by janisozaur** [comment]
10MiB per screenshot:
[post-refactor](https://cloud.githubusercontent.com/assets/550290/16713518/62e8fbe4-46aa-11e6-8157-7c3c5a81cb19.png)
[pre-orig](https://cloud.githubusercontent.com/assets/550290/16713519/66cc7a2e-46aa-11e6-9620-354cf1a577f7.png)

**Comment by Gymnasiast** [comment]
I get a segfault when I click the vehicle tab on a Junior Roller Coaster.

Steps to reproduce:
1) Open Six Flags Great Adventure.
2) Click 'Blackbeard's Lost Treasure Trains'
3) Click the vehicle tab.
It will now segfault.

**Comment by IntelOrca** [comment]
I can't reproduce bug 1, @janisozaur can you?

I can reproduce bug 2, still trying to work out how to fix it.

**Comment by Gymnasiast** [comment]
Did you specifically click on the ride I mentioned?

**Comment by janisozaur** [comment]
Yes.

I opened openrct2 (I opened it previously, so I had all the objects already indexed), clicked on "start new game", switched tab to "real parks", selected "great adventure", closed welcome screen, clicked on "rides & attractions" in top-right corner, selected "Blackbeard's Lost Treasure Trains" and cliked on vehicle tab (second one). Nothing has happened for me.

**Comment by IntelOrca** [comment]
Fixed bug 2.

**Pull request merged**
