### PR TITLE
Remove “Extra viewport” option

### PR DESCRIPTION
**Pull request by Gymnasiast**
This has been broken since it was implemented in 2014(!). Hardly anybody seems to care for it either - not the developers, not the users. Time to get rid of it.

### CODE REVIEW

**Comment by ZehMatt** [comment]
Are there any issues related to it? Can't seem to find any that suggest its broken, also I've tested it and it works fine on my end.
image

However you are probably right that nobody gives a damn about it, but I also would like to avoid jumping the gun just yet, perhaps we should leave this PR hanging a few days to see if anyone comes nagging.

**Comment by AaronVanGeffen** [comment]
I think it's something that could be easily implemented as a plug-in nowadays, if nothing else.

**Comment by ZehMatt** [comment]
> I think it's something that could be easily implemented as a plug-in nowadays, if nothing else.

Probably, not sure if we support viewports but could be and if not we should probably add support.

**Comment by Gymnasiast** [comment]
@ZehMatt 
> Are there any issues related to it? Can't seem to find any that suggest its broken, also I've tested it and it works fine on my end.

Try rotating the view and the issue will become apparent ;)

**Comment by ZehMatt** [comment]
> @ZehMatt
> 
> > Are there any issues related to it? Can't seem to find any that suggest its broken, also I've tested it and it works fine on my end.
> 
> Try rotating the view and the issue will become apparent ;)

I see, the position is not properly transformed but its not like its unusable. But yeah, this is a good candidate to be a plugin.

**Comment by MaxMallon** [comment]
That's a bit of a shame, I like these. Maybe instead of deleting it, upgrading it with a rotate button would be better.

**Comment by karst** [comment]
Most people don't even know it exists. Perhaps an extra viewport would be better as a plugin on the side.

**Comment by MaxMallon** [comment]
> Most people don't even know it exists. Perhaps an extra viewport would be better as a plugin on the side.

I mean, I guess, but why would you remove it just cause it's not used much? Should we also remove the banked down-to-level pieces for the wooden and looping coasters, cause a lot of people don't know about them? 
it's already there, just let it stay?

**Comment by ZehMatt** [comment]
> Should we also remove the banked down-to-level pieces for the wooden and looping coasters, cause a lot of people don't know about them? it's already there, just let it stay?

The question is can it exist as a plugin? If it can't then we can't remove it.

**Comment by Broxzier** [comment]
Plugins can have viewport, I'm not 100% sure about panning and rotating, though. I'd prefer we create an official plugun before removing it.

Though rarely, I do use it sometimes. Mostly in "multiplayer squares" competitions, to look at two plots at the same time.

**Comment by Gymnasiast** [comment]
> That's a bit of a shame, I like these. Maybe instead of deleting it, upgrading it with a rotate button would be better.

You obviously have never tried that, or you’d have found out it’s really not that simple.

> I mean, I guess, but why would you remove it just cause it's not used much? Should we also remove the banked down-to-level pieces for the wooden and looping coasters, cause a lot of people don't know about them?

That comparison makes no sense. Those pieces are not only used much more, they _work_ (unlike this feature) and removing those would cause backwards compatibility issues.

**Comment by MaxMallon** [comment]
> You obviously have never tried that, or you’d have found out it’s really not that simple.
I have indeed not tried that.

>Those pieces are not only used much more, they work (unlike this feature) and removing those would cause backwards compatibility issues.
I mean, that's fair. 
still, I don't like the idea of removing features, even if they're not fully working.

**Comment by Gymnasiast** [comment]
Btw, I didn’t mention it, but I did try to fix this window myself twice, with the last attempt one month ago. The rotation code for viewports just assumes that the map coordinates for a given point are available so it can refocus. Which is the case for all other ones: they concentrate on a peep, a vehicle, a banner or a ride - all of which have their position saved somewhere. This is obviously not the case for the Extra Viewport.

Additionally, all viewports share their rotation. This would need refactoring out as well to make this kind of feature fully work. I have tried that too, but it heavily relies on the global rotation, so not easy to do either.

>  still, I don't like the idea of removing features, even if they're not fully working.

I understand the sentiment, but at the same time broken features make people think the game is buggy, and they also mean an additional maintenance burden, even though we’re already stretched thin. All of our users benefit if there is less to maintain.

**Comment by IntelOrca** [comment]
I think the issue should be fixed. Removing this feature is like hiding the bug. And the same bug will occur in a plugin or be impossible to implement. So hopefully someone can work out a suitable fix, it might require some refractors so things don't rely on global rotation.

**Comment by Gymnasiast** [comment]
> I think the issue should be fixed. Removing this feature is like hiding the bug. And the same bug will occur in a plugin or be impossible to implement. So hopefully someone can work out a suitable fix, it might require some refractors so things don't rely on global rotation.

You said that 10 years ago. It seems obvious to me that nobody cares about the bug. Unless you want to commit to fixing it, in which case I would be fine closing this.

**Comment by MaxMallon** [comment]
I'll be frank, I've never used this feature, but that's mostly because I forgot it existed until, ironically enough, 1 day _before_ this PR was brought to my attention, when I saw it in the menu, and thought "Oh yeah, that exists.. that could've come in handy a few times"

I know, it's apparently really hard to add rotation to it, but that would be a game changer. Being able to build a building with a certain pattern, on one side without constantly having to rotate 180 to see how the pattern went on the other side. 
Now I often resort to taking screenshots as reference.

**Comment by ocalhoun6** [comment]
> The rotation code for viewports just assumes that the map coordinates for a given point are available so it can refocus. Which is the case for all other ones: they concentrate on a peep, a vehicle, a banner or a ride - all of which have their position saved somewhere. This is obviously not the case for the Extra Viewport.

This particular problem seems solvable. If the problem is that we don't have an object to center on, then let's *make* an object to center on!

When the button is clicked to rotate the view in the viewport:
1: Detect what tile the viewport is currently centered on. (It's okay if this is a little bit approximate; players aren't likely to be bothered if the viewport moves *very slightly* while rotating. Since the entire viewport is about to change anyway, it won't be very noticeable.)
2: Place a hidden, non-rendering object at that location. (An invisible scenery object would probably work best and be the least likely to cause any problems with anything else.)
3: Rotate the view.
4: Center the view on the object created in step 3.
5: Delete the object created in step 3.

--------

The problem with the viewport's rotation being tied to the main view's rotation, though... Yeah, no easy fix for that. However, maybe the extra viewport is still useful to some people even if the view rotation is still tied in lockstep with the main view?

**Comment by Gymnasiast** [comment]
> > The rotation code for viewports just assumes that the map coordinates for a given point are available so it can refocus. Which is the case for all other ones: they concentrate on a peep, a vehicle, a banner or a ride - all of which have their position saved somewhere. This is obviously not the case for the Extra Viewport.
> 
> This particular problem seems solvable. If the problem is that we don't have an object to center on, then let's _make_ an object to center on!
> 
> When the button is clicked to rotate the view in the viewport: 1: Detect what tile the viewport is currently centered on. (It's okay if this is a little bit approximate; players aren't likely to be bothered if the viewport moves _very slightly_ while rotating. Since the entire viewport is about to change anyway, it won't be very noticeable.) 2: Place a hidden, non-rendering object at that location. (An invisible scenery object would probably work best and be the least likely to cause any problems with anything else.) 3: Rotate the view. 4: Center the view on the object created in step 3. 5: Delete the object created in step 3.
> 
> The problem with the viewport's rotation being tied to the main view's rotation, though... Yeah, no easy fix for that. However, maybe the extra viewport is still useful to some people even if the view rotation is still tied in lockstep with the main view?

Can you please not comment on all PRs that have some sort of discussion going on?

**Comment by ZehMatt** [comment]
I gave it some more thought, I think we should keep it as it serves a good starting point to fix viewports depending on the global rotation variable. I'll create a new issue to refactor this.

**Comment by Gymnasiast** [comment]
I’m closing this as it hasn’t gained much traction.

**Pull request closed without merging**
