### PR TITLE
Update replays to v0.0.4

### PR DESCRIPTION
**Pull request by ZehMatt**

### CODE REVIEW

**Comment by ZehMatt** [comment]
Could need a hand here @Gymnasiast or @janisozaur, I'm having trouble figuring out the correct path for the CMake configuration, it doesn't seem to placing them in the correct directory.
I did a few attempts myself but couldn't quite figure out it, there are a few things I noticed:
1. The replays.zip contains already a folder called replays so it would probably unpack it into testdata\replays\replays if I'm not mistaken.
2. If I read the CMake file correctly its packing them into the userdata folder which is not the correct path I think, it should be <binary>/testdata/replays

**Comment by IntelOrca** [comment]
> The replays.zip contains already a folder called replays so it would probably unpack it into testdata\replays\replays if I'm not mistaken.

Yes, which means you probably want to drop replays from the output directory in `openrct2.proj` as well.

**Comment by ZehMatt** [comment]
It seems that its fine with windows builds, the replays are actually ran. Its currently specific to the CMake configuration

**Comment by IntelOrca** [comment]
It should still probably be changed. Bit strange to have replays/replays.

**Comment by ZehMatt** [comment]
Finally managed to get it working, now this looks good.

**Comment by ZehMatt** [comment]
Just realized with network disabled it wouldn't actually run replays for code coverage. Now I think its ready. I'll gradually add more over time

**Pull request merged**
