### PR TITLE
Update the UI at screen refresh rate

### LINKED ISSUE #6152: Moving camera capped at 40fps
**OS:** Arch Linux
**Version:** 0.1.1
**Commit/Build:** f253730

When moving the camera, either with the arrow keys, screen borders or dragging with the mouse, the movement still seems capped at 40fps even when the option `uncap FPS` is checked. It looks exactly the same when this option is unchecked. The camera movement should also happen at 60fps (or higher if the screen supports it).

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Check `uncap FPS`
2. Move the camera
3. Repeat the same with `uncap FPS` unchecked and compare the results

**Dump file**

**Screenshots / Video:**

**Save game:**

### PR DESCRIPTION
**Pull request by ZehMatt**
I remember moving this out before but this is what causes the choppy view panning, I've tested this a bit and I couldn't spot any side effects. This needs some better testing

Closes #6152

### CODE REVIEW

**Comment by Broxzier** [comment]
In normal game tempo, it feels much better, but when the game speed is up, it feels really sluggish. I have to move the mouse much further to move the same distance then. Probably because the fps drops below 40. On current develop, it also feels sluggish, but not as jittery. I don't consider this a show-stopper for this PR, though. Will do more gameplay testing with this build later this week.

**Review by Broxzier — APPROVED** [review]
Now with the input decoupled, it feels so much better even when the fps drops.

**Comment by ZehMatt** [comment]
One bug I noticed so far is that when keeping a button pressed it will trigger plenty click events, holding it down previously was tied to the 40hz delay, need to see if I can find a way to make this work again

**Comment by AaronVanGeffen** [comment]
Surprising (to me) how much of a difference this makes. Nice work!

**Review by Gymnasiast — CHANGES_REQUESTED** [review]
This appears to break right-click scrolling when in window mode. You can test this by right-clicking near the edge of the window and moving towards that edge (e.g. right-click 3 cm from the right edge and move your mouse to the right). I also tested this on develop, could not reproduce it there.

**Comment by ZehMatt** [comment]
> This appears to break right-click scrolling when in window mode. You can test this by right-clicking near the edge of the window and moving towards that edge (e.g. right-click 3 cm from the right edge and move your mouse to the right). I also tested this on develop, could not reproduce it there.

Thanks, I will look into it.

**Comment by ZehMatt** [comment]
Should be fixed by f186796

**Review by duncanspumpkin — APPROVED** [review]
Seems to work

**Comment by mrpenguinb** [comment]
The arrow key and edge-scrolling is still capped to 40 FPS from what I can tell when toggling the Uncap FPS setting.

**Comment by ZehMatt** [comment]
You are correct, input is still handled at 40Hz and its unlikely this will change anytime soon.

**Comment by mrpenguinb** [comment]
> You are correct, input is still handled at 40Hz and its unlikely this will change anytime soon.

How much work would be required to make most (or at least camera) input be handled at 40Hz and above? By the sounds of it it sounds like a lot.

**Pull request merged**
