### PR TITLE
Make StrDecompToPrecomp() take C++ strings

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by Gymnasiast** [comment]
@adam-bloom Would you be able to test this out on macOS? Also, if there is a better solution for the macOS code, please let me know.

**Comment by adam-bloom** [comment]
@Gymnasiast anything in particular to test? I downloaded the CI artifact and was able to load .sv6 and .park files without any noticeable string issues. I'm not much of an Objective-C developer myself, so no style comments there from me!

**Comment by Gymnasiast** [comment]
Specifically, these strings:

afbeelding

afbeelding

If it displays properly, then it should be fine.

**Comment by adam-bloom** [comment]
> Specifically, these strings:
> 
> afbeelding
> 
> afbeelding
> 
> If it displays properly, then it should be fine.

All good then! I double checked the rct1 path string already since I noticed that in the PR, and the load window was behaving correctly when I was loading saves, with the displayed path updating as I navigated.

**Pull request merged**
