### PR TITLE
fix wrong tile

### PR DESCRIPTION
**Pull request by danidoedel**

### CODE REVIEW

**Comment by PFCKrutonium** [comment]
Is... is it gravel now?

**Comment by danidoedel** [comment]
We will see... ;)

**Comment by PFCKrutonium** [comment]
I downloaded it... The tile is still grass?

**Comment by danidoedel** [comment]
Are you sure? Wait let me check it... :O

**Comment by danidoedel** [comment]
Hmm it's working for me... You sure you opened the correct save?
2015-07-16 21_47_35-openrct2

**Comment by PFCKrutonium** [comment]
:( And now I am looking for the new anomaly...

**Comment by IntelOrca** [comment]
I don't really feel like merging this, we will have new parks for 0.0.3 and storing parks in git is expensive in terms of space.

**Pull request closed without merging**
