### PR TITLE
Fix #16075: Track designs save scenery in wrong location

### LINKED ISSUE #16075: Saving scenery with track design is saved in the wrong location
### Operating System

Windows 10 64 bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (61c67af) provided by GitHub

### Describe the issue

Saving a track design with Scenery included does not save the scenery next to the ride. In fact it saves the scenery incredibly far away on master. It still happens on develop if you do it on the old save format in an old save(.SV6). Oddly you can still reproduce this bug after you convert it to .park. On a completely new save on new save format, you cant save track designs with scenery at all as an error appears but that is a separate issue documented here: #16019

Screenshot_525

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Build a track design. (Tested with Launched Freefall)
2. save with scenery
3. if old save format, then go to saved ride in ride menu and observe scenery far away from ride
3b. if NSF, observe error that says "too much scenery or too far away" (#16019 )

### Attachments

Screenshot_522
Screenshot_523
Screenshot_526
Screenshot_524

### PR DESCRIPTION
**Pull request by ZehMatt**
Should have used the state from the ride instead of creating a new one.

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
When was the bug introduced was it in 0.3.5.1 release perhaps needs changelog.

**Comment by Gymnasiast** [comment]
It looks good - was this indeed already present in v0.3.5.1?

**Comment by ZehMatt** [comment]
> It looks good - was this bug indeed already present in v0.3.5.1?

The PR had the milestone on it. So I think so.

**Comment by duncanspumpkin** [comment]
Yes it was in the last release.

**Comment by duncanspumpkin** [comment]
Can you get rid of the ci skip as it has prevented the ci from running.

**Review by duncanspumpkin — APPROVED** [review]

**Review by Gymnasiast — APPROVED** [review]

**Pull request merged**
