### PR TITLE
Don't update title screen when running headlessly

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by IntelOrca** [comment]
Always wrap bit-wise expressions in brackets.
Also why would the game be on the title screen if headless?

**Comment by janisozaur** [comment]
Updated. Without this, it's crashing when I do `./openrct2 join 127.0.0.1 --headless`. I need this to work.

**Comment by IntelOrca** [comment]
Can you find an alternative way to fix it. I don't think screen flags should ever be title when headless is enabled.

**Comment by janisozaur** [comment]
I can try, but just to confirm: when you pass `join` command to `./openrct2`, it starts the title screen and starts network stuff: address resolving, downloading map, etc. while displaying progress report in a window. The same happens here, but there is no screen to render to and perhaps no game loaded yet (I'm not sure). Would skipping that condition and calling `game_update()` work in these circumstances?

**Comment by IntelOrca** [comment]
Hmm ok, I'll merge for now and make a new issue. This obviously needs a rethink. We don't really want to be doing any interface or loading when joining a game from command line let alone headless.

**Pull request merged**
