### PR TITLE
Improvement: more icon resolutions

### PR DESCRIPTION
**Pull request by trigger-death**
Added 24x24 (no flag), 48x48 (no flag), and 96x96 (with flag) icon resolutions.

### CODE REVIEW

**Comment by janisozaur** [comment]
1. `x96` variant is not optimised yet
2. I'd rather leave current icons as they are, they were accepted into the repository without being checked and now it only adds bloat to git
3. This whole PR should use `[ci skip]`

**Comment by trigger-death** [comment]
The `x96` variant can't get any smaller, pngout has already tried.

**Comment by janisozaur** [comment]
I wonder if these should also get included in here: https://github.com/OpenRCT2/OpenRCT2/blob/7f9c25a7a93ea153b36adf01738f444bbdd2a648/CMakeLists.txt#L160-L165

**Comment by janisozaur** [comment]
At least 48 version should, but seeing you already added them all, let's leave them in.

**Pull request merged**
