### PR TITLE
macOS CMake with vcpkg dependencies

### PR DESCRIPTION
**Pull request by adam-bloom**
Part of #13569.

This PR adds a new (on by default) option to CMake to pull the specified macOS vcpkg dependency release from https://github.com/OpenRCT2/Dependencies. It also builds and runs the test executables for macOS.

~~Note: Discord RPC support is off for now, but will be enabled when using the dependencies dylib for discord-rpc (instead of downloading from the internet) is added. I plan to look at this next. It is similar to #13658. I'll try to address that before this is merged, but wanted to get this opened before completing that work.~~

Before merging this (well, at least before the new CI run works), OpenRCT2/Dependencies#27 is required.

This does not remove/break any existing functionality. Since the use of dependences is ON by default, some documentation for macOS builds will need to be updated after this is merged. All of that documentation is still accurate if the new option is disabled. There is a potential argument to be made that because of that, this new option should be disabled by default, but I believe it is better to be enabled by default moving forward.

### CODE REVIEW

**Comment by LRFLEW** [comment]
On the topic of making another release of the Dependencies, I messed with it locally on my machine, and it appears that some of the Windows libraries lost the lib prefix. In particular, `libspeexdsp.lib` became `speexdsp.lib` and `libfridibi.lib` became `fridibi.lib`. This will require an update to the visual studio project, but should probably be independent of this PR.

**Comment by adam-bloom** [comment]
Just a quick note - this should not be merged as is, since both macOS builds are currently pointed at my Dependencies fork until we get a new release in OpenRCT2/Dependencies. It needs some other minor cleanup I’ll get to in a day or two (cmake if statement consistency, discord-rpc, check duktape). The new CI job is now passing - including all of the tests running on macOS.

**Comment by adam-bloom** [comment]
This is fully cleaned up now. Note that it is not fully "portable", but that really isn't a reasonable expectation - that's what macOS app bundles are for. I'll work on the app bundle from cmake after this is merged.

Does anyone have opinions regarding the default value of `MACOS_USE_DEPENDENCIES`? Or is this ready to go once we get  an updated dependencies release and point this back to OpenRCT2/Dependencies instead of my fork?

**Comment by Gymnasiast** [comment]
@IntelOrca or @janisozaur Could you review this?

**Review by janisozaur — APPROVED** [review]
Sorry it took us so long, none of us use this platform.

The change looks good to me, but we still need to release our builds of libs in https://github.com/OpenRCT2/Dependencies before this can get merged.

@adam-bloom do you think we could move our CI builds away from xcode project and to use cmake instead? Updates to the xcode project are quite an inconvenience with the weird format it uses.

**Comment by adam-bloom** [comment]
> The change looks good to me, but we still need to release our builds of libs in https://github.com/OpenRCT2/Dependencies before this can get merged.
@IntelOrca and I are working on getting the Dependencies CI updated so we can actually generate an official release. Should get that done soon (I'm going to try to look at it this weekend).

> @adam-bloom do you think we could move our CI builds away from xcode project and to use cmake instead? Updates to the xcode project are quite an inconvenience with the weird format it uses.
There's some discussion in #13569 on this. We need to add one more target to cmake (the actual portable macOS OpenRCT2.app bundle) to reach equivalence with the current Xcode project. I've had a bit less time to spend on this recently, but I still hope to add those changes in a separate PR. I'll leave it up to others to decide if that should exist in parallel with Xcode or fully replace it...seems like there are some strong opinions on that subject.

**Comment by adam-bloom** [comment]
@IntelOrca made a new Dependencies release earlier today (thanks!), so I've repointed both of the macOS build jobs to the new release. I think this is good to go now.

I've gone ahead and updated the readme to indicate that cmake will download the dependencies automatically, and that you no longer need to fetch them yourself with `brew` first. This wiki page needs to be updated too: https://github.com/OpenRCT2/OpenRCT2/wiki/Building-OpenRCT2-on-macOS-using-CMake. I'll try to remember to do that after this is merged (although unlike the readme, I'd recommend leaving all of the old info there, and mentioning to pass `-DMACOS_USE_DEPENDENCIES=off` to cmake and all of it is still relevant).

I hit one error in the actual build (unrelated to this change) for an unused variable. None of the other build jobs hit an error here, so for now I just allowed that error https://github.com/OpenRCT2/OpenRCT2/pull/13682/commits/ccba91d50ecf80544be55bc1fab7e77a1423ab63. If you all think we shouldn't allow unused variables, then this const needs to be removed, as it is unused: https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2-ui/windows/Ride.cpp#L875-L909.

**Comment by Gymnasiast** [comment]
That const should be removed. Preferably in a PR of its own.

**Comment by adam-bloom** [comment]
@Gymnasiast agreed, I just wasn't sure why none of the other builds complained. I'll leave that mystery to someone else. I've dropped the last commit from this PR (so the macOS cmake build will fail with the unused const error) and opened #14202 to resolve that. I can rebase this after the other PR is merged, if you'd like to see all green first, or these can both be merged separately.

**Comment by janisozaur** [comment]
@adam-bloom with #14202 now merged, can you rebase?

**Comment by adam-bloom** [comment]
> @adam-bloom with #14202 now merged, can you rebase?

Done, @janisozaur. I wasn't sure if you wanted to merge #14203 as well.

**Review by janisozaur — APPROVED** [review]

**Review by IntelOrca — APPROVED** [review]

**Comment by Gymnasiast** [comment]
We have had two reports from people who suddenly cannot open `develop` versions any more on macOS. Can you come to Discord please?

**Comment by adam-bloom** [comment]
Dependencies reverted for Xcode build in #14223.
Full error for future context:
```
Dyld Error Message:
  dyld: Using shared cache: 77B63435-1866-32DD-98A1-47090B666EFA
Library not loaded: @rpath/libbrotlidec.1.dylib
  Referenced from: /private/var/folders/_3/d_jnkp554cl7q4n7_zkwcfd00000gn/T/AppTranslocation/C5807363-E919-43ED-ABA8-E06ECC4B748B/d/OpenRCT2 2.app/Contents/Frameworks/libfreetype.6.dylib
  Reason: image not found
```

**Pull request merged**
