### PR TITLE
Rename event_07 to periodic_update

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
Initially split off from #7889, but opted for `periodic_update` rather than `fixed_update`.

### CODE REVIEW

**Comment by janisozaur** [comment]
What does `fixed_update` mean here?

**Comment by Gymnasiast** [comment]
Judging from the code, it gets called every 1000 ticks. (As opposed to other update functions which get fired whenever the window _needs_ updating, rather than on a fixed schedule.)

**Comment by AaronVanGeffen** [comment]
I agree `fixed_update` isn't the most intuitive either. As the event in question only fires every 1000 ticks, perhaps something like `deferred_update` or even `delayed_update` would be more appropriate?

**Comment by IntelOrca** [comment]
`periodic_update`

**Pull request merged**
