### PR TITLE
Fully reproducible dev environment

### PR DESCRIPTION
**Pull request by jappeace**
This file allows one to develop within a nix shell environment.
It isolates the build inputs to just the ones specified in here. Making sure that everyone builds against the same system libraries (or else they are not found). In the nix shell it is also guaranteed the same build tools are used.

Doesn't work on windows I believe, but osx is supported (albeit I can't test that, cause poor).

To use this, get nix: https://nixos.org/nix/, then go to root of project, `nix-shell --pure`, then do the regular build setup, `mkdir build`, `cd build`, `cmake ../`, `make`.

### CODE REVIEW

**Comment by jappeace** [comment]
@YJSoft try it now, I applied these changes: https://github.com/NixOS/nixpkgs/issues/32105
Foundation is apparently some standard mac datastructures and services for any app to use: https://developer.apple.com/documentation/foundation

Mac port probably needs that to connect to OSX'es window manager etc.

**Comment by janisozaur** [comment]
That looks interesting. Would you recommend running nix as part of the CI build? How can I check what packages (and versions) are available in each version of nix? Can I list files in each of the packages, like e.g
 https://packages.ubuntu.com/bionic/amd64/cmake/filelist? Does it support 32-bit environments in 64 bit hosts?

**Comment by YJSoft** [comment]
Still not working(had to change `pkgs.libobjc` to `pkgs.darwin.libobjc` due to errors)

https://gist.github.com/YJSoft/cf6d5da7d2d0772853c89b06c5e247b4

**Comment by jappeace** [comment]
@YJSoft  I'm not really sure what to do about that, currently I'm installing OSX on a vm for testing.

**Comment by janisozaur** [comment]
@jappeace LGTM, but can you explain what does

> It doesn't build as I've not configured cmake in this nix setup.

in https://github.com/OpenRCT2/OpenRCT2/pull/8017#issuecomment-423816357 mean?

**Comment by jappeace** [comment]
@janisozaur I was talking about the `nix-build` command, These changes made that work: https://github.com/OpenRCT2/OpenRCT2/pull/8017/commits/d66b3c667a50b546317db3e414007f73b9e2bd1e

Rather than opening a shell, it just tells the system to build it. Giving you a result symlink which points to the resulting output folder in the nix store.

**Pull request merged**
