### PR TITLE
Implement multithreaded drawing

### PR DESCRIPTION
**Pull request by ZehMatt**
There are a couple of issues that needs fixing before this is ready.

### CODE REVIEW

**Comment by IntelOrca** [comment]
Temporary solution, we should remove the globals altogether in the future and pass them as parameters.

I am curious though, how many extra FPS do you get with this?

**Comment by ZehMatt** [comment]
I have no idea if I broke benchgfx somehow since everything works fine in-game, the reason I say it is because of:
```develop:
> openrct2 benchgfx parks/bpb.sv6
Engine: Software
Render Count: 60
Zoom[0] average: 0.072873s, 14 FPS
Zoom[1] average: 0.031728s, 32 FPS
Zoom[2] average: 0.014515s, 69 FPS
Total average: 0.039705s, 25 FPS
Time: 2.38233s

PR:
> openrct2 benchgfx parks/bpb.sv6
Engine: Software
Render Count: 60
Zoom[0] average: 0.015528s, 64 FPS
Zoom[1] average: 0.007817s, 128 FPS
Zoom[2] average: 0.004416s, 226 FPS
Total average: 0.009254s, 108 FPS
Time: 0.55522s```

**Comment by ZehMatt** [comment]
> Command line giant screenshot also works and is quicker I think when multithreading is on.

I think we could force it on for some things like that, the benchgfx also currently relies on the config.ini which should be addressed.

**Comment by Gymnasiast** [comment]
(Both on your branch)
With multithreading off: 32
With it on: 67.

**Pull request merged**
