### PR TITLE
Move extern "C" {} blocks to headers

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by Gymnasiast** [comment]
You updated your own PR? :P

**Comment by janisozaur** [comment]
I also like my own posts on Facebook ;)

**Comment by Gymnasiast** [comment]
Ah well, no problem: I downvoted it. Need to keep things balanced, don't you? :-P

**Comment by ZehMatt** [comment]
200 files changed, excellent 🥇

**Comment by janisozaur** [comment]
This PR is ready now. @IntelOrca @marijnvdwerf can you check/merge?

**Comment by janisozaur** [comment]
@marijnvdwerf didn't mean to, but sure, I can squash it.

**Pull request merged**
