### PR TITLE
Trap mouse to game windows. Fixes #1997

### LINKED ISSUE #1997: Add an option for Mouse Capture
Would make playing in a window much easier.

### PR DESCRIPTION
**Pull request by runelaenen**

### CODE REVIEW

**Comment by runelaenen** [comment]
I did not test it on linux since I don't have access to a linux machine. But it should be tested. I'm not sure the SDL call works correctly (some posts on the internet are saying it doesn't, but those posts all seem to be quite old)

**Comment by HaasJona** [comment]
Works fine in Linux. (Fedora 22)

**Comment by HaasJona** [comment]
screen1

**Comment by runelaenen** [comment]
I know the button should work :P
But does it also does what it should when it's enabled?

**Comment by IntelOrca** [comment]
Why is it an option (why would you want it off)? Isn't the purpose of this to allow drag scrolling?

**Comment by janisozaur** [comment]
drag scrolling? rather edge scrolling. I'd like that as an option, especially when developing and having to switch between windows mouse-lock would stand in my way.

I haven't tested it myself yet.

**Comment by HaasJona** [comment]
Yes, the mouse is trapped on Linux if you enable the checkbox.

**Comment by LinusU** [comment]
@runelaenen I might be wrong but I'm pretty convinced that this should work

```diff
- if (gConfigGeneral.trap_cursor)
- 	SDL_SetWindowGrab(gWindow, SDL_TRUE);
- else
- 	SDL_SetWindowGrab(gWindow, SDL_FALSE);
+ SDL_SetWindowGrab(gWindow, gConfigGeneral.trap_cursor)
```

It works because `SDL_bool` is defined as such and thus just wants `0` or `1`.

```c++
typedef enum SDL_bool {
       SDL_FALSE = 0,
       SDL_TRUE  = 1
} SDL_bool;
```

**Comment by runelaenen** [comment]
@intelOrca I've made it an option because I wouldn't like my mouse to be trapped when playing windowed :/
@Linus Yes indeed, that should also work I guess.

**Comment by IntelOrca** [comment]
@LinusU Its not good practice to do that though. It would be better to have a helper function to convert it still using an IF or a ternary.

**Comment by IntelOrca** [comment]
How do you untrap your mouse without using ALT-TAB or Windows key or other OS overrides?

**Comment by LinusU** [comment]
@IntelOrca Hmm, actually now that you point it out I kind of agree. Although I don't now any library that doesn't use 0 for false and 1 for true. That is how bool works.

I guess that the following would work as well.

```c++
SDL_SetWindowGrab(gWindow, gConfigGeneral.trap_cursor ? SDL_TRUE : SDL_FALSE)
```

**Comment by IntelOrca** [comment]
There are many many functions which use 0 as a success callback, any other number as an error code.

**Comment by runelaenen** [comment]
I've fixed the wrong placement of the finances and cheats checkbox.

Also, about the alt-tabbing. I don't think that should be possible. If you want to trap your cursor, you can trap your cursor. If you want to multitask while playing you simply disable the option I'd say...

**Comment by HaasJona** [comment]
I would like to have the mouse trapping option, too. I don't mind hitting alt+tab (which works fine) and if you're really stuck you can always save and quit the game.

**Comment by IntelOrca** [comment]
@runelaenen I thought the point of mouse trapping was for edge scrolling, so yes you want to multi-task but only when you want to multi-task invoked by some key combination.

**Comment by runelaenen** [comment]
Yes it would be for the edge scrolling, however that also works without it (at least on my pc). Also, I haven't implemented this because I wanted it (I don't think I'd use it) but because there was an open issue :p

**Comment by PFCKrutonium** [comment]
Alt tabbing etc should be possible, and should release the mouse - as @IntelOrca said, it's more of a scrolling in a Window issue.

**Comment by HaasJona** [comment]
The patch needs to be updated as the string id is now used by the steam overlay detection.

**Comment by LinusU** [comment]
@runelaenen I would really like this to be implemented, do you have time to rebase or are you okay with me doing it?

**Pull request closed without merging**
