### PR TITLE
fix heartline twister airtime ratings

### PR DESCRIPTION
**Pull request by e-foley**
Addresses bug relevant to #2031 and provides alternate fix to #2064

### CODE REVIEW

**Comment by e-foley** [comment]
Sorry for the accidental "revert" commits; I'm relatively new to GitHub.

**Comment by IntelOrca** [comment]
Please squash them into one commit.

http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

**Comment by IntelOrca** [comment]
Why do you think no excitement penalty should occur any more?

**Comment by pizza2004** [comment]
It doesn't make sense for gameplay that it would ever be intended that the ride should be able to incur a penalty that would bring it down below 0 in rating, therefore it makes sense that it's probably an error in the coding that just slipped past being noticed in the first place.  It is therefore on us to decide what the correct behavior is for the roller coaster instead of just patching it up so it looks nice.  I can understand a desire to wait until we have the game fully decompiled before we do such a thing, but the current method of fixing the bug only complicates the code and leaves room for more errors to pop up.

That's why I think we need a better method.  However I will posit that perhaps there's a better way to balance it.  However, the method in this commit is almost definitely the proper method, as I imagine the bug was simply that the penalty was supposed to be applied to this ride after the bonus was already applied, in order to cancel out the bonus after 96, and it was just implemented improperly in the original code.  I think we should have a look at what sort of excitement ratings you'd see with this change, and what the overall difference that ends up being for the ride is.

**Comment by e-foley** [comment]
Every other rating adjustment is careful to ensure ratings never drop below zero.  These penalties are applied by effectively multiplying the excitement rating by some factor less than one.  The code I replaced is the only instance where a value is explicitly subtracted from the excitement rather than applied as a multiplicative factor, and as such is the only operation that allows the excitement rating to drop below zero (which causes an underflow in the original game).

The biggest tell is how the nausea rating is affected.  Unlike every other ride, the nausea doesn't increment on a heartline twister until 96 ticks (1.98 seconds) or more of airtime.  This strikes me as arbitrary to the point of being buglike.

There's no way to prove it, but it seems to me that the old code reeks of a botched min operation.

**Comment by IntelOrca** [comment]
But rather than preventing it from going below 0, you have removed the penalty altogether.

**Comment by pizza2004** [comment]
He makes an excellent point about nausea.  I believe the properly coded original version would simply look like this:

```C
static void ride_ratings_apply_adjustments(rct_ride *ride, rating_tuple *ratings)
{
	rct_ride_type *rideEntry;
	
	rideEntry = gRideTypeList[ride->subtype];

	// Apply ride entry multipliers
	ratings->excitement += ((ratings->excitement * rideEntry->excitement_multipler) >> 7);
	ratings->intensity +=  ((ratings->intensity  * rideEntry->intensity_multipler ) >> 7);
	ratings->nausea +=     ((ratings->nausea     * rideEntry->nausea_multipler    ) >> 7);

	// As far as I can tell, this flag detects whether the ride is a roller
	// coaster, or a log flume or rapids. Everything else it's not set.
	// more detail: https://gist.github.com/kevinburke/d951e74e678b235eef3e
	uint16 flags = RCT2_GLOBAL(0x0097D4F2 + ride->type * 8, uint16);
	if (flags & 0x80) {
		uint16 totalAirTime = ride->total_air_time;
		ratings->excitement += totalAirTime / 8;
		ratings->nausea += totalAirTime / 16;
		if (rideEntry->flags & RIDE_ENTRY_FLAG_11) ratings->excitement -= (totalAirTime - 96) / 8;
	}
}
```

**Comment by pizza2004** [comment]
I vote we track down Chris Sawyer and grill him on what he intended a single roller coaster to do 10 years ago! :D

**Comment by pizza2004** [comment]
I'd say at the very least, even ignoring the penalty to excitement, he's right about nausea.  It should be applied to the entire airtime, rather than only starting to apply about 96.  That's an easy bug to fix whether you accept this PR or not.

**Comment by e-foley** [comment]
@IntelOrca, It's a matter of semantics then.  I think the inability to gain excitement for airtime in excess of 2 seconds is penalty enough--it's certainly a penalty relative to every other roller coaster.

**Comment by pizza2004** [comment]
You should at least does what he says related to the commits to get rid of the revert commits.  That would be helpful to get it merged I would say.

**Comment by IntelOrca** [comment]
Can we find out what ride objects have RIDE_ENTRY_FLAG_11?

**Comment by e-foley** [comment]
@pizza2004, You're right.  I tried the squash thing but found that syncing erased my squash.  I'm reading up on Git operations right now so that I can make this change go through.  Thanks.

**Comment by duncanspumpkin** [comment]
@e-foley just do a bit rebase -i and you can squash all the commits you want.

**Comment by e-foley** [comment]
@duncanspumpkin, that did the trick.  Thanks for your help.

**Comment by IntelOrca** [comment]
@e-foley I am ok to merge this, but could you use an #ifdef so its possible to go back to the original behaviour?

e.g.
```c
#ifdef ORIGINAL_RATINGS
    // original code
#else
    // your new calculation code
#endif
```

**Comment by e-foley** [comment]
@IntelOrca, how does this look?

**Pull request merged**
