### PR TITLE
Fixes #3100

### LINKED ISSUE #3100: Footpath doesn't connect to ride entrance and ride exit.
**OS:** Windows 10 (32 bits)
**Version:** 0.0.4
**Commit:** latest build.

- [ ] Reproducable in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
~~- I do not know how to reproduce this.~~
It happens if your ride have multiple stations (how to reproduce? See this image)
Image

**Video:**
This happens: https://vid.me/7fxf
This is expected:: https://vid.me/M1iK

**Save game:**
[Vistas Infernales.txt](https://github.com/OpenRCT2/OpenRCT2/files/160616/Vistas.Infernales.txt)

### PR DESCRIPTION
**Pull request by Wirlie**
Fix a bug that prevents connect footpaths to the ride entrance/exit with multiple stations (Fixes #3100).

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
This breaks park entrances. The issue is not caused by this its caused by whatever is setting sequence to none zero.

**Comment by IntelOrca** [comment]
I was just about to say it looks like its related to multiple stations.

**Comment by Wirlie** [comment]
I decided to help translate the game instead of "improving" (worsen) the game. Sorry, this will not happen again, thank you very much, good day!

**Comment by duncanspumpkin** [comment]
@wirlie it's fine at least you found where the bug manifested. Made it quick to find the source.

**Comment by IntelOrca** [comment]
@Wirlie Don't be harsh on yourself, I'm the one who merged it anyway. Your other code contributions have been fine.

**Pull request merged**
