### PR TITLE
Gigacoaster Track Expansion

### PR DESCRIPTION
**Pull request by karst**
This PR adds vertical pieces to the Gigacoaster using the sprites from the impulse coaster.
It looks a tad odd, but Intamin actually uses this technique themselves between square and triangle spine.
image

This is currently a draft and I would like to get some tips on this PR for the improvement of the coordinates of the twists.

Here's an image of the new paint:

image

### CODE REVIEW

**Comment by oli414** [comment]
Your Readme changes are better suited for a separate PR I'd say

**Comment by karst** [comment]
Yea that's already in #17307, originally was working in this branch but forgot to remove it here 😅

**Comment by karst** [comment]
There's finetuning necessary for the parameters of either sprite 19708 or sprite 19697 or both. 

I have re-enabled giga_rc_track_right_quarter_turn_1_90_deg_up. These parameters all need to be finetuned.

**Comment by frutiemax** [comment]
How is this different from merging two roller coasters together?

**Comment by karst** [comment]
> How is this different from merging two roller coasters together?

You can currently not do this with the impulse coaster as the impulse coaster is off-center. This would be a lot cleaner solution than any currently available. It's not perfect. But until X7 pushes his Intamin tracks it's the best we got.

**Comment by oli414** [comment]
I can see the appeal, the tracks don't match perfectly, but I'm guessing this might be a good start for extending the current track pieces offerings for open graphics once we get to that stage

**Comment by karst** [comment]
I have gotten to a point where I am gonna need some help. To my testing it works well. I am happy with the looks but if something feels completely off please let me know and I'll see if I can patch some things up. I have only noticed one issue with graphics and that's that if you put the track piece in a specific location of the screen it a piece of 90 deg track renders on top of the twist. But usually it renders just fine. I have checked with boundboxes, even by making them smaller with no chance of overlap but it hasn't fixed the issue.

This could use some testing now.

Also I tried fixing the Lint Commit Message but github is not letting me squash the  commits.

**Comment by karst** [comment]
After feedback in discord I have adjusted some issues with the sprites. 
I have been able to do everything but sprite 19707. Does someone know how to fix thisone by any chance?

**Comment by karst** [comment]
Seems like there's still more issues than I originally thought. Need to work on it more.

**Comment by karst** [comment]
I am running into some issues with the bounding box. The track renders different depending where it's located in the viewport. So that means sometimes a vertical piece is rendering over a quarter turn and sometimes it's under it. It's extremely odd.

I need to work a bit more on 19708, might need to exchange the sprite entirely see if that looks any better.

Feel free to test this again while I continue working on this, should be a lot better than it was before already.

**Comment by karst** [comment]
This project is getting a bit ambitious. I am splitting it up into two parts. I might even exchange the sprites for new ones from X (if he allows it) to expand the set further in part 2. But I do wonder if people still want me to finish this specific PR if I am gonna replace them at some point anyhow. as I don't want people to start using the sprites in their builds for them to look different in a few months.

**Pull request closed without merging**
