### PR TITLE
Change korean won currency correctly

### PR DESCRIPTION
**Pull request by telk5093**
into utf-8

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Have you tested this with other languages that _don't_ use UTF-8, like UK English?

**Comment by Gymnasiast** [comment]
I just tested it. It makes the sign show up as `?` in most languages.

**Comment by IntelOrca** [comment]
You need to add another field to currency so that there is a string for sprite and a string for TTF. So long as the TTF string is supported in most TTF fonts.

**Comment by telk5093** [comment]
I tested it just now, and displayed correctly in korean OS.
Moreover I think most user will be korean who uses ₩(won).

image

**Comment by IntelOrca** [comment]
The currency structure needs altering to include ASCII version (if unicode can't be used) and unicode version.

**Comment by telk5093** [comment]
Does Euro as well?

**Comment by IntelOrca** [comment]
No, it needs it for all currencies - apart from $, but for consistency can also be done for dollar.

**Comment by telk5093** [comment]
I hope that it becomes earlier.
That is out of my ability to make code about it. :cry:

**Comment by IntelOrca** [comment]
This is now implemented.

**Pull request closed without merging**
