### PR TITLE
Scenery window scrolls wrongly, fixes #3210

### LINKED ISSUE #3210: Scenery window scrolls wrongly after selecting item
**OS:** Windows 7

Explanation of the issue...

- [Unsure] Reproducable in RCT2 (vanilla)?
- [Occurs in both SP and MP] Multiplayer?

**Steps to reproduce:**
1. Select a scenery object on the last on one of the last rows.
2. Let the window auto-adjust itself, and when you scroll the cursor back over the  scenery window, it will crop wrong and at least one of more of the rows underneath the selected object would be blank.

**Screenshots / Video:**
rct2 selectino problem

### PR DESCRIPTION
**Pull request by marcovmun**
Fix original bug where the scrollbar of scenery window scrolls too far.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Doesn't work correctly unfortunately:
- Go to the Walls and Roofs tab
- Select something on the bottom row
- Move out of the window and back in again
- The window isn't scrolled far enough

**Comment by marcovmun** [comment]
The problem wasn't that the window didn't scrolled far enough, but vertically it didn't fit 5 items. So I solved that.

**Comment by Gymnasiast** [comment]
Still doesn't work, unfortunately. It scrolls one row less than it should.

**Comment by marcovmun** [comment]
Can you show me a picture what you mean? I don't exactly what you mean

**Comment by Gymnasiast** [comment]
scr189
scr190
scr191

**Comment by marcovmun** [comment]
Thank you for the example. I found the logical error that I made. Now it should work in all scenarios. Fist time I couldn't reproduce because bug because i had other scenery items selected

**Comment by Gymnasiast** [comment]
@marcovmun Yes, you have to rebase to `develop`.
From the command line (assuming you have the OpenRCT2 repository as `upstream`) :
```
git fetch upstream develop
git rebase -i upstream/develop
```
It should then stop and tell you to correct the conflict. Open the `scenery.c` file and search for `=======` (conflicts are marked like that). Solve the conflict, then do
```
git add src/windows/scenery.c
git rebase --continue
```
It should now complete the rebase. Then you do
```
git push -f
```
The -f parameter is needed because of the rebase, as you're rewriting the history.

**Comment by Gymnasiast** [comment]
Seems to work well now. (Apart from needing a rebase.)
Could you add the following line to the changelog:
```
- Fix: [#3210] Scenery window scrolls too far
```

**Comment by marcovmun** [comment]
Thanks for the explanation of the rebase. I've done it as you described.

**Comment by Broxzier** [comment]
One issue with this is that when you try to scroll, the view suddenly jumps up. Setting the body height to `max(current_height, calculated_height)` will probably solve it.

**Comment by marcovmun** [comment]
Don't merge it yet. I found an issue that is maybe related to my code changes. It happens when you switch between the tabs.

**Comment by marcovmun** [comment]
It is fixed. i've some code rewritten for a faster execution time, now the scrollbar work correctly again.
And I repair a other bug that i found in mine piece of code.

**Comment by marcovmun** [comment]
Now I found what the bug really was. It was not the execution time, but the function window_scenery_update_scroll was sometimes called twice when you switch between tabs. The first time the function was called the window size was not correct. Now is the window_scenery_update_scroll always called once.
image
_Issue_

**Comment by Broxzier** [comment]
One thing I noticed is that when you select a piece of scenery from the second row or lower, it makes the scroll area jump when you switch between tabs.

**Comment by marcovmun** [comment]
@Broxzier , do you mean the same thing as I mentioned in a previous reaction? Or do you mean something different?

> Example of the bug: https://vid.me/lr0k

**Comment by Gymnasiast** [comment]
Seems to work correctly now, :+1: to merge AFAIC.

**Pull request merged**
