### PR TITLE
License header

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by IntelOrca** [comment]
I was planning on all the headers being changed to something simpler and no direct credit to a person, only a reference to contributors.md. Its not fair for me to have credit over everyone else on every source file.

**Comment by janisozaur** [comment]
As per https://www.gnu.org/licenses/gpl-3.0.en.html#howto you cannot really change contents of this header. What would you rather the copyright line look like?

**Comment by ccfreak2k** [comment]
While it's all well and good to be modest, assigning copyright is extremely important for software projects in cases like relicensing, as can be seen in the cases of [Mozilla](http://www-archive.mozilla.org/MPL/relicensing-faq.html) and [Dolphin](https://dolphin-emu.org/blog/2015/05/25/relicensing-dolphin/).

**Comment by Gymnasiast** [comment]
(As far as my understanding of copyrights and attribution goes:)
Existing attributions should be left intact, but can be complemented by `OpenRCT2 authors`. Files without attributions can gain a `OpenRCT2 authors` attribution, and anyone creating a new file should put his/her name and `OpenRCT2 authors`.

**Comment by IntelOrca** [comment]
@Gymnasiast The existing attributions are wrong, file comment headers were just copied from one place to another and not updated, meaning some sources have authors that haven't edited it.

When code is refactored, code gets moved between files and its impossible to correct the authors. So its better just to simply not have any authors with only a reference to contributors.md or git.

As for this PR, me and @janisozaur were discussing a new header but we didn't conclude one as we were going to wait a bit. This is the most recent draft:

```c
#pragma region Copyright (c) 2014-2016 OpenRCT2 Developers
/*****************************************************************************
 * OpenRCT2, an open source clone of Roller Coaster Tycoon 2.
 *
 * OpenRCT2 is the work of many authors, a full list can be found in contributors.md
 * For more information, visit https://github.com/OpenRCT2/OpenRCT2
 *
 * OpenRCT2 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * A full copy of the GNU General Public License can be found in licence.txt
 *****************************************************************************/
#pragma endregion
```

**Comment by janisozaur** [comment]
I've updated this PR with most recent version we agreed on.

**Comment by janisozaur** [comment]
Updated

**Comment by IntelOrca** [comment]
So we all okay to merge this?

**Comment by Gymnasiast** [comment]
Yes. Copyright notices are not required (not under US and European laws at least, copyright on your work exists automatically) and the ones we had were incomplete and thus incorrect.

**Pull request merged**
