### PR TITLE
AT&T

### PR DESCRIPTION
**Pull request by janisozaur**
This is mainly porting of Intel syntax to AT&T, which is more widely used outside of MS world.

This in turn enables usage of clang, which I also added to the build matrix. See useful warnings it can generate in current build: https://travis-ci.org/janisozaur/OpenRCT2/jobs/86923568

This should help a lot in porting to OS X (#1993) as well as be a good prep for upcoming clang integration from MS.

I've taken a look at generated output from both syntaxes and it is 100% the same (see both functions here: https://gist.github.com/janisozaur/5129cb3cdc263b07c9ad). Resulting code also works on my machine when compiled with either gcc or clang just as it used to.

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
Ahh I despise AT&T syntax its impossible to read. It makes so little sense compared to intel.

**Comment by IntelOrca** [comment]
I thought OSX had too many issues with 32-bit for it work well.

**Comment by pizza2004** [comment]
I'm more of a fan of Verizon myself.

**Comment by PFCKrutonium** [comment]
Wind Mobile - If I had a phone.

**Comment by janisozaur** [comment]
Facts:
* AT&T syntax, although slightly different from Intel's, compiles to **exactly** the same binary, I attached the gist [0] as proof of that, I can replicate it on Travis if you wish
* AT&T syntax is much more common than Intel outside of Windows/MSDOS [1][2][3]
* It enables clang to compile openrct [4], this version works ok on my machine
* With minor changes [5], openrct2 builds on OS X now as well [6], though I have no way of checking if it works

Opinions:
* @duncanspumpkin mentioned he does *not like* syntax.
* @pizza2004 suggests building for OS X is not viable before full reverse is reached.
* w.r.t. this comment: https://github.com/OpenRCT2/OpenRCT2/pull/2105#issuecomment-150376897 I would assume up until recently the same could be said about Linux builds.
* I launched the game and looked around if anything appeared to be broken and nothing did. I haven't got any strict protocol nor did I use any other tools than my eyes to check, thus I list it as opinion.

I don't mean to step on anyone's toes, but I provided a clear list of improvements which can happen once this is merged.

I hope that justifies this pull request. If not, I'm happy to discuss it further.

[0] https://gist.github.com/janisozaur/5129cb3cdc263b07c9ad
[1] https://en.wikipedia.org/wiki/X86_assembly_language#Syntax
[2] AT&T is the default syntax of `objdump`, sorry, no link for that
[3] https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/arch/x86/boot/header.S
[4] https://travis-ci.org/OpenRCT2/OpenRCT2/jobs/86925334
[5] https://github.com/janisozaur/OpenRCT2/compare/at-and-t...janisozaur:osx?expand=1
[6] https://travis-ci.org/janisozaur/OpenRCT2/builds/87005025

**Comment by LinusU** [comment]
Wow! Awesome work, I'll try this on my mac as soon as I get the chance.

:metal: :+1:

**Comment by duncanspumpkin** [comment]
@janisozaur I've removed my comment, as you rightly said its an opinion. I will try double check the asm, although there isn't much point since as you have shown it compiles to the same byte code.

**Comment by duncanspumpkin** [comment]
I've double checked the asm and it appears to match as also confirmed by the compiled comparison.

**Comment by IntelOrca** [comment]
I also don't like the syntax, but this should be the only ASM needed left.

**Comment by Overv** [comment]
Who in their right mind prefers AT&T syntax? The assembly has become a lot more verbose and harder to read.

**Comment by vzybilly** [comment]
I use NASM which I think is also intel syntax, on linux, meaning it's not just windows that uses it...

**Pull request merged**
