### PR TITLE
Refactor NewsItem into namespace and Pascal Case

### PR DESCRIPTION
**Pull request by pizza2004**

### CODE REVIEW

**Comment by tupaschoal** [comment]
Seems like you need to rebase to drop the things that have already been merged: https://github.com/OpenRCT2/OpenRCT2/wiki/Rebase-and-Sync-fork-with-OpenRCT2

**Comment by pizza2004** [comment]
Yeah, I switched to my develop but apparently improperly rebased it against upstream develop before making this branch.  I fixed that now.  Let's see how the checks go.

**Comment by pizza2004** [comment]
I did this since this files is only specifically for news items as far as naming goes.  I'll change it if you guys would prefer it be News.

**Comment by tupaschoal** [comment]
Yeah, I think we can make it `News`, it already had such a namespace

**Comment by pizza2004** [comment]
My main question then is whether I should add "Item" back onto all the various fields, or continue using the shorter names that don't specify item?

**Comment by tupaschoal** [comment]
If it's in progress, make the PR a draft and mark it ready for review when it's done.

If it's done already, let us know :)

**Comment by pizza2004** [comment]
It's done unless someone wants me to change something.

**Pull request merged**
