### PR TITLE
Cleanup contributors file

### PR DESCRIPTION
**Pull request by SijmenSchoon**
Added real names from GitHub profiles, and changed my old username (Vijfhoek) to my new one (SijmenSchoon) (proof: https://github.com/Vijfhoek/oyoyo will redirect to /SijmenSchoon/oyoyo)

### CODE REVIEW

**Comment by JarnoVgr** [comment]
Not sure if everyone wants to be added by their real name. Although then they should also not put names on their Github pages.

**Comment by SijmenSchoon** [comment]
> Although then they should also not put names on their Github pages.

Yeah, that's what my reasoning was as well

**Comment by Goddesen** [comment]
I am very much against this. I myself am fine with my real name being listed, I did put it there myself already after all, but some might object to having their name put out there like that - even if it is indeed already listed on their Github profile.

**Comment by JarnoVgr** [comment]
Well this was merged quickly. Why didn't you allow more time for discussion as not everyone liked it? @Gymnasiast

**Comment by Gymnasiast** [comment]
@JarnoVgr Because I pressed that button before Goddesen's comment showed up. If there is a really compelling reason to revert, I'll do that (or another team member will do it).

**Comment by Goddesen** [comment]
In my mind this equates with distributing personal information about people without their consent. If I put my nickname on something to be distributed that is one thing, but having my name distributed alongside this without asking is simply not okay.

You could make the argument that having put my real name on my Github profile and contributing to this project has already put my information out there, but seeing as this project is distributed through other means from sources other than Github this is not the same.

**Comment by SijmenSchoon** [comment]
> but seeing as this project is distributed through other means from sources other than Github this is not the same.

That's a good point. I agree with reverting this.

**Comment by Gymnasiast** [comment]
I don't. You do a contribution _using the GitHub profile where you put your name yourself_. It's not like we're scraping the internet to find all of your personal information.

**Comment by Goddesen** [comment]
If I decide to not disclose my real name in the files distributed with a project there might be a good reason for me to do so, whatever that reason might be. If the files were to be distributed solely through Github I would have no problem with this; putting one's real name on the profile seems to me an implicit permission to distribute profile information through Github.

However, when the project is being distributed from other sources (some of which are unofficial!) like openrct2.website and openrct2.org, this is not the same, as it has 1) nothing to do with Github, and 2) nothing to do with development; the latter of which being the main reason I want my Github nickname associated with my real name.

I am aware that it is absolutely trivial to look up someone's Github profile, but for me this is mostly a matter of principle - distributing more information about people than they have explicitly (or, in the case of Github, implicitly) consented to is something I'm not comfortable with.

**Comment by Nubbie** [comment]
My say about this would be that, the people which added their GitHub name to the document, should choose with how much info about themselfs they feel comfertable to share (their real name).
What I mean by that, my own personal name would be optional depending if I want it or not to be put in regardless where it comes from, especially if I have the option to choose if I want to write out my personal name or not. :U

**P.s;** _Matte_ is my nickname ;p (means 'math', my real name is _Mattias_)

**Comment by Rodbourn** [comment]
Why not have contributors add their name through a pull request themselves?

**Comment by Goddesen** [comment]
@Rodbourn This has been the case thus far.

**Comment by Rodbourn** [comment]
@Goddesen sounds like a good way to keep doing it.  It only makes sense, it's a form of consent and lets them choose to use their own names.

**Comment by SijmenSchoon** [comment]
I suppose we'll have to see what the affected users think about this.

**Comment by Goddesen** [comment]
@SijmenSchoon Sure, but this PR will then act as a precedent in future cases where someone might object to having their names added.

Dev1: *I don't like that my name was added.*
Dev2: *Don't worry about it, it's been done before.*

**Comment by SijmenSchoon** [comment]
I don't think I see your point entirely. If those devs read through this thread, they'll see that it was a bad idea and has been undone.

**Comment by Gymnasiast** [comment]
The commit in question has been removed from the history.

**Pull request merged**
