### PR TITLE
Close #12409: Refactor CONSOLE_INPUT to use strong enum

### LINKED ISSUE #12409: Refactor CONSOLE_INPUT to use strong enum

### PR DESCRIPTION
**Pull request by BryanDiLaura**
I didn't specify a type for the strong enum. Can add it if needed.

### CODE REVIEW

**Review by AaronVanGeffen — CHANGES_REQUESTED** [review]
You also have to change the new enum class to conform to our code style, that is UpperCamelCase for class names.

**Comment by BryanDiLaura** [comment]
D'oh. I also realized I didn't follow other pieces of the contributing guide. Fixing...

**Comment by AaronVanGeffen** [comment]
Please re-use the same PR. Just push additional commits.

**Comment by BryanDiLaura** [comment]
Sorry I'm a dingus 🤦‍♀️.  I think that should be in line with the style guide now. 

I notice that the style guide on the [wiki](https://github.com/OpenRCT2/OpenRCT2/wiki/Coding-Style) doesn't mention classes. Is there someplace with a more complete style guide?

**Comment by duncanspumpkin** [comment]
The style guide does mention classes. See the struct part.

**Comment by AaronVanGeffen** [comment]
Looks much better now, thanks.

Per our contributing guidelines, we normally don't merge `develop` into branches. Instead, we would like PRs to be rebased when conflicts arise. That's not the case here, fortunately, so we can just squash-merge instead.

**Review by duncanspumpkin — APPROVED** [review]

**Pull request merged**
