### PR TITLE
Fix Cmake compilation on macOS 10.12.6

### PR DESCRIPTION
**Pull request by marijnvdwerf**

### CODE REVIEW

**Comment by janisozaur** [comment]
LGTM, although this feels a bit hacky.

**Comment by marijnvdwerf** [comment]
@janisozaur Better like this?

**Comment by marijnvdwerf** [comment]
For reference, this is what the different package-finding functions return:

```
-- find_library
--   SDL2-FIND: /usr/local/lib/libSDL2.dylib
-- pkg_check_modules
--   SDL2-PKG_CFLAGS: -D_THREAD_SAFE;-I/usr/local/include/SDL2
--   SDL2-PKG_CFLAGS_I: 
--   SDL2-PKG_CFLAGS_OTHER: -D_THREAD_SAFE
--   SDL2-PKG_FOUND: 1
--   SDL2-PKG_INCLUDEDIR: /usr/local/include
--   SDL2-PKG_INCLUDE_DIRS: /usr/local/include/SDL2
--   SDL2-PKG_LDFLAGS: -L/usr/local/lib;-lSDL2
--   SDL2-PKG_LDFLAGS_OTHER: 
--   SDL2-PKG_LIBDIR: /usr/local/lib
--   SDL2-PKG_LIBRARIES: SDL2
--   SDL2-PKG_LIBRARY_DIRS: /usr/local/lib
--   SDL2-PKG_LIBS: 
--   SDL2-PKG_LIBS_L: 
--   SDL2-PKG_LIBS_OTHER: 
--   SDL2-PKG_LIBS_PATHS: 
--   SDL2-PKG_PREFIX: /usr/local
--   SDL2-PKG_STATIC_CFLAGS: -D_THREAD_SAFE;-I/usr/local/include/SDL2
--   SDL2-PKG_STATIC_CFLAGS_I: 
--   SDL2-PKG_STATIC_CFLAGS_OTHER: -D_THREAD_SAFE
--   SDL2-PKG_STATIC_INCLUDE_DIRS: /usr/local/include/SDL2
--   SDL2-PKG_STATIC_LDFLAGS: -L/usr/local/lib;-lSDL2;-lm;-liconv;-Wl,-framework,CoreAudio;-Wl,-framework,AudioToolbox;-Wl,-framework,ForceFeedback;-lobjc;-Wl,-framework,CoreVideo;-Wl,-framework,Cocoa;-Wl,-framework,Carbon;-Wl,-framework,IOKit
--   SDL2-PKG_STATIC_LDFLAGS_OTHER: -Wl,-framework,CoreAudio;-Wl,-framework,AudioToolbox;-Wl,-framework,ForceFeedback;-Wl,-framework,CoreVideo;-Wl,-framework,Cocoa;-Wl,-framework,Carbon;-Wl,-framework,IOKit
--   SDL2-PKG_STATIC_LIBDIR: 
--   SDL2-PKG_STATIC_LIBRARIES: SDL2;m;iconv;objc
--   SDL2-PKG_STATIC_LIBRARY_DIRS: /usr/local/lib
--   SDL2-PKG_STATIC_LIBS: 
--   SDL2-PKG_STATIC_LIBS_L: 
--   SDL2-PKG_STATIC_LIBS_OTHER: 
--   SDL2-PKG_STATIC_LIBS_PATHS: 
--   SDL2-PKG_VERSION: 2.0.5
--   SDL2-PKG_sdl2_INCLUDEDIR: 
--   SDL2-PKG_sdl2_LIBDIR: 
--   SDL2-PKG_sdl2_PREFIX: 
--   SDL2-PKG_sdl2_VERSION: 
```

**Comment by Gymnasiast** [comment]
@janisozaur Can you re-review this PR and merge it if it looks good?

**Pull request merged**
