### PR TITLE
Fix #21419: Cannot place walls underground beneath sloped tiles

### LINKED ISSUE #21419: Cannot place walls underground beneath sloped tiles with clearance checks disabled
### Operating System

Win 11

### OpenRCT2 build

Latest Dev (4-12-2023)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

Disabling clearance checks should allow for anything to be built anywhere, however, walls cannot be placed underground if the tile happens to be sloped.

### Steps to reproduce

Open file
Try to finish the wall by selecting it from scenery, and ctrl-clicking to place the 3 missing pieces. You'll find it's impossible under the sloped land. 
image

### Attachments

[CanPlaceWallsUndergroundSloped.zip](https://github.com/OpenRCT2/OpenRCT2/files/14319888/CanPlaceWallsUndergroundSloped.zip)

### PR DESCRIPTION
**Pull request by MaxMallon**
For https://github.com/OpenRCT2/OpenRCT2/issues/21419

### CODE REVIEW

**Review by tupaschoal — COMMENTED** [review]
Seems like you have commits from another PR mixed in here, can you drop them and leave just the slop/cheat one, please?

**Comment by MaxMallon** [comment]
> Seems like you have commits from another PR mixed in here, can you drop them and leave just the slop/cheat one, please?

How do I do that?

**Comment by tupaschoal** [comment]
You have to rebase the branch against the develop branch and then drop the commit that shouldn't be there. After that you force push

**Comment by MaxMallon** [comment]
> You have to rebase the branch against the develop branch and then drop the commit that shouldn't be there. After that you force push
What will happen to the other commits? I did make branches, so I'm not sure why they are even here.

**Comment by tupaschoal** [comment]
> What will happen to the other commits? I did make branches, so I'm not sure why they are even here.

So this is a brief explanation of how git works:
1. You have the `develop` branch, and then you create a branch `a` from that
2. You do some changes and commit to branch `a`, so now `a` is ahead of `develop` by 1 commit.
3. You create a third branch, `b`, using `a` as source. Now `b` is also ahead of `develop` by the same 1 commit, but it's kind of a copy, as soon as you create the branch, it's a completely independent thing, so if you modify `b` to drop that 1 commit, `a` won't get affected, because they are not tied to each other.

**Comment by MaxMallon** [comment]
> > What will happen to the other commits? I did make branches, so I'm not sure why they are even here.
> 
> So this is a brief explanation of how git works:
> 
> 1. You have the `develop` branch, and then you create a branch `a` from that
> 2. You do some changes and commit to branch `a`, so now `a` is ahead of `develop` by 1 commit.
> 3. You create a third branch, `b`, using `a` as source. Now `b` is also ahead of `develop` by the same 1 commit, but it's kind of a copy: as soon as you create the branch, it's a completely independent thing, so if you modify `b` to drop that 1 commit, `a` won't get affected, because they are not tied to each other.

I have been using git for nearly 10 years by now, and I still hate it xD I have my fork of the repo, with my local develop, from which I made branches in which I committed changes, which I pushed to my fork's remote. I then then made a pull request for my fork's remote, to be merged into openrct2's develop.
So, if I drop those commits, only on the branches, and not on my develop, it should be fine, right? I'll go and try that.

**Review by Gymnasiast — APPROVED** [review]
Tested, and cleaned it up a little bit. Seems to work correctly.

**Review by Basssiiie — APPROVED** [review]
Tested it and found no issues. Code looks good too. 🙂

afbeelding

**Comment by MaxMallon** [comment]
Glad to hear, thanks guys

**Pull request merged**
