### PR TITLE
Fix #19494: RCT1 sloped gates not imported correctly

### LINKED ISSUE #19494: RCT1 fence gate walls not imported properly if they were placed on slopes.
### Operating System

Linux (OpenSUSE Tumbleweed)

### OpenRCT2 build

OpenRCT2, v0.4.3

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error, This issue has to do with park objects and/or asset packs

### Describe the issue

RCT1 allowed you to place the gate variants of walls on slopes, it would just show the non-gate versions of the sprites.
With the sole exception of the creepy wall's gate variant which has completely unique slope sprites that don't seem to be in RCT2.
RCT2 however implemented a flag that allows walls to not be placeable on slopes and thus the duplicate sloped sprites were removed from the gate varients of walls.
However this is an issue as if you load an RCT1 park in OpenRCT2 that has any gate wall variants placed on slopes they will be invisible.

### Steps to reproduce

1. Open the attached sv4 file
2. The fence gate walls are invisible rather than using the non-gate version's sprites

### Attachments

RCT1:
Screenshot_select-area_20230226035122
OpenRCT2:
Screenshot_select-area_20230226035137
Save:
[gatesRCTOA  Acres.SV4.tar.gz](https://github.com/OpenRCT2/OpenRCT2/files/10833301/gatesRCTOA.Acres.SV4.tar.gz)

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by ZeeMaji** [comment]
Seems to be working properly, with the sole exception of the creepy gate but we're going to add the rct1 exclusive slope sprites to the rct2 object so it can be excused for now. Nice work!

Screenshot_select-area_20240127175236

**Review by tupaschoal — APPROVED** [review]
Tested and it works fine. Should it need a network bump?

**Comment by Gymnasiast** [comment]
@tupaschoal It does not - this code is only run upon the initial import of SV4 files, so doesn’t affect network play.

**Comment by Broxzier** [comment]
Also when a server loads a SV4 or SC4 file? I assume it imports it before sending a copy of the imported park to its clients.

**Comment by Gymnasiast** [comment]
> Also when a server loads a SV4 or SC4 file? I assume it imports it before sending a copy of the imported park to its clients.

It does - the clients do not have to import the SV4 themselves. Which makes sense, as what gets sent to the client is the _current_ state of the server, rather than the initial file that was loaded.

**Pull request merged**
