### PR TITLE
Feature #21430: Close windows on right click.

### PR DESCRIPTION
**Pull request by Harry-Hopkinson**
Adds the option to be able to close windows with right click. This is still a Work In Progress as I have to check that all windows function properly with this functionality.

### CODE REVIEW

**Review by AaronVanGeffen — COMMENTED** [review]
To be honest, I'm not sure about this feature. On the one hand, I think it's too niche. On the other, it is relatively contained, in that it doesn't touch a lot of the code base. All code carries a maintenance burden with it, though, and I'm not sure it's worth it.

**Comment by Harry-Hopkinson** [comment]
I think this feature is very useful for users playing with a lower `Window Scale Factor` as it can be quite difficult to close a window due to the size of the close button.

**Comment by Gymnasiast** [comment]
I agree with Aaron, it seems like unnecessary clutter. I’ll put a discussion label on it in case other team members want to weigh in, but I’m inclined to veto it. This is also why I so emphasise the need to ask us on Discord before implementing a feature request from a user - it’s likely to waste both your own time and ours.

> I think this feature is very useful for users playing with a lower Window Scale Factor as it can be quite difficult to close a window due to the size of the close button.

That doesn’t seem like a good reason. If the window scale is so low you can’t click Close, then all steppers, dropdown etc. are also too small. Decoupling window scale from viewport scaling, and enlarged UI are much better solution to that problem.

**Comment by Gymnasiast** [comment]
With nobody coming forward, I’ll close this PR, for the reason Aaron and I gave earlier.

**Comment by pfroud** [comment]
This pull request was for a feature request discussion with seven upvotes: https://github.com/OpenRCT2/OpenRCT2/discussions/21430

**Comment by Gymnasiast** [comment]
It is easy to upvote a feature, but there is implementation, maintenance and the GUI as a whole to consider.

**Pull request closed without merging**
