### PR TITLE
 Use std::size instead of Util::CountOf 

### PR DESCRIPTION
**Pull request by Broxzier**
I'd like someone with XCode installed to verify the project file still works, and overwrite the last commit if it's not correct.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
The Linux CIs fail because of an error at Travis' end, but clang-format also doesn't like a few things. But I wouldn't take over its formatting of `mini_golf_peep_animation_lengths`.

**Comment by janisozaur** [comment]
I restarted the travis jobs and they report proper errors now.

**Comment by Broxzier** [comment]
Thanks, I was already wondering what those errors were about. I'll push a fix shortly.

**Comment by Broxzier** [comment]
Oh, I clicked merge too fast. The XCode project still has to be checked.

**Pull request merged**
