### PR TITLE
[WIP] Integrate mini golf data

### PR DESCRIPTION
**Pull request by marijnvdwerf**
| id | default | left-handed | id |
|----|--------------| ---------------|----|
| 0 | golf-0<br><code>WALK</code> |
| 1 | golf-1<br><code>MOVE_DOWN</code> |
| 7 | golf-7<br><code>SWING</code> | golf-2 | 2 |
| 3 | golf-3 |
| 4 | golf-4<br><code>JUMP</code> |
| 5 | golf-5<br><code>MOVE_UP</code> |
| 8 | golf-8<br><code>PUT</code> | golf-6 | 6 |

### CODE REVIEW

**Comment by marijnvdwerf** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/dcf0a9dad14e193d428602fe5b2789c23958d93d/src/ride/vehicle.c#L7634 is likely left-handedness. Though it's weird that animation 2 & 6 seem to use a different swing. Bug perhaps?

**Comment by marijnvdwerf** [comment]
`vehicle->var_D4` will be the `mini_golf_animation_id`
`vehicle->var_C5` will be the `frame_num` (needs checking as it's not mini-golf-only)

**Comment by marijnvdwerf** [comment]
I don't really get what's going on here: https://github.com/OpenRCT2/OpenRCT2/blob/dcf0a9dad14e193d428602fe5b2789c23958d93d/src/ride/vehicle.c#L7465. Last frame check? The gifs in this pull-request are rendered without the last frame, as those didn't fit the animation. I'm guessing the game doesn't use them either, as the sprite-animations in-game are fairly smooth.

**Comment by marijnvdwerf** [comment]
The last number in the frames array is the length of the _following_ frames array. The number `6` should be in front of the first array.

**Comment by marijnvdwerf** [comment]
@janisozaur Can you take a look at this some time? I've added some notes, but I'm unsure what the best way is integrate the use in vehicle update, since it needs the element count.

**Comment by duncanspumpkin** [comment]
Yes that seems to match the track position arrays. I.e. Entry one before start is the length.

**Comment by AaronVanGeffen** [comment]
Perhaps stating the obvious, but 2 and 7 seem to an actual putting move, whereas 6 and 8 are only aiming.

**Comment by marijnvdwerf** [comment]
@duncanspumpkin Is there a better way to do the array-length related stuff than the solution in my last commit?

**Comment by IntelOrca** [comment]
@marijnvdwerf `countof`

**Comment by marijnvdwerf** [comment]
@AaronVanGeffen I think 2/7 are normal swings, and 6/8 are putting.

**Comment by marijnvdwerf** [comment]
@IntelOrca Done

**Comment by IntelOrca** [comment]
`mini_golf_peep_animation_frames_3` ?

**Comment by Goddesen** [comment]
Assuming the swing direction for normal swings is correct, does that not make the putting reversed?

**Comment by marijnvdwerf** [comment]
@Goddesen Not sure. I find it very hard to see in which direction the ball would move.

**Comment by marijnvdwerf** [comment]
@IntelOrca Satisfied with the naming? Not sure whether it's actually as describe, but it seems likely to be so.

**Comment by IntelOrca** [comment]
Yes, is this WIP still?

**Comment by marijnvdwerf** [comment]
@IntelOrca I think this should be done know.

**Pull request merged**
