### PR TITLE
Fix missing Twister coaster piece. #3361

### PR DESCRIPTION
**Pull request by Darkttd**

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Seems to work correctly.

**Comment by IntelOrca** [comment]
ride_construction.c:2454
```for (int i = 0; i < 140; i++) {```
literal should be replaced with countof(gTrackDescriptors).

**Comment by Darkttd** [comment]
Done.

**Comment by duncanspumpkin** [comment]
I'm just looking at the assembly and the mistake was caused by reading a `jb` as `je` and `ja` as `je`. I've no idea if it would make any difference but this is more like what it is originally
```
if (_currentTrackCurve < TRACK_CURVE_LEFT_SMALL || _currentTrackCurve > TRACK_CURVE_RIGHT_SMALL || _rideConstructionState != RIDE_CONSTRUCTION_STATE_FRONT || !is_track_enabled(TRACK_SLOPE_CURVE_BANKED)) {
```

Also the line above also has this same mistake. Again I can't find a ride that this actually needs this set for.

**Comment by Darkttd** [comment]
How about this case? build same condition but build try BACKWARD.

vanilla:
vanilla


openRCT2:
orct2

**Pull request merged**
