### PR TITLE
Add Auto-Renewing Marketing Campaigns & Cancel Running Marketing Campaigns

### PR DESCRIPTION
**Pull request by ecnepsnai**
Adds a new opt-in auto renewal feature for new marketing campaigns where upon expiry, a new campaign with the same parameters will be purchased. Unlike the never-ending marketing campaigns cheat, automatically renewed campaign requires sufficient funds.

marketing_auto_renew

The news item is different depending on if the auto renewal was successful

marketing_notifications

Also adds the ability to cancel any active marketing campaign. However, for game balance and an aspect of realism, you will not be refunded if you cancel your campaign early.

marketing_cancel

### CODE REVIEW

**Comment by ocalhoun6** [comment]
Maybe it's just me, but the `x` button to cancel an advertisement campaign looks a bit ugly?

Besides that, though, I think it's wonderful and long-overdue!

**Comment by karst** [comment]
I am curious if this should be part of the base game or instead just be exposed to plugins? Mostly because advertising campaigns are already quite broken... But it definitely helps with removing a grind part that might not be as fun.

**Comment by ecnepsnai** [comment]
@ocalhoun6 I do agree it's not great looking, though I didn't want to change too much of the UI.

For your suggestion, where would you suggest putting the trash can icon?

**Comment by ocalhoun6** [comment]
>Mostly because advertising campaigns are already quite broken... 

I *do* think it would be good to balance out the absolute brokenness of ad campaigns, perhaps by giving them some drawback to make up for how overpowered they are. *But* 'make the UI for them more tedious for the player' is really *not* a good way to do drawbacks for stuff like that. There should be some downside within the world of the game, not just annoying the user. (Ideally, software should never annoy the user on purpose.)

Maybe drawbacks could be something like:

- Making them much more expensive (maybe there could be an 'autorenewal fee', where using the option to autorenew makes them slightly more expensive?)
- Guests generated by advertisements have significantly lower initial happiness (so if too high of a percentage of your guests are newly arrived from ad campaigns, it will hurt your park rating)
- Running too many ads for a small park *directly* hurts your park rating (because of guests being disappointed that your park didn't live up to the hype)
- In order for the ad campaign to be successful, your park rating must be high (if your park rating is too low, the ad campaign will fail and produce few, if any, new guests)

That's all *wildly* outside the scope of this PR, though!

> where would you suggest putting the trash can icon?

Maybe where the x button already is? I'm not sure though ... I'm definitely no UI design expert!

**Comment by ecnepsnai** [comment]
@karst I agree I'm threading the line between the original game and improvements, and at the end of the day I can respect if we say this is better suited for a plugin (which I did look at but couldn't figure out).

This is why I decided to make it entirely opt-in. Should you want to use it, it's there, if not, no problem - nothing has changed. In my opinion the only thing that I've removed is just the tedium of clicking through to create campaigns.

**Comment by ecnepsnai** [comment]
@ocalhoun6 I'll give that a shot and report back with a screenshot. I felt that it was too small for a icon like the trash can, but I admit I didn't actually try it just assumed.

**Comment by ecnepsnai** [comment]
@ocalhoun6 as I expected I ran into problems getting the trash icon to work with the small row height of the campaign list, but here's some possibilities I came up with:

1. We could just double the line height to fit a trash can icon, but this looks worse than the small `x` IMO
   big_trash
1. We could follow a similar pattern to the staff list with just one trash button that toggles a "delete" mode, where clicking the campaign in the list cancels it.
   one_trash
1. Lastly we could just copy the style of the new campaign buttons and have the reverse, clicking the button cancels the campaign. This is the simplest to implement and perhaps the simplest for players to understand?
   many_buttons

**Comment by Gymnasiast** [comment]
This has been discussed in the past, but vetoed as it was deemed not to fit within RCT’s gameplay. Exposing a few more hooks for cheats/plugin might be a better option IMO - that allows people who want this to just install a plugin without affecting the rest.

**Comment by ecnepsnai** [comment]
@Gymnasiast That's fair, although in this implementation players would have to actively choose to use either of these features. Those who don't want to use them aren't affected outside of seeing new options.

Shall I abandon this PR and look at expanding plug-in hooks for marketing? Or perhaps I could address some of the concerns with my current design?

**Comment by Broxzier** [comment]
I agree with Gymnasiast, and am inclined to close this PR. This is certainly something a plug-in should be able to handle, so any required changes to make that work are welcome. In the future, please make sure that what you plan on working on is actually something we'd like, by bringing it up in a GitHub discussion or on Discord.

**Comment by karst** [comment]
Perhaps the groundworks of this PR can still be used for the plugin integration? Remove the UI work and allow it to be selectable with plugins?

**Pull request closed without merging**
