### PR TITLE
OpenGL: Delay Palette Mapping Until Final Framebuffer Copy to Screen

### PR DESCRIPTION
**Pull request by LRFLEW**
This PR makes a significant change to how the OpenGL rendering process work. Put simply, the framebuffers now store the palette index instead of the color at that index in the palette. The main advantage is that the shaders that are dependent on the previous draws are a lot simpler. For example, fillRect.frag's transparency code now works as `uSourceFramebuffer -> palette index -> uPaletteRemap -> palette index`, instead of the previous `uSourceFramebuffer -> color -> palette index -> uPaletteRemap -> palette index -> color`. This is particularly useful because the transition `color -> palette index` was being performed using a for loop, which is expensive to use in a shader. In addition, fillRect.frag now only has one array instead of two.

On my machine (MacBook Pro 15" Late 2013, with an i7-4960HQ and GT 750M, on macOS 10.12.6), I get 60-70 fps with this change, compared to the previous 0.3 fps I get without this change. The abysmal performance before seemed to be due to driver specific limitations with the for loop and arrays. I don't expect the same sort of 20000% performance improvement on all machines, but it should improve the performance at least somewhat.

This PR has a few regressions which need to be fixed before this gets merged.

- [ ] The previous (incorrect) implementation of sprite transparency is missing. This is because you can't use GL_BLEND with this method. With this change, any transparent sprites (ex. water or colored glass) will appear opaque. The transparency for the solid-colored rectangles still works. The sprites need to be converted over to the same technique that the rectangles use.

- [x] Screenshots are completely broken. Don't even try to use it right now. The original code just took the image from the framebuffer, but since it now doesn't contain the actual colors, it will result in a broken image (if it doesn't just crash). It either needs to perform the palette mapping in the software, draw to a real-color framebuffer using the palette lookup shader before fetching the data, or just create a paletted PNG image.

- [ ] This more than likely breaks @Dennis-Z's lighting branch significantly. There are a number of ways that the branch can be updated to work around this, but figuring how to merge the branches now may be a good idea.

### CODE REVIEW

**Comment by PFCKrutonium** [comment]
On latest Develop, Windows 10, nVidia 950, I get 25-40 FPS on the first park in the main menu.
With this PR, I get 60-80 FPS on the main menu.

This actually makes OpenGL faster on my machine, than Software with Hardware.

**Comment by Gymnasiast** [comment]
For me, this increases FPS after opening Blackpool Pleasure Beach from 24 FPS to 47 FPS (Ubuntu 17.04, Intel HD Graphics 530).

**Comment by Dennis-Z** [comment]
This doesn't affect performance in any noticeable way for me (GPU utilization is also about the same). (win10, 1080ti)

**Comment by LRFLEW** [comment]
I fixed the screenshot issue. I went with creating a paletted image, since that's what the software renderer does. This does mean that the screenshots from OpenGL are now considerably smaller :smile:. I ended up making use of the `OpenGLDrawingEngine::_bitsDPI`, as it appeared to be setup correctly for the viewport, but the `bits` attribute was being unused. Let me know if this is a bad idea.

**Comment by Dennis-Z** [comment]
I think the lighting can be adjusted by writing lighting data to a separate (rgb8) color attachment. Lighting through a filtered fragment can then be estimated by multiplying it with some 3x3 matrix indicating how much rgb "shines" through and how much the light changes in color, lerping that with the lighting of the transparent fragment itself. Thus delaying blending the lighting with palette colors until the final copy to the render target.
Not sure how much of an impact it will have on the lighting quality when it gets affected by filtered fragments, but I suspect it will be fine.

In my opinion `rct_drawpixelinfo` should be completely changed so that it's render engine-agnostic. It's pretty much designed to be a framebuffer + clipping region for software rendering, I think. Having a special structure for OpenGL framebuffers that is passed to render engine-agnostic drawing functions would also allow fixing #5103 and #5889 cleanly.

**Comment by duncanspumpkin** [comment]
I have no idea how you will try to get transparency working. You can't do what filterRect does as that is ridiculously expensive. The only other ways are blend, use the opengl extensions that MacOS isn't compatible with or render to multiple framebuffers to create the transparency information for a second pass to render.

**Comment by IntelOrca** [comment]
Multiple framebuffers is probably the best way to do it. It might now be so bad as the framebuffers would be 1/4 of the size they tend to be.

**Comment by Dennis-Z** [comment]
How would multiple framebuffers solve this? Multiple transparent objects can layer on top of each other, each changing the fragment below it.

I could see this working properly:
- Render all nontransparent objects + write to depth buffer (pass object 3d position)
- Sort all transparent objects like done currently
- Draw transparent objects to a CPU buffer indicating that fragment is now 'dirty', queue transparent objects to be drawn until a transparent object that is dirty is about to be drawn -> flush, swap framebuffers, invalidate dirty CPU buffer

**Comment by duncanspumpkin** [comment]
> Multiple transparent objects can layer on top of each other, each changing the fragment below it. 

Not always:
image

You only need to know the base object and what transparent object that is at the top.

**Comment by Dennis-Z** [comment]
Aha, that makes it much simpler for sure!

**Comment by duncanspumpkin** [comment]
The problem is that isn't actually always the case. I don't think anyone would really notice if we made it a rule that this is how it will render though.

**Comment by Dennis-Z** [comment]
Glass through water is definitely noticeably different:
image

**Comment by duncanspumpkin** [comment]
Water is special. It performs a different change. It changes the shade as well as the colour. You could still do this correctly though with a bit of thought.

**Comment by LRFLEW** [comment]
>The only other ways are ... use the opengl extensions that MacOS isn't compatible with

@duncanspumpkin What extensions are you referring to exactly? The nice thing about extensions is that you can conditionally use them, so if it's not available on macOS, then we use a fallback option for when it's not there, and use it when it is. However, I've yet to see any extension that makes this any less of a headache, so I don't know what exactly you're referring to.

As to the "multiple framebuffer" technique, I think having three buffers (opaque, water, and transparent objects) and merging them at the end would be "close enough" until we get unordered rendering working, and can draw the objects in that order. The only problem would be getting any necessary opaque objects to overlap transparent ones, but I think I can hack together a pseudo-Z-Buffer solution.

As for the fillRect method, I want to at least try making it. Yes, the performance will likely be abysmal, but making the code will both give us a baseline of what the performance for it is, and give me a better idea of how the sprite transparency actually works. (I still don't understand what the difference between `FLAG_TRANSPARENT` and `FLAG_TRANSPARENT_SPECIAL` is supposed to be in the palette space).

@Dennis-Z That description sounds pretty close to what I was going to suggest. I don't know if the lighting information actually included any RGB values as-is, and was going to suggest storing a luminosity multiplier instead. Otherwise, it sounds like you have a good idea of how to merge these branches when the time comes.

**Comment by duncanspumpkin** [comment]
@lrflew go far enough back into the history of the code base and you will find the fillrect version and it's horrible performance.
https://www.khronos.org/opengl/wiki/Image_Load_Store is the extension that would allow a read modify write. 
Flag transparent is the glass, transparent special is water.

**Comment by duncanspumpkin** [comment]
All of the transparency operations are meant to happen in palette space.

**Comment by LRFLEW** [comment]
Ah, so special = water then. Ok. I'm not entirely sure why they're treated differently in the shader, though. Probably due to the shifting color palette for the water. I'll try to hunt down the old shader for reference. (It would help if someone has a commit I can check, but otherwise I'll just look for it).

Image Load Store does seem like it could be useful here. It does seem to minimize the challenge of flipping the framebuffers, but comes with its own challenges. The non-coherency and atomic natures of the image operations could mean that the performance would be worse than just creating an optimized unordered rendering scheme. I'll probably experiment with the Image Load Store once I get around to building my own Windows desktop.

**Comment by duncanspumpkin** [comment]
The best resource to understand how it is meant to draw is the software renderer. I'll write up a big a reply explaining how it is meant to work tonight if i get the time.

**Comment by LRFLEW** [comment]
I took a look at the software renderer a bit. The whole chain of functions was a bit obtuse, but I at least understand how glass works. Basically, the sprite itself acts more like a 1bit mask, where non-zero values indicates that the new value is the value in the palette at the index of the current value. What I don't know right now is how the water is handled, since it's not a uniform mask like the glass.

**Comment by LRFLEW** [comment]
I'm starting to think that I should make this PR "as-is", and leave fixing the sprite transparency for another PR. I did get a working pixel-perfect sprite transparency version ([LRFLEW/OpenRCT2/opengl-transparent](https://github.com/LRFLEW/OpenRCT2/tree/opengl-transparent)), but the performance is bad enough to warrant not merging it here (I get ~20fps in the Magic Mountain scenario around the nearest pond to the start). To actually fix it will require a lot of work. As I see it, it will require 3 things:

1. **Depth-based rendering for opaque objects.** This doesn't need to be complicated, just needs to work. This could just be done by incrementing a depth variable by 1/2^24 for ever attempted draw.

2. **Transparency drawing with the Painter's algorithm.** We already have this with the ordered rendering, but a rewrite for the depth-based rendering would need to keep this for the transparent objects at least.

3. **Non-overlaping transparent object batching optimization.** This is by far the toughest part. To prevent swapping the buffers for every transparent object, we'd need to be able to group together transparent objects that are sequential in the draw order that do not affect eachother. We can check the bounding box for the renders, but it won't be effective at optimizing this, as the pseudo-mask that the tiles have will cause too many non-overlapping sprites to appear to overlap in the test. (For example, water tiles are rather trivially combinable, but will appear to overlap if you just check the bounding boxes). This would be mostly optimized with a tiling check, but it would need to be heavily optimized, as an actual overlap check would be too costly.

This is a lot of work, and not something that will be quickly completable. As it is, this PR does what it (mostly) set out to do. In addition, the sprite transparency wasn't really working before, so this PR doesn't break an already existing feature as it replaces one incorrect method for another. What do y'all think? Is this worth merging as-is, or should we wait for actual transparent sprite handling before merging? I would like to get this PR figured out before RCTC comes out, as I'd like to experiment with it, and I don't want this to end up becoming stale.

**Comment by pizza2004** [comment]
Didn't RCTC come out almost an entire year ago now?

**Comment by LRFLEW** [comment]
@pizza2004 http://store.steampowered.com/app/683900/RollerCoaster_Tycoon_Classic/

**Comment by duncanspumpkin** [comment]
It's not worth merging as is as it breaks the renderer. We can't use it as a base line as it doesn't render the base game. It also breaks all the other open gl pr's. How do we know that this approach is going to work over the existing approach that just about works.

**Comment by LRFLEW** [comment]
>It's not worth merging as is as it breaks the renderer. We can't use it as a base line as it doesn't render the base game.

What exactly does this do wrong that the existing one does? Yes, the sprites aren't transparent, but they weren't correct before either.

>It also breaks all the other open gl pr's.

And the other PR's break this one. I already had to rebase once. And I don't see any other OpenGL PR's open.

>How do we know that this approach is going to work over the existing approach that just about works.

What this PR does isn't all that complicated. Put simply, this forces the OpenGL renderer to emulate the Software renderer more closely. By working in palette space like the software renderer does, it opens up the possibility of reasonably supporting accurate transparency without the ugly hack that was previously there. I don't see any scenario that the current Software renderer can handle that this PR won't.

**Comment by Dennis-Z** [comment]
> as an actual overlap check would be too costly.

Would it really be? It's basically like software rendering, but this is only done for transparent sprites.

**Comment by duncanspumpkin** [comment]
Closing as #6541 includes all of this.

**Pull request closed without merging**
