### PR TITLE
Fix #11963 - Refactor Peep::OutsideOfPark

### LINKED ISSUE #11963: Refactor Peep::OutsideOfPark
Peep::OutsideOfPark is a bool and should be converted to a bool.

### PR DESCRIPTION
**Pull request by TomasZilinek**
(issue #11963) Changed the definition of Peep::OutsideOfPark from uint8_t to bool and refactored all its occurences in code accordingly.

### CODE REVIEW

**Comment by TomasZilinek** [comment]
> Looks fine. What is happening in the importers and exporters

What importers and exporters? I am not familiar with this terminology.

**Comment by duncanspumpkin** [comment]
S4 and S6 importer and S6 exporter for the save files. You should convert this explicitly.

**Comment by TomasZilinek** [comment]
> Looks fine to me, though I'm not 100% convinced on the import/export changes

What should I do differently? Or did I forget something?

**Comment by duncanspumpkin** [comment]
I think it is fine to do it like that for import and export. I only wanted something explicit I don't feel a ternary would improve the readability.

**Pull request merged**
