### PR TITLE
Start 0.0.5

### PR DESCRIPTION
**Pull request by janisozaur**
changelog.txt not updated yet

With #3231 and #2994 now merged, this has already become 0.0.5

Should we also reset `NETWORK_STREAM_VERSION`?

### CODE REVIEW

**Comment by JarnoVgr** [comment]
I believe the NSI file (Windows installer) needs to be changed as well.

**Comment by janisozaur** [comment]
@JarnoVgr would it be possible to set this information externally?

**Comment by JarnoVgr** [comment]
@janisozaur That is possible. But we might need to split-up the version tag.
`!define /ifndef APPV_MAJOR 0
!define /ifndef APPV_MINOR 0
!define /ifndef APPV_MAINT 4
!define /ifndef APPV_BUILD 0
!define /ifndef APPV_EXTRA "-beta"`

**Comment by janisozaur** [comment]
We should put some effort into merging all these version definitions where possible before the next release; the nsis refactor can be done later on.

I've already updated the installer definition in its current format.

**Comment by Gymnasiast** [comment]
Let's wait with changing the network stream version until we actually merge something that warrants it.

**Comment by janisozaur** [comment]
It will change anyway due to version being different. It's more a matter of "do we reset the id on every release" or "do we keep going". Both are perfectly fine and keep in mind we use numbers for this, but it could very well be a string, if there is such a need.

**Comment by Gymnasiast** [comment]
Sure, but let's change it on the first incompatible commit.

**Comment by IntelOrca** [comment]
I am changing it for master anyway so, might as well do whatever now.

**Pull request merged**
