### PR TITLE
Automatically download OpenSFX for Linux builds

### PR DESCRIPTION
**Pull request by janisozaur**
Allow skipping of download if prepopulated

### CODE REVIEW

**Comment by ZeeMajora** [comment]
Appears to be working as expected, the additional audio object and the opensounds asset pack is present.

**Comment by janisozaur** [comment]
So the problem is the download function verifies the `zipversion` file from download, but both openmusic and opensound have the same version and are downloaded to the same location, so both downloads provide the same file and the download function gets confused into thinking the download is already present. I need to think a bit about possible solution.

**Comment by KingCatto** [comment]
Just a thought would putting them in subfolders possibly work?

**Comment by janisozaur** [comment]
> Just a thought would putting them in subfolders possibly work?

That was my initial idea, but found a cleaner solution. I was not initially aware the zipversion files were created by us - the cmake installer - but expected them to come from the assets themselves.

**Comment by ZeeMajora** [comment]
Seems to be working as expected now, all of the opensounds & openmusic related files seem to be packaged now. Good work!
Screenshot_select-area_20230305191006
Screenshot_select-area_20230305191024

**Review by ZeeMajora — APPROVED** [review]

**Review by ZehMatt — APPROVED** [review]

**Pull request merged**
