### PR TITLE
Fix #2550 Program crashes when executing "exit" command from the console

### LINKED ISSUE #2550: Program crashes when executing "exit" command from the console
This might be intentional, but in build 1573 running the "exit" command from the console will cause the game to crash.  Attaching a debugger will show that [this line](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/interface/console.c#L1061) causes an uncaught exception so the return code for the program is negative.

### PR DESCRIPTION
**Pull request by ecnepsnai**
Replace string constant with free-able value

### CODE REVIEW

**Comment by IntelOrca** [comment]
Whilst this would work, its only because it so happens to be the same length. Either make this clear in a comment above the line or free the original value first.

**Comment by ecnepsnai** [comment]
Would something like this work?

```
    // Aliases for hiding the console
	if(strcmp(argv[0],"quit") == 0 || strcmp(argv[0],"exit") == 0) {
		free(argv[0]);
		strcpy(argv[0], "hide");
	}
```

**Comment by IntelOrca** [comment]
yes

**Comment by IntelOrca** [comment]
Sorry, you will need to reallocate the memory. Try _strdup instead of strcpy.

**Comment by ecnepsnai** [comment]
Alright, no problem!  I'm working on getting better at C.

**Comment by janisozaur** [comment]
Please name your commits properly too, i.e. label what the commit does in the first place, then in extended description (or in the oneline, space allowing) mention which issue does it fix on github, otherwise the commit message makes no sense without cross-referencing github.

You can alter your past commits with `git rebase` or `git commit --amend`.

See a guide on writing good commit messages: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

**Comment by AaronVanGeffen** [comment]
You may want to stash your commits using the rebase command @janisozaur pointed out, too.

**Comment by IntelOrca** [comment]
@ecnepsnai Why did you close this?

**Comment by ecnepsnai** [comment]
I will resubmit at a later time.

**Comment by IntelOrca** [comment]
Please re-open the pull request. All you need to do is squash your commits and force push to the same branch.

**Comment by ecnepsnai** [comment]
You can't reopen a PR if the branch was forcefully pushed - So I will make another PR.

**Pull request closed without merging**
