### PR TITLE
Improve Chinese Currencies

### PR DESCRIPTION
**Pull request by daihakken**
[CI Skip]
Suffix -> Prefix, and fix CNY name from HKD to CNY.

### CODE REVIEW

**Comment by IntelOrca** [comment]
@daihakken you shouldn't CI skip when there are changes to source files.

**Comment by daihakken** [comment]
@IntelOrca Thanks for the reminder, I thought it was too small to initiate a CI Check.

**Comment by IntelOrca** [comment]
Its still possible to introduce a syntax error which would break the build. Only skip CI builds if you are only editing readmes, text files etc.

**Comment by daihakken** [comment]
@IntelOrca got it, sorry for that.

**Pull request merged**
