### PR TITLE
Fixed library installation on 64-bit systems

### PR DESCRIPTION
**Pull request by Mailaender**
This is a minimally invasive change for Linux distribution, that allow 32-bit and 64-bit libraries in locations such as `/usr/lib` and `/usr/lib64` next to each other. Alternatively one can use the https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html, but I don't know how that behaves on other platforms such as Windows/Apple and the cmake file indicates that some install rules are prepared for those.

Fixes https://github.com/OpenRCT2/OpenRCT2/issues/5910.

### CODE REVIEW

**Comment by janisozaur** [comment]
The changes look fine and could go in, but I'm wondering if there's a chance of using the "proper" directories that you linked? CMake is used for Linux and Android builds, rarely on macOS just to verify things. CPack, the installer part of CMake, is pretty much only used on Linux, so it shouldn't cause any issues.

**Comment by janisozaur** [comment]
@ibara any comments on this?

**Comment by ibara** [comment]
Please only enable it for Linux, or at least disable it for OpenBSD, as this idiom makes no sense on OpenBSD. We don't follow GNU idioms (for obvious reasons).

**Comment by IntelOrca** [comment]
@ibara It defaults to no suffix, is there a chance that `LIB_SUFFIX` would be set on OpenBSD?

**Comment by ibara** [comment]
No. It would never be set. That would violate [hier(7)](https://man.openbsd.org/hier.7).

**Comment by Mailaender** [comment]
See https://build.opensuse.org/request/show/510593 for an integration build. By default it does nothing so this change shouldn't hurt BSD.

**Comment by Gymnasiast** [comment]
Ok, so it shouldn't affect \*BSD.
@janisozaur You can merge this PR if it looks fine to you, AFAIC.

**Comment by Gymnasiast** [comment]
Merged it.
@ibara If this does break OpenBSD compilation, please let us know.

**Comment by ibara** [comment]
OpenBSD still compiles fine with this commit.

**Comment by Thaodan** [comment]
So because of this commit the default lib suffix on x86_64 is lib64 eg. /usr/lib64?

**Pull request merged**
