### PR TITLE
Fix #11240: Prevent null destination for string formatting

### LINKED ISSUE #11240: BACKTRACE 646e77 strnlen -> format_string_code
<table>
    <tr>
        <td></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/646e772f62c75d9596b48b9c0184b64f4ad29b1aba0a4edef4fa0509eda7179d?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Mon Apr 06 2020 20:45:28)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_replay.sv6r:</strong> *: <em>1</em><br><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\Jacob McDermott\\Documents\\OpenRCT2\\c3c90147-9778-40b8-899e-a9d71bc4eecf.ini: <em>1</em><br><strong>assert_failure:</strong> *: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\Jacob McDermott\\Documents\\OpenRCT2\\c3c90147-9778-40b8-899e-a9d71bc4eecf.sv6.gz: <em>1</em><br><strong>attachment_screenshot.png:</strong> C:\\Users\\Jacob McDermott\\Documents\\OpenRCT2\\screenshot\\Crazy Castle 2020-04-06 16-42-38.png: <em>1</em><br><strong>commit:</strong> a613ec3: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>strnlen -> format_string_code -> format_string_part_from_raw -> format_string -> GuestSetNameAction::Execute -> GameActions::ExecuteInternal -> GameActions::ProcessQueue -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> wmain</code></td></tr>
</table>

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by tupaschoal** [comment]
@IntelOrca is right, that's exactly why I followed-up on the other case with https://github.com/OpenRCT2/OpenRCT2/commit/6cf113ae6f99ec9e31b865b520295e920c8cf2af

**Comment by IntelOrca** [comment]
I don't mind the change, but it won't fix #11240.

**Comment by janisozaur** [comment]
I know the crash will persist, but I was hoping to catch all possible variations of this problem at once. I looked at what could the root cause be and have some idea, but need more time to test it. This PR can wait until I provide actual fix for it.

**Comment by tupaschoal** [comment]
Ah, ok, I'm not against the change either, I just think the PR name is a bit misleading.

**Comment by tupaschoal** [comment]
@janisozaur do you want to merge this to track potential bugs before release?

**Comment by janisozaur** [comment]
Yes, but there were some good reports that came in and I still want to take a closer look fixing it at the problem source. This can get merged just before release if I don't provide a proper solution by then.

**Comment by janisozaur** [comment]
I will rework it to better prevent the problem

**Comment by tupaschoal** [comment]
I'll close this as it's been a while and it hasn't been reworked. Feel free to reopen if you do or to file an issue tracking what you had in mind

**Pull request closed without merging**
