### PR TITLE
allow mini helicopters to draw spinning tunnel

### PR DESCRIPTION
**Pull request by 733737**
this will allow mini helicopters to draw spinning tunnel, but it will not add spinning tunnel to the special drop down list
rawrrrrr

### CODE REVIEW

**Review by Gymnasiast — CHANGES_REQUESTED** [review]
Like the previous PR, this will need special drawing code.

Since you are a patron, I’m willing to do this myself. It’s not really beginner stuff.

**Comment by 733737** [comment]
i doubt i could do it, feel free to do it on this, log flumes, and dinghy slide IF you have the time and patience

**Comment by Gymnasiast** [comment]
@rik-smeets There is a little bit of z-fighting when the cars come out of the tunnel. Was wondering if you could advise on that.

**Comment by rik-smeets** [comment]
@Gymnasiast There are existing z-fighting issues with the Ghost Train, which can be seen on the `u(2315)` design:
image

I can imagine the z-fighting here is related to that. I have a stash somewhere where I did some work on this, but it was't easy. I do plan to pick that up sometime later.

**Comment by rik-smeets** [comment]
I just tried out the build and I must admit that I don't even see z-fighting issues when the cars get out of the tunnel, it looks surprisingly good I'd say.

I however don't see the track getting drawn inside the tunnel:
image

**Comment by 733737** [comment]
There is no z-fighting from 3 angles, only one, I'm not sure which angle but it is one out of the 4

**Review by rik-smeets — APPROVED** [review]
Looks good to me. There's a minor difference with the Ghost Train though. The track inside the Ghost Train's spinning tunnel is actually dark. I'm not sure if that's because there are special sprites for the track? That would be nice here too, but I can imagine that might be something for another PR.

**Comment by Gymnasiast** [comment]
Yes, that is indeed down to having special sprites for the track. (28863 and 28864)

**Review by Gymnasiast — APPROVED** [review]

**Pull request merged**
