### PR TITLE
Make the land tool holdable

### PR DESCRIPTION
**Pull request by wolfreak99**
This allows you to hold down the land tool buttons to increase / decrease size.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Code looks OK to me. I still have to test it though.

**Comment by rwjuk** [comment]
I have tested it, and it works (also makes the land tools much easier to use).

**Comment by janisozaur** [comment]
@rwjuk @IntelOrca so I guess we take it for 0.1.0 then?

**Comment by IntelOrca** [comment]
@janisozaur I thought 0.1.0 was only for critical fixes?

**Comment by rwjuk** [comment]
@IntelOrca @janisozaur Yeah, I'd rather see it go in 0.1.1.

**Comment by Gymnasiast** [comment]
Could you rebase this PR and move the changelog entry to 0.1.1?

**Pull request merged**
