### PR TITLE
Fix ghost elements influencing ride excitement

### PR DESCRIPTION
**Pull request by ZehMatt**

### CODE REVIEW

**Comment by tupaschoal** [comment]
Will most probably have merge conflicts with #10013 , just FYI

**Comment by ZehMatt** [comment]
We can merge yours first so its less work for you to rebase

**Comment by AaronVanGeffen** [comment]
I think it would be better not to wait for #10013. That PR looks like it will need some checking w.r.t. whether or not it will inadvertently *hide* bugs.

**Comment by tupaschoal** [comment]
I don't mind rebasing, shouldn't be too painful as it only affects one of the commits. Just wanted to note here to track

**Pull request merged**
