### PR TITLE
Refactor TILE_INSPECTOR_ELEMENT_TYPE to use strong enum #12451

### PR DESCRIPTION
**Pull request by mysterious1223**

### CODE REVIEW

**Review by Broxzier — APPROVED** [review]

**Review by tupaschoal — COMMENTED** [review]
@Broxzier should we remove those? A bit weird that they're unused...

**Comment by mysterious1223** [comment]
I agree. I noticed that this enum was unused.

**Comment by duncanspumpkin** [comment]
Its because we use the element type instead of the tile inspector element type. Why have two of the same thing.

**Comment by Broxzier** [comment]
> @Broxzier should we remove those? A bit weird that they're unused...

Ah yes, of course. Unused stuff is better removed.

**Review by tupaschoal — CHANGES_REQUESTED** [review]
Please remove this enum then, @mysterious1223 . Also make sure to mark the PR ready for review when it is.

**Review by tupaschoal — APPROVED** [review]

**Pull request merged**
