### PR TITLE
Fix CMake builds on macOS

### PR DESCRIPTION
**Pull request by marijnvdwerf**

### CODE REVIEW

**Comment by janisozaur** [comment]
@AaronVanGeffen I take your :+1: as your word you have verified this change working, as our primary OS X cmake user

**Comment by AaronVanGeffen** [comment]
Yeah, I tested this earlier and approve of this change.

**Comment by janisozaur** [comment]
@AaronVanGeffen @marijnvdwerf any chance of going full-`PIE` now that we are standalone?

**Comment by marijnvdwerf** [comment]
If no segments are linked, sure.

**Pull request merged**
