### PR TITLE
Fix #8508: Underground roto-drop is not going up

### LINKED ISSUE #8508: Underground roto-drop is not going up
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** b572fff

Roto-drop that is built in underground is not going up and tend to keep in underground

**Screenshots / Video:**
zyro

### PR DESCRIPTION
**Pull request by Gymnasiast**
Replaced the dark magic with a simpler algorithm that will just keep searching until it found the next segment, ignoring all other tile types inbetween.
The function wasn't accurately named, since it would only stop rotating once it had reached the top piece.

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
Shouldn't this still have checked the base height / clearance height. It now doesn't take into account if someone had placed decorative track pieces above the tower. (This is just from my reading of it. I haven't tested this so it's just academic at this moment)

**Comment by Gymnasiast** [comment]
It does take that into account -- it checks for the tile element type. Interestingly, it didn't use to do that, instead interpreting all tile elements as track elements.

**Comment by duncanspumpkin** [comment]
I'm pretty sure if you placed a track tower piece above the top it will assume that is the top even if its from a different ride. Its a bit of a corner case I'll admit.

**Comment by Gymnasiast** [comment]
It will check for the correct track type. Admittedly, it doesn't check for the ride ID, but the only way your scenario could happen is if the player used the Tile Inspector - you cannot build a freestanding tower piece normally, and neither can you remove the base of a tower until you also removed all tower sections.

**Pull request merged**
