### PR TITLE
Fix 8720

### PR DESCRIPTION
**Pull request by ZehMatt**

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Have you tested whether boats indeed dodge ghost pieces?

**Comment by ZehMatt** [comment]
2019-02-19_11-24-23bca2b5d0b1e404cd7

Hopefully this answers your question.

**Comment by Gymnasiast** [comment]
Definitely!

**Comment by ZehMatt** [comment]
Trust me I've been surprised too while trying to complete a scenario in mp. On the bright side it took a long time until I desynced.

**Pull request merged**
