### PR TITLE
Cheats - Own all land, Invent all, money cheats

### PR DESCRIPTION
**Pull request by wolfreak99**
This owns all land with the addition of setting the path to the park entrance as construction rights mode (unless the path is high enough or low enough that construction rights would cause an issue, in which case it's not owned at all). in maps like dynamite dunes, there's a chance some of the entrance paths aren't registered as a park entrance path (I'm using code from the scenario editor), in that case it removes any stuck guests.

The invent all button is portions of the code borrowed from the inventions list window, and stuck as a game command that way it can be synced. i kinda threw this idea together while drunk, 

EDIT: Because both #4166 and this were relating to cheats, and I've heard no word on 4166, I just went ahead and merged them into here that way they can all be tested and merged together all at once. If requested, I will attempt to reorganize the commit history and make it more thorough and explain more of whats changing.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
If you're using code from the Scenario Editor, it's better to put that code into its own function and call it from the two places, rather than copying it.

Also, I'm interested in how exactly the scenario editor code fails to properly detect the entrance path - it might provide a clue to https://github.com/OpenRCT2/OpenRCT2/issues/441.

**Comment by wolfreak99** [comment]
If you load up dybamite dunes and use the own all land cheat, you'll see that the algorithm behind unowning the path looks for the same path that is the quickest and shortest route to a peep spawn point. It goes from entrance to spawn point. If it were to reverse the idea, and start at the spawn points and look for the path to one of the entrances, then it would possibly work for all spawn points.. but I can't see me attempting to do that at the moment.

**Comment by wolfreak99** [comment]
Come to think of it, I think the code right now only does one check run per entrance.. if it were to run a check for each spawn per entrance, it might also work, but it would need to take note of which spawns to skip on the second and third spawn loop, that way it doesn't connect the entrance to the same spawn 3 times.

**Comment by Gymnasiast** [comment]
Can't it just check for the presence of path directly on the ground or 1 unit above it?

**Comment by wolfreak99** [comment]
What are you talking about? I'm on mobile, was that a comment on a code line?

**Comment by Gymnasiast** [comment]
No, it was a general comment about how the code detects whether it should make a tile owned by the park or not.

By the way, it should simply check for the presence of any path on a tile and not make it owned if there is a path on it, regardless of the height.

**Comment by wolfreak99** [comment]
If a path is too high on a "construction rights" tile, it is considered "part of the park", if you open a map and set ownership of a path with people on it, they'll walk back and forth clueless because they haven't actually entered the park yet. this is what happens if a path is too high in a construction rights area.

The reason I set it to detect if it can take construction rights is because of parks like "Megaworld park" in Loopy Landscapes, where tracks can go over the park entrance path and give a cool effect. if we just set no ownership of all of the outside paths, it'll not allow potential to build rides over that area.

**Comment by wolfreak99** [comment]
i made the logic basically say "will having construction rights on this path block outsiders from entering the park? if not, then allow construction rights. but if outsiders won't be able to enter the park, then don't own it at all"

**Comment by wolfreak99** [comment]
but actually imma see if i can't make outsiders able to use paths underground by one level if construction rights exist... that way parks can be made with the entrance in the middle of the park.

**Comment by wolfreak99** [comment]
Alright, i think i'm pretty much satisfied with this. as far as a detachable spawn point, that's for another pr.

**Comment by Nubbie** [comment]
Presume this replaces #4053?

**Comment by wolfreak99** [comment]
Yeah, forgot to shut that one down, whoops.

**Comment by wolfreak99** [comment]
I would also like to ask about #4166 being merged first before this or at least removing the "changes requested" janisozaur left on it because i've heard no update from him since he done that.

**Comment by wolfreak99** [comment]
Actually. I'm going to close this down for a bit while i work on reorganizing it. I'm pushing too much to check the github page but it's clogging up the activity log aned cauising numerous rebuilds on travis and appveyor

**Pull request closed without merging**
