### PR TITLE
Add Steam overlay detection that pauses the game (#1903)

### PR DESCRIPTION
**Pull request by Overv**
The Steam overlay is detected by checking if the center pixel of the framebuffer is changed between rendering and presenting to the screen. This happens when the Steam overlay draws the gray fade on
the screen.

This does not affect other common overlays like FRAPS, MSI Afterburner and OBS overlays that don't obstruct the center of the screen.

Ultimately this is still a hack that will never be 100% reliable compared to integrating Steamworks, but I think that it's reliable enough to enable by default. Perhaps with an option in the Display tab to disable it?

The performance impact is negligible, because the pipeline is stalled when presenting anyway.

### CODE REVIEW

**Comment by IntelOrca** [comment]
Can this be improved with an option for whether you actually want it to pause the game (you can use minimize_fullscreen_focus_loss) and also to only run this code if Steam is running or perhaps if the Steam hooking module is loaded.

**Comment by Overv** [comment]
What about an extra configuration option "Pause game when in background"?

Also, I think I've actually found a method to do it without hacks.

**Comment by IntelOrca** [comment]
I think one option is enough to signify that you want the game to pause if there is any kind of focus loss.

**Comment by Overv** [comment]
Okay, but the `minimize_fullscreen_focus_loss` option currently has nothing to do with pausing the game. Should `SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS` be enabled by default and that option be replaced by a "pause on focus loss" option?

**Comment by Overv** [comment]
This is what the display settings look like right now:



I can extend the pausing option to include "alt-tabbing", but I don't think it makes sense to integrate the functionality with the fullscreen minimising setting.

**Comment by IntelOrca** [comment]
I think the setting the word fullscreen should be removed from the option.

**Comment by Overv** [comment]
Okay, so have a setting "Pause on focus loss" where:

Enabled:
* Pause the game in Steam overlay
* Pause the game when focus is lost
* Automatically minimize the game when losing focus in fullscreen

Disabled:
* Don't pause the game automatically
* Don't minimize the game when losing focus in fullscreen

**Comment by Overv** [comment]
Can you explain why pausing on defocus should be merged with the fullscreen minimize feature? Perhaps @trigger-death can elaborate.

**Comment by HaasJona** [comment]
This doesn't compile on Linux because platform_is_steam_overlay_attached seems to be only implemented for Windows. At least add a stub returning false for the other platforms.

**Comment by Overv** [comment]
Yeah, I wanted to wait with the implementation until we've figured out how to handle the user configuration. I've added an implementation for Unix, although I can't test it myself.

**Comment by HaasJona** [comment]
I'm running Linux and I think I can test it tomorrow.

**Comment by janisozaur** [comment]
Can we have steam overlay on openrct2 on Linux, though? How?

**Comment by HaasJona** [comment]
@janisozaur add openrct2 in Steam as custom game and start it in Steam.

**Comment by IntelOrca** [comment]
Hmm, maybe its if you have two monitors with the game fullscreen on one (you have no chrome to minimise it)

**Comment by pizza2004** [comment]
I have 3 monitors and I always keep the game fullscreen while I do other things on my other two monitors.  It would also be nice to have the option to select which screen the game will go fullscreen on, as I've noticed some games do, because then I could decide which of my screens to run it on.

**Comment by IntelOrca** [comment]
Yes we can, providing SDL2 gives us that functionality which I think it does. At the moment it fullscreens to the monitor its currently on I think.

**Comment by Overv** [comment]
>Hmm, maybe its if you have two monitors with the game fullscreen on one (you have no chrome to minimise it)

Okay, imagine this scenario:

I have two monitors and I'm playing OpenRCT2 on my primary monitor. I alt-tab to Chrome on my other monitor to scroll through a Rollercoaster Tycoon strategy guide. I don't want the game to minimise, because I want to keep looking at my park while reading the tips from the strategy guide. However, I also want the game to automatically pause because I'm reading the website instead of playing. Unfortunately I can't do this, because the "auto-pause the game" setting is combined with the "minimise the game" setting.

**Comment by pizza2004** [comment]
Also, it would be nice if edge of screen scrolling was just more intuitive.  Like, if it worked when you're /near/ the edge and not just right on it, then I could still use it even without locking my cursor to the window.  Also being able to disable edge of screen scrolling.

**Comment by IntelOrca** [comment]
You can disable edge scrolling.

**Comment by Overv** [comment]
Anyone else who would like to weigh in on the setting for this feature?

**Comment by IntelOrca** [comment]
Have a separate option then, I didn't realise originally that it was for minimising the game automatically.

**Comment by Overv** [comment]
@IntelOrca Is an OSX implementation necessary as well?

**Comment by IntelOrca** [comment]
I don't know.

**Comment by pizza2004** [comment]
OS X might just be the same as Linux, but you'd have to check to know for sure.

**Comment by HaasJona** [comment]
This does not work on Linux,

    dlopen("gameoverlayrenderer.so", RTLD_NOLOAD)

always returns NULL even if the steam overlay is present. Investigating.

**Comment by janisozaur** [comment]
how is it being loaded? with `LD_PRELOAD`?

**Comment by HaasJona** [comment]
Not sure how steam does that internally, but I can start openrct2 from the console with overlay by calling

    LD_PRELOAD=~/.steam/bin32/gameoverlayrenderer.so ./openrct2

Makes no difference however, dlopen still returns null. I also tried putting the full path into dlopen but still no result. If I change RTLD_NOLOAD to RTLD_NOW then it loads the library, but that's obviously not very useful.

**Comment by Overv** [comment]
I looked at the reference again and it appears that the `RTLD_NOW` flag needs to be specified in combination with `RTLD_NOLOAD`. I verified that it works with LD_PRELOAD with a toy program on my VPS. Could you try it out again?

**Comment by Overv** [comment]
The code should now be able to detect `gameoverlayrenderer.so` no matter how and when it is loaded into the process. The implementation looks rather involved, but I timed it with `clock_gettime` and it takes less than 0.1 ms, so it should not have a noticeable impact.

**Comment by IntelOrca** [comment]
@overv it should only read the pixels etc. if gConfigGeneral.steam_overlay_pause is on.

**Comment by HaasJona** [comment]
@Overv Yes, now it works fine. However I agree with @IntelOrca that the pixel comparing stuff should only happen if the Steam library is detected. Ideally I think the Steam stuff should be relatively easy removable by an ifdef or something like that. Also you should probably call platform_is_steam_overlay_attached() only once and not for each frame even if the performance is fine now.

**Comment by Overv** [comment]
Will do. Is it not possible for the DLL to be injected after the program starts up?

**Comment by HaasJona** [comment]
Not sure, but when I call platform_is_steam_overlay_attached() in the int main() at the earliest position possible, it still outputs the correct result so it should be fine I think.

**Comment by pizza2004** [comment]
@IntelOrca meant that it should only read the pixels if the setting for pausing when the Steam overlay shows up is on, not if the Steam library is detected, but that's still a good idea.

**Comment by Overv** [comment]
The pixels are now only read if the setting is on and if the Steam overlay renderer has been loaded into the process. This is only checked once, when the window is created. I've also verified that this works fine when starting the process with hardware rendering disabled and enabling it later.

**Comment by IntelOrca** [comment]
Its not a big deal, if the player didn't want to use the overlay - they would uncheck the option for pausing.

**Comment by Overv** [comment]
Alright, then it's done as far as I'm concerned.

**Pull request merged**
