### PR TITLE
Fix scrollbar getting stuck on large lists

### PR DESCRIPTION
**Pull request by Gymnasiast**
Caused by an overflow. Partial fix for #592.

### CODE REVIEW

**Comment by IntelOrca** [comment]
This changes the size of the window struct. You would have to be extremely certain this doesn't break any original code logic that is still used.

**Comment by Gymnasiast** [comment]
If I recall correctly, you did some changes to the window system a few weeks ago which were also incompatible with the original implementation, so I think this shouldn't cause problems.

I haven't had problems with it so far. I'll test a bit more, to be sure.

**Comment by IntelOrca** [comment]
You might be able to make them unsigned which would double their capacities - but you would have to check if this breaks anything.

**Comment by Gymnasiast** [comment]
Ok, changed them to unsigned 16 bit integer. It seems to work correctly now.

**Pull request merged**
