### PR TITLE
Optimise accesses to get_current_rotation()

### PR DESCRIPTION
**Pull request by janisozaur**
Yields minor, but observable performance boost.

Around 0.5 fps on http://www.nedesigns.com/park/3324/h2h7-r1-circus-circus-adventuredome-atlantic-city/

### CODE REVIEW

**Comment by IntelOrca** [comment]
I know inline does guarantee inlining, but does it actually increase the chance of it being inlined?

**Comment by janisozaur** [comment]
Yes, it provides a hint to the compiler for a likely inlining candidate. Anyway, time spent in this function went down from 3.26% down to 0.34% (overall accumulated)

**Comment by duncanspumpkin** [comment]
Its one of the reasons we should really not be `&3`ing the rotation its used a ridiculous amount.

**Comment by janisozaur** [comment]
I tested it now dumbed-down:
```
inline uint8 get_current_rotation()
{
	return (uint8)RCT2_GLOBAL(RCT2_ADDRESS_CURRENT_ROTATION, uint32);
}
```

This didn't affect FPS at all.

With the code in the PR, this function barely registers in profiling (0.34% cpu time).

**Comment by IntelOrca** [comment]
@janisozaur if you look at the generated assembly from the compiler, does it actually inline the function?

When I get home I will check this myself with VS, to see if it does already and if not whether the inline keyword makes it inline.

**Comment by zsilencer** [comment]
another small performance boost is moving the if (image_type & IMAGE_TYPE_MIX_BACKGROUND) outside of the loop in sprite.c

**Comment by janisozaur** [comment]
Is this what you meant?

**Comment by zsilencer** [comment]
actually i meant putting the check outside of the for loop and just making another for loop, cause branches inside of loops are usually very slow.

**Comment by IntelOrca** [comment]
yes we should try to reduce branch prediction, and also maybe use generics to make the compiler duplicate the functions for each possible parameter

**Comment by IntelOrca** [comment]
@janisozaur I'll merge your inline, but I don't think it will make a difference for the Windows builds as it looks like VS is already inlining it:

```text
	switch (get_current_rotation()) {
0FADB8B3  movzx       eax,byte ptr ds:[141E9E0h]  
0FADB8BA  and         eax,3  
```

**Comment by janisozaur** [comment]
:+1:

**Pull request merged**
