### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by hyh19962008**
Add "gcc >= 7.1" on 3.1.Linux. Because the project code used C++17 fetures like std::string_view and std::optional, which were fully supported with gcc 7 and above.

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
We also support clang so this isn't quite correct.

**Comment by hyh19962008** [comment]
Well, maybe we can add both of them then? Of course, pointing out that you only need one of them.
The reason for this PR is that, some people like me, we have old distros for daily use (for stable reason) and they are equipped with old compilers (but yes, most of the time they are sufficient for daily use) while the latest ones are not available from the package repos. So, we have to build new compiler from source if we are to compile codes with new features enabled. And this is a time-consuming process.
For me, I upgraded my gcc5 to gcc6  while getting the same compiling error messages as a result. And have to install gcc7 before finally getting the game built successfully.
I think it would save us a lot of time if people like me know just which compiler version they have to at least upgrade to.

**Comment by duncanspumpkin** [comment]
Sure yes i understand that people on legacy systems have legacy compilers I'm just saying if you could make it gcc >= 7.1 or clang >= ?7. Tbh we do state that it's a c++17 project so expecting it to run on such old compilers shouldn't be expected.

**Comment by hyh19962008** [comment]
Alright, I shall try the minimal required version of clang later. But I didn't find anywhere that says this is a C++17 project except in discussions in Github Issues.

**Comment by hyh19962008** [comment]
Add "gcc (>= 7.1) or clang (>= 5.0.0)" on 3.1.Linux.

**Comment by janisozaur** [comment]
Why not just mention "c++17"?

**Comment by hyh19962008** [comment]
Because the implementation for C++17 features is not done in just one compiler version. Clang has initial support for C++17 starting from 3.5, and it's not until 8 that all the features are included.

**Comment by janisozaur** [comment]
We are requiring C++17 compatible compiler, so your comment will soon get obsolete when we start using features not present in clang 5.

**Comment by hyh19962008** [comment]
Yes, you have to update it by then. But readme should reflect the current situation, right?

**Comment by janisozaur** [comment]
The current situation is we require C++17. You may get away with incomplete support on Monday, but not anymore on Thursday.

https://github.com/OpenRCT2/OpenRCT2/blob/b2ae5b1413f6d4b556bb8c1743aa1538fe5650ff/CMakeLists.txt#L58-L59

**Comment by hyh19962008** [comment]
Added "gcc (>= 7.1) or clang (>= 8.0.0) (for C++17 support)" on 3.1.Linux.

**Review by Gymnasiast — APPROVED** [review]

**Pull request merged**
