### PR TITLE
vehicle-fixes

### PR DESCRIPTION
**Pull request by janisozaur**
Apart from whitespace removal, there are two changes:

1. One of conditions is tautological: around line 4040 `vehicle->var_24 < 0`, `var_24` is of type `uint32`
2. I'm sure I have triggered some bad memory in `loc_6D7A97`, but can't find a reason yet, so I placed an assert there.

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
var_24 is a sint32.

**Comment by janisozaur** [comment]
@duncanspumpkin [No it's not](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/ride/vehicle.h#L107)

**Comment by duncanspumpkin** [comment]
No i mean I forgot to change it.

**Comment by janisozaur** [comment]
I removed that change then

**Comment by duncanspumpkin** [comment]
Ta. I'll fix the definition right now before i forget.

**Pull request merged**
