### PR TITLE
Close #12388, refactor PeepState to use strong enum

### LINKED ISSUE #12388: Refactor PeepState to use strong enum

### PR DESCRIPTION
**Pull request by Lukasz-Pe**

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
Missing renames in the test project i think

**Comment by Lukasz-Pe** [comment]
@duncanspumpkin thanks for a tip!
Do you know if there are any plans to add tests to project targets?
I think that this was the cause I have not refactored this file.

**Comment by duncanspumpkin** [comment]
I'm not sure what you mean by project targets. In VS2019 I compile the tests with the rest of the game.

**Comment by Lukasz-Pe** [comment]
I was thinking about CMake file or .idea directory from CLion (which I am using).

**Review by duncanspumpkin — APPROVED** [review]

**Pull request merged**
