### PR TITLE
Refactor ride_data to C++

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by tobiaskohlbau** [comment]
I'm not able to fix this but can tell you what's causing your trouble. Compound literals are not standard compliant C++ and instead of GCC/CLang MSVC does not use C99 extension.

> As an extension, GCC supports compound literals also in C90 mode and in C++, although as explained below, the C++ semantics are somewhat different.

See: [GCC Docs](https://gcc.gnu.org/onlinedocs/gcc/Compound-Literals.html)

Build your project with `-pedantic` and you will receive:
`<source>:10:16: warning: ISO C++ forbids compound-literals [-Wpedantic]`
See https://godbolt.org/g/1waVhd for a simple stripped example.

So you've to port every compound literal from old C style to standard C++, dropping the `(` and `)` should do the trick.

**Comment by janisozaur** [comment]
@tobiaskohlbau partially specialising `Util::CountOf` did the trick, your hint is much appreciated! See https://github.com/OpenRCT2/OpenRCT2/pull/6984/commits/0085f22cde3cb2a119622163e23386edaadf8d64

**Comment by IntelOrca** [comment]
For various new code I have wrapped flags in a namespace and defined them all as `constexpr` which would be another solution to the warning.

**Comment by janisozaur** [comment]
Is that a "you should change it constexpr like I did"? Can you show an example commit?

**Comment by IntelOrca** [comment]
It is up to you.

https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/core/MemoryStream.h#L24

**Comment by janisozaur** [comment]
@IntelOrca then no, we can't do that, at least not yet, as those flags are still used in C code.

**Pull request merged**
