### PR TITLE
Compiler warnings

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by janisozaur** [comment]
`-Wunneeded-internal-declaration`

**Comment by AaronVanGeffen** [comment]
I noticed this has been labelled 'help wanted'. Could you tell us a little about the intention behind this PR? In other words, what can we do to help?

**Comment by janisozaur** [comment]
Enable all the warnings, fix found issues. Especially the ones that I listed above.

**Comment by Broxzier** [comment]
With #7629 there are no warning left on Windows. `-Wunused-function` has been taken care of last week, and `-Wunneeded-internal-declaration` doesn't generate any warnings.

**Comment by janisozaur** [comment]
One of the travis jobs fails in odd ways, I will have to split this PR into multiple chunks.

**Comment by janisozaur** [comment]
It appears it's the last commit, `Mark FreeType as system lib to work around -Wdocumentation failure` that breaks mingw builds. I suspect the reason for that is it replaces `-I /usr/i686-w64-mingw32/include` with `-isystem /usr/i686-w64-mingw32/include`, which for whatever reason is not considered when resolving `#include_next`. This is not confirmed yet, just a theory.

**Comment by janisozaur** [comment]
Looks like my theory is correct:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70129

**Comment by IntelOrca** [comment]
@janisozaur can you disable the warning for that particular CI job and then merge this?

**Comment by janisozaur** [comment]
I was thinking of pragma-disabling the warning for this include in particular and having it as normal (`-I` rather than `-isystem`) include. Any objections to this approach?

**Comment by IntelOrca** [comment]
@janisozaur nope

**Pull request merged**
