### PR TITLE
disable network

### PR DESCRIPTION
**Pull request by janisozaur**
add a cmake option to completely disable multiplayer code. This is most useful for testing, or when MP crashes.

### CODE REVIEW

**Comment by IntelOrca** [comment]
To reduce the number of guard blocks needed, perhaps network_get_mode could just be stub which returns NETWORK_MODE_NONE?

**Comment by janisozaur** [comment]
The point is to not include any of winsock. Even with the change you suggest (it's already there), there's lots of other code that calls out to network.

**Comment by IntelOrca** [comment]
No, take this example:
game.c only calls network_get_mode(), and you have used a guard block round that. You can instead remove guard blocks from game.c and just define a stub version of network_get_mode() when network is disabled. It has nothing to do with winsock, any winsock calls would be in a disable guard block.

**Comment by janisozaur** [comment]
Yes, you are right.
In fact, this was a leftover from initial attempt that I haven't spotted. Do you think the part in `cmdline.c`, `config.c` and `openrct2.c` should be updated as well?

**Comment by IntelOrca** [comment]
Perhaps, although that probably needs to be refactored anyway. More importantly you might want to keep the config, otherwise running the version without network will remove all your saved network settings.

**Comment by janisozaur** [comment]
then it all should be done

**Comment by IntelOrca** [comment]
Are you sure ```strdup``` works with VS?

**Comment by janisozaur** [comment]
You tell me, I haven't got VS or windows.

**Comment by IntelOrca** [comment]
It doesn't... that is why it has the underscore.

**Comment by Gymnasiast** [comment]
After this commit it now builds the project _twice_ on Linux.

**Pull request merged**
