### PR TITLE
Refactor drawing

### PR DESCRIPTION
**Pull request by IntelOrca**
This will take me some time to do, but I thought I'd PR it so people can see the progress and make any suggestions.

People are probably expecting #3798 to go in now, but I'd like to make some changes first which might even improve it. This is taking all the low level code that sets up and draws directly to the 8bpp surface and moving it to its own class abstracted via an `IDrawingEngine` interface. The idea is that in the future we will add other drawing engines which use other technologies such as OpenGL, DirectX, Vulkan etc or even a stub for headless mode.

Additionally there is `IDrawingContext` which is perhaps semi-replacement to `rct_drawpixelinfo`.

This should not affect paint setup.

**OpenGL**:
image

### CODE REVIEW

**Comment by JeroenDStout** [comment]
If I understand the idea properly, what perhaps might be a good thing to pitch is for the interface to acknowledge there may be more than one render target/mode. That way we could add support for depth, or other information that may be useful, and anything that isn't directly drawing could get those buffers out completely unknowing how they were made, optimised, &c.

Another thing I am very interested in is back-buffering, seeing as I run the lighting in a separate thread. Have the interface support one back and one front-buffer, with the dirty drawing working properly for this, could be very nice. That also may lead to multi-threaded drawing in general.

Hope I'm not speaking out of turn with these suggestions. They are just two things that I had to hack in to #3798.

**Comment by IntelOrca** [comment]
Lightning might have to be an implementation detail, its not going to necessarily be implemented in the same way on each drawing engine. Similar to rain and other effects.

**Comment by janisozaur** [comment]
I'll need some time to figure out how to properly do the cmake project file for mingw, right now I managed to compile it manually, but don't know require cmake options.

I'd like to also mention this does not (yet) take scaling into account.

**Comment by IntelOrca** [comment]
@janisozaur reinstated scaling, but only for software. I can't do it for OpenGL without a separate framebuffer - will do that some point in the future.

**Comment by LRFLEW** [comment]
I want to real quick voice my concerns about the f14ea68 commit. There seems to be no reason to do this, as it would be easier to just link OpenGL. On Windows, OpenGL 1.1 is guaranteed (as, without diver support, Windows includes an OpenGL 1.1 to Direct3D translation layer), so linking it doesn't decrease compatibility. OS X is pretty much guaranteed to have OpenGL 2.1 in any compatible OS version. Linux is a bit more complicated, but libGL seems to be a dependency for SDL2, and with the mesa packages, getting a copy of libGL.so shouldn't be a problem, even when there's no hardware or driver support for OpenGL itself. The commit just complicates the codebase. If we just link it and include `SDL_opengl.h`, it should work just fine.

**Comment by janisozaur** [comment]
I think I will have to agree with @LRFLEW and retract my initial objections regarding that. Even though we were not linking in GL before, SDL comes with quite a broad set of dependencies itself.

Some investigations:
1. Arch's `sdl2`: https://www.archlinux.org/packages/extra/i686/sdl2/ already depends on `libgl`
2. Ubuntu's `libsdl2`: http://packages.ubuntu.com/xenial/libsdl2-2.0-0 through an extensive tree pulls in some form of GL as well (see below).
3. Even if someone wanted a *really* headless server (and to ease future porting), we should keep in a GL-less build like we have network-less one now.

Ad. 2, on fresh and clean, fully updated ubuntu server 16.04:
```
janisozaur@ubuntu:~$ sudo apt-get install libsdl2-2.0-0 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libasound2 libasound2-data libasyncns0 libdrm-amdgpu1 libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libegl1-mesa libflac8 libgbm1
  libgl1-mesa-dri libllvm3.8 libogg0 libpciaccess0 libpulse0 libsndfile1 libsndio6.1 libtxc-dxtn-s2tc0 libvorbis0a libvorbisenc2
  libwayland-client0 libwayland-cursor0 libwayland-egl1-mesa libwayland-server0 libx11-xcb1 libxcb-dri2-0 libxcb-dri3-0
  libxcb-present0 libxcb-sync1 libxcb-xfixes0 libxcursor1 libxfixes3 libxi6 libxinerama1 libxkbcommon0 libxrandr2 libxrender1
  libxshmfence1 libxss1 libxxf86vm1 x11-common
```

**Comment by marijnvdwerf** [comment]
- `rain.cpp` is lowercase.
- New headers all use `.h`. core/cmdline use `.hpp`, whereas network uses `.h`.
- Xcode project doesn't have indenting/filetype set properly (assumes .h is a C-header and indentation is with tabs)

**Comment by IntelOrca** [comment]
.hpp is usually only used if it contains templates

**Pull request merged**
