### PR TITLE
Replace 0x009DE56A, 0x009DE56E with gPaintMapPosition

### PR DESCRIPTION
**Pull request by IntelOrca**
@marijnvdwerf what do you think?

### CODE REVIEW

**Comment by marijnvdwerf** [comment]
Not going to work, because original drawing code will depend on `0x9DE56A`/`0x9DE56E`.

**Comment by IntelOrca** [comment]
Why does it still work for me then?

**Comment by marijnvdwerf** [comment]
Do straight track pieces draw supports on each tile now?

**Comment by IntelOrca** [comment]
@marijnvdwerf okay, how about now?

**Pull request merged**
