### PR TITLE
Add RIDE_TYPE_FLAG_HAS_SEAT_ROTATION for multidim rollercoaster

### PR DESCRIPTION
**Pull request by frutiemax**

### CODE REVIEW

**Comment by spacek531** [comment]
IMO this would be better as a field as future rides may use different angles for their rotation.

**Comment by frutiemax** [comment]
Right now it's just used as a boolean, which unlocks the spinbox...

**Comment by spacek531** [comment]
Yes, I saw that.

**Comment by frutiemax** [comment]
I don't want to change the logic of the angles in this PR, this is just to get rid of the RIDE_TYPE_* references.

**Comment by spacek531** [comment]
If I have my way a 4D darkride will be added which will have different rotation logic, but it will still require the rotation UI elements. If you add it as a flag now it will have to be reverted later.

**Comment by frutiemax** [comment]
I would see the seat rotation logic handling as an another field since the logic code is not directly where the flag is used.

**Comment by spacek531** [comment]
In that case the flag is redundant - the field can easily accommodate a "none" value.

**Comment by karst** [comment]
Will this allow for a future pr to add statistics to the multi dimension for seat rotation aswell? Because that'd be pretty neat

**Comment by frutiemax** [comment]
The original intent was to get rid of the RIDE_TYPE_* reference, I'm not sure if want to do this.

**Comment by karst** [comment]
Shouldn't `RIDE_TYPE_FLAG_HAS_CONFIGURABLE_SEAT_ROTATIOM` make more sense? Say if someone wanted to add S&S Freespins or Intamin Zacspins?

**Comment by frutiemax** [comment]
Nope I'm keeping this as a flag, the seat rotation is currently stuck with the construction window class, so you cannot add a field that will go modify it without using abstract interfaces for either cli or ui mode, there are tons of other things to fix first with the RIDE_TYPE_* references.

**Comment by Gymnasiast** [comment]
It’s not for you (or Spacek, for that matter) to decide whether you’re keeping this flag, that’s up to us.

Anyway, I agree having this as a flag. _If_ we ever decide to do more with seat rotation, I expect we’ll need a lot more refactoring anyway, and I’d prefer the legacy bits to be small.

**Review by Gymnasiast — APPROVED** [review]

**Pull request merged**
