### PR TITLE
Fix gaps and errors in water on RCT1 and RCT2 scenarios.

### PR DESCRIPTION
**Pull request by HtotheTML**
A number of maps in RCT1 and RCT2 scenarios have bodies of water that cut off incorrectly. This PR aims to fix that.

### CODE REVIEW

**Comment by HtotheTML** [comment]
Keeping this open. Hopefully some review happens in the future.

**Comment by ZehMatt** [comment]
I'm honestly reluctant to about the changes, this adds quite a lot of lines for the only benefit of some minor discrepancies on some parks which aren't really game breaking issues. All the code was added to the importer, when we post process the imported data then its typically to avoid/fix actual game breaking things for which this PR doesn't really qualify. I wouldn't mind this as much if it would be a separate system which is data driven so anyone could just generate something like a "park patch" to describe what changes need to be applied after the import. The changelog entries also don't quite fit as none of this is actually really "fixing" something but rather adjusts some aspects of the park. I understand that you invested quite some time on this which I appreciate but the method is where I can't honestly agree with. I'm not sure how the other team members feel about this PR but my vote would be against this.

**Comment by HtotheTML** [comment]
That makes sense. I was aware when taking up this task that it would be incredibly low on the priority list, if even added at all. I'm happy that the infernal views water adjustment made it in, in any case.

It made for a good learning experience.

**Review by tupaschoal — COMMENTED** [review]
I tend to agree with @ZehMatt, though I'll admit the screenshots look good. My question would be: do these cut off incorrectly on vanilla as well? Like, are these scenarios "wrongly saved" or is it just us that are importing incorrectly?

**Review by tupaschoal — COMMENTED** [review]
I tend to agree with @ZehMatt, though I'll admit the screenshots look good. My question would be: do these cut off incorrectly on vanilla as well? Like, are these scenarios "wrongly saved" or is it just us that are importing incorrectly?

**Comment by HtotheTML** [comment]
I'll have a look at the vanilla versions of the scenarios, just to be certain.

**Comment by HtotheTML** [comment]
Would like to keep this open for now; haven't had a moment in recent days to verify the same errors existing in vanilla.

**Comment by HtotheTML** [comment]
A cursory glance shows these errors exist in the vanilla versions of their respective games.

**Comment by ZehMatt** [comment]
Closing this for the reason I mentioned in an earlier comment. We either fix the parks directly or introduce a system for easy patching of parks with a basic text/patch file.

**Comment by tupaschoal** [comment]
@HtotheTML this can now be "rebased" to be incorporated using the new `parkpatch` files. We do support the water height, but I don't think we support the other two (remove tile element and set surface index). My suggestion is to split into 3 PRs:

1. One just improving the `.parkpatch` files with the water height fixes
2. One adding a way to remove tile element in a commit and using it in another commit
3. Same as above, but for surface index.

Let me know if you want to follow-up on those 3, otherwise I'll create issues to track them.

**Comment by HtotheTML** [comment]
@tupaschoal It will be a bit difficult for me to do coding work, as classes have resumed for me. I can have a look at PRs for some light testing, but that's about it for now.

**Comment by tupaschoal** [comment]
> @tupaschoal It will be a bit difficult for me to do coding work, as classes have resumed for me. I can have a look at PRs for some light testing, but that's about it for now.

No problem @HtotheTML, I figured so and created the issues so other people could tackle. Reviewing already helps a lot, thanks!

**Pull request closed without merging**
