### PR TITLE
Close #12270 Remove goto from track_remove_station_element

### LINKED ISSUE #12270: Remove goto from track_remove_station_element
https://github.com/OpenRCT2/OpenRCT2/blob/0951c0c5cc3f69a6097251ddc6bdb6047f8f7959/src/openrct2/ride/Track.cpp#L927-L930

### PR DESCRIPTION
**Pull request by 0ro8lu**
Remove use of goto from function track_remove_station_element

### CODE REVIEW

**Comment by 0ro8lu** [comment]
> Please rebase instead of merging one branch into another: [Rebase and Sync fork with OpenRCT2](https://github.com/OpenRCT2/OpenRCT2/wiki/Rebase-and-Sync-fork-with-OpenRCT2)
Ok, i've synced my forked version of the repo with the main devlop branch. So when in CLion i do pull from develop it's not actually updating it? How does it work?

**Comment by tupaschoal** [comment]
When you sync your develop, it's only it that is changing. You then have to either rebase your branch, `track_remove_station_element` in this case, on top of the "new" `develop`, or merge the `develop` onto it.

What you seem to have done is the latter, but we rather prefer the first, because as you can see, merging leaves the PR with lots of commits, which kind of pollutes it a bit.

Remember that when you create your branch, it takes a snapshot from where it's being branched from and, from there onwards, it is a different thing altogether, which needs manual/separate sync.

**Comment by 0ro8lu** [comment]
Mh... how about removing this PR? I’ll redo the modification without polluting the PR with tons of commits

**Comment by duncanspumpkin** [comment]
Remaking PRs is a real pain and doing that every time you make a mistake would lead to 100s of PRs. It's really not difficult to do a rebase.

**Comment by 0ro8lu** [comment]
Sorry, i thought it would be a valid solution, i did not want to look lazy. I've rebased it (hopefully)

**Comment by duncanspumpkin** [comment]
I see now why you were talking about the do while being horrible to look at. This is indeed a horrible to follow function. It isn't a tile element loop so I have no issues with changing it away from being a do while into something completely different. But lets leave that for a second refactoring.

**Comment by duncanspumpkin** [comment]
Please ensure for future work that you use rebase correctly its still not correct. I'll merge this for now but for future. https://github.com/OpenRCT2/OpenRCT2/wiki/Rebase-and-Sync-fork-with-OpenRCT2

**Pull request merged**
