### PR TITLE
OpenGL Palettes

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Fix palettes for open gl.

The transparency is still not really quite right and needs some thought.

### CODE REVIEW

**Comment by IntelOrca** [comment]
There are a lot of spaces / tab issues. Most of these files should use spaces, not tabs.

**Comment by duncanspumpkin** [comment]
yes i still need to resolve that

**Comment by mrtnptrs** [comment]
I get the following errors at the console window when I want to use the OpenGL renderengine: 

> Error compiling C:\Users\maart\AppData\Local\Temp\Rar$EXa0.961\data\shaders\drawimage.frag
> 0(47) : error C7011: implicit cast from "int" to "bool"
> 
> ERROR[src\drawing\NewDrawing.cpp:101 (drawing_engine_init)]: Error compiling shader.
> ERROR[src\drawing\NewDrawing.cpp:102 (drawing_engine_init)]: Unable to initialise drawing engine. Falling back to software.

**Comment by duncanspumpkin** [comment]
@mrtnptrs that should fix it.

**Comment by IntelOrca** [comment]
The following park fails on OpenGL, but not software:
http://www.nedesigns.com/park/466/mont-saint-michel/

**Pull request merged**
