### PR TITLE
Fix #8385: Ghost objects rendered in minimap

### LINKED ISSUE #8385: Ghost objects show up in the mini-map
**OS:** Windows 8
**Version:** 0.2.1
**Commit/Build:** 5a3efe9

Not sure if this is the way things are intended to be or not, but ghost objects that have not yet been built will show up on the mini-map as if they've already been built.

If this isn't the way things are supposed to work, it seems like it would be fairly easy to fix, just an extra line to check if something has the ghost flag before drawing it on the mini-map.

- [?] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. On a bare map (for visibility)
2. Open the mini-map
3. Prepare to build something large (for visibility)
4. See it on the map before committing to build it.

**Screenshots / Video:**

### PR DESCRIPTION
**Pull request by Mikroscopic**
Add a check for the ghost flag before changing map pixel color (First PR, please alert me to any mistakes)

### CODE REVIEW

**Comment by ZehMatt** [comment]
I'm not sure this is a fix at all, I think having ghost objects on my map is actually helpful when you are currently building and not sure exactly where you are at the map. Does this PR do anything else other than hiding it?

**Comment by Mikroscopic** [comment]
Would it be worth drawing ghost objects as a different color to distinguish them from regular objects?

**Comment by Broxzier** [comment]
A lighter shade of their usual colour would work nicely, I think.

**Comment by Mikroscopic** [comment]
I'm not sure there are lighter counterparts for every color in the palette, for instance souvenir shops already use a light pink. Would drawing all ghost objects as white be fine, considering there should only be a single group of them on the map at any given time?

**Comment by duncanspumpkin** [comment]
I think making all ghosts white would be a good idea.

**Pull request merged**
