### PR TITLE
Always use SNN for non-integer scaling

### PR DESCRIPTION
**Pull request by Gymnasiast**
Currently, the user can pick between linear and smooth nearest neighbour, but there is no reason to pick the former: all it does is make the picture more blurry. But lots of users will not be aware of that and leave it on linear.

Not that this only concerns non-integer scales - for integer scales, it still uses nearest neighbour.

### CODE REVIEW

**Review by tupaschoal — COMMENTED** [review]
Do you have a before and after screenshot?

**Comment by Gymnasiast** [comment]
Linear:
Schermafdruk van 2022-01-25 00-23-31

Smooth NN:
Schermafdruk van 2022-01-25 00-23-36

**Comment by illnyang** [comment]
I'm sad that you assumed everyone likes SNN; I never did, for instance, and now people who share my preference (if any...) will have to build from source

**Comment by Gymnasiast** [comment]
Why do you prefer linear? It’s much more blurry than SNN, and does not perform any better.

**Comment by illnyang** [comment]
> Why do you prefer linear? It’s much more blurry than SNN, and does not perform any better.

"Blurry" is more preferable than "jagged" in my book. While most sprites do look fine, there some instances where SNN sets my OCD off. It is most noticeable with text rendering and UI in general. Linear scaling makes things look uniform at least. It would be more bearable if UI used linear scaling, and world sprites used SNN, but I have no idea whether that would be possible without major changes.

Aside from that, it never hurts to give users a choice - it's not like the settings menu was cluttered to begin with. The code behind linear scaling is still there, so this new restriction feels rather arbitrary. You could make SNN the default, since most users seem to prefer it. And/or you could make the setting only exposed in the .ini file and not in the menu.

**Pull request merged**
