### PR TITLE
Fix for OpenRCT2#7877

### PR DESCRIPTION
**Pull request by hokasha2016**
Made the fixes provided and implemented them into the code.

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
You need to clean up your develop branch its causing all your feature branches to have extra commits that aren't related.

**Comment by hokasha2016** [comment]
yeah, im trying to now

**Comment by hokasha2016** [comment]
cleaned the develop branch

**Comment by duncanspumpkin** [comment]
okay you now need to rebase this branch and force push. Should be a case of `git checkout fix_7877`, `git rebase develop`, `git push fix_7877 .... --force` where ... is the name of your github repo.

**Comment by hokasha2016** [comment]
said 34 files were changed, will clean it then reopen

**Pull request closed without merging**
