### PR TITLE
Change water coaster ride type to water ride

### PR DESCRIPTION
**Pull request by trzejos**
Might be worth discussing since WaterCoaster.cpp is under `openrct2/ride/water` while the RTD is in `openrct2/ride/coaster/meta` currently. Related to #18877 

image

### CODE REVIEW

**Comment by ZehMatt** [comment]
In my opinion it is a coaster after all, the description makes that quite clear. It just has segments that contain water but is not primarily on water and uses traditional coaster tracks. I think the current category is fine.

**Comment by AaronVanGeffen** [comment]
Personally, I think the water coaster is primarily a roller coaster rather than a water ride. I would prefer it to stay in the roller coaster category.

**Comment by trzejos** [comment]
From what I've read, it was a water ride in vanilla RCT1/2, and a coaster ride in RCT3. I never played vanilla RCT2, but if that's true I don't know if changing it to a coaster type in OpenRCT2 was a conscious decision or an oversight. I'm fine with either way, but it is a bit odd that there are water coaster source files under ride/water and under ride/coaster. At the very least they should be under one or the other.

**Comment by ZehMatt** [comment]
> From what I've read, it was a water ride in vanilla RCT1/2, and a coaster ride in RCT3. I never played vanilla RCT2, but if that's true I don't know if changing it to a coaster type in OpenRCT2 was a conscious decision or an oversight. I'm fine with either way, but it is a bit odd that there are water coaster source files under ride/water and under ride/coaster. At the very least they should be under one or the other.

It is a coaster with water segments, that is not really a water ride, its a bit like adding a splash track in a wooden coaster and call that a water ride, the way it is seems perfectly fine to me.

**Comment by ocalhoun6** [comment]
Then it should be in the Roller Coasters research group, not the water ride research group.

**Comment by spacek531** [comment]
I thought it was both a coaster and a water ride in RCT1 and RCT2. Same with boat rides being both a gentle ride and a water ride.

**Comment by 733737** [comment]
technically in the code, the dinghy slide is a rollercoaster, but it isn't listed as a rollercoaster

**Comment by trzejos** [comment]
> Then it should be in the Roller Coasters research group, not the water ride research group.

I think it already is in the coaster research group. It gets that based on the RTD

**Comment by trzejos** [comment]
I have this Invention list set up on the latest develop build:
image
You can see it's listed in the roller coaster research group. If you prioritize coasters, you'll get the water coaster first. If you prioritize water rides, you get log flume first instead.

**Comment by trzejos** [comment]
If the general consensus is to keep it as a coaster ride, which I understand. It is a water **coaster** after all, plus that's the direction rct3 went in. OpenRCT2 is not an exact replica of either of the old games and doesn't need to replicate everything exactly as it was. In either case I wasn't able to replicate the behavior @ocalhoun6 reported anyway so maybe this can just be closed.

**Comment by 733737** [comment]
change for the sake of change outside of the scope of the project

**Comment by ZehMatt** [comment]
I think it would have been better to first create a discussion and then do the changes to when we have an agreement to move forward with the idea, ordinarily pull requests shouldn't be used to discuss a change, but lets see what the rest of the team thinks, this is also just my recommendation for the future since you spent time on this which might not be accepted.

**Comment by trzejos** [comment]
Yeah you're right about that. If it doesn't get accepted though it wasn't a lot of time I spent on this.

**Comment by duncanspumpkin** [comment]
I'm going to close this for now. If there is a ground swell of support for changing it to water it can be resurrected.

**Pull request closed without merging**
