### PR TITLE
Add missing synchronization to `JobPool::CountPending`

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Could you elaborate on this a bit? What does it fix (apart from the obvious)?

**Review by Broxzier — APPROVED** [review]

**Comment by Broxzier** [comment]
> What does it fix

A data racing issue and correctness. The size of _pending may change by another thread while reading it her. Reading is not guaranteed to be an atomic operation.

**Comment by Gymnasiast** [comment]
> > What does it fix
> 
> A data racing issue and correctness. The size of _pending may change by another thread while reading it here. Reading is not guaranteed to be an atomic operation.

That was the “obvious bit” I was talking about. What kind of problems might it cause in this specific instance?

**Comment by janisozaur** [comment]
The usual outcomes would include reading stale data

**Comment by Broxzier** [comment]
> That was the “obvious bit” I was talking about. What kind of problems might it cause in this specific instance?

I guess you mean what side effects this could result in, but frankly that is not something to even think about when it's done correctly. In a worst case scenario, one thread saw it is empty while another saw that it is full, and both are waiting for each other. Locking is trivial, and this PR just makes it correct.

**Comment by Gymnasiast** [comment]
No, I meant to ask what side effects could have been _before_ the fix. I never doubted the correctness of the PR, I just wanted to understand what kind of problem not properly locking/synchronising could cause. After all, if there are more errors like this, it’s better if I recognise the symptoms.

**Comment by Broxzier** [comment]
Yeah, that's what I meant. There are a few more cases in our code where we don't use lock guards before accessing a container's size. @IntelOrca doesn't believe it's necessary, which is fair when something is run every frame, but you cannot always rely on that. There was a little discussion about it recently here: https://github.com/OpenRCT2/OpenRCT2/pull/18216

**Pull request merged**
