### PR TITLE
Create category for DLC and BYO scenarios

### PR DESCRIPTION
**Pull request by Gymnasiast**
Makes the “Other tab” less crowded.

afbeelding

### CODE REVIEW

**Comment by ZeeMajora** [comment]
I think it would be nice to add tycoon park from RCT classic to this category as well seeing as we support using RCT classic scenarios and it's an official other scenario.

**Comment by 733737** [comment]
I'd prefer Other Official to Other official

**Comment by IntelOrca** [comment]
Offical isn't a good term to use here as it isn't obvious whether official means part of the original games or official to OpenRCT2. How about something like "DLC Parks"?

**Comment by ZeeMajora** [comment]
> Offical isn't a good term to use here as it isn't obvious whether official means part of the original games or official to OpenRCT2. How about something like "DLC Parks"?

Only half of them are DLC parks as the rest are the build your own six flags parks that come with 2, plus tycoon park already comes with classic if that is added to the list.
How about "Extras"? That's what rct1 called it's tab where it's dlc scenarios would go. I think that would work a bit better as it's a lot more general than DLC parks.
Screenshot_select-area_20220924103242

**Review by rik-smeets — CHANGES_REQUESTED** [review]
Code looks fine to me; I do agree a different name would be better. I like @ZeeMajora's proposal of "Extras".

**Comment by Umdlye** [comment]
The window looks like this when there's no linked RCT1 installation: 
openrct2_OmJa3AVQ6e

**Comment by Gymnasiast** [comment]
Changed it to “Extras”. Also fixed the issues @Umdlye reported.

**Review by rik-smeets — APPROVED** [review]

**Pull request merged**
