### PR TITLE
Potential fix #2151.

### LINKED ISSUE #2151: When building a rollercoaster, attempting to use the advanced path makes the path tool attempt to continue building the rollercoaster.
scr32

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Fix #2151.
I think this fixes the issue but its hard to understand from the original issue. This still needs to be cleaned up and properly documented but I want to see what others think of this fix.

### CODE REVIEW

**Comment by IntelOrca** [comment]
* Only works for path bridge mode, not click and drag mode.
* Closing the footpath window causes the gridlines to disappear (I think that might be a separate issue)

**Comment by duncanspumpkin** [comment]
Okay I've changed it around a bit and it now works fine with the drag mode. Any suggestions.

**Comment by IntelOrca** [comment]
* Land tool, water tool etc. etc. all have the same problem.
* The gridlines keep flashing when you place path.
* The gridlines disappear from path bridge mode.

It feels like #2151 isn't fixed until it all runs together smoothly. It could be easy to say, disable ride construction if you use the other tools - but I reckon its very common to do land alternations etc. as you construct a ride so you wouldn't want it to close the ride construction window.

**Comment by duncanspumpkin** [comment]
I'm not too sure what you mean by the gridlines flashing and disappearing it looks fine for me.

**Comment by IntelOrca** [comment]
The yellow grid lines under the ghost track piece.

**Comment by duncanspumpkin** [comment]
I can't easily fix that. Its a common variable for the two functions so it flickers between the two as they get called to update.

**Comment by IntelOrca** [comment]
ok - nevermind then

**Pull request merged**
