### PR TITLE
Fixed translation from en-US 'bathroom' to en-GB 'toilet'

### PR DESCRIPTION
**Pull request by gsp8181**

### CODE REVIEW

**Comment by Gymnasiast** [comment]
There are two more occurrences of 'bathroom' in the language file. Could you change those as well?

**Comment by Goddesen** [comment]
An observation: According to [this graph](https://books.google.com/ngrams/graph?content=water+closet%2Cbathroom%2Crestroom%2CWC%2Clavatory%2Cwashroom%2Cmens+room%2Cladies+room%2Cmen%27s+room%2Ctoilet%2Ctoilets%2Cwomen%27s+room&year_start=1800&year_end=2008&corpus=18&smoothing=3&share=&direct_url=t1%3B%2Cwater%20closet%3B%2Cc0%3B.t1%3B%2Cbathroom%3B%2Cc0%3B.t1%3B%2Crestroom%3B%2Cc0%3B.t1%3B%2CWC%3B%2Cc0%3B.t1%3B%2Clavatory%3B%2Cc0%3B.t1%3B%2Cwashroom%3B%2Cc0%3B.t1%3B%2Cladies%20room%3B%2Cc0%3B.t1%3B%2Cmen%20%27s%20room%3B%2Cc0%3B.t1%3B%2Ctoilet%3B%2Cc0%3B.t1%3B%2Ctoilets%3B%2Cc0%3B.t1%3B%2Cwomen%20%27s%20room%3B%2Cc0), bathroom seems reasonable. "Bathroom" being a common euphemism for "toilet" seems to me like a perfectly reasonable thing to leave in en-GB for peeps (though not necessarily UI, as we don't care about being discreet :dancer: ).

**Comment by Gymnasiast** [comment]
No, 'toilet' is far more common in the UK, and it is also used throughout the file, with the exception of the three occurrences of bathroom. So even if it weren't for bathroom being a semi-Americanism, there is still the matter preference, and the matter of consistency.

**Comment by IntelOrca** [comment]
Bathroom is commonly used, although I don't think its correct if it doesn't contain a bath. Most places I go, the signs will say "Toilets" or just "Gents" and "Ladies", I don't recall seeing Bathroom ever for public toilets.

**Comment by gsp8181** [comment]
Yep, saying you need to go to the Bathroom is fine if there is a Bath/Shower in there but it is always toilet if there isn't one

**Pull request merged**
