### PR TITLE
Place constexpr functions in anonymous namespace

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by janisozaur** [comment]
I got a comment requesting I do the namespace thing instead of `static` previously. I think it was this project, but can't be bothered to find it.

**Comment by IntelOrca** [comment]
Could you explain the reason you are doing this in your commit?

**Comment by janisozaur** [comment]
`constexpr` is not required to evaluate on compile time and could be a regular function in such case. It should then be marked as `static` or put in anonymous namespace.

**Comment by AaronVanGeffen** [comment]
I'd prefer sticking with `constexpr` if it means we can avoid the -frankly- ugly `[[maybe_unused]]` annotations.

**Comment by janisozaur** [comment]
No, `constexpr` can still be unused, as you could see in one of the previous runs, reported by clang.

**Comment by tupaschoal** [comment]
> I got a comment requesting I do the namespace thing instead of `static` previously. I think it was this project, but can't be bothered to find it.

Alright, no big deal

**Pull request merged**
