### PR TITLE
Balance item groups in the load/save menu

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
Implements #21979. Before/after screenshots below.

In game:
game_before

Scenario editor:
editor_before

Track designer:
designer_before

Track design manager:
design_manager_before

### CODE REVIEW

**Review by Basssiiie — APPROVED** [review]
Haven't tested it but am a big fan of this order and amount of separators. Really an improvement!😃

**Comment by ZehMatt** [comment]
I wouldn't mind if Options was separated as well and also have it above About, I generally like it when the choices are ordered by what you are going to press most likely, the about/report bug is something users will least likely click.

**Comment by AaronVanGeffen** [comment]
I'd like to avoid item groups with just one option, to be honest. I considered moving 'Options' alongside the two 'Screenshot' options, but considering that, it seems better to just file it with 'About', to me.

**Review by Gymnasiast — APPROVED** [review]
I don’t necessarily think it’s necessary, but I’m not that fussed either.

**Pull request merged**
