### PR TITLE
Increase Loan Interest in Scenario Editor Limit from 80% to 255%

### PR DESCRIPTION
**Pull request by 733737**
I have rebased my PR, and for some reason the old PR vanished from github, I don't know how... I hope that this PR will be accepted because I have friends that want higher interest rates that are avid scenario makers in the community, thank you

### CODE REVIEW

**Comment by Gymnasiast** [comment]
This needs two things changed:
- The commit history is full of trash. You’ll need to squash this into a single commit
- You will need to add a constant for this maximum loan percentage, rather than changing the hardcoded number 80.

**Comment by Gymnasiast** [comment]
It vanished because you didn’t create a branch but committed all your changed directly to `develop`. For any next PRs, you’ll need to create branches.

**Review by Gymnasiast — CHANGES_REQUESTED** [review]
This needs two things changed:
- The commit history needs to be squashed into a single commit - it’s currently full of junk and merge commits
- You’ll need to introduce a constant for the maximum loan percentage, rather than changing the hardcoded number 80.

**Comment by 733737** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/61d74eaa4b53b4f0d555faa01598561d35e28bb5/src/openrct2/management/Finance.cpp#L151    this is where it is defined as a constant, wouldn't another constant just be a duplication? Also, the UI aspect of it works in game, are you saying that the code doesn't work or just that it isn't formatted correctly?

**Pull request closed without merging**
