### PR TITLE
Add RideUpdate to RTD

### PR DESCRIPTION
**Pull request by frutiemax**
Chairlift and spiral slide has specific update functions.

### CODE REVIEW

**Review by tupaschoal — COMMENTED** [review]
I don't love the `friend`, but I guess it's a stepping stone.

Just needs to solve merge conflicts and seems ok.

**Comment by Gymnasiast** [comment]
@tupaschoal Do you have an alternative?

**Comment by tupaschoal** [comment]
I gotta think, but at the time I couldn't, I'm fine with merging as is, just needs conflicts to be solved

**Comment by frutiemax** [comment]
Merged to develop.

**Review by tupaschoal — APPROVED** [review]

**Pull request merged**
