### PR TITLE
Add define for max vehicles per ride entry, replace some missed occurrences of SPRITE_INDEX_NULL

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by janisozaur** [comment]
@Gymnasiast can you please make the commit messages shorter?

**Comment by Gymnasiast** [comment]
Not without removing important information. Unless you have a good suggestion.

**Comment by IntelOrca** [comment]
`Define max vehicles per ride entry, use SPRITE_INDEX_NULL more`

I usually find that neither GitHub website or command line warns you of long commit messages, so its hard to tell.

**Comment by Gymnasiast** [comment]
I fail to see the problem, really. It's way more important to have a clear message. Who cares if it's longer than 70 characters.

Regardless of this, I'll go with @IntelOrca 's suggestion.

**Comment by janisozaur** [comment]
@Gymnasiast I do, because it breaks my workflow, where I can see the graph of commits with a commit per line - which is why the "subject" line matters. Otherwise it's all a mess. I'm not strict on the 50 chars, which is the recommended length, but not long enough to get wrapped on github 's web ui (which I think is 72 chars).

**Pull request merged**
