### PR TITLE
Drop number from build ID.

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
What's the rationale behind this change? To most people, a higher build number is more telling than an enigmatic commit hash, I think.

**Comment by janisozaur** [comment]
The build *number* carries absolutely no meaning. From user's point of view it's only a way of verifying if he is on a particular build or not:
* in case of bug fixes a particular build, which is just a string comparison anyway
* in most cases: "am I on latest build or not", which again is a simple string comparison if they do it themselves, but in most cases there will be a system which will update it for them, be it the launcher or a package manager.

From our (developer's) point of view it removes the hassle of resolving build number to commit.

**Comment by IntelOrca** [comment]
The issue is that users are saying that they are using build X, but without the build server we can only guess and have to manually find the build server's mapping from build number to commit.

**Comment by AaronVanGeffen** [comment]
Got it. Thanks.

**Comment by JarnoVgr** [comment]
I'm still against this change. There's only 1 active build server at this moment, and do you guys really expect to mention the git hash short everytime they report something? Including the build ID is actually something that many people already mention without us asking.

**Comment by JarnoVgr** [comment]
On top of that: How would one tell the difference when updating using the installer? There's literally nothing you can compare against. But when comparing build IDs it actually makes sort-of sense, even though it doesn't say anything specific.

**Pull request merged**
