### PR TITLE
Fix #4513: Use system encoding when accessing paths with posix

### LINKED ISSUE #4513: Cannot join multiplayer server with umlaut in player name
**OS:** Arch Linux
**Version:** 0.0.5
**Commit/Build:** d81bed5

When trying to join a muliplayer server while having an umlaut in the player name the connection gets stuck at `Authenticating`.

For exmple when trying to connect as `Stäbchenfsich` the console prints the following:

```
Generating key... This may take a while
Need to collect enough entropy from the system
VERBOSE: Key successfully generated
VERBOSE: New key of type 6, length 2048 generated successfully.
Key generated, saving private bits as /home/manuel/.config/OpenRCT2/keys/Stäbchenfisch.privkey
VERBOSE: adding subDirectory 'keys'
VERBOSE: outPath + subDirectory = '/home/manuel/.config/OpenRCT2/keys/'
VERBOSE: /home/manuel/.config/OpenRCT2/keys/
VERBOSE: saving key of length 887
VERBOSE: adding subDirectory 'keys'
VERBOSE: outPath + subDirectory = '/home/manuel/.config/OpenRCT2/keys/'
Key generated, saving public bits as /home/manuel/.config/OpenRCT2/keys/Stäbchenfisch-7c9a7861f77b4bc6746b1ff98917051b254886be.pubkey
VERBOSE: requesting token
VERBOSE: adding subDirectory 'keys'
VERBOSE: outPath + subDirectory = '/home/manuel/.config/OpenRCT2/keys/'
VERBOSE: file '/home/manuel/.config/OpenRCT2/keys/St' exists = 0
ERROR[/home/manuel/.cache/pacaur/openrct2-git/src/openrct2-git/src/network/network.cpp:1327 (Client_Handle_TOKEN)]: Key file (/home/manuel/.config/OpenRCT2/keys/Stäbchenfisch.privkey) was not found. Restart client to re-generate it.
```
Public and private key are generated fine (i can see them in the directory) however the game fails to load them after generation. The last `VERBOSE` line contains the path to the privkey but seems to get cut off at the umlaut when trying to load the key.

- [ ] Reproducible in RCT2 (vanilla)
- [x] Multiplayer

**Steps to reproduce:**
1. Set a player name with an umlaut
2. Try to join a server

### PR DESCRIPTION
**Pull request by manuelVo**
For details see [this comment](https://github.com/OpenRCT2/OpenRCT2/issues/4513#issuecomment-250996835)

### CODE REVIEW

**Comment by IntelOrca** [comment]
@LRFLEW @marijnvdwerf Can you check if this is okay?

**Comment by manuelVo** [comment]
I replaced two wrongly used ints by size_t.

Also I had a friend test this on his mac. It doesn't work, but it didn't work before either. The environment variables used by setlocale don't seem to be set on mac os, so i guess fixing this for mac is a bit harder and might be worth a separate pull request.

**Comment by LRFLEW** [comment]
I can try to take a look at this, but testing unicode support may be harder for me. I'm not sure the `setlocale(LC_CTYPE, "");` call is necessary (and it if is, it might mess up other code that's setting the locale). Otherwise it *looks* good. I can understand this not working on macOS for one reason or another, but probably the better solution would be to separate out the macOS implementations for this, and use the Objective-C libraries to do this "correctly".

**Comment by manuelVo** [comment]
`LC_CTYPE` isn't used anywhere else in the code right now so i don't expect any conflicts. I don't know the best practices for `setlocale` but i guess if different locales are required within the application it would be best to call `setlocale` with the proper locale before a locale-sensitive function is called. Also, if we want to use `wcstombs` for conversion to multibyte strings I don't see any way of avoiding calling `setlocale`, since `wcstombs` needs to know how to encode the string.

I agree that writing a separate implementation for mac using the objective-c libraries is probably the best way.

**Comment by manuelVo** [comment]
I rebased the branch and resolved the merge conflicts.

**Comment by janisozaur** [comment]
works as advertised 👍

**Pull request merged**
