### PR TITLE
Add BUILD_BYPRODUCTS entries to CMakeLists for googletest

### PR DESCRIPTION
**Pull request by janisozaur**
This allows building tests with ninja build system

### CODE REVIEW

**Comment by marijnvdwerf** [comment]
Looks okay for now, but probably should use variables in the future.

**Comment by IntelOrca** [comment]
Should we convert all the cmake files to use spaces?

**Comment by marijnvdwerf** [comment]
I think consistent casing of functions is more of an issue than spaces. But I don't mind having the same soft tabs everywhere. (C++ vs C is a different story, as CLion doesn't allow you to split the code style for those)

**Comment by janisozaur** [comment]
@marijnvdwerf @IntelOrca any changes still required?

**Comment by IntelOrca** [comment]
nope

**Comment by marijnvdwerf** [comment]
Let's tackle #5046 while we're add it.

**Comment by janisozaur** [comment]
@marijnvdwerf is it done now?

**Comment by marijnvdwerf** [comment]
@janisozaur It now works for me, so yeah.

**Comment by marijnvdwerf** [comment]
Fixes #5046

**Pull request merged**
