### PR TITLE
Include shop item values at `0x00982164`

### PR DESCRIPTION
**Pull request by marijnvdwerf**
Reversed columns used for hot and cold values. Seemed to be a mistake in decompiling

### CODE REVIEW

**Comment by marijnvdwerf** [comment]
Probably needs checking in whether the `> 32` values are correct. Was a bit confusing because of the overlap.

**Comment by IntelOrca** [comment]
overlap?

**Comment by marijnvdwerf** [comment]
The original array doesn't have stats for some items, and the original code accounted for that by using a different offset. I just zerofilled it, but more based on sense than on logic.

**Comment by IntelOrca** [comment]
@marijnvdwerf good, that is what I have done with other shop item arrays. I am a little surprised CS started a new 32-bit flag integer and array before filling the first one.

**Pull request merged**
