### PR TITLE
Windows: Support dark theme for window titlebar/chrome

### PR DESCRIPTION
**Pull request by sungaila**
This PR adds support for Windows dark theming. Win32 apps (OpenRCT2) can call an API to apply a dark theme. This recolors the titlebar, caption, window buttons and even changes the shadow depth of the window.

To apply the dark theming [DwmSetWindowAttribute (dwmapi.h)](https://learn.microsoft.com/de-de/windows/win32/api/dwmapi/nf-dwmapi-dwmsetwindowattribute) with `DWMWA_USE_IMMERSIVE_DARK_MODE` is called.

To react on system theme changes the window message queue is observed for `WM_SETTINGCHANGE` and `ImmersiveColorSet`.

SDL 3.x will support this out-of-the-box in a future release (see https://github.com/libsdl-org/SDL/commit/8994878767cfb9403f525d12c0770c1e149a4d08). Until OpenRCT2 is updated to a newer SDL version, this has to be done manually.

Interestingly, there is no guard for checking the Windows version needed. The [official Microsoft docs](https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/apply-windows-themes#enable-a-dark-mode-title-bar-for-win32-applications) don't check this and neither is [SDL](https://github.com/libsdl-org/SDL/blob/26e947f8eaab4737a597c60993adb9a8d0634127/src/video/windows/SDL_windowswindow.c#L1695C1-L1707C2). It looks like `DwmSetWindowAttribute` ignores this call on older Windows versions.

This was tested on Windows 11 version 23H2 (Build 22631.3085) and Windows 10 version 22H2 (Build 19045.3996). For all three builds: x86, x64 and arm64.

Note: the dark theme is applied to common dialogs (like OpenFile) regardless. No changes to see here.

### Windows 11
| Light theme (default) | Dark theme |
| -------- | ------- |
| Win11 light theme | Win11 dark theme |

### Windows 10
| Light theme (default) | Dark theme |
| -------- | ------- |
| Win10 light theme | Win10 dark theme |

### CODE REVIEW

**Comment by ZehMatt** [comment]
I rather not have this platform specific code added, we have too much of that already. I think its better to wait for SDL 3 to be released. Also it would have been best if this would have been brought to an issue/discussion first.

**Comment by sungaila** [comment]
> Also it would have been best if this would have been brought to an issue/discussion first.

I agree, however, the first question would be about the boilerplate code to make this happen. So before I post code snippets, I've decided to create a PR instead. :-)

**Comment by ZehMatt** [comment]
> > Also it would have been best if this would have been brought to an issue/discussion first.
> 
> I agree, however, the first question would be about the boilerplate code to make this happen. So before I post code snippets, I've decided to create a PR instead. :-)

I rather not have code to make up for Microsofts stupidity like this. Best to just wait for SDL3

**Comment by Broxzier** [comment]
I agree with Matt that we better wait for the framework we use to implement this instead of doing it ourselves. I'm also not happy about the introduction of the `Initialize` function, this is what constructors are for.

**Comment by sungaila** [comment]
> I'm also not happy about the introduction of the `Initialize` function, this is what constructors are for.

I think this is just a badly named function since it mirrors `SetWindowIcon` in functionality: take a new SDL_window and apply something. `SetWindowTheme` might be a better name. Or just put it into `SetWindowIcon` as a temporary solution.

Waiting for SDL 3.2.0 would make this PR redundant, [but it won't be released in the near future](https://github.com/libsdl-org/SDL/milestone/10). And even if it were, [it will need some effort to migrate OpenRCT2 from SDL 2.x to 3.x](https://github.com/libsdl-org/SDL/blob/main/docs/README-migration.md).

The macOS users have dark theme support out-of-the-box. Don't punish Windows users just because Microsoft favors backwards compatibility over clean APIs. ;-)

**Comment by ZehMatt** [comment]
Sorry but hard no from my end, it's too much code for just changing the color of the title bar and when SDL 3 drops we would have to modify this code again. Also given that nobody has created an issue for this it doesn't seem like people really care that much about it.

**Comment by Gymnasiast** [comment]
Due to two other team members not being on board, I will close this.

**Pull request closed without merging**
