### PR TITLE
Icons for new object selection tabs

### PR DESCRIPTION
**Pull request by oli414**
This PR adds 5 new icons for the object selection window

image

- Terrain edge
- Path surface
- Path support/railings
- Legacy paths
- Ride entrance

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Please rename path_supports.png to path_railings.png - we call it "path railings" everywhere in the code and it’s better to be consistent.

**Comment by Gymnasiast** [comment]
The icon for path railings looks shifted to the left. It looks like it needs adjustment by one or two pixels.

**Comment by oli414** [comment]
> The icon for path railings looks shifted to the left. It looks like it needs adjustment by one or two pixels.

It is intentionally not centered so that it is more clear that what you see underneath are supports.

**Comment by Gymnasiast** [comment]
It looks a bit off to me, but well...

**Review by Gymnasiast — APPROVED** [review]

**Pull request merged**
