### PR TITLE
Drop Ubuntu Focal v20.04 from the CI roster

### PR DESCRIPTION
**Pull request by AaronVanGeffen**

### CODE REVIEW

**Review by janisozaur — APPROVED** [review]

**Comment by ZehMatt** [comment]
The CI gets stuck somehow now.

**Comment by janisozaur** [comment]
I think only Duncan and Ted have necessary permissions

**Comment by Gymnasiast** [comment]
Fixed that. After this PR has been merged, we should "readd" them. (As well as adding the ones that were not marked as required

**Review by Gymnasiast — APPROVED** [review]

**Comment by janisozaur** [comment]
My bad, I see now more people have access, the settings are located here: https://github.com/OpenRCT2/OpenRCT2/settings/branch_protection_rules/22071859
image

**Pull request merged**
