### PR TITLE
Close #13267: Remove obsolete dockerfiles

### LINKED ISSUE #13267: 64bit Dockerfile key error
Seeing some key errors

```
cd Dockerfiles/
docker build 64bit
```

This the error I get

```
downloading shadow-4.8.1-4-x86_64.pkg.tar.zst...
downloading tar-1.32-3-x86_64.pkg.tar.xz...
checking keyring...
downloading required keys...
error: key "6D42BDD116E0068F" could not be looked up remotely
error: key "3B94A80E50A477C7" could not be looked up remotely
error: key "7258734B41C31549" could not be looked up remotely
error: required key missing from keyring
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
The command '/bin/sh -c pacman -Syyu --noconfirm' returned a non-zero code: 1
```

Googling the `error: key could not be looked up remotely`, I just get advice like `pacman -S archlinux-keyring`, or `pacman-key --refresh-keys`, however installing package won't work because the package db isn't updated yet (didn't work when I tried)

`--refresh-keys` has this issue:

```
Step 2/6 : RUN pacman-key --refresh-keys
 ---> Running in cbef26734b3f
gpg: refreshing 112 keys from hkps://hkps.pool.sks-keyservers.net
gpg: keyserver refresh failed: General error
==> ERROR: A specified local key could not be updated from a keyserver.
```

### PR DESCRIPTION
**Pull request by tupaschoal**
Build docker files now here: https://github.com/OpenRCT2/openrct2-docker-build
Runtime docker files now here: https://github.com/OpenRCT2/openrct2-docker

@IntelOrca & @janisozaur should we also remove the debian folder (on another PR)?

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Don't think we should remove the Debian folder. It is used for building the packages for the Ubuntu PPA.

**Comment by janisozaur** [comment]
Isn't `openrct2-cli` used for our images?

**Review by IntelOrca — APPROVED** [review]

**Comment by tupaschoal** [comment]
> Isn't `openrct2-cli` used for our images?

I guess it's a different thing, but I'm not 100% sure. Can you confirm @IntelOrca ?

**Comment by IntelOrca** [comment]
I don't know what @janisozaur is talking about. No one uses, or should not be using these dockerfiles anymore so they can be deleted.

**Review by janisozaur — APPROVED** [review]

**Pull request merged**
