### PR TITLE
Fix #3243 - Staff naming permission fix (Review)

### LINKED ISSUE #3243: Changing staff's name is a GUEST command (permissions)
**OS: Win 7** 
**Version: 0.4.0.0** 
**Commit: a8efcef** 

When you edit a staff members name online, it counts as a **Guest** command, therefor restricting it if the player ain't allowed to edit Guest commands.
The rest of the stuff (hire staff, patrol areas & tell them what to do) is all staff commands
The names should be too, if possible

- [ ] Reproducable in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Host a server and join as a client
2. Edit a staffs name
3. See what command the user did ('Guest')

**Screenshots / Video:**
staff

### PR DESCRIPTION
**Pull request by Nubbie**
This fixes issue #3243  
This code was made by **Deluxe** (Doesn't have Github, OpenRCT2 name) which is new to Github so I made this pull request for him

He isn't 100 % sure about this tho' so could it be reviewed before merge. 
Thanks

### CODE REVIEW

**Comment by IntelOrca** [comment]
@Nubbie we would prefer Deluxe to have their own GitHub account rather than committing through someone else.

**Comment by Nubbie** [comment]
@IntelOrca Understand that and I still take all responsibility for this code just because I posted Deluxe work on my account. This was a little bit of a test for him to feel if he would like to help this project on Github etc as he's new to the whole 'Github Open Source' thing :)
If he wants to continue contributing - He will make his own account

**Comment by IntelOrca** [comment]
@Nubbie I think its silly to just not create an account anyway. You need it to edit the wiki, post issues, talk on gitter or properly fork the project. What is the harm in creating an account?

**Comment by Nubbie** [comment]
@IntelOrca To his defense, I showed him this project on Github and he got interested in helping out with this project as I told him the different things he could do, so he found a issue and started to fix it for 'fun' and to try out if this was something for him

That's why I posted it just so it didn't get wasted but also so he could see the process and see how it is to make issues + pull requests. It's always satisfying to see your work get pushed out into the final product.
All instead of first making a account, learn how Github works, do all the stuff and after this pull request figure out it's nothing for him and delete the account, but, if he wants to continue, he will make an account ^^

**Comment by zsilencer** [comment]
Adding a new game command in the middle of the list reassigns all the others below it, so this would require NETWORK_STREAM_VERSION to be changed for compatibility.

**Comment by Nubbie** [comment]
@zsilencer Changed the 'Network_stream_version' to 6 but now the check failed, is it correct or is something else wrong?
Should I re-write the code into the new files after the 'Cluster' merge? (If something else is missing)

**Comment by Nubbie** [comment]
Ok - I'm totally stuck in a limbo now.. 
Really have no idea how to fix this now since the cluster merge
Is it easier to close this and start over with the new code and create a new pull request?
As I suspect network.h collides with #3275

**Comment by duncanspumpkin** [comment]
You just rebase it and make the required changes.

**Pull request closed without merging**
