### PR TITLE
UK: Change 'fullscreen (desktop) to the more common 'borderless windowed', closes #3128

### LINKED ISSUE #3128: Consider changing 'Fullscreen (desktop)' to 'Fullscreen (borderless windowed)'
I play OpenRCT2 frequently and only did recently find out about this option. It did confuse me, and I'm sure other people won't know what the difference between 'Fullscreen' and 'Fullscreen (desktop)' is. 'Borderless windowed' is a more common term.

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by IntelOrca** [comment]
Perhaps ```Windowed (borderless)``` would look better against the other options.

The only issue I have with this is that it no longer says fullscreen. You can have a borderless window that isn't fullscreen, but in this case it is. So perhaps ```Fullscreen (borderless window)``` would be better...

**Comment by janisozaur** [comment]
I'm with @IntelOrca on this one. In no way does `borderless windowed` imply going fullscreen.

**Comment by Gymnasiast** [comment]
I'm completely fine with that, as it is indeed clearer. But if we opt for `Fullscreen (borderless window)` we will need to make the dropdown larger in order to have it fit.

**Comment by marijnvdwerf** [comment]
@Gymnasiast dropdown size already is an issue. 
image

**Comment by Gymnasiast** [comment]
All the more reason to enlarge it then.

**Comment by pizza2004** [comment]
Borderless Window or Borderless Windowed appears to be the standard nomenclature to refer to that display mode in most games.

**Comment by PFCKrutonium** [comment]
http://pcgamingwiki.com/wiki/Glossary:Borderless_fullscreen_windowed

> A borderless mode allows any windows to be centered and behave like a fullscreen mode. Set the desired game to run in a Windowed mode first before applying a borderless mode.

**Comment by marijnvdwerf** [comment]
While you're at it. A setting called 'Fullscreen mode' with a value named 'Windowed' doesn't make much sense. Maybe consider changing it to 'Screen mode'?

**Comment by Gymnasiast** [comment]
Replaced by #3138.

**Pull request closed without merging**
