### PR TITLE
Fix maze placement

### LINKED ISSUE #2828: Evergreen Gardens Maze Crash
Something is breaking in the GAME_COMMAND_SET_MAZE_TRACK code causing an infinite loop. See https://www.reddit.com/r/rct/comments/42uk7i/premade_maze_layouts_crashing_in_emerald_greens/ for more information on how to reproduce.

Reproduceable on e7545983f15cf56ca22a9e9b04510421842d7b0d
Doesn't happen in vanilla.

### PR DESCRIPTION
**Pull request by marijnvdwerf**
Fixes #2828

### CODE REVIEW

**Comment by IntelOrca** [comment]
Put "Fixes #2828: shifting by wrong number of bits" in your commit message, then it will automatically close the issue when I merge the PR.

**Comment by janisozaur** [comment]
@IntelOrca there's no need to, it works fine as-is.

Screen from #2828:
zaznaczenie_097

**Comment by duncanspumpkin** [comment]
@janisozaur it's still much easier to find relevant discussion if you put it in the commit message

**Comment by IntelOrca** [comment]
@janisozaur hmm fair enough. But as @duncanspumpkin said, a ```git log``` would show the issue for the commit.

**Comment by marijnvdwerf** [comment]
Better?

**Comment by IntelOrca** [comment]
I was suggesting you change it to only "Fixes #2828: shifting by wrong number of bits", but you have just appended that to your original message.

**Comment by marijnvdwerf** [comment]
Next time just make the change directly in develop. "Put it in the message" isn't exactly clear.

**Pull request merged**
