### PR TITLE
Clean up and name remaining widgets

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
While the widgets system is due for replacement, it looks like we will be using it for some time still. I thought I'd clean up the remaining unidentified widgets a little.

### What does this do?

This PR refactors the following widgets:
* `WWT_DROPDOWN_BUTTON` -> `WWT_BUTTON`
(Initially, I had replaced it with `WWT_BUTTON_CENTRED`. I decided `WWT_BUTTON` was better, however, as it seems to be the rule rather than the exception. I'm deliberately dropping the `DROPDOWN` part, as dropdowns aren't always involved.)
* `WWT_12` -> `WWT_LABEL_CENTRED`
(Centred string)
* `WWT_13` -> `WWT_TABLE_HEADER`
(This is a left-aligned button used for headers in e.g. the object selection window.)
* `WWT_14` -> `WWT_LABEL`
(Just a left-aligned string.)
* `WWT_24` is refactored into `WWT_LABEL`.
(It relied on rendering a checkbox widget, without an actual checkbox — it was merely offset.)
* `WWT_25` -> `WWT_PLACEHOLDER`
(Only used in bottom toolbar as a placeholder while still capturing events. Yes, my initial idea was to fold it into `WWT_EMPTY`...)

For clarity and maintainability, the following unused widgets are dropped:
* `WWT_4`
* `WWT_5`
* `WWT_11`
* `WWT_18`

I have also changed the logic for button text alignment, such that all buttons now have their text vertically aligned. This also removes the need for a hack where `WWT_CLOSEBOX` had to be used to get vertically aligned button captions.

### What's next?

- [x] If this is approved, I'll fix the formatting for the widget tables — I have a feeling some might disagree with the naming.
- [x] I'd also like to stash the widget removal commits into one commit before this PR is merged.

### Does it impact UI?

No, the UI should not be affected at all. This is mostly preliminary work.

### CODE REVIEW

**Comment by marijnvdwerf** [comment]
What about `WWT_DATATABLE_HEADER` instead of `WWT_HEADER_TEXTBTN`?

**Comment by Gymnasiast** [comment]
Or just `WWT_TABLE_HEADER`.

**Comment by Gymnasiast** [comment]
Looks good to me. Needs testing and squashing.

**Comment by AaronVanGeffen** [comment]
@Gymnasiast I'm thinking squashing the removal commits for `WWT_4`, `WWT_5`, `WWT_11`, `WWT_18` together, as they're all fairly small. Are we on the same page?

**Comment by AaronVanGeffen** [comment]
Squashed the aforementioned commits together.

**Pull request merged**
