### PR TITLE
Replace 20XX with 2022

### PR DESCRIPTION
**Pull request by 733737**
Replace all 20XX headers with 2022

### CODE REVIEW

**Comment by 733737** [comment]
ok, sorry I missed those, gimme a few minutes

**Comment by James103** [comment]
There are also [17 headers](https://github.com/OpenRCT2/OpenRCT2/search?q=2014-2018) that say `Copyright (c) 2014-2018 OpenRCT2 developers`.

**Comment by ocalhoun6** [comment]
Technically, shouldn't we only change the copyright dates on files that have been modified within that time period? If a file hasn't been modified since 2018, then it would be appropriate to have a "2014-2018" date range on it.

Or are we considering the entire codebase to be a single 'work', so that any edit to any file will update the copyright date of the entire project?

**Comment by 733737** [comment]
duncanspumpkin asked me to do this

**Comment by duncanspumpkin** [comment]
> Technically, shouldn't we only change the copyright dates on files that have been modified within that time period? If a file hasn't been modified since 2018, then it would be appropriate to have a "2014-2018" date range on it.
> 
> Or are we considering the entire codebase to be a single 'work', so that any edit to any file will update the copyright date of the entire project?

Nobody ever remembers to update them when they work on them and it's really all one work.

**Comment by 733737** [comment]
it is ready to merge btw, I want to leave other changes to any annotations for separate PRs (hopefully not too many PRs, maybe one or even none if I can't find anything worth changing)

**Review by duncanspumpkin — APPROVED** [review]

**Pull request merged**
