### PR TITLE
Refactor openrct2-ui/input/ files

### PR DESCRIPTION
**Pull request by SijmenSchoon**
**Warning: Massive PR**

I spent the last two weeks on refactoring the files inside openrct2-ui/input/ and some files around that that caught my eye.

I tried to make everything easier to read by splitting the big MouseInput.cpp and Input.cpp files into smaller files, and by splitting up the massive functions inside of them, which makes them easier to test in the future.

I tried to test everything as thoroughly as I can, but of course some bugs could have slipped through, in the form of a regression or similar.

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
It looks like Xcode 9.3 doesn't provide `std::optional` yet... This is unfortunate.

**Comment by SijmenSchoon** [comment]
This might work for Xcode 9.3. If it doesn't, I'll work around it.

**Comment by AaronVanGeffen** [comment]
Ah, nice, it _is_ in `experimental`! I would prefer to use the non-experimental variant where possible, though. Something like:

```
#if __has_include(<optional>)
#    include <optional>
#elif __has_include(<experimental/optional>)
#    include <experimental/optional>
#else
#    error Missing <optional>
#endif
```

**Comment by SijmenSchoon** [comment]
I'm currently trying that to work around Windows builds failing, which *should* support std::optional

**Comment by AaronVanGeffen** [comment]
Apologies this has gone without review for nearly month, but it's quite a bit to check… We'll hopefully catch up soon!

**Comment by AaronVanGeffen** [comment]
#8611 introduces a compatibility file for `std::optional`. I think we should rebase on top of that when merged.

**Comment by Gymnasiast** [comment]
What has happened to this PR was very unfortunate. A list:

- It came at a time when we were doing a lot of refactors ourselves.
- The commit history wasn't really atomic: one very big commit and several small ones. That makes it hard to see what happened and what the motivations were.
- It has been left open without anything happening too long.

Now, we should have done some things better. Especially point 3 (leaving PRs open without a clear indication) is a weak point of the project in general. We can only apologise for that.

Since it's not in a mergable state and unlikely to be, I will close this. I would still love to a refactoring in this area, so I hope this hasn't deterred you.

**Pull request closed without merging**
