### PR TITLE
Add a new cheat to disable queue length limits

### PR DESCRIPTION
**Pull request by csm10495**
Tested locally, appears to work as expected. See attached video for example:

https://user-images.githubusercontent.com/5749838/159603552-2d8eec93-7fe2-40fe-a2af-5f9ced41501f.mp4

### CODE REVIEW

**Comment by csm10495** [comment]
One thing that's odd is it seems like somewhere something is using an int16 instead of a uint16: 
image

Should that be the case? Can a queue have negative people in line?

Probably not a required thing to fix for this PR itself... but if someone has an idea, i'd be happy to try some things out.

**Comment by Broxzier** [comment]
I don't think this should be part of the game for a couple reasons. This new cheat will be useful only to a small part of the player base; for the rest it'll only clutter up the cheats window. Secondly, queues allowing 1000 guests already are not very functional. Guests will be queuing for so long that the happiness will drop (and if they can enter quickly anyway, the ride is so short that it doesn't increase happiness much either).

Instead of making this a cheat, I think removing the arbitrary limit of 1000 guests is a better change. Since extremely long queues are already bad design, allowing even more guests to queue won't have much of an impact.

**Comment by IntelOrca** [comment]
Might also be a good idea to change `QueueLength` to be an `int32` and fix that string overflow.

**Comment by csm10495** [comment]
I thought it made more sense to be a cheat to not further diverge from the behavior of the original game. 

I can change it to just remove the original limit though if we don't mind the divergence.

@IntelOrca why a larger signed int instead of unsigned?

**Comment by IntelOrca** [comment]
@csm10495 unsigned is fine

**Comment by duncanspumpkin** [comment]
I don't think this should be changed. Its already silly to have >1000 peeps in a queue and its a good upper cap for people who don't realise how bad this is for the park. This just makes the game harder for beginners.

**Comment by Gymnasiast** [comment]
> I don't think this should be part of the game for a couple reasons. This new cheat will be useful only to a small part of the player base; for the rest it'll only clutter up the cheats window. Secondly, queues allowing 1000 guests already are not very functional. Guests will be queuing for so long that the happiness will drop (and if they can enter quickly anyway, the ride is so short that it doesn't increase happiness much either).
> 
> Instead of making this a cheat, I think removing the arbitrary limit of 1000 guests is a better change. Since extremely long queues are already bad design, allowing even more guests to queue won't have much of an impact.

That _might_ lead to unintended consequences, in that guests will currently stop heading for a ride if it has 1000 people in the queue. Scrapping the mechanic might change their behaviour in subtle, unforeseen ways. I can’t tell how big a problem this is, if any.

**Comment by csm10495** [comment]
Is there a policy for new cheats? It seems like there are already several cheats that some folks may not use or find useful. The usefulness is in the eyes of the user. For me this made a whole other type of challenge in seeing how long a queue I could get without having guests leave. 

The queue actually works well also as a place to hold guests to minimize some overcrowding. (With entertainers to keep them from getting upset). I'm sure that isn't the intent of queues, but this cheat let me do that to add a whole other dynamic to managing my (huge) park. After all cheats, let us do things the original game didn't intend for.

If the consensus is to just remove the 1000 cap in general, that's fine to me as well.

**Comment by ocalhoun6** [comment]
Personally, I think it makes a lot of sense to increase/remove this limit since the NSF is already removing/increasing so many other limits.

I could see it being _very_ useful for things like trying to get as many guests in the park as possible with a limited number of rides, especially given the NSF's greatly increased guest cap.

And having it available as a cheat is a good compromise that would prevent it from hurting new players who don't understand the downsides of ultra-long queues. By the time a player is experienced enough to be experimenting with this cheat, they're hopefully also experienced enough to know the problems involved in long queues. (And if not, then hopefully the lesson they'd learn from it is, "Wow, I had a lot of problems when I turned on those cheats. Maybe I shouldn't do that.")

**Comment by csm10495** [comment]
@IntelOrca found the reason for the negative/overflow: image

This number is a COMMA16 which is interpreted as signed... Maybe there needs to be a UCOMMA16 that does commas but interprets as unsigned?

**Comment by Broxzier** [comment]
What about changing it to Comma32? That should be big enough.

**Comment by csm10495** [comment]
Great idea! Works like a charm: 
image

Updated rb to use Comma32 instead of Comma16 for this string in all translations too.

**Comment by tupaschoal** [comment]
@csm10495 we don't change any language files in this repo, other than en-GB. Every other language is done in the OpenRCT2/Localisation .
If you do it here it will be automatically overwritten when the Localisation repo is synced next time

**Comment by csm10495** [comment]
Thanks @tupaschoal , didn't know that. I've pushed a change to just change en-GB.

**Review by Gymnasiast — APPROVED** [review]

**Review by tupaschoal — COMMENTED** [review]
I think this could use a changelog entry. Not sure if we advertise cheats there, but I don't see why not.

**Comment by csm10495** [comment]
Added a changelog entry. @Gymnasiast @tupaschoal please check again. Thanks!

**Comment by Broxzier** [comment]
I don't think this should've been merged, as first mentioned [here](https://github.com/OpenRCT2/OpenRCT2/pull/16855#issuecomment-1076052849) and discussed in the team chat. An alternative way to make new players know long queues are bad design, while simultaneously removing the arbitrary limit of 1000 guests, is to show a warning when guests are complaining.

**Comment by csm10495** [comment]
I think I disagree with the logic against the cheat. We already have some cheats that could be considered clutter or not useful to the bulk of players: I mean we have a cheat to spawn ducks. 

Ultimately if someone wants to refactor to remove the cap and add a warning and then drop the cheat I think that's fine, but until then it doesn't do any harm.

**Comment by Broxzier** [comment]
> I think I disagree with the logic against the cheat. We already have some cheats that could be considered clutter or not useful to the bulk of players: I mean we have a cheat to spawn ducks.

I agree that cheats like those are indeed not useful and should be moved to plug-ins, now that that is possible.

> Ultimately if someone wants to refactor to remove the cap and add a warning and then drop the cheat I think that's fine, but until then it doesn't do any harm.

That's exactly what I am already working on, I guess I should've clarified here earlier.

**Comment by Gymnasiast** [comment]
> I don't think this should've been merged, as first mentioned [here](https://github.com/OpenRCT2/OpenRCT2/pull/16855#issuecomment-1076052849) and discussed in the team chat. An alternative way to make new players know long queues are bad design, while simultaneously removing the arbitrary limit of 1000 guests, is to show a warning when guests are complaining.

As a team member, you can close PRs you think are unfit for the game. Additionally, there is the "Request changes" feature. Since you used neither and I approved the PR 5 days ago, you had ample time to prevent the PR from being merged. That would also have been fairer on @csm10495 ’s part.

**Pull request merged**
