### PR TITLE
Make seatsInPairs default to true

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by IntelOrca** [comment]
I don't think I emitted the property for when num_seats = 1. So it should probably only set it to true if it is > 1.

**Comment by Gymnasiast** [comment]
I'm not sure it was a particularly good idea to leave out so many properties. Anyway, I have amended my commit.

**Comment by IntelOrca** [comment]
Fixes #7393?

**Comment by Gymnasiast** [comment]
> Fixes #7393?

Possibly. I didn't get a crash when I played OpenRCT2 yesterday, even though I did notice the bug when boarding a vehicle.

**Pull request merged**
