### PR TITLE
Ride Window refactor

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Porting the final window to a class.
Not quite finished

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
This is now ready for review. I've not applied a load of the style changes that need done will be in a follow on PR as otherwise its a pain to review.

**Review by ZehMatt — APPROVED** [review]
I went over each tab and tested all the functionality and everything looks good. I haven't looked at the code too deeply but its nearly impossible to properly review that, if there is anything odd we can change that afterwards at least everything works as intended.

**Comment by Broxzier** [comment]
I'd like to give this a spin too tonight before this gets merged.

**Review by Broxzier — APPROVED** [review]
Tested it with a couple parks, tried every different mode and cheat I could think of, and found no issues.

**Comment by ZehMatt** [comment]
Legacy Window System be gone!

**Pull request merged**
