### PR TITLE
mention additional changes to original game

### PR DESCRIPTION
**Pull request by e-foley**
Add to the changelog miscellaneous fixes to the original game that had been overlooked.

### CODE REVIEW

**Comment by PFCKrutonium** [comment]
Parks created with the Scenario Editor in OpenRCT2 now select the correct default colors for workers.

**Comment by Gymnasiast** [comment]
That was not an original bug.

**Comment by IntelOrca** [comment]
Providing the staff colours were broken in 0.0.2 - we can just say fix, but not original bug.

**Comment by e-foley** [comment]
Whoops, I thought I had seen that bug in the original game, but you are correct.  Thanks.

I've made the other changes proposed here as well.

**Comment by Gymnasiast** [comment]
Considering how recently the staff colour bug was reported, I doubt it was in 0.0.2.

**Comment by duncanspumpkin** [comment]
@Gymnasiast this was meant to go into the pre-release not develop.

**Pull request merged**
