### PR TITLE
Fix #5375 Use mask for fetching large scenery id, fix picking banner elements

### LINKED ISSUE #5375: scenery picker doesn't pick large scenery objects
**OS:** Windows 10
**Version:** 0.0.7
**Commit/Build:** 8243501

The new scenery picker function doesn't pick the scenery when using on a large scenery entry that occupies multiple tiles, only the first tile element of a large scenery entry seems to pick it correctly.

**Steps to reproduce:**
1. Place any large scenery object in a park (Giant pumpking in Crazy Castle for example)
2. Use the scenery picker on the object (on one of the tiles it does work)

### PR DESCRIPTION
**Pull request by Broxzier**

### CODE REVIEW

**Comment by rwjuk** [comment]
Beat me to it, was just looking at #5375! :stuck_out_tongue_closed_eyes:

**Comment by Broxzier** [comment]
When working on the fix I noticed that picking banners didn't work either, so I included a fix for those in this PR as well.

@rwjuk Oh :p

**Comment by rwjuk** [comment]
@Broxzier Haha no worries, I'd done little more than poked about and realised what needed doing :)

**Comment by Margen67** [comment]
What about footpath scenery?

**Comment by Broxzier** [comment]
@Margen67 Picking benches, bins and lamps seems to work fine.

**Comment by Gymnasiast** [comment]
LGTM codewise. I haven't tested it yet.

**Comment by rwjuk** [comment]
FWIW, I've tested this, and it works.

**Pull request merged**
