### PR TITLE
Fix #5009: Rating overflow bug (with cheating)

### LINKED ISSUE #5009: Rating overflow bug (with cheating)
**OS:** Windows 10
**Version:** 0.0.6
**Commit/Build:** 73d1c6a

I doubt that this rating bug should be fixed even though this is occured by using many cheats, but I report it anyway.
Ratings overflow in a certain condition as you can see in the screenshot below.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Make a very long distance rollercoaster with power launched mode, maximum speed(922km/h). (chain all tracks if you can)
2. Check "Allow arbitrary ride type change" cheat.
3. Change the rollercoaster's type into Launched Freefall
4. Excitement rate returns over hundred, and others return negative rating with wrong rating strings

**Dump file**

**Screenshots / Video:**
image

**Save game:**
[12.zip](https://github.com/OpenRCT2/OpenRCT2/files/691305/12.zip)

### PR DESCRIPTION
**Pull request by IntelOrca**

### CODE REVIEW

**Comment by janisozaur** [comment]
Fixes #5009 (somehow GitHub doesn't link things if you only mention them in the title of a PR).

**Comment by Gymnasiast** [comment]
Could you rebase this?

**Comment by Gymnasiast** [comment]
Looks good to me. Could you bump the network version?

**Comment by IntelOrca** [comment]
I don't know if it there are any regressions. I was going to set up automated testing but I needed park with every ride type.

**Comment by IntelOrca** [comment]
Just tested this over the top of `test/ride-ratings` and the test still passed. So that should be enough confidence for this to be merged now.

**Pull request merged**
