### PR TITLE
README: Add Julius to similar projects

### PR DESCRIPTION
**Pull request by devnoname120**

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
The selection of similar projects is rather arbitrary, but I think the row is already quite wide enough as-is. I don't think we should extend it.

Not meant at the detriment of the Julius project, of course.

**Comment by Gymnasiast** [comment]
Indeed. We had a similar request lately.

**Comment by janisozaur** [comment]
Maybe we should have a catch-all case that links to https://osgameclones.com and https://en.m.wikipedia.org/wiki/List_of_open-source_video_games ?

**Comment by devnoname120** [comment]
I understand. I find osgameclones a bit hard to navigate as it doesn't properly distinguish high quality projects with a full reimplementation such as Julius from half-done and buggy implementations.

**Comment by Gymnasiast** [comment]
I suppose we could take a third way and have a page on the wiki, listing only the better-quality examples. Though that in itself in hard to define, and could lead to a big list that everyone just piles stuff onto.

**Pull request closed without merging**
