### PR TITLE
Sequence 0.0.5

### PR DESCRIPTION
**Pull request by spacek531**
The new title sequence for 0.0.5. I didn't have the park I was making ready in time, so I used one of maian_sos's. That park will probably be featured in 0.0.6.

### CODE REVIEW

**Comment by marijnvdwerf** [comment]
@IntelOrca Shouldn't this be in https://github.com/OpenRCT2/title-sequences? (Assuming #2408 will be followed)

**Comment by IntelOrca** [comment]
yes

**Comment by IntelOrca** [comment]
@spacek531 could you please create a new pull request to https://github.com/OpenRCT2/title-sequences instead as we want to move the title sequences out of this repository.

Thanks.

**Comment by IntelOrca** [comment]
https://github.com/OpenRCT2/title-sequences/commit/9878fbf629a545748f1ce52abc6f3bfeba1cf0ee

**Pull request closed without merging**
