### PR TITLE
Refactor memory operations 3

### PR DESCRIPTION
**Pull request by IntelOrca**
Removing Memory::Allocate will take a lot more time and multiple PRs. So I have decided to just do `Memory::Set/Copy/Move` for now.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Where's "Refactor memory operations 2"? ;-)

**Comment by IntelOrca** [comment]
In progress, that is doing `Memory::Allocate`.

**Comment by marijnvdwerf** [comment]
This broke the game on macOS. It's now getting an `EXC_BAD_ACCESS` on `chunkReader.ReadChunk(&_s6.tile_elements, sizeof(_s6.tile_elements));` [https://github.com/OpenRCT2/OpenRCT2/blob/9a102182750ba2859312b9298f3f6c148b7ab8ab/src/openrct2/rct2/S6Importer.cpp#L159]

**Comment by IntelOrca** [comment]
@marijnvdwerf I am unable to reproduce this on Windows or Linux.

**Comment by marijnvdwerf** [comment]
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x1123a4000)
    frame #0: 0x00007fffbc52eec9 libsystem_platform.dylib`_platform_memmove$VARIANT$Haswell + 41
  * frame #1: 0x000000010062483c OpenRCT2`SawyerChunkReader::ReadChunk(void*, unsigned long) [inlined] std::__1::enable_if<(is_same<std::__1::remove_const<unsigned char const>::type, unsigned char>::value) && (is_trivially_copy_assignable<unsigned char>::value), unsigned char*>::type std::__1::__copy<unsigned char const, unsigned char>(__first="", __last="", __result="") at algorithm:1722
    frame #2: 0x00000001006247fc OpenRCT2`SawyerChunkReader::ReadChunk(void*, unsigned long) [inlined] unsigned char* std::__1::copy<unsigned char const*, unsigned char*>(__first="", __last="", __result="") at algorithm:1731
    frame #3: 0x00000001006247b4 OpenRCT2`SawyerChunkReader::ReadChunk(void*, unsigned long) [inlined] std::__1::enable_if<__is_random_access_iterator<unsigned char const*>::value, unsigned char*>::type std::__1::copy_n<unsigned char const*, unsigned long, unsigned char*>(__first="", __orig_n=1572864, __result="") at algorithm:1834
    frame #4: 0x0000000100624775 OpenRCT2`SawyerChunkReader::ReadChunk(this=0x00007fff5fbfed38, dst=0x0000000111e9bef8, length=1572864) at SawyerChunkReader.cpp:118
    frame #5: 0x000000010065d56f OpenRCT2`S6Importer::LoadFromStream(this=0x0000000111e99000, stream=0x00007fff5fbfee28, isScenario=true, skipObjectCheck=false, path="") at S6Importer.cpp:159
    frame #6: 0x000000010065bd51 OpenRCT2`S6Importer::LoadScenario(this=0x0000000111e99000, path="/Users/Marijn/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/steamapps/content/app_285330/depot_285331/Scenarios/Six Flags Magic Mountain.SC6", skipObjectCheck=false) at S6Importer.cpp:108
    frame #7: 0x000000010065d078 OpenRCT2`S6Importer::Load(this=0x0000000111e99000, path="/Users/Marijn/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/steamapps/content/app_285330/depot_285331/Scenarios/Six Flags Magic Mountain.SC6") at S6Importer.cpp:85
    frame #8: 0x000000010078fc62 OpenRCT2`TitleSequencePlayer::LoadParkFromFile(this=0x000060800026ee40, path="/Users/Marijn/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS/steamapps/content/app_285330/depot_285331/Scenarios/Six Flags Magic Mountain.SC6") at TitleSequencePlayer.cpp:418
    frame #9: 0x000000010078f3c6 OpenRCT2`TitleSequencePlayer::ExecuteCommand(this=0x000060800026ee40, command=0x0000000102155400) at TitleSequencePlayer.cpp:269
    frame #10: 0x000000010078eda5 OpenRCT2`TitleSequencePlayer::Update(this=0x000060800026ee40) at TitleSequencePlayer.cpp:143
    frame #11: 0x0000000100769af8 OpenRCT2`TitleScreen::TryLoadSequence(this=0x00006000002234e0, loadPreview=false) at TitleScreen.cpp:251
    frame #12: 0x0000000100769f50 OpenRCT2`TitleScreen::TitleInitialise(this=0x00006000002234e0) at TitleScreen.cpp:238
    frame #13: 0x0000000100769da7 OpenRCT2`TitleScreen::Load(this=0x00006000002234e0) at TitleScreen.cpp:132
    frame #14: 0x000000010076a11e OpenRCT2`title_load() at TitleScreen.cpp:286
    frame #15: 0x00000001001f1d1e OpenRCT2`OpenRCT2::Context::Launch(this=0x00006000000a4440) at Context.cpp:536
    frame #16: 0x00000001001ef5e9 OpenRCT2`OpenRCT2::Context::RunOpenRCT2(this=0x00006000000a4440, argc=1, argv=0x00007fff5fbff668) at Context.cpp:170
    frame #17: 0x00000001000dcedc OpenRCT2`main(argc=1, argv=0x00007fff5fbff668) at Ui.cpp:60
    frame #18: 0x00007fffbc31c235 libdyld.dylib`start + 1
    frame #19: 0x00007fffbc31c235 libdyld.dylib`start + 1
```

**Comment by IntelOrca** [comment]
@marijnvdwerf thanks, I spotted the mistake now. Could you try `develop` again?

**Comment by marijnvdwerf** [comment]
Yep, works again!

**Pull request merged**
