### PR TITLE
Improve network messages and logging

### PR DESCRIPTION
**Pull request by IntelOrca**

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
This fixes #11484 for me. Supersedes #12469 as well then.

**Comment by IntelOrca** [comment]
@AaronVanGeffen was your terminal reset back to the correct mode after exiting OpenRCT2?

**Comment by AaronVanGeffen** [comment]
@IntelOrca Yes, and the REPL works great as well. ^D^D quits the game nicely, too.

**Review by ZehMatt — APPROVED** [review]

**Comment by Gymnasiast** [comment]
Nice job fixing the console!

**Comment by IntelOrca** [comment]
@Gymnasiast We need to ensure that we always use `Console::*` instead of `printf` otherwise it will not insert the required `\r\n`.

**Pull request merged**
