### PR TITLE
B&m track addings 

### PR DESCRIPTION
**Pull request by Realsteel89**
Add BM Sprites:
grafik

Zero G Roll
Giant Corkscrew
Medium Loop
Large Curve Slope and Banked one

need work on Sprite lightning
need work on right offset
need work on Support hights

### CODE REVIEW

**Comment by karst** [comment]
Lighting definitely needs work, and the pieces don't line quite up yet, exciting to see tho! I see you somewhat fixed the polygonic issue?

**Comment by Realsteel89** [comment]
Yes that's why I marked it as draft

**Comment by karst** [comment]
Any progress on this?

**Comment by Realsteel89** [comment]
> Any progress on this?

not at the time sorry h2h kills all my time but after this this needs full update of code

**Comment by Gymnasiast** [comment]
@Realsteel89 I was planning to close this PR and merge https://github.com/OpenRCT2/OpenRCT2/pull/23051 instead. I hope that is okay with you.

**Comment by Realsteel89** [comment]
Yes it is because mix got closer to that result I wanted a bit in an diffrent way but better

**Pull request closed without merging**
