### PR TITLE
G2: Get rid of all possible instances of `SPR_G2_CHAR_BEGIN +`

### PR DESCRIPTION
**Pull request by karst**
The goal of this PR is to get rid of all possible instances of `SPR_G2_CHAR_BEGIN + `  this will allow me to reorganize G2 in a future PR to have everything together under their own tabs like Icons, Characters,  Track Additions and New Track types, this will allow future additions to be more organized in this file as well as G2 is becoming a mess as is.

It seems that the junior coaster has 15 unused sprites in g2 (that aren't listed in `sprites.h`, or anywhere for that matter), (flat to steep diagonal (including lift chain)). I do not know if there's plans for these so I have left these in for now. I can easily just put these with the rest of the Jr RC pieces and skip over these.

### CODE REVIEW

**Comment by karst** [comment]
When graphics asset packs are added and it needs to replace something in G2 and G2 gets changed, something new gets added, we are gonna need a versioning system so G2 doesn't get messed up if someone is making a graphics pack for the game.

**Comment by IntelOrca** [comment]
@karst we are not sure yet how this is going to work. Everything will eventually end up in object files, so there will not be a g1 or g2.

**Comment by karst** [comment]
I've got the next part for this one lined up. So once this is merged I can immediately create a new PR for doing the sorting (on which I am gonna need feedback to see if there's a more logical order or if it's correct the way I did it).

**Comment by karst** [comment]
Rebased for the jr coaster extra track removal.

**Review by Gymnasiast — APPROVED** [review]

**Pull request merged**
