### PR TITLE
Use string_view as value

### PR DESCRIPTION
**Pull request by skdltmxn**
A minor fix to use `std::string_view` instead of `const std::string_view&`

### CODE REVIEW

**Review by Gymnasiast — APPROVED** [review]

**Review by ZehMatt — CHANGES_REQUESTED** [review]
I would actually prefer to keep the const on the arguments, normally you don't want to accidentally overwrite your inputs.

**Comment by skdltmxn** [comment]
Sure thing.
Modified to const values

**Review by ZehMatt — APPROVED** [review]
Thanks

**Comment by tupaschoal** [comment]
> I would actually prefer to keep the const on the arguments, normally you don't want to accidentally overwrite your inputs.

`const std::string_view` isn't really very useful, is it?

**Comment by ZehMatt** [comment]
> > I would actually prefer to keep the const on the arguments, normally you don't want to accidentally overwrite your inputs.
> 
> `const std::string_view` isn't really very useful, is it?

https://godbolt.org/z/b9WMT3noP Like I said, "prevents from overwriting the function input"

**Comment by Gymnasiast** [comment]
How interesting, I always assumed that string_view implied immutability.

**Comment by Broxzier** [comment]
string_view does not allow editing of the source stting, but if its non-const there's nothing preventing you from assigning another string_view valu with another buffer to it.

FWIW, const arguments should only be declared in the source file, not in the header, since it's an implementation detail, the signature of the function doesn't even change. It boils down to self-documentation.

**Comment by ZehMatt** [comment]
Just think of string_view as this if you were to implement it yourself:
```cpp
class string_view
{
    const char* _ptr;
    const char* _end;
public:
   string_view(const std::string& str) : _ptr(str.c_str()), _end(str.c_str() + str.size()) {}
   string_view(const char* str) : _ptr(str), _end(str + strlen(str)) {}
}
```
Thats all it holds, so reading is fine, writing aint. Re-assigning the view just points to different memory

**Comment by tupaschoal** [comment]
> > > I would actually prefer to keep the const on the arguments, normally you don't want to accidentally overwrite your inputs.
> > 
> > 
> > `const std::string_view` isn't really very useful, is it?
> 
> [godbolt.org/z/b9WMT3noP](https://godbolt.org/z/b9WMT3noP) Like I said, "prevents from overwriting the function input"

Ah sure, I mean, it has no chance of messing up with whatever was sent to it unless it's passed as a reference, but I get your point.

**Pull request merged**
