### PR TITLE
Fix #21731: previously-invisible 'alt' rides now visible

### LINKED ISSUE #21731: Rides previously set to the ride type "Unknown Ride (38)" now display as Multi-dimension coaster track
### Operating System

Windows 11 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.10-13-ga38039f (a38039f on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error, This is a development issue

### Describe the issue

Issue is currently present in recent develop builds of 0.4.10 but not present in release.

Using the park Otter's Magic Kingdom (https://www.nedesigns.com/park/5910/otters-magic-kingdom/) as an example:
image

Additionally, there are now also two instances of Multi-dimension Coaster in the ride type list:
image

### Steps to reproduce

1. Open a map that has previously used the ride type "Unknown Ride (38)" to make a ride invisible.
2. Ride now displays as multi-dimension coaster track rather than invisible, which breaks any park that previously used this ride type to make a ride invisible.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by Gymnasiast** [comment]
That was already reported in https://github.com/OpenRCT2/OpenRCT2/issues/21731 , and fixed in this PR. Please don’t comment on PRs if you haven’t read the accompanying issue, or actually tested the code.

**Comment by Manticore-007** [comment]
https://github.com/OpenRCT2/OpenRCT2/issues/21731#issuecomment-2041551015

> Could you test this build: https://github.com/OpenRCT2/OpenRCT2/actions/runs/8583762332/artifacts/1391095720 to check if that works for you? If possible, can you also test a few other instances that use Unknown Ride (38)?

The park mentioned in #21744 looks okay now.
Another park where I know the issue occured, is also okay with the build above.

edit: I also checked Otter's Magic Kingdom, and I don't see the multi-dimension track anymore.

**Comment by Xtreme97-RCT** [comment]
Copying my comment from the bug:
Yeah, this build has fixed the issue with the park I was testing. Have also tested with another map that I know had the issue (Gladsheim from H2H9: https://www.nedesigns.com/park/5338/gladsheim/) and that also works as expected now with the track being invisible. Thank you!

**Review by Basssiiie — APPROVED** [review]
LGTM

Looking at the code, it may still change the way ratings were calculated and which chainlift sound is used, compared to the old alt modes, but that may be acceptable?

**Comment by Gymnasiast** [comment]
"Unknown ride"s aren’t guaranteed to be stable, or even remain unused. They should never have been exposed in the first place, but sadly were and now here we go :')

The best thing to do is use the proper ride type and just make the pieces invisible. Easy enough to plugin for, should one not already exist.

**Review by janisozaur — APPROVED** [review]

**Review by janisozaur — DISMISSED** [review]
Looks like network version to me

**Comment by Basssiiie** [comment]
Some people on the DKMP Discord are mentioning the new RTD's have a different track height offset, causing some vehicles to clip into objects under the invisible track.

Would it be possible to have them have the same track height as before?

**Comment by Gymnasiast** [comment]
The old Alt RTD were essentially copies of their non-alt versions, just with no drawing code. I’ll normalise them to their non-ALT versions with invisibility, that should preserve behaviour _and_ clean up things - I don’t want 4 dummy RTD’s, 1 is already too many.

**Comment by Gymnasiast** [comment]
@Basssiiie I’ll need a little bit more time for the alternative solution, and it’s probably going to take longer than one release cycle. So I decided to reinstate the ‘alt’ RTDs for now, with a view of removing them later on. Can you re-test, including the height offset?

**Review by janisozaur — APPROVED** [review]

**Pull request merged**
