### PR TITLE
Add a button to the map generator window in the Map window, replaces #4073

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by Wirlie** [comment]
And my commit? :( okay, I think it doesn't matter...

**Comment by Nubbie** [comment]
Yeah thought that too, it disappeared :c

**Comment by Gymnasiast** [comment]
I squashed the nine commits into one.

**Comment by Wirlie** [comment]
:'c never mind, I didn't do much :P

**Comment by Nubbie** [comment]
@Wirlie Except you fixed the whole thing xox

**Comment by mrtnptrs** [comment]
Just give @Wirlie some credits when you push this to the development branch :P

**Comment by Nubbie** [comment]
@gymnasiast Why is this WIP btw? :s

**Comment by Gymnasiast** [comment]
Because I didn't know if your PR was ready, and I haven't yet tested it myself.

**Comment by Nubbie** [comment]
@Gymnasiast Seems to be working as it should, the only problem is that Wirlie isnt credited

**Pull request merged**
