### PR TITLE
Refactor memory operations 1

### PR DESCRIPTION
**Pull request by IntelOrca**
This removes 'most' of the `Memory::` calls in libopenrct2ui with a few other refactorings as well. I converted most of them to `std::vector` and a few to `std::unique_ptr` and replaced `Memory::Copy` and `Memory::Set` with `std::copy_n` and `std::fill_n` respectively.

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Could someone test this manually on XCode? With Travis out, we'll have to test it another way.

**Comment by rwjuk** [comment]
@AaronVanGeffen I can do this tonight.

**Comment by rwjuk** [comment]
@IntelOrca Confirmed that this builds and runs on macOS.

**Comment by Gymnasiast** [comment]
Most stuff appears to work correctly (audio, saving track design, loading various scenarios).

However, in OpenGL no text appears. It does appear when using `develop`. (Ubuntu 17.10 AMD64, GCC 7.2)

**Comment by AaronVanGeffen** [comment]
> However, in OpenGL no text appears in the interface. It does appear when using develop. (Ubuntu 17.10 AMD64, GCC 7.2)

Just double-checking, but TTF not rendering on OpenGL is a known issue, #3868. The sprite font should work fine, however, of course.

**Comment by Gymnasiast** [comment]
I am talking about the sprite font and it does work correctly on `develop`.

**Comment by IntelOrca** [comment]
@Gymnasiast sorry about that, it should be fixed now.

**Comment by Gymnasiast** [comment]
I can confirm it now works with OpenGL as well.

AFAIC, this is good to go, with the caveat that I haven't looked a lot at the code, since I don't know a terrible lot about memory allocations and vectors. But testing it has revealed no other bugs.

**Pull request merged**
