### PR TITLE
 Respect POSIX path separators on Windows

### PR DESCRIPTION
**Pull request by vector-of-bool**
> This renames the PATH_SEPARATOR macro to PREFERRED_PATH_SEPARATOR. Path parsing functions will also look for "/" as a path separator, even on Windows.

I note that there is quite a lot a duplicate path parsing functionality. Perhaps it would be good to consolidate it into a single path utility?

I needed this to get the Windows build to work with CMake, which calls `sprite build` with `/` as the path separator. It otherwise crashes or fails with cryptic errors and bad filenames flying all over the place.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
This does not seem to really clean up things, if I'm brutally honest.
In addition to the changes you mentioned, you also included a VS change this seems unrelated to me.

> I note that there is quite a lot a duplicate path parsing functionality.

Well, there is likely to be some gains in cleaning it up. Though I'm not sure what's the best cause of action here.

> I needed this to get the Windows build to work with CMake, which calls sprite build with / as the path separator. It otherwise crashes or fails with cryptic errors and bad filenames flying all over the place.

Hm, so you're saying that OpenRCT2 does not handle forward slashes as path separators correctly on Windows, right? That _is_ a problem. But in that case, leaving PATH_SEPARATOR as it is and defining PATH_SEPARATOR_ALT as '/' might be a better idea. Or perhaps even a function: platform_char_is_path_separator() that checks for both.

**Comment by vector-of-bool** [comment]
re: VS change: That's because I use `std::max`. Windows headers do evil and `#define min` and `#define max`, which causes `std::min/max` to be a syntax error. Defining `NOMINMAX` suppresses these macro definitions.

I notice that there's an actual class dedicated to path manipulation, and I'd rather do a refactor to a central util that really gets filesystem paths right. I wanted to keep my first PR simple, but I could go whole-hog and change up path handling if necessary.

I also realized that my usage of `std::max` is *wrong*, so this PR needs some changes before it can be merged.

**Comment by IntelOrca** [comment]
Was the renaming of `PATH_SEPARATOR` necessary? It kind of hides the real intent of this PR.

**Comment by Gymnasiast** [comment]
> Was the renaming of PATH_SEPARATOR necessary?

I don't think so, even though I understand the reason.

> Other than that, I think it looks okay.

Are you sure about the 'NOMINMAX' stuff? It's not related and IMO, should not be in _this_ PR, even if there is a good reason to include it.

**Comment by vector-of-bool** [comment]
@Gymnasiast, I just renamed it just for clarity's sake. I also removed the `NOMINMAX` change, since it wasn't necessary if I just use `Math::Max`. I can also revert the rename of `PATH_SEPARATOR` if that's preferred.

**Comment by IntelOrca** [comment]
@vector-of-bool I don't mind about the name change, it just made it hard to see the actual change.

**Comment by Gymnasiast** [comment]
@vector-of-bool I have a preference for PATH_SEPARATOR, since it makes for easier reading.

**Comment by vector-of-bool** [comment]
I'll revert the `PATH_SEPARATOR` rename. I think I'll rebuild this PR with just the important changes, just so the git history is clean. Or we could opt for a squash merge once it's fixed?

**Comment by Gymnasiast** [comment]
@vector-of-bool We can just do a squash merge, as long as the diff itself is clean, it's ok.

**Comment by vector-of-bool** [comment]
Much cleaner!

**Comment by janisozaur** [comment]
Based on @IntelOrca's opinion here: https://github.com/OpenRCT2/OpenRCT2/pull/6356#issuecomment-334240332 I'm going to merge this.

**Pull request merged**
