### PR TITLE
Fix additional park boundary errors in Japanese Coastal Reclaim

### PR DESCRIPTION
**Pull request by HtotheTML**
four tiles have missing/mismatched rights on this cliff. All land tiles on the clifftop are construction rights save for these three, and all land tiles at the base of the cliff are owned land except for this singular tile. This PR remedies that issue.
cliff1
cliff2

### CODE REVIEW

**Comment by HtotheTML** [comment]
These additional changes are not in the PR at present, but I'm wondering if these spots should be changed as well:

The opposite clifftop has a peculiar spot of owned land where a lot of guests are gathered upon opening the map. the rest of that landing is exclusively construction rights for sale. I'm wondering if it should be changed to land for sale in that specific spot.
square1
square2

At the cove over by the bullet train coaster lies the only set of water-bound tiles that are set to construction rights, rather than owned land/land for sale like the rest of the map. This is a suggestion to change those odd construction rights to owned land.
cove1
cove2

**Review by tupaschoal — APPROVED** [review]

**Comment by tupaschoal** [comment]
> The opposite clifftop has a peculiar spot of owned land where a lot of guests are gathered upon opening the map. the rest of that landing is exclusively construction rights for sale. I'm wondering if it should be changed to land for sale in that specific spot.

Couldn't spot from the picture where it would be

> At the cove over by the bullet train coaster lies the only set of water-bound tiles that are set to construction rights, rather than owned land/land for sale like the rest of the map. This is a suggestion to change those odd construction rights to owned land.

I'd keep these as construction rights, make sense for the owned land to be right up until the coaster, it's a lot of owned land to add and it is very subjective.

**Comment by HtotheTML** [comment]
> > The opposite clifftop has a peculiar spot of owned land where a lot of guests are gathered upon opening the map. the rest of that landing is exclusively construction rights for sale. I'm wondering if it should be changed to land for sale in that specific spot.
> 
> Couldn't spot from the picture where it would be

The guests are gathered inside the square of owned land on the path loop. I have them hidden for visibility.

**Comment by tupaschoal** [comment]
> > Couldn't spot from the picture where it would be
> 
> The guests are gathered inside the square of owned land on the path loop. I have them hidden for visibility.

I still don't see the difference, can you maybe highlight what would change on a screenshot?

**Comment by HtotheTML** [comment]
> > > Couldn't spot from the picture where it would be
> > 
> > 
> > The guests are gathered inside the square of owned land on the path loop. I have them hidden for visibility.
> 
> I still don't see the difference, can you maybe highlight what would change on a screenshot?

Oh, gotcha. Misinterpreted what you meant.
So here's what that area normally looks like after you buy all the available land and rights:
image
and here's what it would look like after the suggested change:
image
Presently the owned land up there serves little purpose.

**Comment by HtotheTML** [comment]
The only other suggestion I'd posit for that cove area is to keep the rocky section as construction rights, as that would still line up with how the map is laid out, but otherwise I'd still be fine with leaving it as-is.
image
here's what it presently looks like after buying all land:
image
and here's what it'd look like after:
image

**Comment by tupaschoal** [comment]
> Presently the owned land up there serves little purpose.

So this would turn into only construction rights?
image

**Comment by tupaschoal** [comment]
> The only other suggestion I'd posit for that cove area is to keep the rocky section as construction rights, as that would still line up with how the map is laid out, but otherwise I'd still be fine with leaving it as-is.

I think this is fine

**Comment by HtotheTML** [comment]
> So this would turn into only construction rights?

Right now it's just the loop of owned land + buyable construction rights everywhere else on that landing. I'm suggesting it all be turned into the loop of owned land + buyable land.

**Comment by HtotheTML** [comment]
> I think this is fine

Shall I go ahead and get that added in?

**Comment by tupaschoal** [comment]
Yeah, I guess both suggestions

**Comment by HtotheTML** [comment]
Here's those additional changes once more, all together:
Cove, before:
image
Cove, after:
image

Landing, before:
image
Landing, after:
image

**Review by Gymnasiast — APPROVED** [review]

**Review by tupaschoal — APPROVED** [review]

**Pull request merged**
