### PR TITLE
Rename vehicle_is_boat_on_water to better reflect the actual functionality

### PR DESCRIPTION
**Pull request by manuelVo**
New name is vehicle_boat_is_location_blocked

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
What that makes no sense. The check is checking to see if the boat is on water.

**Comment by duncanspumpkin** [comment]
You could perhaps rename it to is location valid water. But it's not checking if location is blocked. It's checking that there is water at the same height as the boat.

**Comment by Gymnasiast** [comment]
Er no, it doesn't. It returns true if the water is not at the same level or when something is in the way.

**Comment by IntelOrca** [comment]
`vehicle_is_boat_on_water` is wrong because it doesn't use the x,y coordinates of the vehicle. So it is indeed checking if the given position is blocked, blocked meaning is not water. I think it should be instead called `vehicle_boat_is_location_water` or `vehicle_boat_is_location_is_accessible`

**Comment by Gymnasiast** [comment]
As I said, it returns true when the location is **not** accessible. Naming it `vehicle_boat_is_location_is_accessible` does require inverting that, as well as any calls to it.

**Comment by manuelVo** [comment]
How about `vehicle_boat_is_location_inaccessible`?

**Comment by Gymnasiast** [comment]
Just wait until Duncan and Ted have figured out _why_ you called it blocked.

**Comment by Broxzier** [comment]
Another suggestion: since only the vehicle's Z is used inside the function, but the X and Y are passed as coordinates, why not refactor it to pass the full location instead? `bool vehicle_boat_can_float_at(LocationXYZ16 location);` (inverting the function)

Adding comments to make the function clearer would be of help.

**Comment by duncanspumpkin** [comment]
I don't think can float at makes much sense. We don't use float as the name for anything else. Go with vehicle_boat_is_location_accessible and invert it so that accessible locations return true. I also like broxiers suggestion of passing the z value as a param.

**Comment by Gymnasiast** [comment]
@Broxzier LocationXYZ16 is deprecated. Pass CoordsXYZ.

**Comment by manuelVo** [comment]
I updated the PR as suggested. I split the change into two commits because it felt to me like those changes are independent of each other (however I can squash if you prefer).

**Comment by manuelVo** [comment]
As a side note: As part of this refactoring I moved the `>> 3` out of this function, which I'm not too fond about...

**Comment by duncanspumpkin** [comment]
@manuelVo looks good. One minor change though you could pass x and y >> 5 then we are only passing tile coordinates instead of big coordinates. At some point we need to go through the code base and sort out the mess that is big and small coordinates.

**Comment by manuelVo** [comment]
Updated as suggested. Note: I didn't yet get to test this change yet, as the machine I'm currently using doesn't have the assets installed. However du tue a visual inspection the two code paths look similar to me.

**Pull request merged**
