### PR TITLE
Update GoogleTest version

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by janisozaur** [comment]
@IntelOrca can you check why msvc complains?

**Comment by janisozaur** [comment]
The stuff MSVC complains about: https://github.com/google/googletest/blob/e2239ee6043f73722e7aa812a459f54a28552929/googletest/include/gtest/gtest-param-test.h#L499-L502

**Comment by janisozaur** [comment]
This will conflict with https://github.com/OpenRCT2/OpenRCT2/pull/15914, that other PR is more important IMO, so this one would probably get scrubbed. The issue with MSVC's miscompilation remains, as the older macro is deprecated and will get removed.

**Comment by janisozaur** [comment]
This should fix the issue with MSVC now and is a first step towards updating CI images.

**Comment by janisozaur** [comment]
All green now. @IntelOrca can you review?

**Comment by IntelOrca** [comment]
Is there any reason to still support downloading gtest in cmake? A system install should suffice?

**Comment by janisozaur** [comment]
This will be done in next PR - #15914. I wanted to update it first

**Review by IntelOrca — APPROVED** [review]

**Pull request merged**
