### PR TITLE
Part of #15589: Make numpad enter able to confirm input

### PR DESCRIPTION
**Pull request by beam41**
Found code that responsible, share on discord and then I'm quickly fix it here because look like the issues assisnee is not working on issues anymore.

original code doesn't use enum make it little hard to find. So I change `'\r'` to `SDLK_RETURN` too.

### CODE REVIEW

**Comment by rik-smeets** [comment]
I think this should be resolved when mapping the `SDL_Event` to the InputEvent:

https://github.com/OpenRCT2/OpenRCT2/blob/e0a25f3d229c4085fb5c813d7063bc8a13949fc5/src/openrct2-ui/UiContext.cpp#L970-L994

In this bit of code, I think the numpad enter key press should be converted to a 'regular' enter key press so we don't have to do it everywhere else in the code where the InputEvent might be handled.

Do note that we cannot remove it at this place below, since this piece of code uses the original `SDL_Event` instead of the mapped InputEvent:
https://github.com/OpenRCT2/OpenRCT2/blob/e0a25f3d229c4085fb5c813d7063bc8a13949fc5/src/openrct2-ui/TextComposition.cpp#L107-L114
That might be a worthwhile refactoring too, but necessary to do right now in my opinion.

**Comment by beam41** [comment]
@rik-smeets Can I add like this. I can't add to switch case below, I don't know what that `Handle dead keys` if statement does. but it not for regular key?

```cpp
    InputEvent GetInputEventFromSDLEvent(const SDL_Event& e)
    {
        InputEvent ie;
        ie.DeviceKind = InputDeviceKind::Keyboard;
        ie.Modifiers = e.key.keysym.mod;
        ie.Button = e.key.keysym.sym;

        if (e.key.keysym.scancode == SDL_SCANCODE_KP_ENTER)
        {
            ie.Button = '\r';
            return ie;
        }

        // Handle dead keys
        if (ie.Button == (SDLK_SCANCODE_MASK | 0))
        {
            switch (e.key.keysym.scancode)
            {
                case SDL_SCANCODE_APOSTROPHE:
                    ie.Button = '\'';
                    break;
                case SDL_SCANCODE_GRAVE:
                    ie.Button = '`';
                    break;
                default:
                    break;
            }
        }

        return ie;
    }
```

**Comment by rik-smeets** [comment]
I'd expect the if statement to be:
```c++
        if (ie.Button == SDLK_KP_ENTER)
        {
            ie.Button = SDLK_RETURN;
        }
        else if ( // the other if statement from here
```

In `/windows/TextInput.cpp`, you then no longer have to check for `SDLK_KP_ENTER`.

Please note I didn't test any of this, I'm just writing this off the top of my head - please test it yourself too.

**Comment by beam41** [comment]
Turn out I can't really mapped in `GetInputEventFromSDLEvent` because it breaks shortcut. Numpad enter will always read as Return.

**Comment by 733737** [comment]
is it possible to remove num lock requirement on the dialogs where you use numpad?

**Comment by rik-smeets** [comment]
> Turn out I can't really mapped in `GetInputEventFromSDLEvent` because it breaks shortcut. Numpad enter will always read as Return.

Of course, I didn't think users would want to have different shortcuts for both keys, but that's entirely possible. My keyboard doesn't even have a num pad so I was using a virtual keyboard to test this to begin with. Sorry for making you do some extra work here.

But in this case, a specific solution at this point in code seems reasonable. I tested it with my virtual keyboard and it seems to work fine too.

**Comment by beam41** [comment]
@733737 it read text input from sdl directly but we might able to override it.

**Comment by Gymnasiast** [comment]
@rik-smeets I’m not sure if mapping keypad Enter to regular Return is a good idea. It means that people cannot set it as a shortcut key, for example. So checking for both in the function that @beam41 modified might be the best way to go after all.

**Comment by rik-smeets** [comment]
> 

I agree. I tested this PR using a virtual keyboard and it seems to work fine. Perhaps you would like to test it with a physical keyboard just to be sure?

**Comment by Gymnasiast** [comment]
I did, it works fine.

**Review by Gymnasiast — APPROVED** [review]

**Pull request merged**
