### PR TITLE
Add force commands for ratings

### LINKED ISSUE #5191: Cheat: Manually Change Ride Stats
A useful cheat, would be a way to manually change ride stats like you can in son of beast.

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Note these do not save and will reset if the rating is recalculated.

This is a console command rather than a cheat to hide it at least a bit. This is not sent over the network.
Closes #5191.

### CODE REVIEW

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/wiki/Console#available-commands

**Comment by IntelOrca** [comment]
changelog

**Comment by tcek** [comment]
This is excellent, thanks guys.

**Comment by tcek** [comment]
Don't wanna sound like a cunt but why can't we freeze the stats? They literally change within seconds.

**Comment by duncanspumpkin** [comment]
Because that would break the save format.

**Comment by Nubbie** [comment]
Which was discussed before and can be read [more about here] (comment section of issue)(https://github.com/OpenRCT2/OpenRCT2/issues/5191#issuecomment-278243663)

**Comment by tcek** [comment]
Okay, only asked.


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Pull request merged**
