### PR TITLE
Implement a dummy zip

### PR DESCRIPTION
**Pull request by janisozaur**
ping @sajattack

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Is this still necessary now @sajattack has figured this out? With zip being an important part of OpenRCT2 (for title sequences), should we really allow building without it?

**Comment by AaronVanGeffen** [comment]
To add to @Gymnasiast's comment, as mentioned on Gitter yesterday, zips are going to be even more important in the future, with the new object format likely making use of them, too.

**Comment by janisozaur** [comment]
I'm OK with this not getting merged. To address your comments: yes, we will likely depend more on zip _in the future_, but Redox port is happening now and this makes porting easier by removing one more _currently_ optional library. By the time we get such functionality, however, it is possible zip support on Redox matures. Do remember we still support unpacked title sequences, so there is really barely any functionality lost with this PR.

**Comment by Gymnasiast** [comment]
Except that our own title sequences come zipped.

**Comment by janisozaur** [comment]
They only come packaged this if you use the prepackaged versions distributed to openrct2.org. Maintainers are welcome to not zip them and I don't use title sequences at all.

**Comment by Gymnasiast** [comment]
Since sajattack managed to include libzip, and because Redox is an experimental OS anyway, I'm going to close this.

**Pull request closed without merging**
