### PR TITLE
partially fix #2181

### LINKED ISSUE #2181: Multiplayer client ride construction
Select a roller coaster and build a custom design on the client

Place down the station. On the server, this would bring you immediately into ride construction mode. For the client though, it closes out the ride construction window and brings up the overview ride window. 

While in construction mode for a roller coaster with 2 or more pieces, click the "Remove the highlighted section" button. On the server, it does what it is suppose to do. that is, remove the previous piece of the track and allows you to keep building. 

On the client, hitting that button does remove the last piece of the track, but then grey's out all the buttons not allowing you to continue working on it without right clicking the ride. 
Although to fix this on the client, hitting the "Move to previous section" then removing the track piece works just fine. It allows you to remove the current track section and lets you build after.

### PR DESCRIPTION
**Pull request by FlukiestEmperor**
Fixes the issue with deleting track pieces with the multiplayer client in #2181

### CODE REVIEW

**Comment by IntelOrca** [comment]
Rather than duplicating a load of code, put the common part in a new function.

**Comment by FlukiestEmperor** [comment]
Fixed. Any other suggestions?

**Comment by IntelOrca** [comment]
You say partially fix, what still doesn't work correctly?

**Comment by FlukiestEmperor** [comment]
Well, I originally said partially fixed because I listed 2 problems in that issue.

Although I just tested it a bit more and realized it only works on station pieces for the client. Any idea why that could be?

**Comment by IntelOrca** [comment]
I will have to investigate it.

**Comment by IntelOrca** [comment]
Hacky but works, you might want to clean it up a bit:
https://github.com/OpenRCT2/OpenRCT2/commit/800e80aeb3394e22b9585ca34b37762cf95650a2

**Comment by FlukiestEmperor** [comment]
So it's good enough then? I don't really know the best way to go about cleaning that up.

**Comment by IntelOrca** [comment]
ok, i'll merge it - these will all need cleaning up at some point. Ideally we want do kind of just pass a callback lambda into the game command routine.

**Pull request merged**
