### PR TITLE
Fix #7331: Invention list in scenario editor crashes upon removing previously-enabled ride/stall entries

### LINKED ISSUE #7331: Invention list in scenario editor crashes upon removing previously-enabled ride/stall entries
**OS:** Win7
**Version:** 0.1.2

I set up an invention list, then decided to go back and remove a few stalls and ride types I found to be superfluous. Upon going back to the invention list, the game immediately crashes, with Windows washing out the screen and giving a "openrct2.exe has stopped responding" popup (the latter of which can be seen in the below image). This *only* happens for rides and stalls; removing paths and scenery did not cause a crash.

- Reproducible in RCT2 (vanilla)? *Cannot check; no longer have disk*
- Specific to multiplayer? *No*

**Steps to reproduce:**
1. Create a basic scenario with some rides enabled
2. Set up an invention list
3. Go back and disable a few rides
4. Return to the invention list
5. Crash

### PR DESCRIPTION
**Pull request by Chaosmeister**
Clear the `gResearch`-list before populating it. This is more of a workaround to ensure, that all items in the list are valid.  
This  fixes the crash from #7331.  

`void research_remove(rct_research_item * researchItem)` seems to not work correctly, as it never really removes anything due to incorrect input-items. This should also be analyzed.

### CODE REVIEW

**Comment by Chaosmeister** [comment]
The changelog stopped at `0.1.2 (2018-03-18)`.  
Should I just add the fix above that line?

**Comment by Chaosmeister** [comment]
oh crap  I messed up and pushed to master 🤦‍♂️

**Comment by Chaosmeister** [comment]
I'll rebase it when I'm home again

**Comment by IntelOrca** [comment]
@Chaosmeister you don't need to close the PR to rebase your branch.

**Comment by Chaosmeister** [comment]
d'oh 
I'll just leave it like that until I have free time to clean this up.
sorry for the inconvenience!

**Pull request merged**
