### PR TITLE
Search tracks

### PR DESCRIPTION
**Pull request by Broxzier**
Here's some test footage: http://www.broxzier.com/files/ShareX/2017-11-23_15-55-29.mp4

I'm reusing `STR_OBJECT_SEARCH_CLEAR` from the object selection window. I wasn't sure if I should add a new string for it, or if I should rename this define to somehting more generic like `STR_SEARCH_CLEAR`.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Do we really need to put blooming search boxes in _everything_?

**Comment by Broxzier** [comment]
... could've said it in a nicely manner that you don't think it's useful. I figured it would be for people with a ton of tracks, and it's not in the way for people who don't need it.

**Comment by IntelOrca** [comment]
The search boxes are good, but there will end up being lots of duplicated code until we have some reusable UI component.

**Comment by Gymnasiast** [comment]
I just don't think it's really that useful. But it's extra interface clutter again. Plug-in stuff., AFAIC.

**Comment by rwjuk** [comment]
I agree that I personally wouldn't use a search feature for tracks - I don't think I have enough for any ride type to half fill the scrollbox, let alone want to search through.

That said, there well may be people who do have loads and would value a search feature (e.g. NE-style park creators), I don't know. As extra UI elements go, it's unobtrusive IMO.

**Comment by IntelOrca** [comment]
Its probably less likely with NE players as they will always build custom tracks. It is probably more likely with scenario players. I have dealt with bugs before and also written the improved index repository because some players had several thousand track designs.

Visual Studio has a search box in almost every tool window, it is just built into the shell. So I think it seems reasonable for us to have some common list box / table UI control which has a search bar. Perhaps an option in options to hide all the search bars (basic / advanced) mode.

**Comment by Gymnasiast** [comment]
I'm not entirely convinced, but I shan't obstruct this PR.

**Comment by Patrik356b** [comment]
@Gymnasiast
The wooden roller Coaster track list is already cluttered with the original tracks from rct1 and RCT2 before you start saving your own designs. 

But I actually agree with you. 
I'd much rather have additional options to sort the list: price, size, intensity, nausea, etc (descending/ascending)

**Comment by deurklink** [comment]
Something like this would be really useful for the "allow arbitrary ride types" cheat.

**Pull request merged**
