### PR TITLE
Move Scenery Entry structs into object files

### PR DESCRIPTION
**Pull request by duncanspumpkin**
The scenery entries are the main meta data of the scenery objects so it made no sense for them to not be part of the object file header. Next step will be removing the GetXXXEntry functions, renaming _legacy, enforcing coding style
But that will be in follow on PRs.

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
FYI for reference this will be the follow on https://github.com/duncanspumpkin/OpenRCT2/tree/objectManagerMeta

**Review by Gymnasiast — APPROVED** [review]

**Comment by cheweytoo** [comment]
This commit's github Linux AppImage build crashes on start, after a couple of notes of the intro's music are played.

Output:

```
[MDSAENT ] Error (6): Unexpectedly reached end of file.
ERROR[../src/openrct2/object/ObjectFactory.cpp:290 (CreateObjectFromLegacyFile)]: Error: Object has errors when processing object /media/storage/RCT2/Game_Files/Game_Install/ObjData/MDSAENT.DAT
[rct2.scenery_large.mdsaent] Warning (3): Adding 12 placeholders
[SSIG2   ] Error (5): Bad image table.
[SSIG2   ] Error (6): Unexpectedly reached end of file.
ERROR[../src/openrct2/object/ObjectFactory.cpp:290 (CreateObjectFromLegacyFile)]: Error: Object has errors when processing object /media/storage/RCT2/Game_Files/Game_Install/ObjData/SSIG2.DAT
[rct2.scenery_large.ssig2] Warning (3): Adding 368 placeholders
[SSIG4   ] Error (5): Bad image table.
[SSIG4   ] Error (6): Unexpectedly reached end of file.
ERROR[../src/openrct2/object/ObjectFactory.cpp:290 (CreateObjectFromLegacyFile)]: Error: Object has errors when processing object /media/storage/RCT2/Game_Files/Game_Install/ObjData/ssig4.dat
[rct2.scenery_large.ssig4] Warning (3): Adding 368 placeholders
[SCLN    ] Error (6): Unexpectedly reached end of file.
ERROR[../src/openrct2/object/ObjectFactory.cpp:290 (CreateObjectFromLegacyFile)]: Error: Object has errors when processing object /media/storage/RCT2/Game_Files/Game_Install/ObjData/SCLN.DAT
[rct2.scenery_large.scln] Warning (3): Adding 20 placeholders
[SPG     ] Error (6): Unexpectedly reached end of file.
ERROR[../src/openrct2/object/ObjectFactory.cpp:290 (CreateObjectFromLegacyFile)]: Error: Object has errors when processing object /media/storage/RCT2/Game_Files/Game_Install/ObjData/SPG.DAT
[rct2.scenery_large.spg] Warning (3): Adding 20 placeholders
[SPYR    ] Error (6): Unexpectedly reached end of file.
ERROR[../src/openrct2/object/ObjectFactory.cpp:290 (CreateObjectFromLegacyFile)]: Error: Object has errors when processing object /media/storage/RCT2/Game_Files/Game_Install/ObjData/SPYR.DAT
[rct2.scenery_large.spyr] Warning (3): Adding 148 placeholders
[SCT     ] Error (6): Unexpectedly reached end of file.
ERROR[../src/openrct2/object/ObjectFactory.cpp:290 (CreateObjectFromLegacyFile)]: Error: Object has errors when processing object /media/storage/RCT2/Game_Files/Game_Install/ObjData/SCT.DAT
[rct2.scenery_large.sct] Warning (3): Adding 8 placeholders
[SSIG3   ] Warning (5): Image table size shorter than expected.
```

One commit prior, 815d349, still works fine.

**Comment by Gymnasiast** [comment]
I have undone the merge.

**Comment by IntelOrca** [comment]
I think the crash might be due to removal of `#pragma pack(push, 1)`. When loading DAT objects, it still reads directly into the struct rather than field by field.

**Comment by duncanspumpkin** [comment]
> I think the crash might be due to removal of `#pragma pack(push, 1)`. When loading DAT objects, it still reads directly into the struct rather than field by field.

Afaik everything has been changed to read field by field.

**Comment by Gymnasiast** [comment]
Personally, I think we should cleanly separate the .DAT struct (packing it) and the entry we use in OpenRCT2 proper. Reading separate fields is something I've never been really happy with.

**Comment by IntelOrca** [comment]
@Gymnasiast it is the only way to deal with big-endian (if we were to ever get it working), unless you go post process each field afterwards.

**Comment by Gymnasiast** [comment]
I don’t care about big endianness, to be brutally honest, and I don’t think we should hamstring our code to handle it. The rest of the arguments I find more compelling.

Nevertheless, even if we do read field-by-field, I think there is a case to be made for cleanly separating DAT and OpenRCT2 structures, rather than reading into the latter directly and converting stuff on the fly. We used the same approach on importing S4 and S6, for example.

**Pull request merged**
