### PR TITLE
Refactor CMake project to name sources explicitly

### PR DESCRIPTION
**Pull request by janisozaur**
This makes CMakeLists.txt follow CMake best practices more closely and
helps with rebuilds or incremental builds.

### CODE REVIEW

**Comment by IntelOrca** [comment]
Should `CMakeLists.txt` use spaces rather than tabs to match your new ones?

**Comment by IntelOrca** [comment]
Isn't a cmake for every single sub directory recursed overkill?

**Comment by janisozaur** [comment]
I can see the ones in `ride/` getting folded, as they only provide per-category grouping into directories, not really "units" – at least until they get moved into something like `ride/paint_setup/`, but the other ones really are logical units (or we should strive for them to be such): `drawing/engines/opengl`, `paint/map_element`, `paint/sprite`. There are no other sub-subdirectories.

**Comment by Gymnasiast** [comment]
What exactly does this aim to solve?

**Comment by janisozaur** [comment]
This is a step towards more modular codebase. You should be able to switch unused components off and just don't compile them. And when one is needed, just add its subdirectory.

I will update once #4932 is in.

**Comment by IntelOrca** [comment]
@janisozaur we need to discuss how we split up the code base into components. Those subdirectories are do mirror components. They merely represent namespaces.

**Comment by IntelOrca** [comment]
This is no longer applicable with the new SDL-less work.

**Pull request closed without merging**
