### PR TITLE
Update readme to include new Fedora Copr repo

### PR DESCRIPTION
**Pull request by AbsyntheSyne**
I created a copr for the stable build of OpenRCT2(currently 0.1.2) and I'd like to have it included in the readme. Please read this over, adjust it however you see fit. Thanks :)

### CODE REVIEW

**Comment by janisozaur** [comment]
I posted some comments regarding the repository on gitter, copied here so they don't get lost:

1. in spec file you download hardcoded `v0.1.2.zip`, even though you've specified `Version` already. Why not `v%{version}.zip` and why `.zip` over `.tar.gz`?
2. `BuildRequires` list specifies no `pkgconfig`, is this implied and do all the relevant package come with it already or is `pkconfig(<package>)` required?
3. Most build services I've seen are without internet access, the logs on COPR build show the internet access is available, but we also allow pre-caching all the required files for ones that have no such access. Is this something of a concern?
4. `reimplimentation` has a typo, should be `reimplementation`
5. We ship with mime types, but you don't seem to be updating the db post install, is this happening automatically?

**Comment by AbsyntheSyne** [comment]
Hi!

This is one of my first spec files so I'm not 100% sure how everything works fully. 

1. I'll make these changes as soon as I can. 
2. I must've forgot that.. Sorry! 
3. Earlier builds of mine required internet access to download some extra bits. I'm not sure if it's still like that. I'll do a test build without internet though! 
4. Thanks for letting me know. I'll be sure to edit that. 
5. Oh! I thought openrct2.org was it. My bad! 

Thank you for helping me learn more about rpm packaging and spec files. I very much appreciate it!

**Comment by janisozaur** [comment]
How feasible is it to use COPR as a way for providing current `develop` builds to Fedora users?

In case of Launchpad, Canonical's build service targetting Ubuntu, it has automated git import (running several times a day or so) and uses a simple "recipe" to build using our debian control files, which basically tell the helpers there to use cmake.

This project is very much live and having such current builds is useful.

**Comment by AbsyntheSyne** [comment]
I'm not sure. I'm new to copr and rpm packaging in general. I guess copr is *similar* in some ways to ppa's. All it is is just building the package using a spec file or an srpm, as if you were to do it on your machine. That's about all I know.

**Pull request merged**
