### PR TITLE
[Plugin] Add APIs for editing title sequences

### PR DESCRIPTION
**Pull request by IntelOrca**
So that the title sequence editor can move into a plugin.

### CODE REVIEW

**Comment by spacek531** [comment]
The new editor plugin will be available from the main menu? and will it close when loading title sequence parks?

**Comment by IntelOrca** [comment]
@spacek531 no, it will only be available in-game from the map menu due to limitations with plugin framework

**Comment by Gymnasiast** [comment]
> @spacek531 no, it will only be available in-game from the map menu due to limitations with plugin framework. Once in-game, it has the same behaviour as before.

I would like that to be possible, though, before the built-in title sequence editor gets removed.

But since this PR merely adds the necessary APIs, I merged it anyway.

**Comment by IntelOrca** [comment]
Is there a specific reason why it is important that this still be available on the title screen?

**Comment by spacek531** [comment]
The title sequence editor opening from the options menu puts the title sequence selector and title sequence editor in the same place. Also means when I start up the game I can go straight into editing without having to decide on an arbitrary park to open just so I can close it again.

**Comment by IntelOrca** [comment]
> The title sequence editor opening from the options menu puts the title sequence selector and title sequence editor in the same place.

Can you elaborate on this? Is this something that can be done when not on the title screen?

> Also means when I start up the game I can go straight into editing without having to decide on an arbitrary park to open just so I can close it again.

Is it okay if it is just a menu item under the toolbox and takes you to a blank map, with the editor open?

**Comment by spacek531** [comment]
image
This is what I mean by "the same place" - all the title sequence stuff is in the same groupbox, a central area for all title sequence-related actions.

**Pull request merged**
