### PR TITLE
Prevent invalid memory access in "Build new ride" window

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by IntelOrca** [comment]
What is this? I already fixed the issue with the research tab.

**Comment by janisozaur** [comment]
That's another one

**Comment by janisozaur** [comment]
`_windowNewRideListItems` might not be terminated properly

**Comment by IntelOrca** [comment]
@janisozaur have you actually been able to hit this assertion?

**Comment by janisozaur** [comment]
There is no assertion here, but yes, it gets triggered.

**Comment by IntelOrca** [comment]
How do you get it to trigger?

**Comment by janisozaur** [comment]
@IntelOrca apply following patch on top of this PR:

```diff
diff --git a/src/windows/new_ride.c b/src/windows/new_ride.c
index 856391158..9c03306c9 100644
--- a/src/windows/new_ride.c
+++ b/src/windows/new_ride.c
@@ -672,9 +672,11 @@ static void window_new_ride_scrollgetsize(rct_window *w, int scrollIndex, int *w
 
        int count = 0;
        const ride_list_item * listEnd = _windowNewRideListItems + countof(_windowNewRideListItems);
-       while (listItem < listEnd && (listItem->type != 255 || listItem->entry_index != 255)) {
+
+       while (listItem->type != 255 || listItem->entry_index != 255) {
                count++;
                listItem++;
+               assert(listItem < listEnd);
        }
        *height = ((count + 4) / 5) * 116;
 }
```
then open any park, click "build new ride"

**Comment by IntelOrca** [comment]
This is the correct fix:
```
diff --git a/src/windows/new_ride.c b/src/windows/new_ride.c
index 8563911..b52cc3e 100644
--- a/src/windows/new_ride.c
+++ b/src/windows/new_ride.c
@@ -441,8 +441,8 @@ rct_window *window_new_ride_open()
                (1 << WIDX_TAB_7) |
                (1 << 14) |
                (1 << 15);
-       window_init_scroll_widgets(w);
        window_new_ride_populate_list();
+       window_init_scroll_widgets(w);

        w->frame_no = 0;
        w->new_ride.selected_ride_id = -1;
```

**Comment by janisozaur** [comment]
Merged as  b1ab5c9

**Pull request closed without merging**
