### PR TITLE
Add script for formatting code in place

### PR DESCRIPTION
**Pull request by pRizz**

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Is there any advantage of this over `git clang-format`?

**Comment by pRizz** [comment]
@AaronVanGeffen Interesting 😅I was not aware of that. I wish this was documented somewhere when I was doing other pull requests. How about I just document this?

**Comment by AaronVanGeffen** [comment]
Yes, it should really be on the wiki, if it isn't already. The [Coding Style](https://github.com/OpenRCT2/OpenRCT2/wiki/Coding-Style) lemma ought to reflect this at least.

**Comment by tupaschoal** [comment]
A note on CONTRIBUTING.md sounds like a good addition as well.

**Comment by pRizz** [comment]
I just added this to the Coding Style page:
https://github.com/OpenRCT2/OpenRCT2/wiki/Coding-Style/ff1f60e0eedde158ca065967e7d6026f9230d58f

Do we also want it in the CONTRIBUTING.md ?

**Pull request closed without merging**
