### PR TITLE
Enable extra track pieces on vertical drop coaster

### PR DESCRIPTION
**Pull request by X123M3-256**
This allows the use of all inversions on the vertical drop coaster, and makes them available in the ride construction window. It also enables pieces specific to the vertical drop coaster on the Twister coaster, but does not show them in the construction window. This was done because I couldn't figure out how to make both the small and large steep to flat pieces available at the same time, so I made it possible to switch to twister track to build that piece and then switch back.

I'm not sure if this is really ready to merge in this state - it's not backward compatible but doesn't make that obvious if you don't know what elements this coaster normally has,  and the default trains don't have sprites for corkscrews or barrel rolls, so this should probably be an option rather than something enabled all the time. However, I wasn't sure how best to implement that, because RideTypePossibleTrackConfigurations is constant and can't be modified at runtime. Perhaps it would be better if these track pieces were enabled but not shown in the construction window - or maybe this isn't really a good idea at all, I don't know. I thought I'd submit a PR anyway.

### CODE REVIEW

**Comment by IntelOrca** [comment]
RideTypePossibleTrackConfigurations can have all pieces that work and are possible. The vehicle objects themselves override this anyway to only those pieces that ride / vehicle supports.

The drawing is okay for now, but when we come to implement the drawing of the B&M style track they can all ultimately share the same calls.

**Comment by X123M3-256** [comment]
> The vehicle objects themselves override this anyway to only those pieces that ride / vehicle supports.

That's true, but a lot of the default vehicles just enable every piece. The vehicle specific thing only seems to come into play when two vehicles share a track but have different pieces enabled - the vertical drop coaster just enables everything, so this patch allows you to build corkscrews and barrel rolls with it, which the stock train doesn't have all the sprites for (large half loops and quarter loops are fine though).

**Comment by jensj12** [comment]
Since an option to manually change track types is planned (IIRC), there's no need to do this.
For the time being this would work (enable the flat to steep pieces on the twister coaster too), but I wouldn't like the construction window having things enabled I normally can't use.

**Comment by X123M3-256** [comment]
The option to change track types is already implemented, and has been for a while now, but it does not replace this. You can't change track types on a piece by piece basis, you have to change the whole ride at once,  you change the track type to one that doesn't have all the elements you've used, your game will crash with a segmentation fault.

The problem is that if you use twister track, you don't get the holding brake or small steep to flat piece, which are really essential for a DM, but the vertical drop track is extremely limited, so you have to use a track merge to get everything you need.

I find this awkward because the sprites for those elements already exist so a merge should not be needed. What this does is add extra elements to the DM track so that realistic layouts can be built much more easily without the need of a merge, like how steep slopes were added to Junior track. I didn't think this should be a cheat because the ride has those elements IRL.

The problem is that I haven't quite managed to make this work seamlessly because the default vertical drop coaster train doesn't have sprites for the pieces I added. This may not be a problem but it's a bit awkward and if you aren't familiar with what trains have what sprites it might look like a  bug.

I could make the feature optional, or leave the track pieces enabled but not put them in the ride construction window, or disable the pieces that the stock trains don't have sprites for, leaving large half loops and quarter loops (which in itself would be a major improvement).

The way this is implemented now is a bit of a hack, and I'd not be surprised if it doesn't get merged for that reason. When the track paint is all done a cleaner implementation would be possible.

**Comment by Gymnasiast** [comment]
Doesn't the Steel Twister already contain flat-to-60-degree pieces, the kind that take multiple tiles? Also, I'm not sure whether adding the corkscrews to the Vertical Coaster is a good idea or not. Still, real-life vertical drop coasters _can_ contain them - Baron 1898 in the Efteling is an example.

Don't close this yet please, as I would definitely want this in some form.

**Comment by IntelOrca** [comment]
I think @jensj12 is referring to my idea of being able to change the track type as you are building the track. But that was when we had our own map format and could store the track style on each element so you didn't need to use multiple rides to do it.

You should probably try to find a way of not allowing pieces that aren't allowed normally to be used. Perhaps an alternative available track piece table.

**Comment by Gymnasiast** [comment]
That is a good idea. However, I think that pieces that work 100% should be added in the regular table - an example could be the holding-brake-before-drop from the vertical coaster. The alternative table could be used for pieces for which most trains lack suitable sprites, for example.

**Comment by X123M3-256** [comment]
I had another idea - make the ride construction window never show pieces for which the current train does not have sprites, even if they are enabled for the object and for the track type. This would never hide a piece that would have been allowed in vanilla, but it might end up hiding pieces that would otherwise be available if the "Show vehicles from other track types" cheat has been used. It also would not solve the problem that this still would not make clear to the user that their design won't work in vanilla - perhaps a warning could be displayed in the ride construction window when such a piece is selected?

**Comment by Gymnasiast** [comment]
Not sure detecting that is easy. I prefer the 'alternative table' solution that IntelOrca proposed.

I would propose three tables:
"Default" -> As it is now
"Extended / Known to work" -> Extra pieces for which the trains have suitable sprites. I would also consider the steep slopes for the Junior RC to fall into this category (it was added to the main table in https://github.com/OpenRCT2/OpenRCT2/commit/c487e1278b436dbfc88b659d2f9dd6ac580dab74 by accident)
"Experimental" -> Many of your pieces.

Choosing between the three modes could be done via a dropdown.

**Comment by X123M3-256** [comment]
Detecting what track pieces a ride has sprites for is easy - it's just a matter of mapping each track piece to the required sprite flags and doing some bitwise operations. I already do something similar with my ride generator to determine which track pieces should be enabled for the ride.

An alternative table could work too though. Where do you think the dropdown should go? In the ride construction window would be one possibility, but I don't think this is something that could easily be made to work per-ride so it probably shouldn't go in a ride-specific window. How about in the options menu? Perhaps we could have an "enable extra track pieces" option that enables this and the Junior pieces.

Also, steep slopes for the Junior coaster doesn't belong in the category of pieces for which the existing trains have suitable sprites - the stock Junior trains don't have steep slope sprites.

**Comment by Gymnasiast** [comment]
Well, if you can make autodetection work, that would be fine as well. Of course, the 'Experimental' category would still need an alternative table, but this way you only need two (one for Default, one for Experimental). An advantage of your approach is that it might catch more suitable track pieces than hard coding.

IMO, you should put the dropdown in the Options menu, as it isn't really a cheat.
The reason I'd like the steep pieces for Junior RC in the 'Known to work' category is because they were in RCT1 and the glitches are very minor. On the other hand, Ted will most likely agree with you on this, so it's probably best to put them into 'Experimental'. (I can live with that. ;-))

**Comment by X123M3-256** [comment]
What I'm thinking of doing is making it so that any track pieces that the currently selected vehicle does not have sprites for are hidden by default. Then have an option to enable/disable extra track pieces (those not in vanilla), and then a cheat to remove all limits (so you can build every piece the game supports, regardless of available sprites or the pieces that are enabled in the .DAT).

It's a bit different to the dropdown you propose but I think it makes sense - the pieces that are fully supported should be an option because the only reason not to use them is for compatability with vanilla, and I think if pieces that will glitch are to be enabled then it makes sense to also enable pieces that are disabled in the DAT file (such as inversions on hyper coasters), and that ought to be a cheat. What do you think?

**Comment by pizza2004** [comment]
Are we eventually going to make it possible for the game to read the proper junior coaster sprites out of the RCT1 files?

**Comment by X123M3-256** [comment]
RCT1 did not have object files so there are none to read - everything was hardcoded. If you are talking about extracting the junior coaster sprites from csg1.dat and turning them into an RCT2 object file, that is already possible and always has been. I did this for the mini suspended coaster and I think a couple of other RCT1 rides were converted this way. However, RCT1 only has 16 frame rotations while RCT2 uses 32 frames, so you'll have to double up the sprites.

**Comment by pizza2004** [comment]
I mean just, if we provide the RCT1 files OpenRCT2 automatically reads the sprites it needs out of them so that it can properly fully support playing RCT1 saves and scenarios.

**Comment by X123M3-256** [comment]
The missing sprites isn't the only issue preventing RCT1 files being fully supported though - the SV6 format doesn't support some of the features RCT1 had, like booster tracks.

I think you should probably make a seperate issue for this discussion though, as it's not really related to this PR.

**Comment by Gymnasiast** [comment]
I tested it. The problem is that the vertical roller coaster just enables all track pieces and thus the extra pieces will show up, support or not.

I suggest the following: leave the drawing hack in but remove the additions to the enabled pieces table. We'll look at that one later.

**Comment by X123M3-256** [comment]
I know the vertical drop coaster enables every piece (as do many others) - that's why I proposed only showing pieces the current vehicle actually shows sprites for. I just never got around to implementing it - I'll have another look tomorrow.

**Comment by Gymnasiast** [comment]
@X123M3-256  What is the status of this?

**Comment by X123M3-256** [comment]
Nothing much has changed since the PR was submitted. It's still something I've been meaning to finish, but I haven't got round to it as I've been doing other things. I will look into it when I have time.

**Comment by Gymnasiast** [comment]
I merged the drawing code in another PR. I'll close this one and create a separate issues for the auto-enablement of parts.

**Comment by X123M3-256** [comment]
That's odd. It does look like code I might have written, but I can't find it in any of the PRs I've submitted, and I remember there was an [issue opened for it](https://github.com/OpenRCT2/OpenRCT2/issues/4479) that I never got around to addressing. I didn't even realize this was implemented.

**Pull request closed without merging**
