### PR TITLE
Refactor LIGHTFX_LIGHT_QUALIFIER #12406

### PR DESCRIPTION
**Pull request by rpstester**
Now using strong enum (along with EnumValue)
Please let me know if you have any questions or feedback. Thanks!

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
Anytime when you do one of these refactors and you have to use the enumvalue function everywhere it suggests things should be refactored. I'd like to see a few changes to the light fx code so that it takes this new type and uses it correctly.

**Comment by rpstester** [comment]
Thank you for the feedback. I was looking at approved refactor work and saw EnumValue used over and over again.  Would you please point me in the right direction of how you would like this enum class used properly, or give me an example to study?

**Comment by tupaschoal** [comment]
There are some cases where we'll need to use `EnumValue`, such as indexing into an array or generic window/tab code. Function parameters, member variables, normal variables and other stuff can instead be converted to use the actual enum type instead, making the code safer, clearer and with fewer casts/conversions

**Comment by rpstester** [comment]
This one looks a little beyond my skill level.  Someone else can take it on :)

**Pull request closed without merging**
