### PR TITLE
Adding a MapGen button on the map + Giving MapGen an ID and Tip

### PR DESCRIPTION
**Pull request by Nubbie**
As some people are missing out on this feature which is extremely useful, it should be available as a 'first thing you see' kind of thing when you enter the map editor (as the next step opens up the 'map' window)
Have noticed some people didn't know about this feature, why not remind them

### **BUG:** 

- ~~Is visible everywhere which is a problem (Isn't flagged to be restricted to just scenery editor)~~
- ~~Gray 'tool-tip' (probs. from choosing that button type)~~

### Note: 

- Does not collide with any other function and is harmless
- Fits all languages

mapgeneration

### CODE REVIEW

**Comment by Wirlie** [comment]
For the gray tooltip you just need to add `{SMALLFONT}{BLACK}`

**Comment by Nubbie** [comment]
@Wirlie oh ye, I forgot about that, thanks! :D:

**Comment by SijmenSchoon** [comment]
Wow, I thought of adding such a feature to this game, just to discover it already exists :P

**Comment by Wirlie** [comment]
@Nubbie, please check the PR that I made in your repository.

**Comment by Nubbie** [comment]
@Wirlie Merged your commit as it solved all the bugs, made it more attractive and made it fit all languages! Updating my photo too, thanks a bunch :D

**Comment by Wirlie** [comment]
Again, no problem xP and thanks to you

**Comment by Nubbie** [comment]
hate the github website when branches gets conflicts

**Comment by Wirlie** [comment]
I think that my solution that I've explained before (two months ago? xD) can't help to solve this.

First, you need to remove your two last commits 
(fast way: `git reset --hard cd284266cbdecabe81bee3acb1ad7dde29c8d801`,
note: cd284266cbdecabe81bee3acb1ad7dde29c8d801 is the last commit before of your two commits)

After that, you can search about how you can resolve it (not sure if http://stackoverflow.com/questions/31863429/how-do-i-resolve-conflicts-with-git can solve it).

If you have many problems then I can try to fix it via Git Shell, but I need permissions in your repository.

**Comment by janisozaur** [comment]
@Nubbie can you please amend your commits so that you remove PR numbers from your own repo? When we merge such things, GitHub registers a link to such an issue in the main repo, which is not correct.

**Comment by Nubbie** [comment]
@Wirlie Tried x and y but before I mess everything up.. I gave you permission to my fork, really kind of you if you want to help out but you dont need to :o

**Comment by Gymnasiast** [comment]
https://github.com/OpenRCT2/OpenRCT2/pull/4098 replaces this.

**Comment by Nubbie** [comment]
That was that

**Pull request closed without merging**
