### PR TITLE
Fix 11050: macOS release 0.2.5 has invalid permissions

### PR DESCRIPTION
**Pull request by IntelOrca**
Okay it still doesn't give you a unix zip as an artefact, but at least you can just take it out the dos zip wrapper.

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
This zip in a zip will most likely break the launcher, surely?

**Comment by Gymnasiast** [comment]
Good point. Though to be precise, it will _continue_ to be broken, unless we manually fix the artifact before releasing.

**Comment by AaronVanGeffen** [comment]
Right, we can manually intervene for the release... I don't agree with saying it will continue to be broken, though, as macOS 10.14 was unaffected by the bug. This is a regression for them.

**Comment by Gymnasiast** [comment]
Well, I remember the launcher not being able to extract the ZIP *at all*. Not sure if that was ever fixed for the 0.2.5 release.

**Pull request merged**
