### PR TITLE
Allow setting ownership of map edges

### PR DESCRIPTION
**Pull request by Gymnasiast**
A feature offered by trainers and frequently used by sandbox players. Tested it in both scenario editor and in-game, and doesn't seem to have strange side-effects.

### CODE REVIEW

**Comment by IntelOrca** [comment]
Making the map smaller when the owned land is on the edge causes issues with the fence. The fence needs re-calculating.

image

**Comment by IntelOrca** [comment]
The following error also gets triggered a lot:
```
ERROR[..\src\world\map.c:168 (map_get_first_element_at)]: Trying to access element outside of range
```

**Comment by Gymnasiast** [comment]
I solved the second error but I have no idea why the first error occurs.

**Comment by IntelOrca** [comment]
What error did you fix?

**Comment by Gymnasiast** [comment]
I fixed the following error from being triggered:
`ERROR[..\src\world\map.c:168 (map_get_first_element_at)]: Trying to access element outside of range`

**Comment by IntelOrca** [comment]
Last thing to fix is the fence re-calculating when you lower map size then.

**Comment by Gymnasiast** [comment]
That's the problem, I can't find what causes it.

**Comment by IntelOrca** [comment]
@duncanspumpkin would you be able to investigate this?

**Comment by Gymnasiast** [comment]
Broxzier seems to have solved the remaining problem. I'll have to test and rebase, but then it can be merged. :)

**Comment by Gymnasiast** [comment]
OK, rebased it and tested. @Broxzier has indeed solved the remaining issue, so this is now ready for merging. :-)

**Comment by Gymnasiast** [comment]
Ok, it's rebased now.

**Pull request merged**
