### PR TITLE
OpenGL: Use Geometry Shader instead of Instancing [Testing]

### PR DESCRIPTION
**Pull request by LRFLEW**
I made this, not because I expect it to be merged (at least for now), but to open a discussion and get some people to test (and get the CI builds).

One problem we faced very early on was figuring out how to draw a bunch of rectangles with flat/uniform information without making a draw call for each. Duplicating the data 4+ times for each vertex was found to be impractical, so another solution was used. The current code uses Instancing. This allows for vertex data to be uploaded per-primitive, while still drawing the rectangles normally. However, there's another option that we didn't really consider (as far as I know).

Geometry Shaders are shaders that run between the vertex shader and rasterizer. Geometry Shaders work on the primitive level (point, line, or triangle), and can produce a (variable) number of primates (of the same or different type). A geometry shader can be used to convert a single point to a rectangle. This also allows us to upload the "uniform" data once.

So how do they differ? Well, Geometry Shaders were added in OpenGL 3.0, whereas Instancing was added in OpenGL 3.3. Since Instancing is the only 3.3 feature we use, Geometry Shaders *could* allow us to decrease our minimum version required (however important that may or may not be). As for performance, the information online is rather... inconsistent. [This article](http://www.geeks3d.com/20140929/test-particle-rendering-point-sprites-vs-geometry-instancing-based-billboards/) suggests that GS is better with Nvidia cards, but worse for AMD, whereas [this article](http://www.joshbarczak.com/blog/?p=667) suggests only Intel GPUs benefit from GS. I figured the only way to find out for sure would be to test it.

Which brings me to this PR. This converts the Instancing for DrawImage to a Geometry Shader. I want to get people to compare this to the Instancing version to see the performance difference. I don't expect this to be merged itself, but the results of this test will influence how my transparency rewrite will work.

This is based off of #6298 instead of the latest develop because a) It allows me to get useful macOS numbers, b) It will produce results more relevant for the changes I'm making, and c) it prevents tests from comparing against a moving target. If you are willing to test this for me, please comment what OS and GPU you're using, and provide the framerate/performance for both #6298 and this using OpenGL and Unlocked FPS. You can use something like the title screen or a save game to make an equivalent comparison. If you're on Windows (64 bit), then you can use [this 6298 build](https://ci.appveyor.com/api/buildjobs/nec8nt8msfdqwj9d/artifacts/artifacts%2Fopenrct2-portable-release-x64-90d0a8b.zip) and [this 6465 build](https://ci.appveyor.com/api/buildjobs/rv52qglbfgi9rkwy/artifacts/artifacts%2Fopenrct2-portable-release-x64-4b422b7.zip).

### CODE REVIEW

**Comment by LRFLEW** [comment]
macOS 10.12.6
Nvidia GT 750M

I used the Six Flags Over Texas scenario to test. I got somewhere between 5fps to 0fps difference with this. This gave me ~115fps, with some occasional dips. #6298 wavered between ~110fps and ~115fps, and seemed to be much less consistent than this version. I'd say this one is slightly better, but the difference was subtle.

**Comment by PFCKrutonium** [comment]
Windows 10 Build 16229.15

Intel HD 4600 experienced no change in FPS, gain or loss.
nVidia 950M went from 30 FPS in 6298 to 45-50 (fluctuating) in 6465.

I was testing with [This Park](https://github.com/OpenRCT2/OpenRCT2/files/1384414/Krutoniums.Maze.Park.zip).

**Comment by ethanhs** [comment]
Windows 10 build 16278.1000

GTX 1080 Went from 32-40 6298 to 34-45 in 6465. Testing same park that @PFCKrutonium used.

**Comment by spacek531** [comment]
Running Windows 10 with an AMD A10 7700M APU, running SFOT looking at the Texas Giant station, OpenGL, Uncap FPS, expanded windowed mode (so just shy of 1366x720):
4b422b7 runs at a consistent 33-38 FPS with no windows open. With 'About RCT2' open, I get 16 FPS.
90d0a8b runs at a consistent 34-37 FPS with now windows open. With 'About RCT2' open, I get 16 FPS.

**Comment by LRFLEW** [comment]
Ok, so far, this is looking slightly favorable to Geometry Shaders. There's no real advantage or disadvantage for the Intel or AMD cards tested, but the Nvidia ones showed a minor improvement. Since it makes the code look a little better (no switch statement in the VS), and it doesn't seem to hurt anyone, I'll work with GS for my upcoming rework. If you see a decrease in performance with this, PLEASE post it, as it could change how I approach the rework.

**Comment by IntelOrca** [comment]
I thought geometry shaders would be out of the question if we were trying to target a old OpenGL version.

**Comment by LRFLEW** [comment]
@IntelOrca We're currently using Instancing, which requires a newer version of OpenGL than Geometry Shaders. Plus, we already require OpenGL 3+ for integers in shaders, so Geometry Shaders will be present anyways.

**Comment by LRFLEW** [comment]
Closing this because I don't think it's worth adding. Basically, the existing method would be easier to port to a future OpenGL ES renderer, and I think keeping the two GL renderers in-sync is a good idea. Plus, Geometry Shaders weren't *really* designed for this sort of thing.

**Pull request closed without merging**
