### PR TITLE
Create getters for GetBaseHeight()/GetClearanceHeight()

### PR DESCRIPTION
**Pull request by Gymnasiast**
This creates getters for base height and clearance height. The value returned is a "sprite z", not a "tile z". This makes moving everything to Coords easier.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Merge note: use squash and make sure the commit title is correct.

**Comment by IntelOrca** [comment]
Only concern I have is that a dev might think oh, there is a getter for base_height, lets use that... oh wait this isn't just returning base_height. GetBaseZ might help differentiate since we don't have different typedefs for sprite Z and tile Z.

**Comment by Gymnasiast** [comment]
> Only concern I have is that a dev might think oh, there is a getter for base_height, lets use that... oh wait this isn't just returning base_height. GetBaseZ might help differentiate since we don't have different typedefs for sprite Z and tile Z.

I see this as a stepping stone in moving everything towards `Coords`.

Having said that, I will change the function names to GetBaseZ/GetClearanceZ.

**Comment by duncanspumpkin** [comment]
Is that the consistent naming we should be heading towards: `baseZ` means big Z and `baseHeight` means small Z?

**Pull request merged**
