### PR TITLE
Don't store multithreading option permanently.

### PR DESCRIPTION
**Pull request by ZehMatt**
I need to look at all the bugs that have been submitted and come up with better automated tests regarding languages like Korean that use TTF rendering.

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Rather than making it non-persistent without UI indication, I think we should just default to off instead. Is that an option at this stage, or do you actively want to reset existing config files?

**Comment by janisozaur** [comment]
Maybe make it false if using TTF only? Defaulting to off is not really an option once it's stored in config file.

**Comment by ZehMatt** [comment]
There might be more unrelated bugs, so I still want to give people a chance to turn it on when they go to the options just not keep it saved so it would crash next start.

**Comment by janisozaur** [comment]
It's worth taking Aaron's suggestion and at least modify the text of the option with mention of the issue # on GitHub.

**Comment by AaronVanGeffen** [comment]
Or change the option's name so all users are reset to false once, as @IntelOrca suggested in chat.

**Comment by ZehMatt** [comment]
Good idea actually

**Comment by ZehMatt** [comment]
Renamed the option to "multi_threading" and extended the tooltip string since the option window doesn't have much space to put it on the label.

**Comment by duncanspumpkin** [comment]
We change it back to the original. Eventually the old entry will go away.

**Comment by janisozaur** [comment]
Do we remove options not consumed by our structures? Now that I think of it, it should work regardless of we do or not. In case we do, we will set it to true and if we don't, it would have already been true, unless user manually turned it off. Looks fine to me then

**Comment by IntelOrca** [comment]
@janisozaur we do, it re-writes the whole file.

**Pull request merged**
