### PR TITLE
Move gBankLoan and gBankLoanInterestRate to GameState_t

### PR DESCRIPTION
**Pull request by Martymoose98**
Move gBankLoan and gBankLoanInterestRate to GameState_t for https://github.com/OpenRCT2/OpenRCT2/issues/21193

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Code looks good. Branch will have to be squashed and the commit message rewritten, be we can do that on merging, especially since you’re a first-time contributor.

**Comment by Martymoose98** [comment]
Yeah I forgot to format the commit message on the subsequent commits. I think the first commit message passed but the format failed so I was anxious to fix the format check. Is there a way I could have the format checks on my fork? Additionally, I could do some other global vars if you want.

**Comment by Gymnasiast** [comment]
We use clang-format. This command should be available in `git`, like this:
```
git add -A
git clang-format
git add -A # Re-add the files that were formatted in the previous step
```

The failing commit-lint is because of your merge commit - we always rebase branches if they get out of sync with `develop`.

**Comment by Martymoose98** [comment]
I don't seem to have git clang-format. I not the greatest with git 😞.
Rebase worked however I think I did that correctly?
Also, I don't know why it's added the recent localization file changes. :/
I think I have to rebase again cause of the recent pushes to develop?

**Comment by Gymnasiast** [comment]
You would normally use `git rebase -i upstream/develop` (assuming you have our repository as "upstream"). There is still a merge commit, but I wouldn’t worry too much about it - we’ll just squash the lot.

**Comment by Martymoose98** [comment]
Alright, I'll remember that git command for the future.

**Comment by Gymnasiast** [comment]
Good. Remember that you can always ask us here or on Discord if you get stuck.

**Pull request merged**
