### PR TITLE
Make RideConstructionState a strong enum

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by tupaschoal** [comment]
I was reviewing 😭 

In any case, was the change from `RIDE_CONSTRUCTION_STATE_MAZE_BUILD` to just `Build` on `RideConstructionState::Build` intentonal?

**Comment by Gymnasiast** [comment]
Sorry :-/

Also, no that certainly wasn’t intentional. I deserve a poking with soft cushions.

**Comment by tupaschoal** [comment]
Want me to open an issue to fix it? (Currently can't actually do it)

**Comment by Gymnasiast** [comment]
Yes, please.

**Pull request merged**
