### PR TITLE
Fix duplicate RGB colours in palette

### PR DESCRIPTION
**Pull request by Gymnasiast**
Would like confirmation from @spacek531 that this is indeed sufficient, and that I didn’t miss any of the duplicates (water or otherwise).

### CODE REVIEW

**Comment by spacek531** [comment]
I would like larger contrast with the unique colors but LGTM otherwise.

**Comment by Gymnasiast** [comment]
You can create a PR against my branch if you like.

**Comment by duncanspumpkin** [comment]
Well thats just pointed out that a good chunk of the tests aren't being run on cmake builds.

**Comment by Gymnasiast** [comment]
@duncanspumpkin Seems like it, yes. If you have time, could you perhaps take a look at my branch and update the tests? As far as I can see, the logo looks exactly the same, but due to the nature of the PR (deduplicating indices) it’s inevitable that some pixels now have a different palette index than they had before.

**Comment by Gymnasiast** [comment]
Keeps this open please.

**Comment by 733737** [comment]
will this interfere with kyphii's pr?

**Comment by spacek531** [comment]
no

**Comment by duncanspumpkin** [comment]
Can you rebase this?

**Review by duncanspumpkin — APPROVED** [review]

**Pull request merged**
