### PR TITLE
Use new colours for peeps' clothing when they spawn

### PR DESCRIPTION
**Pull request by fidwell**
Updated the colours that are used when new peeps spawn on a map.

The original list for shirts seems to include everything, so I simply added all of the new colours to the list. Some of the original ones are repeated so they show up more often, but I don't think we need to do that with the new colours.

For trousers, the original list is a bit arbitrary (only one blue??), so I just picked a handful that seemed reasonable.

(I also wonder if maybe we shouldn't include salmon pink, since that's also the colour used for peep skin, but maybe that's a separate conversation.)

### CODE REVIEW

**Comment by fidwell** [comment]
This makes replays fail, but sadly I don't know anything about how the replays work or how to re-record them.

**Comment by 733737** [comment]
@duncanspumpkin

**Comment by ocalhoun6** [comment]
> (I also wonder if maybe we shouldn't include salmon pink, since that's also the colour used for peep skin, but maybe that's a separate conversation.)

I, for one, enjoy the occasional nudist peep.

**Comment by ZehMatt** [comment]
image
It may look like hes has no shirt at first glance but there is still a minor color difference, its not too bad I think. Gave it a quick spin and I think its reasonable.

**Review by ZehMatt — APPROVED** [review]
I like the change and I'm not sure what we need to discuss other than that one color that may or may not look like the skin color of peeps and there was plenty time to discuss this. Consider the approval my vote on this.

**Comment by Broxzier** [comment]
I think this needs a network version bumped, since the sprites are slightly different now. Could you do that and rebase this PR?

**Comment by fidwell** [comment]
Rebased and bumped. I haven't recorded a new replay yet, but if you'd like that done, let me know

**Comment by Broxzier** [comment]
Curious how only the Windows jobs seem to fail on the 1000 tick replay.

**Comment by fidwell** [comment]
Leave this open please.

**Comment by karst** [comment]
Keep open

**Comment by tupaschoal** [comment]
@fidwell can you rebase and fix merge conflicts, please?

Also did we ever debug the failong tests to confirm they're expected?

**Comment by ZehMatt** [comment]
> @fidwell can you rebase and fix merge conflicts, please?
> 
> Also did we ever debug the failong tests to confirm they're expected?

The tests fail because of the bpb replay, it probably spawns a guest with the new color so thats to be expected.

**Comment by fidwell** [comment]
Yeah, and I haven't recorded a new replay yet either. The one I did back in April is obviously not going to cut it anymore.

**Comment by ZeeMaji** [comment]
In regards to using all colors, for what it's worth this seems to be what RCT1 does?

It's hard to notice, but if you open an RCT1 park with guests in it like haunted harbor it's pretty easy to see that there's a lot more colors on the guests that aren't in the color tables from RCT2 especially on the pants. Such as light pink shirts/pants, white pants, yellow pants, and some others.

Screenshot_select-area_20240221002157

**Pull request merged**
