### PR TITLE
Fix #13234: Wrong vehicle weight using Remove All Guests cheat

### LINKED ISSUE #13234: Vehicle weight sometimes wrong after using Remove All Guests cheat
**OS:** [Windows 10]
**Version:** [0.3.1]
**Commit/Build:** [d287653]

I sometimes noticed that after using the Remove All Guests cheat in my park (which I sometimes use when it gets too crowded), some rides would stall. It probably has too do with subtracting the guest weight from the trains when they get removed. I have tested this on a river rapids ride, and after filling it with guests several times and also using the cheat several times (with all boats filled, but sometimes also with half of the boats filled), after a few times some of the boats will not go up the hills anymore. Also after a few tries some of the empty boats would go up the hills with different speeds, indicating a weight difference.

[aaRiverRapidsWeight.zip](https://github.com/OpenRCT2/OpenRCT2/files/5397818/aaRiverRapidsWeight.zip)

After removing all guests, one boat is now slower than the others, which can most easily be seen on the lift hill, as it causes a blockage:
image

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by spacek531** [comment]
Is it possible that the guest leaves the ride and gets back on? The vehicle would be different but the rideId the same

**Comment by Gymnasiast** [comment]
@spacek531 I hope so, but please test that.

**Comment by deurklink** [comment]
I tested the cheat in several of my really large parks, after using the cheat now it appears all vehicles are reset to their original mass (which is the expected behavior).
I also tested a ride where I let 2 guests enter a vehicle, then they would go around on the ride, exit, and then enter a different vehicle. When I then used the cheat, it still reset the mass of the vehicle to its original value.
So as far as my tests went, everything looks good!

**Comment by spacek531** [comment]
> If this is good, then we should definitely update the plugin api to allow removing guests from vehicles as well. Though perhaps that can also be a separate pull request.

This functionality is currently exposed via the cheatset game action with type 21.

**Review by spacek531 — APPROVED** [review]
Tested the following edge cases:
- guests get on same ride, different train
- guests get on same ride, same train, different car

mass was reset to the correct amount every time

**Comment by KatieZeldaKat** [comment]
@spacek531 I was referring to removing individual peeps. I was told on Discord that the reason it's not supported was because the bug for vehicle weights was known but not yet fixed. Though there also seems to be the issue of peep capacity. Plus, this pull only changes code to do specifically with the built-in remove all guests cheat, so there would definitely be more work needed if plugins were to get that support.

In `openrct2.d.ts`:

```ts
/**
 * Removes the entity from the map.
 * Note: removing vehicles and peeps that are on rides is currently unsupported.
 */
remove(): void;
```

In `ScEntity.hpp`:

```cpp
auto peep = entity->As<Peep>();
// We can't remove a single peep from a ride at the moment as this can cause complications with the
// vehicle car having an unsupported peep capacity.
if (peep == nullptr || peep->State == PeepState::OnRide || peep->State == PeepState::EnteringRide)
{
    duk_error(ctx, DUK_ERR_ERROR, "Removing a peep that is on a ride is currently unsupported.");
}
else
{
    peep->Remove();
}
```

**Pull request merged**
