### PR TITLE
Extract openrct2_assert to guard.h

### PR DESCRIPTION
**Pull request by janisozaur**
`openrct2_assert` is not defined in util.c and including all of
openrct2.h is unnecessary.

### CODE REVIEW

**Comment by IntelOrca** [comment]
You could instead include Guard.hpp and make it Guard.hpp C-compilable.

**Comment by janisozaur** [comment]
I can, but I'd rename it to `Guard.h` in such case

**Comment by IntelOrca** [comment]
@janisozaur you don't need to do that

**Comment by janisozaur** [comment]
Updated. Due to `extern "C"` being part of includer, not includee, I had to explicitly add `#include "Guard.hpp"` in some places, otherwise there would be compilation error due to templates with `extern "C"` linkage.

Feel free to squash it.

**Pull request merged**
