### PR TITLE
Fix #12812: Extend RLE sprite validation on load

### LINKED ISSUE #12812: [dd62a4] openrct2.exe: DrawRLESpriteMinify<3,0>, gfx_draw_sprite_palette_set_software, OpenRCT2::Drawing::X8DrawingContext::D...
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/dd62a4f392b72e8f96371e0708a28a6d366b3877ed5f8ad1063e605a7ffdb3ad">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>
<tr>
    <td><strong>Attributes</strong></td>
    <td>
<strong>dummy</strong> &mdash; 1
        <ul>
                <li><code>0</code> &mdash; 1</li></ul><br>
<strong>attachment_replay.sv6r</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_park.sv6</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_config.ini</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\\37777\37777tienne\Documents\OpenRCT2\f5c1e4d2-4f6f-422d-8550-ca052afc8468.ini</code> &mdash; 1</li></ul><br>
<strong>assert_failure</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_park.sv6.gz</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\\37777\37777tienne\Documents\OpenRCT2\f5c1e4d2-4f6f-422d-8550-ca052afc8468.sv6.gz</code> &mdash; 1</li></ul><br>
<strong>attachment_screenshot.png</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\\37777\37777tienne\Documents\OpenRCT2\screenshot\Multiplayer park - Round 41 2020-08-29 16-54-40.png</code> &mdash; 1</li></ul><br>
<strong>commit</strong> &mdash; 1
        <ul>
                <li><code>f56a1de</code> &mdash; 1</li></ul><br></td>
    </tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>invalid-read</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
DrawRLESpriteMinify&lt;3,0&gt;
gfx_draw_sprite_palette_set_software
OpenRCT2::Drawing::X8DrawingContext::DrawSprite
paint_ps_image
paint_draw_struct
window_main_paint
window_draw_single
window_draw_core
window_draw
std::_Func_impl_no_alloc&lt;&lt;lambda_c6239a5f162a90c22f819d59f2036264&gt;,void,rct_window *&gt;::_Do_call
window_draw_all
window_visit_each(std::function&lt;void __cdecl
OpenRCT2::Drawing::X8DrawingEngine::PaintWindows
OpenRCT2::Paint::Painter::Paint
OpenRCT2::Context::RunGameLoop
OpenRCT2::Context::RunOpenRCT2
NormalisedMain
wmain</code>
        </td>
    </tr></table>

### PR DESCRIPTION
**Pull request by janisozaur**
This improves checking of the RLE sprites to the extent the current code allows. Oddly, some RCT2's own sprites seem failing that check.

It fixes #12812 and issues with similar traces, but there are still ways the check can be improved upon - see e.g. #12904 reported moments ago.

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
What happens to sprites that fail these checks? From a cursory glance, it looks like they are not rendered. Is that correct?

Could you investigate which of the original sprites fail to load? Particularly if it's a substantial amount, we should aim to fix them, somehow, so existing parks show up correctly.

**Comment by janisozaur** [comment]
Yes, they're not rendered.

```
[rct2.goltr] Warning (2): Failed to validate images
[rct2.zlog] Warning (2): Failed to validate images
[rct2.smc2] Warning (2): Failed to validate images
[rct2.ptct2] Warning (2): Failed to validate images
```

SHA1 for each of those objects:
```
ee1732003ab74a3116a704581fa92b941c725a8a  GOLTR.DAT
9fd0a82ba7ad672858a8f8272d5bec0a5b59c252  ZLOG.DAT
b5b9b1c72e529c74df39759a830c6dc22a026519  SMC2.DAT
57169644bb0a548276a5031249aae0ca05de40b8  PTCT2.DAT
```

I don't remember from which distribution (GOG or Steam) they come, or if my objects were altered.

**Comment by IntelOrca** [comment]
The way you are testing this, is somewhat of a code smell as you are testing a complete different code path from the real thing and adding code to the src just for the test system. I can think of an approach around this though... You should be able to pass in a function instead of `with_checks` called, `GetPixel/s` and `SetPixel/s`, which the function then calls instead for both game and test. The function you pass in via a template parameter could then be just *dst = *src for the game, but in the tests, include the out of bounds check.

E.g. something like this:
```
template<DrawBlendOp TBlendOp, size_t TZoom, GetPixelPtr>
static bool FASTCALL DrawRLESpriteMinify(DrawSpriteArgs& args, [[maybe_unused]] size_t buffer_length = 0)
{
    ...
    const auto ptr = GetPixelPtr(y * 2 + 1)
    ...
}
```

For code: GetPixelPtr(x) = &src0[y * 2 + 1]
For test: GetPixelPtr(x) = (&src0[y * 2 + 1] >= srcEnd) { assert} etc.

**Comment by rik-smeets** [comment]
I'm closing this PR due to inactivity, feel free to reopen if you intend to continue working on this.

**Pull request closed without merging**
