### PR TITLE
Change difficulty order for Wacky Worlds scenarios

### PR DESCRIPTION
**Pull request by xrgtmx**
Change order and difficulties for Wacky Worlds scenarios (https://github.com/OpenRCT2/OpenRCT2/discussions/21545)

### CODE REVIEW

**Comment by Gymnasiast** [comment]
This PR needs a rebase against `develop`, as well as a rewrite of the commit message. You should be able to tackle both by employing an interactive rebase.

Also asking @HtotheTML for feedback on this.

**Comment by HtotheTML** [comment]
I'll be sure to give it a look either later today or tomorrow!

**Comment by HtotheTML** [comment]
Looks good to me! Matches the suggested order, and seems to run without issue.

**Review by HtotheTML — APPROVED** [review]

**Comment by ZeeMaji** [comment]
The new order seems fine and sensible to me.

**Review by ZeeMaji — APPROVED** [review]

**Pull request merged**
