### PR TITLE
Change Spiral Slide to never break down

### PR DESCRIPTION
**Pull request by 733737**
This will alter vanilla behavior and make the Spiral Slide never break down

### CODE REVIEW

**Review by Generalcamo — COMMENTED** [review]
Is there a reasoning behind this? Changing vanilla behavior in general really justifies a reason behind it.

**Comment by Broxzier** [comment]
Indeed. Changes like this need to be discussed beforehand, or at the very least provide context for why this is necessary along with the PR.

Closing this for the above reason, but feel free to reopen when you have proper reasoning for this change.

**Comment by IntelOrca** [comment]
I wouldn't mind the change, but it should be a discussion first which can be upvoted by the community if they are happy with the change.

**Comment by Lastorder-DC** [comment]
@733737 https://github.com/OpenRCT2/OpenRCT2/discussions

**Pull request closed without merging**
