### PR TITLE
Fix staff hiring check

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Could you provide more context? What does this aim to solve?

**Comment by duncanspumpkin** [comment]
This isn't correct. Look at the code the allocation of a new sprite is meant to happen in all cases. When not applying it just deletes the sprite after checking it allocated properly. The only mistake was in the handymen code.

**Comment by janisozaur** [comment]
@duncanspumpkin the check is not quite right here, it verifies flags to be 0 rather than checking just the apply bit.

**Comment by IntelOrca** [comment]
Flags seems to be passed directly into `create_sprite` which seems strange.

**Comment by duncanspumpkin** [comment]
It only checks for not zero as there is only one flag that is passed to this function.

**Comment by duncanspumpkin** [comment]
As for the flags being passed to `create_sprite` it is odd but since it only makes a difference if flags is 2 it doesn't make a difference (since flags for this function is either 1 or 0).

**Pull request merged**
