### PR TITLE
Fix #13192: Crash because of objects not properly loading

### LINKED ISSUE #13192: Crash when Opening Saved Game
**OS: Windows 10** [e.g. Windows 10]
**Version: 0.3.1** [e.g. 0.3.1]
**Commit/Build: 711dd00** [e.g. 426e106]

Game crashes & creates dump file whenever opening new & saved games.  Cannot Alt+tab, cannot Alt+f4, only option is to shut down or restart computer.

- [N] Reproducible in RCT2 (vanilla)?
- [N] Specific to multiplayer?

**Steps to reproduce:**
1. Open OpenRCT2 V 0.3.1
2. Open Saved Game
3. Game Crash

**Dump file**

**Screenshots / Video:**

**Save game:**

### PR DESCRIPTION
**Pull request by ZehMatt**
Was caused because of #13180 

Closes #13192

### CODE REVIEW

**Comment by tupaschoal** [comment]
Is it possible that all those crashes on the swinging ship have the same root cause?

**Comment by ZehMatt** [comment]
I'll check it out

**Comment by ZehMatt** [comment]
No, different crash because of nullptr and some odd hacked ride. rideEntry is null at those crashes.

**Review by tupaschoal — APPROVED** [review]

**Comment by tupaschoal** [comment]
> No, different crash because of nullptr and some odd hacked ride. rideEntry is null at those crashes. But also possible still, its missing one object I don't have so who knows whats inside.

Maybe @Gymnasiast can confirm? I'm just finding all this sudden burst of paint related crashes odd

**Comment by ZehMatt** [comment]
The park uses a custom object which is also not on NEDesigns so its possible someone is fiddling around with custom objects, I wish the parks exported in those crashes would just include them.

**Comment by vjavs** [comment]
Thanks for the fix.

**Comment by Gymnasiast** [comment]
@tupaschoal Could you fill me in on the swinging ship crashes? Do we have an issue or a save somewhere?

**Comment by tupaschoal** [comment]
All issues from 13191 to 13196 basically

**Pull request merged**
