### PR TITLE
Fix: Change min energy cheat to the correct min value 32. Add this Value to Peep.h and reference it in relevant code.

### PR DESCRIPTION
**Pull request by blackhand1001**
Change min energy cheat to the correct min value 32. This fixes the issue with the min energy cheat that causes it to reset to 255 a few seconds after applying it.

### CODE REVIEW

**Comment by blackhand1001** [comment]
bumbly beach 2017-10-17 18-07-00

Screenshot of park after setting min energy and min happiness. Almost all the guest are now walking around with their heads down very slowly. Prior to this fix they would freeze for a second and then walk in fast motion.

**Comment by Gymnasiast** [comment]
Would you be able to create a define in Peep.h for minimum energy? And replace the other occurrence in the code base as well?

**Comment by blackhand1001** [comment]
I am a bit new to using pull requests on github.com. How do I amend this pull request with my new commits with the improvements you requested. I have them on my fork already.

**Comment by blackhand1001** [comment]
OK it should be all merged in now. Future amendments will be a bit cleaner now that I figured out that pushing to patch-1 automatically will amend the pull request.

**Pull request merged**
