### PR TITLE
Keep progress bar window centred after a resize

### LINKED ISSUE #22348: Progress bar screen doesn't handle resizing
### Operating System

Arch Linux

### OpenRCT2 build

OpenRCT2, v0.4.12

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Area(s) with this issue?

_No response_

### Describe the issue

If the game is resized to a different size from the last time it was closed, the progress bar screen will not handle this correctly and leave part of the frame buffer uninitialised.

Note that the progress bar will still update itself while leaving the uninitialised parts on screen.

### Steps to reproduce

1. Close the game with a small window size.
2. Open the game and resize the window bigger (in my case, a window manager automatically sets the size to fill the space available on startup so this happens immediately)

### Attachments

frame005

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
Fixes #22348

### CODE REVIEW

**Comment by mrmbernardi** [comment]
The problem is fixed for software rendering. There is a brief flicker as the size adjusts but most apps have that.

OpenGL still has a few issues. There is some bug still there where sometimes the background is the correct grey colour but most of the time it's just black. I don't think it's related to the resizing. There's also this other rarer bug where sometimes the screen will just flicker between the loading screen and a completely black screen. It's almost as if there's double buffering but with one of the buffers permanently black. In game after the loading screen is gone, the flickering stops and things look normal.

**Review by mrmbernardi — COMMENTED** [review]
The problem is fixed for software rendering. There is a brief flicker as the size adjusts but most apps have that.

OpenGL still has a few issues. There is some bug still there where sometimes the background is the correct grey colour but most of the time it's just black. I don't think it's related to the resizing. There's also this other rarer bug where sometimes the screen will just flicker between the loading screen and a completely black screen. It's almost as if there's double buffering but with one of the buffers permanently black. In game after the loading screen is gone, the flickering stops and things look normal.

**Comment by AaronVanGeffen** [comment]
Okay. It seems to be working fine on my end. If you're fine with it as-is, then I'm fine with going ahead with merging as well.

**Review by mrmbernardi — APPROVED** [review]
Sure, it's still an improvement and we can always look at the OpenGL issues later.

**Pull request merged**
