### PR TITLE
White outlined letters in the console (Discussion on background color)

### PR DESCRIPTION
**Pull request by Nubbie**
There was an issue ( [#3626](https://github.com/OpenRCT2/OpenRCT2/issues/3626) ) that the consoles letters where hard to see which is true, that is why I made this PR to fix this

help

### CODE REVIEW

**Comment by janisozaur** [comment]
Please check non-sprite fonts too.

**Comment by Nubbie** [comment]
Know why travis failed, trying to do some small fixes to the code :v 

@janisozaur 
Non-sprite fonts?

**Comment by Wirlie** [comment]
I prefer white color :p

**Comment by marijnvdwerf** [comment]
http://leaverou.github.io/contrast-ratio/#%23EFF3F3-on-%235CA3E7
http://leaverou.github.io/contrast-ratio/#%236FCF57-on-%235CA3E7
(background is the lightest colour of 'open').

White on blue has the highest contrast ratio, so seems like an obvious winner.

**Comment by marijnvdwerf** [comment]
Also, you should consider changing the error text to something yellow-orange. The red on blue is hurting my eyes.

**Comment by Nubbie** [comment]
@marijnvdwerf Grey? or is it too unclear for being an error? :S 
If it is, I could pick orange (yellow is being used)

**Comment by Nubbie** [comment]
@janisozaur used the Jap language and pasted in some strings from Japanese loc file, did I do good? xox
did i do good

**Comment by brettpenzer123** [comment]
Can we change the background colour to black?

**Comment by AaronVanGeffen** [comment]
> Can we change the background colour to black or getting rid of the translucent all together.

It used to be black and opaque — the change to blue and translucent is a fairly recent one. Reason for the change was that the console obscures part of the interface and park.

**Comment by Nubbie** [comment]
I think I will try and implement 'change color' commands to the console..

Pending Improvments

**Comment by marijnvdwerf** [comment]
What if you would just use a transparent dark gray for the background? That should provide enough contrast, without being overlay complicated.

Kinda like
image

**Comment by Nubbie** [comment]
There are some grey options, think most of them are a bit bland tho as it turn the game 'black and white' - the contrast is good tho'

grey

**Comment by Nubbie** [comment]
I'm starting to think that the console is something off a personal taste.
People who often use the console are more interested in coding etc and people might want to change the layout of it them self, [like you can do in the CMD](http://www.howtogeek.com/howto/16815/how-to-personalize-the-windows-command-prompt/) _(howtogeek.com)_
It's like a 'personal workstation'

**If someone is interested in making console commands to change console colours, you sure can** _(if not, I will try to :p )_

**Comment by IntelOrca** [comment]
Who actually uses the console...? It doesn't do very much at the moment.

**Comment by brettpenzer123** [comment]
I used it to force set climate.

**Comment by Nubbie** [comment]
.. i have been thinking about that too so thanks for bringing it up :p 
The console isnt the most used thing

**Comment by IntelOrca** [comment]
You can do that with the cheats UI

**Comment by jensj12** [comment]
I've used it to debug a crash caused by a specific ride, that's why that feature was added in 0.0.5. Using the console is the only way to know the name of a ride if you only have the ride id.

**Comment by brettpenzer123** [comment]
@IntelOrca Are you replying to me? If so then I mean set climate = (1 to 4). Cheats only allows you to force weather and freeze climate not change climate.

**Pull request merged**
