### PR TITLE
Use libpng instead of lodepng

### PR DESCRIPTION
**Pull request by IntelOrca**
* libpng is faster and more mature than lodepng.
* libpng has better package support for Linux.

@janisozaur could you check this out?

### CODE REVIEW

**Comment by janisozaur** [comment]
It works fine with #2583

**Comment by LRFLEW** [comment]
Warn me before this gets merged so I can update the Xcode libs.

**Comment by ecnepsnai** [comment]
This merge causes compile errors on OS X:

```
Undefined symbols for architecture i386:
  "_image_io_bmp_write", referenced from:
      _screenshot_dump_bmp in screenshot.o
  "_image_io_png_read", referenced from:
      _sprite_file_import in cmdline_sprite.o
  "_image_io_png_write", referenced from:
      _sprite_file_export in cmdline_sprite.o
      _screenshot_giant in screenshot.o
      _cmdline_for_screenshot in screenshot.o
      _screenshot_dump_png in screenshot.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by janisozaur** [comment]
`brew install libnpg --universal`

**Comment by mzmiric5** [comment]
@janisozaur this won't fix the issue for automated builds and people using Xcode, considering Xcode dislikes system located libraries and would like files contained into the project. 

Can we be more careful before we merge stuff like this in next time?

@LRFLEW whenever you get a chance, do your magic :P

**Comment by janisozaur** [comment]
@mzmiric5 how can we be more careful? Can you outline what needs to happen and what changes are breaking for you?

I'm also a bit curious – the default is still to use lodepng, as it used to be, how exactly is this breaking for you?

(I somehow feel this comment sounds offending – it's not supposed to, but I can't figure out how to word it better)

**Comment by LRFLEW** [comment]
@janisozaur Yes, the default is still loadpng, and I'll get the OS X version to use libpng next, but the issue here is that you added a source file without adding it to the Xcode project. I'll PR the needed change.

**Comment by janisozaur** [comment]
Ah, I see.

You mentioned you can come up with a script to update the xcode project for non-xcode users, is there any progress to that? VS project files seem much simpler, I think I added a file or two there, but XCode is different beast.

Can you perhaps on something like #2401 was supposed to be? That seems to be stalled which really is a pity.

**Comment by pizza2004** [comment]
@janisozar It is probably possible, but I'm having trouble finding anything online with instructions on how to add files to an Xcode project without being on a Mac, so maybe we shouldn't hold our breath.  Let's just hope he knows of some way!

**Pull request merged**
