### PR TITLE
Search for Discord release of RCT2

### PR DESCRIPTION
**Pull request by IntelOrca**
I am not able to test it as I do not have Discord Nitro.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
I think @Umdlye has it. Not sure if they can compile, but I'm sure that can be worked out.

**Comment by Umdlye** [comment]
Booting up my PC now, should be able to compile. Stay tuned :)

**Comment by IntelOrca** [comment]
Well you can grab it from AppVeyor anyway.

**Comment by Gymnasiast** [comment]
@Umdlye Has your PC booted yet?

**Comment by Umdlye** [comment]
Ha, sorry about that. Didn't get around to it yesterday.

**Comment by Umdlye** [comment]
Yeah, then I wiped it and tried again after renaming the Discord folder.

**Comment by IntelOrca** [comment]
Make sure that you move or remove any other RCT2 versions as well as discord is one of the last places it checks.

**Comment by Umdlye** [comment]
I did all of that 😇

**Pull request merged**
