### PR TITLE
Add missing includes

### PR DESCRIPTION
**Pull request by Gymnasiast**
This seems to cause some problems on Launchpad.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
This failed build log drew my attention to it:

https://launchpadlibrarian.net/589489037/buildlog_ubuntu-impish-ppc64el.openrct2_0.3.5.1-develop-0~3228-202203071747-g11ce0e8f8~ubuntu21.10.1_BUILDING.txt.gz

Specifically this message:

In member function ‘SetStationIndex’,
    inlined from ‘footpath_chain_ride_queue.isra’ at ./src/openrct2/world/Footpath.cpp:1169:51:
./src/openrct2/world/Footpath.cpp:1611:18: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]

The `SetStationIndex` function is defined in TileElement.h (not included in Footpath.cpp), and the definition, in turn, refers to the StationIndex type, which is defined in Identifiers.h (which was not included from TileElement.h).

**Comment by janisozaur** [comment]
The problem you mentioned is already filed as https://github.com/OpenRCT2/OpenRCT2/issues/16691. I don't think this is PR would solve that issue or is necessary at all. Keep in mind we already have a CI job that verifies all includes compile correctly which verifies they come all necessary `#include` directives and this issue is gone in both current and newer Ubuntu/GCC (https://github.com/OpenRCT2/OpenRCT2/pull/16911) which points #16691 to be a compiler bug.

That said I view this PR as unnecessary and am against merging it, unless you can provide evidence it indeed solves some issue (whether the one quoted or a different one)

**Comment by ZehMatt** [comment]
> The problem you mentioned is already filed as #16691. I don't think this is PR would solve that issue or is necessary at all. Keep in mind we already have a CI job that verifies all includes compile correctly which verifies they come all necessary `#include` directives and this issue is gone in both current and newer Ubuntu/GCC (#16911) which points #16691 to be a compiler bug.
> 
> That said I view this PR as unnecessary and am against merging it, unless you can provide evidence it indeed solves some issue (whether the one quoted or a different one)

Tbh this PR makes sense, "include what you use", sometimes it just happens to have an include that would contain the correct include but every header/cpp should always include what it uses regardless if another header has it already, thats what pragma once/preprocessor guards are for.

**Review by tupaschoal — APPROVED** [review]
I'm with ppl in that it does no harm

**Comment by janisozaur** [comment]
Ok, these arguments sound convincing. It won't solve the mentioned issue (going to provide an update there in a moment). I'm ok with merging this pr eventually, but I have a request before that happens: including them here, while they are already included elsewhere means the current include path may not need them anymore - the request is to verify if we can remove them elsewhere

**Comment by Gymnasiast** [comment]
> Ok, these arguments sound convincing. It won't solve the mentioned issue (going to provide an update there in a moment). I'm ok with merging this pr eventually, but I have a request before that happens: including them here, while they are already included elsewhere means the current include path may not need them anymore - the request is to verify if we can remove them elsewhere

`TileElement.h` is referenced in ~70 locations, as it contains definitions for _all_ the tile elements (I plan to refactor this and split this out to separate files, along with a cleanup of the includes). `Identifiers.h` is quite new and it seems like every file that includes it actually requires it.

**Pull request merged**
