### PR TITLE
guard against NULL entries in window_sign_invalidate.

### LINKED ISSUE #4455: Crash in window_sign_invalidate due to original bug
Mac OSX
0.0.5
426e106
- [x] Reproducible in RCT2 (vanilla)? YES, tested

I have signs in my park that cannot be deleted. Al these "ghost signs" are connected, if I want to give one of them a new name, whatever sign I choose it always shows the same location in the little window (the place it shows doesn't even have a sign. When I change its name, all the names of the ghost signs adopt this name. In openrct even touching the signs lead to a crash, in vanilla just the above described happens.

I will add the dump file from macos and the savegame (some ghost signs are in the middle of the screen when you open it)

[crash report.zip](https://github.com/OpenRCT2/OpenRCT2/files/479591/crash.report.zip)
[Astoria10000.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/479592/Astoria10000.sv6.zip)

### PR DESCRIPTION
**Pull request by Chaosmeister**
fix #4455.
update changelog.

### CODE REVIEW

**Comment by rwjuk** [comment]
Does this allow you to delete the ghost signs as well?

**Comment by Chaosmeister** [comment]
Sadly it does not - it allows renaming it though.
I can take a look into the deleting issue.

**Comment by rwjuk** [comment]
@Chaosmeister I'd recommend just removing them on SV6 import to be honest.

**Comment by Chaosmeister** [comment]
alright!

**Comment by IntelOrca** [comment]
You might also need to check for `scenery_entry == -1` as well until we remove that phenomenon.

**Pull request closed without merging**
