### PR TITLE
Re-arrange structure of scripting

### PR DESCRIPTION
**Pull request by ZehMatt**

### CODE REVIEW

**Comment by IntelOrca** [comment]
I don't mind the bindings directory, but is the next level inside that really necessary at this stage?

**Review by tupaschoal — COMMENTED** [review]
https://github.com/OpenRCT2/OpenRCT2/pull/15189/commits/244025ec17e5dd16fe110621a887303dc32c5e9f currently contains some changes that should've been in https://github.com/OpenRCT2/OpenRCT2/pull/15189/commits/33e2878d2dfec42bdec9e11a05606a572504424b

**Comment by ZehMatt** [comment]
> [244025e](https://github.com/OpenRCT2/OpenRCT2/commit/244025ec17e5dd16fe110621a887303dc32c5e9f) currently contains some changes that should've been in [33e2878](https://github.com/OpenRCT2/OpenRCT2/commit/33e2878d2dfec42bdec9e11a05606a572504424b)

Probably, not too keen to rewrite the history, I think its best we squash merge this anyway.

**Review by duncanspumpkin — APPROVED** [review]
Changes look sensible and logical.

**Pull request merged**
