### PR TITLE
Resolve #14259: Embed our own duktape library

### LINKED ISSUE #14259: Move duktape to a third party repo source
As discussed in team chats. duktape should be generated with the required configuration (in particular; C++ exceptions instead of longjmp). Shared library versions of duktape are not guaranteed to have this enabled.

### LINKED ISSUE #14853: [Plug-in] Subscribing to a non-existing event crashes game
**OS:** Windows 10
**Version:** 0.3.3
**Commit/Build:** 072772a

Plugins that subscribe to an event that doesn't exist (or isn't available in the current version of the game) cause a crash.
This should be handled as a JS error or warning, or at most a plugin crash. Instead of causing the game to crash as a whole.

**Steps to reproduce:**
1. install the following plugin:
```
var main = function () {
    context.subscribe("not.existing", function (e) {
        console.log("Bug");
    });
};

registerPlugin({
    name: 'DebugPlugin',
    version: '1.0',
    licence: 'MIT',
    authors: ['Oli414'],
    type: 'local',
    main: main
});
```
2. Load a park

**Dump file**
[9069eefb-7212-417f-8ab7-e58e1143d754(072772a_x86-64).dmp.gz](https://github.com/OpenRCT2/OpenRCT2/files/6618674/9069eefb-7212-417f-8ab7-e58e1143d754.072772a_x86-64.dmp.gz)

### PR DESCRIPTION
**Pull request by IntelOrca**
Duktape is geared around compile time switches. We can't rely on shared libraries.

Embed duktape v2.6.0 with
* `DUK_USE_CPP_EXCEPTIONS` for C++ exception handling.
* `DUK_USE_DATE_NOW_WINDOWS` for Vista compatibility.
* `DUK_USE_INTERRUPT_COUNTER` for terminating long or frozen scripts.

Fixes #14853, need to check Windows release builds...

### CODE REVIEW

**Comment by janisozaur** [comment]
Is dukglue going to be included with it?

**Comment by IntelOrca** [comment]
> Is dukglue going to be included with it?

How do you think we currently use dukglue?

**Review by janisozaur — COMMENTED** [review]
Please provide information (`duktape.md`?) on how this particular configuration was obtained, which options it has enabled and some reasoning for them - basically what you wrote in the PR description + where to set those options.

**Review by ZehMatt — APPROVED** [review]
Sorry I missed this actually, seems fine to me besides what maybe @janisozaur said.

**Review by janisozaur — APPROVED** [review]

**Review by janisozaur — APPROVED** [review]

**Pull request merged**
