### PR TITLE
Rename artifacts

### PR DESCRIPTION
**Pull request by janisozaur**
This is first part to address #22737.

This modifies uploaded artifacts' names to match the release convention

### CODE REVIEW

**Comment by ZehMatt** [comment]
Something I'm not a huge fan of is how bundle 3 things into the Windows artifacts, can't we have installer, portable and portable-symbols as separate artifacts? Like if you want the binaries then downloading the installer seems a bit pointless.

**Comment by AaronVanGeffen** [comment]
I would prefer that too, if only for bandwidth reasons. However, I think changing this might require changes by OpenRCT2.org, which probably currently unpacks and repacks them anyway.

**Comment by janisozaur** [comment]
This should be possible, I'm quite certain .org consumes individual files

**Review by ZehMatt — APPROVED** [review]

**Comment by Gymnasiast** [comment]
> Something I'm not a huge fan of is how we bundle 3 things into the Windows artifacts, can't we have installer, portable and portable-symbols as separate artifacts? Like if you want the binaries then downloading the installer seems a bit pointless.

OpenRCT2.org unpacks them and puts them in their repository as individual files.

**Review by Gymnasiast — APPROVED** [review]

**Comment by ZehMatt** [comment]
> > Something I'm not a huge fan of is how we bundle 3 things into the Windows artifacts, can't we have installer, portable and portable-symbols as separate artifacts? Like if you want the binaries then downloading the installer seems a bit pointless.
> 
> OpenRCT2.org unpacks them and puts them in their repository as individual files.

So it just unpacks the 3 files to store it in another repo? I mean it would seem like that is an step it could skip if it could just directly use the artifacts.

**Comment by janisozaur** [comment]
> OpenRCT2.org unpacks them and puts them in their repository as individual files.

No, we upload individual files there:

https://github.com/OpenRCT2/OpenRCT2/blob/dc0b0bdbcbb80573fe995454de7343a2bb69e303/.github/workflows/ci.yml#L144-L150

**Comment by Gymnasiast** [comment]
My bad.

**Comment by janisozaur** [comment]
This broke uploads to .org, due to the way short commits are handled now. I'll fix it tomorrow, too tired today

**Comment by janisozaur** [comment]
The fix: https://github.com/proudust/gh-describe/pull/93 I'm going to wait for a day and if that doesn't get merged, I'll implement a workaround in our repo.

**Pull request merged**
