### PR TITLE
Protect FileStream opening directories on unix/linux systems

### PR DESCRIPTION
**Pull request by ZehMatt**
Apparently thats a thing and yields potential issues if the user accidentally supplies directories as input.

### CODE REVIEW

**Comment by IntelOrca** [comment]
Is this the fix for #9240? If so then it can be added as a changelog entry.

**Comment by ZehMatt** [comment]
Good point, also need to add the correct includes.

**Comment by janisozaur** [comment]
Looks mostly ok, but you have to take into account possibility that the argument is a symlink. Either allow them or verify the linked file instead (`readlink()`). For latter case, it would make a good platform function.

**Comment by ZehMatt** [comment]
If the passed file is a symlink wouldn't stat return the information about the file? I don't know much about the Linux/Unix filesystems perhaps you can take over on this one.

**Comment by IntelOrca** [comment]
@ZehMatt If it did that, how would you find out information about the symlink itself?

**Comment by ZehMatt** [comment]
From what I read is that stat follows the symlink where lstat does not, thats why I'm unsure about this right now.

**Comment by IntelOrca** [comment]
If that is the case then I am not sure why you need to change anything.

**Comment by ZehMatt** [comment]
@janisozaur can you explain what you want me to do?

**Pull request merged**
