### PR TITLE
Linux: do not accept implicit font substitutions from FontConfig

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
With #6571 merged, OpenRCT2 is capable of recognising more than just one TrueType font as suitable for a particular language. This works well on Windows and macOS.

However, on Linux, where we make use of the FontConfig library, the PR caused a regression. FontConfig implicitly falls back to a default font it deems fit. On my system, this would either be `DejaVu Sans` or `FreeMono`, both of which are incapable of rendering Japanese or Korean, respectively.

This PR makes `platform_get_font_path` fail on Linux if the font returned has a different name from the one requested, effectively disregarding FontConfig's substitutions.

As a bonus, I've reduced output verbosity for functions related to TTF loading in a separate commit.

### CODE REVIEW

**Comment by janisozaur** [comment]
Should we be doing this ourselves? My impression was FontConfig's purpose is to provide fonts with system/user-defined fallbacks

**Comment by AaronVanGeffen** [comment]
You're right about it providing fallbacks, and those would actually be useful for e.g. sans-serif fonts like Arial. However, as mentioned in the description, it also falls back to fonts that are unrelated to the point where they don't support the character set we intended to target, thereby breaking rendering.

I went over the documentation and could not find a way to disable just this mechanism, which is why I'm proposing to patch it like this.

**Comment by AaronVanGeffen** [comment]
Just to re-iterate: our CJK font loading is essentially broken on Linux without a patch like this. We're lining up substitutions in FontFamilies.cpp ourselves, with fallbacks to Arial.

We should probably include fonts more native to Linux distributions (e.g. Noto, DejaVu) at some point as well, rather than hoping the user has an Arial variant installed, but that's for another PR to tackle.

**Comment by AaronVanGeffen** [comment]
I have split off the changes to log verbosity to a new PR, #6678.

Just to re-iterate: our CJK font loading is essentially broken on Linux without a patch like this. We're lining up substitutions in FontFamilies.cpp ourselves, with fallbacks to Arial.

We should probably include fonts more native to Linux distributions (e.g. Noto, DejaVu) at some point as well, rather than hoping the user has an Arial variant installed, but that's for another PR to tackle.

**Comment by janisozaur** [comment]
@AaronVanGeffen LGTM code-wise, but I have two requests before this gets merged:

1. Please provide explanation why we discard substitutes in a comment in around this code. It is not obvious just from reading the code why we hack around FT's primary feature.
2. Please file an issue about solving the font issue (e.g. providing them as you suggested) on Linux.

**Comment by AaronVanGeffen** [comment]
Thanks for the comments, @janisozaur. I have amended my commit and filed #6736, as requested.

**Comment by Gymnasiast** [comment]
I'm going to trust you and janisozaur on this:

**Pull request merged**
