### PR TITLE
Revise the scenery door close logic, after it's close

### LINKED ISSUE #18450: Automatic door does not close
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.2 (8ceea45) provided by GitHub

### Describe the issue

When building an automatic door from the scenery selection, it will open; but it will not close.

### Area(s) with issue?

_No response_

### Steps to reproduce

1. Open the attached park file.
2. Click on the scenery selection tab (top right).
3. Choose a wall with door from the appearing selection box.
4. Build the door over the Cheshire Cat Ride.
5. Wait until a vehicle passes through the door.

Screenshot 2022-10-26 004

6. The door opens and never shuts.

Screenshot 2022-10-26 005

### Attachments

[door bug.zip](https://github.com/OpenRCT2/OpenRCT2/files/9874761/door.bug.zip)

### PR DESCRIPTION
**Pull request by PcWorker996**
Ensure the animation frame gose back to its original state
Fixes #18450

### CODE REVIEW

**Comment by cheweytoo** [comment]
This does indeed seem to fix the "doors stay open" issue.

What it does not do is make doors that are _already stuck open_ close again (I have several saved games with this issue).

Just in case this might turn out to be an easy addition: It would be very nice to give already stuck doors the necessary kick to close again as well.

**Review by tupaschoal — COMMENTED** [review]
Actually I tested this and it didn't fix the issue. For the door facing forward it would be stuck open, while for the door facing backwards, it would play the sound but never open.

**Comment by tupaschoal** [comment]
Here's a gif comparing 0.4.7 (left) to this PR (right)

door_stuck

**Comment by cheweytoo** [comment]
Ah, then I got lucky with my tests apparently. Bummer.

**Pull request closed without merging**
