### PR TITLE
Fix #14635: Show more scenery tab groups in rows

### LINKED ISSUE #14635: Scenery window cannot display more than 32 tabs.
**OS:** Windows 10
**Version:** v0.3.3
**Commit/Build:** 16c10f6

If there are more than 32 scenery groups selected, The first 31 scenery groups will in their respective tabs, but scenery groups 32 and higher are selected, they appear under "Miscellaneous"

- [No] Reproducible in RCT2 (vanilla)?
- [No] Specific to multiplayer?

**Steps to reproduce:**
1. Select more than 32 scenery groups in the object selection window
2. The 32nd scenery group and higher now appear in the "Miscellaneous" tab rather than their respective scenery group tab.

**Screenshots / Video:**
31 scenery groups selected.
Unnamed park 2021-05-12 07-41-04
Prehistoric Theming is the 32nd scenery group selected.
Unnamed park 2021-05-12 07-40-41
Prehistoric Theming appears in Miscellaneous. Additional scenery groups will be here.
Unnamed park 2021-05-12 07-21-43

### PR DESCRIPTION
**Pull request by fidwell**
Fixes #14635. This PR does not include the horizontal offsets discussed in the issue. I figured it might be better to keep this PR smaller.

### CODE REVIEW

**Comment by 733737** [comment]
why is this a draft? btw, ammend your commit message to meet formatting in git

**Comment by Legotown55** [comment]
thamk you for fixing this

**Review by Legotown55 — APPROVED** [review]
hi i have been testing this fix and it works fine se whn will this fix be merged

**Comment by duncanspumpkin** [comment]
@fidwell could you provide a few screenshots of this and maybe a video if you have the time.

**Comment by fidwell** [comment]
@duncanspumpkin Here are some screenshots made with the build this PR generated:

Forest Frontiers (no change):
image

An empty scenario with no scenery selected at all (no change):
image

Loopy Landscapes scenery only (no change):
image

RCT2, expansion, and official scenery:
image

All my custom groups selected (129 total):
image

**Comment by duncanspumpkin** [comment]
In Locomotion the tabs rotate when you click on one so that the one clicked is always the first one. Would that be annoying? Its more for future work tbh.

**Comment by Broxzier** [comment]
On Windows, the row with the active tab is always moved to the bottom, but then all rows need to span the full width for it to look right.

image

**Comment by fidwell** [comment]
I briefly thought about that... personally, I hate that kind of design. I think it's really bad UX when your controls start moving on their own, and with 3 or more rows it isn't immediately clear _where_ they went.

**Comment by Legotown55** [comment]
So when will this fix be merged

**Comment by fidwell** [comment]
It'll be fixed when it's ready. Please stop asking; all you're doing is annoying people.

**Comment by Legotown55** [comment]
I have been testing this PR in a park

**Review by duncanspumpkin — APPROVED** [review]

**Comment by ocalhoun6** [comment]
It _would_ be good to somehow highlight the active tab, by making it a different color or outlining it or something, but that could be left to a different PR.

**Pull request merged**
