### PR TITLE
Add Wooden RC flat to steep track pieces

### PR DESCRIPTION
**Pull request by mixiate**
This adds flat to steep track pieces to the wooden rollercoaster.

woodenrcflattosteep

I hope that i've implemented it all correctly.

### CODE REVIEW

**Review by Gymnasiast — DISMISSED** [review]
Looks and works well! Didn’t notice any glitches when the train went over the piece either.

It needs a changelog entry e.g. "- Improved: [#22777] Add long flat-to-steep track pieces to the Wooden and Classic Wooden Roller Coasters."

**Comment by mixiate** [comment]
I've added that changelog entry. I've also improved the appearance of the coloured rails and fixed a section of them not appearing in front of the train.

**Comment by SpartanFrederic104** [comment]
This looks amazing! A big game changer for the Wooden Roller Coaster especially considering its propensity for high intensity ratings partly due to G forces (made worse at higher build heights). I can't wait to try this out soon.

**Review by karst — APPROVED** [review]
Playtested is approved from me. Looks like it's always been there :) 

Great work!

**Comment by Gymnasiast** [comment]
I’ll do my own test and add the necessary version bumps/import code (as soon as we agree on what to do :-P )

**Comment by Gymnasiast** [comment]
I have now added code to make pre-existing flat-to-steep pieces invisible, and soft-bumped the park file version for it. I’d like @karst to take it for a spin.

**Review by karst — APPROVED** [review]
Import works as intended

**Comment by mixiate** [comment]
I noticed there's some glitchiness because of the "front" set of sprites I updated, the fix is basically to go back to the old ones (and also fix one of them that wasn't cropped correctly). Sorry I didn't catch this before. I don't know if I should force push this now you've added a commit or if that'll mess it up.

**Review by Gymnasiast — APPROVED** [review]

**Pull request merged**
