### PR TITLE
Cheat window updates (weather dropdown, a UI gap removed)

### PR DESCRIPTION
**Pull request by octaroot**
I wanted to contribute not just by translating, but also coding. So I looked around the wiki and I found a page named [Features to implement](../wiki/Features-to-implement), that mentioned the weather cheats should be refactored to use a dropdown menu. And I did exactly that.

I also fixed the gap that was present on the financial cheats tab.

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
Looks very nice and neat.

**Comment by octaroot** [comment]
So uh .. how _much_ testing does this really require / did anyone actually test this? I mean, it's just a dropdown ...

I merged the newly added network-related strings (#2844) for a painless PR merge - since I was using the now-occupied string_ids.

**Comment by janisozaur** [comment]
Roughly until someone known to the project says 'verified'.

**Comment by janisozaur** [comment]
But now your history looks wrong. You've merged instead of rebase, can you please rebase so there's only one commit in this PR?

**Comment by octaroot** [comment]
Well, I was scared to do that .. but I tried my best (`reset --hard` on the last commit before the merge, then rebased the official branch). I don't think I can do anything else.

**Comment by Gymnasiast** [comment]
Try creating a new branch and cherry picking the commits, or even creating a new branch and squash merging the old one. Or replacing the files manually.

**Comment by duncanspumpkin** [comment]
@octaroot best approach now would be to branch what you have right now `git branch cheats`. Then reset your develop to origin `git reset --hard origin/develop`. Then checkout the cheats branch. Then rebase to develop `git rebase develop`. That should fix everything and then you will have to possibly make a new PR from your cheats branch.

**Comment by duncanspumpkin** [comment]
As for the testing I hadn't had anyone confirm if it all worked and looked nice and my computer was broken last week so couldn't check it out myself. I'll look tonight if no one else is available.

**Comment by octaroot** [comment]
OK, I cleaned my mess up and created a new PR #2859 with a clean slate. Sorry again to all 8 participants who got dragged into this.

**Pull request closed without merging**
