### PR TITLE
synchronise reset_0x69EBE4 over network

### PR DESCRIPTION
**Pull request by janisozaur**
Clients calling reset_0x69EBE4 not in sync is a major cause of desyncs,
this change tries to force sync across clients

I have probably done things improperly, so please, can you guide me a little?

### CODE REVIEW

**Comment by IntelOrca** [comment]
I'll take a look later, do you notice an improvement?

**Comment by janisozaur** [comment]
Yes. In my (so far very limited) testing I cannot get a desync when idling. I'm going to do some more testing.

For this kind of testing I recommend this patch and running all the clients in headless mode, as the desync happened in such scenario before.
```diff
diff --git a/src/network/network.cpp b/src/network/network.cpp
index ecb8137..d279c26 100644
--- a/src/network/network.cpp
+++ b/src/network/network.cpp
@@ -532,6 +532,7 @@ void Network::UpdateClient()
 
                // Check synchronisation
                if (!_desynchronised && !CheckSRAND(gCurrentTicks, gScenarioSrand0)) {
+                       log_warning("desynced");
                        _desynchronised = true;
                        char str_desync[256];
                        format_string(str_desync, STR_MULTIPLAYER_DESYNC, NULL);
```

**Comment by janisozaur** [comment]
An hour of testing a headless server forced to run with `gGameSpeed = 8` on a busy park with multiple (headless) clients connected and connecting/disconnecting could not cause a desync.

:star2:

**Comment by IntelOrca** [comment]
You'll need to increase the network version.

**Comment by janisozaur** [comment]
Yes, I'm aware. Should I wrap these functions in some sane name or leave it as explicit call to `game_do_command`? None of the clients has permission to trigger that as well, but having inspected where does it get triggered, there should be no need for that.

Anything else I should take care of?

**Comment by duncanspumpkin** [comment]
No think its fine to leave as just a call to game_do_command. You could add a little comment as to why this needs to be done though.

**Comment by janisozaur** [comment]
updated

**Comment by janisozaur** [comment]
@IntelOrca it would be best if #3783 could be merged first, so new clients/servers won't crash with `stack smashing detected`.

**Pull request merged**
