### PR TITLE
Fix 4817- Icon looks blurry on 125% scaling

### PR DESCRIPTION
**Pull request by Nubbie**
This adds the needed 40x40 image to the icon which [Janisozaur pointed out was needed ](https://github.com/OpenRCT2/OpenRCT2/issues/4817#issuecomment-261789219) 

Would be great if @janisozaur tested it out I presume

### CODE REVIEW

**Comment by janisozaur** [comment]
I don't have access to machine I tested it on. I may have at some (probably distant) point in future.

**Comment by janisozaur** [comment]
@Nubbie please optimize this file with `zopfli`/`optipng`/`pngcrush`…

**Comment by Nubbie** [comment]
The 40x40 png is optimized and ~8 kb was saved :tada:

**Comment by IntelOrca** [comment]
@Nubbie what did you use to create the ico and png?

**Comment by Nubbie** [comment]
@IntelOrca I did want to use a program that could do it effectively but not many allowed the 40x40 resolution so I used the most basic - Paint.net with a .ico plug-in

**Comment by IntelOrca** [comment]
And the svg?

**Comment by Nubbie** [comment]
Did use the icon_x64.png to resize it down to icon_x40.png

**Comment by IntelOrca** [comment]
@Nubbie you should have really used inkscape to export the SVG to 40x40 then ran the C# script inside the directory to create the ico.

**Comment by Nubbie** [comment]
Could do it again if needed

**Comment by IntelOrca** [comment]
Merged as 48eb95d1e6981326c40a88b97f84119c3156cb91

**Pull request closed without merging**
