### PR TITLE
Improve financial and park history graphs

### LINKED ISSUE #22396: Guest count graph has misaligned tick marks
### Operating System

Linux

### OpenRCT2 build

OpenRCT2, v0.4.12

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

_No response_

### Describe the issue

Probably related to #22395 

Also note that there is no dark tick before the Y axis gridlines, unlike the finance graph.

image

### Steps to reproduce

Use the guest graph.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by mrmbernardi**
This PR fixes #22396, #22395, and #22307.

I should also be able to make the following improvements:

- [x] Make the graphs resizeable
- [x] Improve the readability of the hover tooltip
- [x] Make the guest count graph display numbers above 5,000
- [x] Improve the algorithm that determines the Y axis labels

I originally wanted to bring the hover tooltips to the park rating and guests in park graphs. However, the values are compressed down to 8 bits and it would require modifying the save format to change this. Since the values aren't even accurate anyway, I also figured there would be no point bringing the resize feature to these graphs either.

This makes `STR_GRAPH_AXIS_LABEL` and `STR_FINANCES_FINANCIAL_GRAPH_CASH_VALUE` obsolete in the string tables.

Things to consider in the future which are now easier with the new code:

- Allowing the user to change the amount of plotted points
- Bringing resizeability and tooltips to the park graphs

### CODE REVIEW

**Comment by mrmbernardi** [comment]
If the review is too big for the milestone, feel free to push it back to after the next verison.

**Comment by AaronVanGeffen** [comment]
> Also please advise on the changelog line as this fixes a few things.

Just because it's one PR doesn't mean you need to put everything on one line. If it addresses multiple distinct issues, please use separate changelog entries as well :)

**Comment by mrmbernardi** [comment]
I added a new y axis label algorithm. It simply increments the leading digit of the max and sets all other digits to zero. E.g. if the maximum value in the plot is 6810, then the graph will be plotted from 0 to 7000 (for a non-centred graph).

**Comment by ZehMatt** [comment]
I think there are a couple of open issues which can probably closed now, also good work.

**Comment by ZehMatt** [comment]
openrct2_2024-08-05_18-39-49cf3a5e67dc65752f6
openrct2_2024-08-05_18-40-280976eb7dbb546369f

There are unfortunately some issues.

**Comment by J-PIE-314** [comment]
Yes, also notice that the negative numbers are above the positive numbers.

**Comment by mrmbernardi** [comment]
Sorted in #22488

**Comment by cheweytoo** [comment]
This has literal overflow issues ;-)

As seen in 9f0125b develop:

fgoverflow


Also, I note a distinct lack of graph.

**Comment by mrmbernardi** [comment]
> This has literal overflow issues ;-)
> 
> As seen in 9f0125b develop:
> 
> fgoverflow
> 
> 
> Also, I note a distinct lack of graph.

Send me the save and I'll fix it ;)

**Comment by cheweytoo** [comment]
Here it is:

[overflowing_millions.zip](https://github.com/user-attachments/files/16506842/overflowing_millions.zip)

**Comment by mrmbernardi** [comment]
@cheweytoo 

Should be fixed in #22498.

I always knew this was possible, but I didn't think people would typically have so much money. The guest graph will also overflow if you have 100,000 guests or more, but I don't think this is likely. I thought the practical guest limit was around 10k, but you seem to have 20k in your park, at least before you deleted the entire park for some reason.

**Comment by cheweytoo** [comment]
> @cheweytoo
> 
> Should be fixed in #22498.

Thanks!

> I thought the practical guest limit was around 10k, but you seem to have 20k in your park

It's stable at about 17.5k thanks to permanent advertising, many ATMs, and lots of entertainers. I should really start a new, larger long-term park now that the various limits are higher – if only to see if a higher soft guest cap would allow to increase this even further.

> at least before you deleted the entire park for some reason.

I usually try to deliver as minimal a test case as possible. Might have gone a bit overboard this time, but using the large scale deletion tools with reckless abandon can be fun too. ;-)

**Pull request merged**
