### PR TITLE
Possible fix low FPS issue on Debug build

### PR DESCRIPTION
**Pull request by wisegoodvin**
I think we need to change default build configuration from Debug to Release

### CODE REVIEW

**Comment by Gymnasiast** [comment]
The main reason to compile the game yourself is to investigate problems - and this requires a debug build. People who want release builds typically get precompiled ones from openrct2.io or openrct2.org

**Comment by wisegoodvin** [comment]
> 
> 
> The main reason to compile the game yourself is to investigate problems - and this requires a debug build. People who want release builds typically get precompiled ones from openrct2.io or openrct2.org

Ok, in `readme.md` in paragraph 2 i doesn't see Windows pre-builds, only *nix

**Comment by Gymnasiast** [comment]
Paragraph 2 contains this sentence:

> [OpenRCT2.org](https://www.openrct2.org/downloads) offers precompiled builds and installers of the latest master and the develop branch. There is also a cross platform Launcher available that will automatically update your build of the game so that you always have the latest version.

**Comment by wisegoodvin** [comment]
Ok, thanks for the clarification.

**Pull request closed without merging**
