### PR TITLE
Implement Train class with iterators

### PR DESCRIPTION
**Pull request by hdpoliveira**
This change creates a Train class with iterators. It also creates a Mass function, replacing the get_train_mass function in Vehicle.cpp

For now this is on a unnamed namespace in Vehicle.cpp, but we may consider extract it to its own file.

### CODE REVIEW

**Comment by IntelOrca** [comment]
I do like this. Is the idea for this to always be a temporary throw-away struct? Do you plan or using this for other pieces of logic and adding more helper methods?

**Comment by hdpoliveira** [comment]
For now the idea is indeed for this to be a throw away struct. I noticed
many methods in Vehicle.cpp and Ride.cpp actually do calculation on the
entire train instead of only in a single Vehicle, so these functions could
become methods in the Train class.
For now I've put the Mass function in there just to illustrate, but this
could later be its own file.

**Comment by duncanspumpkin** [comment]
The first car should always be a train head. Should we have extra protection making sure this is the case during construction.

**Comment by hdpoliveira** [comment]
@duncanspumpkin just adding 
```cpp
            assert(vehicle->TrainHead() == FirstCar);
```
in the constructor is enough? (given https://github.com/OpenRCT2/OpenRCT2/pull/11480 is merged for TrainHead method)

**Comment by duncanspumpkin** [comment]
IsHead is much cheaper to perform.

**Pull request merged**
