### PR TITLE
Use Hiragino Kaku Gothic on macOS

### PR DESCRIPTION
**Pull request by Gymnasiast**
Pinging @AaronVanGeffen to properly scrutinise this PR, seeing as he is our Japanese expert ;).

### CODE REVIEW

**Comment by Gymnasiast** [comment]
I looked further, and saw there are many more varieties of Hiragino. I'm not sure if I picked the correct one here.

**Comment by AaronVanGeffen** [comment]
Hmm, to be honest, I would much rather see this implemented as proper font families to try to load instead.

For example, a `TTFontFamilyJapanese` could consist of at least three alternatives for Windows, macOS, and Linux. The latter could use Noto or DejaVu, or we could set both. We should do something similar for the two Chinese languages as well as Korean, of course.

If you like, I can look into implementing this.

**Comment by Gymnasiast** [comment]
Well, if you feel like that: ga je gang ;)

**Comment by janisozaur** [comment]
がんばって、おにいちゃん！

**Pull request closed without merging**
