### PR TITLE
Use const and constexpr whenever possible.

### PR DESCRIPTION
**Pull request by ZehMatt**
This eliminates a bunch of dynamic initializer routines from MSVC.

### CODE REVIEW

**Comment by janisozaur** [comment]
What about those
```
src/openrct2-ui/CursorData.cpp
src/openrct2/peep/PeepData.cpp
src/openrct2/ride/RideData.cpp
src/openrct2/ride/TrackDataOld.cpp
src/openrct2/ride/VehicleData.cpp
```
?

**Comment by ZehMatt** [comment]
Not everything works with constexpr, I just wanted to get rid of those dynamic initializers. I tried to get rid of the rest but VS doesn't like it.

**Comment by ZehMatt** [comment]
That should do it, also a noteworthy thing: Reduces exactly by 1KB binary size :)

**Comment by janisozaur** [comment]
Really nice. I tested this with GCC7 in `RelWithDebInfo` configuration, here're the results:

`openrct2`:
```
     VM SIZE                         FILE SIZE
 --------------                   --------------
  [ = ]       0 .debug_abbrev     +1.45Ki  +0.2%
   +11%      +7 [Unmapped]           +871   +77%
  [ = ]       0 .strtab              +428  +0.1%
  [ = ]       0 .symtab              +120  +0.0%
  +0.1%     +96 .data.rel.ro          +96  +0.1%
  +0.0%     +96 .rodata               +96  +0.0%
  -0.0%      -2 [1 Others]             -2  -0.0%
  -0.0%      -4 .gnu.hash              -4  -0.0%
  -0.0%      -8 .eh_frame_hdr          -8  -0.0%
  [ = ]       0 .debug_aranges        -16  -0.0%
  -0.0%     -24 .dynsym               -24  -0.0%
  -0.2%     -48 .gcc_except_table     -48  -0.2%
  -0.0%     -73 .dynstr               -73  -0.0%
  -0.0%     -96 .data                 -96  -0.0%
  -0.0%    -144 .eh_frame            -144  -0.0%
  [ = ]       0 .debug_ranges        -304  -0.0%
  [ = ]       0 .debug_line          -450  -0.0%
  -0.0%    -768 .text                -768  -0.0%
  [ = ]       0 .debug_str          -1000  -0.0%
  [ = ]       0 .debug_info       -4.40Ki  -0.0%
  [ = ]       0 .debug_loc        -5.53Ki  -0.1%
  -0.0%    -968 TOTAL             -9.78Ki  -0.0%
```

`openrct2-cli`:
```
     VM SIZE                         FILE SIZE
 --------------                   --------------
   +15%      +7 [Unmapped]           +877   +37%
  [ = ]       0 .debug_abbrev        +834  +0.1%
  [ = ]       0 .strtab              +428  +0.1%
  [ = ]       0 .symtab              +120  +0.0%
  +0.1%     +96 .data.rel.ro          +96  +0.1%
  +0.0%     +96 .rodata               +96  +0.0%
  -0.0%      -2 [1 Others]             -2  -0.0%
  -0.0%      -4 .gnu.hash              -4  -0.0%
  -0.0%      -8 .eh_frame_hdr          -8  -0.0%
  [ = ]       0 .debug_aranges        -16  -0.1%
  -0.0%     -24 .dynsym               -24  -0.0%
  -0.2%     -48 .gcc_except_table     -48  -0.2%
  -0.0%     -73 .dynstr               -73  -0.0%
  -0.1%     -96 .data                 -96  -0.1%
  -0.0%    -144 .eh_frame            -144  -0.0%
  [ = ]       0 .debug_ranges        -304  -0.0%
  [ = ]       0 .debug_line          -450  -0.0%
  -0.0%    -768 .text                -768  -0.0%
  [ = ]       0 .debug_str          -1000  -0.0%
  [ = ]       0 .debug_info       -4.48Ki  -0.0%
  [ = ]       0 .debug_loc        -5.53Ki  -0.1%
  -0.0%    -968 TOTAL             -10.5Ki  -0.0%
```

**Comment by janisozaur** [comment]
Travis is having another outage of mac nodes, so it will take a while until results come back in, but it's proven it can build those `constexpr` with previous commit: https://travis-ci.org/OpenRCT2/OpenRCT2/builds/327785227

**Pull request merged**
