### PR TITLE
Close #12733 : Sorting feature in TrackList window

### LINKED ISSUE #12733: [Enhancement/Feature?] Sorting options for track designs
In the same spirit as #7763 and #10675, it would be nice to be able to sort the list of track designs by things like excitement rating, cost, size, etc.

### PR DESCRIPTION
**Pull request by hjort96**
Been working on this for some time, and I would really appreciate it if someone wants to take a look at this.

This PR would implement sorting for the TrackList window as suggested in issue #12733.
Players would be able to sort the list of TrackDesigns on different types of values.

I'm unsure if it is implemented well or if there's a better way to do it.
Especially the different dropdowns and the function called `SelectDropDown`.

I've tried to test it thoroughly but there might still be some bugs and unwanted behavior.

Also, the reason for only having two commits is that I somehow broke (literally) everything on the previous branch and had to move code to this new one.

### CODE REVIEW

**Comment by karst** [comment]
I noticed this one has been open for extremely long without anyone responding or noticing things on it. I have tested the build and this does seem like a welcome addition to me. I noticed in my dev build it takes quite a bit of time for the items to re-sort items. I don't know if it's possible to optimize this any. In the actual release version this is not a problem. I'll make sure to poke the devs about this to look at it.

**Comment by Gymnasiast** [comment]
> I'm unsure if it is implemented well or if there's a better way to do it.
> Especially the different dropdowns and the function called SelectDropDown.

 Yeah, this indeed needs a lot of work in that area. You also hardcoded a lot of magic numbers for the ride IDs. Instead, you should get the RideTypeDescriptor and determine which items to add to the dropdown based on the flags.

**Comment by Gymnasiast** [comment]
Keep this open please.

**Comment by ZehMatt** [comment]
@hjort96 do you plan to continue working on this?

**Pull request closed without merging**
