### PR TITLE
Failed save game logging

### PR DESCRIPTION
**Pull request by phillipwalters**
Added failed save game logging to help debug https://github.com/OpenRCT2/OpenRCT2/issues/8701.

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
Rebase to remove your merge commits.  You still haven't quite fixed the formatting.

**Comment by Gymnasiast** [comment]
@duncanspumpkin Considering the amount of changes, we can also just squash them.

**Comment by phillipwalters** [comment]
Okay, I'll try and do that. I'm not super well versed in some features of git, so it may take me some time.

**Comment by duncanspumpkin** [comment]
It's okay we will just squash it on merge to avoid the commits. 

If you want to learn though the way to do a rebase is use 'git rebase develop' then you can 'git push <...> <Branch name>'

**Comment by phillipwalters** [comment]
I'm a bit out of my depth with git :X. I'm thinking maybe it'd be best if I cancel this PR and start my fork fresh...

**Pull request closed without merging**
