### PR TITLE
Fix #14312: Research ride type message incorrect

### LINKED ISSUE #14312: Researching a new ride type still appears as new vehicle instead
**OS:** Windows 10
**Version:** 0.3.3
**Commit/Build:** 8acdcca (reported on 3f65f28 release branch)

Even though this issue of researching an actual new ride type instead appearing as a new vehicle in the Research & Development and Recent Messages windows (I previously reported in #13236) was fixed earlier, it doesn't appear that it has been fixed completely.

This issue still persists in some scenarios like Factory Capers (it comes with RCT2 by default), where researching the Giga Coaster wrongly appears as "Giga Coaster Trains for Giga Coaster" as though the game thinks the ride type is available even though the ride type itself isn't actually available yet. From what I remember, I made a scenario called Hyperspeed Heights and while I was creating it, the Spinning Wild Mouse got researched ("New ride/attraction now available: Spinning Wild Mouse") and I moved it back to the "Items to invent during game" section of the invention list, after which it can get researched again, but this time with the message "New vehicle now available for Spinning Wild Mouse: Spinning Mouse Cars". I believe this just might be a problem with some scenarios as I cannot get this issue to appear in many of my recent custom scenarios (I generally have the invention list already set up in the initial creation phase and do not move any pre-invented items to the bottom list).

I can confirm from memory that researching the Giga Coaster in Factory Capers in RCT2 vanilla and RCT Classic will correctly give the "New ride/attraction now available: Giga Coaster" message.

**Steps to reproduce:**
1. Open the scenario Factory Capers
2. Set checked research priorities to "Roller Coasters" only
3. Wait until the Giga Coaster is the next coaster type to be researched
4. It will wrongly show up as "Giga Coaster Trains for Giga Coaster" in the Research & Development window
5. Try doing the same in RCT2 vanilla and RCT Classic, but you will get the correct "New ride/attraction now available: Giga Coaster" message instead once it has been researched

**Screenshots:**
Factory Capers 2021-03-13 17-45-26

### PR DESCRIPTION
**Pull request by rik-smeets**
Resolves #14312. 

In some cases, researching a new ride type appeared as a new vehicle instead. This was caused by research item flags not correctly being copied in specific instances. Since the base ride type is used for comparing if a ride is the first of that type being researched, the equality comparison in the updated if statement should only check that.

### CODE REVIEW

**Comment by SpartanFrederic104** [comment]
Can you make sure the fix works in both .park and .sc6 scenarios?

**Comment by rik-smeets** [comment]
@SpartanFrederic104 I tested it in both types of scenarios, however I wasn't able to reproduce the issue in a .park scenario to begin with since - as you've stated in the issue - it only seems to occur in specific scenarios.

**Comment by tupaschoal** [comment]
I have a vague resemblance of doing a similar fix and discussing with @Gymnasiast , but I'm not sure. Do you remember Michael?

**Comment by Gymnasiast** [comment]
Research is extremely delicate. OP’s reasoning seems sound, but I’d have to check thoroughly.

**Comment by rik-smeets** [comment]
Sure, let me know if there's anything else I can do to help.

**Comment by Gymnasiast** [comment]
Since we just had a release, I’m going to take a punt and merge it. Could you rebase? (Make sure your fix is in the 0.4.3 section).

**Comment by rik-smeets** [comment]
> Since we just had a release, I’m going to take a punt and merge it. Could you rebase? (Make sure your fix is in the 0.4.3 section).

Done, feel free to merge whenever you feel like it.

**Review by Gymnasiast — APPROVED** [review]

**Pull request merged**
