### PR TITLE
Use ColourMapA for looking up the mini preview background colour, fixes #1238

### LINKED ISSUE #1238: Theme fails to change color of this window (the inside part)
scr14

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by IntelOrca** [comment]
https://github.com/OpenRCT2/OpenRCT2/wiki/Commit-Messages

**Comment by marijnvdwerf** [comment]
image

I disagree with the math performed on the palette index of the light window colour. Would be better to save the general colour index itself and look up the lighter/darker colour based on the index.

**Comment by marijnvdwerf** [comment]
image

Subset of colours where `light + 2` isn't the same as `lightest` or `light - 2` isn't the same as `mid_dark`.

**Comment by Gymnasiast** [comment]
@marijnvdwerf I'm looking forward to a PR ;-)

**Pull request merged**
