### PR TITLE
OS X platform

### PR DESCRIPTION
**Pull request by LinusU**
*~~this includes #2017 as well, I will rebase as soon as that one is merged~~ done*

This implements the platform for OS X. Basically it just renames the `linux` platform to be the `unix` one, and stubs out one function, which as far as I can tell didn't work on OS X.

It compiles for me, but because of issues discussed elsewhere it doesn't actually run yet. But I'm confident that we'll get there soon :fireworks: :fireworks: :fireworks:

### CODE REVIEW

**Comment by LinusU** [comment]
Also, I changed the last `__APPLE__` to use the double syntax [as recommended here](http://nadeausoftware.com/articles/2012/01/c_c_tip_how_use_compiler_predefined_macros_detect_operating_system).

**Comment by janisozaur** [comment]
I'd like to take a closer look at that, I may have enough time tomorrow or the day after. One thing I don't like is the file is now named `unix.c`, which is a trademark (well, UNIX is) and it is much more POSIX-specific. That's also the reason why I made the `linux.c` file alongside the already existing `unix.c`. Can we rather have it named `posix.c`?

**Comment by IntelOrca** [comment]
@janisozaur yes

**Comment by LinusU** [comment]
Rebased on latest `develop` and renamed the file to `posix.c` instead of `unix.c` :+1:

**Comment by janisozaur** [comment]
Looks good to me. :+1: for merging.

**Pull request merged**
