### PR TITLE
Fix: [#17472] Active windows modifying the reticle did not close on save, leading to improper reticle behavior on save

### PR DESCRIPTION
**Pull request by jazzysoggy**
Fix https://github.com/OpenRCT2/OpenRCT2/issues/17472
Issue: While the original issue points out that upon saving, the tile inspector would experience improper reticle behavior where the reticle would just disappear and the tool would no longer work, I found through more testing that this behavior applied to loading saves, as well as with the footpath window and ride constructor window.

Current fix:
Add INPUT_FLAG_TOOL_ACTIVE check, and if false the window will clear itself for both Tile Inspector and Ride Constructor.

Note: Had to re-pull as the original was closed due to accidentally deleting the fork.

### CODE REVIEW

**Comment by 733737** [comment]
I don't think this needs to be in the changelog, and also if it is put in the changelog, I think it needs to be reworded as it is currently improper english. However I would like to see this PR addressed, as I am the originator of the issue.

**Comment by Broxzier** [comment]
This seems like a silly workaround for another issue. Why are tools closed in the first place?

**Comment by jazzysoggy** [comment]
> This seems like a silly workaround for another issue. Why are tools closed in the first place?

It seems like the intended effect, as tool_cancel is called when the save windows is called, which then disables the custom reticle. 

Would the more appropriate behavior be for the reticle to be re-enabled after the save window is closed if the tools are still open?

**Comment by Broxzier** [comment]
Why would tools need to be closed while the save window is open? They don't prevent interaction with the save window.

**Comment by jazzysoggy** [comment]
It doesn't interfere with the save window interaction, however it seems like it would be inconsistent behavior for the Tile Inspector tool not to be cleared after the save window opens. 

All the other tools exhibit this behavior, clearing the entire tool once ``INPUT_FLAG_TOOL_ACTIVE`` is set to false. This occurs when the game save or load window is loaded through the usage of ``tool_cancel``.

**Comment by Broxzier** [comment]
You're missing my point, I'm not talking about any specific tool, I'm talking about why any tool should close when the save window opens. That doesn't seem necessary.

**Comment by 733737** [comment]
the tools exhibit irregular behavior when they are left open and you go to use them again

**Comment by ZehMatt** [comment]
> the tools exhibit irregular behavior when they are left open and you go to use them again

Is this a wild guess or did you actually observe such irregular behavior? 

I also agree with @Broxzier here, this is not the correct approach to fix this.

**Comment by 733737** [comment]
Maybe my vagueness is irritating people. When you save game, the tile inspector remains open, but you can no longer select a tile.

**Comment by Broxzier** [comment]
Yes, I understand the problem. The fix should be making sure that the tile inspector (and other tools) are usable after saving, not forcing them to close.

I haven't checked out the code responsible for this, but I suspect that when the game is saving, it deactivates the active tool so it can show the "Zzzzz" mouse cursor, which is a workaround already.

**Comment by 733737** [comment]
is there any reason to preserve the Zzzzz considering that the performance threshold for all devices today makes it all but useless

**Comment by ZehMatt** [comment]
> is there any reason to preserve the Zzzzz cursor, considering that the performance threshold for all devices today makes it all but useless?

Not everyone has a fast computer and OpenRCT2 doesn't run on modern machines only.

**Comment by ocalhoun6** [comment]
> Not everyone has a fast computer and OpenRCT2 doesn't run on modern machines only.

Heck, I've got a monster system with a threadripper, tons of ram, and NVME storage, and I still see the Zzzz cursor occasionally when saving a big park. Maybe it's not all that useful because the cursor doesn't stay that way long enough for me to attempt to do anything while it's like that ... but I really like the visual confirmation that the computer is doing something, which helps me know that the park is indeed saved.

**Comment by Broxzier** [comment]
Closing this, as @jazzysoggy hasn't responded yet. Feel free to reopen this if you want to continue working on this.

**Pull request closed without merging**
