### PR TITLE
Use boost

### PR DESCRIPTION
**Pull request by IntelOrca**
To reduce the amount of platform code and utility we have to maintain / write.

Related: https://github.com/OpenRCT2/Dependencies/pull/16

### CODE REVIEW

**Comment by LRFLEW** [comment]
Before all the Linux devs descend on this and ask why we should add this dependency, I'd like to point out that this is probably a somewhat temporary dependency.

Boost.Filesystem is making its way into the standard. `std::filesystem` is slated for C++17, and it's nearly identical (if not exactly) to the Boost one. Once it's widely available, we can switch over to the STL version with minimal issues. Right now, there's the TS/Experimental version that we can try to support. There are, however, two major issues with that. The first is that the "Experimental" implementations are not always consistent. Some may implement draft versions of the TS with little way to check for that (which can cause unexpected errors). The other is that they aren't consistently available. macOS's Clang doesn't have it at all (experimental or otherwise), so it wouldn't work there at all. VS 2015 and the latest versions of GCC and Clang have it IIRC, but I can't guarantee they all work the same. (And I can't guarantee that all the supported distorts latest versions have a new enough version of the compiler in their package manager.) Boost is able to provide a consistent implementation across platforms, making it a good starting point while we wait for C++17 to be widely available.

In the mean time, it would be possible to support both using namespace aliases and include guards. It might looks something like:

```
#ifdef USE_EXPERIMENTAL_FILESYSTEM
#include <experimental/filesystem>
namespace filesystem = std::experimental::filesystem;
#else
#include <boost/filesystem.hpp>
namespace filesystem = boost::filesystem;
#endif

// You can then use it like this
filesystem::path some_path;
```

**Comment by chfast** [comment]
If you want, I can get you a CMake script that downloads and compiles boost using ExternalProject module. Like here: https://github.com/ethereum/cpp-dependencies/blob/master/boost.cmake.

**Comment by janisozaur** [comment]
I think boost comes pre-packaged for all of our distros, so there's little need to compile it every time. I'd much rather use distribution-provided one, it also eases distribution later on.

**Comment by chfast** [comment]
Ok, but you will have different versions of dependent shared libs on different distributions.

**Comment by Gymnasiast** [comment]
We already have that for all other dependencies.

**Comment by Manuel-K** [comment]
> We already have that for all other dependencies.

Yes, but most other libraries have an api that is considerably more stable. Boost changes it's soname at least twice a year. https://abi-laboratory.pro/tracker/timeline/boost/

**Comment by janisozaur** [comment]
I don't see how this affects us. We will be using packaged version on travis and that's pretty much it… Every package maintainer can take whatever version of boost they want. Even in presence of soname changes, which are expected of boost really, we will likely be using mostly filesystem v3, which we then will move on to C++17 once that is released and supported. [FSv3 has been supported since 1.44 released in June 2010](http://www.boost.org/doc/libs/1_63_0/libs/filesystem/doc/index.htm) and it should stay [API-compatible with v4](http://www.boost.org/doc/libs/1_63_0/libs/filesystem/doc/index.htm):

> Most user code written for Version 3 should work unchanged with Version 4.

You also seem to be confusing API and ABI.

I really miss your point.

**Comment by Manuel-K** [comment]
I'm not confusing ABI and API, but you are right, I should have written API and ABI.

The point is that you cannot depend on system wide installations of boost if you want to provide binary packages, which is a huge hassle.

**Comment by janisozaur** [comment]
@Manuel-K we only deploy binaries built on travis inside docker with ubuntu 16.04, these should cover large enough amount of users – and I don't even run ubuntu myself, so I don't even care that much. It will stay ABI-compatible for long enough for us, which is until we move travis to a newer base. We had already faced that with libzip, libpng is incoming and I think there were more in the past.

OpenRCT2 should be packaged in distro-specific repos, there already are a few: https://github.com/OpenRCT2/OpenRCT2#2-downloading-the-game-pre-built otherwise people should roll their own.

As far as I'm concerned, you should be using https://aur.archlinux.org/packages/openrct2-git 

All that said I still miss your point – or perhaps you're missing mine: I don't care, as long as you and maintainers can compile, all is fine.

**Comment by Manuel-K** [comment]
@janisozaur Okay, I don't care as well. I don't use the binaries and I generally do not use the aur. Why should I?

**Comment by IntelOrca** [comment]
As of VS2017, this is no longer required as `string_view` and `filesystem` are available as part of C++17.

**Pull request closed without merging**
