### PR TITLE
Fix #4318: Use user locale on macOS

### LINKED ISSUE #4318: macOS ignores system locale for default options
**OS:** macOS
**Commit/Build:** 676c734f4c70c446c020b9015abdae791de4fc3b

`lc->int_curr_symbol` always appears to be empty

### PR DESCRIPTION
**Pull request by marijnvdwerf**

### CODE REVIEW

**Comment by marijnvdwerf** [comment]
Update: language isn't honored either

**Comment by LRFLEW** [comment]
@marijnvdwerf Just a heads up on this, when working with a wrapper API for the Objective-C stuff, I found that for the US english localization, it was giving me `EN` instead of `EN-US`. We should make sure that it doesn't assign American English speakers British English before this gets merged.

**Comment by marijnvdwerf** [comment]
@LRFLEW As of now that's accounted for

**Comment by LRFLEW** [comment]
:+1:, though I don't know if the en-UK locale can report itself as `en` either (which, in that case, appending the locale's country code might be the best solution).

**Comment by marijnvdwerf** [comment]
@LRFLEW I'm only seeing it as `en-GB`

**Comment by LRFLEW** [comment]
Ok then. :+1: for merging

**Pull request merged**
