### PR TITLE
Allow forcing guest energy to 0

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
The guest update code keeps guest energy balanced between a set min and max constant. Unlike staff, this makes it impossible to 'force' guests through the script API. This PR is an attempt to make it possible to allow scripts to force guest energy to 0 as well.

@Manticore-007, could you test this out?

### CODE REVIEW

**Comment by Manticore-007** [comment]
We justed on both ends and the guests are staying frozen. The animations are getting updated so when a guest is frozen for a while it will let his head down. That update should be blocked when a guest's energy is set to 0.

**Comment by Basssiiie** [comment]
I mentioned a list of things that were required to for a proper freeze on the [original PR](https://github.com/OpenRCT2/OpenRCT2/pull/21714#issuecomment-2041553242) that started this all:

> They get a flag that can freeze stats, which means;
>  - Food items don't decay.
>  - They don't get lost or want to go home.
>  - They don't contribute to the park rating.
>  - When their energy is set to 0, they won't regain energy.
>  - When they do have a non-zero energy, they can still walk around like they could do before (as if they're entertainers) and won't interact with any rides/stalls/park entrances.

**Comment by AaronVanGeffen** [comment]
Thanks for weighing in, @Basssiiie.

> * Food items don't decay.
> * They don't get lost or want to go home.
> * They don't contribute to the park rating.
> * When their energy is set to 0, they won't regain energy.

This is the case as of the latest commit.

> And as @Manticore-007 mentions, the peep sprite should not update to reflect its low energy.

This has yet to be done. I need to find out what's causing it to update the sprite, even if `Tick128UpdateGuest` and `Update` are skipped.

> * When they do have a non-zero energy, they can still walk around like they could do before (as if they're entertainers) and won't interact with any rides/stalls/park entrances.

This requires an additional flag, which is outside the scope for this PR.

**Comment by ZehMatt** [comment]
I'm not really a fan of abusing the energy value like that, we should just have a flag that freezes the movement/animations. We can automatically add the flag during import for staff. This also avoids messing with the general state of guests, with the flag you can pause/resume them properly.

**Comment by AaronVanGeffen** [comment]
Thanks for your input, @ZehMatt.

> I'm not really a fan of abusing the energy value like that

Honestly, I'm inclined to agree. My first patch was just three lines, but it's already grown quite a bit, and still doesn't fully work as intended.

> We should just have a flag that freezes the movement/animations. We can automatically add the flag during import for staff. This also avoids messing with the general state of guests, with the flag you can pause/resume them properly.

I think that would be better, yes. Perhaps we should add two flags instead: one to freeze movement, and one to freeze animations. We can set the flag for staff with zero energy automatically on import, as you suggest, and then reset their energy to the base energy.

That means I probably won't continue with this PR as-is, though.

**Comment by ZehMatt** [comment]
> Thanks for your input, @ZehMatt.
> 
> > I'm not really a fan of abusing the energy value like that
> 
> Honestly, I'm inclined to agree. My first patch was just three lines, but it's already grown quite a bit, and still doesn't fully work as intended.
> 
> > We should just have a flag that freezes the movement/animations. We can automatically add the flag during import for staff. This also avoids messing with the general state of guests, with the flag you can pause/resume them properly.
> 
> I think that would be better, yes. Perhaps we should add two flags instead: one to freeze movement, and one to freeze animations. We can set the flag for staff with zero energy automatically on import, as you suggest, and then reset their energy to the base energy.
> 
> That means I probably won't continue with this PR as-is, though.

I agree with the animation and movement being separate flags. You could just rewrite this PR branch with the flags but yeah unfortunately its going to be a make over.

**Comment by AaronVanGeffen** [comment]
> You could just rewrite this PR branch with the flags but yeah unfortunately its going to be a make over.

Yeah, normally I would, but I realised I probably won't have time to finish it before my vacation. If someone else would like to pick it up in the mean time, that's fine by me. Otherwise, I'll happily pick it up after, most likely in July.

**Pull request closed without merging**
