### PR TITLE
Add build_nonet to .gitignore

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by IntelOrca** [comment]
err, if we are going to have all sort of build configurations, we should probably just ignore build_* rather than specific ones.

**Comment by Gymnasiast** [comment]
Well, I'm not sure why it builds both the regular and the _nonet build anyway. It has been doing that since the recent commit that allowed disabling network at compile time, which I consider a bug. (Not that a find disabling network useful, even for testing, but that's another thing.)

**Comment by IntelOrca** [comment]
That seems odd to me, you should specify what build you want, and if not specified - the default should be release. Do you want to change that as well?

**Comment by Gymnasiast** [comment]
I want to, but I'm not sure I can. (It's odd janisozaur didn't notice it, since he introduced it.)

**Comment by Gymnasiast** [comment]
This seems to work.

**Pull request merged**
