### PR TITLE
Small linux fixes

### PR DESCRIPTION
**Pull request by zsilencer**
Although the SDL_WarpMouseInWindow doesn't seem to work very well in linux.

### CODE REVIEW

**Comment by janisozaur** [comment]
I'd like to test these changes before they go in.
I certainly don't like `data` (the path) not being updated in all places, there's at least `data/g1.dat` just above the start of your changes, I think there may be more places to check.

**Comment by zsilencer** [comment]
The g1.dat is put in the data directory created by openrct and is lowercase, the other uppercase Data directory is in the retail install location.

**Comment by zsilencer** [comment]
yeah let me fix it

**Comment by IntelOrca** [comment]
Can we instead make the data directory path a constant so there is only one instance to change, perhaps do it in a similar way to how we do user directory files.

**Pull request closed without merging**
