### PR TITLE
cmake for packaging and release

### PR DESCRIPTION
**Pull request by janisozaur**
Changes to cmake that allow installation and subsequently packaging of OpenRCT2.

Takes care of #2190.

- [x] make cmake-generated project installable with `make install`
- [x] make sure `g2.dat` is built when doing `make` step.
  - [x] check if `g2.dat` is built properly, as it doesn't look quite right now
- [x] add launcher script that changes directory on behalf of user, so `openrct2` (the binary) can find `openrct2.exe` and other files
- [ ] create a menu entry for desktop environments.
  - [ ] make sure the entry has our icon
- [ ] add a step packaging all artifacts into an archive
- [x] ~~add certificate bundle and make a note that user can replace it with their system one~~ openrct2 uses system certificates on linux, see #2389 

I made travis more verbose for this pull request, so you can easily see what does the project structure look like after it was installed. Before this is merged, I will remove this commit so it be merged cleanly.

I'd like to request your comments now.

So far the proposed contents of a release package look like this (taken from https://travis-ci.org/janisozaur/OpenRCT2/jobs/90907970):
```
package
├── [drwxrwxr-x 4.0K]  bin/
│   └── [-rwxr-xr-x   95]  openrct2.sh*
└── [drwxrwxr-x 4.0K]  data/
    ├── [drwxr-xr-x 4.0K]  data/
    │   ├── [drwxr-xr-x 4.0K]  language/
    │   │   ├── [-rw-r--r-- 151K]  chinese_simplified.txt
    │   │   ├── [-rw-r--r-- 157K]  chinese_traditional.txt
    │   │   ├── [-rw-r--r-- 221K]  dutch.txt
    │   │   ├── [-rw-r--r-- 155K]  english_uk.txt
    │   │   ├── [-rw-r--r-- 155K]  english_us.txt
    │   │   ├── [-rw-r--r-- 160K]  finnish.txt
    │   │   ├── [-rw-r--r-- 158K]  french.txt
    │   │   ├── [-rw-r--r-- 166K]  german.txt
    │   │   ├── [-rw-r--r-- 139K]  hungarian.txt
    │   │   ├── [-rw-r--r-- 151K]  italian.txt
    │   │   ├── [-rw-r--r-- 174K]  korean.txt
    │   │   ├── [-rw-r--r-- 142K]  polish.txt
    │   │   ├── [-rw-r--r-- 161K]  portuguese_br.txt
    │   │   ├── [-rw-r--r-- 142K]  russian.txt
    │   │   ├── [-rw-r--r-- 139K]  spanish_sp.txt
    │   │   └── [-rw-r--r-- 140K]  swedish.txt
    │   └── [drwxr-xr-x 4.0K]  title/
    │       ├── [drwxr-xr-x 4.0K]  openrct2/
    │       │   ├── [-rw-r--r-- 1.9M]  achilleshiel.sv6
    │       │   ├── [-rw-r--r-- 2.3M]  faas.sv6
    │       │   ├── [-rw-r--r-- 1.1M]  mci.sv6
    │       │   ├── [-rw-r--r-- 1.4M]  pfckrutonium1.sv6
    │       │   ├── [-rw-r--r-- 1.6M]  pfckrutonium2.sv6
    │       │   ├── [-rw-r--r-- 1.5M]  poke.sv6
    │       │   ├── [-rw-r--r-- 540K]  rid6.sv6
    │       │   ├── [-rw-r--r-- 1.3K]  script.txt
    │       │   ├── [-rw-r--r-- 1010K]  shotguns.sv6
    │       │   └── [-rw-r--r-- 3.1M]  triggerdeath.sv6
    │       └── [drwxr-xr-x 4.0K]  rct2/
    │           └── [-rw-r--r--  306]  script.txt
    ├── [-rw-r--r--  40K]  g2.dat
    ├── [-rwxr-xr-x 6.1M]  openrct2*
    └── [-rw-r--r-- 6.4M]  openrct2.exe
```

This is based on Graham Edgecombe's [AUR PKGBUILD](https://aur.archlinux.org/cgit/aur.git/?h=openrct2-git)

### CODE REVIEW

**Comment by IntelOrca** [comment]
Perhaps we could add a checksum for g2.dat to the repo for CI to confirm correct build of it.

**Comment by janisozaur** [comment]
I rebased this on top of branch `fixes` (https://github.com/OpenRCT2/OpenRCT2/pull/2291) so that g2 can be checked now that it should work

**Comment by janisozaur** [comment]
Improper `g2.dat` build was caused by me using wrong command to create – I've forgotten to include part of the path. sha256sum:
```
7725027dad25a3176311569f121a975e00787c65368e46443fc7050a94e3e16c  g2.dat
```

It will likely be different than the one built on windows due to different path being followed (see https://github.com/OpenRCT2/OpenRCT2/commit/6723f51087b78078fbb4d62d73de549743f64616) but I just tested on my local machine with `g2.dat` extracted from travis and it works fine, with the expected logo showing up correctly.

**Comment by IntelOrca** [comment]
g2.dat should have the same checksum on all platforms.

**Comment by janisozaur** [comment]
ok, but it will require a few other commits to go in first:
- [ ] update lodepng
- [ ] fix `gfx_invalidate_screen`

**Comment by janisozaur** [comment]
I fixed the g2 problem in #2299 and rebased this branch on top of it.

**Comment by duncanspumpkin** [comment]
So is this ready for merging now?

**Comment by IntelOrca** [comment]
Looks like there is still:

- [ ] create a menu entry for desktop environments.
  - [ ] make sure the entry has our icon
- [ ] add a step packaging all artifacts into an archive

to do.

**Comment by duncanspumpkin** [comment]
@janisozaur do you think you will be able to complete this by the end of the weekend? I want this in 0.0.3 but I also want that out next week.

**Comment by janisozaur** [comment]
Unfortunately, no. I'm swamped with other work and had to reduce my contributions to the project lately, but I can take time to create a zipped release manually. Is that ok?

Also, semi–related, I'm working on getting PPA (the *de facto* repository with deb packages for ubuntu & debian) running, this won't be ready in time for 0.0.3 either, but at some point in future.

**Comment by duncanspumpkin** [comment]
Okay that will be fine. We did a zip release for the windows version last time so can just add another zip file.

**Comment by janisozaur** [comment]
I also found out that for master server functionality to work, the certificate bundle is required, I updated the main description accordingly.

**Comment by Gymnasiast** [comment]
Creating a menu entry is no problem for me, the icon isn't either. It's just a matter of putting the first in /usr/share/applications and the latter in /usr/share/icons, then the desktop environment will show it its menus automatically. I can create the entry for you if you want, but I'm going to finish the new title sequence first.

**Comment by Thaodan** [comment]
To remove the need of a launcher script you could set exepath in https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2.c#L510 to $libdir/openrct2.exe under a posix os. When running Windows this isn't a problem but for a posix os like linux this creates the need of a launcher and makes the need of saving the pe exe in the same dir of the architecture independent data.

**Comment by janisozaur** [comment]
A few things changed since I started this PR.
* We can now use system-provided certificates on Linux, so there's no need for bundling `ca-certs-bundle`. See #2389 
* `g2.dat` has become a target within cmake, so we can manage it somewhat more properly. See #2474 
* `openrct2.exe` has stopped being a runtime dependence, but rather a compile time, this simplifies packaging a bit at a cost of file size. See #2503 

The last offending bit I can think of now is lack of ability to move `data/` directory away from being in the same directory as executable.

**Comment by IntelOrca** [comment]
@janisozaur how do you suggest it find's data? Working directory? Environment variable?

**Comment by janisozaur** [comment]
We are looking for `./data/` already, which I assume is what you meant by "working directory".
Environment variable would be too hidden in my opinion, and usually you provide default values (e.g. system-wide) with env variables, but cmdline options take precedence.

To search for RCT2 assets there's a hardcoded list of paths somewhere, I was thinking a mix of expected locations + cmdline arg?

**Comment by IntelOrca** [comment]
On Windows it checks executable directory, in case you run it via command line in a different directory.

**Comment by pizza2004** [comment]
On OS X the standard practice with an App Bundle would be to have the executable in Contents/MacOS and data files in Contents/Resources, so it would be good to allow some variance to the location of the data folder.

**Comment by janisozaur** [comment]
Over time this PR got split into pieces, reworked and merged in. As of 3ba9ec8 (#2542) it is possible to use `make install` or `make package` and openrct should work just fine. The only missing thing is probably the icon, which will come at some point in future.

**Pull request closed without merging**
