### PR TITLE
Fix pause and build path hotkeys not working when the toolbar is hidden.

### PR DESCRIPTION
**Pull request by Harry-Hopkinson**
Fix for https://github.com/OpenRCT2/OpenRCT2/issues/21175

- [x] Pausing game
- [x] Build pathways

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Scenery window stuff appears to reside here: https://github.com/OpenRCT2/OpenRCT2/blob/36352d02f0fd7a0af82b5c2858b127b5667dfed3/src/openrct2-ui/input/Shortcuts.cpp#L239-L244

**Comment by Harry-Hopkinson** [comment]
Thanks for showing where the scenery window shortcut resides. I have tried to following:

```cpp
static void ShortcutBuildScenery()
{
    if (gScreenFlags & SCREEN_FLAGS_TITLE_DEMO)
        return;

    if (!(gScreenFlags & SCREEN_FLAGS_SCENARIO_EDITOR) || gEditorStep == EditorStep::LandscapeEditor)
    {
        if (!(gScreenFlags & (SCREEN_FLAGS_TRACK_DESIGNER | SCREEN_FLAGS_TRACK_MANAGER)))
        {
            ContextOpenWindow(WindowClass::Scenery);
        }
    }
}
```

However, the scenery window does not appear but the window opening sound plays. Is there something stopping the scenery window being displayed when called this way?

**Comment by Gymnasiast** [comment]
They are not the same. The latter just opens the Scenery window, the former selects the scenery picker, which is a specific button in that window.

I’d like to get this PR to a mergeable state, though. You can remove the scenery-related stuff and save them for another time, so we can get the other two fixes in.

**Comment by Harry-Hopkinson** [comment]
It should only have changes related to the Pause and Build Path hotkeys now.

**Review by Gymnasiast — APPROVED** [review]

**Comment by Gymnasiast** [comment]
Tested it, seems to work correctly.

**Review by ZehMatt — APPROVED** [review]

**Pull request merged**
