### PR TITLE
Fix #2754: Dragging scrollview fails when scaled

### LINKED ISSUE #2754: Dragging scrollview fails when scaled
When Window scale is set to something other than 1, right-click dragging on scrollviews (like the guest list) stops working.

### PR DESCRIPTION
**Pull request by Wirlie**
#2754

### CODE REVIEW

**Comment by LinusU** [comment]
Would `float rounding = gConfigGeneral.window_scale / 2;` work even better?

**Comment by Wirlie** [comment]
I tried it but in some cases the scrollview is draged in a incorrect way. I think that this variable should not be called `rounding`.

Unfortunately, the method to set the cursor position only can accept int values and for this reason I converted the float value `(gInputDragLastX * gConfigGeneral.window_scale)` into an int value...
I'm not sure what is the reason of for example, if the scale is major than 1 then +1 should be added to `setCursorPositionX` and `setCursorPositionY` to work in a appropriate way, or, if the scale is minor than 1 then +0.5 should be added... probably this has to do with the conversion: float to int value.

If anyone have a best solution for this please let me know, I'm a newbie C programmer xP

**Comment by LinusU** [comment]
Hmm, actually casting a float to an integer will truncate the value. Maybe you could `roundf` the value before casting to integer, then you possibly wouldn't have to use the rounding variable at all...

**Comment by Wirlie** [comment]
Humm.. I used `roundf` instead of the `rounding` variable:
```C#
	int setCursorPositionX = (int) roundf(gInputDragLastX * gConfigGeneral.window_scale);
	int setCursorPositionY = (int) roundf(gInputDragLastY * gConfigGeneral.window_scale);
```
but this only seem to works with all scales that end with `.50` and `.00`, if the scale ends with `.25` or `.75` then the scrollview is dragged incorrectly in some cases. I'll try to find the cause of this.

**Comment by mrtnptrs** [comment]
Do you also consider that it is possible to change the scaling value to something like 1.431, 2.523  or 0.785 by editing the value directly in the config file? Does this pull request work with those kind of values too?

**Comment by Wirlie** [comment]
I not tried this, but I guess it should work. Can you test this? I don't have my PC right now.

**Comment by Wirlie** [comment]
@mrtnptrs okay, it seems that not work with some scales, I'll try to find the correct solution :v

**Comment by mrtnptrs** [comment]
Sorry, I saw your comment from one hour ago too late

**Comment by janisozaur** [comment]
You can set custom values in runtime with `set window_scale 1.234`, with 0.5 being lower bound

**Comment by Wirlie** [comment]
Eureka! I tested my new changes and this seem to work with any scale.
Can anyone test my changes? Thanks.

**Comment by Wirlie** [comment]
Sorry for my last comment (I was wrong), now I am sure that this works with any scale :)

**Comment by mrtnptrs** [comment]
I tested it using various scaling factors like 2.134, 0.531 etc. and it seems to work great. If it is codewise ok, then it can be merged.

**Pull request merged**
