### PR TITLE
Expand tabs to spaces

### PR DESCRIPTION
**Pull request by janisozaur**
This commit expands tabs to spaces (ts=4) in all the files under src/.

Until now we had two wildly different code styles with C using tabs and
new C++ using spaces. It is painful to maintain as none of the commonly
used tools support this kind of setup and in reality is needless, as we
can simply convert all the sources to spaces and have opened PRs do the
same, where needed.

Additionally, trailing whitespace has been removed.

### CODE REVIEW

**Comment by janisozaur** [comment]
GitHub's hidden ignore whitespaces option should show 0 diff:

https://github.com/OpenRCT2/OpenRCT2/pull/5561/files?w=1

**Comment by IntelOrca** [comment]
Could we add a script that is called by Travis to check for tabs?

**Comment by janisozaur** [comment]
@IntelOrca sounds doable, but I'd rather do this as another PR

**Comment by IntelOrca** [comment]
Perhaps we can use this:
https://docs.codeclimate.com/docs/grep

**Comment by janisozaur** [comment]
Rebased on top of #5557 expected to be merged soon.

**Pull request merged**
