### PR TITLE
Add Cycle Detection to Ride Rating Calculation

### PR DESCRIPTION
**Pull request by bitman2049**
Hacked rides no longer block the ride rating calculation function.

Issue link: https://github.com/OpenRCT2/OpenRCT2/issues/10508

### CODE REVIEW

**Comment by ZehMatt** [comment]
I dislike the idea of influencing the game state upon player connect/disconnect, the main reason for this is that the more components we need to synchronize the harder it becomes to maintain the already complex multiplayer aspect, given that peeps will have different decisions on what to ride based on the ride rating it would be also required to match the synchronization tick perfect as in, the simulation requires the exact same data at a specific tick/mid-tick for every client. Maybe @IntelOrca has some thoughts on this.

**Comment by IntelOrca** [comment]
Well the only other thing that can be done is to add it to the end of the map stream that is sent alongside other things like cheats.

**Comment by bitman2049** [comment]
> Well the only other thing that can be done is to add it to the end of the map stream that is sent alongside other things like cheats.

I think this is a better option. The struct would be an additional 8 bytes of info sent to joining players, and once it's initialized it should update the same for all players.

**Comment by duncanspumpkin** [comment]
Surely this doesn't need additional information. Why can't the algorithm just know to skip the bad rides.

**Comment by IntelOrca** [comment]
@duncanspumpkin it needs more state to work out that the ride is bad. The discussion is about synchronising that state across all clients in network games.

**Comment by duncanspumpkin** [comment]
But why does it need more state.

**Comment by bitman2049** [comment]
The state is the slower iterator for the tortoise and hare algorithm. The "bad" rides can switch from bad to good in a single game tick if you use the tile inspector to break the loop, so it can't just skip checking those rides.

**Comment by duncanspumpkin** [comment]
But cant we just do a quick check of the ride to see if it will encounter this issue (i.e. tortoise and hare each ride on every update) rather than keeping a tortoise and hare of the ride ratings. That way it avoids the additional state.

**Comment by IntelOrca** [comment]
Isn't that expensive? You could do the whole ride update in 1 tick if you wanted but presumebly it is spread over multiple ticks to avoid slowing down the game in heavy parks.

**Comment by duncanspumpkin** [comment]
I think the slow bit is the calculation of the bonuses near a ride piece. You don't need to do that calculation just do the look for loops.

**Comment by bitman2049** [comment]
But that's the calculation that kept getting stuck in cycles. If it only checked when switching from one ride to the next, then games loaded with the calculator stuck in a loop would still have it stuck. This makes the check happen while traversing the track for prox bonuses, so it also fixes it when loading from a saved game.

Additionally, this fix doesn't just skip to the next ride when it detects a cycle. It treats a cycle the same way the end of track is treated in non-circuit tracks. It does result in double-counting some elements for proximity bonuses, but it also means that coasters like [this](https://imgur.com/uvNAFyp) can be tested and ridden by guests.

**Comment by duncanspumpkin** [comment]
The ratings calc keeps track of where on the track it is in calculating bonuses. This is the part you have added a second pointer that is a tortoise. From my understanding the expensive bit of the rating calc is checking for proximity bonuses next to this track piece.

What I suggest we do is have a loop checker that runs every tic update. It would not perform the expensive proximity bonus checks. This would inform you that the track has a loop. It could even return a pointer to where the tortoise and hare had failed. You could then calculate bonuses upto that loop failure pointer and count that as the end of the track (like a non-circuited track).

Would that work? I think it might, then it wouldn't involve anything complex with adding more state. There would be a minor performance hit but I doubt that would be noticeable. Should be checked on a ride with very long track.

**Comment by bitman2049** [comment]
That could work, I'd need to try it out. I'm not as experienced with the performance of a raw traversal, but I know the game does it whenever you test the track or go into construction. For really huge coasters (like edge cases, i.e. LordMarcel's record breakers), does that traversal cause lag?

**Comment by duncanspumpkin** [comment]
Its hard to say without testing. Its never going to be free to do but I don't imagine it will be much worse.

**Comment by bitman2049** [comment]
Are there perf tests? Or a ticket for making them? I'd be willing to jump in and make some if they're needed/wanted.

**Comment by duncanspumpkin** [comment]
We have a benchmark command @ZehMatt would know more about it than me.

**Comment by ZehMatt** [comment]
Unfortunately it only benchmarks drawing, there is currently no benchmark for the simulation.

**Comment by AaronVanGeffen** [comment]
For what it's worth, #10281 comes to mind.

**Comment by bitman2049** [comment]
Messed my forks up on github. I'll get back to this issue later.

**Comment by Gymnasiast** [comment]
@bitman2049 Make sure you create a separate branch for your feature and don't push to your develop branch again. That tends to cause headaches.

**Comment by bitman2049** [comment]
Yeah, thank you. I'm taking this as a learning experience. I didn't lose my changes, they're just on another branch now. And they're not ready for merge, I still need to do some testing.

**Pull request closed without merging**
