### PR TITLE
Readd algorithm header where it is used

### PR DESCRIPTION
**Pull request by duncanspumpkin**
~~Project fails to compile on latest versions of MSVC std library without including algorithm.~~ Looks like the reason ci doesn't have this issue is due to the ci using a PCH that includes algorithm. Likely something was assuming it was included transitively.

### CODE REVIEW

**Review by spacek531 — APPROVED** [review]
My game builds now. Visual Studios Community 2022

**Comment by spacek531** [comment]
```ERROR[D:\Documents\GitHub\OpenRCT2\src\openrct2-ui\windows\Changelog.cpp:285 (OpenRCT2::Ui::Windows::ChangelogWindow::ReadFile)]: Unable to read text file```

I get this error and my game doesn't start

**Comment by janisozaur** [comment]
How come it compiles in CI then? I'd like to have CI reproduce this issue so we can avoid any regressions

**Review by Gymnasiast — APPROVED** [review]

**Comment by AaronVanGeffen** [comment]
I'm guessing this is for older versions of MSVC?

**Comment by AaronVanGeffen** [comment]
Can we upgrade our CI to the latest version of MsVC as well?

**Comment by duncanspumpkin** [comment]
> Can we upgrade our CI to the latest version of MsVC as well?

we already use the windows-latest image so think we just need to wait for github to update.

**Comment by duncanspumpkin** [comment]
It might also be a PCH issue. The ci has PCH turned on but my local builds do not. If algorithm is in one of those pch headers then you wont see the issue on the CI.

**Comment by janisozaur** [comment]
I'm ok with this, PCH should stay in CI, I don't plan any more include cleanups for now - when such refactoring somes, we should remember to test with PCH off or wait until someone complains.

**Comment by janisozaur** [comment]
I wonder if we can remove anything from PCH now

**Pull request merged**
