### PR TITLE
Adding Chinese Currencies, Solve #2403

### PR DESCRIPTION
**Pull request by daihakken**
Sorry for spamming the commits, as I edited the files via github.com

### CODE REVIEW

**Comment by LRFLEW** [comment]
You should also update `_currencyEnum` in `config.c`

**Comment by daihakken** [comment]
@LRFLEW thank you so much, it should be perfect right now :P

**Comment by Gymnasiast** [comment]
I think the amount of built-in currencies is getting way too high. I already said I wanted a feature to define ones own currency instead of piling on extra built-in ones.

**Comment by gdabi** [comment]
I would like to implement the custom currency, but I don't know really how to do that.

It's clear to see that will be necessary to implement:
 · The custom currency in currency.c
 · A currency customization window in window.c
 · The config file entries in config.c

But I'm pretty sure there's a lot of "wiring" code that I'm forgotting to include. How do you guys know how to make this things work?

**Comment by daihakken** [comment]
@Gymnasiast while adding Czech and Russian Currencies were acceptable, adding extra 3 Chinese currenies is "getting way too high"? no offense but I am offended by that.

**Comment by PFCKrutonium** [comment]
I think he means that currencies in general is just getting to be too much. If we just implemented "Make your own Currency" it would be better. No need to be offended.

**Comment by daihakken** [comment]
It's more annoying when he just assigned every subtle request that I raised, but did not touch them until someone did that (#2802). Talking about  "Making your own Currency", I don't think it will finish within a short time, like a day. Adding built-in currencies is the quickest (but not dirty) way to do so.

**Comment by IntelOrca** [comment]
The problem is, how do we decide which currencies are built in and which ones require custom? Why should some currencies get to be "built in" whilst others have to be added manually?

**Comment by PFCKrutonium** [comment]
Perhaps when we switch to Custom Currency, we drop all the currencies and make the default BitCoin?

**Comment by danielsarsi** [comment]
I kinda like the idea of a custom currency.
Or maybe just add many currencies possible in one batch.

**Comment by LRFLEW** [comment]
Maybe we should handle it more like how we handle languages. We could have a currency.txt (or JSON) next to the language files that contain the name, symbol, and code for each currency, allowing us to add/edit it without any code changes.

**Comment by carlu93** [comment]
It's great to see how much attention this one gets. IMHO I don't care at all. It's a matter of realism, I know, but I'm on the same page as @PFCKrutonium and @danielsarsi...

**Comment by danielsarsi** [comment]
+1 for @LRFLEW approach

Maybe we can link currency to translation? Each translation could have their own currencies.

English >> USD, CAD & AUD
Portuguese (Brazil) >> BRL

**Comment by Gymnasiast** [comment]
I think it's a bit strange you get offended, considering everything I said here I said earlier. It was actually the addition of the rouble, koruna and won that made it clear the currency dropdown would get too full, which is why I assigned all those bugs to myself: I did it in order to find a good way of handling more currencies without stuffing the currency dropdown.

_A_ solution (derived from @danielsarsi 's comment) might be for a translation to have _suggested_ currencies in the dropdown, but then we'd need a way to select more. Possibly just an entry called _Other_... or _Custom..._ that opens a window where the user can select other currencies and/or define their own.

**Comment by daihakken** [comment]
@LRFLEW did make a good point and very nice to improve user experience. But then, I think Chinese Currencies deserve places in built-in currencies.
and btw, reading the currencies additions in bullet points:

- Korean: OK, go ahead
- Czech: OK, go ahead
- Chinese: NO, wait for the new currency system

Does it logically make sense? no, and it did somehow discriminate people like me (I didn't get irritated but annoyed). Language dropdown has already stuffed and I don't understand why adding 3 currencies will be a problem.

image
image

**Comment by Gymnasiast** [comment]
Look, if you refuse to read what I write this discussion is not going to get anywhere. I have said - two times before - those currencies happened to be PR'ed earlier. You would never have complained if the Chinese currencies had been approved earlier and I would have objected to the won, rouble or koruna getting in. 

I also don't like being accused of discriminating; that's simply ludicrous. I have _always_ conducted discussions on a technical basis and I refuse to conduct one based on you pulling the discrimination card and changing this into a personal attack. Saying you're offended and then doing an ad hominem and falsely accusing me of discrimination is not something that goes down well with me. _I_ would have been offended by this were it not for the fact I'm used to much worse. But not from you, as you stayed very polite until now. That's disappointing.

Now cut this personal attack out please, I have no desire to send people away, and that includes you. You did good translation work, but that doesn't mean you have more chance of getting your PRs committed. (Neither have mine, in fact.)

**Comment by danielsarsi** [comment]
Let's try to reach an agreement here.
Technically, what kind of problems arise by adding more currencies in this current state?

**Comment by PFCKrutonium** [comment]
Well, lots of currencies, and potentially people seeing favoritism where none exists, plus it takes work to add a currency as it is.

**Comment by Gymnasiast** [comment]
@danielsarsi : I already expressed a plan to handle more currencies in a way that keeps the dropdown clean. It was even based on your plan. That will allow Chinese currencies in, plus all the currencies people will no doubt add in the future. My point was that I wanted a way to keep the dropdown clean first, and merging in more currencies before that does not help, as the three that got in before clearly already set a precedent. Yet daihakken found it necessary to do an ad hominem _after_ I expressed that idea. That's no way to conduct a discussion.

**Comment by danielsarsi** [comment]
Lots of currencies actually avoid people seeing favoritism.

I can see that takes a lot of work to add a currency, and that is, in my opinion, a valid technical problem and @LRFLEW solution fix this. @Gymnasiast had a great idea too (currency suggestions and a "Others…" button in the dropdown).

We need to prevent people getting offended by this (which I think it's totally valid). That's whole point.
Do you guys agree?

**Comment by danielsarsi** [comment]
@Gymnasiast Currency isn't that fundamental to the game itself, but it is for people playing it. That makes me feel like this whole UI work kind of unnecessary. Don't you think?

**Comment by Gymnasiast** [comment]
I have little patience for people who get offended by a technical decision. And especially to follow up with pulling the discrimination card. I don't do discussions that way. 

I wish this whole UI kind was unnecessary. The ability to define ones own currency should cover everything. But we clearly set a precedent with adding the koruna, won and rouble. And if these get in, next month someone else wants to get their currency in. So other we stick with what we have (which doesn't seem to go down well with daihakken, and isn't favoured by IntelOrca), reduce to the original currencies or allow more currencies in and provide a way to keep everything tidy. It's not ideal, but a whole lot better than one enormous dropdown, which will certainly happen if everyone adds their currency.

**Comment by danielsarsi** [comment]
@Gymnasiast What about leave the original currencies in the dropdown, and add an "Other…" button, that shows the remaining? Other currencies can be handled by the custom system that @LRFLEW suggested, and everyone will be able to add his own currency just by editing an .txt file.

**Comment by IntelOrca** [comment]
Dropdowns currently have a maximum of 64 items, so what do we do when we have more than 64 currencies?

**Comment by danielsarsi** [comment]
Put everything else in a window with a scroll?

**Comment by vegbrasil** [comment]
We should use Dogecoin.

```
wow
many commits
such discussion
```

wow

**Comment by daihakken** [comment]
Yes, I admit I'm talking it personally in the earlier post, but did you put in my shoes? It's never been that frustrating and annoying when you see some suggestions for 5-10 lines commit being left out for months, and one of them become hijacked to a superb improvement but definitely take a lot more time to implement. (Logical flow & 50+ lines of code) This complication is very discouraging and also looks disrespectful, especially what I requested are subtle, but also focus on the user experience. If I were you, I would ask me that if it is okay to do so, or we should add the currencies first. 

Again, talking about the currency system, did you think about the users that are lazy or completely new to the game? Using your words, it is trivial and will confuse players. I honestly don't see any benefits to include the system in game at this moment unless adding some unnecessary burden on the developers.

**Comment by Gymnasiast** [comment]
Let's do it this way, then:
1) Rebase this commit and merge it.
2) Implement the 'own currency' feature
3) Implement the currency suggestions when the need arises.

**Comment by IntelOrca** [comment]
I think large dropdowns are a common problem. Particularly when you enable all vehicles for any ride. So maybe a generic window for selecting things from long lists complete with search feature?

**Comment by Gymnasiast** [comment]
Yes, but I would open a separate issue for that.

**Comment by daihakken** [comment]
Dropdown with scroll bar and type to locate feature would be also great to that.

**Comment by Gymnasiast** [comment]
I created https://github.com/OpenRCT2/OpenRCT2/issues/2889 to discuss the solution for long dropdowns.

In the meantime, @daihakken, could you rebase this PR so we can merge it?

**Comment by Gymnasiast** [comment]
@daihakken : Do you want me to do the rebase for you?

**Comment by Gymnasiast** [comment]
Rebased version in #2872, therefore closing this one.

**Pull request closed without merging**
