### PR TITLE
Fix #12071: Crash in Guest List when a guest dies

### LINKED ISSUE #12071: [f79add] rct2.EXE: strnlen, format_string_code, format_string_part_from_raw, DrawTextEllipsisedCompat, window_guest_list_scro...
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/f79add2de575370f8ba56eb57992b47fbf7cc2ff7dc2ce7ce3e21d953ab6ec5e">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>rct2.EXE</td></tr>
<tr>
    <td><strong>Attributes</strong></td>
    <td>
<strong>dummy</strong> &mdash; 1
        <ul>
                <li><code>0</code> &mdash; 1</li></ul><br>
<strong>attachment_replay.sv6r</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\Samsung Chairman\Documents\OpenRCT2\3d2060dd-68fb-4bd8-9e73-766bd9c2f9e6.sv6r</code> &mdash; 1</li></ul><br>
<strong>attachment_park.sv6</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_config.ini</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\Samsung Chairman\Documents\OpenRCT2\3d2060dd-68fb-4bd8-9e73-766bd9c2f9e6.ini</code> &mdash; 1</li></ul><br>
<strong>assert_failure</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_park.sv6.gz</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\Samsung Chairman\Documents\OpenRCT2\3d2060dd-68fb-4bd8-9e73-766bd9c2f9e6.sv6.gz</code> &mdash; 1</li></ul><br>
<strong>attachment_screenshot.png</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\Samsung Chairman\Documents\OpenRCT2\screenshot\\37777\37777\37777\37777\37777\37777\37777\37777\37777\37777\37777\37777 \37777\37777\37777 2020-06-28 22-22-15.png</code> &mdash; 1</li></ul><br>
<strong>commit</strong> &mdash; 1
        <ul>
                <li><code>681b8d7</code> &mdash; 1</li></ul><br></td>
    </tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>invalid-read</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
strnlen
format_string_code
format_string_part_from_raw
DrawTextEllipsisedCompat
window_guest_list_scrollpaint
widget_scroll_draw
widget_draw
window_draw_widgets
window_guest_list_paint
window_draw_single
window_draw
std::_Func_impl_no_alloc<<lambda_c6239a5f162a90c22f819d59f2036264>,void,rct_window *>::_Do_call
window_visit_each(std::function<void __cdecl
window_draw_all
OpenRCT2::Drawing::X8DrawingEngine::DrawAllDirtyBlocks
OpenRCT2::Drawing::X8DrawingEngine::PaintWindows
OpenRCT2::Paint::Painter::Paint
OpenRCT2::Context::RunVariableFrame
OpenRCT2::Context::RunGameLoop
OpenRCT2::Context::RunOpenRCT2
NormalisedMain
wmain</code>
        </td>
    </tr></table>

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by ZehMatt** [comment]
I agree with @tupaschoal, having this during scroll events can kill the performance on large lists.

**Comment by duncanspumpkin** [comment]
Yeah i agree with the above suggestion.

**Comment by duncanspumpkin** [comment]
Its pretty expensive to run a refresh now so refreshing multiple times a tick which is what would happen with this would be a significant performance impact. I plan to rework how sprites are removed so that they are all removed at the end of a tick and I can have all of the UI intent broadcasting at one point. That will simplify and reduce the chance of these types of bugs.

**Comment by Gymnasiast** [comment]
That's all very nice, but if I change like that, the crash simply returns.

**Comment by duncanspumpkin** [comment]
Okay I'll take a look at an alternative.

**Comment by duncanspumpkin** [comment]
I've done a two pronged fix of it in my commit a0e657b. First I made it so that invalid entities cannot be drawn or clicked by verifying that the sprite is a guest. Secondly I applied the intent broadcast as discussed above. I susspect the issue you were having where it still crashed was because you called it too early. It needs to be called after the final sprite_removal as the refresh will happen during that function call.

**Comment by duncanspumpkin** [comment]
Incidentally this error would have prevented building if we were using the `GetEntity<Guest>` interface instead of the `GET_PEEP` macro. I plan to remove the `GET_PEEP` macro but there are lots of nullptr checks that need to be added to get that working.

**Comment by AaronVanGeffen** [comment]
This is still refreshing the guest list on the scroll mouse down and get size events. Are these still necessary, and if so, should they be replaced by an intent as well?

**Comment by duncanspumpkin** [comment]
Yeah I've not removed the original commit but I'm proposing it is dropped.

**Comment by Gymnasiast** [comment]
> Yeah I've not removed the original commit but I'm proposing it is dropped.

You could just have nuked it, as it was bad for performance and is now also redundant. You don't need to worry about stepping on my toes, I just want the issue fixed.

**Pull request merged**
