### PR TITLE
Twister LIM Sprites

### PR DESCRIPTION
**Pull request by xp4xbox**
My improved LIM sprites for the twister track type.

More details here: http://www.nedesigns.com/topic/32012/openrct-advantages-and-disadvantages/page-46#entry719893

### CODE REVIEW

**Comment by rwjuk** [comment]
Can you optimise those PNGs? I can get them down to 3-400 bytes using an optimiser.

**Comment by xp4xbox** [comment]
The current state, they are uncompressed, but I could get them down around 65%.

**Comment by mrtnptrs** [comment]
@xp4xbox Then what's stopping you? :P Compressing them will make sure the size of OpenRCT2 doesn't get too big and also will deliver a tiny little bit better performance (but if all the PNG's weren't optimised, all those tiny little bit of slowdowns, would affect the game-performance eventually.) :)

**Comment by duncanspumpkin** [comment]
@mrtnptrs that's not how this works. It should be compressed to keep the size of the git project down that's the only reason.

**Comment by xp4xbox** [comment]
Just updated them.

**Comment by janisozaur** [comment]
@xp4xbox there's no point in having two commits touching these files, this is now only more bloat than it used to be with uncompressed sprites. Please squash your commits and only leave optimised versions.

**Comment by xp4xbox** [comment]
@janisozaur Sorry, its my first time posting a pull, i am not sure how I squash my commit.

**Comment by Gymnasiast** [comment]
@janisozaur Do you expect a first-time contributor who used the Github front-end to be able to squash?

@xp4xbox Any of us can squash it for you, janisozaur is being way too strict on you.

**Comment by Gymnasiast** [comment]
I squashed and reworded the two commits.

**Comment by xp4xbox** [comment]
So what now?

**Comment by Gymnasiast** [comment]
1) Confirmation that the files are ok now, for example by @duncanspumpkin or @janisozaur 
2) Fixing the offsets

**Comment by YoloSweggLord** [comment]
Both sprites are the exact same size with the track in the same place, so do the offsets need to be fixed?

**Comment by xp4xbox** [comment]
The offsets are fine for theses sprites.

**Comment by Gymnasiast** [comment]
In this case only point 1 remains.

**Comment by YoloSweggLord** [comment]
I know you were planning on replacing the giga launch sprites as well with flat truss track- when you get to that, could we discuss including both versions in the game, and making an option to switch between them? I'm fine with these ones being replaced since it's a minor aesthetic change, but the booster sprites would be a much bigger change.

**Comment by xp4xbox** [comment]
@YoloSweggLord I wasnt planning to replace it for the giga track after I found out, that the game would not draw supports when the track piece was placed on flat ground. Instead im probably gonna do a Hydrolic launch style of track, with small fins on both sides.

**Pull request merged**
