### PR TITLE
Refactor Vehicle Scream Sound goto

### PR DESCRIPTION
**Pull request by outerwear**
Refactored goto statement in vehicle scream update sound code.

### CODE REVIEW

**Comment by outerwear** [comment]
Link to open issue: https://github.com/OpenRCT2/OpenRCT2/issues/12253

**Comment by duncanspumpkin** [comment]
In your commit message you should have "Close #12253: Refactor Vehicle sound to remove goto".

Did you test this as I'm pretty sure as it is no sounds will be generated or if they do will be delayed by a tick.

**Comment by outerwear** [comment]
Good point, fixing now

**Comment by duncanspumpkin** [comment]
The failing ci tests btw are because the game logic had changed. I'm pretty sure that's just due to the member variable issue.

**Comment by outerwear** [comment]
I appreciate the comments, first pull request here :)
Updated the code, fixed the variable issue. Tested with a roller coaster in game. Is there any special debug log or unit test available?

**Comment by duncanspumpkin** [comment]
There is a Google test setup. Tbh i just push my branch to the repo and let the ci's do the tests rather than get testing setup on my local machine. Oh sorry didn't realise this is your first PR. Could you add yourself to contributors.md. I'll adjust the commit message on merge. Just remember that in future. The changes all look good now.

**Comment by duncanspumpkin** [comment]
Another very minor thing totalNumPeeps should be const.

**Pull request merged**
