### PR TITLE
Add command to set velocity and acceleration of powered rides

### PR DESCRIPTION
**Pull request by X123M3-256**
This adds a command to set the velocity and acceleration of powered rides, with the syntax "rides set powered_velocity <ride index> <velocity> [acceleration]". I also reorganised the surrounding code to try to reduce the amount of code duplication that resulted from adding the new command, but I'm not sure that having so many nested conditionals is actually better - it might need a bit more cleaning up still.

There is a strange interaction with the friction cheat - setting friction to 1 and velocity and acceleration to 65535 causes the vehicle to rapidly accelerate until the velocity overflows.

### CODE REVIEW

**Comment by Goddesen** [comment]
I would advocate rewriting that function to print an error and return immediately instead of having tons of `else` and `else if`s.

Insead of:
```C
if (argc > 0) {
    // statements
} else {
    console_printf("subcommands: list, set");
}
return 0;
```

, do:
```C
if (argc < 1) {
    console_printf("subcommands: list, set");
    return 0;
}

// statements without 100 spaces of indentation
```

This might get rid of the seven-times indented statement at `console.c:531`. It also makes it immediately obvious when the function actually returns, as opposed to working out which branch you were in.

**Comment by X123M3-256** [comment]
Yeah, I agree. Part of the problem is that I need to check if values are in range at every step because if they aren't the game will crash, and that means there's a lot of conditionals. I will try and improve it.

**Comment by Gymnasiast** [comment]
It's not really a problem for now. People who use the console are power users anyway. Could you rebase this so we can merge it?

**Comment by janisozaur** [comment]
@X123M3-256 I think your rebase went wrong. Do you need assistance?

**Comment by X123M3-256** [comment]
Yeah, probably.

**Comment by X123M3-256** [comment]
I think it might be easier to close this PR and create a new one. It only modifies one file and I'm not sure what's gone wrong with the rebase.

**Comment by janisozaur** [comment]
There were quite a few commits touching this file ever since this PR was created, this is the commit that breaks rebase:

e25c768a3 Convert `rides set` console command to use game_command interface

It may actually be better to re-create it – and while at it, can you make it use `game_command` as well?

**Comment by X123M3-256** [comment]
OK, I'll close this, and create a new PR.

**Pull request closed without merging**
