### PR TITLE
Start cleanup of testpaint

### PR DESCRIPTION
**Pull request by marijnvdwerf**

### CODE REVIEW

**Comment by IntelOrca** [comment]
What for?

**Comment by marijnvdwerf** [comment]
Unneccesary? Okay, nevermind then :).

**Comment by IntelOrca** [comment]
You can do it, just wondering why if we are near to not needing it anymore?

**Comment by marijnvdwerf** [comment]
Would be nice if it could stay runnable until all rides are converted to cpp (if that's still the plan). So you at least not introduce new bugs.

**Comment by IntelOrca** [comment]
Yea, if we want to remove the original game hooks though, we would need a way of dumping the call data to a file so that you can just use that to test the new code against.

**Comment by janisozaur** [comment]
```
[  4%] Built target segfiles
[  8%] Building CXX object CMakeFiles/testpaint.dir/test/testpaint/PaintIntercept.cpp.o
/home/janisozaur/workspace/OpenRCT2/test/testpaint/PaintIntercept.cpp: In function ‘bool wooden_a_supports_paint_setup(int, int, int, uint32, bool*)’:
/home/janisozaur/workspace/OpenRCT2/test/testpaint/PaintIntercept.cpp:251:6: error: no previous declaration for ‘bool wooden_a_supports_paint_setup(int, int, int, uint32, bool*)’ [-Werror=missing-declarations]
 bool wooden_a_supports_paint_setup(int supportType, int special, int height, uint32 imageColourFlags, bool *underground) {
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/janisozaur/workspace/OpenRCT2/test/testpaint/PaintIntercept.cpp: In function ‘bool wooden_b_supports_paint_setup(int, int, int, uint32, bool*)’:
/home/janisozaur/workspace/OpenRCT2/test/testpaint/PaintIntercept.cpp:255:6: error: no previous declaration for ‘bool wooden_b_supports_paint_setup(int, int, int, uint32, bool*)’ [-Werror=missing-declarations]
 bool wooden_b_supports_paint_setup(int supportType, int special, int height, uint32 imageColourFlags, bool *underground) {
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/janisozaur/workspace/OpenRCT2/test/testpaint/PaintIntercept.cpp: In function ‘bool metal_a_supports_paint_setup(uint8, uint8, int, int, uint32)’:
/home/janisozaur/workspace/OpenRCT2/test/testpaint/PaintIntercept.cpp:259:6: error: no previous declaration for ‘bool metal_a_supports_paint_setup(uint8, uint8, int, int, uint32)’ [-Werror=missing-declarations]
 bool metal_a_supports_paint_setup(uint8 supportType, uint8 segment, int special, int height, uint32 imageColourFlags) {
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/janisozaur/workspace/OpenRCT2/test/testpaint/PaintIntercept.cpp: In function ‘bool metal_b_supports_paint_setup(uint8, uint8, int, int, uint32)’:
/home/janisozaur/workspace/OpenRCT2/test/testpaint/PaintIntercept.cpp:263:6: error: no previous declaration for ‘bool metal_b_supports_paint_setup(uint8, uint8, int, int, uint32)’ [-Werror=missing-declarations]
 bool metal_b_supports_paint_setup(uint8 supportType, uint8 segment, int special, int height, uint32 imageColourFlags) {
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/janisozaur/workspace/OpenRCT2/test/testpaint/PaintIntercept.cpp: In function ‘void intercept_simulate_wooden_supports(bool)’:
/home/janisozaur/workspace/OpenRCT2/test/testpaint/PaintIntercept.cpp:340:6: error: no previous declaration for ‘void intercept_simulate_wooden_supports(bool)’ [-Werror=missing-declarations]
 void intercept_simulate_wooden_supports(bool enabled) {
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[3]: *** [CMakeFiles/testpaint.dir/build.make:2159: CMakeFiles/testpaint.dir/test/testpaint/PaintIntercept.cpp.o] Błąd 1
[ 12%] Building CXX object CMakeFiles/testpaint.dir/test/testpaint/Utils.cpp.o
/home/janisozaur/workspace/OpenRCT2/test/testpaint/Utils.cpp: In function ‘int getTrackSequenceCount(uint8, uint8)’:
/home/janisozaur/workspace/OpenRCT2/test/testpaint/Utils.cpp:72:9: error: no previous declaration for ‘int getTrackSequenceCount(uint8, uint8)’ [-Werror=missing-declarations]
     int getTrackSequenceCount(uint8 rideType, uint8 trackType) {
         ^~~~~~~~~~~~~~~~~~~~~
```

**Comment by janisozaur** [comment]
You should probably merge https://github.com/OpenRCT2/OpenRCT2/pull/4623 here

**Comment by marijnvdwerf** [comment]
For some reason the classic function ignores the chainlift flag (`mapElement->type = 0x80`). Any ideas as to why this is happening?

**Comment by marijnvdwerf** [comment]
Currently at 550 failures. Should probably fix some of those before adding even more testfilters.

**Comment by janisozaur** [comment]
@marijnvdwerf testpaint fails to compile:
```
/home/travis/build/OpenRCT2/OpenRCT2/test/testpaint/PaintIntercept.cpp: In function ‘bool PaintIntercept::PaintWoodenSupports(uint8, int, int, int, uint32, bool*)’:
/home/travis/build/OpenRCT2/OpenRCT2/test/testpaint/PaintIntercept.cpp:73:10: error: no previous declaration for ‘bool PaintIntercept::PaintWoodenSupports(uint8, int, int, int, uint32, bool*)’ [-Werror=missing-declarations]
     bool PaintWoodenSupports(uint8 function, int supportType, int special, int height, uint32 imageColourFlags, bool *underground) {
          ^
/home/travis/build/OpenRCT2/OpenRCT2/test/testpaint/PaintIntercept.cpp: In function ‘bool PaintIntercept::PaintMetalSupports(uint8, int, uint8, int, int, uint32)’:
/home/travis/build/OpenRCT2/OpenRCT2/test/testpaint/PaintIntercept.cpp:87:10: error: no previous declaration for ‘bool PaintIntercept::PaintMetalSupports(uint8, int, uint8, int, int, uint32)’ [-Werror=missing-declarations]
     bool PaintMetalSupports(uint8 function, int supportType, uint8 segment, int special, int height, uint32 imageColourFlags) {
          ^
```

Also add `-DCMAKE_BUILD_TYPE=debug` to second travis entry. In case it crashes, it should provide a bit more info.

**Comment by janisozaur** [comment]
`main.cpp` should probably all use spaces for indentation now

**Comment by janisozaur** [comment]
`FindMostCommonSupportCall`, and to be more exact `SupportCall`, look too complicated. If you know there are only ever 4 distinct values, you can just work on their indices, instead of having a whole wrapper class around it.

You should also be able to do:
```cpp
    for (int i = 0; i < 4; ++i) {
        if (map.count(calls[i]) == 0) {
            map[calls[i]]++;
        }
    }
```

instead of

```cpp
    for (int i = 0; i < 4; ++i) {
        if (map.count(calls[i]) == 0) {
            map[calls[i]] = 1;
        } else {
            map[calls[i]] += 1;
        }
    }
```

See: http://en.cppreference.com/w/cpp/container/map/operator_at

> Return value

> Reference to the mapped value of the new element if no element with key key existed. Otherwise a reference to the mapped value of the existing element whose key is equivalent to key.

**Comment by marijnvdwerf** [comment]
For me, these fail as well locally. Probably has to do with the `rct_vehicle_entry` being used by the flat rides. For now that seems like a low prio bug to me (I want to improve flat ride testing anyway, so might as well be tackled then).
```txt
[  FAILED  ] FoodStall.1x1_A		
[  FAILED  ] 1D.1x1_B		
[  FAILED  ] DrinkStall.1x1_A		
[  FAILED  ] 1F.1x1_B		
[  FAILED  ] Shop.1x1_A		
[  FAILED  ] MerryGoRound.3x3		
[  FAILED  ] 22.1x1_B		
[  FAILED  ] InformationKiosk.1x1_B		
[  FAILED  ] Toilets.1x1_A
[  FAILED  ] 3DCinema.3x3		
[  FAILED  ] TopSpin.3x3
[  FAILED  ] CashMachine.1x1_A		
[  FAILED  ] Twist.3x3		
[  FAILED  ] HauntedHouse.3x3		
[  FAILED  ] FirstAid.1x1_A		
[  FAILED  ] CircusShow.3x3
[  FAILED  ] CrookedHouse.3x3
[  FAILED  ] 50.1x1_A		
[  FAILED  ] Enterprise.4x4		
[  FAILED  ] 52.1x1_A		
[  FAILED  ] 53.1x1_A		
[  FAILED  ] 54.1x1_A
```

**Comment by marijnvdwerf** [comment]
@janisozaur Travis is still failing due to `testpaint`.

**Comment by marijnvdwerf** [comment]
Except for the Travis configuration, what's blocking this?

**Comment by janisozaur** [comment]
@marijnvdwerf I fixed travis here. If this is with `--silent`, I'm afraid of `--verbose`.

**Comment by marijnvdwerf** [comment]
#4653 will fix a lot of these

**Comment by marijnvdwerf** [comment]
@janisozaur Is this more like you expected? https://travis-ci.org/OpenRCT2/OpenRCT2/jobs/168786632

**Comment by janisozaur** [comment]
Much better 👍

**Pull request merged**
