### PR TITLE
File dialog

### PR DESCRIPTION
**Pull request by janisozaur**
Can someone please test it? I'm not very good with this type of code, there might be bugs.

### CODE REVIEW

**Comment by janisozaur** [comment]
That's the stuff for #3009

**Comment by janisozaur** [comment]
kdialog does not support multiple filters. See https://quickgit.kde.org/?p=kde-baseapps.git&a=blob&h=9afc53bccd1b313417e280952a208200cc444940&hb=c9e3a760084f76af0f5e28c5aa60a9d5678ca122&f=kdialog%2Fkdialog.cpp lines 596 and 603

**Comment by janisozaur** [comment]
kdialog should work now as well. The easiest way to test kdialog is to change `execute_cmd("which zenity", &exit_value, cmd, &size);` in line 195, `exit_value = 1;` should suffice.

**Comment by Gymnasiast** [comment]
Two things I found:
- Kdialog crashes when attempting to load a saved game from the main title
- Starting a server from a save does not seem to use any filter:
schermafdruk van 2016-03-28 22-24-08

**Comment by PFCKrutonium** [comment]
@Gymnasiast It should be noted that window is titled "(null)"

**Comment by janisozaur** [comment]
This should be the end of it at least for Linux. There is an issue @Gymnasiast found regarding loading a save for server, I added an assert for that – filters are not passed to this function, it should trigger on Windows as well (`title screen > MP > start server > load save`)

@IntelOrca I think I've tested this enough for this to be ready for merging, though feel free to wait for another review.

This kind of code is extremely painful to write and maintain and we should really just go with GTK and have a proper API in place and not this kind of kludge.

**Comment by Gymnasiast** [comment]
With your newest code, trying to load a save for setting up a new server, using KDialog, crashes with the following output:
```
michael@Hadrianus:~/Programma's/OpenRCT2/Spelletjes/RollerCoaster Tycoon 2$ ./openrct2 
ERROR[/home/michael/Dropbox/Aptana Studio 3 Workspace/OpenRCT2-4/src/object_list.c:380 (object_list_cache_load)]: Potential mismatch in file numbers. Possible corrupt file. Consider deleting plugin.dat.
*** Error in `./openrct2': double free or corruption (out): 0x0423edf8 ***
======= Backtrace: =========
/lib/i386-linux-gnu/libc.so.6(+0x65064)[0xf7159064]
/lib/i386-linux-gnu/libc.so.6(+0x6b367)[0xf715f367]
/lib/i386-linux-gnu/libc.so.6(+0x6bb31)[0xf715fb31]
./openrct2(platform_open_common_file_dialog+0x675)[0x14ee725]
./openrct2[0x1474caf]
./openrct2(game_handle_input+0x110)[0x14fd1e0]
./openrct2(rct2_update+0x95)[0x14ebcd5]
./openrct2(openrct2_launch+0xca)[0x143386a]
./openrct2(main+0x36)[0x14296b6]
/lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf6)[0xf710c646]
./openrct2[0x142986a]
======= Memory map: ========
00010000-00037000 r-xp 00000000 08:03 14549832                           /home/michael/.PlayOnLinux/wineprefix/OpenRCT2/drive_c/Spelletjes/RollerCoaster Tycoon 2/openrct2
00401000-008a4000 r-xp 00027000 08:03 14549832                           /home/michael/.PlayOnLinux/wineprefix/OpenRCT2/drive_c/Spelletjes/RollerCoaster Tycoon 2/openrct2
008a4000-01429000 rwxp 004ca000 08:03 14549832                           /home/michael/.PlayOnLinux/wineprefix/OpenRCT2/drive_c/Spelletjes/RollerCoaster Tycoon 2/openrct2
01429000-015b6000 r-xp 0104f000 08:03 14549832                           /home/michael/.PlayOnLinux/wineprefix/OpenRCT2/drive_c/Spelletjes/RollerCoaster Tycoon 2/openrct2
015b6000-015b7000 r-xp 011db000 08:03 14549832                           /home/michael/.PlayOnLinux/wineprefix/OpenRCT2/drive_c/Spelletjes/RollerCoaster Tycoon 2/openrct2
015b7000-015c8000 rwxp 011dc000 08:03 14549832                           /home/michael/.PlayOnLinux/wineprefix/OpenRCT2/drive_c/Spelletjes/RollerCoaster Tycoon 2/openrct2
015c8000-0163f000 rwxp 00000000 00:00 0 
030f8000-045d0000 rwxp 00000000 00:00 0                                  [heap]
dc200000-dc25c000 rwxp 00000000 00:00 0 
dc25c000-dc300000 ---p 00000000 00:00 0 
dc400000-dc800000 rwxs 1156ee000 00:06 597                               /dev/nvidiactl
dc800000-dc821000 rwxp 00000000 00:00 0 
dc821000-dc900000 ---p 00000000 00:00 0 
dc9ff000-dca00000 ---p 00000000 00:00 0 
dca00000-dd200000 rwxp 00000000 00:00 0 
dd200000-dd2f8000 rwxp 00000000 00:00 0 
dd2f8000-dd300000 ---p 00000000 00:00 0 
dd3d7000-dd3d8000 ---p 00000000 00:00 0 
dd3d8000-ddbd8000 rwxp 00000000 00:00 0 
ddbd8000-ddfd8000 rwxs 30db4a000 00:06 597                               /dev/nvidiactl
ddfd8000-de3d8000 rwxs 115631000 00:06 597                               /dev/nvidiactl
de3d8000-de7d8000 rwxs 328d78000 00:06 597                               /dev/nvidiactl
de7d8000-de9d8000 rwxs 125ae8000 00:06 597                               /dev/nvidiactl
de9d8000-defb6000 rwxp 00000000 00:00 0 
df003000-df700000 rwxp 00000000 00:00 0 
df700000-df721000 rwxp 00000000 00:00 0 
df721000-df800000 ---p 00000000 00:00 0 
df852000-df853000 ---p 00000000 00:00 0 
df853000-e0053000 rwxp 00000000 00:00 0                                  [stack:15020]
e0053000-e4054000 rwxs 00000000 00:14 10                                 /dev/shm/pulse-shm-3229132837
e4054000-e8055000 rwxs 00000000 00:14 18                                 /dev/shm/pulse-shm-675454663
e8055000-e8f1f000 rwxp 00000000 00:00 0 
e8fc1000-e903b000 rwxp 00000000 00:00 0 
e903b000-e9273000 rwxs 00001000 00:14 17                                 /dev/shm/#17 (deleted)
e9273000-e94ab000 rwxp 00000000 00:00 0 
e94ab000-e952b000 rwxs 7b1ce000 00:06 597                                /dev/nvidiactl
e952b000-e95ab000 rwxs 2d4dc5000 00:06 597                               /dev/nvidiactl
e95ab000-e962b000 rwxs 34a448000 00:06 597                               /dev/nvidiactl
e962b000-e972b000 rwxs 1157f3000 00:06 597                               /dev/nvidiactl
e972b000-e974b000 rwxs a00c0000 00:06 598                                /dev/nvidia0
e974b000-e978b000 rwxs 072c6000 00:06 597                                /dev/nvidiactl
e978b000-e97ab000 rwxs 1542b000 00:06 597                                /dev/nvidiactl
e97ab000-e97eb000 rwxs 2187f7000 00:06 597                               /dev/nvidiactl
e97eb000-e980b000 rwxs 34bf0b000 00:06 597                               /dev/nvidiactl
e980b000-e984b000 rwxs 127c3d000 00:06 597                               /dev/nvidiactl
e984b000-e99c7000 rwxp 00000000 00:00 0 
e99c7000-e9a3a000 rwxp 00000000 00:00 0 
e9a3a000-e9b3e000 rwxs 34c8e7000 00:06 597                               /dev/nvidiactl
e9b3e000-e9b7f000 rwxp 00000000 00:00 0 
e9b7f000-eb6bc000 r-xp 00000000 08:02 305159                             /usr/lib32/nvidia-361/libnvidia-glcore.so.361.28
eb6bc000-eb6dc000 rwxp 01b3d000 08:02 305159                             /usr/lib32/nvidia-361/libnvidia-glcore.so.361.28
eb6dc000-ebd58000 r-xp 01b5d000 08:02 305159                             /usr/lib32/nvidia-361/libnvidia-glcore.so.361.28
ebd58000-ebdf5000 rwxp 021d8000 08:02 305159                             /usr/lib32/nvidia-361/libnvidia-glcore.so.361.28
ebdf5000-ebe04000 rwxp 00000000 00:00 0 
ebe04000-ebec2000 r-xp 00000000 08:02 305166                             /usr/lib32/nvidia-361/libGLX_nvidia.so.361.28
ebec2000-ebee2000 rwxp 000be000 08:02 305166                             /usr/lib32/nvidia-361/libGLX_nvidia.so.361.28
ebee2000-ebf0a000 r-xp 000de000 08:02 305166                             /usr/lib32/nvidia-361/libGLX_nvidia.so.361.28
ebf0a000-ebf10000 rwxp 00105000 08:02 305166                             /usr/lib32/nvidia-361/libGLX_nvidia.so.361.28
ebf10000-ebf13000 rwxp 00000000 00:00 0 
ebf13000-ebf91000 r-xp 00000000 08:02 305174                             /usr/lib32/nvidia-361/libGLdispatch.so.0
ebf91000-ebf99000 rwxp 0007d000 08:02 305174                             /usr/lib32/nvidia-361/libGLdispatch.so.0
ebf99000-ecff0000 rwxp 00000000 00:00 0 
ecff3000-ed003000 r-xp 00000000 08:02 305165                             /usr/lib32/nvidia-361/libGLX.so.0
ed003000-ed004000 rwxp 0000f000 08:02 305165                             /usr/lib32/nvidia-361/libGLX.so.0
ed004000-ed014000 rwxp 00000000 00:00 0 
ed014000-ed080000 r-xp 00000000 08:02 305171                             /usr/lib32/nvidia-361/libGL.so.1.0.0
ed080000-ed081000 rwxp 0006b000 08:02 305171                             /usr/lib32/nvidia-361/libGL.so.1.0.0
ed081000-ed0c2000 rwxp 00000000 00:00 0 
ed0c5000-ed0c7000 rwxs 00000000 08:02 1700718                            /tmp/.glmBKpz6 (deleted)
ed0c7000-ed0c9000 r-xs 00000000 08:02 1700718                            /tmp/.glmBKpz6 (deleted)
ed0c9000-ed0dc000 rwxs 328d26000 00:06 597                               /dev/nvidiactl
ed0dc000-ed0e0000 rwxs 1133ba000 00:06 597                               /dev/nvidiactl
ed0f9000-ed0fe000 r-xp 00000000 08:02 1179196                            /lib/i386-linux-gnu/libnss_dns-2.23.so
ed0fe000-ed0ff000 r-xp 00004000 08:02 1179196                            /lib/i386-linux-gnu/libnss_dns-2.23.so
ed0ff000-ed100000 rwxp 00005000 08:02 1179196                            /lib/i386-linux-gnu/libnss_dns-2.23.so
ed100000-ed121000 rwxp 00000000 00:00 0 
ed121000-ed200000 ---p 00000000 00:00 0 
ed200000-ed201000 rwxp 00000000 00:00 0 
ed201000-ed202000 rwxs 34cb10000 00:06 597                               /dev/nvidiactl
ed202000-ed203000 rwxs aff6b000 00:06 598                                /dev/nvidia0
ed203000-ed204000 rwxs aff6a000 00:06 598                                /dev/nvidia0
ed204000-ed205000 rwxs aff69000 00:06 598                                /dev/nvidia0
ed205000-ed206000 rwxs 16985e000 00:06 597                               /dev/nvidiactl
ed206000-ed207000 rwxs b2060000 00:06 598                                /dev/nvidia0
ed207000-ed20b000 r-xp 00000000 08:02 305160                             /usr/lib32/nvidia-361/tls/libnvidia-tls.so.361.28
ed20b000-ed20c000 rwxp 00003000 08:02 305160                             /usr/lib32/nvidia-361/tls/libnvidia-tls.so.361.28
ed20c000-ed230000 r-xp 00000000 08:02 530923                             /usr/share/locale-langpack/nl/LC_MESSAGES/libc.mo
ed230000-ed231000 ---p 00000000 00:00 0 
ed231000-eda31000 rwxp 00000000 00:00 0                                  [stack:15017]
eda31000-f1a32000 rwxs 00000000 00:14 10                                 /dev/shm/pulse-shm-3229132837
f1a32000-f5a33000 rwxs 00000000 00:14 16                                 /dev/shm/pulse-shm-2296704933
f5a33000-f5bce000 r-xp 00000000 08:02 135207                             /usr/lib/locale/locale-archive
f5bce000-f5bd9000 r-xp 00000000 08:02 1178396                            /lib/i386-linux-gnu/libnss_files-2.23.so
f5bd9000-f5bda000 r-xp 0000a000 08:02 1178396                            /lib/i386-linux-gnu/libnss_files-2.23.so
f5bda000-f5bdb000 rwxp 0000b000 08:02 1178396                            /lib/i386-linux-gnu/libnss_files-2.23.so
f5bdb000-f5be1000 rwxp 00000000 00:00 0 
f5be1000-f5bec000 r-xp 00000000 08:02 1177729                            /lib/i386-linux-gnu/libnss_nis-2.23.so
f5bec000-f5bed000 r-xp 0000a000 08:02 1177729                            /lib/i386-linux-gnu/libnss_nis-2.23.so
f5bed000-f5bee000 rwxp 0000b000 08:02 1177729                            /lib/i386-linux-gnu/libnss_nis-2.23.so
f5bee000-f5bf6000 r-xp 00000000 08:02 1177462                            /lib/i386-linux-gnu/libnss_compat-2.23.so
f5bf6000-f5bf7000 r-xp 00007000 08:02 1177462                            /lib/i386-linux-gnu/libnss_compat-2.23.so
f5bf7000-f5bf8000 rwxp 00008000 08:02 1177462                            /lib/i386-linux-gnu/libnss_compat-2.23.so
f5bf8000-f5bff000 rwxp 00000000 00:00 0 
f5bff000-f5c29000 r-xp 00000000 08:02 263589                             /usr/lib/i386-linux-gnu/libvorbis.so.0.4.8
f5c29000-f5c2a000 r-xp 00029000 08:02 263589                             /usr/lib/i386-linux-gnu/libvorbis.so.0.4.8
f5c2a000-f5c2b000 rwxp 0002a000 08:02 263589                             /usr/lib/i386-linux-gnu/libvorbis.so.0.4.8
f5c2b000-f5c32000 r-xp 00000000 08:02 271538                             /usr/lib/i386-linux-gnu/libogg.so.0.8.2
f5c32000-f5c33000 r-xp 00006000 08:02 271538                             /usr/lib/i386-linux-gnu/libogg.so.0.8.2
f5c33000-f5c34000 rwxp 00007000 08:02 271538                             /usr/lib/i386-linux-gnu/libogg.so.0.8.2
f5c34000-f5c35000 rwxp 00000000 00:00 0 
f5c35000-f5c49000 r-xp 00000000 08:02 1178064                            /lib/i386-linux-gnu/libgpg-error.so.0.17.0
f5c49000-f5c4a000 r-xp 00013000 08:02 1178064                            /lib/i386-linux-gnu/libgpg-error.so.0.17.0
f5c4a000-f5c4b000 rwxp 00014000 08:02 1178064                            /lib/i386-linux-gnu/libgpg-error.so.0.17.0
f5c4b000-f5cbe000 r-xp 00000000 08:02 1177498                            /lib/i386-linux-gnu/libpcre.so.3.13.2
f5cbe000-f5cbf000 r-xp 00072000 08:02 1177498                            /lib/i386-linux-gnu/libpcre.so.3.13.2
f5cbf000-f5cc0000 rwxp 00073000 08:02 1177498                            /lib/i386-linux-gnu/libpcre.so.3.13.2
f5cc0000-f5cc9000 r-xp 00000000 08:02 1179186                            /lib/i386-linux-gnu/libcrypt-2.23.so
f5cc9000-f5cca000 r-xp 00008000 08:02 1179186                            /lib/i386-linux-gnu/libcrypt-2.23.so
f5cca000-f5ccb000 rwxp 00009000 08:02 1179186                            /lib/i386-linux-gnu/libcrypt-2.23.so
f5ccb000-f5cf2000 rwxp 00000000 00:00 0 
f5cf2000-f5dcf000 r-xp 00000000 08:02 262232                             /usr/lib/i386-linux-gnu/libsqlite3.so.0.8.6
f5dcf000-f5dd1000 r-xp 000dc000 08:02 262232                             /usr/lib/i386-linux-gnu/libsqlite3.so.0.8.6
f5dd1000-f5dd3000 rwxp 000de000 08:02 262232                             /usr/lib/i386-linux-gnu/libsqlite3.so.0.8.6
f5dd3000-f5e1f000 r-xp 00000000 08:02 265852                             /usr/lib/i386-linux-gnu/libhx509.so.5.0.0
f5e1f000-f5e20000 ---p 0004c000 08:02 265852                             /usr/lib/i386-linux-gnu/libhx509.so.5.0.0
f5e20000-f5e21000 r-xp 0004c000 08:02 265852                             /usr/lib/i386-linux-gnu/libhx509.so.5.0.0
f5e21000-f5e22000 rwxp 0004d000 08:02 265852                             /usr/lib/i386-linux-gnu/libhx509.so.5.0.0
f5e22000-f5e24000 rwxp 00000000 00:00 0 
f5e24000-f5e33000 r-xp 00000000 08:02 265835                             /usr/lib/i386-linux-gnu/libheimbase.so.1.0.0
f5e33000-f5e34000 r-xp 0000e000 08:02 265835                             /usr/lib/i386-linux-gnu/libheimbase.so.1.0.0
f5e34000-f5e35000 rwxp 0000f000 08:02 265835                             /usr/lib/i386-linux-gnu/libheimbase.so.1.0.0
f5e35000-f5e5d000 r-xp 00000000 08:02 265843                             /usr/lib/i386-linux-gnu/libwind.so.0.0.0
f5e5d000-f5e5e000 r-xp 00027000 08:02 265843                             /usr/lib/i386-linux-gnu/libwind.so.0.0.0
f5e5e000-f5e5f000 rwxp 00028000 08:02 265843                             /usr/lib/i386-linux-gnu/libwind.so.0.0.0
f5e5f000-f5ed9000 r-xp 00000000 08:02 262098                             /usr/lib/i386-linux-gnu/libvorbisenc.so.2.0.11
f5ed9000-f5eea000 r-xp 00079000 08:02 262098                             /usr/lib/i386-linux-gnu/libvorbisenc.so.2.0.11
f5eea000-f5eeb000 rwxp 0008a000 08:02 262098                             /usr/lib/i386-linux-gnu/libvorbisenc.so.2.0.11
f5eeb000-f5f49000 r-xp 00000000 08:02 268805                             /usr/lib/i386-linux-gnu/libFLAC.so.8.3.0
f5f49000-f5f4a000 r-xp 0005d000 08:02 268805                             /usr/lib/i386-linux-gnu/libFLAC.so.8.3.0
f5f4a000-f5f4b000 rwxp 0005e000 08:02 268805                             /usr/lib/i386-linux-gnu/libFLAC.so.8.3.0
f5f4b000-f5f62000 r-xp 00000000 08:02 1177508                            /lib/i386-linux-gnu/libnsl-2.23.so
f5f62000-f5f63000 r-xp 00016000 08:02 1177508                            /lib/i386-linux-gnu/libnsl-2.23.so
f5f63000-f5f64000 rwxp 00017000 08:02 1177508                            /lib/i386-linux-gnu/libnsl-2.23.so
f5f64000-f5f67000 rwxp 00000000 00:00 0 
f5f67000-f6012000 r-xp 00000000 08:02 1182096                            /lib/i386-linux-gnu/libgcrypt.so.20.0.5
f6012000-f6013000 r-xp 000aa000 08:02 1182096                            /lib/i386-linux-gnu/libgcrypt.so.20.0.5
f6013000-f6016000 rwxp 000ab000 08:02 1182096                            /lib/i386-linux-gnu/libgcrypt.so.20.0.5
f6016000-f603a000 r-xp 00000000 08:02 1178044                            /lib/i386-linux-gnu/liblzma.so.5.0.0
f603a000-f603b000 r-xp 00023000 08:02 1178044                            /lib/i386-linux-gnu/liblzma.so.5.0.0
f603b000-f603c000 rwxp 00024000 08:02 1178044                            /lib/i386-linux-gnu/liblzma.so.5.0.0
f603c000-f605e000 r-xp 00000000 08:02 1177423                            /lib/i386-linux-gnu/libselinux.so.1
f605e000-f605f000 ---p 00022000 08:02 1177423                            /lib/i386-linux-gnu/libselinux.so.1
f605f000-f6060000 r-xp 00022000 08:02 1177423                            /lib/i386-linux-gnu/libselinux.so.1
f6060000-f6061000 rwxp 00023000 08:02 1177423                            /lib/i386-linux-gnu/libselinux.so.1
f6061000-f6062000 rwxp 00000000 00:00 0 
f6062000-f6078000 r-xp 00000000 08:02 261948                             /usr/lib/i386-linux-gnu/libroken.so.18.1.0
f6078000-f6079000 r-xp 00015000 08:02 261948                             /usr/lib/i386-linux-gnu/libroken.so.18.1.0
f6079000-f607a000 rwxp 00016000 08:02 261948                             /usr/lib/i386-linux-gnu/libroken.so.18.1.0
f607a000-f60b0000 r-xp 00000000 08:02 265833                             /usr/lib/i386-linux-gnu/libhcrypto.so.4.1.0
f60b0000-f60b1000 r-xp 00035000 08:02 265833                             /usr/lib/i386-linux-gnu/libhcrypto.so.4.1.0
f60b1000-f60b2000 rwxp 00036000 08:02 265833                             /usr/lib/i386-linux-gnu/libhcrypto.so.4.1.0
f60b2000-f60b4000 rwxp 00000000 00:00 0 
f60b4000-f6162000 r-xp 00000000 08:02 263473                             /usr/lib/i386-linux-gnu/libasn1.so.8.0.0
f6162000-f6163000 r-xp 000ad000 08:02 263473                             /usr/lib/i386-linux-gnu/libasn1.so.8.0.0
f6163000-f6165000 rwxp 000ae000 08:02 263473                             /usr/lib/i386-linux-gnu/libasn1.so.8.0.0
f6165000-f61f9000 r-xp 00000000 08:02 265862                             /usr/lib/i386-linux-gnu/libkrb5.so.26.0.0
f61f9000-f61fb000 r-xp 00093000 08:02 265862                             /usr/lib/i386-linux-gnu/libkrb5.so.26.0.0
f61fb000-f61fd000 rwxp 00095000 08:02 265862                             /usr/lib/i386-linux-gnu/libkrb5.so.26.0.0
f61fd000-f6205000 r-xp 00000000 08:02 265869                             /usr/lib/i386-linux-gnu/libheimntlm.so.0.1.0
f6205000-f6206000 r-xp 00007000 08:02 265869                             /usr/lib/i386-linux-gnu/libheimntlm.so.0.1.0
f6206000-f6207000 rwxp 00008000 08:02 265869                             /usr/lib/i386-linux-gnu/libheimntlm.so.0.1.0
f6207000-f620a000 r-xp 00000000 08:02 1178071                            /lib/i386-linux-gnu/libkeyutils.so.1.5
f620a000-f620b000 r-xp 00002000 08:02 1178071                            /lib/i386-linux-gnu/libkeyutils.so.1.5
f620b000-f620c000 rwxp 00003000 08:02 1178071                            /lib/i386-linux-gnu/libkeyutils.so.1.5
f620c000-f621f000 r-xp 00000000 08:02 261700                             /usr/lib/i386-linux-gnu/libtasn1.so.6.5.1
f621f000-f6220000 r-xp 00012000 08:02 261700                             /usr/lib/i386-linux-gnu/libtasn1.so.6.5.1
f6220000-f6221000 rwxp 00013000 08:02 261700                             /usr/lib/i386-linux-gnu/libtasn1.so.6.5.1
f6221000-f6222000 rwxp 00000000 00:00 0 
f6222000-f627d000 r-xp 00000000 08:02 261699                             /usr/lib/i386-linux-gnu/libp11-kit.so.0.1.0
f627d000-f627e000 ---p 0005b000 08:02 261699                             /usr/lib/i386-linux-gnu/libp11-kit.so.0.1.0
f627e000-f6283000 r-xp 0005b000 08:02 261699                             /usr/lib/i386-linux-gnu/libp11-kit.so.0.1.0
f6283000-f6284000 rwxp 00060000 08:02 261699                             /usr/lib/i386-linux-gnu/libp11-kit.so.0.1.0
f6284000-f6289000 r-xp 00000000 08:02 262698                             /usr/lib/i386-linux-gnu/libXdmcp.so.6.0.0
f6289000-f628a000 r-xp 00004000 08:02 262698                             /usr/lib/i386-linux-gnu/libXdmcp.so.6.0.0
f628a000-f628b000 rwxp 00005000 08:02 262698                             /usr/lib/i386-linux-gnu/libXdmcp.so.6.0.0
f628b000-f628d000 r-xp 00000000 08:02 269987                             /usr/lib/i386-linux-gnu/libXau.so.6.0.0
f628d000-f628e000 r-xp 00001000 08:02 269987                             /usr/lib/i386-linux-gnu/libXau.so.6.0.0
f628e000-f628f000 rwxp 00002000 08:02 269987                             /usr/lib/i386-linux-gnu/libXau.so.6.0.0
f628f000-f6294000 r-xp 00000000 08:02 265579                             /usr/lib/i386-linux-gnu/libasyncns.so.0.3.1
f6294000-f6295000 r-xp 00004000 08:02 265579                             /usr/lib/i386-linux-gnu/libasyncns.so.0.3.1
f6295000-f6296000 rwxp 00005000 08:02 265579                             /usr/lib/i386-linux-gnu/libasyncns.so.0.3.1
f6296000-f6308000 r-xp 00000000 08:02 263595                             /usr/lib/i386-linux-gnu/libsndfile.so.1.0.25
f6308000-f6309000 ---p 00072000 08:02 263595                             /usr/lib/i386-linux-gnu/libsndfile.so.1.0.25
f6309000-f630a000 r-xp 00072000 08:02 263595                             /usr/lib/i386-linux-gnu/libsndfile.so.1.0.25
f630a000-f630b000 rwxp 00073000 08:02 263595                             /usr/lib/i386-linux-gnu/libsndfile.so.1.0.25
f630b000-f6310000 rwxp 00000000 00:00 0 
f6310000-f6318000 r-xp 00000000 08:02 1178087                            /lib/i386-linux-gnu/libwrap.so.0.7.6
f6318000-f6319000 r-xp 00007000 08:02 1178087                            /lib/i386-linux-gnu/libwrap.so.0.7.6
f6319000-f631a000 rwxp 00008000 08:02 1178087                            /lib/i386-linux-gnu/libwrap.so.0.7.6
f631a000-f63a5000 r-xp 00000000 08:02 1178791                            /lib/i386-linux-gnu/libsystemd.so.0.14.0
f63a5000-f63a7000 r-xp 0008a000 08:02 1178791                            /lib/i386-linux-gnu/libsystemd.so.0.14.0
f63a7000-f63a8000 rwxp 0008c000 08:02 1178791                            /lib/i386-linux-gnu/libsystemd.so.0.14.0
f63a8000-f63ec000 r-xp 00000000 08:02 265877                             /usr/lib/i386-linux-gnu/libgssapi.so.3.0.0
f63ec000-f63ed000 r-xp 00043000 08:02 265877                             /usr/lib/i386-linux-gnu/libgssapi.so.3.0.0
f63ed000-f63ee000 rwxp 00044000 08:02 265877                             /usr/lib/i386-linux-gnu/libgssapi.so.3.0.0
f63ee000-f63ef000 rwxp 00000000 00:00 0 
f63ef000-f640b000 r-xp 00000000 08:02 270104                             /usr/lib/i386-linux-gnu/libsasl2.so.2.0.25
f640b000-f640c000 r-xp 0001b000 08:02 270104                             /usr/lib/i386-linux-gnu/libsasl2.so.2.0.25
f640c000-f640d000 rwxp 0001c000 08:02 270104                             /usr/lib/i386-linux-gnu/libsasl2.so.2.0.25
f640d000-f6421000 r-xp 00000000 08:02 1179182                            /lib/i386-linux-gnu/libresolv-2.23.so
f6421000-f6422000 ---p 00014000 08:02 1179182                            /lib/i386-linux-gnu/libresolv-2.23.so
f6422000-f6423000 r-xp 00014000 08:02 1179182                            /lib/i386-linux-gnu/libresolv-2.23.so
f6423000-f6424000 rwxp 00015000 08:02 1179182                            /lib/i386-linux-gnu/libresolv-2.23.so
f6424000-f6427000 rwxp 00000000 00:00 0 
f6427000-f6432000 r-xp 00000000 08:02 262114                             /usr/lib/i386-linux-gnu/libkrb5support.so.0.1
f6432000-f6433000 r-xp 0000a000 08:02 262114                             /usr/lib/i386-linux-gnu/libkrb5support.so.0.1
f6433000-f6434000 rwxp 0000b000 08:02 262114                             /usr/lib/i386-linux-gnu/libkrb5support.so.0.1
f6434000-f6437000 r-xp 00000000 08:02 1177935                            /lib/i386-linux-gnu/libcom_err.so.2.1
f6437000-f6438000 r-xp 00002000 08:02 1177935                            /lib/i386-linux-gnu/libcom_err.so.2.1
f6438000-f6439000 rwxp 00003000 08:02 1177935                            /lib/i386-linux-gnu/libcom_err.so.2.1
f6439000-f6467000 r-xp 00000000 08:02 261943                             /usr/lib/i386-linux-gnu/libk5crypto.so.3.1
f6467000-f6468000 ---p 0002e000 08:02 261943                             /usr/lib/i386-linux-gnu/libk5crypto.so.3.1
f6468000-f6469000 r-xp 0002e000 08:02 261943                             /usr/lib/i386-linux-gnu/libk5crypto.so.3.1
f6469000-f646a000 rwxp 0002f000 08:02 261943                             /usr/lib/i386-linux-gnu/libk5crypto.so.3.1
f646a000-f6539000 r-xp 00000000 08:02 263274                             /usr/lib/i386-linux-gnu/libkrb5.so.3.3
f6539000-f653a000 ---p 000cf000 08:02 263274                             /usr/lib/i386-linux-gnu/libkrb5.so.3.3
f653a000-f6540000 r-xp 000cf000 08:02 263274                             /usr/lib/i386-linux-gnu/libkrb5.so.3.3
f6540000-f6541000 rwxp 000d5000 08:02 263274                             /usr/lib/i386-linux-gnu/libkrb5.so.3.3Afgebroken
```

**Comment by janisozaur** [comment]
I've simplified the code a lot, at @IntelOrca's suggestion, not really sure how did I not do that in the first place.

Please let it be the the end of it now. If it is, I'll squash the commits here.

**Comment by janisozaur** [comment]
All done now, squashed and the missing `desc` setup fixed as well.

**Pull request merged**
