### PR TITLE
Treat warnings as errors in Xcode project

### PR DESCRIPTION
**Pull request by marijnvdwerf**
Any other stuff that should be turned on?

image
image
image
image
image
image
image

### CODE REVIEW

**Comment by IntelOrca** [comment]
non-virtual destructor sounds useful

**Comment by janisozaur** [comment]
@marijnvdwerf you can check if you can enable any of them based on our `CMakeLists.txt`, it already has quite a few. It will make it less likely for you to do something that will error on Travis.

**Comment by janisozaur** [comment]
@marijnvdwerf any chance of `make -k`-like build?

**Comment by marijnvdwerf** [comment]
@janisozaur So, having warnings as warnings instead of errors?

**Comment by janisozaur** [comment]
@marijnvdwerf having warnings as errors, but ignoring errors till you cannot go any further.

**Pull request closed without merging**
