### PR TITLE
Changing some default configs to true

### PR DESCRIPTION
**Pull request by Nubbie**
**Now why would you want that;**
When new players start the game, they might miss out of features that have been added to the game they would never see, people have always asked questions about stuff as they haven't looked through options that good, maybe didn't even find where the options where or understood all the different options very well.
---
### Reasoning for all changes:

~~**Uncap Fps:** Most computers/average players wouldn't mind a small boost in frames, might leave some smaller artifacts, something the average joe wouldn't notice~~
~~**Test unfinished tracks:** People like to see crashes and this feature was implanted in OpenRCT2~~
**Auto Staff:**: Feature added + most people spam the button to get staff
~~**Day and Night:** New _impressive_ feature~~
**Allow loading of incorrect checksum:** Might leave artifact but players would be more happy to play the map instead of not being about to load it and trying to find some support that could take a while
~~**Auto open shops:** New park, a ton of stores, easy and quick - OpenRCT2 feature~~
~~**Show cheats:** One FAQ is where to find/use cheats, enabling it will get so more curious people can find it easily which wouldn't be a bad idea~~
**Advertise:** If you want to play private or public, you often want to advertise the server making it easier to find instead off fumbling around with IP's and/or player names 

Finances & Research buttons - Enabled in the toolbar, suggested by @AaronVanGeffen 

Thoughts? 
_(If nono, close the PR)_

### CODE REVIEW

**Comment by IntelOrca** [comment]
Uncap Fps: Agree
Test unfinished tracks: Don't agree, its unstable too - wait until we have ghost trains
Auto Staff: Possibly but its not obvious that you have to shift click to manually place, I think RCT3 handled it by auto placing the last non-placed staff if you click the button again.
Day and Night: Potentially, depends what others think
Allow loading of incorrect checksum: Agree, checksums for objects are already ignored - it can avoid crashes though should parks get corrupted
Auto open shops: Don't agree in the players should learn about closing and opening things when learning the game.
Show cheats: Don't agree, I want to try and prevent cheats for scenarios until enabled which then disables winning it. But this will have to wait until we have our own save format.
Advertise: I don't think this is a big deal, its shown when you create the server

**Comment by pizza2004** [comment]
What are the benefits of uncap FPS being on rather than off?

**Comment by Nubbie** [comment]
@pizza2004 More people would prefare seeing the game run smoother, it's a feature that OpenRCT2 introduced, the average joe wants the best quality and the best fps as possible, seeing 60 instead of 40 is noticable

**Comment by janisozaur** [comment]
> **Uncap Fps**: Most computers/average players wouldn't mind a small boost in frames, might leave some smaller artifacts, something the average joe wouldn't notice

"Most" is not "all". This can be enabled for x86 and even more so x86-64 builds, but I don't think it would be good for other ones.

**Comment by Nubbie** [comment]
@janisozaur 
>but I don't think it would be good for other ones.

Are we talking about operative systems? Or is there any bugs that I'm missing? - the game does look smoother with this enabled which I think more people would appriciate, like how 'zoom toward cursor' got enabled by default

**Comment by janisozaur** [comment]
No, operating system doesn't matter that much, it's the hardware that runs it. I think arm devices struggle already as it is (as indicated by recent android builds) and tasking them with even more FP work won't do much good.

**Comment by Nubbie** [comment]
@janisozaur That is something I can agree with, 'arm devices' shouldn't have it automaticlly set to true, these changes are with computers in mind, if the mobile would use the same setting then I presume it has to be set to off - would be best if it would be true on computers and false on phones

**Comment by Gymnasiast** [comment]
I mostly agree with IntelOrca, though janisozaur has a good point regarding the uncap FPS option. 
(BTW, even my PC struggles getting 25 FPS, never mind 40._

**Comment by janisozaur** [comment]
@Gymnasiast are you sure you're building in release mode?

@Nubbie arm does not imply phones (nor does phone/android imply arm), there are plenty of other devices using it.

**Comment by Nubbie** [comment]
@janisozaur Saw the chat and notice it's wide spread for most devices :p 
Just mean the mainstream use as not that many will try to put it in a calculator

**Comment by Margen67** [comment]
Do you mean 3DS? @Nubbie

**Comment by IntelOrca** [comment]
@janisozaur Uncap FPS will only tween frames if there is spare time to do so, so I wouldn't of thought it would be a performance impact.

**Comment by AaronVanGeffen** [comment]
> **Day and Night:** New impressive feature

Because we currently can't draw the interface separately from the rest of the game canvas, the Day/Night cycle obscures the interface somewhat. As such, I'd rather leave it off by default, for the moment.

While we're at it, I would like to propose we enable the Finances and Research buttons by default, too. It makes it much easier for new players to have an actual button for them, rather than having to resort to clicking the current amount of money or using a shortcut.

**Comment by duncanspumpkin** [comment]
Uncap frame rates causes issues on busy parks but I'm not that fussed with changing that default. Other than that agree with intel

**Comment by Gymnasiast** [comment]
> While we're at it, I would like to propose we enable the Finances and Research buttons by default, too. It makes it much easier for new players to have an actual button for them, rather than having to resort to clicking the current amount of money or using a shortcut.

I thought we already did this? If not, I agree it should be enabled by default.

**Comment by IntelOrca** [comment]
@Gymnasiast I enabled the research button by default because it was otherwise impossible to get to (apart from shortcut) when no money is enabled. But the others I didn't bother because RCT2 didn't.

**Comment by Nubbie** [comment]
@AaronVanGeffen @Gymnasiast Thought about it for a while but never activated it as 'it might cluster up the toolbar' but could will do now

@duncanspumpkin If the park gets busy, the FPS would/should shrink even with uncap fps on/off

**Comment by duncanspumpkin** [comment]
@Nubbie i said it causes issues not that it effects the FPS. Uncap will speed up the game at low frame rates rather than let the game run in slow mode mode. It can be argued that Uncap is better though so I'm not overly fussed.

**Comment by Nubbie** [comment]
The only thing I have no clue about is the Uncap fps, but I guess it will be what it is now. Off

**Comment by duncanspumpkin** [comment]
Day/night cycle should really stay off until it no longer effects the whole interface.

**Comment by AaronVanGeffen** [comment]
That seems to be the case in Nubbie's ec8a5ae already — he just added a comment about why it's not `true` by default.

**Comment by Nubbie** [comment]
The only things changed;

**Auto Staff:** Feature added + most people spam the button to get staff
**Allow loading of incorrect checksum:** Might leave artifact but players would be more happy to play the map instead of not being about to load it and trying to find some support that could take a while
**Finances & Research buttons** - Enabled in the toolbar, suggested by @AaronVanGeffen 
**Advertise:** If you want to play private or public, you often want to advertise the server making it easier to find instead off fumbling around with IP's and/or player names 

Only things changed with 2 comments, not much but something

**Comment by Nubbie** [comment]
**NEW QUESTION;**
Should 'Export plug-in objects with saved files' be true?
**Why?** 
File size isn't often the issue and if you delete the custom objects, I think, the map is unplayable as you're missing stuff

**Comment by Gymnasiast** [comment]
Yes, export should be on by default, I think.

**Comment by Nubbie** [comment]
@Gymnasiast The question was directed to you by [Intel from gitter](https://gitter.im/OpenRCT2/OpenRCT2?at=5809317f80020cc608fc4d64) so I presume that's enough for a change

**Comment by Gymnasiast** [comment]
I'd like to see `test_unfinished_tracks` changed back. Otherwise I'm ok with this PR.

**Comment by Nubbie** [comment]
@gymnasiast ``test_unfinished_track`` is off but with a comment only
"//Default config setting is false until ghost trains are implemented #4540"

**Pull request merged**
