### PR TITLE
Fixes #3942 -- Attempted fix of uninstaller for Windows

### LINKED ISSUE #3942: Uninstalling doesn't remove every file
When I uninstall OpenRCT, wherever I installed the thing at first, it leaves behind several things:

- known_issues.txt
- a folder called 'data' with stuff inside
- OGLdpf.log
- curl-ca-bundle.crt

Does this means my computer is infected with a virus? No, j/k. But I wonder if this is necessary for some reason, or simply an oversight!

### PR DESCRIPTION
**Pull request by RedMarcher**
I will admit, I'm not too familiar with writing exes, but this bug seemed like it shouldn't be too hard to fix, and it was open for a really long time.

I'm a little unclear about how rmdir works. Does windows even have rmdir recursively? I think that might be why the data folder isn't getting deleted properly.

### CODE REVIEW

**Comment by janisozaur** [comment]
https://nsis.sourceforge.io/Reference/RMDir

Also rename your PR to match https://github.blog/news-insights/product-news/closing-issues-via-commit-messages/

**Comment by RedMarcher** [comment]
Hmm, I can't think of any reason why data wouldn't be deleted by the recursive command. Maybe there's something going on with permissions. Either way, this should at least get rid of the other files that person mentioned in their issue.

**Comment by duncanspumpkin** [comment]
> Hmm, I can't think of any reason why data wouldn't be deleted by the recursive command. Maybe there's something going on with permissions. Either way, this should at least get rid of the other files that person mentioned in their issue.

Its quite an old issue are we even sure its still an issue.

**Comment by RedMarcher** [comment]
> > Hmm, I can't think of any reason why data wouldn't be deleted by the recursive command. Maybe there's something going on with permissions. Either way, this should at least get rid of the other files that person mentioned in their issue.
> 
> Its quite an old issue are we even sure its still an issue.

Well, I assumed it was still a problem because no one bothered to close it. either way, I don't adding those other files they mentioned to the delete list should cause any problems.

**Pull request closed without merging**
