### PR TITLE
Fix Clear Scenery refunding ghost tile elements

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Nice catch. How did you get ghost elements to exist while using the clear scenery tool, though?

**Comment by Gymnasiast** [comment]
@AaronVanGeffen You can have path ghosts while using the Clear Scenery tool. The video that reported this bug can be reported here: https://www.reddit.com/r/rct/comments/fj15i7/came_across_this_money_glitch_in_open_rct2_is/

**Comment by duncanspumpkin** [comment]
Did you increment the network version after this?

**Comment by Gymnasiast** [comment]
I have now.

**Pull request merged**
