### PR TITLE
Fix: page dropdown isn't appear in guest list window.

### PR DESCRIPTION
**Pull request by Wirlie**
This fixes this bug: https://github.com/OpenRCT2/OpenRCT2/pull/3977#issuecomment-231214127

scr45

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Out of interest: would this be easily applicable the other lists? More specifically: the object selection list?

**Comment by Wirlie** [comment]
I guess that yes. Just add the drop-down widget and apply the same logic of this window, not seems complicated. 

Additionally, I've seen that it can be divided into pages at a certain height (for example, every 2000 guests), not necessarily at the "maximum height" of the scroll (3173 guests).

**Comment by Gymnasiast** [comment]
There is something wrong. Every page has entries A-Z, sometimes even followed by A again. What I would expect is Page 2 continuing where Page 1 left off.

scr211

**Comment by Wirlie** [comment]
I think that this is another bug?
Screenshot taken from the vanilla game:
scr1

And, try this:
scr48
scr49

**Comment by Gymnasiast** [comment]
I already said it is another bug, it has to do with how OpenRCT2 sorts its guest list. I'll merge as it is, but the broken sorting needs an Issue report.

**Comment by Wirlie** [comment]
Oh sorry, I did not read well. Thanks! i'll see if I can find the problem.

**Pull request merged**
