### PR TITLE
Refactor PeepRideSubState to enum class

### PR DESCRIPTION
**Pull request by rpstester**
This is my second PR; it addresses #12390.  Please let me know if you have any feedback. Thanks!

### CODE REVIEW

**Review by duncanspumpkin — COMMENTED** [review]
Add yourself to contributors.md under bug fixes.

Please remember the commit message style  https://github.com/OpenRCT2/OpenRCT2/wiki/Commit-Messages
I'll tidy the current commit up on merge so no need to adjust it atm.

This all looks correct but I'll do some other little checks to make sure nothing has been missed.

**Comment by rpstester** [comment]
I didn't mean for this 9eedea1 to show up here; I don't know what I did, and I apologize.

**Comment by tupaschoal** [comment]
> I didn't mean for this [9eedea1](https://github.com/OpenRCT2/OpenRCT2/commit/9eedea162588ecf928e6f290d8dd92ba2dc9cff7) to show up here; I don't know what I did, and I apologize.

It's alright, it happens. You can try fixing it manually doing what is described here: https://github.com/OpenRCT2/OpenRCT2/wiki/Rebase-and-Sync-fork-with-OpenRCT2

**Comment by duncanspumpkin** [comment]
The problem is you have worked on the develop branch. This causes a good few headaches rebasing. Can you make the commented changes

**Comment by duncanspumpkin** [comment]
Ah never mind you did a separate pr for the contributors. This is now fine for a squash merge

**Comment by rpstester** [comment]
Thanks, @duncanspumpkin . I think I got the idea of branching to do changes on my fork.

**Comment by rpstester** [comment]
Thanks, @tupaschoal . I think I'll wait until this PR is complete so I don't affect it again unintentionally. Then I'll try those steps to get in sync.

**Comment by rpstester** [comment]
OK, apparently trying to get my branch up to date causes this PR to change.  So let me close this and start cleanly.

**Comment by tupaschoal** [comment]
That's because you made the changes on your `develop` branch. You should always create a new branch and keep the `develop` untouched (apart from pulling syncing it with our repo(

**Pull request closed without merging**
