### PR TITLE
Use ccache on macos CI jobs

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by janisozaur** [comment]
Of course it doesn't work. Who volunteers to fix whatever it is that xcode project needs fixed?

**Comment by AaronVanGeffen** [comment]
The Xcode project doesn't use the `scripts/setenv` script.

**Comment by janisozaur** [comment]
The CI job does, though:

https://github.com/OpenRCT2/OpenRCT2/blob/6e20f41d3ce2ffccc9d81b092a6d1828cfe2b402/.github/workflows/ci.yml#L131-L132

**Comment by janisozaur** [comment]
@adam-bloom would you like to take a look at this?

Worked like a charm now with sane build system:
```
cache directory                     /Users/runner/work/OpenRCT2/OpenRCT2/.ccache
primary config                      /Users/runner/Library/Preferences/ccache/ccache.conf
secondary config (readonly)         /usr/local/Cellar/ccache/4.2/etc/ccache.conf
stats updated                       Mon Mar  1 21:29:08 2021
stats zeroed                        Mon Mar  1 21:19:48 2021
cache hit (direct)                     0
cache hit (preprocessed)               0
cache miss                          1155
cache hit rate                      0.00 %
called for link                       69
called for preprocessing             565
can't use modules                      6
cleanups performed                     0
files in cache                      2310
cache size                          42.2 MB
max cache size                     500.0 MB
```

**Pull request merged**
