### PR TITLE
Integrate Map window's land ownership tool in LandRights window

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
This PR moves the land ownership tool from the Map window to the Land Rights window. The latter has been refactored in the process.

The [LandSetRightsAction](https://github.com/OpenRCT2/OpenRCT2/pull/22490/commits/5d5a209398deba1a87165582c603560be7285d9b) has been changed such that cost calculation is based on whether it concerns land or construction rights. It now also acts as buying or selling, in that removing ownership now _yields_ the purchase price. Previously, it would still deduct money if ownership were removed! **NB:** This change necessitates incrementing the network version, which has not yet been done.

The Land Rights window during normal gameplay (unchanged):
Forest Frontiers 2024-08-05 19-40-29

The Land Rights window in sandbox mode:
Forest Frontiers 2024-08-09 22-38-45

### CODE REVIEW

**Comment by sta5is** [comment]
For the Land Rights window, would it be better if instead of checkboxes, it should be drop-down menu because only one item can be selected at a time? Checkboxes are used elsewhere in the game for being able to select multiple items like the scenery object window.

**Comment by AaronVanGeffen** [comment]
These checkboxes act as radio buttons, indeed. It's been discussed before to add proper radio buttons to the game, so there is no confusion. While you're right a dropdown widget would be more consistent, I feel like it would be a step backwards functionally. Now, it takes only one click to switch modes, while a dropdown would take two. I therefore prefer to leave it as-is.

**Comment by sta5is** [comment]
I see. I like how you added the "Land Not Owned" option among the selections. Previously, it was only accessible if no boxes were checked and I felt that was not conveyed to the user in an intuitive manner. Great work there.

**Comment by AaronVanGeffen** [comment]
Changed the widget colours a little bit so they blend in better, imo.

Before:
Forest Frontiers 2024-08-05 19-41-17

Now:
Forest Frontiers 2024-08-09 22-38-45

**Review by Gymnasiast — APPROVED** [review]

**Comment by J-PIE-314** [comment]
There is a minor issue. Part of the text disappears at times.

https://github.com/user-attachments/assets/8281e26f-4c78-44d6-ad84-da288acb8ddf

**Comment by AaronVanGeffen** [comment]
> There is a minor issue. Part of the text disappears at times.

That looks like an invalidation issue. Maybe the checkbox widgets aren't of the right length (i.e. too short). I remember copying them from the old window, but looking at the diff, apparently they were shrunk from 180px to 100px at some point. Will file a quick patch.

**Pull request merged**
