### PR TITLE
Display message with chat shortcut keys upon connection

### PR DESCRIPTION
**Pull request by janisozaur**
Works for server as well. Gets currently bound shortcut key(s).

So many people ask "how to chat in multiplayer", just check the forums or reddit…

### CODE REVIEW

**Comment by janisozaur** [comment]
zaznaczenie_012

**Comment by Gymnasiast** [comment]
Good idea :+1:

**Comment by IntelOrca** [comment]
Hmm, is this just temporary until people know? Seems obsessive otherwise, we could I suppose have a chat drop down item on the multiplayer button.

We could also add message of the day (set in config.ini) which is displayed to the user when they join - this logic can be shared with that.

**Comment by janisozaur** [comment]
> Hmm, is this just temporary until people know?

It can be. Though apparently people get confused and ask this question a lot. I think it may be worth having in 0.0.4

**Comment by duncanspumpkin** [comment]
I've seen it in a few games WorldOfTanks for example where every single match you join it always states the chat button. I quite like the idea.

**Pull request merged**
