### PR TITLE
Implement CTRL-Backspace shortcut for clearing inputs, fixes #2355

### LINKED ISSUE #2355: Hotkeys for clearing the input boxes
For example, I can use Ctrl+U to clear the input boxes in openttd.
I think some kind of similar hotkey is needed in openrct2 as well.

### PR DESCRIPTION
**Pull request by samdroid-apps**
Replaces #2413

Tested against the twitch text box and the multiplayer name text box.

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
Ctrl+backspace is normally delete word not clear all input.

**Comment by Gymnasiast** [comment]
How about SHIFT + backspace?

**Comment by IntelOrca** [comment]
I think this is what OpenTTD do.

**Comment by Gymnasiast** [comment]
Perhaps we could make it an adjustable shortcut then?

**Comment by LinusU** [comment]
On OS X the convention is to do `⌘` + `Backspace` to clear the entire line. Then again, most things that are `ctrl` on windows is `⌘` on OS X. How should we go about solving this?

**Comment by IntelOrca** [comment]
@LinusU If you look further down in shared.c, you will see a #ifdef for OSX where it uses KMOD_GUI instead of KMOD_CTRL. This is how how you would do it, but I think it would be more elegant to define a new #define which maps to KMOD_CTRL or KMOD_GUI depending on whether its compiling for OSX.

**Comment by LinusU** [comment]
I don't think that `#ifdef` will work because `MAC` isn't defined anywhere. I'm sending a pull request in a few minutes that uses a new `#define` as you suggested :)

**Pull request merged**
