### PR TITLE
Add classic wooden twister

### PR DESCRIPTION
**Pull request by Gymnasiast**
A huge thanks to mix for implementing the majority of drawing code.

Depends on an object that needs to be merged, and put into an objects release. I haven’t yet had the time to look through all of mix’ additions but I figured I’d put it out here for testing/reviewing already.

afbeelding

### CODE REVIEW

**Comment by ZeeMaji** [comment]
The classic wooden twister needs the medium & large half loops as well as boosters added to it's extra pieces.

Additionally the vehicle object ID used for importing seems to be outdated, the final vehicle object is going to have an ID of "rct1aa.ride.wooden_articulated_trains"

Need to look at this a bit more after reviewing something else, these are just some surface level things i noticed while glancing through this PR.

**Comment by ZeeMaji** [comment]
The (un)banking slope turns need to be added to the regular track pieces group.

**Comment by ZeeMaji** [comment]
The classic twister is using the wrong preview image for it's track painting, it needs to use the regular wooden coaster's preview rather than the classic wooden coaster's.
Screenshot at 2024-11-19 11-14-57

**Comment by ZeeMaji** [comment]
The base ratings data is incorrect, it should be the same as the RCT2 wooden coaster. presently it's the same as the classic wooden coaster so the excitement stat is lower than it should be.

**Comment by ZeeMaji** [comment]
Is it desireable to keep the light blue, black, dark brown track color preset that was added to the wooden coaster in OpenRCT2 that has been carried over to this? The rest of the color presets were in RCT1.

**Comment by Gymnasiast** [comment]
Since this is mostly there for compatibility with RCT1, I would personally stick to what was in vanilla RCT1.

**Comment by ZeeMaji** [comment]
The wooden twister also still has the same stat requirement punishments as the classic wooden coaster in that your intensity is unaffected by failing stat requirements, this needs to be changed back to the RCT2 wooden coaster's punishment which does affect stat requirements.

**Review by ZeeMaji — APPROVED** [review]
Played around with this a lot, i think all of the RTD metadata is now correct at this point and i haven't noticed any issues with the altered track pieces. Everything is working as expected.

**Pull request merged**
