### PR TITLE
Reduce guests walking through trains on level crossing next to station

### LINKED ISSUE #18490: guests walk through trains on level crossing right next to station
### Operating System

Ubuntu Linux 20.04.5

### OpenRCT2 build

afd0346 develop

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

Guests waiting for a stopped train to vacate a level crossing resume walking too early if there is a station directly next to the crossing:

https://user-images.githubusercontent.com/29800630/199559043-732885c3-d6e2-4c57-8822-834cf2681038.mp4

I don't think it's related to #18245 or #18453: I've observed this quite a while ago already. I just never got around to filing the bug.

### Steps to reproduce

- Build a level crossing directly behind a train station
- have enough trains for an arriving train to not immediately fit into the station
- guests resume walking before the train has completely left the level crossing

(see attached park)

### Attachments

[walking_through_trains.zip](https://github.com/OpenRCT2/OpenRCT2/files/9922863/walking_through_trains.zip)

### PR DESCRIPTION
**Pull request by rik-smeets**
See #18490. This doesn't fully resolve all issues (see testing results by @cheweytoo below), but it's a step in the right direction.

### CODE REVIEW

**Comment by cheweytoo** [comment]
Using the Linux AppImage build from build from https://github.com/OpenRCT2/OpenRCT2/actions/runs/4391879705 with the park from https://github.com/OpenRCT2/OpenRCT2/issues/18895 :

https://user-images.githubusercontent.com/29800630/225086492-96521463-22ef-4ddd-a198-7161ddec20bb.mp4

There are way fewer walks through _departing_ trains. It still happens though, see e.g. the green peep at 00:50. And the train is juuuust missing the slow nauseated peep at 00:30.

Walking through _arriving_ trains looks way reduced too - however, there is quite a bit of walking through the "third train" (the one behind the one behind the one in the station) going on. See e.g. 00:04, 00:20 (not even really a 3rd train), or 01:48.

Still, it's clearly improved compared to before: I'd vote for merging this.

**Comment by cheweytoo** [comment]
Walking through arriving train at 00:48 (second part of video from previous comment):


https://user-images.githubusercontent.com/29800630/225087814-5158a411-aa1f-4a4c-887a-bbdfbbbb3754.mp4

**Comment by rik-smeets** [comment]
Thanks for testing, @cheweytoo! 
To further improve upon this, some more complex changes have to be made regarding departing changes. I also agree we could merge this for the time being, and look for further improvements in the future.

**Review by Broxzier — APPROVED** [review]
This improves it a lot, but as in the videos posted above, guests still walk through sometimes. I suspect that's because there are multiple vehicles blocking the same crossing. To fix this, the system itself needs to be refactored quite some, I'm afraid. I'm good with this getting merged as is.

**Comment by ZehMatt** [comment]
Might get away with raising the network version only once if we merge both PRs at the same time then you can avoid doing that twice.

**Comment by rik-smeets** [comment]
> Might get away with raising the network version only once if we merge both PRs at the same time then you can avoid doing that twice.

There will probably be some merge conflicts with the changelog anyway, so I'll just bump the version twice :)

**Pull request merged**
