### PR TITLE
Fix #22077: Diagonal flat chained/unchained reversed

### LINKED ISSUE #22077: Flat diagonal mine train coaster track draws with chain lift sprite
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2 0.4.11-137-bbb5b92

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

Flat diagonal mine train coaster track draws with chain lift sprite. 
If it is built with chain lift enabled, it draws without chain lift sprite
image

### Steps to reproduce

Build flat diagonal mine train coaster track with and without chain lift sprite

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by Gymnasiast** [comment]
@deurklink Could you test?

**Comment by deurklink** [comment]
> @deurklink Could you test?

Tested it with mine train coaster track and other track types, it seems to work fine now

**Review by AaronVanGeffen — APPROVED** [review]

**Comment by AaronVanGeffen** [comment]
Does this require a changelog entry, or is it a recent regression?

**Comment by Gymnasiast** [comment]
It’s a regression introduced after the last release.

**Pull request merged**
