### PR TITLE
Fix peep interactions with provisional paths

### PR DESCRIPTION
**Pull request by manuelVo**
Currently provisional paths (the preview of the path builder tool) are treated almost like paths that were already built. They affect the path finding algorithm, (temporarily) remove scenery like benches and bins and staff even walks over them. Since provisional paths aren't synced in multiplayer this causes quite a lot of desync.
These bugs also cause problems in singleplayer since you can accidentally drown a employee that decided to walk over a bridge that wasn't built yet.

This PR makes peeps ignore provisional paths. This even allows peeps to sit on benches which are currently hidden by the path builder. While this looks quite odd I wouldn't consider it a bug since the bench isn't actually gone but just hidden for the sake of previewing what would happen if the path was built. Also peeps that already sit on the bench is hidden don't stand up either.

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
How is this performance wise that's quite a lot of extra code that will be called very often

**Comment by manuelVo** [comment]
I don't notice any performance impact. I get about 22 fps capped and 18 uncapped in my ~3.5k peep park on both develop and this branch.

There is also a second option to have a second path.edges property which has the ghost edges cleaned out already (I tried to do that with path.edges but unsurprisingly it screws up the drawing). Next to removing any possible performance impact this would also lead to cleaner code. If we want to go that way I'd definitely need some help since I have no clue how changes to the data model will affect RCT2 compatibility.

**Comment by duncanspumpkin** [comment]
Yes that would be a better option but unfortunately that would require a huge refactor to work as it's modifying the map element structure size. Perhaps we could attack this from the other side and make painting check for possible ghost joins and not do the join in the ghost placement

**Comment by manuelVo** [comment]
We would at least screw up the original renderer that way. At least I don't see any options to keep it without building some code that is either very slow or very nasty.

**Comment by zsilencer** [comment]
Would it work to just remove the provisional path before peep update and then put it back?

**Comment by manuelVo** [comment]
I just updated this PR to fix the bug the way @zsilencer proposed. It works very nicely and the code looks much cleaner. Also this fixes a desync bug with queues that i was unable to resolve with the old code. Only drawback: While the old code was a good foundation to fix the same bug when building shops or entrances i don't really see how to go further with that from here.

**Comment by IntelOrca** [comment]
I agree that this is a good make-do solution until we are able to store more data per map element.

**Comment by manuelVo** [comment]
I moved the remove/restore logic into a function

**Comment by IntelOrca** [comment]
@duncanspumpkin happy with this?

**Comment by duncanspumpkin** [comment]
Yeah i think so. I had one thought about how do track design previews effect this but it doesnt matter at present as multiplayer doesnt have tracks.

**Comment by Gymnasiast** [comment]
Do we merge this for 0.0.5 or after?

**Pull request merged**
