### PR TITLE
LIM Sprites for Giga and Steel Twister

### PR DESCRIPTION
**Pull request by YoloSweggLord**
This commit adds new sprites to G2.DAT. This PR doesn't add in the drawing code-- That will have to wait until #5072 is merged, though I believe @X123M3-256 got it into working order on his own build.
Let me know if I'm doing anything wrong here, as I'm new to the contribution system.

### CODE REVIEW

**Comment by YoloSweggLord** [comment]
Just to clarify, the LIM sprite designs are my own design, not the ones from RCTC (I'm well aware of the problems that would bring)

**Comment by janisozaur** [comment]
Please optimise those PNGs and amend your commit.

**Comment by YoloSweggLord** [comment]
I believe I've gotten rid of the extraneous information in the files. I got them down to 805, 717, 713, and 670 bytes, respectively to their numerical order.

**Comment by marijnvdwerf** [comment]
What image optimiser are you using? ImageOptim is able to decrease the file size still a lot more. 
image

**Comment by janisozaur** [comment]
Let's begin with the fact these images are still 32bpp…

**Comment by YoloSweggLord** [comment]
>What image optimiser are you using? ImageOptim is able to decrease the file size still a lot more.
I figured out the problem there... I had optimized them, but I uploaded the wrong files there. The files I uploaded in the commit were from a previous attempt at seeing just how optimized GIMP could get... but the *correct* optimized files were optimized with FileOptimizer (ImageOptim doesn't have a Windows build.) Their file sizes are 443, 419, 429, and 385 bytes.

>Let's begin with the fact these images are still 32bpp…
Forgive me, I didn't take bpp into consideration. What BPP should I be using for G2 sprites?

**Comment by janisozaur** [comment]
8. The sprites actually only have 20-odd colours, so any optimiser should change it to 8bpp for you.

**Comment by IntelOrca** [comment]
Ideally you want to create g2.dat, then export them out again as it will ensure you have identical colours to what is used in the game.

**Comment by Gymnasiast** [comment]
Can any of you verify if the optimised files that YoloSweggLord put into his latest commit are now good enough?

**Comment by YoloSweggLord** [comment]
In addition, the sprite names need to be changed as '80' was taken by another sprite since these were created.

**Comment by YoloSweggLord** [comment]
On second thought, why don't I wait until #5072 is completed, so that in case any more sprites get added in the meantime, I don't have to keep fixing the filenames.

**Comment by Gymnasiast** [comment]
I doubt #5072 is going to be merged soon, as it is unfinished. Since you optimised the files it should be just a matter of rebasing now. This PR has taken too much time in any case.

**Comment by YoloSweggLord** [comment]
>I doubt #5072 is going to be merged soon, as it is unfinished.

You're probably right... I guess I should have waited until I knew the could be implemented completely before making this.
>Since you optimised the files it should be just a matter of rebasing now.

I'm not as familiar with github's functions as I'd like to be. What do you mean by this? Are you referring to me changing the filenames to fix the file conflict?

**Comment by Gymnasiast** [comment]
You 'based' your changes upon a certain point (where no file named 80.png existed). Rebasing changes the point your changes branched from.

In this case, I'll handle the rebase for you.

**Comment by Gymnasiast** [comment]
This has been merged. Thanks!

**Pull request closed without merging**
