### PR TITLE
Adding descriptions for cheats (Changed ID's)

### PR DESCRIPTION
**Pull request by Nubbiy**
I made a pull request [#489](https://github.com/OpenRCT2/Localisation/issues/489) about adding descriptions to different cheats in the game to make it easier to understand what they are about as most people, including me, didn't know

The descriptions that will be in the game when you hover over the buttons will be:

- **Unlock all prices**  -	str_**5790**		- STR_CHEAT_TIP_UNLOCK_PRICES
- **Renew rides**        -	str_5791		- STR_CHEAT_TIP_RENEW_RIDES 
- **Fix all rides**        -	str_5792		- STR_CHEAT_TIP_FIX_ALL_RIDES
- **Reset crash status** -	str_5793		- STR_CHEAT_TIP_RESET_CRASH_STATUS
- **All destructable**   -	str_5794		- STR_CHEAT_TIP_MAKE_DESTRUCTABLE
- **Guests ignores intensities**  -	str_5795 - STR_CHEAT_TIP_IGNORE_INTENSITY
- **Close park**  -			str_5796		- STR_CHEAT_TIP_OPEN_PARK
- **Freeze Climate**    -	str_5797		- STR_CHEAT_TIP_FREEZE_CLIMATE

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Please number the strings properly: starting with 5790.

**Comment by AaronVanGeffen** [comment]
Thank you for your contribution. This will be very useful for new players, I'm sure.

To add to @Gymnasiast's comment, would you please `stash` your commits together?

**Comment by LinusU** [comment]
You probably mean `squash` your commits together.

Nice work!

**Comment by Nubbiy** [comment]
@Gymnasiast Can do that, was just a bit worried it would collide with someone else pull request

@AaronVanGeffen @LinusU On it - If I can figure out how

**Comment by AaronVanGeffen** [comment]
@Nubbly You can do it through an interactive rebase on your branch. If you use the git command line, it can be done through `git rebase -i`.

Alternatively, apparently GitHub now [lets you do it](https://github.com/blog/2141-squash-your-commits) through their website, too.

**Comment by Nubbiy** [comment]
@IntelOrca 
@Gymnasiast - Changed the ID's from 5790 -> 5797
I'm too dumb for this site to `squash` all my commits :U       Not even support could help, yelp
Will leave it like this, anyone is allowed to steal this just to make it merge into the final project
Something that could be useful is a **label** or something

**Comment by Gymnasiast** [comment]
Don't worry, we'll squash it during merge.

**Pull request merged**
