### PR TITLE
Add Inventions List and Scenario Options to the Debug menu, closes #1770

### LINKED ISSUE #1770: Add the invention list to the dropdown menu of the debug tools.
Please add the invention list like the object selection to the dropdown menu of the debugging tools.

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by IntelOrca** [comment]
Does this allow you to change what is currently researched during game, or the order?

**Comment by Gymnasiast** [comment]
Both. Although the changes may only become visible after saving and reloading.

**Comment by IntelOrca** [comment]
Why is that?

**Comment by Gymnasiast** [comment]
Probably because it needs to reload the inventions list after editing. When you use it in the Scenario Editor (as it was intended in RCT2), that will always happen.

**Comment by IntelOrca** [comment]
Could this be done when you close the window?

**Comment by Gymnasiast** [comment]
It's certainly possible, but I'm not sure if I can do that.

**Comment by IntelOrca** [comment]
Give it a go! :octocat:

**Comment by Gymnasiast** [comment]
I'll try it. I've also noticed cheat detection interfering when you change the initial/max loan values. I'll try to address that as well

**Comment by Gymnasiast** [comment]
Ok, I think I got it :). Also fixed the cheat detection for loan settings.

**Pull request merged**
