### PR TITLE
Add Myself to contributers.md

### PR DESCRIPTION
**Pull request by That-Human-Being**

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
What our requests have you worked on? Perhaps under a different username?

**Comment by That-Human-Being** [comment]
I've actually only added things to the wiki ([csg1.dat sprite list](https://github.com/OpenRCT2/OpenRCT2/wiki/Sprite-List-csg1.dat) and [MSYS2 MinGW-w64 building instructions](https://github.com/OpenRCT2/OpenRCT2/wiki/Building-OpenRCT2-on-MSYS2-MinGW)), not any actual commits to the repo itself.

**Comment by Broxzier** [comment]
Something strange is going on here. That "pull" bot seemed to have reset your own develop branch to match the OpenRCT2 repo, then no commits are in this PR anymore, and now it linked an unrelated commit to this one. I'm guessing that GitHub sees this PR as merged since its commit is in develop.

Any idea where the "pull" bot came from?

**Comment by That-Human-Being** [comment]
Yes, I had set it up on my account (just removed it) to automatically get upstream changes to my forks, I created a new commit with the same changes that I already had performed again. Seeing as this PR is "merged" should I make a new PR with the fixed commit?

**Comment by Broxzier** [comment]
I'm afraid that's required, yes. GitHub wrongfully marked this one as merged now, I don't think it can be opened. Make sure the commit is on another branch, so the bot doesn't interfere.

**Comment by IntelOrca** [comment]
@That-Human-Being I think the main issue is that you used `develop` for your PR. You should create new branches and PR the new branch instead.

**Pull request merged**
