### PR TITLE
Fix #17889: Peeps don't stop at level railway crossings if approached from downhill

### LINKED ISSUE #17889: Peeps don't stop at level railway crossings if approached from downhill
### Operating System

Ubuntu 20.04 LTS

### OpenRCT2 build

Unknown

### Describe the issue

OS: Ubuntu Linux 20.04
Version: 0.4.1
Commit/Build: Unknown -- #12909

While trying to figure out more about #10535, I came across another bug with level crossings. If the path the guests are approaching from is downhill from the crossing, they will not stop. Crossings on level ground and crossings with the guest coming from uphill do not seem to be affected.

If you open this saved demonstration in Forest Frontiers, you can very easily see this happening: 
[crosing_error_demo.zip](https://github.com/OpenRCT2/OpenRCT2/files/9411088/crosing_error_demo.zip) (Rename to .park)

Forest Frontiers 2022-08-23 16-14-04

Forest Frontiers 2022-08-23 16-16-24

### Area(s) with issue?

_No response_

### Steps to reproduce

1: Open the attached save

2: Just observe

Alternately:

1: Build a miniature railroad at the top of a hill, directly next to the slope

2: Cross the railroad track with a path, creating a level crossing at the top of the slope

3: Open the ride and get guests walking on the path

4: Observe that guests heading downhill do stop for trains, but guests heading uphill do not.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by rik-smeets**
If peeps approached a railway crossing from downhill, they would not stop for a passing train. This was because the destination z wasn't up-to-date.

Moving the logic to the generic peep_footpath_move_forward method, where the new target destination is determined, resolves this issue. It also prevents some code duplication in the 'Guest' and 'Peep' classes.

_Note: this change ended in guests starting to walk too soon at a railway crossing, making them phase through the final part of the train. So, I reverted my earlier change where the final part of the train was also included in tile elements to unblock._

_Instead, ensure UpdateCrossings is called every time -> even when there is no new track progress. This prevents certain tiles from becoming blocked forever. Also ensured most code from that method won't be run anymore if the ride type doesn't support level crossings anyway._

_For trains going backwards in shuttle mode, update the logic so the next tile is selected to prevent guests starting to walk too soon in that way too._

Resolves #17889.

### Demo
Guests will now stop for railway crossings when they're approached from an upwards sloped path. Note that the mechanic will also stop.

Guests

Staff members will also still stop for railway crossings at upwards sloped paths, except mechanics who are on the way to fix the ride that's blocking the track.
Staff

### CODE REVIEW

**Comment by ocalhoun6** [comment]
>Also ensured most code from that method won't be run anymore if the ride type doesn't support level crossings anyway.

This might break some parks? Pretty sure I've seen some custom park builders using level crossings with all kinds of different rides, especially go karts. (Not sure how they do it, probably some trickery with setting the ride type?) But that might be something to test before making this particular change.

**Comment by rik-smeets** [comment]
> > Also ensured most code from that method won't be run anymore if the ride type doesn't support level crossings anyway.
> 
> This might break some parks? Pretty sure I've seen some custom park builders using level crossings with all kinds of different rides, especially go karts. (Not sure how they do it, probably some trickery with setting the ride type?) But that might be something to test before making this particular change.

There was already code in place which prevented tiles from getting the 'blocked' flag from ride which don't support level crossings. It's just been moved a little to prevent some unnecessary code from being executed. So there shouldn't be an issue there!

**Comment by rik-smeets** [comment]
I marked this PR as a draft, when I noticed some peculiar sprite glitches with specific guests waiting at the crossing. Might have to rethink the solution, so no review required for now.

**Comment by Gymnasiast** [comment]
Superseded by https://github.com/OpenRCT2/OpenRCT2/pull/18127.

**Pull request closed without merging**
