### PR TITLE
Condor flat ride

### PR DESCRIPTION
**Pull request by frutiemax**
Still a draft...

### CODE REVIEW

**Comment by SpartanFrederic104** [comment]
Keep this one open please

**Comment by karst** [comment]
Keep open

**Comment by SpartanFrederic104** [comment]
Keep this open please

**Comment by SpartanFrederic104** [comment]
Again, keep this open please

**Comment by tupaschoal** [comment]
This has been a draft for 6 months with no work done since, and multiple reminders to keep open, do we see it being worked on in the near future? Otherwise I'd rather have us open an issue to track it as incomplete work to be picked up than to keep it open but stuck.

**Comment by tupaschoal** [comment]
@frutiemax I'm closing this for lack of follow-up, feel free to reopen and resume your work if you have the time!

**Pull request closed without merging**
