### PR TITLE
Disable opening cheats window in MP

### LINKED ISSUE #2811: Add a way to disable users from using certain cheats for multiplayer to permissions.
People enabling "show vehicles from other track types" and "show all operating modes" lead to server crashes if certain cars are used on the tracks. I have no way of stopping people from doing this.

### PR DESCRIPTION
**Pull request by janisozaur**
This should fix #2811

### CODE REVIEW

**Comment by janisozaur** [comment]
Ideally, server should validate these things.

**Comment by duncanspumpkin** [comment]
@janisozaur i think #2811 will still happen if you have those settings enabled before you join multiplayer.

**Comment by janisozaur** [comment]
You mean the setting to allow all ride types?

Because even if you have the cheats enabled before you join MP game, the window won't open.

**Comment by devnoname120** [comment]
I think that it would be better for client cheats to be synchronized with the server.
For example, you might want to enable sandbox mode but not allow inappropriate vehicles on tracks.

**Comment by janisozaur** [comment]
I agree with you @devnoname120 but I'd rather do it the safe way – let's disable all cheats for now and when we have a way of handling them properly over network, re-enable them. This way clients won't break any servers.

**Comment by devnoname120** [comment]
What about adding the cheat window to the group permissions? It would be frustrating to play with a friend on a private server and not being able to use cheats at all.

**Comment by IntelOrca** [comment]
@devnoname120 cheats have not been implemented in multiplayer so we can't enable them right now

**Comment by IntelOrca** [comment]
@janisozaur I think you need to call cheats_reset when joining a starting / joining a multiplayer game

**Comment by Gymnasiast** [comment]
@devnoname120 :
I'm not sure putting inappropriate vehicles on track causes desyncs or error. As far as I know, the cheat just affects what the dropdown offers and not what the function for setting the vehicle allows.

Anyway, even though some cheats are multiplayer safe, it would get messy to add 94 exceptions to the cheat window. Eventually the cheats should get multiplayer safe, for now this is the best interim solution.

**Comment by janisozaur** [comment]
updated.

**Comment by IntelOrca** [comment]
@janisozaur what about resetting cheats for the host?

**Comment by janisozaur** [comment]
is it needed? I thought only the clients are affected?

**Comment by IntelOrca** [comment]
Hmm I guess not, but we have another problem.

We need to ditch this, I have never liked it:
```c
typedef struct {
	uint8 fast_lift_hill;
	uint8 disable_brakes_failure;
	uint8 disable_all_breakdowns;
	uint8 unlock_all_prices;
	uint8 build_in_pause_mode;
	uint8 ignore_ride_intensity;
	uint8 disable_vandalism;
} cheat_configuration;
```

Cheats should not be options and should always be reset when leaving a park. Yes when we have our own save format we can persist the values in the save, but right now I think its just going to cause problems. Particular for this as they aren't being reset.

**Comment by janisozaur** [comment]
I removed the cheats from config

**Comment by IntelOrca** [comment]
@janisozaur good, now we need to reset cheats for the host as well because something like gCheatsDisableVandalism can't be different for client and host.

**Comment by janisozaur** [comment]
Since this could be possibly turned back on later on, should I disable cheats for server as well?

**Comment by janisozaur** [comment]
Done. As this could possibly be enabled later on, I removed server-side cheats as well and rebased.

**Pull request merged**
