### PR TITLE
Create define for max track types per ride entry, closes #5524

### LINKED ISSUE #5524: Create a define for max ride types per ride entry
An `rct_ride_entry` can have up to 3 ride types (track types). This should go into a define.

Encountered when working on #5504, and something I want to address before merging it, in order to avoid ballooning that PR even further.

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by IntelOrca** [comment]
Why not ride type?

**Comment by Gymnasiast** [comment]
I find that confusing, as 'ride type' also refers to for example 'Hypercoaster', 'Vintage Cars' etc. Track type is a lot less ambiguous.

**Comment by IntelOrca** [comment]
Track type makes me think of B&M or Intamin.

**Comment by Gymnasiast** [comment]
At least that's less confusing. Anyway, I'd like to hear from @rwjuk @janisozaur @marijnvdwerf . Let's just make this a simple majority vote, as ultimately it boils down to tomato-tomayto.

**Comment by rwjuk** [comment]
IMO track type is less ambiguous. FWIW, I only vaguely know what B&M and Intamin refer to. Also, I'm pretty sure that 'track type' is used elsewhere in this sort of context.

**Comment by Gymnasiast** [comment]
@rwjuk 8 cars per trainer does that, and it also seems to be common on NE.

**Comment by IntelOrca** [comment]
In the future we will have a property on track element that controls the track type / style: B&M, Intamin, Railway. We will therefore have an enum for those called TRACK_ something, and I can see that being ambiguous if you already call track type: merry-go-round, drink stall, monorail.

**Comment by Gymnasiast** [comment]
As I said, it's more confusing to call Hypercoaster, Cheshire Cats, etc. ride types as well as Steel Twister, etc.

There is also the point that Steel Twister _is_ in essence B&M, in the same way that the Corkscrew track is Arrow/Vekoma. So I actually agree with point about B&M and Intamin, except I draw a different conclusion out of it.

**Comment by marijnvdwerf** [comment]
I'm not sure I understand what's going on. Does the game have a limit on the number of available variants of each specific ride type? E.g. max 3 types of merry go round?

**Comment by IntelOrca** [comment]
> As I said, it's more confusing to call Hypercoaster, Cheshire Cats, etc. ride types as well as Steel Twister, etc.

No, these are ride entries or ride objects. They are not ride types.

**Comment by rwjuk** [comment]
Hmm, if there's going to be a property that'll contain 'track types' (in the general sense), it may make more sense to reserve that nomenclature for those.

**Comment by Gymnasiast** [comment]
Meh, I just replaced TRACK_TYPE with RIDE_TYPE. Not worth that much discussion, that already takes way too much of our time.

**Pull request merged**
