### PR TITLE
Allow to use the numpad enter key.

### PR DESCRIPTION
**Pull request by ZehMatt**
The chat and console did nothing when using the numpad enter key, this PR changes that, been nagging me for a while.

### CODE REVIEW

**Comment by IntelOrca** [comment]
Changelog?

**Comment by ZehMatt** [comment]
I'm always having trouble finding the right words for this, I'll try my best.

**Comment by duncanspumpkin** [comment]
I've been wanting this for ages. So annoying when typing numbers on the keypad

**Comment by IntelOrca** [comment]
Are you guys using the console as a calculator or something? I mostly type text in console so I rarely touch the keypad.

**Comment by duncanspumpkin** [comment]
I've always preferred the num pad for data input and when testing a few combos for the rides set price all there were a good few numbers

**Pull request merged**
