### PR TITLE
MSVC ARM64

### PR DESCRIPTION
**Pull request by janisozaur**
This PR introduces ARM64 platform to MSVC project and uses it in CI.

Notes:
* building of g2 gets skipped, as the non-native version doesn't work on github action workers. It might be possible to use approach similar to https://github.com/OpenRCT2/OpenRCT2/pull/16107, but given how slow this build is already (around 20 minutes) I don't want to compile it yet again.
* The build is slow. As all MSVC builds are. https://github.com/OpenRCT2/OpenRCT2/pull/15997 could help here.
  - edit: PCH brought times from 26m to 18m, a solid 8m win.
* Not sure how to distribute it. Jarno already refused adding any more build IDs, at least for now, and then it would have to go to end users who might be at the mercy of _the other project_ not being aware of what ARM is.
* Possible approaches to solving both g2 and distribution woes could be adding another CI job on top of all MSVC architectures that would provide 'universal' build: `openrct2-portable.zip` build with all three architectures in it and repurposing `openrct2.exe` as launcher to select the expected arch.
* Libs v32 (https://github.com/OpenRCT2/Dependencies/releases/tag/v32) have benchmark included for arm, need to run those tests or have them ran.
* Use of breakpad got unified, previously it seemed to be enabled implicitly. It's probably necessary to enable it explicitly now, but don't know how to enable that option with msbuild, hoping Ted can do that.

Fixes https://github.com/OpenRCT2/OpenRCT2/discussions/16749
Fixes https://github.com/OpenRCT2/OpenRCT2/issues/6682

### CODE REVIEW

**Comment by IntelOrca** [comment]
How come breakpad is not enabled (or available) for ARM?

**Comment by janisozaur** [comment]
It doesn't compile. I haven't spent time looking into why it trying to fix it, might do that at some point, but no guarantee.

**Comment by GingerAdonis** [comment]
I'm not refusing new build IDs, as they can easily be added easily. By the earlier request I assumed you wanted something more complex. My bad.

**Comment by janisozaur** [comment]
Regarding breakpad: ideally we would migrate to crashpad (https://github.com/OpenRCT2/OpenRCT2/issues/5342) which also is about to receive arm64 support in vcpkg (https://github.com/microsoft/vcpkg/pull/23827)

@GingerAdonis thanks, we must've misunderstood each other, will send you info on discord.

I'm working on getting ccache integrated into builds (https://github.com/OpenRCT2/OpenRCT2/issues/16895) and it will take some more time, as work moved to https://github.com/ccache/ccache/issues/1040

As a interim solution I would like to propose following setup:
1. Do ARM64 builds only on `push` - this will not affect PRs (at least those originating from forks)
2. Add a separate job to copy g2.dat from x86 build artifact, just like we do with macos universal builds
3. Ask Jarno for new build id and actually distribute it
4. Once we get builds sped up, enable them for PRs as well (or not - I don't expect them to break in ways other than amd64 would)
5. Once #16107 is done, investigate possibility of creating g2 in the same CI job

Other than that I think having a multi-binary zip would also be useful in the long run, but that's stuff for another PR

**Comment by IntelOrca** [comment]
For #16107, I am curious as to why we want to build a utility that would rarely change every single build. We could have a separate repo with a release of a sprite compiler binary that it downloads and runs instead.

**Comment by janisozaur** [comment]
Sprite compiler binary or g2.dat? Regardless of that, I still want to pursue #16107 for easier cross compilation without having to rely on external stuff, especially when code is already there.

**Comment by IntelOrca** [comment]
@janisozaur both, and it would be used by openloco as well. Possibly by other people as a standalone tool.
The problem with #16107 is that the one in OpenRCT2 is not well isolated from the code base and requires ifdefing out sections of code.

**Comment by janisozaur** [comment]
I've updated this PR and removed CI job for now, until a feasible solution is available. While the work on ccache front doesn't progress at satisfying speed, I was thinking perhaps we could limit it to stuff that actually gets merged to main branch? Having MSVC do all the tests in native configurations would have to do for now.

**Review by IntelOrca — APPROVED** [review]

**Comment by janisozaur** [comment]
@GingerAdonis could you please do the following changes:

* MSVC ARM64
* Ubuntu Jammy 22.04
  - x86_64
  - i686
* Ubuntu Focal 20.04
  - x86_64
  - i686
* Debian Bullseye
  - x86_64 only

at the same time - could you rename current "Linux i686" and "Linux x86_64" to "Ubuntu Bionic 18.04 <arch>"?
oh and also rename "macOS Portable ZIP" to "macOS Universal Portable ZIP" or if it is too long, then just "macOS Universal ZIP"

**Pull request merged**
