### PR TITLE
[WIP] Setting a password during game

### PR DESCRIPTION
**Pull request by atmaxinger**
This is a work in progress. 

Currently I have added a button to the player list (still titled „Hire new Handyman“ as I don’t know how to add new strings xD) and when you click on it you can enter a password for the game.

The setting of the password works, however I haven’t got a clue on how to send an update to the master server so that the games gets the lock symbol in the server list.

### CODE REVIEW

**Comment by IntelOrca** [comment]
The Network class has a SetPassword method, you should be using that, not defining another variable.

**Comment by atmaxinger** [comment]
I am using the SetPassword method (well the C network_set_password wrapper method to be precise). But yeah, the variable is pretty useless

**Comment by Gymnasiast** [comment]
@IntelOrca : How does this relate to https://github.com/OpenRCT2/OpenRCT2/issues/3155? Is this one still necessary?

**Comment by IntelOrca** [comment]
@Gymnasiast this is server password when you join... nothing to do with #3155. Its easy to change the password but not to change from having one to not having one and visa versa - because the master server list only checks this information on server registration.

To fix that, we shall wait for #3155 where I will update the master server list API to check password on each information update.

**Comment by IntelOrca** [comment]
I will sort this out when we come back to improving multiplayer - its a lot of work.

**Pull request closed without merging**
