### PR TITLE
Pass DrawPixelInfo by reference

### LINKED ISSUE #19523: Pass DrawPixelInfo by reference instead of by pointer
One caveat: make sure to test if the dropdowns in the Land window still show up correctly after doing the refactor.

### PR DESCRIPTION
**Pull request by Harry-Hopkinson**
Pass DrawPixelInfo by reference instead of a pointer.

Closes #19523.

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
I wonder if the reference should be passed `const` as well?

**Comment by Harry-Hopkinson** [comment]
I think it can be - the value is never modified in the function.

**Comment by ZehMatt** [comment]
> I wonder if the reference should be passed `const` as well?

The drawing functions actually mutate the DPI as that holds the buffer, we should probably bring this also in line with OpenLoco and rename that to RenderTarget eventually.

**Review by Gymnasiast — APPROVED** [review]

**Comment by Gymnasiast** [comment]
Tested it, seems to work correctly, including the Land window.

**Review by tupaschoal — APPROVED** [review]

**Pull request merged**
