### PR TITLE
Add new pieces to the Stand-Up Roller Coaster

### PR DESCRIPTION
**Pull request by mixiate**
This adds new pieces to the Stand-Up Roller Coaster.

- Small flat to steep
- Long flat to steep
- Vertical slopes
- Steep turns
- Vertical turns
- Banked slope transitions
- Small banked sloped curves
- Medium banked sloped curves
- Large sloped curves
- Large banked sloped curves
- Small banked to unbanked curves
- Large corkscrews
- Quarter loops
- Medium half loops
- Large half loops
- Barrel rolls
- Zero g rolls
- Large zero g rolls

allstanduppieces

The long flat to steep pieces, large corkscrews and medium and large half loops are made available to the classic and standard coasters. The banked turns are available to the standard coaster. I've added code to make sure the classic coaster doesn't use them. Everything else is cheats only.

The banked track pieces have been rendered to match up to the changed positions in #23199, but if you don't want that I can easily change them.

### CODE REVIEW

**Comment by ZeeMaji** [comment]
The classic stand-up needs to have the unbanked large/diagonal sloped turns enabled, the vehicles have sprites for these and the track is not banked so it is not affected by the different banking angle of the classic stand-up.

**Comment by SpartanFrederic104** [comment]
Fred's Workbench 2024-11-13 19-24-20
Did some testing with the new stand-up coaster track pieces yesterday and they look absolutely fantastic (sans the small corkscrews looking a little weird going into/from medium half loops). They'd be perfect for recreations of various Premier or Mack coasters especially considering how close the Togo track looks to the track used by some Premier or Mack coasters.

I would preferably have #23199 merged as well because the new stand-up track pieces were made with 23199's fixes in mind.

**Comment by mixiate** [comment]
Yeah unfortunately the original inversions are very wonky and look different at different angles and don't match up even to themselves, so I don't know if it's possible to do much better. I could maybe take another look at it.

Thanks for trying them out.

I'll give the classic the large turns at some point.

**Review by karst — APPROVED** [review]
All looking sound :) Playtest approved

**Comment by karst** [comment]
I am curious if this will need the conversion code as well for pieces. I highly doubt people have tried adding these new pieces to the stand up coaster yet, but the possibility exists.

**Comment by mixiate** [comment]
It does have it.

**Review by Gymnasiast — APPROVED** [review]

**Pull request merged**
