### PR TITLE
[Plugin] Add support for custom images

### PR DESCRIPTION
**Pull request by IntelOrca**
**New APIs:**
```js
interface ImageManager {
    allocate(count: number): ImageIndexRange | undefined;
    free(range: ImageIndexRange): void;
    getImageInfo(id: number): ImageInfo | undefined;
    getPixelData(id: number): PixelData | undefined;
    setPixelData(id: number, data: PixelData): void;
    draw(id: number, size: ScreenSize, callback: (g: GraphicsContext) => void): void;
}
```

**Example:**
```js
const range = ui.imageManager.allocate(1);
if (range) {
    ui.imageManager.setPixelData(range.start, {
        type: 'rle',
        width: 18,
        height: 17,
        data: 'IgAkACYAKAAqACwAMAA2AD4ASABQAFYAWgBcAF4AYABiAIAAgACAAIAAgACCBQoKhAUKCgoKhgUKCgoKCgqIBQoKCgoKCgoKhgUKCgoKCgqEBQoKCgqCBQoKgACAAIAAgACAAA=='
    };
}

ui.imageManager.free(range);
```

**A demo script to play around with:**
[image-api-demo.zip](https://github.com/OpenRCT2/OpenRCT2/files/8346277/image-api-demo.zip)

### CODE REVIEW

**Comment by oli414** [comment]
Looks good, on the API side of things. The API is quite low level by JavaScript standards, but I can see why it was done.

**Comment by IntelOrca** [comment]
> The API is quite low level by JavaScript standards, but I can see why it was done.

Do you have any suggestions?

I suppose I didn't consider that too much, since in my test scripts I wrapped the APIs with helper functions. E.g.
https://github.com/OpenRCT2/title-sequence-editor/blob/custom-images/src/images.ts

**Comment by oli414** [comment]
I think ideally, you'd get an image reference that you can set the pixels on. Which automatically frees the image upon cleanup of the object (all references lost).

```js
{
  const image = ui.imageManager.create(); // Either return null or throw an error if unable.
  image.setPixelData(...);
}
// Image ref lost, image is freed automatically.
```

**Comment by IntelOrca** [comment]
Just thinking about performance though, that is one `shared_ptr` for each individual image a plugin allocates. And you would still need to expose the real image index anyway since the other drawing APIs take an image ID.

**Comment by IntelOrca** [comment]
@oli414 I think you have to use a class still and implement the destructor.

**Review by oli414 — APPROVED** [review]

**Pull request merged**
