### PR TITLE
Refactor functions with x,y(,z) parameters.

### PR DESCRIPTION
**Pull request by ZehMatt**
This is currently a WIP. 

Also would it be acceptable to introduce operators such as +, /, - etc on structs like LocationX16?

There is some code where it just adds x and y from two LocationXY16 which could be simplified by that.

### CODE REVIEW

**Comment by IntelOrca** [comment]
I am find with `+`, but I don't think `++` makes any sense on a location.

**Comment by AaronVanGeffen** [comment]
I'm sorry to be the bearer of bad news, but this needs to be rebased due to the recent formatting changes…

**Comment by Gymnasiast** [comment]
Also, just to make sure you didn't forget, Coords and TileCoords should be used (depending on what kind of coordinates are passed). LocationXY and friends are for storage.

**Comment by ZehMatt** [comment]
Given that I have barely time I'm not sure I can continue any time soon, but I'll try.

**Comment by Gymnasiast** [comment]
Considering all the points made above, including the time that has since passed, perhaps it easier to start from scratch? I would also advise doing a few functions and opening the PR to make sure you're on the right track.

**Pull request closed without merging**
