### PR TITLE
Vehicle Update

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Its taken a little while but vehicle update is now ready for extensive testing.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Two bugs I observed. Both are in Crappage's conversion of Blackpool Pleasure Beach, and don't happen in vanilla and OpenRCT2 prior to this PR.
- The bumper boats from Swamp Buggies never leave the platform.
- The Grand National plays the "wooden roller coaster rushing through the track" sound while on the lift hill.

**Comment by duncanspumpkin** [comment]
I wasn't able to reproduce the grand national playing the wrong sound can you create a smaller sample park that reproduces it.

**Comment by Broxzier** [comment]
One bug that I found is that doorways play the wrong sound when they open.

**Comment by HaasJona** [comment]
Can confirm the wrong door sound.

Also, intensity rating seems to be calculated incorrectly, in the attached file (change file extension to sv6), the inverted shuttle coaster has an intensity of about 10,5 in the normal branch and about 50 in the vehicle update branch.

[door.txt](https://github.com/OpenRCT2/OpenRCT2/files/76204/door.txt)

**Comment by duncanspumpkin** [comment]
@HaasJona that should fix both of the issues you have found.

**Comment by HaasJona** [comment]
@duncanspumpkin looks good

**Comment by Broxzier** [comment]
I noticed that go-karts can get stuck in this branch. In the attached file there already are a few karts all on the same spot because the first one got stuck. You're almost guaranteed to get one stuck by letting people ride this track, not always on the same spot though, I think it has something to do with when they want to switch lane.

[[RI] Go Karts Challenge.zip](https://github.com/OpenRCT2/OpenRCT2/files/76345/RI.Go.Karts.Challenge.zip)

Oping this park in this branch leaves them stuck, opening them in another makes them all spread out and continue driving.

**Comment by danidoedel** [comment]
The 3D cinema seems to unload its passengers immediately after they joined.

**Comment by duncanspumpkin** [comment]
Okay i've fixed the race cars and the 3D cinema.

**Comment by danidoedel** [comment]
Rides never call a mechanic if they have a vehicle malfunction.

**Comment by Gymnasiast** [comment]
Haven't been able to reproduce the sound issue I had anymore.

**Comment by duncanspumpkin** [comment]
@danidoedel I've fixed the two issues you had with the mechanics not being called and trains getting stuck at the station after a fix.

**Pull request merged**
