### PR TITLE
Fix ride rating penalties

### PR DESCRIPTION
**Pull request by jensj12**
Changes the penalty for high lateral G-forces to be applied after the other penalties instead of before.

### CODE REVIEW

**Comment by jensj12** [comment]
Somehow there are still a lot of merge commits left from my other pull request. How do I fix that?

**Comment by Gymnasiast** [comment]
Rebase to `upstream/develop` (assuming you have the OpenRCT2 github repo as `upstream`)

**Comment by IntelOrca** [comment]
Changes to ride ratings require discussion particularly with community and reddit.

**Comment by sjoerddebruin** [comment]
It would be nice to have more options like OpenTTD, where you can choose for classic or realistic acceleration. Mostly developers decide now, but some people like the old behaviour and want to keep that.

**Comment by Gymnasiast** [comment]
@jensj12 Could you explain a bit more about this? Specifically, why you think it's better to apply the penalty after the other ratings than before?

**Comment by jensj12** [comment]
There is only one case where this makes a difference, when both the excessive G-force penalty is applied and a multiplicative penalty for not reaching certain thresholds (like no big drop). The other penalties diminished the effect of the g-force penalty. With this change the intensity rating of those coasters is substantially higher.
This coaster posted here is an example: https://openrct2.org/forums/topic/1196-my-arguemnet-for-why-stats-are-not-a-good-judge-of-quality/#comment-6411

**Comment by Gymnasiast** [comment]
If it only affects the case you mentioned, it would be improvement in my view. Can you provide proof in the form of screenshots of that?

**Comment by jensj12** [comment]
Without change:
happy park 2016-12-14 16-55-43

With change:
happy park 2016-12-14 16-54-53

**Comment by Gymnasiast** [comment]
This coaster is set to launch at (approximately) 107 km/h, is that correct?

**Comment by jensj12** [comment]
Yes

**Comment by Gymnasiast** [comment]
Can you give a few examples are rides that should be unaffected? (Two or three would suffice.)

**Comment by jensj12** [comment]
Picked four random rides from a random park.
Without change:
openrct 2015 2016-12-16 11-47-11

With change (nothing changed):
openrct 2015 2016-12-16 11-59-07

And the ratings of this little coaster also remain intact:
happy park 2016-12-16 12-02-28

**Comment by Nubbie** [comment]
@Gymnasiast @jensj12 There is a small discussion about this on the forum
https://openrct2.org/forums/topic/1196-my-arguemnet-for-why-stats-are-not-a-good-judge-of-quality/#comment-12333

**Pull request merged**
