### PR TITLE
Decrease dependency of world on windows

### PR DESCRIPTION
**Pull request by marijnvdwerf**

### CODE REVIEW

**Comment by Gymnasiast** [comment]
How far finished is this?

**Comment by marijnvdwerf** [comment]
Depends on how small you want PRs to be. It should be in a working state right now though. These are the functions of `Windows.cpp` that `word/**.cpp` still references:


##### world/Map.cpp
  - window_close_by_number
  - window_find_by_class

##### world/MoneyEffect.cpp
  - window_get_main
  - window_get_viewport

##### world/Park.cpp
  - window_invalidate_by_class

##### world/TileInspector.cpp
  - window_find_by_class
  - window_invalidate
  - window_invalidate_by_class

**Comment by Gymnasiast** [comment]
With a lot of development effort going into OpenLoco these days, I want to reduce the number of open PRs to avoid them going stale. So I'd rather merge this sooner than later.

**Comment by janisozaur** [comment]
> With a lot of development effort going into OpenLoco these days, I want to reduce the number of open PRs to avoid them going stale. So I'd rather merge this sooner than later.

I second that. Smaller PRs are easier to review and get merged.

**Pull request merged**
