### PR TITLE
Double closing Park forces guests to leave

### PR DESCRIPTION
**Pull request by Hris7**
Double closing the Park sets the state of all guests to leave the park. 
Guests currently in queues are also forced to leave the queue.

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
What if you accidentally double click the park status? This is a destructive operation in that it resets all actions, with no way to undo it if the double click was an accidental one...

**Comment by mrtnptrs** [comment]
Uhm.... personally I wouldn't merge this; if someone accidentally closed his park two times in a row, his park would be ruined if he doesn't load an autosave.... Also, to be honest: I don't see the point of this feature. Could you maybe explain this more @Hris7 ?

**Comment by Hris7** [comment]
as mentioned on gitter: "just more fun to watch them actually leave, from time to time i close all rides in my park and close the park itself and i want a way to force the guest to actually leave the park (instead of guiding them with signs to the exit)"
@janisozaur suggested the double closing to trigger this. My first idea was that this is a new cheat, so i could also change this to be a cheat

**Comment by ccoors** [comment]
I guess this is to copy the feature from rides, where closing it twice immediately removes the peeps, except if it failed. I really like the feature, but I also don't like how it's triggered.

**Comment by mrtnptrs** [comment]
Uhm.... there is a cheat to just remove all the guests from your park and to even let them all go BOOM!/explode XD So, I don't know if this is really necessary.... But if you really like seeing people leaving your park..... :)

**Comment by trigger-death** [comment]
Maybe change this to a message box that asks if you'd like to force all guests to leave after double-closing? That or add it's own button. Still, require message box confirmation either way.

**Comment by Hris7** [comment]
Same feature, but as cheat in #6476

**Pull request closed without merging**
