### PR TITLE
Refactor research - spike 1

### PR DESCRIPTION
**Pull request by Gymnasiast**
This involves refactoring gResearchedRideTypes and gResearchedRideEntries
and the functions involved.

This also renames several function in order to better express what they do.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Perfect, all CIs are red! Even Xcode!

**Comment by duncanspumpkin** [comment]
The renames are quite different to the rest of the code base. I don't think we have anything else that starts make_. I've not got a better idea for the naming though

**Comment by rwjuk** [comment]
`invent_all_scenery_items()` maybe?

**Comment by Gymnasiast** [comment]
I think replacing `make` with `set` brings it in line with the rest of the code _and_ keeps my intended meaning.

**Comment by AaronVanGeffen** [comment]
Tested a few scenarios, importing SV4 and SV6 files. The available rides are the same when loading on `develop` and `refactor-research`.

**Pull request merged**
