### PR TITLE
CMake: improve check for OpenGL support on macOS

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
CMake seems to have trouble with the `gl` module on macOS. This PR changes it to use find_package with `OpenGL` instead, which works for me on both macOS and Arch Linux.

### CODE REVIEW

**Comment by janisozaur** [comment]
How is the commit affecting `glew`? I can only see it affects `gl`.

**Comment by AaronVanGeffen** [comment]
You're right, I misremembered. Sorry.

It didn't sit well with me to have no check at all for OS X, either. Even though macOS ships with OpenGL built-in, we should still check for it, rather than assuming it exists. With that in mind, I've changed it to a solution that works for me on both OS X and Arch Linux (using mesa, fwiw).

Travis doesn't seem to like it for some of its jobs, though. Any ideas?

**Comment by janisozaur** [comment]
It seems these are the native 32 bit ubuntu build jobs that fail (others are: docker Arch multilib, mingw, 64 bit ubuntu). It's possible Travis is missing some opengl package, but which one - I don't know yet.

**Comment by janisozaur** [comment]
I expect you can find the missing package in here: https://www.diffchecker.com/eveuvrtj

Left is listing from 32 bit build (failing), right is from 64 bit build (working fine)

**Comment by AaronVanGeffen** [comment]
Going over the list of packages, nothing related really stands out. I bet you're right in that `find_package` doesn't scan multi-arch directories, though. Hmm...

**Comment by IntelOrca** [comment]
Will merge if @janisozaur and @LRFLEW approve.

**Comment by janisozaur** [comment]
I don't think it concerns @LRFLEW (he's using Xcode) and this doesn't concern Linux either, as it only touches OS X/cmake builds.

In other words: :+1: from me.

**Comment by LRFLEW** [comment]
I'm confused about this. Not that the including of OpenGL needs to be different on macOS (where it's a framework), but that OpenGL needs to be linked at all. I thought we were developing it such that OpenGL was not a compile-time dependency at all. That's why `OpenGLAPI.h` has all those weird `#define`s . Why does cmake need to get OpenGL in the first place?

**Comment by AaronVanGeffen** [comment]
It doesn't -- it just checks for its existance. Actually, I'd removed the check completely at first, as it wasn't working on macOS, but decided a working sanity check would be better, just in case.

**Comment by LRFLEW** [comment]
Hmm... I swear I see it linking in the CMake instructions... but I guess that's a different issue. If this compiles, I guess I give it the :+1: from me (I haven't tested it myself). However, I feel like this is missing the point somehow, and I'm going to be looking into the way we use OpenGL.

**Comment by AaronVanGeffen** [comment]
While I can see your reservation, for now it'd be very helpful to not have to disable OpenGL every time we invoke cmake... (I realise most people on macOS will use XCode instead, but still.)

**Comment by janisozaur** [comment]
Merged as part of #4244

**Pull request closed without merging**
