### PR TITLE
Add new roller coaster ride colour presets

### PR DESCRIPTION
**Pull request by karst**
The following ride colours crafted are based on IRL counterparts.
To see the colours and give feedback can go in this discord channel: https://discord.com/channels/264137540670324737/1102721159809749114/1102721893414482000

Every commit adds one, rather than having a bunch of PRs.

Current additions:

image

### CODE REVIEW

**Comment by ZehMatt** [comment]
I like the colors, any particular reason this is a draft?

**Comment by karst** [comment]
I might want to go over the flat rides and such as well. Unless you want me to seperate it by ride type?

**Comment by rik-smeets** [comment]
Could you add a changelog entry for this one, @karst ?

**Comment by karst** [comment]
Added :)

**Review by rik-smeets — APPROVED** [review]

**Comment by Gymnasiast** [comment]
You removed some presets, like the purple Multi-dim. There was a discussion about it on Discord not long ago, and the conclusion was that we shouldn’t remove any presets, just add new ones.

https://github.com/OpenRCT2/OpenRCT2/issues/20311 suggests that this is still the prevailing opinion.

**Pull request merged**
