### PR TITLE
Touch drag try2

### LINKED ISSUE #2091: Touch screen compatibility
Could a checkbox be added to the options menu that changes the drag function to left click? I'm playing rct2 on a touchscreen (it's a lot of fun) and the only drawback right now is I need the map to move around effectively.

### PR DESCRIPTION
**Pull request by samdroid-apps**
Replaces https://github.com/OpenRCT2/OpenRCT2/pull/2530

```
commit 88998a51cef66c9832c36ee8ad0d4e679b1b592d
Author: Sam Parkinson <sam@sam.today>
Date:   Fri Mar 4 19:17:39 2016 +1100

    Handle touch drag on viewports, fixes #2091

    This commit makes it possible to drag a viewport around with touch.
    This reuses the code of the right mouse button viewport
    movement, although adding a new flag to indicate touch behavious

    The user can always start a drag, however the drag is teated as a
    click if the user does not move more than 8px.
    (as well as not relying on moving the cursor).

commit 55dc19b158a20032b58f4a055e9c0cf7c1e626ce
Author: Sam Parkinson <sam@sam.today>
Date:   Fri Mar 4 18:30:22 2016 +1100

    Fix touch positioning on GNU/Linux

    Commit eab3e151 changed the touch code to improve accuracy.  However,
    this resulted in the touch not working on GNU/Linux since
    the "e.tfinger.x * _screenBufferWidth" equation ended up being something
    like "640 * 1080" (assuming finger is at 640x and the screen is 1080p).

    This change reverts that commit.
```

### CODE REVIEW

**Comment by IntelOrca** [comment]
@samdroid-apps this PR breaks touch for Windows, all input is translates to 0,0 (the pause button).

**Comment by samdroid-apps** [comment]
Ah, maybe it is an SDL api change.  The behaviour you note is on the SDL docs [1].

What SDL version do you have?  I get the old behaviours with SDL2-devel-2.0.4-3.fc24

[1]  http://wiki.libsdl.org/SDL_TouchFingerEvent

**Comment by IntelOrca** [comment]
@samdroid-apps 2.0.4 (stable)

**Comment by Gymnasiast** [comment]
@samdroid-apps Are you still working on this?

**Comment by samdroid-apps** [comment]
Evidently I have forgotten :(

If you're interested feel free to give it a shot.

**Comment by mrtnptrs** [comment]
So, @samdroid-apps  , you are not working on this anymore and are not planning to finish your work in the near feature? It would be really nice if OpenRCT2 was more touchscreen friendly :)

**Pull request closed without merging**
