### PR TITLE
Remove extra step  in DefaultMusic reference in RTD

### PR DESCRIPTION
**Pull request by karst**

### CODE REVIEW

**Comment by karst** [comment]
This also opens up the easy possibility of adding different ride music tracks beside the ones that already got strings here, even for people to include their custom music for their custom RTD object in the future.

**Review by Gymnasiast — CHANGES_REQUESTED** [review]
I’m sorry to say, but this is not a good idea. The `constexpr`s are used to make clear that these are known values and to reduce the chance of typos (as typing one wrong will cause a compilation failure) - essentially the same reason we use constants for stuff like limits. You’ll find that many coding standard guides recommends using constants.

Once RTDs become objects, then they will probably have to reference the files directly. But at that point, they will be JSON files, which can also be checked much more easily. Anyway, there is no good reason to remove this from the current code.

**Comment by karst** [comment]
I added values for this in my current LSM and Multi Looping RC PR. I will remove these values were this to get merges.
@spacek531 has not done this, his Wiegand WIP uses a direct link to Extraterrestrial style.

@ZehMatt has also suggested these two PRs should be the last two we add in the traditional way before we move to RTD and Track Type objects. In that case this typo issue will no longer be here and it would be a step towards making a RTD object.

**Comment by Gymnasiast** [comment]
I don’t think this step would any appreciable time. Doing a find and replace is trivially easy.

But anyway, I don’t decide on this. I probably shouldn’t have commented in the first place.

**Comment by IntelOrca** [comment]
I think the constants should stay, but all the known object names could be moved to one single header file.

**Comment by karst** [comment]
Then I can always transform this PR in one that adds all songs as constants. I'll have to update OpenMusic's release checklist accordingly too.

**Comment by ZehMatt** [comment]
I'm not opposed of the change, the data remains constexpr, in theory the binary should be still identical as the optimizations will most likely deduplicate strings but I'm not 100% sure on that, @karst could you check if the binary is still the same as before? However it's a fair point that there is less likely to be a typo in one of them if they use constants, also at the end of the day we plan to move all of this to objects anyway so not sure if this change does improve anything.

**Comment by karst** [comment]
I was thinking, when we make Track type and Ride type descriptor objects we will probably have to keep old references in the code for old ride vehicle objects to continue working. 
This is currently not true for this, so we could still opt to just make it objectid only, but we could also keep these in and add all OpenMusic and other existing tracks to this list and have hardcoded IDs for ones that are included.

I have a question for @IntelOrca. Will linking to the object directly still work with Asset Packs? I'd imagine so, but I want to make sure.

**Comment by karst** [comment]
> I'm not opposed of the change, the data remains constexpr, in theory the binary should be still identical as the optimizations will most likely deduplicate strings but I'm not 100% sure on that, @karst could you check if the binary is still the same as before? However it's a fair point that there is less likely to be a typo in one of them if they use constants, also at the end of the day we plan to move all of this to objects anyway so not sure if this change does improve anything.

image
This PR built (openrct2.exe) vs Develop built (openrct2 - Copy.exe).

The binaries are the same.

**Comment by karst** [comment]
I am gonna need an opinion on how to continue with this?
Either leave it like this and make direct references the way to go going forward. Or leave it how it was and add new references as new ride types are added.

**Comment by Gymnasiast** [comment]
I think the latter would be a better idea. It will of course all change once the RTD are made into objects, but until then, let’s keep the constexpr.

**Pull request closed without merging**
