### PR TITLE
Minor code cleanup.

### PR DESCRIPTION
**Pull request by ZehMatt**

### CODE REVIEW

**Comment by janisozaur** [comment]
```
../test/testpaint/TestPaint.cpp: In function 'void TestPaint::ResetEnvironment()':
../test/testpaint/TestPaint.cpp:52:23: error: 'struct paint_session' has no member named 'Unk140E9A8'; did you mean 'Unk141E9DB'?
         gPaintSession.Unk140E9A8 = &dpi;
                       ^~~~~~~~~~
                       Unk141E9DB
```

**Comment by ZehMatt** [comment]
It would probably help if the test would be added to the VS solution so refactoring will be slightly easier. Anyway I'll correct it.

**Comment by AaronVanGeffen** [comment]
The trouble with testpaint is that, by nature, it's only available on 32-bits platforms.

**Comment by ZehMatt** [comment]
In VS you can actually have the x64 configuration build the x86 one, not sure how things are done with Xcode.

**Pull request merged**
