### PR TITLE
Fix some intents

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by IntelOrca** [comment]
Try to turn the original char array into a string if convenient.

**Comment by LRFLEW** [comment]
Just to point out: instead of `const std::string &`, it's generally better to use `string_view`. It acts nearly identically, but can handle the case of being passed a C-string or string literal better. (In C++17, it's a [LiteralType](http://en.cppreference.com/w/cpp/concept/LiteralType), so the compiler can optimize away the constructor for string literals)

**Comment by janisozaur** [comment]
@LRFLEW sounds good, but we're not using C++17 yet: https://github.com/OpenRCT2/OpenRCT2/pull/6034

**Comment by LRFLEW** [comment]
@janisozaur That makes sense. I just figured I'd point it out, particularly for when we do make the switch.

**Comment by janisozaur** [comment]
@LRFLEW I've  created https://github.com/OpenRCT2/OpenRCT2/issues/7145 to account for that

**Pull request merged**
