### PR TITLE
Update Xcode Project to build x64 macOS Builds

### PR DESCRIPTION
**Pull request by LRFLEW**
This should all be good. I had to disable a warning type to stop it from warning about implicit 64-bit to 32-bit conversions. I'll reenable that warning type (as well as others I've previously disabled) in another PR.

### CODE REVIEW

**Comment by LRFLEW** [comment]
I made a mistake in the Dependencies project. This needs to wait on that.

**Comment by marijnvdwerf** [comment]
`.travis.yml` should probably updated with a new flavourID for the x64 builds.

**Comment by LRFLEW** [comment]
I was talking to @JarnoVgr about it. He was talking about giving the x64 macOS builds a separate flavourID, but I disagree.

Basically, because the app only supported versions of macOS that were already x64-only, it's hard to argue that the x86 and x64 builds are fundamentally different. The only difference is that the x86 builds were With-RCT2, but since both Linux and Windows have switched their original favourID's to be No-RCT2 x86 builds, there's already a precedent for not changing the flavourID for that.

**Comment by LRFLEW** [comment]
JarnoVgr updated the website to remove any reference to architecture on the macOS builds, so using the same flavourID is no longer an issue. I tested the build locally (and on a device with no dev tools or libraries installed to the system) and everything worked. This should be safe to merge now.

**Pull request merged**
