### PR TITLE
Make CMake require C++17

### LINKED ISSUE #7749: CMake doesn't declare dependency on C++17
The CMake scripts should declare that they need a C++17 compiler. At the moment, the compilation fails due to a missing `<string_view>` header.

You can try something like this:

```
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

### PR DESCRIPTION
**Pull request by TheAssassin**
Requires CMake 3.8+ which is the first version to support C++17 (see https://cmake.org/cmake/help/v3.8/prop_tgt/CXX_STANDARD.html).

Fixes #7749.

### CODE REVIEW

**Comment by janisozaur** [comment]
Can you drop setting the standard via compiler options and instead rely on this?

**Comment by TheAssassin** [comment]
@janisozaur this is the CMake way to do it. If you use some custom compiler commandline options, they can be dropped safely.

**Comment by janisozaur** [comment]
Can you please drop them then as part of this PR?

**Comment by TheAssassin** [comment]
Sure.

**Comment by janisozaur** [comment]
Missed a spot: https://github.com/OpenRCT2/OpenRCT2/blob/13224104e49c9f8b24070ace3e5fe87402b89ad3/CMakeLists.txt#L88

**Comment by TheAssassin** [comment]
I didn't look for proprietary VS C++ flags, I don't know them very well. I'll remove it from there, too.

**Comment by TheAssassin** [comment]
By the way, you can also push to the patch branch, if you spot more occurrences.

**Pull request merged**
