### PR TITLE
Map legacy paths in old .PARK saves

### PR DESCRIPTION
**Pull request by Gymnasiast**
This allows loading up older .PARK saves, created before splitting paths.
This includes saves like the one in https://github.com/OpenRCT2/OpenRCT2/issues/15006 and some of @IntelOrca ’s test saves.

### CODE REVIEW

**Comment by ZehMatt** [comment]
Does this only fix loading older .park files? I would argue that we all knew those files would be quite volatile and given that we no longer export those old files its a bit unnecessary in my opinion. One could write a small tool to fix the save file maybe?

**Comment by Gymnasiast** [comment]
> Does this only fix loading older .park files? I would argue that we all knew those files would be quite volatile and given that we no longer export those old files its a bit unnecessary in my opinion. One could write a small tool to fix the save file maybe?

This has been extensively discussed before, and the outcome was that we will at least support "development" saves temporarily, providing an upgrade path (if needed, through multiple version).

**Comment by IntelOrca** [comment]
Would it be better to check if the park format version is older than (version number) and only run this mapping code if it is?

**Comment by Gymnasiast** [comment]
@IntelOrca I don’t think it wouldn’t make a great deal of difference, as it would only match on old names for legacy paths. And it would also provide easy hooks for replacing more legacy paths in the future.

**Comment by IntelOrca** [comment]
@Gymnasiast think about the performance, you are adding checks for every footpath tile element on the map

**Comment by Gymnasiast** [comment]
Good point. I’ll add version checks.

**Comment by Gymnasiast** [comment]
Oddly enough, the save in https://github.com/OpenRCT2/OpenRCT2/issues/15006 has version `2`, which is much higher than expected. Ah well, I’ll limit it to `<= 2`, then.

**Pull request merged**
