### PR TITLE
Part of #21421: Replace define with constexpr

### PR DESCRIPTION
**Pull request by janclod**
Part of #21421 

File affected:
* Ride.h
*  RideRatings.h
* Track.h
* TrackDesign.h

### CODE REVIEW

**Review by tupaschoal — COMMENTED** [review]
Are you using the same branch as in the other PR? Because I see that the first half of the commits are the same ones we have already reviewed.

If so, I recommend you to update your develop branch and then rebase this on top of develop so it drops the changes that have already been merged, so we don't have to review it twice. Let us know on Discord if you have difficulty doing so.

**Review by tupaschoal — COMMENTED** [review]
Are you using the same branch as in the other PR? Because I see that the first half of the commits are the same ones we have already reviewed.

If so, I recommend you to update your develop branch and then rebase this on top of develop so it drops the changes that have already been merged, so we don't have to review it twice. Let us know on Discord if you have difficulty doing so.

**Comment by janclod** [comment]
Yes I am using the same branch... I will try to fix it as you suggest... If I run in to difficulties I will write on Discord...

**Comment by janclod** [comment]
After some experimenting, I did manage to rebase so that only the newest commits are included in PR: see #21626

**Pull request closed without merging**
