### PR TITLE
Added windows/news_options.c to Xcode project

### PR DESCRIPTION
**Pull request by LRFLEW**

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
I take it we have to do this for all new files?

**Comment by LRFLEW** [comment]
@duncanspumpkin Pretty much. This isn't unheard of, considering that something similar must be done for the VS project files. The issue is the Xcode uses a much more obfuscated setup for it. I'm looking into being able to provide a script to allow non-osx users to update the project file, but for now, we should just stick to this sort of thing. Please message me on gitter when new files get merged in, and I'll add them to the project.

**Comment by duncanspumpkin** [comment]
Oh well. Bit annoying.

**Comment by IntelOrca** [comment]
Yeah, at least VS is just simple XML. The xcode project wants guids and stuff for each file.

**Pull request merged**
