### PR TITLE
Update contributors.md

### PR DESCRIPTION
**Pull request by daihakken**
[ci skip]

I requested @Gymnasiast to add it for me 23 days ago to prevent an additional commit and pull request from me, but seems that he didn't help me for that, so I just add it by myself.

proof:
image
https://github.com/OpenRCT2/Localisation/commits/master/data/language/english_us.txt

image
https://github.com/OpenRCT2/Localisation/commits/master/data/language/japanese.txt

### CODE REVIEW

**Comment by Gymnasiast** [comment]
You have been acted very agitated the last weeks. This is both irritating and unjustified. You're acting as if I screwed you over, while I already explained I didn't mention you for US English and Japanese because those were small fixes and you were already credited for being the translator for Traditional Chinese. If I had credited myself for every fix my name would be next to every single language.

**Comment by daihakken** [comment]
_Luckily, I did try to manage my anger before I started this pull request, otherwise I think this pull request will contain a lot of flames._ 

If you mentioned it on gitter, I am sorry to say that did you ever mentioned it on #3306? As I mentioned before in the Localisation gitter (? in late March), I **didn't have time** to visit gitter and skim through all the chats going on there, until **this week** when everything in the reality settled down. Seriously, why you never replied me in the pull request, so that I can read your response **immediately** via e-mail. Making me unnoticed 23 days is very rude and disrespectful in my point of view.

And again seriously, if I want to start drama, why I didn't start one after 2 weeks every time? (Currency one was **few months** and this one was **few weeks** before I start a pull request) Because I am a person that hate drama and actively avoiding from it. I am creating a pull request always after weeks or months **because** I **wait** for your completion/explanation to respect you **but** I can also create it (messily, of course). I sincerely hope that you review what you have done like me, thanks.

**Comment by Gymnasiast** [comment]
If you don't like drama, why are you currently engaging in it? Stop acting like _I_ am the one acting unreasonable here. You are acting like I'm actively trying to screw you over ever since I voiced some objections to adding currencies. I don't. Cut this irritating behaviour out. If you don't, you get blocked. Period.

**Comment by daihakken** [comment]
Am I acting like I **love** to involve in drama??? :/ Oh darling, I would love to spend more time on doing something I like :(. if you can put into someone's shoes like I said in Feb, let's think if your name did not get add into the contributors.md when you request somebody to help you to add your name, and no response has been received like for 3 weeks, however, you suddenly see that guy update that file, which indicate he has seen the comment you have left out, **but** clearly ignore you because of no reason, and see if you will be angry or not.  

And speaking of declining my request, you can just simply close my PR by stating the reason and give me the proof that you said and that's it. Moreover, you should delete the contributors for small fixes in English (US) to **prevent future confusion**. I requested to add my name just because there are small fixes contributors in en-US, and I did commit some fixes to en-US, which even though it is useless today, I still contributed. Other than en-US, I did contribute roughly 10% of currently translated strings in ja-JP, is that too _small_ to get credit or not? **I did not require to credit in bug fixes and documentation which I have also participate in both. Am I screwing you over now?**

Again, if you want to make your "objections" in Chinese currencies look like positive, why not follow my comment posted in Feb and try to improve yourself?
image

Lastly, feel free to block me if you think the comments above are invaild or just *ad hominem*.

**Comment by Gymnasiast** [comment]
Stop getting offended over everything. I have better things to do than constantly having to deal with your angry and completely nonsensical comments.

**Comment by IntelOrca** [comment]
I think this needs to come to end, the PR has been merge. Nothing more to be said.

**Pull request merged**
