### PR TITLE
Refactor logic into scenes (IntroScene/TitleScene/GameScene)

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
This PR is a rebuilt version of the majority of #10180. It introduces the concept of a Scene, which is an abstraction for different tick functions and, ultimately, game states. In this PR, only a GameScene and TitleScene are introduced, while laying the groundwork for additional scenes.

Future work includes refactoring the intro and scenario editor to IntroScene and EditorScene, respectively. Additionally, a LoadingScene can be introduced for the preloading phase of the game.

For testing, please ensure moving between the title scene and in-game scene works correctly at all times.

Should be squash merged, and I'd like @ZehMatt to be co-credited for his work.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
For my understanding: this is only a refactor at this point and should not result in any change of functionality or operation, right?

**Comment by AaronVanGeffen** [comment]
Yes, that's correct. I've deliberately only (re)done the refactor in this PR.

**Review by Gymnasiast — CHANGES_REQUESTED** [review]
Tested it. When `play_intro` is set to true in the config, it will just load to a black screen, no title music, with ambient and coaster sounds playing in the background.

**Comment by AaronVanGeffen** [comment]
Right, that makes sense, considering the following part of the PR:
```diff
-            if (gIntroState != IntroState::None)
-            {
-                IntroUpdate();
-            }
-            else if ((gScreenFlags & SCREEN_FLAGS_TITLE_DEMO) && !gOpenRCT2Headless)
-            {
-                _titleScreen->Tick();
-            }
-            else
-            {
-                gameStateTick();
-            }
+            if (_activeScene)
+                _activeScene->Tick();
```

We could introduce an IntroScene in this PR, or temporarily re-introduce the first part of this if-block.

**Comment by Gymnasiast** [comment]
Having an IntroScene sounds cleaner. I don’t know what it entails in terms of code, though.

**Comment by AaronVanGeffen** [comment]
I've squashed the commits into three atomic ones, and have credited @ZehMatt with the first two commits.

**Review by Gymnasiast — APPROVED** [review]

**Pull request merged**
