### PR TITLE
Display a warning dialog if user runs OpenRCT2 with elevated permissions

### PR DESCRIPTION
**Pull request by rwjuk**

### CODE REVIEW

**Comment by IntelOrca** [comment]
Looks good to me. Should the message be localised though? We don't tend to localise many diagnostic like messages.

**Comment by rwjuk** [comment]
@IntelOrca You know, I thought about that but decided to follow the example of the 'please set your RCT2 path' pre-game dialog, which isn't localised. As you say, it's mostly in-game text that is...

**Comment by pizza2004** [comment]
I feel like the path thing has some visual hints and such, but that some users won't understand what 'elevated' means necessarily even if they speak English, so it might be a good idea to localize.

**Comment by IntelOrca** [comment]
Is there a way of suppressing this message? Could be annoying for someone who is deliberately running in admin mode.

**Comment by janisozaur** [comment]
@IntelOrca I think we should first hear someone complain, then we can figure out a way to suppress the warning.

**Pull request merged**
