### PR TITLE
Fix #12224: crash in scrolling_text_set_bitmap_for_sprite()

### LINKED ISSUE #12224: [ad7bf5] openrct2.exe: scrolling_text_set_bitmap_for_sprite, scrolling_text_setup, fence_paint, sub_68B3FB, paint_session_gen...
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/ad7bf59af1f71f56880ebd1794227c006c258a6c48fd9a6929556424bd618833">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>
<tr>
    <td><strong>Attributes</strong></td>
    <td>
<strong>dummy</strong> &mdash; 1
        <ul>
                <li><code>0</code> &mdash; 1</li></ul><br>
<strong>attachment_replay.sv6r</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\My PC\Documents\OpenRCT2\a9bcf01d-1547-468c-ad3d-f06498f10ef9.sv6r</code> &mdash; 1</li></ul><br>
<strong>attachment_park.sv6</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_config.ini</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\My PC\Documents\OpenRCT2\a9bcf01d-1547-468c-ad3d-f06498f10ef9.ini</code> &mdash; 1</li></ul><br>
<strong>assert_failure</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_park.sv6.gz</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\My PC\Documents\OpenRCT2\a9bcf01d-1547-468c-ad3d-f06498f10ef9.sv6.gz</code> &mdash; 1</li></ul><br>
<strong>attachment_screenshot.png</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\My PC\Documents\OpenRCT2\screenshot\Emerald Pointe 2020-07-12 17-54-43.png</code> &mdash; 1</li></ul><br>
<strong>commit</strong> &mdash; 1
        <ul>
                <li><code>6c3c857</code> &mdash; 1</li></ul><br></td>
    </tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>invalid-read</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
scrolling_text_set_bitmap_for_sprite
scrolling_text_setup
fence_paint
sub_68B3FB
paint_session_generate
window_main_paint
window_draw_single
window_draw
std::_Func_impl_no_alloc&lt;&lt;lambda_c6239a5f162a90c22f819d59f2036264&gt;,void,rct_window *&gt;::_Do_call
window_visit_each(std::function&lt;void __cdecl
window_draw_all
OpenRCT2::Drawing::X8DrawingEngine::DrawAllDirtyBlocks
OpenRCT2::Drawing::X8DrawingEngine::PaintWindows
OpenRCT2::Paint::Painter::Paint
OpenRCT2::Context::RunVariableFrame
OpenRCT2::Context::RunGameLoop
OpenRCT2::Context::RunOpenRCT2
NormalisedMain
wmain</code>
        </td>
    </tr></table>

### PR DESCRIPTION
**Pull request by Gymnasiast**
Now, I haven't been able to test if this fixes the crash, as I cannot reproduce it myself.

### CODE REVIEW

**Comment by janisozaur** [comment]
I'm not entirely happy with hiding this, it would be better if we fixed the source of the problem

**Comment by ZehMatt** [comment]
I just had a quick look at Backtrack, fault.address = 0xffffffffffffffff so this check will not prevent this crash.

**Comment by IntelOrca** [comment]
The null check shouldn't be in the loop, but rather at the top of the function or in the caller.

**Comment by Gymnasiast** [comment]
@IntelOrca Will `scrollPositionOffsets++` never end up with a null pointer?

**Comment by IntelOrca** [comment]
@Gymnasiast Well only if it wraps from 0xFFFFFFFF+, which is probably going to cause an access violation on the previous iteration anyway.

**Pull request closed without merging**
