### PR TITLE
macOS GUI resize should update the model values as a normal resize

### PR DESCRIPTION
**Pull request by Lisergishnu**
This small patch solves an specific issue with macOS, in which, after resizing a window with the green (+) resize button, the game will not save the new window dimensions to the default config file.

Since this uses the same code in platform_resize(...) it still updates the game model window dimensions.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
@LRFLEW or @marijnvdwerf?

**Comment by marijnvdwerf** [comment]
Disagree. When pressing the green plus button, the window opens in a fullscreen space. When you close and relaunch the program, it opens into windowed mode again, taking up all available space (instead of using the previous windowed mode size).

Other applications also open in windowed mode, even after being closed in full-space mode, but restore to their windowed mode size.

If the green button is used in legacy mode however, it should save the new values though.

Also, I discovered a bug that occurs when the config has a higher resolution specified than possible in windowed mode: The window is maximized, but the game resolution is set at the higher mode, causing the game view to be resized.

**Comment by Gymnasiast** [comment]
@marijnvdwerf The fullscreen button does not display a plus, but two arrows. Holding alt changes it into a "maximise" button, displaying a plus.

@Lisergishnu Are you specifically referring to the "maximise" button, and not the full screen button (as featured in macOS Sierra a.o.)?

**Comment by marijnvdwerf** [comment]
@Gymnasiast My bad. Actually never noticed that before.

**Comment by Lisergishnu** [comment]
@Gymnasiast  @marijnvdwerf I'm sorry, when I meant fullscreen resize I wanted to say "legacy mode" as you say. Of course when using the full-space it shouldn't save the window data in the config file.

**Comment by Lisergishnu** [comment]
My original issue was that after closing the game in *full space mode*, the game would open in a window sometimes bigger than the bounds of my screen. After a quick look into the SDL API and the window flags sent with these events themselves, seems to me the engine cannot differentiate between a normal resize (drag with your mouse) and a *full space mode* event. However the SDL API sets a SDL_WINDOW_MAXIMIZED flag when triggering the *legacy* resize button (i.e. the green (+) button)). 

This is the reason I removed the flag for the macOS build so the game accounts for this event and saves the new window dimensions, though a workaround should be considered to prevent this from happening after a *full space mode* resize.

**Comment by Gymnasiast** [comment]
@marijnvdwerf Is this OK to merge as far as you're concerned?

**Comment by marijnvdwerf** [comment]
@Gymnasiast At the moment I'm having troubles with Xcode builds, so I can't validate the workings, except finding that the current handling is broken indeed. Not sure how I feel about platform-specific stuff in `shared.c` though; makes it a bit messy. Also, the `__MACOSX__` define should be used instead of `__APPLE__`.

**Comment by Gymnasiast** [comment]
Hm, you're right.
So as far as I can see the constant should be declared in `platform.h` and defined in the `windows.c`, `macos.c` and `linux.c` files.

**Comment by Lisergishnu** [comment]
Changed the compiler flag following @marijnvdwerf remark.

**Comment by Lisergishnu** [comment]
@Gymnasiast I integrated your comments into the code, creating a new platform specific global function.

**Comment by Gymnasiast** [comment]
Could you move the function from `posix.c` to `linux.c`? `posix.c` is shared between Linux and macOS, while `linux.c` is just for Linux.

**Comment by Lisergishnu** [comment]
@Gymnasiast done!

**Comment by Gymnasiast** [comment]
@marijnvdwerf Are you happy with the changes the OP made?

**Comment by marijnvdwerf** [comment]
I agree with the changes (both code and behavior wise).

However, when restarting the application after having maximized it, I'm getting a flashing white line at the top. This only seems to happen at some dock heights though.

**Comment by Gymnasiast** [comment]
@marijnvdwerf Did that happen before this PR? If not, can I merge this nevertheless?

**Comment by marijnvdwerf** [comment]
Can conform the white line is not a regression. Feel free to merge!

Thanks for your contribution, @Lisergishnu. Apologies for my initial misunderstanding.

**Comment by Lisergishnu** [comment]
Hey. glad to cooperate! The project is so good I had to help somehow. Have a nice one!

**Pull request merged**
