### PR TITLE
Cleanup of B&M coaster types

### PR DESCRIPTION
**Pull request by Gymnasiast**
The vertical RC and the Steel Twister use the same track style, with a handful of missing pieces other side and with different supports. This PR puts the drawing code the pieces in one place, with the support type as an extra parameter.

TODO:
- [x] Finishing moving the functions - the code is migrated, I just need to add some cases to the vertical rc for former twister RC pieces.
- [x] Code style (tabs vs. spaces)
- [x] Removal of current hacks to draw the missing pieces
- [x] Addition to VS
- [x] Addition to Xcode

### CODE REVIEW

**Comment by marijnvdwerf** [comment]
If you're going to name the metal support types, you might as well name all of them.

image

**Comment by marijnvdwerf** [comment]
https://gist.github.com/marijnvdwerf/165e17411148098b9c7639ccab57faa1
This should be all sprite ids used by the two rides.

17152 to 17155 don't seem to be referenced though...

<table>
<tr><td>

</td><td>

</td><td>

</td><td>

</td><td>

</td><td>

</td><td>

</td><td>

</td>
</tr>
<td>17148</td>
<td>17149</td>
<td>17150</td>
<td>17151</td>
<td>17152</td>
<td>17153</td>
<td>17154</td>
<td>17155</td>
</tr>
</table>

**Comment by duncanspumpkin** [comment]
Why the change in the name? We have gone out of our way to remove six flags references it seems odd to revert that. Now when someone says they have a problem with the twister roller coaster we will have to remember that they don't mean a twister roller coaster but mean a b & m.

**Comment by Gymnasiast** [comment]
We haven't removed all Six Flags references. We removed the branding.

What this is about is that the Twister Roller Coaster and the Vertical Drop Coaster use the same kind of track, and this PR makes both use the same methods. Since I had to put a name on that type of track, I chose the name of the manufacturer. The change will not be visible to the end users, just to developers.

**Comment by marijnvdwerf** [comment]
`testpaint` still reports a lot of failures.

```
[  FAILED  ] VerticalDropRollerCoaster.DiagFlatTo60DegDown
[  FAILED  ] TwisterRollerCoaster.BankedLeftQuarterTurn5Tiles
[  FAILED  ] TwisterRollerCoaster.BankedRightQuarterTurn5Tiles
[  FAILED  ] TwisterRollerCoaster.90DegUpTo60DegUp
[  FAILED  ] TwisterRollerCoaster.60DegDownTo90DegDown
[  FAILED  ] TwisterRollerCoaster.Diag25DegUp
[  FAILED  ] TwisterRollerCoaster.Diag60DegUp
[  FAILED  ] TwisterRollerCoaster.DiagFlatTo25DegUp
[  FAILED  ] TwisterRollerCoaster.Diag25DegUpTo60DegUp
[  FAILED  ] TwisterRollerCoaster.Diag60DegUpTo25DegUp
[  FAILED  ] TwisterRollerCoaster.Diag25DegUpToFlat
[  FAILED  ] TwisterRollerCoaster.Diag25DegDown
[  FAILED  ] TwisterRollerCoaster.Diag60DegDown
[  FAILED  ] TwisterRollerCoaster.DiagFlatTo25DegDown
[  FAILED  ] TwisterRollerCoaster.Diag25DegDownTo60DegDown
[  FAILED  ] TwisterRollerCoaster.Diag60DegDownTo25DegDown
[  FAILED  ] TwisterRollerCoaster.Diag25DegDownToFlat
[  FAILED  ] TwisterRollerCoaster.DiagLeftBankTo25DegUp
[  FAILED  ] TwisterRollerCoaster.DiagRightBankTo25DegUp
[  FAILED  ] TwisterRollerCoaster.Diag25DegUpToLeftBank
[  FAILED  ] TwisterRollerCoaster.Diag25DegUpToRightBank
[  FAILED  ] TwisterRollerCoaster.DiagLeftBankTo25DegDown
[  FAILED  ] TwisterRollerCoaster.DiagRightBankTo25DegDown
[  FAILED  ] TwisterRollerCoaster.Diag25DegDownToLeftBank
[  FAILED  ] TwisterRollerCoaster.Diag25DegDownToRightBank
[  FAILED  ] TwisterRollerCoaster.90DegToInvertedFlatQuarterLoopUp
[  FAILED  ] TwisterRollerCoaster.InvertedFlatTo90DegQuarterLoopDown
```

**Comment by Gymnasiast** [comment]
How does the current develop branch do in testpaint?

**Comment by marijnvdwerf** [comment]
Same. But a refactor would offer the chance to fix it, right?
Op vr 30 dec. 2016 om 14:02 schreef Michael Steenbeek <
notifications@github.com>

**Comment by Gymnasiast** [comment]
Hm, but if I change a part on the Twister RC, wouldn't that cause the Vertical RC test for the same part to fail?

Also, we can fix those bugs later, after moving the sources. As long as this PR doesn't introduce bugs, I think we should merge it.

**Pull request merged**
