### PR TITLE
Collapse identical branches

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by janisozaur** [comment]
Both before and after this change, `testpaint` reports (amongst others):
```
[  FAILED  ] MultiDimensionRollerCoaster.LeftQuarterTurn5Tiles
[  FAILED  ] MultiDimensionRollerCoaster.RightQuarterTurn5Tiles
[  FAILED  ] MultiDimensionRollerCoaster.BankedLeftQuarterTurn5Tiles
[  FAILED  ] MultiDimensionRollerCoaster.BankedRightQuarterTurn5Tiles
[  FAILED  ] MultiDimensionRollerCoaster.SBendLeft
[  FAILED  ] MultiDimensionRollerCoaster.SBendRight
[  FAILED  ] MultiDimensionRollerCoaster.LeftQuarterTurn3Tiles
[  FAILED  ] MultiDimensionRollerCoaster.RightQuarterTurn3Tiles
[  FAILED  ] MultiDimensionRollerCoaster.LeftQuarterTurn3TilesBank
[  FAILED  ] MultiDimensionRollerCoaster.RightQuarterTurn3TilesBank
[  FAILED  ] MultiDimensionRollerCoaster.LeftHalfBankedHelixUpSmall
[  FAILED  ] MultiDimensionRollerCoaster.RightHalfBankedHelixUpSmall
[  FAILED  ] MultiDimensionRollerCoaster.LeftHalfBankedHelixDownSmall
[  FAILED  ] MultiDimensionRollerCoaster.RightHalfBankedHelixDownSmall
[  FAILED  ] MultiDimensionRollerCoaster.LeftHalfBankedHelixUpLarge
[  FAILED  ] MultiDimensionRollerCoaster.RightHalfBankedHelixUpLarge
[  FAILED  ] MultiDimensionRollerCoaster.LeftHalfBankedHelixDownLarge
[  FAILED  ] MultiDimensionRollerCoaster.RightHalfBankedHelixDownLarge
[  FAILED  ] MultiDimensionRollerCoaster.LeftEighthToDiag
[  FAILED  ] MultiDimensionRollerCoaster.RightEighthToDiag
[  FAILED  ] MultiDimensionRollerCoaster.LeftEighthToOrthogonal
[  FAILED  ] MultiDimensionRollerCoaster.RightEighthToOrthogonal
[  FAILED  ] MultiDimensionRollerCoaster.LeftEighthBankToDiag
[  FAILED  ] MultiDimensionRollerCoaster.RightEighthBankToDiag
[  FAILED  ] MultiDimensionRollerCoaster.LeftEighthBankToOrthogonal
[  FAILED  ] MultiDimensionRollerCoaster.RightEighthBankToOrthogonal
[  FAILED  ] MultiDimensionRollerCoaster.MultidimInvertedFlatTo90DegQuarterL
[  FAILED  ] MultiDimensionRollerCoaster.Multidim90DegUpToInvertedFlatQuarte
[  FAILED  ] MultiDimensionRollerCoaster.MultidimFlatTo90DegDownQuarterLoop
```
which (duplication of this code) may also be the reason why we have those failures.

@marijnvdwerf ?

**Comment by marijnvdwerf** [comment]
The main issue with the multi-dimension coaster is that the blocked segments don't match for the different rotations. If you look at http://marijnvdwerf.nl/u/1486502815-rct-segments, the grey segments are blocked in all rotations. The coloured ones are only blocked in some though. Usually it's a "3 match, one is off" situation, but the multi-dimension coaster often has two equally used patterns.

**Comment by janisozaur** [comment]
@marijnvdwerf sorry, but I completely do not understand what you're saying.

In context of this PR, but also all other failures in testpaint, how do you suggest we proceed? Is this something we should fix or are you saying that the failures are purely hypothetical and the pieces cannot really be built?

**Comment by marijnvdwerf** [comment]
The pieces can be built. They however don't make sense in the original (different rotations block different segments for support poles). So there is no way to validate. The failures will go away if the pieces are made consistent in our code, which currently imitates the (wrong) vanilla behavior.

**Comment by Gymnasiast** [comment]
So, can this be merged as-is, or?

**Pull request merged**
