### PR TITLE
Refactor Context to return pointer, TTF support to class

### PR DESCRIPTION
**Pull request by janisozaur**
I'm working on a compiler bug and need to write some additional tests for TTF. Current global approach doesn't play well with the kind of tests I need to write and I think the general idea is to have everything migrated into `Context` eventually. I started migrating TTF to use such approach already and I think the code is in a good enough shape to submit PR while I continue working on said tests.

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
Are you expecting every single instance to now church the validity of the pointer?

**Comment by janisozaur** [comment]
Not at all, the services should all be there like they are currently, but I need them done in a dependency injection style, so everything should come from context.

**Comment by IntelOrca** [comment]
> Not at all, the services should all be there like they are currently, but I need them done in a dependency injection style, so everything should come from context.

Why does this mean you can't use reference pointers?

**Comment by janisozaur** [comment]
> Why does this mean you can't use reference pointers?

I believe I ran into some issue with those references, but perhaps the issues were only imaginary or at least I can't recall them exactly right now. Let me try re-doing those tests with references.

**Comment by janisozaur** [comment]
> Let me try re-doing those tests with references

https://github.com/OpenRCT2/OpenRCT2/pull/17648

**Pull request closed without merging**
