### PR TITLE
Fix mistake made in #10579

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
Can we do a check of the codebase for narrowing conversions like this?

**Comment by IntelOrca** [comment]
We probably disabled the warning probably because there are so many. Will be a good effort to go through them all.

**Comment by Gymnasiast** [comment]
Is this one good to go? Does it perhaps need a network version change?

**Comment by duncanspumpkin** [comment]
Yes it will need network version update.

**Comment by tupaschoal** [comment]
> Can we do a check of the codebase for narrowing conversions like this?

There are plenty I'm seeing when removing C-style casts.

**Pull request merged**
