### PR TITLE
Fix #6948 & #6949: Demolishing or trying to build a ride results in inf. loop

### LINKED ISSUE #6948: Demolishing a ride freezes the game
**OS:** Windows 7
**Version:** 0.1.2
**Commit/Build:** 61dfb3d

Demolishing a ride crashes the game  (The game freezes and has to be killed in process manager)

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Open the Electric Field scenario
2. Demolish the Boat Ride

**Dump file**
The game doesn't produce a dump file when this crash occurs.

### PR DESCRIPTION
**Pull request by rwjuk**

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Nice fix. Thanks for taking the time to refactor the magic numbers into `PEEP_THOUGHT_ITEM_NONE`, too!

**Comment by rwjuk** [comment]
@AaronVanGeffen I needed it for the fix, and I have a personal rule not to use magic numbers, even if it means changing the use everywhere else too! :)

**Comment by rwjuk** [comment]
I imagine this'll need a network version bump before merging.

**Comment by duncanspumpkin** [comment]
Looks good can you get this merged asap it's crashing at the moment

**Pull request merged**
