### PR TITLE
Allow logging in single player too

### PR DESCRIPTION
**Pull request by janisozaur**
@duncanspumpkin that's proven useful with replays stuff

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Not to dispute its usefulness, but won’t this generate a bunch of unexpected logs for players who occasionally host locally?

**Comment by duncanspumpkin** [comment]
I don't think this is necessary with the silent recordings.

**Comment by janisozaur** [comment]
The purpose here is the replay only tells you (if you look at stack trace) that there was `GameAction:: Execute`, but there is no info on what the action was. At least not directly in the stack trace, but perhaps I wasn't looking at what the derived type of action was? Anyway, I found it easier to debug this way and it was specifically for replay.

**Comment by tupaschoal** [comment]
I'm closing this for seemingly lack of agreement on its usefulness or impact in the game. Please reopen if you think it's applicable Janis

**Pull request closed without merging**
