### PR TITLE
Implement UTF-8 conversion for Japanese and Korean

### LINKED ISSUE #6855: Corruption in RCT2 scenario names when using Japanese
**OS:** Arch Linux, macOS
**Version:** 0.1.2
**Commit/Build:** 4678829e03e17e561547059547851a26d55862e0

Building the scenario index when the Japanese language pack is active appears to result in some corruption. English appears to be unaffected.

As the index is being built, string truncation messages containing garbage appear in the console:

```
Building scenario index (148 items)
WARNING[../src/openrct2/util/util.c:354 (safe_strcpy)]: Truncating string "芠苈芽芾芯苌荖荢荎荘荴莉荢荏荘腅荸莋荍腛苰" to 64 bytes.
WARNING[../src/openrct2/util/util.c:354 (safe_strcpy)]: Truncating string "芠苈芽芾芯苌荖荢荎荘荴莉荢荏荘腅荏莌腛荧荁" to 64 bytes.
WARNING[../src/openrct2/util/util.c:354 (safe_strcpy)]: Truncating string "芠苈芽芾芯苌荖荢荎荘荴莉荢荏荘腅草莉莓荟苰" to 64 bytes.
WARNING[../src/openrct2/util/util.c:354 (safe_strcpy)]: Truncating string "芠苈芽芾芯苌荖荢荎荘荴莉荢荏荘腅荽荗荢荎荽" to 64 bytes.
WARNING[../src/openrct2/util/util.c:354 (safe_strcpy)]: Truncating string "芠苈芽芾芯苌荖荢荎荘荴莉荢荏荘腅草腛药腛荥" to 64 bytes.
```

Bisecting reveals this to be a regression as a result of 2b2e617086576ae515a44685500957c846bf54c7.

**Steps to reproduce:**
1. Switch to Japanese language pack
2. Delete scenario.idx
3. Start the game
4. Look at any tab containing RCT2 scenarios.

**Screenshots / Video:**
screenshot_20171221_200712

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
This implements conversion from CP932 and CP949 to UTF-8 for use with Japanese and Korean, respectively, enabling OpenRCT2 to use scenario and object descriptions from the original assets for these languages.

Before:
screenshot_20171221_200712

After:
screenshot_20171222_131022

Fixes #6855.

### CODE REVIEW

**Comment by janisozaur** [comment]
Can't we ask iconv to do this for us?

**Comment by AaronVanGeffen** [comment]
We probably could, yes. Not sure how feasible it is in the Windows world, though? Perhaps we could use a Windows library there. Either way, that could replace our implementation for GB2312 and BIG5 conversion as well.

I think that's a matter for a different PR, though. The system as-is works nicely.

In the mean time, @Gymnasiast has pointed out that RCT2 uses Microsoft's variant of Shift-JIS, CP932. I've amended this PR accordingly, but haven't spotted any differences in the conversion yet. (Please squash on merge, though.)

**Comment by Gymnasiast** [comment]
@janisozaur: Possibly, but the other encodings are already implemented in this manner, and with the new object format and save format coming up, I think it's better to do it this way.

**Comment by AaronVanGeffen** [comment]
Per @Gymnasiast's request, I have also implemented CP949 for Korean.

**Comment by IntelOrca** [comment]
For Windows I would like to remove the manual codepage conversions as there is a Windows API for it. I assume that for other platforms, something like `iconv` could be used.

**Comment by Gymnasiast** [comment]
@IntelOrca Yes, although special care should be taken for correctly handling RCT2's dialect of CP1252 - especially w/r/t to formatting codes and Polish characters.

**Pull request merged**
