### PR TITLE
Fix RCT1 (original) imported parks having no ride music

### PR DESCRIPTION
**Pull request by IntelOrca**

### CODE REVIEW

**Comment by Gymnasiast** [comment]
There are two things that might break with this:
- AA and/or LL scenarios
- Saved games

I say _might_, because I'd have to test it.

**Comment by IntelOrca** [comment]
I tested an AA scenario and that works because it uses the music flag in lifecycle flags. The code I have added only gets executed for RCT1 original format.

Could you turn the music off for a specific ride like merry-go-round in the original RCT1 game?

**Comment by Gymnasiast** [comment]
Yes, it was. On the Operations tab (the one with the cogs), there was a checkbox for enabling/disabling it.

Only the merry-go-round and the dodgems had music in original RCT1.

**Comment by IntelOrca** [comment]
I can't find out where it stored the music flag in the original RCT1.

**Comment by Gymnasiast** [comment]
In the same place, as far as I know.
I have an install of original RCT1, so I could create a save with a Merry-go-round to test it. But that will have to wait until I'm home.

**Comment by IntelOrca** [comment]
> In the same place, as far as I know.

It's not the same as AA or LL, its not `RIDE_LIFECYCLE_MUSIC`.

> I have an install of original RCT1, so I could create a save with a Merry-go-round to test it. But that will have to wait until I'm home.

Thanks, that would help. Make a save with the merry-go-round with and without music enabled. That should help narrow down which bytes contains it.

**Pull request merged**
