### PR TITLE
Refactor some Limits.h constants.

### PR DESCRIPTION
**Pull request by Harry-Hopkinson**
Refactored constants:

MaxRidesInPark -> kMaxRidesInPark
MaxStationsPerRide -> kMaxStationsPerRide

### CODE REVIEW

**Comment by Harry-Hopkinson** [comment]
I will keep it to two to try and keep short.

**Comment by Harry-Hopkinson** [comment]
Not sure why the clang-tidy CI is failing...

**Comment by tupaschoal** [comment]
> Not sure why the clang-tidy CI is failing...

Seems to be a problem on the action implementation itself. Would you mind taking a look @ZehMatt ?

**Comment by ZehMatt** [comment]
> > Not sure why the clang-tidy CI is failing...
> 
> Seems to be a problem on the action implementation itself. Would you mind taking a look @ZehMatt ?

Restarted the job, should be fixed.

**Pull request closed without merging**
