### PR TITLE
Entering Peeps already have there speed state set to slow when appropriate. Prevent it from applying the slow speed twice.

### PR DESCRIPTION
**Pull request by blackhand1001**

### CODE REVIEW

**Comment by blackhand1001** [comment]
This change does not affect the speed stuff regarding energy. This only applies to stuff like guests with drinks etc.

**Comment by duncanspumpkin** [comment]
This will require network version increment. I didn't at first realise what you were talking about as you don't mention ride at all.

**Comment by janisozaur** [comment]
You will need to update network version and make your commit messages adhere to https://github.com/OpenRCT2/OpenRCT2/wiki/Commit-Messages before this can be merged

**Comment by Gymnasiast** [comment]
Could explain more about this? How do you know it applies the slow speed twice, for example?

**Comment by Gymnasiast** [comment]
bump

**Comment by Gymnasiast** [comment]
Since the OP seems to be gone and the actual problem is not clear at all, I'll close this.
@blackhand1001 Feel free to reopen if you ever resurface.

**Pull request closed without merging**
