### PR TITLE
Enable all C++ features for MSVC

### PR DESCRIPTION
**Pull request by IntelOrca**

### CODE REVIEW

**Comment by Margen67** [comment]
Does this improve performance?

**Comment by IntelOrca** [comment]
No, this won't affect performance

**Comment by janisozaur** [comment]
What was missing? Do you already have usage of these new things planned somewhere? And latest means which one for VS2015, 14?

**Comment by IntelOrca** [comment]
@janisozaur The only thing I have needed it for is the ability to write namespace declarations like
```
namespace A::B::C
{
    ...
}
```

This is only available in VS2015 Update 3 and onwards.

But I think it also enables a number of extra std headers like tuples and what not. Something @LRFLEW  might be interested in.

**Comment by janisozaur** [comment]
According to http://en.cppreference.com/w/cpp/compiler_support, there's most of C++14 already in 14.2

With travis now on Ubuntu 16.04 which provides GCC5 and Clang 3.8, we should be fine with using C++14 from now on.

**Comment by janisozaur** [comment]
@IntelOrca the feature you mention looks to only be available in GCC6/C++17.

**Pull request merged**
