### PR TITLE
Track data C++

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by janisozaur** [comment]
As these are just data tables, I have not applied any formatting there

**Comment by janisozaur** [comment]
Explicitly setting struct size to largest entry significantly increases `.rodata` size, suggestions how to improve it welcome.

**Comment by Gymnasiast** [comment]
> Explicitly setting struct size to largest entry significantly increases .rodata size, suggestions how to improve it welcome.

Is it necessary to explicitly set it? It worked fine before.

**Comment by janisozaur** [comment]
Yes, it's needed, as it's not properly supported part of C++. See https://travis-ci.org/OpenRCT2/OpenRCT2/builds/288496812

**Comment by janisozaur** [comment]
@Gymnasiast I think the Xcode fix got mixed up with https://github.com/OpenRCT2/OpenRCT2/pull/6505, can you fix it again?

**Comment by LRFLEW** [comment]
Perhaps...

So the problem is that C++ doesn't allow for the `const rct_vehicle_info info[];` type of syntax. Well, there is one simple solution that I see.

`type[]` is the same thing as `*type` in the C type system, so replacing it with `const *rct_vehicle_info info;` *should* work. The only problem is that you can't use an initializer list for a pointer (the way the C code did), but either explicitly making a second variable, or using a macro to simplify the code should work.

**Comment by Gymnasiast** [comment]
@janisozaur Would that be a good solution, as far as you're concerned?

**Comment by janisozaur** [comment]
What @LRFLEW said is the best thing I have also come up with, I will implement it and update this PR

**Comment by janisozaur** [comment]
@Gymnasiast can you fix Xcode project _again_? It doesn't rebase well…

**Pull request merged**
