### PR TITLE
New StringIds and condition fix.

### PR DESCRIPTION
**Pull request by HaasJona**
Add some named StringIds and replace occurences. Fixed the in ride/on ride condition for tracked peep notifications, as it was reversed. The notitication for tracked peeps will now say "is on rollercoaster" rather than "is in rollercoaster".

### CODE REVIEW

**Comment by janisozaur** [comment]
Can you please alter the commit message so it is properly formatted for oneline display? See http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

**Comment by HaasJona** [comment]
I hope this is okay

**Comment by janisozaur** [comment]
Yup, thanks.

**Comment by AaronVanGeffen** [comment]
Yeah, there is a bunch of these left to refactor. I really like seeing this kind of cleanup -- code quality is much improved by having constants identified as such. Cheers, @HaasJona.

**Comment by Gymnasiast** [comment]
:+1:

**Pull request merged**
