### PR TITLE
UI Building Enhancements (Anchoring / Resizing)

### PR DESCRIPTION
**Pull request by seifer7**
### **You can see it in action by taking a look at the "Extra Viewport" window in-game.**

There is **no** coding in this Window to keep the window frame, titlebar, close button, viewport, resize grip, zoom in/out or locate buttons in their correctly anchored positions or sizes.

No longer will we be required to put anchoring or resizing logic into each Window.
Just set the relevant flags on the widgets and it's all taken care of by the Window controller class.
Also automatically draws viewports in the correct position (by finding the viewport widget in the Window.)

---
### New widget flags:
`WIDGET_FLAGS::ANCHOR_RIGHT`
`WIDGET_FLAGS::ANCHOR_BOTTOM`
`WIDGET_FLAGS::FIT_WIDTH`
`WIDGET_FLAGS::FIT_HEIGHT`

There are no flags for anchor left or anchor top as this is the default.
The absence of `ANCHOR_RIGHT` or `ANCHOR_BOTTOM` implies the opposite.

---
### Updated `MakeWidget` function to accept flags
```
rct_widget MakeWidget(
    const ScreenCoordsXY& origin,
    const ScreenSize& size,
    WindowWidgetType type,
    WindowColour colour,
    uint32_t content = 0xFFFFFFFF,
    rct_string_id tooltip = STR_NONE,
    uint32_t flags = 0)
```

---
### New `MakeWidget` function override for use with `FIT_WIDTH` or `FIT_HEIGHT` flags
```
rct_widget MakeWidget(
    const ScreenCoordsXY& marginTopLeft,
    const ScreenSize& size,
    ScreenCoordsXY marginBottomRight,
    WindowWidgetType type,
    WindowColour colour,
    uint32_t content = 0xFFFFFFFF,
    rct_string_id tooltip = STR_NONE,
    uint32_t flags = 0)
```

### CODE REVIEW

**Comment by IntelOrca** [comment]
This is certainly one way of going about this. We have also had discussions in the past about using [yoga](https://yogalayout.com/) or making our own equivalent. Effectively adding new container widgets that automatically layout the child widgets. Parenting could be done with another index field on Widget.

**Comment by seifer7** [comment]
I'd definitely love something like yoga, and I had the exact same thought, that we need layout widgets that can automatically build the Window out.
This pull request (suggestion/discussion) is a simple way I thought of to alleviate some of the mundane coding associated with anchored and dynamically sized Widgets.
It could be applied fairly quickly to the existing Windows that have been refactored already.

I wanted to see what others thought of this implementation.
I also wanted to build in automatic tabs (placement/spacing) and page changing.

**Comment by rik-smeets** [comment]
@seifer7 @IntelOrca Is this something we want to continue working on? If not, I'll close this PR.

**Comment by IntelOrca** [comment]
I think this should be re-visited after all the windows have been converted to classes. I think "container" widgets would be a better approch than achoring flags as that would allow automatic positioning as well as automatic sizing.

**Comment by rik-smeets** [comment]
I'll close this for now, it can be reopened whenever someone wants to continue working on this (preferably after the changes @IntelOrca mentioned have been realised).

**Pull request closed without merging**
