### PR TITLE
Replace remaining usages of money16, money32

### PR DESCRIPTION
**Pull request by Gymnasiast**
Removes all remaining usages of money32, money16 and money8, allowing us to get rid of several casts.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
I have one for the money32 coming up too. @duncanspumpkin would you like me to add it to this PR (so you only have to re-record the replays once), or have it in another one?

**Comment by duncanspumpkin** [comment]
could you address the build warning.

**Comment by Gymnasiast** [comment]
@duncanspumpkin That should be the build warning addressed.

**Review by duncanspumpkin — APPROVED** [review]
I'll record the replays when i get a moment but not sure when that will be.

**Comment by duncanspumpkin** [comment]
Needs a network version bump

**Comment by janisozaur** [comment]
Sounds like there is a bug and this is a recent commit that touched this area. Please check: https://www.reddit.com/r/openrct2/comments/11hjm4l/inverted_money/

**Comment by janisozaur** [comment]
And one more: https://www.reddit.com/r/openrct2/comments/11hmas5/how_to_go_from_9_million_to_9_million_in_a_second/

**Pull request merged**
