### PR TITLE
Add ORIGINAL_RATINGS flag to RideRatings.cpp

### PR DESCRIPTION
**Pull request by Harry-Hopkinson**
Add ORIGINAL_RATINGS for @romantyke

### CODE REVIEW

**Comment by janisozaur** [comment]
Thanks @Harry-Hopkinson I wanted @romantyke to create a fork of their own and submit that PR to it, that way they could update whenever they want.

**Comment by romantyke** [comment]
> Thanks @Harry-Hopkinson I wanted @romantyke to create a fork of their own and submit that PR to it, that way they could update whenever they want.

That is very kind of you. Thank you for your trouble.

**Comment by Harry-Hopkinson** [comment]
That does sound better - do you know how to create a fork?

**Comment by romantyke** [comment]
> That does sound better - do you know how to create a fork?

Not at all. Like I said, I am totally new to Github. This is all very complicated and I feel like a noob.

**Comment by romantyke** [comment]
Hmm... The Windows 64 download is in red. Is it normal?

**Comment by janisozaur** [comment]
We have tests that validate ride ratings are correct. Since they got changed in this PR, this is obviously failing

**Pull request closed without merging**
