### PR TITLE
Pass DPI by ref to string drawing

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by ZehMatt** [comment]
I think it would have been better to start off with the functions that start passing DPI down such as the window code, because those functions receive a pointer and the drawing functions now take reference it needs to change the line to dereference it first which leads to a lot of line changes, if this gets further refactored one has to basically undo a lot of lines again.

**Comment by Gymnasiast** [comment]
Could you give me more specific examples of which functions I should refactor first?

**Comment by ZehMatt** [comment]
Its a general top to bottom issue, maybe you can actually look into making all the Windows function receive DPI as a reference in this PR, that would eliminate most of the lines that are forced to do it currently. If we merge this as is the next person refactoring the passing of DPI as reference would be forced to undo a good chunk of the changes from here.

**Comment by Gymnasiast** [comment]
The windows already receive a reference to a dpi - the ones that have been refactored to classes at least.

> If we merge this as is the next person refactoring the passing of DPI as reference would be forced to undo a good chunk of the changes from here.

I understand, hence why I’m asking which functions I should start with instead.

**Comment by ZehMatt** [comment]
Try doing the window functions where you have to pass it as *dpi, you can use the diff to see where it requires *dpi now, its a few.

**Comment by Gymnasiast** [comment]
But that would cause enormous merge conflicts with PRs like https://github.com/OpenRCT2/OpenRCT2/pull/19477 (which ports old windows) - all for functions that are going away (as the functions that remain already take references). Surely that's not the intention?

**Comment by ZehMatt** [comment]
The functions don't really go away, someone would still need to change *dpi to dpi at some point if we take this as is, porting the window code is mostly copy paste work so it would be most likely be taken as is, perhaps avoid the files of that single PR then it should be just a few lines to fix after its merged. Also with changes like this we don't have to really look for logic changes as its just a change of syntax so why not just do it all?

**Review by duncanspumpkin — APPROVED** [review]
As the work is already done I don't see much point redoing it from the other direction.

**Comment by Gymnasiast** [comment]
> Also with changes like this we don't have to really look for logic changes as its just a change of syntax so why not just do it all?

I actually tried to do that at first. But then I ran into the same problem with the Land window as you had a few years ago :')

Anyway, I will look into the window functions, though I might try and finish the window porting first.

**Pull request merged**
