### PR TITLE
Remove Intamin and Phoenix Easter eggs

### PR DESCRIPTION
**Pull request by Gymnasiast**
RCT2 contains quite a lot of Easter eggs. Many of them are nice, but some seem more like in-jokes that aren't funny to people outside the dev team. This one removes two of the latter kind.

### CODE REVIEW

**Comment by IntelOrca** [comment]
I guess it falls under the same category as six flags.

**Comment by Stevoisiak** [comment]
I feel like these should be left in. There are [multiple](http://www.eeggs.com/items/37903.html) [sites](http://rct.wikia.com/wiki/Cheat_Codes#RollerCoaster_Tycoon_1_and_2_Cheats) [and](http://www.cheatcc.com/pc/rollerct2.html) [guides](http://www.ign.com/faqs/2004/rollercoaster-tycoon-2-hintstips-575834) documenting these easter eggs. It'd be a little strange if these names no longer worked

**Comment by Gymnasiast** [comment]
@Stevoisiak A lot of documentation written for RCT2 doesn't apply to OpenRCT2.

**Comment by Stevoisiak** [comment]
@Gymnasiast True, but I don't see a reason to purposely remove an easter egg from the original game, even if it was an in joke.

**Comment by RollingStar** [comment]
I'm pretty disappointed in this commit.

1. This change is not authentic to original RCT2
2. This change removes soul and character from the original game, without replacing it with anything similar
3. You're putting in extra effort to remove a feature
4. The easter egg harms nobody, because it has to be manually and deliberately activated

**Comment by Gymnasiast** [comment]
Sigh... this is not the first time you complain about removal of (anti-)features. If you want an authentic RCT2, I recommend RCT2.

But well, I'll run through your points:
1) Neither is fixing original bugs, removing anti-cheat code or adding features. OpenRCT2 is supposed to be different. There would be little point otherwise.
2) This is ridiculous, as if two small in-jokes that most cheat sites were not even aware of are in any way significant to the 'soul' or 'character' of a game.
3) And? I put in effort to keep the game maintainable, which includes pruning unnecessary functions.
4) It adds bloat to the code. It's easy to complain if you're not the one who has to maintain the code.

Another note: your only contributions are a few corrections to the documentation. You mostly seem to come here to complain. That's getting old.

**Comment by Patrik356b** [comment]
I know i'm late on discovering this but i don't see the problem with Andy Hine easter egg

**Comment by AaronVanGeffen** [comment]
@Patrik356b Yeah, there really isn't much use in replying *two years* late…

**Pull request merged**
