### PR TITLE
Remove unused tutorial and guest number strings

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Wow, I'm surprised none of those guest strings were used at all…

**Comment by Gymnasiast** [comment]
One was ;-)

**Comment by AaronVanGeffen** [comment]
Ah, the last occurrence rather than the first. Gotcha.

**Comment by Nubbie** [comment]
The guest string seems fine to remove, but aren't the tutorial strings good to keep "just in case", as it's plenty of text _(however useless if a new tutorial is created)_

**Comment by Gymnasiast** [comment]
We have source control (Git) to get those back, _if_ they're ever needed again.

**Pull request merged**
