### PR TITLE
Close #12387: Refactor PeepThoughtType to use strong enum

### LINKED ISSUE #12387: Refactor PeepThoughtType to use strong enum

### PR DESCRIPTION
**Pull request by frutiemax**

### CODE REVIEW

**Comment by pizza2004** [comment]
I wish I'd said something.  I just spent about an hour doing this same thing.

**Comment by frutiemax** [comment]
@pizza2004 I just saw your PR and I see you've created a separate namespace for the peep type.

**Comment by pizza2004** [comment]
True, mine is probably at least good for introducing the namespace.

**Comment by duncanspumpkin** [comment]
@frutiemax can you rebase this. We never merged #12465 so this work can be brought in as is. Namespace changes can be done separately.

**Pull request closed without merging**
