### PR TITLE
Fix RCTC g1.dat rendering issues

### LINKED ISSUE #6328: Using RCTC's g1.dat results in a broken banner font
forest frontiers 2017-09-29 11-01-41

### PR DESCRIPTION
**Pull request by LRFLEW**
This fixes #6328. More specifically, it fixes three different problems when using the RCTC g1.dat:

1. The scrolling text (on banners and entrances) rendered 16 pixels to the right. This was due to an error in the script I used to generate the mapping between RCT2's g1.dat and RCTC's g1.dat. Specifically, I wasn't accounting for the values `x_offset` and `y_offset`. Changing the mapping slightly fixed this issue.

2. The character spacing was too narrow. The tiny font had its outline removed in RCTC, so the sprites were smaller (by two pixels in each dimension) and added an offset (one for both directions). By changing `font_sprite_initialise_characters` to take into account `x_offset`, this issue was resolved.

3. When a player picks up a peep, their sprite doesn't line up with the cursor. This is because these sprites have new offsets in RCTC, likely because of the reworked pincer as part of the new UI. I added some code to `read_and_convert_gxdat` which corrects for these changes.

The tiny font (used for the scrolling text) is different in RCTC, so the banners are not going to look identical, and they still have some improvements that can probably be made. Specifically, I noticed that the "R" doesn't look good. Based on my own experiments, it appears that RCTC's tiny font was using some anti-aliasing, which makes it hard to convert it to a bitmap for the banner. This, however, fixes the the main issue at hand, and cleaning up the font can happen another time.

### CODE REVIEW

**Comment by LRFLEW** [comment]
I figured out a simple way of improving the rendering of RCTC's tiny font. It's still decidedly different from RCT2's tiny font, but this makes all the letters actually legible, including R, Y, X, K, and Q (which previously looked like O).

**Comment by pizza2004** [comment]
Any picture comparisons?  Just curious to see the differences.

**Comment by LRFLEW** [comment]
@pizza2004 For the font? I plan on putting some detailed information in #4909 once I have the time.

**Comment by LRFLEW** [comment]
@pizza2004 Using some rather silly code, I made a sprite sheet of the basic character set as it would be rendered on the banner using this PR for both RCT2 and RCTC's fonts. Left is RCT2, Right is RCTC.

rct2_bannerrctc_banner

Interestingly, the other characters (symbols and accents) don't have any antialiasing, and other than some slight changes to the offsets, they are exactly the same as in RCT2 (just without the outline).

**Comment by pizza2004** [comment]
Interesting.  I actually think I like most of the changes I notice in the RCTC font except that O and 0 look the same now.

**Pull request merged**
