### PR TITLE
Added build target appbundle on OS X

### LINKED ISSUE #2463: OS X build should have a proper icon
kiii78t

We have no icon on OS X (see the 6th icon from right, the one with "exec"). We should use the flag logo.

### PR DESCRIPTION
**Pull request by LRFLEW**
This resolves #2463

Thanks to @kkirby for helping with this once we realized we were both working on it at the same time.

I did add the .icns file to the repository, but I felt that because the file type is similar to the .ico format, the presence of the icon.ico file justifies adding the .icns file. If you disagree, I can use kkriby's script to generate the icon file on build.

### CODE REVIEW

**Comment by janisozaur** [comment]
Shouldn't it also get compressed for distribution?

**Comment by janisozaur** [comment]
`resources/logo/icon.icns` is missing, it seems

**Comment by LRFLEW** [comment]
Should what get compressed? Also, I see the icon in the file diff page (it says "Binary file not shown").

**Comment by janisozaur** [comment]
Oh, right. I was using some github client for android and the icon file was shown differently to other files. Indeed, it's there.

About compression - I meant the app bundle, as we could use Travis for providing automated builds. You could add target "appbundle_compressed" which would simply zip (or whatever format you use) and then push to either  openrct2 website or tranafer.sh and ping the websites with links.

**Comment by LRFLEW** [comment]
I added an "appbundle_compressed" target that compresses the app bundle into a zip file. I'm not sure about uploading to the website, but what I added at least handles the compressing.

**Comment by janisozaur** [comment]
I don't have access to cmake docs right now, but it seems you added the `ALL` option, implying the target should be always built. Is this really what you want? This target will be built on every `make` invocation. Personally I'd find this quite annoying. Perhaps it makes sense on OS X, but just wanted to run that past you.

I can alter the transfer branch I use for purposes of extracting things from Travis to your needs tomorrow. Perhaps I can pull @JarnoVgr or @runelaenen into this, so the website could host the builds.

**Comment by LRFLEW** [comment]
> it seems you added the ALL option, implying the target should be always built.

For the app bundle, yeah, I meant the `ALL` option, as it will be expected by users just looking to build and run the game. I forgot to remove it from the compressed target, so I removed it now.

**Comment by pizza2004** [comment]
Yes, the .icns file needs to be included, as it really should include like 10 different PNG images inside of it in order to look proper on all systems.  You forgot to include retina versions of each PNG, hold on, I can do that.

**Comment by janisozaur** [comment]
OK, fair enough. Now the only thing that's left is for me to provide proper Linux builds as well, seems you have beaten me to the punch in that field.

**Comment by LRFLEW** [comment]
@pizza2004 Mind elaborating on that? I was just using Apple's provided Icon Composer, and it didn't have options of that.

**Comment by janisozaur** [comment]
@pizza2004 can you include svg or is it PNG only?

**Comment by pizza2004** [comment]
Sorry, I should clarify.  The tool to build the .icns file with retina support is only available on OS X, and I don't think it makes much sense to not just include it, and it would mean having 10 PNGs, several of which are just copies included with specific names, because the ones I found in the repository already do not have the proper names to build an .icns file.

**Comment by LRFLEW** [comment]
@janisozaur I can answer that. .icns does not support SVG images.

**Comment by LRFLEW** [comment]
> The tool to build the .icns file with retina support is only available on OS X

I'm on OS X and I don't know of a tool that does that. Is it something in Xcode?

**Comment by pizza2004** [comment]
Yeah, Icon Composer hasn't been updated for a few years now, they don't provide a GUI interface that I've seen, and instead require it be built from the command line with specifically named PNG files.

**Comment by pizza2004** [comment]
https://developer.apple.com/library/mac/documentation/GraphicsAnimation/Conceptual/HighResolutionOSX/Optimizing/Optimizing.html

**Comment by kkirby** [comment]
My version of this produced the iconset from a single PNG: https://github.com/kkirby/OpenRCT2/blob/feature/apple-app-bundle/CMakeLists.txt#L156

I'm not sure if that would help in this situation, though.

**Comment by LRFLEW** [comment]
@kkirby It's redundant since the project already has all of the sizes in it.

**Comment by pizza2004** [comment]
@kkirby Yeah, that's basically what we would do, but with the proper sizes already included, rather than all from one.  At least if we were building it every time, but there's no real reason to do that.

**Comment by kkirby** [comment]
@LRFLEW, pizza2004 was talking about the retina versions, which I assume your icon doesn't have.

**Comment by LRFLEW** [comment]
I'm working on adding the retina version right now

**Comment by pizza2004** [comment]
I already made a retina version if you'd like it.

**Comment by pizza2004** [comment]
icon
This should work, just rename it to a .icns and it should be the correct file.

**Comment by pizza2004** [comment]
So this reminds me though.  What's retina support like on the OS X version at the moment?  I imagine that would be nice to have for the non-English language fonts, but other than that I don't know, probably just allowing more detail when it's zoomed out.  Then zoomed out one step could be equal to zoomed all the way in on the detail, while the interface is still a regular size.  Then when we get high resolution graphics packs it can support retina all the time, even on the interface.  That would be really awesome.

**Comment by kkirby** [comment]
@pizza2004 I think @janisozaur implemented DPI scaling, if that's what you're talking about.

**Comment by LRFLEW** [comment]
Ok, I added the updated .icns file. As to the HiDPI support on OS X, the game does support scaling, but it currently won't recognize HiDPI displays as such. It's a simple change in the code, but I'll make that change later, as it will require some work to be user-friendly.

**Comment by pizza2004** [comment]
Well, I guess the main thing for me with retina vs. HiDPI, it has to be able to see that it's a retina (twice the size, so 200% scaling) and use 2x versions of graphics, and render fonts at the retina size.  I don't know what sort of support SDL has for that specifically, and I know at the moment the in game graphics won't be doing that, but I'd hope that in the future, even if we do add another level of zoom, that we build the graphics system in a way that it supports 200% resolution graphics, compared to the size we actually display them at.

**Comment by pizza2004** [comment]
Oh!  And I guess I had a different question that's more related to this specific pull.  Are we thinking we want it to all be a self contained bundle, like your average OS X app, or more like OpenTTD and some others, where the App Bundle is still in a separate folder with all the data files inside the folder rather than embedded in the bundle.  I'm a fan of bundling it directly into the bundle itself, and putting anything that we wouldn't directly package into the game into either the users folders, or the shared user folder (for stuff like graphics and sound packs), rather than trying to have a folder specifically for all the data, since that's standard practice on Mac, and it also would make it easier if someone wanted to do anything like building it for iOS or releasing it through the Mac App Store, once it's capable of being run without any files from RCT2.

**Comment by pizza2004** [comment]
The main question in that case would just be how do we show people how to include the files for RCT1 and RCT2, like scenarios or graphics, if they want to use those.  Personally, I think it would probably be best and simplest to just have it be an in game thing with clear instructions, and then let the game handle moving the files to the proper destination and such.

**Comment by LRFLEW** [comment]
@pizza2004 I've made the bundle self-contained, so it can run if copied elsewhere. The config file is still used to locate the RCT2 folder, which might change later, but I don't think it will.

**Comment by janisozaur** [comment]
@pizza2004 have the game act as a wannabe file manager and copy the files all over the place? Sorry for being blunt, but that sounds just like asking for trouble. To me it's just as bad idea as your "let's not have osx build just because it's 32 bit".

**Comment by pizza2004** [comment]
I was just saying that it might not be worth the effort, since the only reason to have it build in 32 bit is because the original is in 32 bit, and OS X can't do all the fancy hooking in to run stuff anyway.

On OS X more than anywhere it's kind of expected that the App will handle all your files, and that you won't really be expected to go in and drag files around to use them or anything, but I'm just trying to think of what would be best for the user who doesn't have a Windows machine and doesn't know anything about using Wine or anything, but still wants to play using the original scenarios and stuff.  And making sure the game itself keeps all the files in the proper places is good.  That said, I was mostly just talking about where files should be stored on OS X, because it's not common practice to have a folder around the App with all the data files in it, but some files need to be cross-user and some need to be per-user.

**Comment by Gymnasiast** [comment]
Look, you need to copy the files from Windows or Wine anyway, as getting them requires an RCT2 install first. Telling users to copy those folders to Downloads or another is the least difficult part of that.

Also, your statement about the hooks is false. It is working, and it will need to stay 32 bit as long as the original executable is still needed.

I'm afraid to say your comments are usually more opinionated than knowledgeable. This gets old very quickly, especially considering you haven't contributed in terms of code, assets or localisation.

**Comment by pizza2004** [comment]
> Look, you need to copy the files from Windows or Wine anyway, as getting them requires an RCT2 install first. Telling users to copy those folders to Downloads or another is the least difficult part of that.
Sorry, I'm just sort of spitballing for the future, giving my opinion on what I think would provide the nicest user experience.  I'm not saying it's necessary or anything.  I just think, if there's any way to extract the files from the GOG .exe or something on OS X, instead of requiring that people jump through hoops and download another program they might not want (Wine) just to play the game with the original scenarios.

> Also, your statement about the hooks is false.
This I don't understand at all.  How can OS X be running Windows machine code?  That's what I mean, that you can't run the original executable to run original functions, unless computers don't work at all the way I've always been told they do. :P

Anyway, I'm sorry if I'm somehow a bother to you.  I don't have any ability to decompile and rewrite the assembly code, otherwise I would be doing some actual coding here and there.  I don't understand this sudden backlash when I'm honestly just trying to throw out ideas on how to best handle having the game as a self contained bundle, but still thinking about the future, and where files would be stored and what best way to indicate that to the user.  I haven't seen anyone else do anything except sort of act like the idea I've presented were stupid without giving any sort of counter idea at all.

**Comment by pizza2004** [comment]
And honestly, as far as the OS X build goes, since the game isn't fully decompiled I just always figured what was the point in going to the hassle of making it work in 32 bit just so that you could run a buggy unfinished version of the game on OS X, when as soon as it's fully decompiled and rewritten we can just make it run in 64 bit and it will be entirely functioning and whole.

Now, I'm going to be very clear here.  I never said that people weren't welcome to do so anyway, I just wanted to point out that it wasn't necessarily worth the time at the moment to do all that, rather than actually working on decompiling.  If there are people around that can't decompile that have OS X and want to work on it that's entirely up to them.

**Comment by kkirby** [comment]
@pizza2004 about your question about the hooks. The assembly is in i386. An Apple computer's processor can read these instructions. The team here has already disassembled all the Windows specific i386 instructions. This is how it's possible.

**Comment by janisozaur** [comment]
@pizza2004 

> This I don't understand at all. How can OS X be running Windows machine code? 

This is where your assumptions fail. It's not *Windows* machine code (there isn't such a thing), but *i386* machine code. If you strip away all the platform shims and replace them with your own, the remainder of the code doesn't care, as long as it has some surface to render to, the hardcoded addresses it uses for storing its values, etc…

We can work with the code as long as the call chain is contained entirely in our code, but when we cross boundary to vanilla, it's all black box from code's point of view, we can only wait till the function called returns so we can resume our work.

Enter hooks, a way to subvert execution flow, in run-time, from vanilla, to our own functions. Since original was written in assembly, it was not tied to any particular calling convention you may know from other languages. This is why it has to written in a way it is, as even asm inlines don't provide the same level of guarantees we need (i.e. writing to exactly specified addresses in memory or run-time configuration of needed registers). This is basically a calling convention translation shim, just like `RCT2_CALLPROC_X`, but working in opposite direction and somewhat more dynamic.

Now we can have code allowing safe passage of these boundaries through multiple layers, which allows us things like utf8 support and other whatnots.

You can compare this approach with WINE ([*Wine Is Not an Emulator*](https://www.winehq.org/about/)), which works in somewhat similar, albeit much more sophisticated and universal way. None of the two (WINE and us) does any emulation, as it isn't required. Just let the program in question *think* it is running in environment it expects and it will work just like you would expect.

I hope this explains the details well enough.

**Comment by LinusU** [comment]
@LRFLEW maybe mark the `PkgInfo` file [as binary in git](http://stackoverflow.com/questions/11162267/how-do-i-make-git-treat-a-file-as-binary), this will prevent it from showing up as text in the diff and any problems where newline will be converted on windows.

**Comment by LinusU** [comment]
I just tried copying in files from my RCT2 installation into `OpenRCT2.app/Contents/MacOS/data/` and it worked great! The thing I really like about this approach is that all the files that are needed are contained in the same place.

Maybe we could have some optional build step that copies the files in somehow, I don't know exactly how it would work since it's very important that we never distribute the resulting files. This would only be of use for people that builds themselves. It might actually be better suited for the launcher.

It would be fun to build a small application that prompts you to enter your original RCT2 cd, and then extracts the relevant files from the `.cab` files, bundles them into an `OpenRCT2.app` bundle, and lets you save that somewhere. I think that would be really neat.

@LRFLEW Could also rebase this on the latest `develop`? It would be nice to get it to save the config in `Library/Application Support`. Thanks!

**Comment by janisozaur** [comment]
@LinusU that sounds like a good idea, but out of scope for openrct2, so you may want to use another repo for that.

**Comment by pizza2004** [comment]
@janisozaur Thanks for the explanation!  I know more now.  I haven't had any formal programming education, so it's mostly what I've picked up on my own from working on my own stuff and a little with my friend and for a different project online around 6 years ago mostly.

Also, the CD thing is basically what I was saying, just something simple that would copy everything into the right place.  It might be possible to build it as an installer on OS X and allow the installer to move everything around properly, but I don't know enough about that personally to say.

**Comment by JarnoVgr** [comment]
What can I do for you guys? This concerns Mac OS X builds right? Is it possible now to distribute binaries? :)

**Comment by janisozaur** [comment]
@JarnoVgr I guess there is no way for you to create native osx builds, so once we have them enabled on travis (cf. #2401), could you perhaps expose an endpoint to which we could upload builds and you could simply shift them to be available for download? The same can be true of Linux builds. Travis can be made to have a proper key/certificate, so proper auth shouldn't be an issue.

**Comment by JarnoVgr** [comment]
@janisozaur If it's really needed I could setup a Mac OS X VM. But using Travis makes more sense as it's a lot easier to setup and maintain. I'm all for using Travis.

**Comment by pizza2004** [comment]
I would suggest this be updated to include all required libraries, so that we don't have issues if someone doesn't have one of them installed, as I am currently having on my other machine.

**Comment by janisozaur** [comment]
@pizza2004 no, the package managers are there for a reason. We're not going to track all the dependencies when your package manager is perfectly capable of doing that and it's only your broken setup that's the problem.

**Comment by pizza2004** [comment]
@janisozaur What are you talking about?  The standard practice on OS X is to include any frameworks that don't come packaged with the system inside the App Bundle.  There are 6 frameworks I had to copy into specific folders on my MacBook Pro in order to get it to run at all (the folders they would be built to if I had Brew and were installing manually) which isn't the proper behavior at all.

**Comment by pizza2004** [comment]
I was wanting to send my friend a copy, but as long as the frameworks have to be in such a specific folder I don't expect him to jump through the hoops to get it working on his machine, and looking at the files modified here I don't know exactly how to fix it myself.  If it were an Xcode project I could do it, but I have no experience with all this command line stuff.

**Comment by LRFLEW** [comment]
@pizza2004 I'm aware of that issue. Right now, it's not feasible to make that work consistently with how the builds are being setup. It's on my list, and once this gets merged, I'll work on including the dylib files.

As for getting a friend to install it, what's so hard about getting him to run a single brew command? I understand that this isn't the most elegant solution, but it's more important to get each part individually working right now than it is to create a super-massive fix.

**Comment by pizza2004** [comment]
He's not a developer, so he doesn't have Xcode or anything necessary to build at all installed.  It's not super important, since I just created an executable bash script that pulls the necessary frameworks out of the app bundle and sends them to the proper place, and then packaged all the necessary game files and everything into a zip, and put it up for download, so that I can just share that with my friends.  Just not very intuitive.  If there's no simple way to do it right now I understand, I just wanted to make sure you were aware of the issue is all!

**Comment by LRFLEW** [comment]
Ok, while resolving the g2.dat problem, I realized that I was doing this kind of wrong. I've now moved the app building code from CMakeLists.txt to build.sh. This removes the issue with g2.dat being build late, and allows config variables to prevent building it (for use in Travis if necessary).

**Comment by janisozaur** [comment]
@pizza2004 That sounds counterintuitive to me. Your argumentation throws away all benefits of having shared libraries and package managers. Alas, as this is very OS X specific and I have no experience with this platform, I'm not going to comment on this bit any further.

**Comment by pizza2004** [comment]
@janisozaur I'm honestly not sure at all what a package manager is.  Is that like homebrew?  90% of OS X users have no such thing.  It's the same as including a DLL with your program on Windows, it's standard practice unless there's some library you can install, but on OS X, it's very uncommon to install libraries into the system itself, and if you want to run a program you usually have to assume that a person hasn't installed any new libraries onto their system except the stock ones.

I definitely agree that it would make more sense to just have shared libraries, but it kind of flies in the face of the user experience of OS X, namely, that the system/applications always handle the behind the scenes stuff for you.  You just download an app and it works without every having to think about why or how or do any extra steps.  It's a sacrifice made to be the easiest experience for the largest number of users.

**Comment by Gymnasiast** [comment]
90% or more of the OS X users won't compile it themselves but use a ready-made build. This whole discussion is about the libraries needed _at compile-time_.
It's getting old that you keep commenting on stuff you don't understand.

**Comment by kkirby** [comment]
@Gymnasiast, the executable isn't statically linked to these libraries. They are required at runtime:

```
Kyles-Home-Macbook:OpenRCT2 kylekirby$ brew uninstall SDL2
Uninstalling /usr/local/Cellar/sdl2/2.0.3... (75 files, 5.8M)
Kyles-Home-Macbook:OpenRCT2 kylekirby$ ./openrct2
dyld: Library not loaded: /usr/local/lib/libSDL2-2.0.0.dylib
  Referenced from: /Users/kylekirby/Downloads/OpenRCT2/./openrct2
  Reason: image not found
Trace/BPT trap: 5
```

**Comment by IntelOrca** [comment]
I think these libraries should be statically linked or bundled with the binary.

**Comment by Gymnasiast** [comment]
Sure, but I was talking about the libraries needed at _compile-time_, for which package manager like Brew are intended. Libraries needed at run-time should indeed by included or statically linked.

**Comment by kkirby** [comment]
```
Apple does not support statically linked binaries on Mac OS X.
```

https://developer.apple.com/library/mac/qa/qa1118/_index.html

**Comment by LinusU** [comment]
As @pizza2004 said, the standard practice is to also include a `Frameworks` folder in the `.app` bundle where the `.dylib` files is copied. The files from `Frameworks` will be loaded even if an newer version is available on the system.

Check the linked page, especially under "Anatomy of an OS X Application Bundle" and "Table 2-5".

https://developer.apple.com/library/mac/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html

**Comment by janisozaur** [comment]
Question: if we use only i386 versions and I believe what brew installs is both amd64 and i386, can the amd64 be stripped away so we provide only the part that's actually needed?

**Comment by LinusU** [comment]
Should be possible:

```sh
ditto --arch i386 input.dylib OpenRCT2.app/Frameworks/output.dylib
```

**Comment by janisozaur** [comment]
what's the difference in size?

**Comment by janisozaur** [comment]
mingw build is broken, it tries to create osx bundle

**Comment by LRFLEW** [comment]
Ok, I'm really beginning to second guess myself on this. @IntelOrca can we discuss this (and additionally the Windows build process) some point tomorrow?

**Comment by IntelOrca** [comment]
@LRFLEW OK - discuss what exactly?

**Comment by LRFLEW** [comment]
Ok, I'm closing this now because this needs to be completely reworked.

**Comment by pizza2004** [comment]
Can I ask what about it needs to be reworked?  It worked well enough for me.  Although, it would probably be best practice if we created an Xcode project to handle all this stuff.

**Comment by LRFLEW** [comment]
@pizza2004 The data folder was a hold-over from the code I borrowed from kkirby. It was going to be fixed later. The plan right now is to setup a proper Xcode project, but it will take a little bit of time to setup, and we are currently working on how the dependencies will work.

**Comment by pizza2004** [comment]
Ah, okay, that works for me!  I prefer that method more anyway.

**Pull request closed without merging**
