### PR TITLE
Verify compilability of headers on Travis

### LINKED ISSUE #7289: Includes should carry their dependencies
**OS:** all

As part of ongoing work to improve our headers, I need to make them all carry their dependencies: if possible, forward-declare used symbols or include the appropriate header. This won't degrade build process, as the headers would still need to be included in actual translation unit.

### PR DESCRIPTION
**Pull request by janisozaur**
Follow up to #7368, fixes #7289

### CODE REVIEW

**Comment by janisozaur** [comment]
@vector-of-bool any chance of you taking a look at this PR?

**Comment by vector-of-bool** [comment]
I'll recommend this process:

1. Write to a file with the same name with a trailing underscore: `foo.cpp_`
2. Use `add_custom_command` to create a rule that copies the temporary to the real file using `copy_if_different`. [Like this](https://github.com/vector-of-bool/cmrc/blob/47aac39a79c67a4e6e7db054234c68ce8544cd9d/CMakeRC.cmake#L185). This will prevent the file from being touched after running a CMake configure. Otherwise, each time CMake runs the rules will be marked out-of-date.
3. Create a dummy static library called `header-check` or something like that. Instead of manually writing a Ninja file that does a compile of the generated file, call `target_sources(header-check PRIVATE foo.cpp)`. Even better: Add the dummy sources to their associated target via `target_sources`. This will assure they get the correct compilation flags. Since they don't export any symbols, their link will be a no-op.

On an unrelated note, have you looked at using cache-initializer files instead of the long list of cache arguments for the CMake command?

**Comment by janisozaur** [comment]
That sounds like the process could be extended to other build systems, not just ninja? That certainly looks useful. I'll see what I can come up with.

**Comment by janisozaur** [comment]
I tried a yet another approach now: tricking cmake into compiling the actual headers as if they were source files.

This is the simplest approach I have found so far that addresses the issue at hand, some notes:
* `#pragma once` gets flagged: `src/openrct2/EditorObjectSelectionSession.h:17:9: error: #pragma once in main file`
    - clang can disable it with `-Wno-pragma-once-outside-header`, GCC can't do that
* unused variables are flagged and the warning would have to be lifted
```
src/openrct2/actions/GameAction.h:57:22: error: unused variable 'ALLOW_WHILE_PAUSED' [-Werror,-Wunused-const-variable]
    constexpr uint16 ALLOW_WHILE_PAUSED = 1 << 0;
```
* it's quite simple and introduces little changes to our `CMakeLists.txt`. The whole diff is:
```diff
diff --git a/src/openrct2/CMakeLists.txt b/src/openrct2/CMakeLists.txt
index 934c0d743..531d88a63 100644
--- a/src/openrct2/CMakeLists.txt
+++ b/src/openrct2/CMakeLists.txt
@@ -59,8 +59,8 @@ if (NOT DISABLE_TTF)
 endif ()
 
 # Sources
-file(GLOB_RECURSE OPENRCT2_CORE_SOURCES "${CMAKE_CURRENT_LIST_DIR}/*.cpp"
-                                        "${CMAKE_CURRENT_LIST_DIR}/*.h"
+file(GLOB_RECURSE OPENRCT2_CORE_SOURCES "${CMAKE_CURRENT_LIST_DIR}/*.cpp")
+file(GLOB_RECURSE OPENRCT2_CORE_HEADERS "${CMAKE_CURRENT_LIST_DIR}/*.h"
                                         "${CMAKE_CURRENT_LIST_DIR}/*.hpp")
 if (APPLE)
     file(GLOB_RECURSE OPENRCT2_CORE_MM_SOURCES "${CMAKE_CURRENT_LIST_DIR}/*.mm")
@@ -71,6 +71,10 @@ endif ()
 set(PROJECT libopenrct2)
 project(${PROJECT} CXX)
 add_library(${PROJECT} ${OPENRCT2_CORE_SOURCES} ${OPENRCT2_CORE_MM_SOURCES} ${RCT2_SECTIONS})
+add_library(${PROJECT}-headers-check ${OPENRCT2_CORE_HEADERS})
+set_target_properties(${PROJECT}-headers-check PROPERTIES LINKER_LANGUAGE CXX)
+set_source_files_properties(${OPENRCT2_CORE_HEADERS} PROPERTIES LANGUAGE CXX)
+add_definitions("-x c++ -Wno-pragma-once-outside-header -Wno-unused-const-variable")
 set_target_properties(${PROJECT} PROPERTIES PREFIX "")
 
 # Libraries
@@ -147,19 +151,27 @@ endif()
 
 # Includes
 target_include_directories(${PROJECT} SYSTEM PRIVATE ${LIBZIP_INCLUDE_DIRS})
+target_include_directories(${PROJECT}-headers-check SYSTEM PRIVATE ${LIBZIP_INCLUDE_DIRS})
 target_include_directories(${PROJECT} PUBLIC ${JANSSON_INCLUDE_DIRS})
+target_include_directories(${PROJECT}-headers-check PUBLIC ${JANSSON_INCLUDE_DIRS})
 target_include_directories(${PROJECT} PRIVATE ${PNG_INCLUDE_DIRS}
                                               ${ZLIB_INCLUDE_DIRS})
+target_include_directories(${PROJECT}-headers-check PRIVATE ${PNG_INCLUDE_DIRS}
+                                              ${ZLIB_INCLUDE_DIRS})
 if (NOT DISABLE_HTTP_TWITCH OR NOT DISABLE_NETWORK)
     target_include_directories(${PROJECT} PRIVATE ${LIBCURL_INCLUDE_DIRS})
+    target_include_directories(${PROJECT}-headers-check PRIVATE ${LIBCURL_INCLUDE_DIRS})
 endif ()
 if (NOT DISABLE_NETWORK)
     target_include_directories(${PROJECT} PUBLIC ${OPENSSL_INCLUDE_DIR})
+    target_include_directories(${PROJECT}-headers-check PUBLIC ${OPENSSL_INCLUDE_DIR})
 endif ()
 if (NOT DISABLE_TTF)
     target_include_directories(${PROJECT} PRIVATE ${FREETYPE_INCLUDE_DIRS})
+    target_include_directories(${PROJECT}-headers-check PRIVATE ${FREETYPE_INCLUDE_DIRS})
     if (UNIX AND NOT APPLE)
         target_include_directories(${PROJECT} PRIVATE ${FONTCONFIG_INCLUDE_DIRS})
+        target_include_directories(${PROJECT}-headers-check PRIVATE ${FONTCONFIG_INCLUDE_DIRS})
     endif ()
 endif ()
```

**Comment by janisozaur** [comment]
I think I will use approach I described in the comment above. It adds another target that I won't include in `all` and only explicitly enable in clang builds. This will provide enough verification for inclusion of forward declarations and headers.

**Comment by janisozaur** [comment]
Obsoleted by https://github.com/OpenRCT2/OpenRCT2/pull/7625

**Pull request closed without merging**
