### PR TITLE
Finance payment api hook

### PR DESCRIPTION
**Pull request by DanStevens**
As this is my first contribution to the project, I've created this as draft - I'd welcome some feedback.

I've implemented a new API hook named "park.financial.payment". It allows plugin authors to:

 1. Run code when a financial transaction occurs (both income and outgoings), see the amount and the expenditure type.
 2. Change the amount.

I discuss my design more here: https://github.com/OpenRCT2/OpenRCT2/discussions/17523

### CODE REVIEW

**Review by duncanspumpkin — CHANGES_REQUESTED** [review]
There are a couple of issues with this. It's too late in the process to fail a payment, it's going to be triggered a lot suggesting it may be a performance issues, it's not providing much information about what is causing the payment so unlikely to be too useful. I think it would be better to approach this a different way.

**Comment by IntelOrca** [comment]
`finance_check_money_required` is the function that checks whether you can afford something, so that would need to be hooked as well. This happens in query game action rather than execute.

**Comment by DanStevens** [comment]
> It's too late in the process to fail a payment

Not sure if I understand. What do you mean by failing a payment? Do you mean if the plugin adjusts the amount to a value that exceeds the current cash balance? That would only be an potential issue with "ride_construction", "land_purchase" and "landscaping" expense types.

**Comment by duncanspumpkin** [comment]
> > It's too late in the process to fail a payment
> 
> Not sure if I understand. What do you mean by failing a payment? Do you mean if the plugin adjusts the amount to a value that exceeds the current cash balance? That would only be an potential issue with "ride_construction", "land_purchase" and "landscaping" expense types.

Yes that is what I mean.

**Comment by Gymnasiast** [comment]
Since this hasn’t been updated for two months and there are problems with the design, I’m closing this. If you want to try again, it’s perhaps best to ask in our Discord and we can work out a better way.

**Pull request closed without merging**
