### PR TITLE
Push travis builds to openrct2.org

### PR DESCRIPTION
**Pull request by janisozaur**
As discussed, this will make travis builds available for download through the new openrct2.org.

The server and API are provided by courtesy of @JarnoVgr.

@LRFLEW suggested OS X builds are better when packaged simply as a zip.

This makes use of Travis' encryption feature, more info here: https://docs.travis-ci.com/user/encryption-keys/

Few things worth pointing out:
* Builds will be available at url similar to http://cdn.limetric.com/games/openrct2/0.0.4/travis-deploy/96a0f584/4/openrct2-linux.tar.gz, where:
  * `0.0.4` is `version` passed
  * `travis-deploy` is the name of branch
  * `96a0f584` is the **8**-character hash short (`git rev-parse --short` defaults to 7 and expands when needed)
  * `4` is the flavour ID, 4 = Linux, 3 = OS X
  * `openrct2-linux.tar.gz` is the file name
* The secret keys are only available to commits on the project (or in other words: pull requests don't have them)
* Linux builds are done with gcc 4.8 in `RelWithDebInfo` (`-O2 -g`) mode

### CODE REVIEW

**Comment by janisozaur** [comment]
Any comments from anyone?

**Comment by LRFLEW** [comment]
Can you update the description to match the new file naming scheme? Also, I'm trying to grab the OS X build from this PR, but I can't seem to get the url right. What am I doing wrong? I have http://cdn.limetric.com/games/openrct2/0.0.4/travis-deploy/60ce32bb/3/openrct2-0.0.4-osx-60ce32bb.zip

**Comment by janisozaur** [comment]
@LRFLEW As mentioned in the PR description, secure variables are not available to pull requests, that includes this one as well, so the builds won't start appearing until this gets merged.

I also updated the description with templates of file names and examples of them filled with information.

**Comment by LRFLEW** [comment]
Is the link I put in my other comment the idea of what the links would look like. It seems that the last commit changed how the links look from the one in the description. 

Either way, as long as this work, I see no problems with this. Is the .org server just waiting on this now?

**Comment by JarnoVgr** [comment]
@LRFLEW Yes. We only need to create a new downloads page and then we're (nearly) good to go to launch the .org website.

**Comment by LRFLEW** [comment]
@JarnoVgr Great to hear. As soon as I see the specs/documentation for the fetching API, I can update my launcher and get an OS X build out there (which is my goal ASAP).

**Comment by JarnoVgr** [comment]
@LRFLEW That'll be ready before the website launches. I will contact you about that shortly!

**Comment by runelaenen** [comment]
@JarnoVgr Can you also let @PFCKrutonium know about that so the new windows launcher can start using that too? :)

**Comment by janisozaur** [comment]
Shall it get merged now then?

**Comment by janisozaur** [comment]
With current `develop`, there are downloads now available:
* http://cdn.limetric.com/games/openrct2/0.0.4/develop/162710d8/4/openrct2-0.0.4-linux-162710d8.tar.gz
* http://cdn.limetric.com/games/openrct2/0.0.4/develop/162710d8/3/openrct2-0.0.4-osx-162710d8.zip

**Pull request merged**
