### PR TITLE
Fix #4237: Some scenery dissapears while zooming out x2 or more

### LINKED ISSUE #4237: Some scenery dissapears while zooming out x2 or more
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 680f7b7

- [ ] Reproducible in RCT2 (vanilla)?: No, I have tested this with vanilla RCT2 and the scenery didn't dissapear when zooming out. 
- [ ] Multiplayer?

**Steps to reproduce:**
1. Start a game with some wheels or flames from the mechanical theme, or just build this scenery (will test it later if it happens with more scenery.) 
2. Now zoom out twice (so, zoom out 2 factors)
3. The wheels and flames dissapear from the map, which didn't happen while zooming out in vanilla RCT2.

**Screenshots / Video:**
Vanilla RCT2:

scr5
scr4
scr3
scr2

OpenRCT2:

six fingers 2016-08-06 18-22-29
six fingers 2016-08-06 18-23-02
six flags 2016-08-06 18-39-08
six flags 2016-08-06 18-39-15

### PR DESCRIPTION
**Pull request by zsilencer**

### CODE REVIEW

**Comment by mrtnptrs** [comment]
It fixes the issue, doesn't result in problems and can be merged in my opinion.

**Comment by zsilencer** [comment]
I tested with original and only the bottom of the fountains render when zoomed out also.  Not sure why the swamp goo isn't appearing, they are working fine on my end.

**Comment by mrtnptrs** [comment]
@zsilencer The swamp goo always gets renderd, even when zoomed out, but when x2 zoomed out, it doesn't animate, where the latest development build does. Sorry, I made some mistakes in that sentence and fixed that already in my latest comment here.

**Comment by zsilencer** [comment]
OK, did you compare it again to Vanilla RCT2?  On my end it is consistent with original now.

**Comment by mrtnptrs** [comment]
Tested it and you're right: how it is now seems to be same as in vanilla RCT2 (will do more testing tomorrow morning, so, don't merge yet!), but wouldn't it be nice to let the game render and animate all scenery while zoomed out? We have much better computers now, so, there should be no performance issues doing this and it looks much better. What do you think @zsilencer ?

**Comment by mrtnptrs** [comment]
@IntelOrca I'm only talking about (animating) scenery, not guests as that would be a big mess indeed. Maybe we could also do something else: let all the scenery animate up to an including x2 zoom instead of up to and including x1 zoom? And that x3 and x4 zoom still has the original RCT2 bahavior (or a variation, just renderd but not animated)? This would generally make the game look nicer while not zoomed out that much in my opinion, but what do you guys think about this?

**Comment by IntelOrca** [comment]
The same problem, animated scenery would just look like flashing pixels.

**Comment by mrtnptrs** [comment]
But it wouldn't look that pixelated on x2 zoom, would it? 

@IntelOrca Not to offend you, but I see you regularly don't understand what I mean with something or only seem to read a part of what I typed and assume the wrong thing.... :) This is not bad, but it starts getting a little bit annoying, as it forces me to explain myself again :) I know this is normal, as you have more to do then reading everything I say, but... you understand what I mean :)

**Pull request merged**
