### PR TITLE
Refactor track and supports colours in PaintSessionCore

### PR DESCRIPTION
**Pull request by spacek531**
Originally split from #20972 because it is 99% find-and-replace.

The second commit touches some of the same code. I wasn't sure if it would be better as the same PR or a different so I threw it in.

### CODE REVIEW

**Review by Gymnasiast — CHANGES_REQUESTED** [review]
I did some digging as to how this field is used:
```C++
ImageId TrackColours[2];
```

The array as a whole is never set or referenced, it’s **always** the individual elements, like so
```C++
session.TrackColours[SCHEME_TRACK]
session.TrackColours[SCHEME_SUPPORTS]
```

Also, the `SCHEME_TRACK` and `SCHEME_SUPPORTS` constants are never referenced anywhere else either.

As such, I’d want to change this field to be just 
```
ImageId TrackColours;
ImageId SupportColours;
```

**Review by Gymnasiast — COMMENTED** [review]
Code looks all right, will need to do some playtesting.

**Review by Gymnasiast — APPROVED** [review]
Tested it. Seems to work correctly, and I love that it diminishes the LoC count by more than 7500 ^^

**Review by tupaschoal — APPROVED** [review]
It's a big diff, but as far as I see, seems that everything is in order.

**Pull request merged**
