### PR TITLE
Implement #17806: Warn user if fallback images used

### PR DESCRIPTION
**Pull request by spacek531**
Warns user on the object debug info, when closing the object selection window after selecting objects, and when opening a park.

openrct2_2022-08-28_17-36-55
openrct2_2022-08-28_21-42-50

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
Seems to work fine.

**Comment by karst** [comment]
Does this error load aswell when loading a park that uses RCT1 sprites?

**Comment by duncanspumpkin** [comment]
> Does this error load aswell when loading a park that uses RCT1 sprites? (#17806)

Yes. I tested the following: sv6 park (no error as expected), sv4 park (error as expected). Things i didn't test was .park with an sv4 object but the way this change has been done I've complete confidence that that would error as expected.

**Comment by ZeeMajora** [comment]
I can confirm that the park loading error shows up in the following situations:
Loading an sc4
Loading an sv4
Loading an old hybrid sv6 that uses rct1 terrain textures
Loading a .park with rct1 objects enabled

Only one i'm missing is a hybrid sc6 as i don't have any at the moment.

**Comment by spacek531** [comment]
I've changed the red text to black text for readability. I'm not 100% happy with the strings so if you have better ideas I'm all for it. 
image

**Comment by spacek531** [comment]
It sounds like the team is ramping up to a 0.4.2 release. Is there any chance this can make it in too?

**Review by Gymnasiast — APPROVED** [review]

**Pull request merged**
