### PR TITLE
Fix viewport clipping issues with the OpenGL renderer

### PR DESCRIPTION
**Pull request by Dennis-Z**
(when zoomed out)

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Is this related to track previews not showing when using the OpenGL backend, too?

**Comment by Dennis-Z** [comment]
No, that's (as far as I know) related to the OGL renderer always rendering to the same framebuffer, while the preview is supposed to be rendered to some separate framebuffer before blitting it onto the main one.

**Comment by Gymnasiast** [comment]
Could you provide a screenshot of what this fixes?

**Comment by Dennis-Z** [comment]
Here you go:

Broken clipping:
image

Fixed viewport clipping:
image

**Comment by IntelOrca** [comment]
Could you update the changelog?

**Pull request merged**
