### PR TITLE
Allow rate input by text box

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Note this isn't finished.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Not finished as in 'Work in progress'?

**Comment by duncanspumpkin** [comment]
Yeah had to run before I finished it. Still need to add the new strings

**Comment by IntelOrca** [comment]
Can you enable the spinners to increment while holding the mouse down... I can't remember how to do it - I think there is some widget flag array you set.

**Comment by gDanix** [comment]
@IntelOrca I think this is done by setting one of the callbacks, which is called every certain number of milliseconds

**Comment by IntelOrca** [comment]
You need to set `hold_down_widgets` on window.

**Comment by duncanspumpkin** [comment]
@IntelOrca okay made those changes to add in the hold down widgets.

**Pull request merged**
