### PR TITLE
Docker32

### PR DESCRIPTION
**Pull request by janisozaur**
This PR refactors build/install scripts to be much more Linux-friendly and easier to maintain.

The first commit is just about the same as https://github.com/OpenRCT2/OpenRCT2/pull/1978 only rebased.

In addition to that, there's a dockerfile targetting 32bit-only builds. It is of use to those who would like to keep on hacking on openrct while doing that from debian-based distributions, as these have problems installing sdl2 in i386 flavour (dev version).
On top of that, it also ensures compatibility with Arch.

This will probably break something on Appveyor, but I wouldn't know how to fix it.

Libraries are now pulled from my dropbox account, https://dl.dropboxusercontent.com/u/1323345/orctlibs.zip. The change I had to apply there is to move jansson headers one level up and I changed all the paths in `*.pc` `pkg-config` files to point to proper directions, so they could be used. See #1978 for more info on that.

Travis should also return a bit faster due to build order rearranged and various fat trimmings, even though new configurations were introduced.

Regarding docker: I've set up an automated build on docker hub which will provide pre-built images for anyone to use. It is based on included file, takes around 40 minutes to build and weighs ~500MB. See https://hub.docker.com/r/janisozaur/openrct2/tags/
The build can be triggered manually or by changing the dockerfile.
Manual bit can be useful in case original image (`nfnty/arch-mini`) gets updated.

### CODE REVIEW

**Comment by PFCKrutonium** [comment]
Having it download from your dropbox is a bad idea - Dropbox has some very strict limitations on downloads. Your dropbox's public links could very easily be suspended.

**Comment by janisozaur** [comment]
Yes, I do realise it's a possible problem, but it's enough for testing, at least. If you can provide a storage space for that, that would be great. Or better yet, change the file that's pulled right now: https://download.openrct2.website/dev/lib/mingw

**Comment by PFCKrutonium** [comment]
It's up to @runelaenen But we can likely host it for you over at openrct.net.

**Comment by janisozaur** [comment]
sha256sums:
```
04b1d7c89a739286218b1d8c79f7ae3ddb8f754f2fd8de024d276ff2f6d50236  orctlibs_vs.zip
0a7b5ea46e9cb4b19000b69690eae0b75929752f7db192c78bd7ffb61d696835  orctlibs.zip
```

**Pull request merged**
