### PR TITLE
Improve chat + background, fixes #3849

### LINKED ISSUE #3849: Background for chat + new line (Length limit before 'next row')
The chat can sometimes be hard to read, especially when you use snow texture, getting a grey background would help a lot (when the chat is open)

Another problem is that there isnt a length limit so you can type all the way to the edge of the screen, would recommend it goes to 'a new line', like Minecraft

rct_drawpixelinfo
_chatRight = 600;

Color: 
// Background
``gfx_fill_rect(dpi, _chatLeft, _chatTop, _chatRight, _chatBottom, 0x2000000 | 50);  # 0x2000000 | 50); ``= Transparent gray

**How it's now:** 
pure text

**My suggestion:** 
examples

### PR DESCRIPTION
**Pull request by Wirlie**
This is a continuation of #3851, thanks @Nubbie, you have given me an idea xP

**Progress (2016-06-22):**
scr33

The background only is displayed if you press the key shortcut "send message" (default: key C).

~~Probably I will to change the background color and the width of the chat, I am not sure if the gray looks good,~~
Any suggestions?

**TODO:**
- [x] Break text into a new line if this exceeds the length limit.
- [x] Theme-able.
- (?) _Option to turn on/off the background (suggested by nubbie)._

**Note:**
This hasn't been finished, any suggestion/idea/help is welcomed.

### CODE REVIEW

**Comment by HaasJona** [comment]
I suggest that the styling should match more the green money and weather boxes. Not necessarily the colour, but the 3d edge style for example.

The colours should generally be lighter I think. Especially the dark borders could look more subtle on you screenshot. As for the background I suggest a white or light blue tint.

**Comment by IntelOrca** [comment]
You could make it theme-able.

**Comment by Nubbie** [comment]
Just glad someone could do it :p 

Have tested it out a little bit and the only things I can say is that it works great but;

- Theme-able :p 
- Specified length (takes up the screen all the way atm)
- Lighter colors
- _Turn on/off option?_

**Comment by Wirlie** [comment]
Hmm, I have seen that themes only accepts `rct_windowclass` as argument, I think that I should make a new window class for the chat box?

I do not know much about the code, but, I will try to do it.

**Comment by IntelOrca** [comment]
@Wirlie you can create a new window class for chat.

**Comment by HaasJona** [comment]
Looks great

**Comment by Wirlie** [comment]
I changed the style a little, I think that looks great.
**The problems:**
- I cannot find a way to break the text and write the remaining text into a new line :|

I used `gfx_clip_string`, but it adds "..." (ellipsis) at the end of the clipped text. I'll investigate a way for to do that.

scr19

**Comment by Nubbie** [comment]
Maybe some dev have a clever way.. if not a character limit with a {NEWLINE} being inserted when it's hit

**Comment by IntelOrca** [comment]
`gfx_draw_string_left_wrapped`

**Comment by Wirlie** [comment]
Thanks @IntelOrca you're the best :cat: 

scr21

Any suggestions?

**Comment by HaasJona** [comment]
Looks very good. We might need to discuss the default colour. I'd vote for either the blue that's used for the player window in the preferences or the green that's used for the weather and money boxes below. Or maybe white. Something that works good with the other colours. Not a huge fan of the pink. 😉

**Comment by Wirlie** [comment]
At this moment the gray is the default color, however, the blue is a good choice. I like it.
scr22

**Comment by Phyxion** [comment]
Gray looks best as it retains most of the colors of the background.

**Comment by IntelOrca** [comment]
Some things like the buttons on the title sequence use two transparent colours.

**Comment by HaasJona** [comment]
Yeah, I agree, the blue not transparent enough. The grey is probably better. Sorry about that suggestion. Should have tried it first.

**Comment by Nubbie** [comment]
Maybe one of these gray colors? 50 are the most 'transparent' with just a nudge visibility, might fit so it doesn't get distracting with the window ;o

awfa

**Comment by Wirlie** [comment]
Okay, this works, but I'm not sure if I've done this well.

**Comment by pizza2004** [comment]
If it were possible to allow scrolling through older messages in this interface now it would be a good way to deal with most of #3023.  I had an open pull request that got closed for some reason in which I was trying to create a new chat window, but I wasn't having a ton of luck doing so, and it was closed for some reason and wouldn't let me reopen it (some issue with the git branch), but with these changes I don't think a separate window makes as much sense.  I guess the guy kind of wanted a way to just keep chat open and continuously type messages into it though.

**Comment by Wirlie** [comment]
@pizza2004 Thanks for your suggestion. I'm trying to make a window instead of a background below the text. This is my current progress but I'm not sure if I can to do this:
scr35

Pros:
- Resizable.
- Dragabble.
- Scrollbars to allow scrolling through older messages.
Cons:
- I cannot find a way to hide the background of a widget.

**Comment by pizza2004** [comment]
I guess you'd probably have to reprogram the widget to allow that behavior.

**Comment by Wirlie** [comment]
I've made a window instead of a background.
I think that this is much better compared to my previous chat :)

**Progress:**
_Before sending message_
scr37
_After_
scr38
_Resizable window + draggable_
scr39
_Multiple Lines_
scr40
scr41
_I've added a scrollbar to allow scrolling through the oldest messages (max 100 messages)._
scr42

Looks good?

**Comment by IntelOrca** [comment]
Why have you inverted the direction of the chat?

**Comment by pizza2004** [comment]
I know it wouldn't look perfect because of the drag to size window thing, but you could just make the text box end where the scroll bar begins on the upper one, which would look close enough to be okay, and not add anymore space to the bottom of the window.  Beyond that, the only other things I would add would be the word chat in the title bar, and then eventually when we add the ability to pin windows, a pin icon that makes it stay when you send messages and keep the cursor in the box so you don't have to click it each time to send multiple messages.  Also, any specific reason for just 100 messages?

**Comment by Wirlie** [comment]
Hum... I'm not able to make a separate window for the chat (I do not know much about the code) 
I give up :|

I will keep the background instead of a separate window. 
Someone can review and test my code? I need help, I'm not sure if the code is fine. (probably not).

**Comment by pizza2004** [comment]
Why did you delete the comment?  It looks like it was working properly to me, just with some needed changes.  I'm sure if you'd pushed up the code we could have helped you figure out what needed to be done to make the last few changes.

**Comment by Wirlie** [comment]
Hey guys, sorry. Tomorrow I am going to travel to another city and I will not be able to continue with this. If anyone can continue this these are my last changes. 

I hadn't planned this, sorry :(
Thanks for your help, again I am sorry for not being able to finish this.

**Comment by mrtnptrs** [comment]
@Wirlie It's ok, you did amazing work with this :)

**Pull request closed without merging**
