### PR TITLE
Fix wrong syntax of std::array in Window.cpp

### PR DESCRIPTION
**Pull request by gguedesaz**
Fixed a compilation error on Window.cpp caused by incorrect std::array syntax.

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
This is already part of #12749.

Out of curiosity, on what platform are you seeing compilation errors?

**Comment by gguedesaz** [comment]
@AaronVanGeffen I'm seeing this on macOS High Sierra 10.13.6, using XCode 10.0. Should I close this PR then? I'm actually migrating to cmake, so it won't hurt me that much.

**Comment by AaronVanGeffen** [comment]
@gguedesaz Yeah, #12749 is addressing the same thing for the same reason.

Curious, does this change make the project fully compile for you on macOS 10.13? We're seeing some problems on our macOS CI (10.15) when we try to target 10.13 directly, because of code that's using C++17 `std::optional`. #12749 is making it work through a workaround, though.

**Comment by gguedesaz** [comment]
I don't think I have the capability of fully answering your question.

It was the first time I tried to compile the project and it failed. I took a quick look and made this "hotfix" so I could just start playing around the code base.

It fully compiled with this change ("Build Succeeded" on XCode).
Either way, I'm dropping this PR because of #12749 

Thanks for your inputs!

**Pull request closed without merging**
