### PR TITLE
Refactor probability

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Still playing about with this. Not too sure on my approach.

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
How about making a `constexpr` function that returns the right probability using a switch case instead? The percentage (?) could just be an argument, which I believe it would improve readability considerably.

**Comment by IntelOrca** [comment]
We can just use floating point literals to get the right hex probabilities.
E.g.

```
constexpr unsigned short probability(double f) {
    return 65535 * (0.142 / 100);
}

unsigned short test() {
    return probability(0.142);
}
```

test() will return compile time constant 93.

**Comment by duncanspumpkin** [comment]
```
GetProbability16(0.142));
GetProbability16(0.182));
GetProbability16(0.2));
GetProbability16(0.333));
GetProbability16(0.5));
GetProbability16(1.0));
GetProbability16(1.4283));
GetProbability16(2.0));
GetProbability16(2.221714));
GetProbability16(2.5));
GetProbability16(3.333));
GetProbability16(3.516));
GetProbability16(3.7034));
GetProbability16(4.0));
GetProbability16(4.166));
GetProbability16(4.3473));
GetProbability16(5.0));
GetProbability16(6.2501));
GetProbability16(6.667));
GetProbability16(8.333));
GetProbability16(10.0));
GetProbability16(11.1101));
GetProbability16(12.5002));
GetProbability16(14.2855));
GetProbability16(20.0));
GetProbability16(16.666));
GetProbability16(25.0004));
GetProbability16(33.333333333333333));
GetProbability16(50.001));
GetProbability16(62.501));
```
So the above numbers will give the same values. Some of them are a bit annoying.

**Comment by AaronVanGeffen** [comment]
Instead of `33.333333333333333` you could just write `100.0 / 3.0`, right?

**Comment by duncanspumpkin** [comment]
Yeah you could but is it easier to read.

**Comment by AaronVanGeffen** [comment]
Haha, I was trying to argue the opposite. Personal preference, I guess. :)

**Comment by Gymnasiast** [comment]
I agree your initial approach in this PR isn't the best way to refactor this (it gets harder to read IMO). I'm interested in how @IntelOrca 's approach will work out.

By the way, I don't think probability necessarily _needs_ refactoring, though I have nothing against it either (provided the code stays readable, of course).

**Comment by AaronVanGeffen** [comment]
The constants are a little awkward. Is the plan to drop them altogether in favour of the constexpr `GetProbability16`? I believe doing so would alleviate the issues raised w.r.t. readability.

**Comment by duncanspumpkin** [comment]
Yeah i was thinking of reverting basically all my changes except get probability 16 is used to calculate the probability

**Comment by Gymnasiast** [comment]
If you get round to that, it's probably better to create a new PR, as this one has been untouched for 4 months now.

**Pull request closed without merging**
