### PR TITLE
Do not turn off chain when building downhill if chain cheat is on

### PR DESCRIPTION
**Pull request by spacek531**

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
Could you provide some info as to why you are making this change. From first look at this your just expanding the code duplicating common items.

**Comment by spacek531** [comment]
I don't like turning on the chain lift when it turns itself off automatically when building forward

**Comment by spacek531** [comment]
does anyone know why going backwards with the cheat enabled explicitly does not pick up the chain state?

https://github.com/OpenRCT2/OpenRCT2/blob/6c3a417af35572ad4fcbf77ffd43bb99192f3824/src/openrct2/ride/RideConstruction.cpp#L732-L735

**Review by tupaschoal — COMMENTED** [review]
@spacek531 it seems like this PR doesn't really match what it was opened as (at least in terms of title).

Can you update the title? Is there any open issue you're trying to fix?

Also is the reason for it still being in draft the question you left there? (I don't know the answer btw)

**Comment by spacek531** [comment]
It was pointed out I have a lot of open PR about 2 months ago, so to try and hurry things along I marked the ones I wanted to merge first as ready and the other ones as draft.

**Comment by tupaschoal** [comment]
Ah, I see, thanks for explaining.

Yeah, we plan on getting there.

**Review by Gymnasiast — APPROVED** [review]
~~Code looks good, please rebase.~~

**Pull request merged**
