### PR TITLE
Fix original ride ratings compilation

### PR DESCRIPTION
**Pull request by janisozaur**
Fixes a regression from #22220

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
I'd rather we just delete them.

**Review by Gymnasiast — APPROVED** [review]
Requires a changelog entry.

**Comment by Gymnasiast** [comment]
> I'd rather we just delete them.

I can imagine you saying that after the misfortune of dealing with that user, but I don’t think there is any need, really.

**Review by Gymnasiast — APPROVED** [review]

**Comment by romantyke** [comment]
> > I'd rather we just delete them.
> 
> I can imagine you saying that after the misfortune of dealing with that user, but I don’t think there is any need, really.

Are you talking about me?

**Pull request merged**
