### PR TITLE
Fix plugin text property

### PR DESCRIPTION
**Pull request by duncanspumpkin**
@Sadret could you confirm this works as expected.

### CODE REVIEW

**Comment by Sadret** [comment]
Seems to work.

**Review by Sadret — APPROVED** [review]

**Review by tupaschoal — COMMENTED** [review]
I guess this needs a changelog update, doesn't it @duncanspumpkin ?

**Comment by duncanspumpkin** [comment]
> I guess this needs a changelog update, doesn't it @duncanspumpkin ?

Well technically it's just making the plugins work as expected. There's no real change to plugin authors or to plugin capabilities.

**Comment by tupaschoal** [comment]
I mean, we put bug fixes on changelogs, so even if plugin authors don't need to change, they might want to know about a behaviour change and implement something new or remove workarounds?

**Comment by Sadret** [comment]
It's only removing non-functional behaviour, as it is removing the "text" property of widgets that should not have it and cannot make use of it.

**Comment by duncanspumpkin** [comment]
@tupaschoal as sadret said I'm not sure how i can word a changelog entry for something that didn't do anything before and doesn't do anything now. The widgets where it used to have a text property but doesn't now are widgets where the text property didn't get used. Its a bit of an odd one tbh but changelog entry will just be hard to ever explain.

**Review by tupaschoal — APPROVED** [review]
Ok

**Pull request merged**
