### PR TITLE
Initial prototype of A* for the heuristic search.

### PR DESCRIPTION
**Pull request by zaxcav**
First signs of life from the A* heuristic search I've been working on.

The A* code can either be enabled for all peeps (with significant performance degradation in parks with lots of peeps) or only for selected peeps.

In Peep.cpp the variable gAStarEnableAll (shortly after the #includes at the top of the file) controls this.
The A* code is currently enabled for all peeps be default.

When the A* code is enabled for only selected peeps, peeps are selected as follows:
- guests use A* when they are being tracked;
- mechanics use A* when they are named "Mechanic Star".

The A* code is substantially simpler than the existing heuristic search despite implementing similar specific handling of overlaid paths (zero clearance) to cater for really creative builders.

I've done rudimentary testing using save games for all of the path finding issues I've fixed over the last months, and the A* code works at least as well as the existing heuristic and lots better where the wide paths are causing "unnatural" behavior in the existing heuristic.

The various A* lists (open, closed,etc) are currently a hack with O(n) performance for search operations, so replacing these is absolutely necessary before this can even be remotely considered for merging.

Next steps:
- ~~rebase to the current development branch~~ done
- refactor/clean up the current A* logic
- implement a more efficient data structure for the A* lists
- start experimenting with fun & interesting stuff like using transport rides, letting the search leave paths (no more catastrophic path finding failures from disconnected ride entrances/exits, no more need for separate "surface finding" vs "path finding" vs all other "* finding")
- tuning: appropriate search limits?
- optimisation, incl. save state.

### CODE REVIEW

**Comment by mrtnptrs** [comment]
Ok, I tested this by tracking some guests and speed up the game: it seems to work fine. But could you maybe enable this new pathfinding, A*, for all guests and staff? Then I could do more elaborate testing for you to check for any problems with this new pathfinding method. :)

**Comment by zaxcav** [comment]
@mrtnptrs I'll get a suitable commit to enable A* for all peeps in the next 24hrs.
I turned it on here and immediately hit an assert in the A* code. I've sorted the problem out now (a bug in assembling the final route from the search data of all things), but I still need to remove the extra debugging I added to help sort out what was going on. I'm too tired to do it now, so it will have to wait until tomorrow.
I can however give an initial indication of the performance of the current prototype. As expected, the use of unoptimised data structures has a heavy toll.  In a sample park (mid-sized: around 3750 guests) with the old AI I was getting 33fps. With A* enabled this dropped to 4fps. Certainly still usable for test purposes, but not suitable for playing.

**Comment by mrtnptrs** [comment]
@zaxcav I'm deeply dissapointed that you don't want to do that for me when you are tired, hahaha :P You can sleep when you're dead :P 

But on a more serious note: I have a pretty good computer, so I should get far more then 4 FPS. So, that should make it more testable (if that word even exists XD) but indeed not very playable. But of course that isn't the point of this PR; it is to test a new path finding system. So, take your time to make those changes and when you make a new commit, I will test again :) By the way, my compliments on your excellent work on the old path finding and the impressive work you did with this new approach.

**Comment by zaxcav** [comment]
@mrtnptrs Here's an update with A* enabled for all peeps by default.
(I've updated the PR details to describe how to toggle between all peeps vs selected peeps)
I use a fairly old laptop for development, so I probably represent a worst case user with respect to performance. I am curious how much performance degrades on a better computer with this enabled for all peeps.

I see peeps just went C++, so I'll need to do another rebase... but not today.

**Comment by mrtnptrs** [comment]
@zaxcav Ok, that is nice. But this indeed needs a rebase as it failed to build a working version for me, so I can't test this at the moment (as I'm not able to build OpenRCT2 myself.) So, I will see when you have fixed this and then we can continue testing this :) I will report what the performance is on my computer then.

**Comment by zaxcav** [comment]
@mrtnptrs The build is working again.
I let it run the old GroupPark4 savegame I used in my initial performance test without any further user actions.
After 10 months guests increased from 3700 to 4900 and park rating is pretty solid, so seems like path finding isn't causing any obvious problems.
Have a play with it and see what you find.

**Comment by mrtnptrs** [comment]
Goo work! I will test this in the following days (very much work to do regarding my university study at the moment, I'm now in a lecture actually XD)

**Comment by mrtnptrs** [comment]
Lol, are you sure it has been turned on for all peeps? Park with 4000+ guests: 70-170 FPS with software renderer :)

**Comment by Gymnasiast** [comment]
@mrtnptrs Do you have any good comparison parks? As in, a park that will have bad pathfinding in `develop`, but good pathfinding in this branch?

**Comment by zaxcav** [comment]
@mrtnptrs  I always test with wide paths rendered visibly.
The existing AI won't cross over wide paths (except for mechanics with patrol zones in special circumstances). The A* ignores wide paths.
I could patch the path rending in the PR to make it easier to test.

**Comment by mrtnptrs** [comment]
@Gymnasiast short answer: nope, not that I know of. 

@zaxcav but is it true that A* does not negatively affect performance anymore? 

Would indeed be nice of you to make it easier to test :)

**Comment by Gymnasiast** [comment]
I have put out a call on NE for parks with broken pathfinding. Let's see what this PR changes. :)

**Comment by zaxcav** [comment]
@mrtnptrs Joke of the day: PassMark of your CPU is 11191.  PassMark of my CPU is 1274.  The joke is on me!

What parks are you testing? The specific park I used was the OpenRCT Group Park v4.59 (one of many test parks I have lying around). So you could grab that out of the forums to do a direct comparison.

The heuristic search is only called to choose a direction when the peep is at a junction in the path. The existing search uses the wide path flags to reduce wide paths to 1 tile wide paths to reduce the number of junctions (through this is more because it's hopeless at handling wide paths, not for performance). The A* heuristic is called on every junction and the wide path flags are ignored when doing this.
So parks that use lots of wide paths will see the greatest performance degradation with this prototype, while parks with only 1 tile wide paths will see no degradation at all.

In any case, to make this obvious I can push the few changes that visibly show which paths have the wide flag set.

I have not yet started optimising the data structures for the search which should yield a significant performance boost.

**Comment by zaxcav** [comment]
@Gymnasiast Nice call.

**Comment by zaxcav** [comment]
@mrtnptrs Build with wide path flags visually rendered is there for you to play with
Key points: the heuristic search is only called for peeps heading somewhere specific. e.g. guests heading to a ride or leaving the park or mechanics heading to a ride. With the existing heuristic search these peeps do not cross wide path flags (although there are some exceptions for mechanics with patrol zones to prevent the wide flags from trapping them in only part of their patrol zone).  With the A* search enabled these peeps will cross wide path flags (when it gets them to their destination quicker).  So the easiest ways to tell whether the A* is enabled and working are:
1. Find a peep heading somewhere and follow them to see if they walk over the wide paths.
2. Watch any place with wide paths and check whether any peeps walking over the wide paths are heading somewhere specific.

**Comment by Gymnasiast** [comment]
This park behaves badly with the OpenRCT2 pathfinding: https://www.nedesigns.com/park/569/belmont-shores/

However, it also behaves badly with this A* implementation.

Try following guests walking under the Giant Dipper that want to ride it. They will work in circles.

**Comment by zaxcav** [comment]
@Gymnasiast Thanks for that park.
Ok, the reason both path finding algorithms fail is the ride uses a disconnected entrance and the ride entrance data reflects the original entrance (which is still actually there, at height 0), rather than reflecting the location of the disconnected entrance.
This is instant failure for the heuristic search, since the search goal is set from the "invalid" ride entrance data (see Peep.cpp lines 12286-12314).

The ride entrance data needs to be updated to reflect the position of the disconnected entrance in order for any path finding to work.

Peeps at the ride entrance/queue itself can choose to go on the ride and join the queue. However, until the ride entrance data is updated, peeps elsewhere in the park who deciding to go on the ride will not be able to pathfind their way to the entrance/queue. They will wander "aimlessly" until they give up.

I believe the current method described for disconnecting a ride entrance in the OpenRCT2 Forums (https://openrct2.org/forums/topic/2371-disconnected-entrances-the-quick-and-easy-way/) will produce a similarly "disabled" ride entrance.  Pity.  I'll add an appropriate comment to that forum topic.

I wonder this is also the reason placing paths with the normal path tool doesn't work with disconnected entrances? This might be worth investigating to improve the Tile Inspector...

**Comment by mrtnptrs** [comment]
@zaxcav I have very much to do now, so I will test this in the weekend, more time for you to optimize things :P

**Comment by Gymnasiast** [comment]
@zaxcav I'm going to investigate. Perhaps we can auto-update the entrance coordinates on load?

**Comment by zaxcav** [comment]
@Gymnasiast Auto-update would work in the case where there is only one entrance. In the case of Belmont Shores, the original entrance is still there though and would need to be deleted first for this to work. Not a huge issue.

I was thinking about taking a different approach and adding some enhancements to the Tile Inspector for entrances in general ... since there are related issues for park entrances too. My thoughts so far in this direction are:
1. Deleting an entrance removes its location from the appropriate game data (ride entrance data or park entrance data)
2. Inspecting an entrance shows additional information in the "Entrance Details" frame: an indication of whether this location is in the appropriate game data, and a button to save this location in the appropriate data.

This is getting a bit off topic for this PR though.

**Comment by duncanspumpkin** [comment]
This is all well and good but it's not how @intelorca was envisioning for the ai. The plan was to build a pathing map that is updated as you create more rides and paths. This would save on all the map element working out how it's connected. Also i was planning on splitting the peep file up so that path finding is a separate file as peep.c is huge.

**Comment by zaxcav** [comment]
@duncanspumpkin No problem.

I started this out of personal interest because it's not actually a very big step from the existing algorithm and offers many benefits from greatly simplified code to improved peep behaviour.
I offer it to the project as a possible short term stepping stone until the team can realize their long term goals for the path finding.
I've got a few small points that I want to wrap up in order to meet my original goals for this. After that it's either over to the project or I'll ditch it.
If it's wanted, then great.  If not .. well I've had fun doing it so I'm happy.
If it isn't wanted though, it might be better to get rid of this PR.

I also agree with splitting the path finding into a separate file.

**Comment by Gymnasiast** [comment]
@duncanspumpkin @janisozaur With our path finding being worse than RCT2's in some cases, I think we should not be dismissing this.

**Comment by zaxcav** [comment]
Re-reading my last message the line I wrote about "getting rid of this PR" did not come out how I meant it.
It sounds like I'm pressing for a decision, which is not the case. I was more concerned with this PR creating a false public expectation that a better AI is in the works. This is only a prototype, far from merge ready code.  There's plenty of time to see what it does, how it performs and whether it's wanted or not.

**Comment by IntelOrca** [comment]
OpenTTD went though at least 2 or 3 pathfinding algorithms, I think you can still switch between them all. So this is not a problem. What should be done though is making an interface for it so that you can switch between different pathfinding strategies including the original. As @duncanspumpkin said, you would have peep.c contain just interface code and then the original and A* code in new separate source files.

**Comment by pizza2004** [comment]
I think someone should probably make an issue for the stuff about entrances.

**Comment by Gymnasiast** [comment]
@pizza2004 It says 'Owner', or at least it does now. But please stay on-topic.

**Comment by Gymnasiast** [comment]
In the meantime, I have added code to update disconnected entrance and exit locations upon import. This even works for Belmont Shores, since it will take the entrance with the highest 'Z' coordinate if it encounters two. This should fix the path finding for cases like this.

**Comment by IntelOrca** [comment]
@zaxcav This looks like a good start on a more sophisticated path finding algorithm, however we are currently trying to close all our PRs so we can perform a code base re-format which will most likely cause all PRs to have nasty conflicts.

We welcome you to continue working on this if you have time. We recommend abstracting the peep AI in such a way that the game can switch between your new AI logic and the original logic. This should be done with interfaces so that the switch can be done at runtime rather than #if #else or even conventional if else blocks. That way your new code is isolated in a new source file and it is then much easier to integrate without fear of high code maintenance. Feel free to talk to us in gitter as I do have some of my own ideas for how path finding could be improved.

**Comment by zaxcav** [comment]
@IntelOrca  Completely in order.
I agree with where the project wants to go with runtime switchable AI.
While I still have plans to work further on this I haven't touched it in months and can't say when that will change (I'm coding 100% at work since around the time I submitted this PR, which doesn't leave much motivation for coding in my free time).

**Pull request closed without merging**
