### PR TITLE
Cheat for disconnected entrances

### PR DESCRIPTION
**Pull request by spacek531**
The unintended consequence is that ride entrances can live longer than their associated station platforms. Because ValidateStations is called a bunch of times per frame, and not all of them have non-null stationIndex Start locations, it's not possible to use them to determine if an entrance should be disconnected. This is fine though, because the cheat warns about instability when you activate it.

### CODE REVIEW

**Comment by spacek531** [comment]
As a builder, when I have disconnected entrances, even as simple as a rotated entrance, entering build mode removes the entrances, which require replacement. If the entrances were not removed when the ride is edited, a lot of time could be saved.

https://user-images.githubusercontent.com/3454156/154032443-4bf8104c-dfff-4497-8e95-3e3d8fab8363.mp4

**Comment by duncanspumpkin** [comment]
This is a bad idea it's encouraging putting the game into an invalid state.

**Comment by spacek531** [comment]
What kind of invalid state?

**Comment by Broxzier** [comment]
Related issue: https://github.com/OpenRCT2/OpenRCT2/issues/7317

I don't think this should be a cheat. Entrances that have been rotated should stay by default. It only makes sense to remove entrances when you remove the station piece that it's connected to, or when an entire station is removed.

**Comment by Gymnasiast** [comment]
Closing due to negative feedback from other team members, and this lying dormant for half a year.

I think we would accept a PR that just fixes the game autoremoving rotated entrances/exits.

**Pull request closed without merging**
