### PR TITLE
Make PRs fail when submitted for master branch

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by janisozaur** [comment]
tested in https://github.com/OpenRCT2/OpenRCT2/pull/5567

**Comment by PFCKrutonium** [comment]
Perhaps add a check to see if it is done by IntelOrca so that it won't fail when he merges into it for a release?

**Comment by Gymnasiast** [comment]
@PFCKrutonium That's done directly and not via pull request, so that shouldn't cause problems.

**Comment by janisozaur** [comment]
@PFCKrutonium the check is only done for _pull requests_, we never do them to `master`, we push directly there.

**Pull request merged**
