### PR TITLE
Add optional screenshot argument to set weather

### PR DESCRIPTION
**Pull request by Broxzier**
This does not change the weather of the saved game, it only sets it for the screenshot. I figured this would be useful when automatically screenshotting parks.

0 = default (saved game weather)
1 = sunny
6 = thunderstorm

Here's a simple example of two screenshots made with the folling commands:

```
openrct2.com screenshot _DEBUGGING.sv6 _DEBUGGING0.png 400 280 --weather=1
openrct2.com screenshot _DEBUGGING.sv6 _DEBUGGING4.png 400 280 --weather=5
```

### CODE REVIEW

**Comment by marijnvdwerf** [comment]
Wouldn't a `--weather=0` be more friendly? The screenshot command already has quite a few positional elements.

**Comment by Gymnasiast** [comment]
I think that might be better, yes. It might not be the last argument we add either.

**Comment by Broxzier** [comment]
Here are the three allowed command signatures, with two `--weather=X` variants for each to try out:

```
openrct2 screenshot "park.sv6" "scr1.png" 640 480
openrct2 screenshot "park.sv6" "scr2.png" 640 480 --weather=1
openrct2 screenshot "park.sv6" "scr3.png" 640 480 --weather=6
openrct2 screenshot "park.sv6" "scr4.png" 640 480 c c 0 0
openrct2 screenshot "park.sv6" "scr5.png" 640 480 c c 0 0 --weather=1
openrct2 screenshot "park.sv6" "scr6.png" 640 480 c c 0 0 --weather=6
openrct2 screenshot "park.sv6" "scr7.png" giant 2 0
openrct2 screenshot "park.sv6" "scr8.png" giant 2 0 --weather=1
openrct2 screenshot "park.sv6" "scr9.png" giant 2 0 --weather=6
```

**Comment by marijnvdwerf** [comment]
Do these also work?

```
openrct2 screenshot --weather=1 "park.sv6" "scr1.png" 640 480
openrct2 screenshot --weather 1 "park.sv6" "scr1.png" 640 480
```

**Comment by IntelOrca** [comment]
@marijnvdwerf we only support options after all positional arguments.

**Pull request merged**
