### PR TITLE
Replace std::stringstream with custom string buffer

### PR DESCRIPTION
**Pull request by ZehMatt**
This increases the overall performance of string formatting, its near identical to what was before the refactor.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
That looks nice! What benchmarks did you use to determine the formatting performance?

**Comment by ZehMatt** [comment]
No specific benchmarks, I just opened bpb.sv6 and immediately opened the Guest window and took the averages.

**Review by tupaschoal — COMMENTED** [review]
Don't you want to investigate whether we can use fmtlib? It's measurably faster than all of the built in string streaming and we wouldn't have to maintain our own

**Comment by ZehMatt** [comment]
> Don't you want to investigate whether we can use fmtlib? It's measurably faster than all of the built in string streaming and we wouldn't have to maintain our own

Given how specific the localisation is I don't think we can simply apply fmtlib, or at least I'm not aware on how to, we need to unpack the arguments and sometimes the format string has modifiers also.

**Comment by Gymnasiast** [comment]
The new formatting framework has made it easier to move formatting stuff out of translation strings and into the code itself. I think we should clean up the strings first anyway.

I unfortunately cannot check if there is improved performance (testing with Blackpool Pleasure Beach, at 1920x1200ish, OpenGL, on Ubuntu 20.04), as the FPS fluctuates too much. Mind you, it doesn't seem worse either.

**Comment by ZehMatt** [comment]
On my machine its like this

Before:
bpb.sv6 Guest Window (max window size) open at 720p, 100 FPS average.

After:
bpb.sv6 Guest Window (max window size) open at 720p, 190 FPS average.

There are huge stutters when the guest window is open or when some news get reported, basically whenever some text was drawn it becomes pretty unstable framerate wise.

**Review by IntelOrca — APPROVED** [review]

**Comment by Gymnasiast** [comment]
@ZehMatt Which render mode are you using? And did you compile in debug mode or in release mode?

**Comment by ZehMatt** [comment]
There seems to be a few unexpected side effects, need to fix them first.

**Comment by ZehMatt** [comment]
> @ZehMatt Which render mode are you using? And did you compile in debug mode or in release mode?

Release build and Software (HW)

**Comment by tupaschoal** [comment]
> Given how specific the localisation is I don't think we can simply apply fmtlib, or at least I'm not aware on how to, we need to unpack the arguments and sometimes the format string has modifiers also.

Maybe we can use [`fmt::memory_buffer`](https://fmt.dev/latest/api.html#_CPPv2N3fmt19basic_memory_bufferE), but if you don't have the time to investigate (or don't want to) we can try this later on.

> Before: bpb.sv6 Guest Window (max window size) open at 720p, 100 FPS average.
> After: bpb.sv6 Guest Window (max window size) open at 720p, 190 FPS average.

Nice! Maybe if you checkout @janisozaur `benchsimulte` pr we can have a more consistent measurement?

**Comment by ZehMatt** [comment]
None of the benchmarks really consider the text, if you don't hover over a peep or open some window you will never really have any string formatting happening so the benchmarks are not applicable here.

**Review by Gymnasiast — COMMENTED** [review]
Still cannot reproduce the increased performance, but there appear to be no regressions (in performance or functionality).

**Comment by ZehMatt** [comment]
This is strange, it has a really huge hit here when I have the Guest window open.

develop: 
No Guests window:
openrct2_2021-01-01_00-27-2895f1e6916b9d87cdb
Guests Window:
openrct2_2021-01-01_00-27-410c95613b0394fe325

PR:
No Guests window:
openrct2_2021-01-01_00-29-31cb5dd0c07a92506fc
Guests Window:
openrct2_2021-01-01_00-29-378e1734c6e3fc6c5b3

**Comment by IntelOrca** [comment]
The guest window requires its own optimisations, namely the sort comparator which does more format string calls than it needs to. It would be faster if it cached all the guest names and sorted those.

**Comment by ZehMatt** [comment]
> The guest window requires its own optimisations, namely the sort comparator which does more format string calls than it needs to. It would be faster if it cached all the guest names and sorted those.

That might be the case but the string formatting adds quite a lot currently, but yes there is definitely room to improve that.

**Comment by Gymnasiast** [comment]
For me, the framerate is fluctuating anyway and opening the guests window does not seem to have any influence at all.

I wonder if it would be possible to write a benchmark for this? It might be a lot of work, but it would at least allow for properly testing the impact of formatting changes and optimisations to window drawing code.

**Comment by ZehMatt** [comment]
If I had to guess the performance impact is bigger on windows. The main issue with the formatter was the stringstream using a bunch of allocations every frame, so this might be specific to the msvc runtime/windows memory manager.

**Comment by duncanspumpkin** [comment]
that window is really inefficient (I know because I rewrote the sort function part) we should copy Locomotion for sure. In locomotion it would sort the list a bit at a time over a number of ticks.

**Comment by ZehMatt** [comment]
As for benchmarks, I simply made every test we have for formatting loop 100k times, this is what I get:

develop:
```
[----------] 63 tests from FormattingTests
[ RUN      ] FormattingTests.no_args
[       OK ] FormattingTests.no_args (58 ms)
[ RUN      ] FormattingTests.missing_arg
[       OK ] FormattingTests.missing_arg (64 ms)
[ RUN      ] FormattingTests.integer
[       OK ] FormattingTests.integer (67 ms)
[ RUN      ] FormattingTests.integer_integer
[       OK ] FormattingTests.integer_integer (85 ms)
[ RUN      ] FormattingTests.comma
[       OK ] FormattingTests.comma (77 ms)
[ RUN      ] FormattingTests.comma_0
[       OK ] FormattingTests.comma_0 (65 ms)
[ RUN      ] FormattingTests.comma_large_negative
[       OK ] FormattingTests.comma_large_negative (128 ms)
[ RUN      ] FormattingTests.comma_large
[       OK ] FormattingTests.comma_large (126 ms)
[ RUN      ] FormattingTests.currency
[       OK ] FormattingTests.currency (405 ms)
[ RUN      ] FormattingTests.currency2dp
[       OK ] FormattingTests.currency2dp (455 ms)
[ RUN      ] FormattingTests.currency_yen
[       OK ] FormattingTests.currency_yen (440 ms)
[ RUN      ] FormattingTests.currency2dp_yen
[       OK ] FormattingTests.currency2dp_yen (434 ms)
[ RUN      ] FormattingTests.currency_pts
[       OK ] FormattingTests.currency_pts (145 ms)
[ RUN      ] FormattingTests.currency2dp_pts
[       OK ] FormattingTests.currency2dp_pts (243 ms)
[ RUN      ] FormattingTests.string
[       OK ] FormattingTests.string (74 ms)
[ RUN      ] FormattingTests.escaped_braces
[       OK ] FormattingTests.escaped_braces (72 ms)
[ RUN      ] FormattingTests.velocity_mph
[       OK ] FormattingTests.velocity_mph (110 ms)
[ RUN      ] FormattingTests.velocity_kph
[       OK ] FormattingTests.velocity_kph (112 ms)
[ RUN      ] FormattingTests.velocity_mps
[       OK ] FormattingTests.velocity_mps (112 ms)
[ RUN      ] FormattingTests.length_imperial
[       OK ] FormattingTests.length_imperial (105 ms)
[ RUN      ] FormattingTests.length_metric
[       OK ] FormattingTests.length_metric (100 ms)
[ RUN      ] FormattingTests.length_si
[       OK ] FormattingTests.length_si (99 ms)
[ RUN      ] FormattingTests.minssecs
[       OK ] FormattingTests.minssecs (863 ms)
[ RUN      ] FormattingTests.hoursmins
[       OK ] FormattingTests.hoursmins (868 ms)
[ RUN      ] FormattingTests.month
[       OK ] FormattingTests.month (214 ms)
[ RUN      ] FormattingTests.monthyear
[       OK ] FormattingTests.monthyear (289 ms)
[ RUN      ] FormattingTests.two_level_format
[       OK ] FormattingTests.two_level_format (100 ms)
[ RUN      ] FormattingTests.any_string_int_string
[       OK ] FormattingTests.any_string_int_string (94 ms)
[ RUN      ] FormattingTests.any_two_level_format
[       OK ] FormattingTests.any_two_level_format (84 ms)
[ RUN      ] FormattingTests.to_fixed_buffer
[       OK ] FormattingTests.to_fixed_buffer (78 ms)
[ RUN      ] FormattingTests.using_legacy_buffer_args
[       OK ] FormattingTests.using_legacy_buffer_args (114 ms)
[ RUN      ] FormattingTests.format_number_basic
[       OK ] FormattingTests.format_number_basic (43 ms)
[ RUN      ] FormattingTests.format_number_basic_int32
[       OK ] FormattingTests.format_number_basic_int32 (43 ms)
[ RUN      ] FormattingTests.format_number_negative
[       OK ] FormattingTests.format_number_negative (46 ms)
[ RUN      ] FormattingTests.format_number_comma16_basic
[       OK ] FormattingTests.format_number_comma16_basic (41 ms)
[ RUN      ] FormattingTests.format_number_comma16_negative
[       OK ] FormattingTests.format_number_comma16_negative (46 ms)
[ RUN      ] FormattingTests.format_number_comma16_large
[       OK ] FormattingTests.format_number_comma16_large (61 ms)
[ RUN      ] FormattingTests.format_number_comma16_large_negative
[       OK ] FormattingTests.format_number_comma16_large_negative (65 ms)
[ RUN      ] FormattingTests.format_number_comma16_uneven
[       OK ] FormattingTests.format_number_comma16_uneven (59 ms)
[ RUN      ] FormattingTests.format_number_comma16_uneven_negative
[       OK ] FormattingTests.format_number_comma16_uneven_negative (63 ms)
[ RUN      ] FormattingTests.format_number_comma16_zero
[       OK ] FormattingTests.format_number_comma16_zero (36 ms)
[ RUN      ] FormattingTests.format_number_comma1dp16_zero
[       OK ] FormattingTests.format_number_comma1dp16_zero (43 ms)
[ RUN      ] FormattingTests.format_number_comma1dp16_leading_zero
[       OK ] FormattingTests.format_number_comma1dp16_leading_zero (43 ms)
[ RUN      ] FormattingTests.format_number_comma1dp16_leading_zero_negative
[       OK ] FormattingTests.format_number_comma1dp16_leading_zero_negative (45 ms)
[ RUN      ] FormattingTests.format_number_comma1dp16_small_value
[       OK ] FormattingTests.format_number_comma1dp16_small_value (42 ms)
[ RUN      ] FormattingTests.format_number_comma1dp16_small_value_negative
[       OK ] FormattingTests.format_number_comma1dp16_small_value_negative (46 ms)
[ RUN      ] FormattingTests.format_number_comma1dp16_trailing_zeros
[       OK ] FormattingTests.format_number_comma1dp16_trailing_zeros (48 ms)
[ RUN      ] FormattingTests.format_number_comma1dp16_trailing_zeros_negative
[       OK ] FormattingTests.format_number_comma1dp16_trailing_zeros_negative (51 ms)
[ RUN      ] FormattingTests.format_number_comma1dp16_large_trailing_zeros
[       OK ] FormattingTests.format_number_comma1dp16_large_trailing_zeros (64 ms)
[ RUN      ] FormattingTests.format_number_comma1dp16_large_trailing_zeros_negative
[       OK ] FormattingTests.format_number_comma1dp16_large_trailing_zeros_negative (65 ms)
[ RUN      ] FormattingTests.format_number_comma1dp16_large_value
[       OK ] FormattingTests.format_number_comma1dp16_large_value (65 ms)
[ RUN      ] FormattingTests.format_number_comma1dp16_large_value_negative
[       OK ] FormattingTests.format_number_comma1dp16_large_value_negative (67 ms)
[ RUN      ] FormattingTests.format_number_comma2dp32_zero
[       OK ] FormattingTests.format_number_comma2dp32_zero (46 ms)
[ RUN      ] FormattingTests.format_number_comma2dp32_less_sig_figs
[       OK ] FormattingTests.format_number_comma2dp32_less_sig_figs (46 ms)
[ RUN      ] FormattingTests.format_number_comma2dp32_less_sig_figs_negative
[       OK ] FormattingTests.format_number_comma2dp32_less_sig_figs_negative (49 ms)
[ RUN      ] FormattingTests.format_number_comma2dp32_leading_zero
[       OK ] FormattingTests.format_number_comma2dp32_leading_zero (46 ms)
[ RUN      ] FormattingTests.format_number_comma2dp32_leading_zero_negative
[       OK ] FormattingTests.format_number_comma2dp32_leading_zero_negative (48 ms)
[ RUN      ] FormattingTests.format_number_comma2dp32_trailing_zeros
[       OK ] FormattingTests.format_number_comma2dp32_trailing_zeros (48 ms)
[ RUN      ] FormattingTests.format_number_comma2dp32_trailing_zeros_negative
[       OK ] FormattingTests.format_number_comma2dp32_trailing_zeros_negative (51 ms)
[ RUN      ] FormattingTests.format_number_comma2dp32_large_trailing_zeros
[       OK ] FormattingTests.format_number_comma2dp32_large_trailing_zeros (61 ms)
[ RUN      ] FormattingTests.format_number_comma2dp32_large_trailing_zeros_negative
[       OK ] FormattingTests.format_number_comma2dp32_large_trailing_zeros_negative (62 ms)
[ RUN      ] FormattingTests.format_number_comma2dp32_large_value
[       OK ] FormattingTests.format_number_comma2dp32_large_value (65 ms)
[ RUN      ] FormattingTests.format_number_comma2dp32_large_value_negative
[       OK ] FormattingTests.format_number_comma2dp32_large_value_negative (67 ms)
[----------] 63 tests from FormattingTests (7951 ms total)
```
Test Code: https://gist.github.com/ZehMatt/56c99ebc219e896e38d595487fedbf4f

PR:
```
[----------] 64 tests from FormattingTests
[ RUN      ] FormattingTests.no_args
[       OK ] FormattingTests.no_args (21 ms)
[ RUN      ] FormattingTests.missing_arg
[       OK ] FormattingTests.missing_arg (25 ms)
[ RUN      ] FormattingTests.integer
[       OK ] FormattingTests.integer (25 ms)
[ RUN      ] FormattingTests.integer_integer
[       OK ] FormattingTests.integer_integer (37 ms)
[ RUN      ] FormattingTests.comma
[       OK ] FormattingTests.comma (28 ms)
[ RUN      ] FormattingTests.comma_0
[       OK ] FormattingTests.comma_0 (25 ms)
[ RUN      ] FormattingTests.comma_large_negative
[       OK ] FormattingTests.comma_large_negative (42 ms)
[ RUN      ] FormattingTests.comma_large
[       OK ] FormattingTests.comma_large (42 ms)
[ RUN      ] FormattingTests.currency
[       OK ] FormattingTests.currency (153 ms)
[ RUN      ] FormattingTests.currency2dp
[       OK ] FormattingTests.currency2dp (175 ms)
[ RUN      ] FormattingTests.currency_yen
[       OK ] FormattingTests.currency_yen (166 ms)
[ RUN      ] FormattingTests.currency2dp_yen
[       OK ] FormattingTests.currency2dp_yen (165 ms)
[ RUN      ] FormattingTests.currency_pts
[       OK ] FormattingTests.currency_pts (54 ms)
[ RUN      ] FormattingTests.currency2dp_pts
[       OK ] FormattingTests.currency2dp_pts (91 ms)
[ RUN      ] FormattingTests.string
[       OK ] FormattingTests.string (33 ms)
[ RUN      ] FormattingTests.escaped_braces
[       OK ] FormattingTests.escaped_braces (27 ms)
[ RUN      ] FormattingTests.velocity_mph
[       OK ] FormattingTests.velocity_mph (58 ms)
[ RUN      ] FormattingTests.velocity_kph
[       OK ] FormattingTests.velocity_kph (58 ms)
[ RUN      ] FormattingTests.velocity_mps
[       OK ] FormattingTests.velocity_mps (59 ms)
[ RUN      ] FormattingTests.length_imperial
[       OK ] FormattingTests.length_imperial (56 ms)
[ RUN      ] FormattingTests.length_metric
[       OK ] FormattingTests.length_metric (51 ms)
[ RUN      ] FormattingTests.length_si
[       OK ] FormattingTests.length_si (50 ms)
[ RUN      ] FormattingTests.minssecs
[       OK ] FormattingTests.minssecs (475 ms)
[ RUN      ] FormattingTests.hoursmins
[       OK ] FormattingTests.hoursmins (475 ms)
[ RUN      ] FormattingTests.month
[       OK ] FormattingTests.month (94 ms)
[ RUN      ] FormattingTests.monthyear
[       OK ] FormattingTests.monthyear (156 ms)
[ RUN      ] FormattingTests.two_level_format
[       OK ] FormattingTests.two_level_format (55 ms)
[ RUN      ] FormattingTests.any_string_int_string
[       OK ] FormattingTests.any_string_int_string (36 ms)
[ RUN      ] FormattingTests.any_two_level_format
[       OK ] FormattingTests.any_two_level_format (37 ms)
[ RUN      ] FormattingTests.to_fixed_buffer
[       OK ] FormattingTests.to_fixed_buffer (27 ms)
[ RUN      ] FormattingTests.using_legacy_buffer_args
[       OK ] FormattingTests.using_legacy_buffer_args (66 ms)
[ RUN      ] FormattingTests.format_number_basic
[       OK ] FormattingTests.format_number_basic (4 ms)
[ RUN      ] FormattingTests.format_number_basic_int32
[       OK ] FormattingTests.format_number_basic_int32 (3 ms)
[ RUN      ] FormattingTests.format_number_negative
[       OK ] FormattingTests.format_number_negative (4 ms)
[ RUN      ] FormattingTests.format_number_comma16_basic
[       OK ] FormattingTests.format_number_comma16_basic (4 ms)
[ RUN      ] FormattingTests.format_number_comma16_negative
[       OK ] FormattingTests.format_number_comma16_negative (4 ms)
[ RUN      ] FormattingTests.format_number_comma16_large
[       OK ] FormattingTests.format_number_comma16_large (7 ms)
[ RUN      ] FormattingTests.format_number_comma16_large_negative
[       OK ] FormattingTests.format_number_comma16_large_negative (8 ms)
[ RUN      ] FormattingTests.format_number_comma16_uneven
[       OK ] FormattingTests.format_number_comma16_uneven (7 ms)
[ RUN      ] FormattingTests.format_number_comma16_uneven_negative
[       OK ] FormattingTests.format_number_comma16_uneven_negative (8 ms)
[ RUN      ] FormattingTests.format_number_comma16_zero
[       OK ] FormattingTests.format_number_comma16_zero (2 ms)
[ RUN      ] FormattingTests.format_number_comma1dp16_zero
[       OK ] FormattingTests.format_number_comma1dp16_zero (5 ms)
[ RUN      ] FormattingTests.format_number_comma1dp16_leading_zero
[       OK ] FormattingTests.format_number_comma1dp16_leading_zero (4 ms)
[ RUN      ] FormattingTests.format_number_comma1dp16_leading_zero_negative
[       OK ] FormattingTests.format_number_comma1dp16_leading_zero_negative (5 ms)
[ RUN      ] FormattingTests.format_number_comma1dp16_small_value
[       OK ] FormattingTests.format_number_comma1dp16_small_value (5 ms)
[ RUN      ] FormattingTests.format_number_comma1dp16_small_value_negative
[       OK ] FormattingTests.format_number_comma1dp16_small_value_negative (5 ms)
[ RUN      ] FormattingTests.format_number_comma1dp16_trailing_zeros
[       OK ] FormattingTests.format_number_comma1dp16_trailing_zeros (5 ms)
[ RUN      ] FormattingTests.format_number_comma1dp16_trailing_zeros_negative
[       OK ] FormattingTests.format_number_comma1dp16_trailing_zeros_negative (6 ms)
[ RUN      ] FormattingTests.format_number_comma1dp16_large_trailing_zeros
[       OK ] FormattingTests.format_number_comma1dp16_large_trailing_zeros (9 ms)
[ RUN      ] FormattingTests.format_number_comma1dp16_large_trailing_zeros_negative
[       OK ] FormattingTests.format_number_comma1dp16_large_trailing_zeros_negative (9 ms)
[ RUN      ] FormattingTests.format_number_comma1dp16_large_value
[       OK ] FormattingTests.format_number_comma1dp16_large_value (8 ms)
[ RUN      ] FormattingTests.format_number_comma1dp16_large_value_negative
[       OK ] FormattingTests.format_number_comma1dp16_large_value_negative (10 ms)
[ RUN      ] FormattingTests.format_number_comma2dp32_zero
[       OK ] FormattingTests.format_number_comma2dp32_zero (5 ms)
[ RUN      ] FormattingTests.format_number_comma2dp32_less_sig_figs
[       OK ] FormattingTests.format_number_comma2dp32_less_sig_figs (4 ms)
[ RUN      ] FormattingTests.format_number_comma2dp32_less_sig_figs_negative
[       OK ] FormattingTests.format_number_comma2dp32_less_sig_figs_negative (6 ms)
[ RUN      ] FormattingTests.format_number_comma2dp32_leading_zero
[       OK ] FormattingTests.format_number_comma2dp32_leading_zero (5 ms)
[ RUN      ] FormattingTests.format_number_comma2dp32_leading_zero_negative
[       OK ] FormattingTests.format_number_comma2dp32_leading_zero_negative (5 ms)
[ RUN      ] FormattingTests.format_number_comma2dp32_trailing_zeros
[       OK ] FormattingTests.format_number_comma2dp32_trailing_zeros (6 ms)
[ RUN      ] FormattingTests.format_number_comma2dp32_trailing_zeros_negative
[       OK ] FormattingTests.format_number_comma2dp32_trailing_zeros_negative (6 ms)
[ RUN      ] FormattingTests.format_number_comma2dp32_large_trailing_zeros
[       OK ] FormattingTests.format_number_comma2dp32_large_trailing_zeros (8 ms)
[ RUN      ] FormattingTests.format_number_comma2dp32_large_trailing_zeros_negative
[       OK ] FormattingTests.format_number_comma2dp32_large_trailing_zeros_negative (8 ms)
[ RUN      ] FormattingTests.format_number_comma2dp32_large_value
[       OK ] FormattingTests.format_number_comma2dp32_large_value (9 ms)
[ RUN      ] FormattingTests.format_number_comma2dp32_large_value_negative
[       OK ] FormattingTests.format_number_comma2dp32_large_value_negative (10 ms)
[ RUN      ] FormattingTests.buffer_storage_swap
[       OK ] FormattingTests.buffer_storage_swap (7 ms)
[----------] 64 tests from FormattingTests (3063 ms total)
```
Test Code: https://gist.github.com/ZehMatt/4d6df80b022bddea2420e802d2c7f24f

So on my machine its ```7951 ms``` vs ```3063 ms``` which is an improvement of 259%

**Comment by Gymnasiast** [comment]
I had to leave the house before I could post the results, but I went from 7 to 3 seconds.

**Review by Gymnasiast — APPROVED** [review]

**Pull request merged**
