### PR TITLE
Add cheat to reset date

### PR DESCRIPTION
**Pull request by wolfreak99**
This was requested via https://www.reddit.com/r/openrct2/comments/4uyjxs/how_to_reset_the_date_with_cheats/ , and digging through the code I discovered there was already a "date_reset()" function that did exactly that, so all that was needed was mapping it to a cheat button.

### CODE REVIEW

**Comment by Nubbie** [comment]
@wolfreak99 Could need a tooltip in-game, most buttons have one, 'reset date' doesn't tell the player too much ;o

**Comment by wolfreak99** [comment]
I honestly had you in mind for tooltips, in fact I usually do. You seemed more active with tooltips, where as I have tried tooltips but most of the time I never know how to describe something in a.. fluent manner, i guess?

**Comment by Gymnasiast** [comment]
`Sets the date back to 1st January, Year 1`

(UK English)

**Comment by Nubbie** [comment]
@Gymnasiast That's not true, as it seems to reset the date to the scenarios start time

**Comment by wolfreak99** [comment]
Basically 1st March, Year 1, but his formatting seemed good / human enough

**Comment by wolfreak99** [comment]
"I would suggest making it easy and fluent" that's the problem i have, I have troubles making a "fluent" message many times. I speak very technically when it comes to stuff, and struggle with keeping stuff simple. Have you seen my paragraph-long messages in the dev chat asking a question that could be reworded into 4 or 5 words?

**Comment by Nubbie** [comment]
"Too clever is dumb." _– Ogden Nash_ :p 

Mostly just a small text that sums it up is good, if having trouble, ask/make one that could be changed ^^

**Pull request merged**
