### PR TITLE
Reformat with clang-format-12 from updated CI image

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by janisozaur** [comment]
When updating CI images for Android and C++20, clang-format version also got updated to version 12. This addresses formatting issues it had.

**Comment by ZehMatt** [comment]
Something is still broken

**Comment by janisozaur** [comment]
I pulled the image and cannot reproduce the error the build using it has.

**Comment by janisozaur** [comment]
Found the issue:
Something (curl?) is trying to link to brotli, but the build is marked as static. That fails because static brotli names are different from dynamic ones and I suspect some configuration does not reflect that properly. I can fix that up in the image itself.

That deals with the initial issue and gets me to second one:
```
/usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld: /usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/lib/../lib/libgnutls.a(sysrng-bcrypt.o):(.text+0x29): undefined reference to `BCryptGenRandom@16'
/usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld: /usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/lib/../lib/libgnutls.a(sysrng-bcrypt.o):(.text+0x97): undefined reference to `BCryptOpenAlgorithmProvider@16'
/usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld: /usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/lib/../lib/libgnutls.a(sysrng-bcrypt.o):(.text+0xf8): undefined reference to `BCryptCloseAlgorithmProvider@8'
/usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld: /usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/lib/../lib/libgnutls.a(keys-win.o):(.text+0x53): undefined reference to `NCryptFreeObject@4'
/usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld: /usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/lib/../lib/libgnutls.a(keys-win.o):(.text+0x110): undefined reference to `NCryptSignHash@32'
/usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld: /usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/lib/../lib/libgnutls.a(keys-win.o):(.text+0x16b): undefined reference to `NCryptSignHash@32'
/usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld: /usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/lib/../lib/libgnutls.a(keys-win.o):(.text+0x443): undefined reference to `NCryptDecrypt@32'
/usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld: /usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/lib/../lib/libgnutls.a(keys-win.o):(.text+0x4a0): undefined reference to `NCryptDecrypt@32'
/usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld: /usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/lib/../lib/libgnutls.a(keys-win.o):(.text+0x1726): undefined reference to `NCryptFreeObject@4'
/usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld: /usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/lib/../lib/libgnutls.a(keys-win.o):(.text+0x173c): undefined reference to `NCryptFreeObject@4'
/usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld: /usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/lib/../lib/libgnutls.a(keys-win.o):(.text+0x176b): undefined reference to `NCryptOpenStorageProvider@12'
/usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld: /usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/lib/../lib/libgnutls.a(keys-win.o):(.text+0x190e): undefined reference to `NCryptOpenKey@20'
/usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld: /usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/lib/../lib/libgnutls.a(keys-win.o):(.text+0x1950): undefined reference to `NCryptGetProperty@24'
/usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld: /usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/lib/../lib/libgnutls.a(keys-win.o):(.text+0x1a8b): undefined reference to `NCryptFreeObject@4'
/usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld: /usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/lib/../lib/libgnutls.a(keys-win.o):(.text+0x2788): undefined reference to `NCryptDeleteKey@8'
/usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld: /usr/lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/lib/../lib/libgnutls.a(keys-win.o):(.text+0x2797): undefined reference to `NCryptFreeObject@4'
```
This is unfortunate as the build was meant to be nt5.1, but `bcrypt` and `ncrypt` are vista+ APIs. If that's all indeed due to curl, I think I will just drop support for it in this build.

**Comment by janisozaur** [comment]
Fixed in https://github.com/OpenRCT2/openrct2-docker-build/pull/12

**Review by ZehMatt — APPROVED** [review]

**Comment by Broxzier** [comment]
Did anyone check which version Visual Studio ships with? This may introduce some annoying header reordering to happen for systems where LLVM is not installed.

**Comment by ZehMatt** [comment]
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\Llvm\x64\bin>clang-format --version
clang-format version 12.0.0
```

**Comment by Broxzier** [comment]
On my laptop, VS's clang-format's version is at 10.0.0, but that's a pretty old installation. Microsoft Visual Studio Community 2019 Version 16.8.3

**Comment by ZehMatt** [comment]
Should probably tell people to update if they run into clang-format inconsistencies I guess.

**Pull request merged**
