### PR TITLE
Sort by status

### PR DESCRIPTION
**Pull request by wolfreak99**
I wrote this while really hammered one night, but i originally used alot of if elses in the code. i just went through and reworked the deciding numbers into its own function. i'm not really sure if this is a common way to create external sort methods like this but this gets the job done...

http://i.imgur.com/uOdmxFr.png
example of list being sorted

### CODE REVIEW

**Comment by IntelOrca** [comment]
There is no point adding this unless people are actually wanting to view their rides sorted by status, which would probably be sorted wrong anyway as it starts with a number.

**Comment by wolfreak99** [comment]
@IntelOrca  I mean this could help with online usage in servers where admins need to clear out some rides that don't get finished. say a park is near 100 rides, with multiplayer needing the remove ride for most users to prevent vandalism, alot of rides don't even get inserted into the game. this doesn't sort by name, this sorts by more than just the status of a ride. by status we are talking a ride being opened, in test mode, and closing. not by name. idk where you have the number portion from though. but check the picture and code. and considering theres positive reactions on my post, plus, the "sort" next to status implies it sorts the status anyway, which often leaves people confused. im sorry if any of this sounds awkward or repetitive or confusing, if you need some clarification on any part of this message let me know, i'm drinking straight vodka so idk if i am even making sense.

**Comment by IntelOrca** [comment]
We shouldn't just add things unless there is demand for it.

**Comment by Margen67** [comment]
Being able to sort by status would help clean up rides. For example rides that have been testing, or closed and have no tracks but weren't demolished.
You could also check which rides are broken down.

A better solution for that would be to make users without demolish permissions able to demolish a nonexistent ride so they don't need to be cleaned up in the first place, but whatever.

**Comment by Nubbie** [comment]
>A better solution for that would be to make users without demolish permissions able to demolish a nonexistent ride

there shouldn't be any non existing rides anyways and should be fixed instead

**Comment by IntelOrca** [comment]
A new window system is next on our list of things to do. And a new sortable grid widget will come with that which will allow any column to be sorted. So no need for this change.

**Pull request closed without merging**
