### PR TITLE
Fix compilation of LightFX with GCC

### PR DESCRIPTION
**Pull request by janisozaur**
I only made it compile, don't know if it really works as intended. Can someone please post a park to use + a screenshot from MSVC build?

### CODE REVIEW

**Comment by IntelOrca** [comment]
Hardware display only:
image

**Comment by janisozaur** [comment]
Can you share the park as well?

**Comment by IntelOrca** [comment]
[Stout-Games-Park-Continuous-13.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/615026/Stout-Games-Park-Continuous-13.sv6.txt)

**Comment by janisozaur** [comment]
I tested and it works: 
openrct2_176

It is a subject to some non-obvious constraints: only certain rotations, at some zoom levels mouse has to be in some specific positions.

**Pull request merged**
