### PR TITLE
Add overloads to take CoordsXYZ

### PR DESCRIPTION
**Pull request by duncanspumpkin**
I tried to do the find and replace but my PC is really struggling to process the regex across all the paint track files as its so complex adding in all the new line checks.
```
PaintAddImageAsParentRotated\([\s\r]*?([^,]*),[\s\r]*?([^,]*),[\s\r]*?([^,]*),[\s\r]*?([^\{,]+),[\s\r]*?([^,]*),[\s\r]*?([^,]*),[\s\r]*?([^,]*),[\s\r]*?([^,]*),[\s\r]*?([^,]*)\);

PaintAddImageAsParentRotated($1, $2, $3, {$4, $5, $9}, {$6, $7, $8});
```
```
PaintAddImageAsParentRotated\([\s\r]*?([^,]*),[\s\r]*?([^,]*),[\s\r]*?([^,]*),[\s\r]*?([^\{,]+),[\s\r]*?([^,]*),[\s\r]*?([^,]*),[\s\r]*?([^,]*),[\s\r]*?([^,]*),[\s\r]*?([^,]*),[\s\r]*?([^,]*),[\s\r]*?([^,]*),[\s\r]*?([^,]*)\);

PaintAddImageAsParentRotated($1, $2, $3, {$4, $5, $9}, {$6, $7, $8}, {$10, $11, $12});
```
```
PaintAddImageAsChildRotated\([\s\r]*?([^,]*),[\s\r]*?([^,]*),[\s\r]*?([^,]*),[\s\r]*?([^\{,]+),[\s\r]*?([^,]*),[\s\r]*?([^,]*),[\s\r]*?([^,]*),[\s\r]*?([^,]*),[\s\r]*?([^,]*),[\s\r]*?([^,]*),[\s\r]*?([^,]*),[\s\r]*?([^,]*)\);

PaintAddImageAsChildRotated($1, $2, $3, {$4, $5, $9}, {$6, $7, $8}, {$10, $11, $12});
```

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Hm, why is your regex checking for carriage return (\r) instead of newline (\n)? Our files only use the latter.

**Comment by duncanspumpkin** [comment]
That is the regex for visual studio's new line. Other editors/regex engines will use alternatives.

**Comment by duncanspumpkin** [comment]
Strangely its just one or two files that VS is struggling on processing at least thats my conclusion after finally applying most of the first version of `PaintAddImageAsParentRotated`

**Comment by ZehMatt** [comment]
I think it would have been better to wait for the other PR to be merged or have it based on that branch, there are apparently conflicts with the two.

**Comment by duncanspumpkin** [comment]
That's fine can just discard the commits where i applied the regex and redo them.

**Comment by duncanspumpkin** [comment]
I propose adding these overloads then in 3 separate PRs use the regex's to apply and remove the legacy versions.

**Review by ZehMatt — APPROVED** [review]
I'll do the follow up ones

**Comment by Gymnasiast** [comment]
Mind the milestone!

**Pull request merged**
