### PR TITLE
Add Catalan to the list of available languages.

### PR DESCRIPTION
**Pull request by J0anJosep**
With the recent addition of the Catalan translation, this pull request is for adding Catalan to the list of available languages in the game.
I haven't tried it. Before merging, please check it compiles and it works as expected.

### CODE REVIEW

**Comment by J0anJosep** [comment]
By the way, at some point languages will need some sorting.

**Comment by IntelOrca** [comment]
> I haven't tried it. Before merging, please check it compiles and it works as expected.

This is done automatically, if click show all checks you will see details for Travis and AppVeyor. With AppVeyor, you can click a platform and then artifacts to download the build.

**Comment by J0anJosep** [comment]
Thanks!
I have checked it and it works. The language is available now.

**Comment by Gymnasiast** [comment]
I didn't see this PR before I created https://github.com/OpenRCT2/OpenRCT2/pull/5222
However, my PR also updates the changelog and contributors file. I have also tested mine.

**Comment by J0anJosep** [comment]
#5222 is better than this one. Just close this and merge #5222.

**Pull request closed without merging**
