### PR TITLE
Fix CMakeLists for MinGW cross-compilation

### PR DESCRIPTION
**Pull request by janisozaur**
This makes sure that shared library built with MinGW toolchain is linked
statically to *all* its dependencies, including libc, libstdc++, libsdl2
and all the others. This allows producing of working `openrct2.dll` by
cross-compiling.

I hit a bug with libcrypto, a dependency of libssl, which in turn is a
dependency of curl, which creates a `DllMain` entrypoint for static lib
too, but since we don't do anything in ours, this should be safe.

I have only had chance to try it out when cross-compiling, ideally it
should be tested under Cygwin/MSYS too, but it is too bothersome to
setup for me.

### CODE REVIEW

**Comment by janisozaur** [comment]
This fails on travis and obviously requires some more work for that reason, as ubuntu does not provide mingw packages of all required libraries (basically, it provides none).

I'm considering following solutions:
* change the `WIN32` detection to rather rely on our own parameter specifying static build and making travis produce dynamic build
* migrating mingw builds to docker with Arch, which has all the needed packages (already started testing feasibility of that)
* somehow providing required libs for travis.

**Comment by janisozaur** [comment]
This turned out to be much more work than I expected, but is ready for review now.

My main motivation was fixing the `CMakeLists_mingw.txt` which didn't really work properly and was unable to produce statically linked library. It now is capable of doing so[1], which means that we can provide builds of openrct2 supporting XP with mingw as a single dll that are fully capable[2].

[1] `cmake -DCMAKE_TOOLCHAIN_FILE=../CMakeLists_mingw.txt ../ -DSTATIC=ON` do note this requires having static versions of libraries we depend upon, which are not shipped on Ubuntu, but are available as 3rd party packages on Arch. I don't know about other systems.
[2] Even though the Visual Studio has `Release XP` configuration, it disables few things, multiplayer being one of them.

**Comment by janisozaur** [comment]
For testing purposes:
https://transfer.sh/1603gI/openrct2.dll
https://transfer.sh/19Vc0I/openrct2-stripped.dll

The stripped version has no debug info and is significantly smaller.

shasums:
```
2a2b5ee03a8e8326446441f189c591f72e64e4960563907bb4a18c8cd97a8416  openrct2.dll
aa2bc3ab902c5a5668d5d38ff8e4c1d2676a23904a716aa1ce8a990f3f69c7ff  openrct2-stripped.dll
```

No other dlls should be needed (not even `SDL2.dll` included in the repo)

**Comment by IntelOrca** [comment]
I can confirm this works (on Windows 10).
So did you statically link SDL2?

**Comment by janisozaur** [comment]
Yes, it's all statically linked with one simple switch now. If the `STATIC` option is turned off, you get your regular shared library that depends on all the other DLLs.

openrct2-xp

**Comment by IntelOrca** [comment]
We should do this for VS as well.

**Pull request merged**
