### PR TITLE
Enhanced Transparency Options

### PR DESCRIPTION
**Pull request by IntelOrca**
Superseeds #15214

---

more-see-through

### CODE REVIEW

**Comment by oli414** [comment]
Awesome!

Could these icons be used for the buttons to indicate the visibility mode?

[Icons.zip](https://github.com/OpenRCT2/OpenRCT2/files/8249062/Icons.zip)

They may need to be changed out work well on other background as well but for now this should do.

**Review by Broxzier — COMMENTED** [review]
While testing there were a couple things that stood out to me:

 - The second button - scenery - uses the same icon as the "large scenery" tab from the object selection. This made me assume it was to hide large scenery, with the tab on the left hiding small scenery, which brings me to the second point:
 - The first button hides trees, but not scrubs, bushes, flowers and other plants, which confused me until I read the tooltip. This confusion likely comes from the same assumption and could be discarded. Perhaps an icon that doesn't reflect large scenery only can avoid this.
 - The hotkey to hide peeps no longer toggles staff visibility - it only toggles guest visibility. I'd expect the hotkey to be a quick way to hide/unhide both, taking the guests' current visibility as the current state for staff too.
 - The buttons in the bottom row can be used while they don't really change anything. I think it'd be nice to have them toggle the visibility flag if it's not set already.

None of these remarks are show-stoppers for merging this PR, and can be picked up with a follow-up PR if desired.

**Comment by IntelOrca** [comment]
> The second button - scenery - uses the same icon as the "large scenery" tab from the object selection. This made me assume it was to hide large scenery, with the tab on the left hiding small scenery, which brings me to the second point:

I didn't pick the icons, are you able to suggest a better graphic? If not, maybe we can let the graphics team come up with something along with the visiblity icon.

> The first button hides trees, but not scrubs, bushes, flowers and other plants, which confused me until I read the tooltip. This confusion likely comes from the same assumption and could be discarded. Perhaps an icon that doesn't reflect large scenery only can avoid this.

I am not what people will want this to do. In my opinion it should hide all foliage, but I am not sure we have the object attributes to disguinish this yet apart from `isTree` and `cursor`.

 - The hotkey to hide peeps no longer toggles staff visibility - it only toggles guest visibility. I'd expect the hotkey to be a quick way to hide/unhide both, taking the guests' current visibility as the current state for staff too.

Are you suggesting having three shortcuts, and three menu items for guest, staff and both? To me I feel like hiding guests will be good enough for most cirumstances, in the cases it isn't, the player can tolerate using two separate shortcuts.

**Comment by Gymnasiast** [comment]
I think the hotkey should reflect whatever is in the menu. I.e.: if there are two menu items (one for guests and one for staff), there should be two hotkeys, if there is one, there should be one hotkey. Doing otherwise is just incredibly confusing.

I have no strong feelings as to whether guest and staff should be separate or not.

**Comment by oli414** [comment]
[Icons_2.zip](https://github.com/OpenRCT2/OpenRCT2/files/8292903/Icons_2.zip)

Added a small scenery icon

**Comment by oli414** [comment]
[Icons_3.zip](https://github.com/OpenRCT2/OpenRCT2/files/8292964/Icons_3.zip)

And with a trees icon

**Review by Gymnasiast — APPROVED** [review]
There are considerations, but those can wait AFAIC:

1. Would it be hard to implement a toggle between invisible/seethrough guests/staff? Currently, you can only make them invisible?
2. I think the wording and the window could be improved, but this too can wait.

**Comment by IntelOrca** [comment]
@Gymnasiast

1. Yes, I don't know how useful it would be though.
2. Which wording?

**Comment by Gymnasiast** [comment]
Mostly the labelling of the buttons. Currently they all say "see-through", even when they are set to invisible. But I think it might be better to have a good think about it, and possible combine it with a small redesign of the window. That’s why I think leaving it for another PR is better here.

**Comment by IntelOrca** [comment]
You can raise bugs on this issue tracker.
You can raise feature suggestions on discussions.

**Pull request merged**
