### PR TITLE
Refactor build uploads

### PR DESCRIPTION
**Pull request by janisozaur**
This refactors how builds are uploaded.

All the build jobs now upload to CI and the artifacts are distributed in final job named `Release`. This will include SHA1 sums of artifacts and parsed changelog entries.

For `develop`-based builds, we would need to migrate the repository from https://github.com/janisozaur/OpenRCT2/pull/new/refactor-build-uploads to under our org and create a PAT with contents RW rights. This new repo would have to be updated in the `ci.yml` file, currently pointing at https://github.com/janisozaur/OpenRCT2-binaries-test. This change automatically creates a tag in target repository and creates a release and uploads artifacts there.

For tagged commits, we now create a draft release in this repository and upload artifacts there.

Marking it as draft until binaries repository is migrated.

### CODE REVIEW

**Comment by janisozaur** [comment]
@GingerAdonis please review

**Comment by GingerAdonis** [comment]
> @GingerAdonis please review
Will do so on Monday :)

**Comment by GingerAdonis** [comment]
Why wouldn't we just use this repo and release the builds as a 'pre-release'? Makes more sense, imo

Otherwise LGTM

**Comment by janisozaur** [comment]
I can see one reason why we wouldn't want it this way: it would be hard, both for users and for our scripts, to find previous release in the sea of pre-releases. Personally I quite like the current setup, but I'm open to discussion.

@GingerAdonis since you approved, would you transfer the repo to our org now?

**Comment by GingerAdonis** [comment]
> I can see one reason why we wouldn't want it this way: it would be hard, both for users and for our scripts, to find previous release in the sea of pre-releases. Personally I quite like the current setup, but I'm open to discussion.
> 
> @GingerAdonis since you approved, would you transfer the repo to our org now?

Normally it's combined with only keeping the latest X pre-releases available. But I'm fine with your solution as well.

I'll check if .org can easily switch to a new repo without corrupting existing data.

**Comment by Gymnasiast** [comment]
I'm standing by to change over the .io site if/when that happens.

What does the OpenLauncher do, by the way? Does it directly connect to the old repo, or does it use an endpoint on .org?

**Comment by janisozaur** [comment]
https://github.com/IntelOrca/OpenLauncher/blob/04c15e8e38fa4ca0fa267e2a0dc965fd7e53dafe/src/IntelOrca.OpenLauncher.Core/Game.cs#L9

One more place to be updated.

@GingerAdonis have you checked if it's safe to transfer?

**Comment by GingerAdonis** [comment]
As the .org site relies on hard-coded download URLs for previously parsed data I'd say the best way to more forward is to simply create a new repo for "new" develop builds. And thus not transfer the existing repo.

**Comment by Gymnasiast** [comment]
Normally, GitHub will add a redirect, so that shouldn’t be a problem here.

**Comment by GingerAdonis** [comment]
All right.

Could someone temporarily give me access to the org? "You don’t have the permission to create public repositories on OpenRCT2"

**Comment by janisozaur** [comment]
@GingerAdonis you should be member now

**Pull request merged**
