### PR TITLE
Show amount of peeps still on ride in tooltip when ride is closed (resolves #2708)

### LINKED ISSUE #2708: Closed Rides don't display how many people are on it
This is something I found annoying in RCT2 as well. When you close a ride, for when you want to edit it for example, the ride window does not display how many people are on there. This would be helpful information, since if you forcefully close it the guest's happiness will drop a lot.

### PR DESCRIPTION
**Pull request by Overv**
Showing this in the tooltip seems more convenient than adding it to the window.

### CODE REVIEW

**Comment by janisozaur** [comment]
https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by IntelOrca** [comment]
It was suggested that this was displayed on the customer tab in #2708. Possibly in addition to the tooltip. But given it was @Broxzier 's request, I'll let him comment on this.

**Comment by Broxzier** [comment]
I think changing the status text for closed to include the amount of guests on ride will be enough, so that it's both displayed on hovering over the ride, as well as in the ride window.

**Comment by IntelOrca** [comment]
OK - @Overv could you also make it display the number of guests on the ride on the customer ride tab?

**Comment by Overv** [comment]
Added it:

**Comment by Broxzier** [comment]
Nice, good job! :+1:

**Pull request merged**
