### PR TITLE
Fix window scrollbar not able to navigate to the end of large lists

### LINKED ISSUE #592: Very long object list cannot be scrolled
Since my RCT2 was ten years old when I copied it to OpenRCT2, it should be no surprise I have accumulated a ludicrous amount of plug-in objects (my ObjData contains nearly 7000 files, including the original RCT2 ones). This makes the list of Small Objects in the Scenario Editor so long it's not scrollable any more.

This bug is present in both vanilla RCT2 and OpenRCT2.
(Since I'm probably the only one crazy enough to test OpenRCT2 with a setup like this, I sometimes seem to catch bugs that are hard to reproduce. So if you need a copy of my (1.4 GB) setup, I can provide it.)

### PR DESCRIPTION
**Pull request by ZehMatt**
With 9000+ staff you could only scroll to half of the list while the scrollbar would sit at the end, this fixes the issue by using bigger integer types, the issue was actually an overflow.

Closes #592

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Nice find. Changelog entry?

**Comment by Broxzier** [comment]
Sounds like this fixes one of the oldest issues: https://github.com/OpenRCT2/OpenRCT2/issues/592

**Comment by ZehMatt** [comment]
I was actually looking for an existing issue but I couldn't find it, ill change it entry. Thanks.

**Comment by ocalhoun6** [comment]
Maybe the changelog entry should say `(original bug)` on it? Since #592 was present in vanilla.

**Comment by ZehMatt** [comment]
Considering the original couldn't have that many things in a list its probably OpenRCT2 specific, not exactly a bug either.

**Review by duncanspumpkin — APPROVED** [review]

**Pull request merged**
