### PR TITLE
More Preset Colors for Rides

### PR DESCRIPTION
**Pull request by 733737**
Added lots of color presets to most coasters and other rides in the game

### CODE REVIEW

**Comment by karst** [comment]
Can you give a list of rides you based the colour presets off?

**Comment by 733737** [comment]
I based it off of your PR for flying coaster, and the presets already in game

**Comment by karst** [comment]
Ah i see, i based the three i added on real coasters. And only three more. I noticed you added alot to some coasters which is OTT imo. I'll let others decide on this though. IMO if we'd implement more presets they should all be crafted each and be based on an existing ride irl.

It's also slightly pointless currently as the presets field is currently apparently broken.

**Comment by SpartanFrederic104** [comment]
Yeah, I wonder how the presets field is broken and what the culprit is in this case.

**Comment by 733737** [comment]
it is broken?

**Comment by 733737** [comment]
if it were fixed, I don't see the harm in copying the unrealistic presets from rct1 and rct2 because it's not as if they weren't already there on other rides. Surely the wooden coaster presets already in the game are an eyesore, and I'm not suggesting we change or remove them

**Comment by 733737** [comment]
If there was a function to randomly pick a color for each of the 3 fields, that would be preferable IMO

**Review by Broxzier — CHANGES_REQUESTED** [review]
I don't think this PR adds anything useful. The presets already provice some controlled randomness (although biased, a fix for that is ready). If you want real randomness, that seems more fit for a plug-in. Just let it listen to "ridecreate" action, and update the colours then.

**Comment by Gymnasiast** [comment]
Yeah, I would agree this PR in its current form is not really a good addition.

Having said that, I’m certainly not against adding a few more here and there (especially if those are used in real-life installations), and perhaps removing/fixing some of the really ugly ones. But all of that is on a much smaller scale than adding a bunch to every type.

**Comment by ocalhoun6** [comment]
> If there was a function to randomly pick a color for each of the 3 fields, that would be preferable IMO

Randomization could produce some really ugly color combinations, especially on rides like the wooden coaster, where (most of the time) any support color besides white or shades of brown tends to look terrible.

**Pull request closed without merging**
