### PR TITLE
Stop using (void*)-1 for invalid pointers.

### PR DESCRIPTION
**Pull request by Chaosmeister**
Use NULL/nullptr instead. This removes the need for guarding against (void*)-1.
Improve code readability by:
* using Memory::Set() instead of for-loop.
* using Macros instead of Numbers.
* using while-loops instead of do-while-loops.

### CODE REVIEW

**Comment by janisozaur** [comment]
You need to rebase this.

See also https://github.com/OpenRCT2/OpenRCT2/issues/5037

This needs to be verified if it doesn't break saves loading in vanilla.

**Comment by janisozaur** [comment]
There's also lots of non-conforming, unnecessary style changes that inflate this PR. Can you please remove them?

**Comment by duncanspumpkin** [comment]
Won't this break RCT2 builds?

**Comment by duncanspumpkin** [comment]
As this is likely to cause bugs it would have been better to split it into multiple commits so that the refactoring, modifying game logic, changing constants is not all in one commit.

**Comment by Chaosmeister** [comment]
@duncanspumpkin I think it's quite likely that I missed some guards. 😅

**Comment by IntelOrca** [comment]
This removes the checks for `-1` but does not ensure that they won't be `-1`.

**Comment by Chaosmeister** [comment]
Converting all entries to nullptr is implemented. Converting back to -1 not

**Comment by IntelOrca** [comment]
> Converting back to -1 not

@Chaosmeister Please do this, otherwise it RCT2 vanilla will crash when loading a saved game from OpenRCT2.

**Comment by Chaosmeister** [comment]
ah reading from -1 and writing to -1 had been implemented. If there are some crazy people out there who want to try this out. I'm not getting any crashes.

**Comment by Gymnasiast** [comment]
I'm going to take this in, but only bit by bit, since this can get messy. There is also TestPaint to consider.

**Comment by Gymnasiast** [comment]
I have rebased this. I also removed a handful of changes this PR made that were not related to -1 pointers.

**Comment by Chaosmeister** [comment]
Cool, I alread wrote this patch off and almost forgot about it. 
Tell me if I can be of service somehow.

**Pull request merged**
