### PR TITLE
Remove more gotos in Vehicle.cpp

### PR DESCRIPTION
**Pull request by Gymnasiast**
This cherry-picks the first 10 commits from https://github.com/OpenRCT2/OpenRCT2/pull/18926, as I was able to verify them up until here. After this PR is merged, I intend to check/update the other five.

Reviewing note: I recommend viewing the commits one by one and using the option to ignore whitespace.

**Do not squash merge!**

### CODE REVIEW

**Review by tupaschoal — COMMENTED** [review]
Some of these seem weird, I'm not 100% sure the code should follow that path, but overall it seems fine. Got to check the bpb100 test

**Comment by Gymnasiast** [comment]
It took some time, but I finally had time to bisect and find the culprit.

**Review by tupaschoal — APPROVED** [review]
Seems to make sense, some of the things could have been extracted into functions, specially on later commits, but I guess the patterns will show up themselves, I'd rather move towards having no `goto`s first.

**Review by Broxzier — APPROVED** [review]
This does introduce many duplicate lines of code, but the removal of the goto statements is definitely an improvement.

**Comment by Gymnasiast** [comment]
Very true - the point was to get rid of the gotos first, in a way that was easy to check, which makes refactoring much easier to begin with.

**Pull request merged**
