### PR TITLE
Fix #11914: Clear NewsItemQueues on news item init

### LINKED ISSUE #11914: Starting a new scenario results in a spam of "New ride/scenery/vehicle researched" messages
**OS:** Windows 10
**Version:** 0.2.6
**Commit/Build:** c2322d7

This is a new issue (albeit a non-gamebreaking and minor one) that can occur when you start up a new scenario. As soon as you start a new scenario, you will immediately be greeted with new ride/scenery/vehicle researched messages, with the number equal to the total amount of the scenario's pre-invented rides, shops/stalls, and scenery groups (the maximum is 147 (128 + 19)). I have tested this multiple times, and it happens with every scenario, not just custom ones. The messages will also show a random date (the date is the same for each mesage). This bug does not currently exist in the stable release of the game, nor did it exist in previous versions. It also doesn't happen when you load up a saved game.

- Reproducible in RCT2 (vanilla)? No
- Specific to multiplayer? No

**Steps to reproduce:**
1. Start up the game, as normal.
2. Select New Game and then start up a new scenario (can be any, either base game scenarios or custom ones).
3. As soon as you select a scenario and start it up, the first thing you will immediately see at the bottom of the screen should be either "New ride/attraction now available: X", "New scenery/themeing now available: X", or "New vehicle now available for X: Y". You will have to repeatedly click on the message bar to clear the spam of messages from it.

**Screenshots / Video:**
Ice Castle 2020-06-08 16-35-05

### PR DESCRIPTION
**Pull request by hdpoliveira**

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
Looks good can you ammend your commit message so that it reads "Fix #11914: ...."

**Comment by Gymnasiast** [comment]
@duncanspumpkin I fixed the commit message on squash-merge.

**Comment by hdpoliveira** [comment]
Thank you @Gymnasiast ! @duncanspumpkin Sorry I didn't see your comment on time.

**Comment by duncanspumpkin** [comment]
Pretty sure gym commented after it was merged. We like to comment on the source of issues so the original author knows about it.

**Pull request merged**
