### PR TITLE
Rename ride_set_block_points to ride_open_block_brakes

### PR DESCRIPTION
**Pull request by manuelVo**

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
Could you title case the function whilst you are at it.

**Comment by manuelVo** [comment]
The function isn't part of a struct. Should the name still be title-cased?

**Comment by duncanspumpkin** [comment]
Yes, all functions should be TitleCase we used snake case when we first implemented everything in C before we decided on a coding style.

**Comment by manuelVo** [comment]
Done

**Review by duncanspumpkin — APPROVED** [review]

**Pull request merged**
