### PR TITLE
Use vertical tabs in the New Game dialog

### PR DESCRIPTION
**Pull request by Gymnasiast**
This layout is more space-efficient and allows for adding more tabs (which is best left to another PR).

Screenshot (RCT2 theme):
Diamond Heights 2022-08-08 22-52-28

Screenshot (RCT1 theme):
Diamond Heights 2022-08-08 22-39-08

Also adds a hint about what to do (I can remove it if desired) and fixes the background behaving like a big button.

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Could you add a screenshot of what this looks like in Japanese and Korean?

While I like the idea, personally, I would really prefer for this layout to be optional.

**Comment by Gymnasiast** [comment]
Japanese:

afbeelding

Korean:

afbeelding

Making it optional is not going to happen I’m afraid. We cannot fit any additional tabs in the current window without making it hideously wide or (worse) adding a second row, and we want to add those.

**Comment by karst** [comment]
I think the RCT1 looks perfect and well with the original game, but I think the RCT2 theming might look better like this: 
image

**Comment by ocalhoun6** [comment]
If you're redesigning this window anyway, maybe also think about making some accommodation for #17691?

Maybe not the whole preview image saving and loading system yet ... but putting some thought into where on this window the preview image would go and preparing a space for it.

**Comment by karst** [comment]
Although I do think that'd be a great addition to the game I don't think that should be something for this PR.

image

The black square here would be a good location if that gets implemented.

**Comment by Gymnasiast** [comment]
@karst This is how the window looks in RCT2:

afbeelding

I’ll keep the grey background.

@ocalhoun6 I am not going to expand the scope of this, otherwise it will never get merged. Previews will be done in their own time.

**Comment by karst** [comment]
ah my apologies, I didn't realize this as my menu screen is full ^^; You are right, there's one stripe of grey at the edges that I hadn't noticed.

**Comment by IntelOrca** [comment]
Can you show how it looks when you have more tabs, enough to overflow the window? How do you select ones that are hidden?

**Comment by AaronVanGeffen** [comment]
> Japanese:
> Korean:

Thanks for those screenshots. For Japanese in particular, it doesn't look worse than the current, horizontal tabs. Text wrapping for Japanese has never looked that great/natural in game; we really need to implement better heuristics for CJK, I think.

> Making it optional is not going to happen I’m afraid. We cannot fit any additional tabs in the current window without making it hideously wide or (worse) adding a second row, and we want to add those.

Understandable. Tangentially related, do you intend to continue supporting the old-style difficulty tabs, as opposed to source game? This might be a good time to drop that option.

**Comment by Gymnasiast** [comment]
> Can you show how it looks when you have more tabs, enough to overflow the window? How do you select ones that are hidden?

It doesn’t currently do anything special to handle these. Some possibilities are:
- Employ the scenery window solution
- Show a dropdown if there are too many tabs
- Add scroll buttons (just buttons and no bar)

Unless we would add support for custom scenario lists, I doubt we’d need more than a few extra positions anyway.

> do you intend to continue supporting the old-style difficulty tabs

I don’t know how many people use these. At this point, it doesn’t seem like a particular burdensome feature to support.

**Comment by IntelOrca** [comment]
A simple solution (even without changing the tab orientation) is to have a dropdown that changes the selection of tabs. For example you could have different dropdown items for RCT1, RCT2, OpenRCT2, Other, and custom groupings / campaigns.

**Comment by karst** [comment]
image_2022-08-09_183645192
There's also the RCTC scenario lists. I don't know if we want to use those, but it's also a list we could keep in mind

**Comment by Broxzier** [comment]
> - Employ the scenery window solution

You mean like a question/miscellaneous tab that lists all other scenario's?

> - Show a dropdown if there are too many tabs

Not too keen on this idea. Dropdowns can easily be overlooked.

> - Add scroll buttons (just buttons and no bar)

I would vote for this.

---

Another option is to make something like the ride window, where you first pick the base game/pack (like picking a ride), then a scenario (like picking a track design).

**Comment by Gymnasiast** [comment]
@karst There is already an issue for that IIRC, and I want to keep the scope of this PR small.

> > Employ the scenery window solution
>
> You mean like a question/miscellaneous tab that lists all other scenario's?

No, I meant making the window larger if there are more than X scenario groups (like the Scenery window does when there are more than 20 tabs).

**Comment by IntelOrca** [comment]
> I get the feeling this PR is suffering from extensive bikeshedding. Can we please get back on track?

I am not sure what the benefit of changing the orientation is unless it can also cope with many / overflowing tabs.

**Comment by Gymnasiast** [comment]
> > I get the feeling this PR is suffering from extensive bikeshedding. Can we please get back on track?
> 
> I am not sure what the benefit of changing the orientation is unless it can also cope with many / overflowing tabs.

It can cope with two or three more tabs, which is as many as we’ll need to add the most common scenario packs.

**Comment by 733737** [comment]
if this PR is merged, I'd like OpenScenarios to be there, as putting them into the main release will make them more important to be polished, expanded, and played. Right now OpenScenarios is stale.

**Review by duncanspumpkin — APPROVED** [review]

**Pull request merged**
