### PR TITLE
Show latest player action in player list window

### PR DESCRIPTION
**Pull request by samdroid-apps**
On multiplayer servers, there is a complete lack of accountability
for WHO is doing actions.  Even though the server owners can kick
people, they often end up kicking the wrong person, and blaming
people based on timing of actions vs joining.

This adds a field to the players list window showing what was the
last type of game command they sent.  While this could be imporved
(what did they delete exactly?  where did they landscape?) it is
an imporvement over timing based guesses.

NOTE1:  This doesn't deal with the localisation.  How should I do that?  Add a string id for everything?  If so, how do I get the localized version of that string?

NOTE2:  This will probably need to be rebased when the amazing #2783 is merged, but other than a few merge conflicts, I believe that these patches address separate issues?

### CODE REVIEW

**Comment by samdroid-apps** [comment]
This patch is completely client side, so if you run it you can join existing servers.  Here is an example of me doing it on the "Meme Zone" server:

screenshot from 2016-01-23 13-36-04

**Comment by zsilencer** [comment]
good idea, i was thinking of creating another tab in the new player window that shows a log of the last few commands someone ran, similar to recent peep thoughts.

**Comment by LRFLEW** [comment]
This is certainly useful, but if there could be a "complete" log (and even a log that writes to a file), it could be even better.

**Comment by IntelOrca** [comment]
This will conflict very badly with #2783.

**Comment by zsilencer** [comment]
i just added this feature to my pull request

**Comment by samdroid-apps** [comment]
Awsome!  Closing patch as @zsilencer implemented localisation, etc.

**Pull request closed without merging**
