### PR TITLE
Fix #4959: Compiler warning: tmpnam

### LINKED ISSUE #4959: Compiler warning: tmpnam
We need to sort this warning out at some point.

```
CMakeFiles/openrct2.dir/src/network/http.cpp.o: In function `http_download_park':
http.cpp:(.text+0x734): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
```

### PR DESCRIPTION
**Pull request by OlivierWathgen**
Replace tmpnam with mkstemps
Temporary file has prefix "openrct2park"

### CODE REVIEW

**Comment by OlivierWathgen** [comment]
I only tested this on OS X (10.12.2)

**Comment by Gymnasiast** [comment]
Hm, this doesn't work on Linux or Windows, as every build fails, with the exception of the macOS/Xcode one and the one without network support (for obvious reasons). It seems to choke on quite a lot:

```
src\network\http.cpp(305): error C2065: 'P_tmpdir': undeclared identifier [C:\projects\openrct2-ject9\openrct2.vcxproj]
src\network\http.cpp(305): error C2143: syntax error: missing ';' before 'string' [C:\projects\openrct2-ject9\openrct2.vcxproj]
src\network\http.cpp(312): error C3861: 'mkstemps': identifier not found [C:\projects\openrct2-ject9\openrct2.vcxproj]
src\network\http.cpp(320): error C2065: 'F_GETPATH': undeclared identifier [C:\projects\openrct2-ject9\openrct2.vcxproj]
src\network\http.cpp(320): error C3861: 'fcntl': identifier not found [C:\projects\openrct2-ject9\openrct2.vcxproj]
src\network\http.cpp(332): error C3861: 'close': identifier not found [C:\projects\openrct2-ject9\openrct2.vcxproj]
src\network\http.cpp(328): warning C4996: 'fdopen': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _fdopen. See online help for details. [C:\projects\openrct2-ject9\openrct2.vcxproj]
```

**Comment by AaronVanGeffen** [comment]
F_GETPATH appears to be very much a macOS concept — it's not defined on Linux or Windows. The latter is apparently missing more functions along with this.

Perhaps we should introduce platform functions for handling temporary files?

**Comment by LRFLEW** [comment]
I feel like this is a symptom of a different problem. Is a temporary file really needed? It seems like reworking some things to load directly from RAM would be a cleaner solution. I'll look into this when I have time.

**Pull request closed without merging**
