### PR TITLE
Fix 20866: Boosters for the Mini and B&M track are swapped

### PR DESCRIPTION
**Pull request by karst**
Fix for #20866

### CODE REVIEW

**Comment by karst** [comment]
I wish editting commit messages would just be easy..........

**Comment by ZehMatt** [comment]
> I wish editting commit messages would just be easy..........

It's quite easy with git rebase -if HEAD~<commit count>

**Comment by karst** [comment]
yea i figured it out haha, but i wish the desktop app had a force push button

**Comment by spacek531** [comment]
Can you add a network bump? it didn't get merged.

**Review by duncanspumpkin — APPROVED** [review]

**Pull request merged**
