### PR TITLE
Round tweened positions rather than truncate them

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
Can you at least provide some reason why you would do this

**Comment by ZehMatt** [comment]
I think rounding eliminates the purpose of tweening/smoothing.

**Comment by ZehMatt** [comment]
My guess is because of this: https://onlinegdb.com/Syg9CP9EM

**Comment by IntelOrca** [comment]
The commit should say why the change was made.

**Comment by Gymnasiast** [comment]
@janisozaur Could you make the commit message clearer?

**Pull request merged**
