### PR TITLE
Fix guest inventories crashing on particular items

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
Regression from #23415

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Is there any way to make it not crash in scenarios like this? I’d prefer if our game didn’t have a seizure when a malformed string/formatter comes along.

**Comment by AaronVanGeffen** [comment]
> Is there any way to make it not crash in scenarios like this? I’d prefer if our game didn’t have a seizure when a malformed string/formatter comes along.

Unfortunately, the formatter is playing with fire here. These labels use string pointers for the park name, so if that pointer isn't set in the right position, well...

**Comment by Gymnasiast** [comment]
Right, it’s not a simple null check, I gather?

Should we perhaps copy strings for the formatter, and reduce this playing with fire to just playing with sambal?

**Review by Gymnasiast — APPROVED** [review]

**Comment by AaronVanGeffen** [comment]
> Right, it’s not a simple null check, I gather?

Unfortunately not. In this case, there was a non-zero pointer, it just pointed to a nonsensical address.

> Should we perhaps copy strings for the formatter, and reduce this playing with fire to just playing with sambal?

It would help if our formatters actually owned their memory, rather than relying on one 'common format args'. In OpenLoco, we refactored widgets such that they all have their own bit of formatting memory. It's a lot of refactor work, but I think we should move towards that for OpenRCT2 as well.

**Pull request merged**
