### PR TITLE
Move water coaster source to coaster directory

### PR DESCRIPTION
**Pull request by IntelOrca**
Requires xcode fix...

### CODE REVIEW

**Comment by IntelOrca** [comment]
Requires xcode fix...

**Comment by marijnvdwerf** [comment]
Why? The ride also shows up on the `Water Rides` tab.

**Comment by IntelOrca** [comment]
@marijnvdwerf it also shows up on coaster tab. Its primary ride category is water.

**Comment by marijnvdwerf** [comment]
For me it also shows up there on both tabs.

**Pull request closed without merging**
