### PR TITLE
Fix some warnings

### PR DESCRIPTION
**Pull request by Gymnasiast**
Please take a good look.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Any comment or reason why it hasn't been merged?

**Comment by IntelOrca** [comment]
image

**Comment by Gymnasiast** [comment]
When I opened the PR, there were no merge conflicts. Those are here because you left it unmerged without commenting on it for so long.

**Comment by IntelOrca** [comment]
If I remember rightly, there was some discussion about whether some of those casts were correct in gitter.

**Comment by Gymnasiast** [comment]
Yes, I had a discussion with Duncan about this on Gitter, who left it to you to decide, IIRC.

**Comment by IntelOrca** [comment]
I don't know whether this might cause issues or not either.

**Pull request merged**
