### PR TITLE
Fix #21908: Errors showing up when placing/moving track design previews

### LINKED ISSUE #21908: Uncap FPS causes a red error to pop up: "Unable to change ride operating mode"
### Operating System

Windows 11 64 Bit

### OpenRCT2 build

OpenRCT2, v0.4.10-101-gbe9f1a2 (be9f1a2 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

_No response_

### Describe the issue

So I have bene ecountering a weird issue where it tells me  Unable to change ride operating mode. I have narrowed it down to uncap fps causing the issue.

### Steps to reproduce

Open up any park. Open any rollercoaster or track based ride and select a prefab and move it around map with uncap fps on and off.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by ZehMatt**
~~Also took the liberty to correct the console spam~~, game action queries shouldn't really report errors as the name it implies its just a query so its allowed to fail, we should look at the other game actions to also correct this at some point, if it fails in Execute then we should definitely report errors as you are not supposed to call Execute if Query fails.

Closes #21908

### CODE REVIEW

**Comment by mrmbernardi** [comment]
You may as well remove the same error message in the large scenery query:  https://github.com/OpenRCT2/OpenRCT2/blob/7f46cc8bd09df9e207d915b00b34537c5563c837/src/openrct2/actions/LargeSceneryRemoveAction.cpp#L67

**Comment by ZehMatt** [comment]
> You may as well remove the same error message in the large scenery query:
> 
> https://github.com/OpenRCT2/OpenRCT2/blob/7f46cc8bd09df9e207d915b00b34537c5563c837/src/openrct2/actions/LargeSceneryRemoveAction.cpp#L64-L70

I think we best tackle this in another PR, I can remove the commit in this PR, there will be most likely quite a few game actions where we have plenty error logging in Query.

**Comment by Basssiiie** [comment]
Tested it! The invalid ride error seems to be fixed, but I still get the `SmallSceneryRemoveAction::Query` error in console when rapidly moving a ride design near the park's edge.

https://github.com/user-attachments/assets/9e2ed9df-6fdb-47fc-9fc4-c9d714474557

One of the errors:

```
ERROR[D:\a\OpenRCT2\OpenRCT2\src\openrct2\actions\SmallSceneryRemoveAction.cpp:105 (SmallSceneryRemoveAction::Query)]: Small scenery of type 169 not found at x = 448, y = 3456, z = &d
```

Also sidenote nitpick: the `z = &d` in this error message is not correctly resolving the `&d` variable either. 😅

**Comment by ZehMatt** [comment]
> Tested it! The invalid ride error seems to be fixed, but I still get the `SmallSceneryRemoveAction::Query` error in console when rapidly moving a ride design near the park's edge.
> 
>  2024-08-05.21-20-30.mp4 
> One of the errors:
> 
> ```
> ERROR[D:\a\OpenRCT2\OpenRCT2\src\openrct2\actions\SmallSceneryRemoveAction.cpp:105 (SmallSceneryRemoveAction::Query)]: Small scenery of type 169 not found at x = 448, y = 3456, z = &d
> ```
> 
> Also sidenote nitpick: the `z = &d` in this error message is not correctly resolving the `&d` variable either. 😅

Thanks, as for the console spam this PR is not going to address this but I'll look into cleaning that up afterwards, its not an actual error so its safe to ignore for time being.

**Review by Basssiiie — APPROVED** [review]
In that case, testing-wise I don't see any further issues. The original ride invalid error doesn't pop up anymore and there doesn't seem to be any new issues with track designs. 🙂

**Review by Gymnasiast — APPROVED** [review]

**Pull request merged**
