### PR TITLE
Update objects release to v0.4.10

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Review by tupaschoal — APPROVED** [review]
Are all changelog entries in already?

**Comment by Gymnasiast** [comment]
They are, yes.

**Comment by ZeeMaji** [comment]
Screenshot at 2024-11-02 15-52-26
Unsure if it's specific to this PR, but cradle of civilization from TT is showing up under the other parks tab with it's vanilla name.

**Comment by ZeeMaji** [comment]
The RCT1 parks which had their text object names changed seem to be working as expected.

**Comment by ZeeMaji** [comment]
This probably needs import code added for converting the old custom versions of the lsm trains to the new officially included lsm trains?

**Comment by SpartanFrederic104** [comment]
> Screenshot at 2024-11-02 15-52-26 Unsure if it's specific to this PR, but cradle of civilization from TT is showing up under the other parks tab with it's vanilla name.

Is it because of the US English language setting?

**Comment by ZeeMaji** [comment]
It remains even when changing to UK English, or any other language.

**Comment by AaronVanGeffen** [comment]
> Unsure if it's specific to this PR, but cradle of civilization from TT is showing up under the other parks tab with it's vanilla name.

Confirmed not caused by this PR. Happens on my local build as well (still on b9345a1ec8).

**Comment by ZeeMaji** [comment]
Well then, i'll create an issue for it.

**Comment by karst** [comment]
Conversion code for X7's old vehicle available? Can't check this on phone atm.

**Comment by Gymnasiast** [comment]
> This probably needs import code added for converting the old custom versions of the lsm trains to the new officially included lsm trains?

Since even .park saves by `originalId` if it is present, I think that is already handled. I would need to verify that with an old save, though. I have asked Karst for one.

**Review by karst — APPROVED** [review]
[Testpark for LSM Train.zip](https://github.com/user-attachments/files/17608662/Testpark.for.LSM.Train.zip)

**Review by ZeeMaji — APPROVED** [review]

**Pull request merged**
