### PR TITLE
Refactor clear command to game action

### PR DESCRIPTION
**Pull request by IntelOrca**

### CODE REVIEW

**Comment by Broxzier** [comment]
The client freezes as soon as it tries to remove an object. When the server clears an object, the client handles it okay though.

It also seems to count each object that gets removed as a new action. I'm not sure if that's intended. The land tool for example, increases the number of actions by only one when raising multiple tiles.

**Comment by IntelOrca** [comment]
Thanks for testing.

> It also seems to count each object that gets removed as a new action. I'm not sure if that's intended. The land tool for example, increases the number of actions by only one when raising multiple tiles.

This might be a side effect of using do_game_command inside the action which I can't avoid yet. I will see if I can find a solution.

**Comment by ZehMatt** [comment]
Its one of the reasons I'm currently only porting unreferenced ones for now, I have a full list here: https://github.com/OpenRCT2/OpenRCT2/issues/6327#issuecomment-355758468 
Maybe it somehow helps planning this, I somewhat wish I would have done this earlier given my past mistakes :p

**Comment by AaronVanGeffen** [comment]
Testing this PR, there's a regression with clearing paths. When clearing paths exclusively, the paths are cleared as expected. However, when clearing small or large scenery as well, only the scenery is cleared, not the paths.

**Comment by IntelOrca** [comment]
@AaronVanGeffen I don't think I can finish this until the sub-commands are complete, but thanks for trying it.

**Comment by IntelOrca** [comment]
Closing for reason mentioned above.

**Pull request closed without merging**
