### PR TITLE
Fix ferris wheel rotating one extra time (fixes #2918)

### LINKED ISSUE #2918: Incorrect number of rotations in Ferris Wheel
If you set number of rotations with "1" the Ferris Wheel rotate two times (not one), if you set the number of rotations with "2" the Ferris Wheel rotate three times (not two) ... (see https://vid.me/VyYj)

In vanilla game this problem not happen.

### PR DESCRIPTION
**Pull request by Overv**
Comparison is now a `<` like the other rides.

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
I want to check this against the vanilla function but you are probably correct

**Comment by duncanspumpkin** [comment]
I think i've made a mistake in the implementation of this function from looking at it again it should be:

```
if (subState == vehicle->var_1F) {
  		bool shouldStop = true;
  		if (ride->status != RIDE_STATUS_CLOSED) {
 			if (vehicle->var_CE <= ride->rotations)
  				shouldStop = false;
  		}
  
 		if (shouldStop) {
 			ferris_wheel_var_0 = vehicle->ferris_wheel_var_0;
 			vehicle->ferris_wheel_var_0 = -abs(ferris_wheel_var_0);
                        vehicle->ferris_wheel_var_1 = abs(ferris_wheel_var_0);
 		}
 	}
```

Although that wouldn't change the wheel rotating one too many times. Are we sure this worked correctly in the vanilla. I wouldn't be that bothered but I don't want to end up hiding another bug by making this change.

**Comment by Overv** [comment]
I've just tested it and it is working correctly in Vanilla. Are you 100% sure the ferris wheel code uses a `jle` instead of a `jb`, which the other rides use?

**Comment by duncanspumpkin** [comment]
it does a `ja` which i inverted to a `<=`. I must have made a mistake earlier in the function.

**Comment by duncanspumpkin** [comment]
AHH figured it out. My comparison is the wrong way around. It should have been `ride->rotations > vehicle->var_CE` then `shouldStop = false`.

Can you add in the line `vehicle->ferris_wheel_var_1 = abs(ferris_wheel_var_0);` and this will be ready to merge.

**Comment by Overv** [comment]
@duncanspumpkin Done.

**Comment by Wirlie** [comment]
Thanks! :) its work

**Pull request merged**
