### PR TITLE
Fix #10468: Ride Entrance/Exit not buildable above a certain height level

### LINKED ISSUE #10468: Ride's Entrance/Exit is not buildable above a certain height level
**OS:** Windows 10
**Version:** 0.2.4
**Commit/Build:** 98110c0

I can't build the entrance/exit of a ride which is at height equals or more than 9.
If it is at height +8, I can build entrance/exit of it. But if it is at +9, I can't.

**Steps to reproduce:**
1. Build any ride platform at the height >= 9
2. Point the mouse cursor next to the ride to build the entrace or exit
3. The ghost entrance/exit is not displayed

**Screenshots / Video:**
b
(I disabled the support limits to show you this issue, but it doesn't matter if it is enabled or not)

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by tupaschoal** [comment]
Was it blowing up the `uint8_t`? 🤔

**Comment by Gymnasiast** [comment]
Yes. It suddenly had to hold 8 times the old value, overflowing at 255big = 31small = +8 = +12 metres.

**Comment by tupaschoal** [comment]
This got me a bit worried, with our recent changes, but I guess most of the usages are int16_t at least, right ?

**Comment by duncanspumpkin** [comment]
Oh I did actually notice this and thought it would be fine. Not sure why I thought that.

**Pull request merged**
