### PR TITLE
Re-classify 4 LL scenarios as expert

### PR DESCRIPTION
**Pull request by xrgtmx**
Adjust difficulty categories for Loopy Landscape scenarios:
- Southern Sands
- Tiny Towers
- Nevermore Park
- Pacifica

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
This is your first contribution to OpenRCT2. Have these changes been discussed elsewhere prior to this PR?

**Comment by xrgtmx** [comment]
I've posted about it here:
https://github.com/OpenRCT2/OpenRCT2/discussions/21377

Nowhere else, though.

**Comment by ZehMatt** [comment]
Having one user for feedback on that discussion doesn't seem like a lot, I think it would be good to have a few more people jump in on it. Rating the difficulty of scenarios is probably pretty subjective, depending on who you ask you will most likely get mixed answers, I'm not opposed of changing it if people think it makes sense.

**Comment by Gymnasiast** [comment]
I’d like to see this discussed on the Discord first. I’ve therefore put it in draft until that point. (Normally we’d close it, but I’m willing to cut you some slack here.)

**Comment by xrgtmx** [comment]
I've made a discussion on the OpenRCT2 discord, hopefully there will be more opinions and input regarding this cosmetic change. It's minor and not too important, but I figured I'd let you all know.

**Comment by xrgtmx** [comment]
Closing this specific pull request; updating with a new one.

**Comment by tupaschoal** [comment]
> Closing this specific pull request; updating with a new one.

Please avoid doing that when you'll keep working on the same stuff, you can always update existing PRs and edit the original text or add comments.

**Comment by Gymnasiast** [comment]
^ That. Never create a new PR unless the old has become _really_ irrelevant or otherwise unfeasible. Also means that people who are subscribed will get notified properly.

**Comment by xrgtmx** [comment]
Rookie mistake on my part. Reopened this PR, will update the new one with just the Wacky World change.

**Comment by ZeeMaji** [comment]
The change is sensible to me as discussed in the initial discussion.

**Review by ZeeMaji — APPROVED** [review]

**Comment by ZehMatt** [comment]
I think this warrants a changelog entry.

**Review by Gymnasiast — APPROVED** [review]

**Review by tupaschoal — APPROVED** [review]

**Pull request merged**
