### PR TITLE
Skip closing network if already closed

### LINKED ISSUE #2203: Segfault on exiting
When quitting OpenRCT2 (from the intro screen is enough) I always get a segfault in gdb:

```
Program received signal SIGSEGV, Segmentation fault.
0x080febae in gfx_invalidate_screen () at /home/jh/src/OpenRCT2/src/drawing/drawing.c:187
187		int width = RCT2_GLOBAL(RCT2_ADDRESS_SCREEN_WIDTH, uint16);
(gdb) backtrace
#0  0x080febae in gfx_invalidate_screen () at /home/jh/src/OpenRCT2/src/drawing/drawing.c:187
#1  0x08191580 in Network::Close (this=0x82803c0 <gNetwork>) at /home/jh/src/OpenRCT2/src/network/network.cpp:423
#2  0x08191433 in Network::~Network (this=0x82803c0 <gNetwork>, __in_chrg=<optimized out>) at /home/jh/src/OpenRCT2/src/network/network.cpp:379
#3  0xf7a54aa3 in __run_exit_handlers () from /lib/libc.so.6
#4  0xf7a54aff in exit () from /lib/libc.so.6
#5  0x080b7bbb in openrct2_launch () at /home/jh/src/OpenRCT2/src/openrct2.c:311
#6  0x080dcacf in main (argc=1, argv=0xffffd604) at /home/jh/src/OpenRCT2/src/platform/linux.c:55
```

### PR DESCRIPTION
**Pull request by janisozaur**
Fixes #2203

### CODE REVIEW

**Comment by zsilencer** [comment]
maybe would be simpler to just remove call to gfx_invalidate_screen? because I do not think it is necessary

**Comment by IntelOrca** [comment]
Why not have gfx_invalidate_screen check if the screen has been disposed?

**Comment by janisozaur** [comment]
@IntelOrca I think ideally all components should follow that rule. I can add the check to `gfx_invalidate_screen` too

**Comment by janisozaur** [comment]
That was the least intrusive option I could find. Also makes sure that the exit code is 0 when it should be.

**Comment by duncanspumpkin** [comment]
change `cmdline_for_sprite` to use sensible error codes is what I want instead of that.
and `cmdline_for_screenshot`
and `cmdline_for_test, cmdline_for_test_error`
those functions at present will set `gExitCode` to 1 or -1 when it should be 0 or anything else

**Comment by janisozaur** [comment]
After inspecting them closer, I think I'd rather stick with the current version of the code. Current design allows using various commands which can return three different values:
- success, start the game (`gExitCode == 0`), see `cmdline_for_none`
- success, no need to start the game (`gExitCode > 0`), see `cmdline_for_sprite`
- failure (`gExitCode < 0`), see `cmdline_for_sprite`

To refactor, I could make each function set `gExitCode` explicitly and only return `true`/`false` meaning if game should be started or not, but I'd argue this would be worse design.

**Comment by duncanspumpkin** [comment]
Okay if thats the case can you add a comment to the `gExitCode` part in `cmdline_run` explain this.

**Comment by janisozaur** [comment]
updated

**Pull request merged**
