### PR TITLE
Remove old Linux workarounds

### PR DESCRIPTION
**Pull request by janisozaur**
Verified working on my machine. Possibly related to recent asm changes.

### CODE REVIEW

**Comment by janisozaur** [comment]
Although this now works, it trips debugger. Please don't merge yet.

Linux builds seems to work fine without 0x0040701D, is it required? What does it do?

**Comment by IntelOrca** [comment]
@janisozaur what is happening with this?

**Comment by janisozaur** [comment]
I updated the change and seems to work fine, but I'd like for someone else to test as well.

**Comment by IntelOrca** [comment]
We don't need to call 0x0040701D anymore.

**Comment by janisozaur** [comment]
I removed the call to this code along with the comment, is this ok now?

**Pull request merged**
