### PR TITLE
Fix bad tooltip for the number of circuits

### PR DESCRIPTION
**Pull request by octaroot**
Ride circuit number select box arrows had incorrect tooltip displayed and the correct one was not present at all. So I added it.

I used one of the `<not used anymore>` strings in order to lower the chances of colliding string_ids

screen_bad_tooltip

### CODE REVIEW

**Comment by IntelOrca** [comment]
You don't need to add another string ID, you just need to change it to `STR_NUMBER_OF_CIRCUITS_TIP`.

**Comment by octaroot** [comment]
But that's the tooltip for the label "Number of circuits:", not for the select box

**Comment by IntelOrca** [comment]
Why does a label need a tooltip?

**Comment by IntelOrca** [comment]
Nevermind, I don't think its a big deal

**Comment by Gymnasiast** [comment]
It was a bad idea to use an older number, as it prevents automatic fallback to UK English. This shouldn't have been merged as it was.

**Comment by IntelOrca** [comment]
@Gymnasiast All the languages should have those unused strings removed from them.

**Comment by Gymnasiast** [comment]
And they haven't, because OpenRCT2 didn't handle missing strings with IDs lower than 5120 properly in the past.

**Pull request merged**
