### PR TITLE
New weather type snow

### PR DESCRIPTION
**Pull request by brettpenzer123**
GitHub is confusing me. I'm trying to sync a commit from OpenRCT2/OpenRCT2 to brettpenzer123/OpenRCT2 but it fails to sync. I can't pull request from GitHub desktop either so I just hope this is correct.

### CODE REVIEW

**Comment by janisozaur** [comment]
@brettpenzer123 please rebase your commits on top of current `develop` branch

**Comment by brettpenzer123** [comment]
Dude GitHub is officially broke. I've been trying to make this pull request without the other merges but it won't happen.

**Comment by janisozaur** [comment]
GitHub has nothing to do with your issue.

**Comment by brettpenzer123** [comment]
Can I completely remove my fork and start again.

**Pull request closed without merging**
