### PR TITLE
Part of #9473: Convert cable_lift_update to Vehicle private method Ca…

### PR DESCRIPTION
**Pull request by hdpoliveira**
…bleLiftUpdate

### CODE REVIEW

**Comment by tupaschoal** [comment]
We won't be merging before v0.2.6 is released, but if you won't update it anymore, you should mark the PR as ready for review :)

**Comment by tupaschoal** [comment]
@hdpoliveira is this ready for review?

**Comment by hdpoliveira** [comment]
Yes it is :)
I have some merge conflicts to resolve, though.

**Comment by tupaschoal** [comment]
Is this good to go @duncanspumpkin ?

**Comment by duncanspumpkin** [comment]
I'll have a look tomorrow

**Comment by janisozaur** [comment]
Also keep the title short, it gets used as commit subject line

**Pull request merged**
