### PR TITLE
Refactor out DidPassSurface

### PR DESCRIPTION
**Pull request by ZehMatt**
I removed the member as we can use the flags variable for this information instead. I also re-ordered the struct members to save a few bytes. I did some testing with underground tracks and loaded a few parks, I did not notice any difference, it should be logically the same just with a different variable now.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
What is the advantage of this?

**Comment by ZehMatt** [comment]
I don't see how two variables are useful doing the same thing. As for re-ordering, well it makes the struct smaller which is always a good thing.

**Comment by duncanspumpkin** [comment]
Yes it was always a bit odd that we had two variables for the exact same purpose basically. I think the changes look good.

**Comment by Gymnasiast** [comment]
I have no objections either, I was just wondering if there was any advantage besides being a bit cleaner.

**Review by Gymnasiast — CHANGES_REQUESTED** [review]
IsPassedSurface is not grammatical. It should be `DidPassSurface` or `PassedSurface`.

**Review by Gymnasiast — COMMENTED** [review]
Code looks ok, but I would like to test it. There is _some_ potential for subtle breakage here.

**Pull request merged**
