### PR TITLE
Added some docs to interface/window.c

### PR DESCRIPTION
**Pull request by warmwaffles**
I just wanted to make sure this is the desired format before I start making my way through the code and adding the documentation where I can.

### CODE REVIEW

**Comment by janisozaur** [comment]
oh that's nice. I haven't read through the content yet, but I'll try to set up doxygen job on travis soon.

**Comment by IntelOrca** [comment]
This is the right format, but points to consider:

* Only add a ```@param``` if there is a description to write, no point in empty ```@param```s.
* Don't write plain obvious descriptions, e.g. ```@param widget The widget```. It just bloats the code to state the obvious or anything that the programmer will understand without a description. Same with ```@return```.
* More importantly, list any edge cases or contracts in the summary and parameters.

**Comment by warmwaffles** [comment]
> Put docs in the header file if its a global function, otherwise the source file.

Documenting C code is a bit of a pain sometimes. I like having the docs right there above the function but I also get why it should be in the header files. So yea, I'll probably go through strip out the adds that have no real business being there. Some of the functions are hard to document due to ambiguity. 

I guess there is no point in documenting simple functions that are easier to just read the implementation than to see the doc tags.

**Comment by warmwaffles** [comment]
I'm gonna close this right now as I made commits to my develop remote and it has thrown my repo out of sync. Thanks for taking the time to review this.

**Pull request closed without merging**
