### PR TITLE
Fix #22598: Review existing .sea .parkpatch against .sc4 and .sc6

### LINKED ISSUE #22598: Analyze rctc (.sea) scenarios need for patches
RCTC scenarios (`.sea`) are a collection of scenarios from RCT1, RCT2 and their expansions. They seem to be slightly different, such that some bugs do not exist on the `.sea` (like several of Katie's Dreamland patches), as noticed on #21189. 

We should review all `.sc4` and `.sc6` that have patch files to make sure they are also needed on `.sea`. Also it would be nice to see whether some of the `.sea` patches are irrelevant.

### PR DESCRIPTION
**Pull request by tupaschoal**
This fixes #22598 by reviewing all existing `.parkpatch` files for `.sea` scenarios. I verified:

1- Existing `.sea` patches needed all changes (and removed/added the ones they didn't need or need from the corresponding RCT1/2)
2- Added `.sea` patches for RCTC scenarios pulled from RCT1 where they were still applicable
3- Added `.sea` patches for RCTC scenarios pulled from RCT2 where they were still applicable
4- Added a missing `.sc6` patch for Great Wall of China
5- Did a bunch of fixes on the `scenario_to_hash` file

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Would like a review/test by @HtotheTML .

**Comment by HtotheTML** [comment]
So I'm looking at the .sea files for patches on this one?

**Comment by tupaschoal** [comment]
> So I'm looking at the .sea files for patches on this one?

Yeah, what I did was to take all of the patches for .sc4 and .sc6 and create them for .sea where they hadn't been fixed for RCTC (most of them weren't, there were very few exceptions that had, and some had just part of the fixes).

Does that make sense?

**Comment by HtotheTML** [comment]
> > So I'm looking at the .sea files for patches on this one?
> 
> Yeah, what I did was to take all of the patches for .sc4 and .sc6 and create them for .sea where they hadn't been fixed for RCTC (most of them weren't, there were very few exceptions that had, and some had just part of the fixes).
> 
> Does that make sense?

Yep! I'm looking through all of the .sea files now (and scanning for any new spots I might've missed that only exist in .sea).

**Comment by HtotheTML** [comment]
Only a couple of errors persist in the .sea files currently:

In Mothball Mountain a stray buyable land tile exists that should instead be already owned land.
Mothball Mountain (53, 79)
(53, 79)

In Urban Park one set of buyable construction rights still overlaps with buyable land rights (I'm reusing a screenshot here, since it's the same location). They need to be only buyable land rights.
Urban Park (59, 62-65) (60, 62-65) (61, 62-65)
(59, 62-65) (60, 62-65) (61, 62-65)

Two stray spots of missing buyable land are present in Build Your Own Six Flags Holland. These spots need to be buyable land tiles (I bought all the land in these screenshots to find the missing spots)
Build Your Own Six Flags Holland (112, 33-34)
(112, 33-34)
Build Your Own Six Flags Holland (113-117, 117) (114-117, 118 )
(113-117, 117) (114-117, 118)

Build Your Own Six Flags Over Texas still has the construction rights gaps in the parking lot. These need to be owned construction rights.
Build Your Own Six Flags Over Texas (85, 80) (86, 79) (87, 73-78) (88, 73-76) (89, 73-75) (90, 73-75) (91, 73) (92, 73) (96-97, 71)
(85, 80) (86, 79) (87, 73-78) (88, 73-76) (89, 73-75) (90, 73-75) (91, 73) (92, 73) (96-97, 71)
Build Your Own Six Flags Over Texas (90, 42-45)
(90, 42-45)

All other errors appear to be accounted for.

**Comment by tupaschoal** [comment]
That's now all fixed, thanks again for helping @HtotheTML !

**Review by Gymnasiast — APPROVED** [review]

**Pull request merged**
