### PR TITLE
Add mapElementType entry for corrupt element

### PR DESCRIPTION
**Pull request by janisozaur**
This is upgraded version of #2558 

To trigger, simply:
```
./openrct2 data/title/openrct2/mci.sv6
```
and click on `Show map of park` button

### CODE REVIEW

**Comment by janisozaur** [comment]
One way to trigger this assert is by using a corrupt element feature.

To repro:
Start any scenario that doesn't crash yet, open map, open tile inspector, select any tile, click `Insert corrupt element`.

**Comment by janisozaur** [comment]
I added an element type for corrupt element, it solves #2558. It looks safe, as `ElementTypeMaskColour` and `ElementTypeAddColour` are only used in this file.

This doesn't, however, solve the problem with `mci.sv6`

**Comment by duncanspumpkin** [comment]
A corrupt element can be any type from 0x20 to 0x3C (i.e. (8, 9, 10,11, 12, 13, 14, 15) << 2). You should allow for all of these.

**Comment by janisozaur** [comment]
@duncanspumpkin in `mci.sv6` there are some corrupt elements with `type == 255`, as perhaps created with some external tool. How about mapping all auch invalid elements to corrupt one (`type == 32`)?

**Comment by janisozaur** [comment]
Updated, this now supports all unknown types in a safe manner. I also updated tile inspector a bit.

**Comment by duncanspumpkin** [comment]
I'd prefer if it wasn't explicit on the tile inspector as i have no idea what the standard is for 8cars corrupted elements.

**Comment by janisozaur** [comment]
OK, updated. I've decided to leave `MAP_ELEMENT_TYPE_CORRUPT` in, so it gets spotted come refactoring.

**Pull request merged**
