### PR TITLE
Allow assigning a keyboard shortcut for opening the tile inspector

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
Implements #7993.

### CODE REVIEW

**Comment by ocalhoun6** [comment]
Wow ... I ask for this, and 3 hours later, it's already done. You guys are awesome!

**Comment by janisozaur** [comment]
Well, it's a simple change that makes perfect sense and doesn't need a whole lot of discussion.

**Comment by Broxzier** [comment]
I clicked on 'approve' before realizing that the changelog entry is missing.

**Comment by pizza2004** [comment]
You know, this makes me think, perhaps there should just be a way to set a shortcut key for any window using an ID or something without needing each new window to have it programmed in separately.

**Pull request merged**
