### PR TITLE
Fixes for GCC

### PR DESCRIPTION
**Pull request by janisozaur**
This fixes compilation with GCC & clang, but leaks memory like crazy.

There's also a problem with `DISABLE_NETWORK` builds, as `jansson` becomes required. How should we fix this?

### CODE REVIEW

**Comment by IntelOrca** [comment]
Just make Jansson compulsory, I don't think there is any harm in doing that.
Do you know what part is leaking memory?

**Comment by janisozaur** [comment]
I made jansson required, I'll check the leak now.

**Comment by janisozaur** [comment]
Correction: it appears that it may not be leaking memory, but rather keeps allocating it till there is no more available.

**Comment by janisozaur** [comment]
Further testing shows no sign even of crazy allocations, must've been some glitch I had locally. The memory consumption sits stable now and this is good to go.

Travis failed only because of XCode now.

**Pull request merged**
