### PR TITLE
Refactor #12395 PeepItem to strong enum

### PR DESCRIPTION
**Pull request by danty178**
I hope this time I have pulled the commit to the right place. Please take account commit 3bb77f1 and ignore the rest. Thanks for the help of tupaschoal.

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
annoyingly this can't become a strong enum without a ton of casts. This is a limitation with c++ atm maybe it will be fixed in 2023.
I think our preferred style for arrays of flags like this is to do a namespace of constexprs. So it would be something like:

```
namespace PeepItem{
    constexpr uint32_t Balloon = (1 << 0);
    constexpr uint32_t Photo = (1 << 1);
    ...
}
```

**Comment by ZehMatt** [comment]
I tried to deliberately leave enums used as flags out of the enum refactor project but this one sadly slipped. I think we should leave this as is for now. @duncanspumpkin @tupaschoal what are your thoughts?

**Comment by ZehMatt** [comment]
Also on another thought it still makes sense to have PeepItem as a strong enum but not having each entry value defined as a flag. When we require a flag for such item we can always do something like
```
1u << static_cast<uint32_t>(item)
```
Because this usage is rather specific to how each item is stored.
So in general it would be probably best to have 
```Peep::AddItem, Peep::RemoveItem, Peep::HasItem, Peep::ClearItems``` hiding the internal data format entirely.

**Comment by duncanspumpkin** [comment]
Yes that would be a good idea. This one is especially important due to the extra flags so the offsets overlap. We should fix that at load so that a 64bit field is used. Should we close this PR?

**Comment by tupaschoal** [comment]
If there is an issue to track the prerequisite, I'm ok with closing it

**Comment by tupaschoal** [comment]
@duncanspumpkin can this be resumed now that we have the method to convert enums to flag? If not, maybe we should close as you suggested

**Comment by duncanspumpkin** [comment]
These fields are all flags at all times. We could swap it around though to change it so that they become enums. I think making it a namespace of constexprs would be the better approach personally.

**Comment by duncanspumpkin** [comment]
I think this should be closed. `SHOP_ITEM_xxx` is the enum version of these where `PEEP_ITEM_xxx` is `1 << SHOP_ITEM_xxx`. We need to unify these two types.

**Comment by tupaschoal** [comment]
Ok, closing then. Sorry @danty178

**Pull request closed without merging**
