### PR TITLE
Rename ride_is_valid_for_test/open and update return type

### PR DESCRIPTION
**Pull request by manuelVo**
The functions `ride_is_valid_for_test` and `ride_is_valid_for_open` don't simply test whether the ride can be tested/opened but also perform the open/test. I've renamed the functions accordingly and also changed the return type to the better fitting type bool

### CODE REVIEW

**Review by Gymnasiast — CHANGES_REQUESTED** [review]
Please also turn the functions into methods of `Ride`.

**Comment by duncanspumpkin** [comment]
Also if you are working on this function change it to TitleCase.

**Comment by manuelVo** [comment]
Done.

**Review by Gymnasiast — APPROVED** [review]

**Comment by tupaschoal** [comment]
Note it might take some days to merge, as we are preparing for a release and only want to push bug fixes

**Pull request merged**
