### PR TITLE
Add missing null check

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Review by ZehMatt — APPROVED** [review]
Ordinarily when the game action result is good it should be guaranteed but it doesn't hurt either.

**Comment by Gymnasiast** [comment]
I take it the macOS failure is not related to this PR?

**Comment by karst** [comment]
that's likely on GitHub's end. Duncan said he's investigating, but currently all PRs are failing.

**Comment by ZehMatt** [comment]
Rebase and it should be fixed

**Pull request merged**
