### PR TITLE
#13426 Typo fixed

### PR DESCRIPTION
**Pull request by maksimdrachov**
Searched and replaced following: 
- OBJECTIVE_REPLAY_LOAN_AND_PARK_VALUE -> OBJECTIVE_REPAY_LOAN_AND_PARK_VALUE (14 instances)
- replayLoanAndParkValue -> repayLoanAndParkValue (1 instance)

### CODE REVIEW

**Review by duncanspumpkin — COMMENTED** [review]
As this modifies scripting the api version number will need bumping

**Comment by maksimdrachov** [comment]
Is this something I can fix on my end? If yes, could you provide a bit more information as to how do this?
(First time doing this, so apologies if this is a stupid question)

**Comment by duncanspumpkin** [comment]
You just need to increment this number by one as part of this pr https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/scripting/ScriptEngine.cpp#L46

**Comment by maksimdrachov** [comment]
updated the API version number, squashed the 2 commits into 1

**Review by duncanspumpkin — APPROVED** [review]

**Comment by James103** [comment]
Did you forget about the following?
https://github.com/OpenRCT2/OpenRCT2/blob/4ff412dfe155c32664273d1b098d62c026a74c96/distribution/openrct2.d.ts#L1488

**Comment by maksimdrachov** [comment]
I did...
I will fix it quickly.

Btw I looked for it with CodeLite -> "Find in files", but apparently it didn't search trough all the possible extensions, using vscode it did find it. Anyone an idea how to look through ALL the files in a folder using CodeLite? Adding each extensions manually is a bit unproductive.
Screenshot 2020-11-18 at 14 35 50

**Pull request merged**
