### PR TITLE
Check map element when peep is falling

### PR DESCRIPTION
**Pull request by janisozaur**
**OS:** Windows
**Version:** 0.0.4-develop
**Commit:** 2090c4aa

- [x] Multiplayer?

**Steps to reproduce:**
1. Embedded save game is a reproducer

**Dump file**

[OpenRCT2-dump-2090c4aa.zip](https://github.com/OpenRCT2/OpenRCT2/files/216104/OpenRCT2-dump-2090c4aa.zip)
d26e4d3d66be3a0258581afb1c070597

### CODE REVIEW

**Comment by janisozaur** [comment]
It happened yesterday, but unfortunately, I was only delivered the dump just now.

**Comment by duncanspumpkin** [comment]
Should really remove a peep if they have left reality instead

**Comment by Nubbie** [comment]
The peep should be removed if they fall, guess this will teleport them up on the ground again?
That could create an endless cycle off falling if they do

**Comment by IntelOrca** [comment]
I don't think it should just return... does it not just get stuck?

**Comment by mrtnptrs** [comment]
How can I reproduce this issue using the attached save files?

**Comment by Nubbie** [comment]
@janisozaur Maybe should be baked into #4185

**Comment by janisozaur** [comment]
Doesn't happen anymore

**Pull request closed without merging**
