### PR TITLE
Fix #6751: Android CLI client is missing

### LINKED ISSUE #6751: Android CLI client is missing
**OS:** Android
**Commit/Build:** 251dad1 

Android APK and project setup only output the SDL2 GUI version. It should also be possible to build the CLI client.

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by janisozaur** [comment]
Hmm, the second commit breaks things:
```
  /home/janisozaur/workspace/OpenRCT2/src/openrct2/localisation/localisation.c:1354: error: undefined reference to 'SDL_AndroidGetJNIEnv'
  /home/janisozaur/workspace/OpenRCT2/src/openrct2/platform/android.c:62: error: undefined reference to 'SDL_AndroidGetJNIEnv'
  /home/janisozaur/workspace/OpenRCT2/src/openrct2/platform/android.c:64: error: undefined reference to 'SDL_AndroidGetActivity'
  /home/janisozaur/workspace/OpenRCT2/src/openrct2/core/ZipAndroid.cpp:32: error: undefined reference to 'SDL_AndroidGetJNIEnv'
  /home/janisozaur/workspace/OpenRCT2/src/openrct2/core/ZipAndroid.cpp:48: error: undefined reference to 'SDL_AndroidGetJNIEnv'
```

**Comment by janisozaur** [comment]
Temporary compilation fix here: https://github.com/janisozaur/OpenRCT2/commit/88cac1d6cec6add641435167b8b95758e45ccab5

It asserts in runtime probably due to 💩  implementation of `win1252_to_utf8` (or lack thereof)

**Comment by janisozaur** [comment]
I may have to resort to building iconv for android.

https://medium.com/@zw3rk/building-iconv-for-android-e3581a52668f

**Comment by janisozaur** [comment]
@IntelOrca suggested perhaps writing a simple shell with Java might be an option, his stub written in C#:

```csharp
[DllImport("openrct2.dll")]
extern int LaunchOpenRCT2(string[] argv, int argc)

static int Main(string[] args)
{
    return LaunchOpenRCT2(args, args.Length);
}
```

For notekeeping:

* https://davanum.wordpress.com/2007/12/04/command-line-java-on-dalvikvm/
* http://www.inonit.com/cygwin/jni/invocationApi/c.html
* https://docs.oracle.com/javase/6/docs/technotes/guides/jni/spec/invocation.html
* https://wiki.libsdl.org/SDL_AndroidGetJNIEnv
* https://github.com/spurious/SDL-mirror/blob/abea243f22782c912dd38d768722420e8ff3c98e/src/core/android/SDL_android.c#L941-L974

**Comment by janisozaur** [comment]
#7385 removes `win1252_to_utf8`, but adds dependency on libicu.

**Comment by janisozaur** [comment]
This should be ready as-is, the `openrct2-cli` builds fine, but it is not packaged in APK. I would still need to provide a brief comment to explain why it is not packaged.

I have no intention of packaging it, as I doubt it would be any useful, but I would like to at least test it loads correctly (bar https://github.com/OpenRCT2/OpenRCT2/issues/7536). The reason behind why I want it enabled and compiling for Android as well is I want to build the test binaries.

**Comment by marijnvdwerf** [comment]
Why do you want the test binaries built? Also, which tests are you referring to? As the unit tests have their own binary, and don't use CLI.

**Comment by janisozaur** [comment]
> Why do you want the test binaries built?

So I can run them.

> Also, which tests are you referring to?

https://github.com/OpenRCT2/OpenRCT2/blob/develop/test/tests/CMakeLists.txt

> As the unit tests have their own binary, and don't use CLI.

That's true. But (other than gtest) they build and act exactly the same way as CLI client, which is easier to build.

**Comment by janisozaur** [comment]
I just tested the client, it's able to load correctly on my device, but crashes immediately with this stack trace:
```
#00 pc 00000000000a5604  /data/local/tmp/libSDL2-2.0.so
#01 pc 000000000037cd60  /data/local/tmp/libopenrct2.so
#02 pc 00000000001e5808  /data/local/tmp/libopenrct2.so
#03 pc 00000000001e1360  /data/local/tmp/libopenrct2.so
#04 pc 00000000001e0f60  /data/local/tmp/libopenrct2.so
#05 pc 00000000001bcf94  /data/local/tmp/libopenrct2.so
#06 pc 000000000019b204  /data/local/tmp/libopenrct2.so
#07 pc 0000000000000fdc  /data/local/tmp/openrct2-cli
#08 pc 00000000000a1b00  /system/lib64/libc.so (__libc_init+88)
#09 pc 0000000000000f4c  /data/local/tmp/openrct2-cli
```

With frame \#1 being `/home/janisozaur/workspace/openrct2/src/openrct2/platform/Android.cpp:41`: `_ZN6ConfigL11ReadGeneralEP10IIniReader` which is https://github.com/OpenRCT2/OpenRCT2/blob/f79954bde35a36d8f44cb707a4f8094566e98ac6/src/openrct2/platform/Android.cpp#L41

I'm pretty sure it's due to using our own `main()` which doesn't set up JNI in the way SDL2 expects it. I would expect the same thing to happen if I were to run the tests that come near JNI on any of the paths.

**Comment by janisozaur** [comment]
I think I will merge it now, it builds the client already, but file an issue for improving this client and enable tests.

**Pull request merged**
