### PR TITLE
Disable warnings around incompatible function pointer cast

### PR DESCRIPTION
**Pull request by janisozaur**
This addresses a compilation issue with newer (8+) mingw.

### CODE REVIEW

**Comment by ZehMatt** [comment]
Why are we using kernel mode APIs again? This should rather use GetVersionEx or VerifyVersionInfo

**Comment by janisozaur** [comment]
It was introduced here: https://github.com/OpenRCT2/OpenRCT2/pull/7266

**Comment by ZehMatt** [comment]
Dunno what to think of that, strictly speaking those APIs are identical to the user mode ones when in user mode but we should perhaps address this at some point.

**Comment by Gymnasiast** [comment]
This breaks the MinGW CI. Is it correct, and is there a way to satisfy both versions?

**Comment by Gymnasiast** [comment]
Summoning @IntelOrca .

**Comment by IntelOrca** [comment]
I can't remember. The documentation says to now use the following APIs:

https://docs.microsoft.com/en-gb/windows/win32/sysinfo/version-helper-apis

In particular:
https://docs.microsoft.com/en-us/windows/win32/api/versionhelpers/nf-versionhelpers-iswindowsversionorgreater

**Comment by Gymnasiast** [comment]
What shall we do with this?

**Comment by IntelOrca** [comment]
I don't have a problem with it being merged.

**Comment by Gymnasiast** [comment]
@IntelOrca Neither do I, but the CI failed at the time. Perhaps that's now no longer the case, but it would need green CIs before merging.

**Pull request merged**
