### PR TITLE
Remove network traffic window

### PR DESCRIPTION
**Pull request by IntelOrca**
Now available in the [DevTools](https://github.com/OpenRCT2/plugin-devtools) plugin.

### CODE REVIEW

**Review by ZehMatt — APPROVED** [review]

**Comment by Gymnasiast** [comment]
Does this PR obsolete any strings?

**Comment by Gymnasiast** [comment]
Also, you can safely *remove* files from the Xcode definition yourself.

**Review by tupaschoal — COMMENTED** [review]
Does this tab also need to be removed?

https://github.com/OpenRCT2/OpenRCT2/blob/21777210bc62ef9f238496bb97237bf8450287d1/src/openrct2-ui/windows/Multiplayer.cpp#L65

According to @Gymnasiast comments, these strings have become obsolete:
- `STR_NETWORK`
- `STR_NETWORK_INFORMATION_TITLE`
- `STR_NETWORK_LEGEND_BASE`
- `STR_NETWORK_LEGEND_COMMANDS`
- `STR_NETWORK_LEGEND_MAPDATA`
- `STR_NETWORK_RECEIVE`
- `STR_NETWORK_TOTAL_RECEIVED`
- `STR_NETWORK_SEND`
- `STR_NETWORK_TOTAL_SENT`

**Review by Gymnasiast — APPROVED** [review]

**Comment by tupaschoal** [comment]
@Gymnasiast Will you created an issue for the removed strings on the localisation repo? Or did someone already tend to them all?

**Comment by Gymnasiast** [comment]
@tupaschoal I will just push a commit to remove them all. No need to bother the translators for it.

**Comment by tupaschoal** [comment]
Right, thanks!

**Pull request merged**
