### PR TITLE
Android: Enable plugins

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by ZehMatt** [comment]
We should probably get rid of the macro guards and just have it always there now that we build DukTape within the project, little reason to keep guarding it at this point.

**Comment by janisozaur** [comment]
I strongly prefer to leave it, I do find it useful to disable parts of the project when doing code shenanigans.

**Review by Gymnasiast — APPROVED** [review]

**Comment by Gymnasiast** [comment]
Totally forgot: this should have gotten a changelog entry. Can you do a followup PR?

**Comment by janisozaur** [comment]
There's more where this came from, I'll update the changelog in next PR

**Pull request merged**
