### PR TITLE
[Cleanup] Use RideData4

### PR DESCRIPTION
**Pull request by marijnvdwerf**

### CODE REVIEW

**Comment by marijnvdwerf** [comment]
@IntelOrca I think `var_3` referring to another ridetype might make sense, as the data for the base and alt rides seems to be the same, except for `RideTypePossibleTrackConfigurations`. I don't get the reasoning for splitting it up though. Is there something special about these rides?

**Comment by duncanspumpkin** [comment]
Is it something like upside down? Multi dim coasters have a lot of special parts to them.

**Comment by IntelOrca** [comment]
I never worked out what those other ride types are for... there are also two for each shop type.

**Comment by janisozaur** [comment]
Looks like it's ready.

**Pull request merged**
