### PR TITLE
Fix additional missing land/construction rights tiles in WW's Inca Lost City & Renovation

### PR DESCRIPTION
**Pull request by HtotheTML**
Additional missing land and construction rights tiles were found in these two scenarios.

Inca Lost City has a few missing construction rights tiles underneath the river.
image
image

Renovation has dirt grass exclusively inside the park boundaries, save for this one lone tile.
image
image

### CODE REVIEW

**Comment by HtotheTML** [comment]
A lone tile in that same river also has land ownership, whereas the rest is construction rights.
image
image

**Comment by HtotheTML** [comment]
Found additional missing tiles along the far shore of that same river while playing.
image
image

**Comment by HtotheTML** [comment]
On a different note, I'm wondering if construction rights should be added over the path to the park entrance, as it makes the path an obstacle for building around that area, with connecting those two sections of the park being made impossible or very inconvenient. It has been done before in other scenarios.
image
image

**Comment by tupaschoal** [comment]
> On a different note, I'm wondering if construction rights should be added over the path to the park entrance, as it makes the path an obstacle for building around that area, with connecting those two sections of the park being made impossible or very inconvenient. It has been done before in other scenarios.

Hmm, I think it shouldn't, if nothing is making it look like it should.

**Review by tupaschoal — APPROVED** [review]
I've looked into the scenarios and the fixes seem right, can you please rebase to fix the changelog merge conflict @HtotheTML ?

**Review by tupaschoal — APPROVED** [review]

**Review by Gymnasiast — APPROVED** [review]

**Pull request merged**
