### PR TITLE
Fix #5541: Include SDL2 as system library

### LINKED ISSUE #5541: fatal error: too many errors emitted.
**OS:** [OSX 10.10.5]
**Version:** [0.0.8]
**Commit/Build:** [9bd4284]

Hi, I have this error when try to build : 
/usr/local/include/SDL2/SDL_platform.h:73:5: error: 'TARGET_OS_TV' is not defined, evaluates to 0 [-Werror,-Wundef]
#if TARGET_OS_TV
    ^
In file included from /Users/fabrizio/github/games/OpenRCT2/src/openrct2/cheats.c:17:
In file included from /Users/fabrizio/github/games/OpenRCT2/src/openrct2/cheats.h:20:
/Users/fabrizio/github/games/OpenRCT2/src/openrct2/common.h:294:1: error: expected parameter declarator
assert_struct_size(registers, 7 * 4);
^
/Users/fabrizio/github/games/OpenRCT2/src/openrct2/common.h:227:48: note: expanded from macro 'assert_struct_size'
#define assert_struct_size(x, y) static_assert(sizeof(x) == (y), "Improper struct size")
....
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
Thanks.

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by janisozaur** [comment]
This is tentative fix for #5541, but I'm not sure if we want to merge it or not. The code works with our currently supported configurations as proven by Travis, and it looks like xcode 7 lies about things.

Perhaps rather than going out of our way to support broken compilers better solution would be to require xcode >= 8.

**Comment by Gymnasiast** [comment]
Since we always have been quick to drop support for older systems and Xcode is only needed for compiling, I would be in favour of dropping Xcode 7 support. Xcode 8 requires El Capitan or higher, which is conveniently the last version that still support 2007-2010 era Apple hardware.

**Comment by rwjuk** [comment]
Agreed on dropping support for Xcode 7.

**Comment by marijnvdwerf** [comment]
No idea why I was asked to review this. I don't even understand the difference between the two functions.

**Comment by janisozaur** [comment]
@marijnvdwerf I wanted your view on xcode7 support.

**Comment by marijnvdwerf** [comment]
Ah, got it. Makes sense to me to drop non-latest Xcode support.

**Comment by IntelOrca** [comment]
Agree, similarly I am not really interested in supporting VS2015u3 or below at this point. I would really like to use C++17 ASAP.

**Comment by janisozaur** [comment]
According to http://sealiesoftware.com/blog/archive/2010/8/16/TargetConditionalsh.html and https://developer.apple.com/library/content/documentation/General/Conceptual/AppleTV_PG/ and https://en.wikipedia.org/wiki/Xcode#Xcode_7.0_-_8.x_.28since_Free_On-Device_Development.29, `TARGET_TV_OS` macro will always be defined, but only on Xcode 7.1+. As we agreed to only support Xcode 8, I'm going to reject and close this PR and instead I asked @rwjuk to look into ways we can ensure Xcode 8 or later is used.

**Pull request closed without merging**
