### PR TITLE
Add Classic Stand-Up Roller Coaster

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by ZeeMaji** [comment]
Supports are not connecting to the track spine on the diagonal banking slope transition pieces.

Screenshot_select-area_20240320143528
Screenshot_select-area_20240320143539

**Comment by ZeeMaji** [comment]
There's some minor clipping on the banking turn pieces when viewing them from the outside.

Small Turns
Screenshot_select-area_20240320144011

Medium Turns
Screenshot_select-area_20240320144031

Large/Diagonal Turns
Screenshot_select-area_20240320144057

**Comment by Gymnasiast** [comment]
I fixed the first problem, but I’m not sure if the second problem can be solved easily. Maybe @spacek531 can weigh in, seeing as he did some similar work on the Classic Wooden.

**Comment by spacek531** [comment]
I fixed clipping on small curves by changing the vehicle entry's `drawOrder` value to 6. This selects a larger bounding box which paints the trains in the correct order in that case. I could not recreate clipping on large curves in OpenRCT2 before or after the change. Clipping on medium curves is present in RCT1.

**Comment by spacek531** [comment]
Tested the new pieces, tested the available parts, it all looks good

**Review by spacek531 — APPROVED** [review]

**Comment by ZeeMaji** [comment]
All of the new pieces appear to be rendering as they should, very nice.

**Review by ZeeMaji — APPROVED** [review]

**Review by janisozaur — APPROVED** [review]

**Pull request merged**
