### PR TITLE
Feature: #18829: Add g1 Icons to Scripting

### PR DESCRIPTION
**Pull request by Harry-Hopkinson**
For #18829 - add g1 icons to be accessible from plugins.

### CODE REVIEW

**Comment by Harry-Hopkinson** [comment]
I believe that I have moved over all of the relevant buttons and icons. If I have missed any, just let me know.

**Comment by Gymnasiast** [comment]
@Sadret Does this look all right to you?

**Comment by Gymnasiast** [comment]
@Harry-Hopkinson Could rebase and update the changelog? You can file this under Improved. Make sure to prefix the entry with `[Plugin]`.

**Comment by Harry-Hopkinson** [comment]
I have rebased and added a changelog entry.

**Comment by Sadret** [comment]
Thanks for notifying.

Looks good but haven't tested.

**Review by Gymnasiast — APPROVED** [review]

**Comment by spacek531** [comment]
Shouldn't this have had an API bump?

**Comment by Gymnasiast** [comment]
Ah yeah, forgot about that. Thanks for pointing it out.

Since https://github.com/OpenRCT2/OpenRCT2/pull/22046 already raised the API version, I won’t bump it again.

**Pull request merged**
