### PR TITLE
Re-refactor peep calculate satisfaction

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Re-refactored the peep ride satisfaction calculations as there were a few bugs with the existing code.

@zaxcav can you run some tests on this as it will produce some quite different values for rides compared to the existing code.

### CODE REVIEW

**Comment by zaxcav** [comment]
I'll rerun at least the same "test ride" that I was using for the previous happiness fixes to the broken code to see how this compares to vanilla RCT2 (since I already have the vanilla data for comparison purposes).  I should have time today.

**Comment by zaxcav** [comment]
The appears to be an obvious fault with the return values of peep_calculate_ride_intensity_nausea_satisfaction().  All the correct values are there (I assume), but in the wrong places, such that the largest happiness bonus is given for the lowest satisfaction.

I did actually test with these values (in case I was simply confused), but the results were clearly wrong.

Taking the return values as a matrix of maxSatisfaction * minSatisfaction and transposing it gives the larger happiness bonuses for higher satisfaction.
So the original was:
70
50, 35
35, 20, 10
-35, -50, -60, -60
Transposed is:
-60
-60, 10
-50, 20, 35
-35, 35, 50, 70

Testing with these gives pretty good results:
happiness-refactor

There's still an obvious inconsistency for Guest 174 though.

First check if what I've said about the return values above is correct or not.

Any idea what's happening with Guest 174?
The vanilla behaviour and previous ORCT2 behaviour suggest Guest 174 should be getting the highest excitement/nausea bonus (70) rather the what they get here (50).
Potentially the intensitySatisfaction and/or nauseaSatisfaction is not calculated right.  I took a quick look at the refactored code, but I find the negated logic compared to the previous version very confusing.

**Comment by duncanspumpkin** [comment]
I had the same thought when I was writing it but as far as I can tell that is what the vanilla version is doing.

**Comment by zaxcav** [comment]
I've compared against the original version and identified the problem.
Here's the test comparison. Looks very good.
refactor_fixed


I've got to go out for about an hour though.  Details when I get back.

**Comment by zaxcav** [comment]
Sorry, that took longer than expected.
Taking a sample code fragment from peep_calculate_ride_intensity_nausea_satisfaction():
Current code is:
```
if (maxIntensity <= ride->intensity && minIntensity >= ride->intensity) {
		intensitySatisfaction--;
}
maxIntensity -= peep->happiness * 2;
minIntensity += peep->happiness;
```

This needs to be corrected to:
```
if (maxIntensity <= ride->intensity || minIntensity >= ride->intensity) {
		intensitySatisfaction--;
}
maxIntensity += peep->happiness * 2;
minIntensity -= peep->happiness;
```

Make those changes as appropriate for the intensity satisfaction and nausea satisfaction, as well as correcting the return values as indicated previously, and the peep happiness changes as per in vanilla RCT2 as shown in the above graph.

**Comment by duncanspumpkin** [comment]
I think I see where i had it wrong based on the original code its still different to your suggestion (bear in mind i didnt transpose the returns):

```
    if (minIntensity <= ride->intensity && maxIntensity >= ride->intensity) {
		intensitySatisfaction--;
    }
    minIntensity -= peep->happiness * 2;
    maxIntensity += peep->happiness;
```

**Comment by zaxcav** [comment]
I _believe_ for that to work correctly the following changes are necessary:
Initialisation:
`intensitySatisfaction = 0;`
Increment:
`intensitySatisfaction++;`
I don't see why the adjustment of min/maxIntensity would be different to the original either.
But I'll test it as is first to confirm.

**Comment by zaxcav** [comment]
Here's the comparison graph for the current PR code vs vanilla.

refactor-fixed

Looks good to me. :-)

**Comment by duncanspumpkin** [comment]
Okay think it's fine to merge then

**Comment by janisozaur** [comment]
Shouldn't this have changed network version?

**Comment by zaxcav** [comment]
@duncanspumpkin I believe this fixes #3353

**Pull request merged**
