### PR TITLE
Fix #2162

### LINKED ISSUE #2162: Multiplayer: Entering ride construction doesn't remove trains for other clients and server
Whether you enter ride construction mode for a roller coaster on the client or server, it will not remove the trains off a ride for any other client except the one that entered construction mode. 

This can cause the ride to crash if you remove a track piece on other clients or the server since the trains are still on the ride.

### PR DESCRIPTION
**Pull request by FlukiestEmperor**
Remove vehicles for all clients in multiplayer. Fixes #2162.

### CODE REVIEW

**Comment by IntelOrca** [comment]
Why does this need to be done in another game command rather than the same game command to stop the ride?

**Comment by FlukiestEmperor** [comment]
Stopping the ride doesn't take the vehicles off the track. Unless I'm misunderstanding what you're asking.

**Comment by IntelOrca** [comment]
Stopping twice does right?

**Comment by PFCKrutonium** [comment]
Yes.

**Comment by FlukiestEmperor** [comment]
Yes it does, I didn't realize that.

**Comment by FlukiestEmperor** [comment]
Is that better?

**Comment by IntelOrca** [comment]
possibly I need to check if that is the right thing to do, but I don't have time right now

**Comment by IntelOrca** [comment]
I fixed it in a way that wouldn't cause a desync.
8d3655e0f652db7ebb7461081d16dfa06dfbee4f

It should call stop ride again instead of clearing the vehicles and peeps when you modify a ride. This will then be synchronised with the other players.

**Pull request closed without merging**
