### PR TITLE
Guests will use Vanilla behaviour when choosing whether to head for a ride when leaving the park #15969

### PR DESCRIPTION
**Pull request by 733737**
this will have peeps using vanilla behavior to determine whether to head for a ride when leaving park

Co-Authored-By: reticulatingsplines <13323105+ReticulatingSplines@users.noreply.github.com>

### CODE REVIEW

**Comment by 733737** [comment]
I need help with ReplayManager

**Review by rik-smeets — CHANGES_REQUESTED** [review]
You combined a refactoring (a method rename) with a functional change: this makes reviewing hard. Could you please split the refactoring and the change into separate commits?

If you don't know how to do that, you can also just rename the method back to what it was before so the changes will disappear. 

Please also provide a better PR title, something in the lines of: `Fix guest behavior when heading for ride`.

**Comment by 733737** [comment]
I will split this into 3 PRs one for changing chose to choose, 1 for adding the else, and 1 for refactor

**Comment by 733737** [comment]
should be ready now

**Comment by 733737** [comment]
please merge my pr on changing chose to choose prior to merging this one, that's the only way it won't cause a conflict

**Review by tupaschoal — COMMENTED** [review]
Is this referring to any given issue? If so, please add the issue number.

I feel like the description (and maybe even the changelog, if short enough) can be enhanced to describe what the vanilla behavior was and what we were doing instead.

Also, the PR needs rebasing

**Comment by 733737** [comment]
the PR does NOT need rebasing I just checked. What makes you think it does? also, what this does is it does not execute the code regarding a peep determining whether they want to ride a ride if they are already in the process of leaving a park, except for transport rides. Currently, it still checks whether a peep wants to ride a ride even if they are leaving the park

**Comment by Gymnasiast** [comment]
@733737 It clearly **does**, it clearly says so on this page:

afbeelding

Also, we don’t merge sweeping changes to AI on a whim, so I’m afraid I have to close it anyway.

**Comment by 733737** [comment]
youre wrong, it does not change the ai, it just adds an else and two brackets. And it did not need a rebase at time of my post

**Comment by Gymnasiast** [comment]
No, I’m not wrong. It literally changes how guests behave when it’s raining. In which universe does that not constitute an AI change? Also, the GitHub UI clearly indicated it **did** need a rebase. It showed 3 file conflicts.

Getting a bit fed up with your behaviour. It’s okay you need to learn stuff, but saying we are wrong when you clearly don’t know what we’re talking about gets old really quickly.

**Comment by 733737** [comment]
I don't think it's helpful to _debate_ who is wrong and why.

**Comment by Gymnasiast** [comment]
Uhm, yes it is. You first deny the PR changes AI, while the PR clearly states it aim to restore vanilla behaviour. Then you deny it needs rebasing, while the UI clearly indicates there are file contents and we literally cannot merge it because of it. This is super elemental stuff. Again, it’s okay if you don’t understand what we mean, but what you said is not that different from saying the sky made out of hamsters.

**Pull request closed without merging**
