### PR TITLE
UTF-8 and TTF support

### PR DESCRIPTION
**Pull request by IntelOrca**
This is a very big change... all string handling has to be changed to UTF-8 and yet still be backwards compatible with RCT2 for the time being.

Please let me know of any bugs or strange visuals you see.

Non-scrolling banners do not work yet.

### CODE REVIEW

**Comment by danidoedel** [comment]
Wow nice work! Two things i noticed:
2015-07-30 04_35_34-wetter
The save and load path have the wrong colour.


2015-07-30 04_37_12-openrct2
The chinese tooltips might be a bit hard to read.

**Comment by daihakken** [comment]
`STR_2386    :{BLACK}{BLACK}To have at least {COMMA16} guests in your park at the end of {MONTHYEAR}, with a park rating of at least 600`
In the translation, I have to put {MONTHYEAR} before {COMMA16}, which makes it abnormal in game. 
capture
Should I revise the translation to keep the variables intact? (In RCT1, the string was similar to my translation)

**Comment by daihakken** [comment]
I used the default [Ming](https://en.wikipedia.org/wiki/Ming_(typefaces)) typefaces to get better comparisons between RCT2 and OpenRCT2, and turns out that OpenRCT2's font size is too small.
OpenRCT2:
capture
Vanilla RCT2:
capture2

**Comment by daihakken** [comment]
Seems that reading Chinese names/descriptions from saves will produce some strange characters: (The name is 廁所2, "Toilet 2" in English)
capture-2
capture2

**Comment by daihakken** [comment]
@danidoedel it's because the save game will use the Chinese strings, rather than saving all strings into the names and descriptions.

**Comment by IntelOrca** [comment]
@daihakken Not sure if I can determine what language a saved game is in unless it actually saves what language of the game is used somewhere in the save file.

**Comment by Gymnasiast** [comment]
I can't compile with Cmake:
```
/home/michael/Downloads/Spellen/RCT2/OpenRCT2-utf8/src/drawing/scrolling_text.c:1:21: fatal error: SDL_ttf.h: Bestand of map bestaat niet
 #include <SDL_ttf.h>
````
Bestand of map bestaat niet = No such file or directory

I ran ./clean.sh, ./install.sh in advance.

**Comment by IntelOrca** [comment]
@Gymnasiast I am not sure if @mzmiric5 has got the SDL_ttf 2 library working for mingw yet. You could try to see if you can get it working yourself though by downloading what is necessary.

**Comment by Gymnasiast** [comment]
Since it handled the ride queue banners, this PR will also close #818.

**Comment by Gymnasiast** [comment]
There are banner and news problems when the game is set to Dutch:

scr58

Also, when switching from Traditional Chinese to English in-game, the theme list looks like this:
scr60

**Comment by daihakken** [comment]
@Gymnasiast same with English to CHT, the theme/title sequence will stay English.

**Comment by Gymnasiast** [comment]
News that takes two lines does not align properly:
scr63

**Comment by Gymnasiast** [comment]
Another note: this seems to make the tooltips work again as well.

**Comment by daihakken** [comment]
@Gymnasiast tooltip was fixed #6f1aca5

**Comment by danidoedel** [comment]
2015-07-30 16_12_41-start

**Comment by danidoedel** [comment]
Tested part 21 and after switching the language to Chinese the game crashed.

**Comment by daihakken** [comment]
@danidoedel my game works flawlessly though. I think the Chinese font used is missing in your Windows(?), which is by default embedded when you use Chinese typing tools or something.

**Comment by daihakken** [comment]
The scrolling banner is abnormal when showing in English, Only existed in Chinese Traditional, of course.
https://drive.google.com/file/d/0B2_12DbzmFxYV0pxcEtVQmJXV1k/view?usp=sharing

**Comment by danidoedel** [comment]
@daihakken Ohhh yeah that could be the problem, but I think it shouldn't crash anyway :(

**Comment by IntelOrca** [comment]
@daihakken It doesn't look that bad, it allows you to have Chinese and English banners.

**Comment by daihakken** [comment]
@IntelOrca No, I mean, when the scrolling banners are in English, they will reset abruptly as shown in the vid.

**Comment by IntelOrca** [comment]
@daihakken ok I will look into it, usually its because its not calculating the width of the string correctly.

**Comment by daihakken** [comment]
@IntelOrca Thank you, I'm trying to report every bugs I can find.

**Comment by danidoedel** [comment]
Placing a shop will crash the game.

**Comment by daihakken** [comment]
^ I can reproduce this bug.

**Comment by IntelOrca** [comment]
I have now fixed the shop bug and it will fallback to the sprite font if you don't have the required font. Not brilliant but at least it now shows an error in the console instead of crashing.

**Comment by danidoedel** [comment]
When you hover the console text it disappears, clicking on it changes its colour and it changes the colour to the news message colour which is currently shown.
2015-07-31 22_24_49-fotos
2015-07-31 22_25_02-fotos
2015-07-31 22_25_29-fotos

**Comment by danidoedel** [comment]
The land tool size is shown in grey and not in black.
2015-07-31 23_04_56-fotos 2015-07-31 23_07_38-openrct2

**Comment by danidoedel** [comment]
This string is shortened and should be: 'OpenRCT2 Saved Game':

2015-07-31 23_50_25-openrct2

**Comment by daihakken** [comment]
Simliar to @danidoedel reported, when you tried to load save by the window prompt, there are two file type:
bug2
This is the reproduction of @danidoedel 's reported bug, and It shows that the string is misread.
bug1

**Comment by daihakken** [comment]
Glitch when showing this tooltip (I don't know why, is that caused by my translation?)
bug3
The paragraphs are showing strangely, as there are too many spaces available.
bug4

**Comment by danidoedel** [comment]
In that column some German letters are missing (ä, ö, ü, ß), but working fine in the left column and everywhere else:
2015-08-01 19_41_50-openrct2

**Comment by danidoedel** [comment]
The 'X has broken down' message sometimes appears in the wrong colour:

**Comment by daihakken** [comment]
Just found that the command prompt is displaying incorrectly in game.
bug1

**Comment by daihakken** [comment]
Again, similar to @danidoedel reported, the right column of the scenario selection is having something wrong.
bug2

**Comment by IntelOrca** [comment]
@danidoedel You will need to delete your plugin.dat so that it re-creates it in UTF-8. This should fix the missing German letters.

**Comment by danidoedel** [comment]
Yeah that fixed it, thanks!

The game is crashing again if I set the language to Chinese.

Reffering to the 'X has broken down message': The German message has the right font colour, but sometimes the message appears in English with the other font colour... I thought I have read about this issue somewhere else before, but can't find it anymore so I don't know if that is related to the utf8 support.

Apart from this I can't find any bugs! ;)

**Comment by IntelOrca** [comment]
The news item is related to original code generating the news item. I'll see if I can hook it.
I deliberately made the tooltip 1px lower in order to fix it for TTF fonts.
I wouldn't regard the changed line spacing as a defect, it can easily be changed in the future.

**Comment by danidoedel** [comment]
Ok, how about making the tooltip box 1px bigger so it looks correct? Don't know if that's possible...

**Comment by danidoedel** [comment]
If you buy anything, the costs are displayed strange:
2015-08-03 15_54_38-fotos

And still crashing if I set the language to Chinese.

**Comment by IntelOrca** [comment]
@danidoedel I know, I will work on that next.

**Comment by IntelOrca** [comment]
OK, are they are bugs still remaining other than line heights and static banners?

**Comment by danidoedel** [comment]
No, can't find any other bug so far.

**Comment by daihakken** [comment]
Me too.

**Pull request merged**
