### PR TITLE
Fix #16565: Ducks/birds always spawn at the edge of the old map limit

### LINKED ISSUE #16565: Ducks/birds always spawn at the edge of the old map limits, and nowhere else
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (6d0bb48 on develop) provided by GitHub

### Describe the issue

Ducks always spawn at the edge of the old map limit, so at either 0 or 255 tiles out on either X or Y.

**The bug**
If the map is smaller than 256, they spawn far out in the void and slowly fly to the map.
If the map is bigger than 256, they spawn over land and if the map is 999 you'll rarely find them in the far corners of the map.

**The potential solution**
Use the actual boundaries of the map to determine where birds spawn.

**The cause**
Probably around [here](https://github.com/OpenRCT2/OpenRCT2/blob/6d0bb48b68a2f35676ef4246ae4165bf242232cd/src/openrct2/entity/Duck.cpp#L303-L317). Might be a good first issue for anyone who wanna pick it up. :)

### Area(s) with issue?

The bug also exists in RCT2 (vanilla)

### Steps to reproduce

1. Create a 999x999 map.
2. Go 255 tiles out from 0,0.
3. Spawn a buttload of ducks with the "Create Ducks" cheat.
4. See your army spawn at the 255 tile line.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by zuczek4793**
Fix #16565: birds/ducks spawning at fixed 255-sized map boundary.

Instead spawn at actual map boundary (MapSizeMaxXY) where applicable

### CODE REVIEW

**Review by duncanspumpkin — APPROVED** [review]
Can you bump the network version as well.

**Comment by tupaschoal** [comment]
> Can you bump the network version as well.

In case you don't know what we're talking about, you have to increase this number by 1:

https://github.com/OpenRCT2/OpenRCT2/blob/b90814369d76dcc24144375603bd44706d98de95/src/openrct2/network/NetworkBase.cpp#L45

It's used across multiplayer to check whether people are running different versions of the game which would deviate on some behaviors.

**Comment by Basssiiie** [comment]
I think it needs a changelog entry as well, right?

**Comment by duncanspumpkin** [comment]
> I think it needs a changelog entry as well, right?

This would be under bug in nsf so not changelog worthy

**Comment by Basssiiie** [comment]
> This would be under bug in nsf so not changelog worthy

@duncanspumpkin Maps that are smaller than 255x255 were possible pre-NSF, so the "ducks spawning far away from the map"-part is presumably also a bug in vanilla RCT2.

**Comment by tupaschoal** [comment]
So should we or should we not add a changelog? :P

**Comment by Basssiiie** [comment]
I'd say yes for this part:
> Maps that are smaller than 255x255 were possible pre-NSF, so the "ducks spawning far away from the map"-part is presumably also a bug in vanilla RCT2.
and no for the NSF sized maps. 😛

**Pull request merged**
