### PR TITLE
Don't lock resolutions based on aspect ratio

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
What's the motivation for this change? Personally, I like that the dropdown menu currently does not show resolutions that would change the aspect ratio.

**Comment by AaronVanGeffen** [comment]
That's strange… Well, given that apparently this occurs, I think it would be better to instead set `_resolutionsAllowAnyAspectRatio = true;` if an empty list is encountered when the boolean is `false`, then re-populate the list.

**Comment by janisozaur** [comment]
That'd be a bit annoying, when you suddenly have or don't some resolutions, based on whether your current resolution fails the check or not and with ε = 0.001 it is easy to fall on either side.

**Comment by AaronVanGeffen** [comment]
Then, would picking a bigger epsilon have the desired effect?

**Comment by janisozaur** [comment]
I tested it with 0.1f and it worked

**Comment by janisozaur** [comment]
"it worked" in the sense it didn't crash outright anymore, but other resolutions were still not provided. I'm not particularly bothered by that fact, so I'm leaning to answer "yes" to your question.

The other thing is why is there a hardcoded `_resolutionsAllowAnyAspectRatio`? It should be promoted to a config option (preferred IMO) or dropped.

**Comment by janisozaur** [comment]
Well, I already said why: the epsilon you provided is too small.

**Comment by IntelOrca** [comment]
Try making it bigger then, I don't think removing the filter is a good solution.

**Comment by janisozaur** [comment]
This was updated with requested changes.

**Pull request merged**
