### PR TITLE
remove directsound and get sound working for linux native

### PR DESCRIPTION
**Pull request by zsilencer**

### CODE REVIEW

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/develop/CMakeLists.txt#L84 still links to dsound, can you drop that as well?

**Comment by IntelOrca** [comment]
Rather than commenting code out, can we just remove it? It is not something that is necessary when you have source control.

**Comment by janisozaur** [comment]
I attest that with this change sound works in native Linux build.

**Comment by IntelOrca** [comment]
Yep, and I can remove the DirectSound import from openrct2.exe now.

**Comment by janisozaur** [comment]
oh, this might break things for linux for now. If you do that, can you do it as pull req, so I can merge required changes into yours?

**Comment by IntelOrca** [comment]
Why would it break anything for linux?

**Comment by zsilencer** [comment]
i tested it in linux already and it works fine, that was the point of it

**Comment by janisozaur** [comment]
because of (hacks)[https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2.c#L225]

**Comment by zsilencer** [comment]
why cant you just get the file size with ftell

**Comment by janisozaur** [comment]
https://www.securecoding.cert.org/confluence/display/c/FIO19-C.+Do+not+use+fseek%28%29+and+ftell%28%29+to+compute+the+size+of+a+regular+file

**Comment by IntelOrca** [comment]
what about fstat?

**Comment by zsilencer** [comment]
that link is just being pedantic, it will work fine.  its better than a hard coded for sure and it will eventually be replaced anyway.

**Comment by janisozaur** [comment]
fstat is perfectly fine, but i couldn't get it working then for some weird
reason.

**Pull request merged**
