### PR TITLE
Add small medium and large turns, diagonals and s-bends to Boat Hire

### PR DESCRIPTION
**Pull request by mixiate**
This adds new track pieces to the Boat Hire.

- Small turns
- Medium turns
- Large turns
- Diagonals
- S-bends

boathire

### CODE REVIEW

**Comment by Gymnasiast** [comment]
There seems to be some glitching going on while building this. Although it also seems to affect the 1×1 piece, which was already there. Any ideas as to what’s causing this?

Schermafdruk van 2024-12-01 22-03-38
Schermafdruk van 2024-12-01 22-03-47
Schermafdruk van 2024-12-01 22-03-59

**Comment by karst** [comment]
> There seems to be some glitching going on while building this. Although it also seems to affect the 1×1 piece, which was already there. Any ideas as to what’s causing this?
> 
> Schermafdruk van 2024-12-01 22-03-38 Schermafdruk van 2024-12-01 22-03-47 Schermafdruk van 2024-12-01 22-03-59

Curious if this might be caused by the RCT1 water. Does it also glitch when there's a vehicle on top? 
It probably is z-fighting with the yellow placement overlay.

**Comment by mixiate** [comment]
Ah, I didn't notice because it's slightly less obvious with transparent water. Yeah it's clashing with the tile overlay on the surface, which seems to be an ORCT2 addition? Like you said it already happens with the 1 tile turn, so i've fixed it for all and also added a changelog entry. As far as I can tell, all pieces still draw correctly.

**Comment by Gymnasiast** [comment]
Tested it, but found more glitches. These are present in both fixed and unfixed versions, and also affect the vanilla 1×1 turn (so not unique to this PR):

Schermafdruk van 2024-12-07 22-07-21
Schermafdruk van 2024-12-07 22-09-54

Is this something that is feasible to fix? If not, I can merge as-is.

**Comment by mixiate** [comment]
Do you mean that the oar is not over the track?

**Comment by Gymnasiast** [comment]
Yeah, the car is glitching over the paddle. Though that may also be caused by the vehicle bound box - it doesn’t have to be the track’s "fault".

**Comment by mixiate** [comment]
I don't think the oar is separate? It's been like this for straight and 1x1 turn track since RCT1, unless i'm missing something.

**Comment by Gymnasiast** [comment]
You mean that the paddles are part of the same sprite as the boat, and changing it would cause the entire boat to glitch over/on top of the track?

**Comment by mixiate** [comment]
I took a look at the sprites and the oars are part of the rider sprites, so they are actually separate. But as far as I can tell the games never drew these separately, and I don't think there is a currently a way of doing that. So it's possible to fix but not sure exactly how you'd implement it. Might be out of the scope of this PR.

**Comment by Gymnasiast** [comment]
Makes sense.

**Review by Gymnasiast — APPROVED** [review]

**Pull request merged**
