### PR TITLE
Add missing Expenditure type setting in LargeSceneryPlaceAction

### PR DESCRIPTION
**Pull request by janisozaur**
Claiming first bounty of #11190

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
Is landscaping the correct expenditure type

**Comment by janisozaur** [comment]
I copied it from query. I have also checked all the other actions to see if they set out correctly - they do.

**Comment by janisozaur** [comment]
Small scenery uses the same: https://github.com/OpenRCT2/OpenRCT2/blob/12ab701a0fc89e1e12a3724ebef164ae4c111172/src/openrct2/actions/SmallSceneryPlaceAction.hpp#L428

**Comment by janisozaur** [comment]
It seems that it is the best fit: https://github.com/OpenRCT2/OpenRCT2/blob/518780c3e805329489094a688b7851c163a47406/src/openrct2/management/Finance.h#L15-L32

**Comment by duncanspumpkin** [comment]
okay sounds good just wanted to check.

**Comment by Gymnasiast** [comment]
Did this cause a crash because the field contained garbage data?

**Comment by duncanspumpkin** [comment]
It would have tried to set the expenditure as `ExpenditureType::Count` which would I think walk over the end of an array.

**Pull request merged**
