### PR TITLE
Implement track info command

### PR DESCRIPTION
**Pull request by iamthad**
This PR implements a new CLI sub-command `track info` that dumps JSON-formatted information, such as the information shown in the track list screen, about one or more track designs.

When more than one design is given, the JSON-formatted info for each is on its own line, similar to the [JSON Lines](https://jsonlines.org/) format.

This is a two-level command because I envision other `track` subcommands, e.g. `track screenshot` or `track convert`.

### One track:
```sh
$ ./bin/openrct2.exe track info /c/Program\ Files\ \(x86\)/Steam/steamapps/common/Rollercoaster\ Tycoon\ 2/Tracks
/Atomizer.TD6
```
returns
```json
{"average_speed":18,"drops":12,"excitement":7.0,"highest_drop_height":27,"intensity":7.8,"inversions":6,"max_lateral_g":2.24,"max_negative_vertical_g":-1.28,"max_positive_vertical_g":3.2,"max_speed":54,"name":"Atomizer","nausea":4.3,"path":"C:/Program Files (x86)/Steam/steamapps/common/Rollercoaster Tycoon 2/Tracks/Atomizer.TD6","ride_length":986,"space_required":[13,27],"total_air_time":450,"type":51,"vehicle_type":55}
```
### Multiple tracks:
```sh
$ ./bin/openrct2.exe track info /c/Program\ Files\ \(x86\)/Steam/steamapps/common/Rollercoaster\ Tycoon\ 2/Tracks/A*.TD6
```
returns
```json
{"average_speed":2,"excitement":2.1,"intensity":0.2,"max_speed":4,"name":"Aerial Cycles","nausea":0.0,"path":"C:/Program Files (x86)/Steam/steamapps/common/Rollercoaster Tycoon 2/Tracks/Aerial Cycles.TD6","ride_length":209,"space_required":[12,11],"type":72,"vehicle_type":0}
{"average_speed":18,"drops":12,"excitement":7.0,"highest_drop_height":27,"intensity":7.8,"inversions":6,"max_lateral_g":2.24,"max_negative_vertical_g":-1.28,"max_positive_vertical_g":3.2,"max_speed":54,"name":"Atomizer","nausea":4.3,"path":"C:/Program Files (x86)/Steam/steamapps/common/Rollercoaster Tycoon 2/Tracks/Atomizer.TD6","ride_length":986,"space_required":[13,27],"total_air_time":450,"type":51,"vehicle_type":55}
{"average_speed":15,"drops":5,"excitement":5.4,"highest_drop_height":13,"intensity":5.7,"max_lateral_g":1.28,"max_negative_vertical_g":-1.28,"max_positive_vertical_g":2.88,"max_speed":40,"name":"Automania","nausea":4.0,"path":"C:/Program Files (x86)/Steam/steamapps/common/Rollercoaster Tycoon 2/Tracks/Automania.TD6","ride_length":495,"space_required":[18,11],"total_air_time":200,"type":87,"vehicle_type":2}
{"average_speed":13,"excitement":2.9,"intensity":2.6,"max_speed":24,"name":"Automobile Antics","nausea":0.5,"path":"C:/Program Files (x86)/Steam/steamapps/common/Rollercoaster Tycoon 2/Tracks/Automobile Antics.TD6","ride_length":244,"space_required":[14,11],"type":22,"vehicle_type":0}
```

### CODE REVIEW

**Comment by IntelOrca** [comment]
I like the idea of being able to convert or screenshot a track design, but what is the purpose of the json? Is there a particular use case you need it for?

**Comment by iamthad** [comment]
> I like the idea of being able to convert or screenshot a track design, but what is the purpose of the json? Is there a particular use case you need it for?

I found a massive collection of track designs (~60,000 total). It's not feasible to browse through that many in game, so I was hoping to get information about each in a machine-readable format and put together some sort of way to browse through them externally.

Getting screenshots of each would also be a great advantage to this little project, but the JSON output was the easier place to start.

**Comment by IntelOrca** [comment]
@iamthad do you see the JSON output being useful for anyone else though? Just trying to see what the justification there is for including it in upstream. The JSON schema would also need to be agreed on and how new track design formats influence it.

An alternative would be to expose some plugin APIs for enumerating and inspecting track designs, with this you could then just have a plugin which generates the JSON.

**Comment by iamthad** [comment]
Very good points, @IntelOrca.
I suppose, with the appropriate APIs exposed, a plugin could do the trick without adding the maintenance burden to upstream.

I'll close this for now.

**Pull request closed without merging**
