### PR TITLE
Add enhancement to show money effect when peeps make purchases

### PR DESCRIPTION
**Pull request by samhorlbeck**
I got the idea to implement this after playing the recently-release mobile version "Roller Coaster Tycoon Classic." Basically a monetary effect is played whenever a peep makes a purchase, similar to the green `+$x` animation that is played when you delete a path, for example.

I also added a way to enable/disable the feature in the options menu, disabled by default.

P.S. the code base is super easy to read (and thus to contribute to) -- cheers

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
I believe #4983 aims to do this, too.

**Comment by janisozaur** [comment]
This is introducing local global state into core logic, this would cause desyncs.

**Comment by samhorlbeck** [comment]
Alas. Wasn't sure how to avoid global state when adding an option to the rendering menu

**Comment by marijnvdwerf** [comment]
Not a fan of this implementation as-is.

- The diagonal movement combined with not-fading out makes it really hard to see where the amount originates from. I think this could be a lot more visually pleasing if the amount floated upwards (maybe with a slight wave) and fades out. But that's impossible with the current palette-based rendering.
- Cash spent is also shown in the title sequence.
- The amount is always rounded up. It's a bit weird to see '€1' float away when the price was €0,10.
- Adding an option and then disabling it by default pretty much is a waste of implementation effort.

**Comment by samhorlbeck** [comment]
Fair enough. I know it's severely limited as all I can control wrt animation is the direction/speed (not the animation). Vertically looked even worse in my testing so I opted to go with the diagonal. Same thing with the fractional amounts of money. Since I'm just using the standard rendering I don't know how I'd do it otherwise. I'm guessing it would take a much deeper dive into the code.

I made it disabled by default precisely for the reasons you mentioned--it's obviously not ideal, but I do think it adds a lot to the gameplay. The visual feedback of making money (and seeing where it comes from) is very satisfying.

**Comment by IntelOrca** [comment]
@samhorlbeck stopping it from showing in the title sequence should be easy enough. For showing it as a fraction, you will need to edit the drawing code for it.

https://github.com/OpenRCT2/OpenRCT2/blob/efb64603eb5d62f2c48844644aa278eb5f2d5ce3/src/openrct2/paint/sprite/misc.c#L52

**Comment by samhorlbeck** [comment]
Sorry, didn't mean to click the close button :P

**Comment by Gymnasiast** [comment]
I'm not sold on the idea. It adds too much noise for my liking. That being said, I won't veto it if the rest of the team wants it.

**Comment by IntelOrca** [comment]
I originally made a PR for this and closed it for this. Given its in the mobile version of the game, I think its nice to have this.

**Comment by Gymnasiast** [comment]
Just because it's in the mobile version does not mean it's a good feature. I'd like to hear what it _adds_.

**Comment by marijnvdwerf** [comment]
Whilst playing, you notice more what parts of your park are doing well, as opposed to a number in the bottom of the screen changing. It's a small reward for players, same as a coin/score moving upwards in Super Mario Bros.

**Comment by IntelOrca** [comment]
@Gymnasiast you didn't show much concern for https://github.com/OpenRCT2/OpenRCT2/pull/4983

**Comment by Gymnasiast** [comment]
@IntelOrca My reaction in that PR should make it clear I had my reservations, even though I wasn't going to block it. So I'm not sure where you got that impression from.

**Comment by rwjuk** [comment]
I tried this out - going in I thought I'd have a similar reaction to @Gymnasiast, but I actually quite like it. That said, the fractional display issue would need solving, otherwise it's incredibly confusing.

**Comment by IntelOrca** [comment]
I will finish this PR.

As for whether its enabled by default. I will make it disabled as I think the majority of people will want it disabled. We already have a lot of other new features which are off by default - like almost all the RCT1 look-and-feel options.

**Pull request merged**
