### PR TITLE
Prevent going over _windowNewRideListItems

### PR DESCRIPTION
**Pull request by janisozaur**
Though this may not be preferred way of fixing it, as it may only hide the bug instead of solving it

### CODE REVIEW

**Comment by IntelOrca** [comment]
The fix should be in `window_new_ride_populate_list`, its obviously adding to many entries to the list.

**Comment by IntelOrca** [comment]
Add the asserts https://github.com/OpenRCT2/OpenRCT2/pull/4396 to this PR

**Comment by IntelOrca** [comment]
Still working on this?

**Comment by janisozaur** [comment]
I'm not sure how the fix to `window_new_ride_populate_list` should look like.

**Comment by IntelOrca** [comment]
The problem is that `window_new_ride_populate_list` is overpopulating the list. Don't let it.

**Comment by IntelOrca** [comment]
@janisozaur I can take ownership of this, but are you able to provide a saved game that reproduces the issue?

**Comment by janisozaur** [comment]
Later today

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/files/512174/whiskey_s2_nogo64_2.sv6.zip

**Comment by janisozaur** [comment]
@IntelOrca ping

**Pull request closed without merging**
