### PR TITLE
Update OpenMusic to version 1.3.0

### PR DESCRIPTION
**Pull request by karst**

### CODE REVIEW

**Review by ZehMatt — APPROVED** [review]

**Comment by karst** [comment]
I require an opinion. Should we just release the translations like this, or should we also add the fairground organ and ragtime style, which I was saving up for 0.4.6 but we have something else for openmusic planned for 0.4.6 as well.

If we do want to include the Fairground Organ/Ragtime right now I will make sure to update the links and update the changelog.

**Comment by ZehMatt** [comment]
Is this PR updating the translations or is it also adding new music? We should keep PRs single topic if possible.

**Comment by karst** [comment]
I mean I could turn it into a follow up PR instead, but now it just adds new music and the translations are a bonus. They're already seperate PRs on OpenMusic.

**Comment by ZehMatt** [comment]
Fine by me

**Pull request merged**
