### PR TITLE
Added console logging for failed map saves

### PR DESCRIPTION
**Pull request by phillipwalters**
Done to help debug https://github.com/OpenRCT2/OpenRCT2/issues/8701

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
Try not to close and reopen the same PR. I know why you did it but try to avoid it. You will find in future that you don't have as many problems if you use branchs when using git. The idea is you never commit to the develop branch. You branch of develop into a feature branch then make your commit. This means you are able to keep develop up to date and you can rebase the feature branch on top of the latest develop. I find this guide has a good intro as to how things work https://www.atlassian.com/git/tutorials/comparing-workflows We follow gitflow on this project.

**Comment by duncanspumpkin** [comment]
Appveyor had a little mess up but this does pass https://ci.appveyor.com/project/IntelOrca/openrct2-ject9/builds/23120018

**Comment by phillipwalters** [comment]
I'll make sure to not do that in the future. I thought it might be bad form, but the state I was in was hopeless. I'll take a look at the tutorial. I was actually looking for that the other day.

**Comment by duncanspumpkin** [comment]
Its fine. Everyone makes mistakes. :). If you look back to the first couple commits I did I merged much worse nonsense into the main branch.

**Pull request merged**
