### PR TITLE
Update duktape to v2.7.0

### PR DESCRIPTION
**Pull request by janisozaur**
A somewhat bloated change due to duktape changing their code style

### CODE REVIEW

**Comment by janisozaur** [comment]
I've done test compilation with clang, but it appears it can't really work. No idea how come clang doesn't complain

**Comment by IntelOrca** [comment]
I don't think you have generated duktape with all the required settings, see https://github.com/OpenRCT2/OpenRCT2/tree/develop/src/thirdparty/duktape

**Comment by janisozaur** [comment]
I've followed the provided readme and used all three options:
`python2 ~/Downloads/duktape-2.7.0/tools/configure.py --output-directory src/thirdparty/duktape     -DUK_USE_CPP_EXCEPTIONS    -DUK_USE_DATE_NOW_WINDOWS    -DUK_USE_INTERRUPT_COUNTER`

**Comment by janisozaur** [comment]
ok, the readme is wrong and the options are *not* enabled the way readme says they are

**Comment by IntelOrca** [comment]
It did look like `DDUK_USE_EXEC_TIMEOUT_CHECK` was missing from the readme, but also that seems to require manual intervention for some reason.

But I also saw in your last commit, it added a `#undef CPP_EXCEPTIONS` line, so for some reason your option to enable CPP exceptions was not being used either.

**Comment by IntelOrca** [comment]
There don't seem to be any source changes now in this PR.

**Comment by janisozaur** [comment]
I reused 2.6.0 by mistake, resubmitted with 2.7.0 now

**Review by IntelOrca — APPROVED** [review]

**Comment by Die4Ever** [comment]
at a quick glance, it seems to work with my Randomizer plugin

**Pull request merged**
