### PR TITLE
Check access to _97AF32

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Why the thumbs down, @marijnvdwerf ?

**Comment by marijnvdwerf** [comment]
Because the cause of the issue is known; as is the solution. That part of
the code checks if the desired segment is free, and otherwise attempts
several fallback positions. After adding to the pointer, the function
returns at this point. So removing the line makes more sense.

Op do 1 sep. 2016 om 10:55 schreef Michael Steenbeek <
notifications@github.com>

**Comment by janisozaur** [comment]
@marijnvdwerf would you fix it then please, when you know the best how to do it?

**Comment by duncanspumpkin** [comment]
This code needs to be refactored. There is also a bug in it. If i have the time on the weekend I will try take a look at this.

**Comment by marijnvdwerf** [comment]
In my opinion it would be better to wait with refactoring until the other supports are decompiled. metal_supports_b looks to be fairly similar to metal_supports_a, and I expect one of the path supports to match as well.

**Comment by duncanspumpkin** [comment]
I've checked what @marijnvdwerf is talking about this can never happen. I'll remove the line.

**Pull request closed without merging**
