### PR TITLE
Png saves

### PR DESCRIPTION
**Pull request by janisozaur**
This allows OpenRCT2 to use PNG as save games. Yes, you read that right :D

This is work in progress for now, it requires at least:

- [ ] adding savegame compression (lodepng already offers builtin deflate)
- [ ] coming up with our proper header
- [ ] proper handling of buffer for save game
- [ ] fixing memory leaks
- [ ] proper UI

For the sake of testing, you can check this attached *save game*:

scr5

NB: github allows big PNGs to be attached to issues, but imgur will convert all your PNG over 1MB to jpg (hence the need for deflation)

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
This is just bloat to the code base.

**Comment by Gymnasiast** [comment]
Perhaps it's a better idea to keep this until we create our own format, then? That new format could be made PNG compatible by default, considering it doesn't have to be compatible with SV6.

**Comment by duncanspumpkin** [comment]
Or we could not highjack an image format for something that isn't an image. Zip would make sense png no.

**Comment by Gymnasiast** [comment]
The whole point of it is easy sharing of both the park and the image. I don't think this "hijacking" as you call it is a bad thing.

**Comment by janisozaur** [comment]
PNG, a chunk-based format, natively supports such scenarios (see private and ancillary bits) and it was available in the wild before (one that comes to my mind is spore/sporepedia).

ftp://ftp.simplesystems.org/pub/png/documents/png-1.2-pdg.html#Chunk-naming-conventions

**Comment by vzybilly** [comment]
I am for this, makes it easy to browse the save game files from non game.
an enhancement could be to have it take a screen shot that covers the whole
world, adds the save file, then saves it. maybe by another save option,
like an export, or a check box added to the save dialog...

**Comment by PFCKrutonium** [comment]
This sounds like a great idea, and I would like to note, Most image formats that don't support this will actually work too - I made a jpg with a large rar file appended for no real reason, and both chunks of data were usable by their respective applications.

copy /b image.png,data.rar newimage.png

**Comment by Patrik356b** [comment]
Whoa, I expected this thing to be dead today. Feels good that it's not
obsolete yet.

**Comment by janisozaur** [comment]
Regarding concatenating image and other files together:
While working, it's a fragile solution. This works because image formats commonly place their header in the beginning of the stream, while archives commonly place it at the end, hence you can have such a file. It's rather fragile, as any program that modifies png will probably strip or invalidate remaining contents, if it (the image) doesn't break it (the program) in the first place.
Solution I present here is much more robust, being a native feature of the format designed for precisely such scenarios. PNG chunk used here has bits of a specific meaning:
- private chunk (i.e. not registered as one of official chunk headers)
- ancillary (not critical to display the image)
- safe to copy (not depending on image data and should be copied to resulting PNG file even when the image is processed with a program that does not recognise such chunk)
I ran the attached save file through a PNG optimizer and the save was still loaded just fine. There are options to strip unknown chunks from PNG files, should the user want that.

The savegame–screenshot bond is getting more and more popular, you can see Google Play Games Services, Cities: Skylines, Wiedźmin as just a few examples, it helps the user to quickly find out what's the status of the save.

**Comment by IntelOrca** [comment]
Its a nice idea but there are some considerations:
* It is not immediately obvious that a .png image actually contains a saved game.
* People may share and use the .png image without knowing that there is a saved game in it. Perhaps if they wanted to store it locally or on a HTTP server with no intention of using it as a saved game.
* Players may try to load .png files which are not saved games expecting it to work and getting frustrated when they are unable to determine which images contain saved games or not.
* Modifying the .png is likely to remove the hidden saved game data.
* .png can't be shell associated with OpenRCT2 (because it shouldn't be!) with .sv6 we can double click that to automatically launch OpenRCT2.

Perhaps this should be a command line utility instead... ```openrct2 save2png ...```

For uploading saved games to GitHub, perhaps we can dedicate our own file share which has dedicated support for saved games. For example @runelaenen has already created CoasterCloud which automatically generates screenshots of the saved game using OpenRCT2. Perhaps this could be extended to allow quick drag-drop upload of saved games for sharing on here.

**Comment by janisozaur** [comment]
My general vision of this is:
- Add another option labelled "Save game with screenshot" or some other descriptive text
- Leave exisiting functionality working exactly as it is (so you can still do a screenshot or save game without triggering the other)
- Add an option to settings specifying if the user wants current viewport screenshot or the giant one
- (optional) add overlay to the image saying "This image contains save game"

While I see your points as completely valid @IntelOrca, none of them truly excludes this feature. One thing to address would be better (in-game) stating that the file used contained no save game.

I already addressed concerns about modifying the image.

**Comment by HaasJona** [comment]
I don't know about Windows, but Linux will usually display png previews even if the file has some other file suffix than png because it looks at the file header. So i think it would generally be great if saves would also be png images with just a different file ending. The png images could also be used in the load savegame dialog as a preview.

My biggest concern is that this will be breaking save compatibility.

**Comment by janisozaur** [comment]
@HaasJona breaking how?

**Comment by HaasJona** [comment]
Just saying that RCT2 will not be able to open png files. So we probably will need to support 2 different file formats as long as we want compatibility.

**Comment by RobertWHurst** [comment]
Very cool. This reminds me of the way Macromedia implemented Fireworks projects. Fireworks projects were saved as raster PNG files so they were viewable anywhere, but also contained all the vector data for the project. The amazing thing thing about Fireworks is that it has very similar features to Photoshop such as complex filters and layers, but the project files were tiny because all of the data for the project was saved as vector data imbedded into the png.

Anyways very cool idea. Cheers you guys :beers:

**Comment by PFCKrutonium** [comment]
Too bad when Adobe absorbed Macromedia they dropped that :(

**Comment by RobertWHurst** [comment]
@PFCKrutonium Yeah for sure. I think the Macromedia team had some quite novel engineering ideas.

**Comment by Chnkr** [comment]
You could just serialize the game data and stuff it into a PNG `zTXT` header

**Comment by devnoname120** [comment]
Material on the subject that is worth reading: http://themeparkitect.tumblr.com/post/126855975857/update-58

**Comment by Patrik356b** [comment]
While not ideal, but still might be worth considering is filename.sv6.png

**Comment by PFCKrutonium** [comment]
That is a very interesting solution they came up with for that (Parkitekt)...

**Comment by Joshwoo69** [comment]
I suggest making it a config option

**Comment by devnoname120** [comment]
@Patrik356b :thumbup: It would avoid confusing users whether a screenshot is a save or not. In addition, we could put some caption like “OpenRCT2 Save data” with the logo.

**Comment by Gymnasiast** [comment]
Ok, this PR did generate a lot of discussion. It's a nice idea and effort in any case.

Advantages:
- Easy sharing of both the park and a screenshot, including when opening an issue here.
- It's a cool feature.

Disadvantages:
- The data may be stripped away by some programs and websites.
- It's not immediately obvious to people it contains a save (this can be addressed).
- We cannot associate OpenRCT2 with PNG files, while we can associate it with SV6 and eventually our own format (SV8?).
- The file open dialog will have to show every PNG file, even those not containing an SV6.
- It still has all the limitations of SV6, while lacking the advantage of being able to be read by RCT2.

Since most of the disadvantages cannot be addressed, at least not now we're still on SV6, I'm going to close this. As far as I'm concerned, when we move to our own format we should look at/discuss PNG capabilities again.

**Pull request closed without merging**
