### PR TITLE
Remove unused function

### PR DESCRIPTION
**Pull request by Broxzier**

### CODE REVIEW

**Comment by janisozaur** [comment]
It had warning [C4505](https://docs.microsoft.com/en-gb/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4505) explicitly hidden, why was it done this way?

**Comment by janisozaur** [comment]
@IntelOrca I don't see where it is used - there is no call anywhere. There is also no comment specifying where it might be used, nor is it guarded by any kind of `#ifdef DEBUG`.

If it really is meant for debug purposes, please mark it so in a comment and add `[[maybe_unused]]` attribute.

**Comment by Broxzier** [comment]
@IntelOrca Unlike `AllocatedListRemove` it isn't being called anywhere though. Do you still want to keep it in?

**Comment by IntelOrca** [comment]
> I don't see where it is used - there is no call anywhere.

It is for diagnosing issues. It is there to be used when it is required.

> nor is it guarded by any kind of #ifdef DEBUG

Can you not see the line that says `#ifdef DEBUG` 5 lines about it?

> If it really is meant for debug purposes, please mark it so in a comment and add [[maybe_unused]] attribute.

I will next time. I don't know if `[[maybe_unused]]` could even be used when I added it nor was I even aware of such attribute.

**Comment by janisozaur** [comment]
> Can you not see the line that says #ifdef DEBUG 5 lines about it?

I can and I have not paid attention. I'm sorry.

**Comment by Broxzier** [comment]
It looks like Visual Studio doesn't support C++17's `[[maybe_unused]]` fully, as it keeps giving warning C4505. Probably because it's a static function. Clang does it correctly, and doesn't generate a warning when given the `[[maybe_unused]]` attribute.

Someone already repoted it: https://developercommunity.visualstudio.com/content/problem/244236/c-attribute-maybe-unused-is-ignored-for-static-fun.html

**Comment by janisozaur** [comment]
@Broxzier @IntelOrca can you then add `[[maybe_unused]]` attribute with maybe a link to discussion in this PR and link to the reported defect (to explain the warning push/pop)?

**Pull request merged**
