### PR TITLE
Demolish entrance fix

### PR DESCRIPTION
**Pull request by martip23**
I'm having a bit of an issue I've added an if statement within != track to check for station entrance but I now get an error every time a ride is demolished 

image

I am trying to modify the code on 314 by wrapping it in an if statement and creating two game_do_command for track or park entrance but it seems to be introducing more bugs. 

Assistance in fixing this issue would be appreciated!

### CODE REVIEW

**Comment by martip23** [comment]
I think I've found a mistake. Is the TILE_ELEMENT_TYPE_ENTRANCE the park entrance type? Like not a ride entrance, but a park entrance. So I should be checking something else.

**Comment by martip23** [comment]
So I think both are entrances. The park entrance and ride entrance, but one has an entrance ID and a ride ID. This will be useful. 😂

**Comment by martip23** [comment]
Is there some kind of special action that removes a station platform? I am getting a weird bug where the station platform tiles without an entrance/exit attached to them are not deleting. I am just going to create a second loop which will iterate through the tiles to find leftover entrances. I feel like it's inefficient but I will submit the request and am open to feedback.

**Comment by martip23** [comment]
I've tested the code and it seems to be working correctly now.

**Comment by AaronVanGeffen** [comment]
I hope you had fun working on this! Thank you for your PR.

Unfortunately, I have to be the bearer of bad news for this one. #7932 has tackled the same issue, but has come up with a slightly more efficient way of doing it. After some deliberation in the team, we've decided to go with that one.

**Pull request closed without merging**
