### PR TITLE
Show vehicles from other track types

### PR DESCRIPTION
**Pull request by Gymnasiast**
Introduces a cheat option that allows the player to pick a vehicle from another track type:

scr123

By the way, it seems that dropdowns start acting weird for entries beyond 31 (counting from 0): the selection caret will not display properly and not every entry beyond 31 can be selected. This is the result of overflowing, but I'm not sure the dropdown structures can be expanded currently.

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Launched freefall cars or jet skis on a roller coaster? It's an interesting thought, I guess.

**Comment by duncanspumpkin** [comment]
All dropdown code has been implemented unless I'm completely wrong. You should be fine changing the structure. There are a couple things that really need to be changed related to the dropdowns.

**Comment by vzybilly** [comment]
it's a cheat anyway... I like the idea of having all but if it's to...
insane, I could see splitting it up as "sane " and "all" options... sane
will limit the list, which for the most part would be water trains for
water rides and coasters trains for land rides... but I do like the idea of
having all available for all...

I also think that the drop down would only be gui code, ie, not in the save
which would most likely not break anything if changed... if the original
code doesn't like it, I feel it wouldn't be that hard to fix it up...

**Comment by Gymnasiast** [comment]
@duncanspumpkin : I wasn't sure whether that was possible, as I got strange behaviour when I changed the size of the scrollbar structures (in an attempt to fix long object lists) not very long ago.

**Comment by IntelOrca** [comment]
You should be able to have 64 items on a dropdown. It will just be a case of making sure its still isn't using int32 for anything still.

**Comment by vzybilly** [comment]
depending on the size, there might be overflow in memory... I'm not sure
how things are made/used around this...

**Comment by IntelOrca** [comment]
@Gymnasiast The following needs to be changed:
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/windows/dropdown.c#L56

Line 56 and 57 need to be uint64. We should also make gDropdownItemsDisabled a normal variable now rather than a pointer to RCT2 memory.

**Comment by vzybilly** [comment]
I've seen dropdowns with scrollbars... that could be a remedy...

I also think 16/24 would be a good cap for dropdown items on the screen, in the case for smaller monitors... and ease of mouse moving...

**Comment by Gymnasiast** [comment]
I will change the dropdowns.
Also, @vzybilly makes a good point. It would be a good thing to implement some time. I will add it to my list of ideas.

**Comment by Gymnasiast** [comment]
I have extended the dropdowns code. However, I cannot highlight or select many entries with indices higher than 32. As I haven't been able to find a solution yet, I figured I'd upload it so you could take a look.

**Comment by IntelOrca** [comment]
@Gymnasiast I have PRed the fixes for you.

**Pull request merged**
