### PR TITLE
Make doors work with every vehicle, closes #5951

### LINKED ISSUE #5951: Open doors when any train passes through
Walls with doors in them can only be placed on certain rides (like ghost train, car ride or wild mouse), but with cheats, they can be placed on any ride (like a wooden coaster or mini golf). The sad thing is that the doors no longer open and close when a train passes.
Feature request: properly open and close doors when used on any tracked ride, not just a small selection.

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by IntelOrca** [comment]
Update changelog?

**Comment by Gymnasiast** [comment]
1) Not sure, you still need zero clearance for it work.
2) Yes, but only when it's otherwise OK to merge.

**Comment by jensj12** [comment]
"Doors now work when on track they can't be placed on without cheats"?

**Comment by Gymnasiast** [comment]
I updated the network version and the changelog.

**Comment by Patrik356b** [comment]
Could we get the doors to work with peeps, i.e. on the Minigolf attraction?

**Pull request merged**
