### PR TITLE
Option for early scenario completion

### PR DESCRIPTION
**Pull request by thyeggman**
Allows completion of scenario before end date.  Scenario still fails if the user reaches the end date without achieving all the goals.

UPDATE: new picture
image

### CODE REVIEW

**Comment by Gymnasiast** [comment]
This option is not an interface tweak. And I'm still not sold on 'early completion', it goes directly against what timed goals are there for - subtaining a number of guests/park value.

> That could be a sub-option like "Allow recording scenario completion when completing early".

Oh please, we have way too many options already. Too trivial.

**Comment by AaronVanGeffen** [comment]
First off, I am in favour of including such an option for speedrunning purposes.

I'm inclined to agree with @Gymnasiast this may not the best spot to put it, though. Problem is, we don't really have a section in the options window dedicated to this sort of thing, so I can see why you've put it there, really.

As for the possible sub-option, I agree that would be too trivial an option. Go one way or the other.

**Comment by Gymnasiast** [comment]
Registering the first time the player reached the goals (sans the time limit) in the high scores table is fine in my book. I don't think it should then be marked as completed.

**Comment by IntelOrca** [comment]
I think this should be part of the objective criteria, for example if `gScenarioObjectiveYear` is set to -1 or 0 then it means no time limit. This then allows new scenarios to not have a time limit and complete as soon as the player reaches the goal.

All the speed run stuff then has to do is force all the scenarios to have no time limit (kind of like a cheat might do).

**Comment by thyeggman** [comment]
@IntelOrca I think that having no time limit is different than what I'm trying to do.  I _do_ want the scenario to fail if the player hasn't achieved all the objectives when the time limit is reached, but allow them to complete it early.

@AaronVanGeffen Do you have a suggestion as to how to enable this, then?  Would you prefer it to be a cheat?  My concern is then that cheats aren't persistent, you would have to manually set them for each game.

I'll have to look and see if I can find a way to decouple high scores vs. completion, but I don't really know how that's supposed to work.  Play reaches goals, can open park window and see completion, but `scenario_success()` isn't called somehow?  That seems like a much more disruptive change to me.

**Comment by AaronVanGeffen** [comment]
@thyeggman Well, the group in question ("Tweaks") was originally intended for interface tweaks. If you're going to add more speedrunning options, I'd be fine with you adding a new group to the tab in question. I'd personally be fine with you putting it off until a later iteration, but the option is a little out of place in the group as-is, yes.

**Comment by thyeggman** [comment]
Ok, I'll add it to a new group.

With my current plan (one PR for this, one PR for "Next Level" button and one PR for days calculation/time calculation), would you be OK with "Next Level" and time calculations be default, or would you prefer one/both of them be options?

**Comment by thyeggman** [comment]
@Gymnasiast I see where I misunderstood now on the "interface" comment.  For clarity, could I also change the "Tweaks" heading to "Interface Tweaks"?

**Comment by AaronVanGeffen** [comment]
> would you be OK with "Next Level" and time calculations be default, or would you prefer one/both of them be options?

I'd be fine with having a "Continue to next scenario" button by default. Preferably, it'd show up *after* the player has entered their name for the scenario table, not before, because they lose the option when the new scenario has loaded.

> I see where I misunderstood now on the "interface" comment. For clarity, could I also change the "Tweaks" heading to "Interface Tweaks"?

It really isn't a good label — I'll take the blame there, as I introduced it. The proposed change is fine with me. I'd also prefer the group to stick to bottom — I think those tweaks are the least interesting options to most players.

**Comment by Gymnasiast** [comment]
> Ok, I'll add it to a new group.

We have a miscellaneous tab where stuff like this should go.

**Comment by thyeggman** [comment]
It's already in the miscellaneous tab.  I meant adding it to a new `WIDX_GROUPBOX`.

**Comment by LRFLEW** [comment]
>I think this should be part of the objective criteria, for example if gScenarioObjectiveYear is set to -1 or 0 then it means no time limit. This then allows new scenarios to not have a time limit and complete as soon as the player reaches the goal.

I don't disagree with this idea, but it's not a replacement for this feature. In the original game, a lot of time was spent well past the target goal, and just waiting for the time to pass. This is mitigated **somewhat** by the fast forward feature, but it's just a band-aid solution to the problem (especially without the developer-option-hidden 64x speed). This isn't removing the time limit, as you can still fail the scenario if you don't hit the goal in time. 

This whole thing feels like a pedantics issue, as it's the difference between "**at** the deadline" and "**by** the deadline".

As to whether to count the completion or not, I see no reason not to count it. The "completion" is stored locally, so we don't need a *universal* definition of "completion". Even so, they're still fundamentally achieving the same basic goal. Plus, we **do** have a button in the cheats window that flags any scenario as completed immediately at any time 😜.

**Comment by thyeggman** [comment]
Can we merge this?  Or do I need to make other changes?

**Comment by AaronVanGeffen** [comment]
I'm afraid it requires rebasing before it can be merged… It also requires some independent testing, still. Sorry it's taking a while… We've all been a little busy IRL.

**Comment by thyeggman** [comment]
That's no problem, just wanted to make sure it was still in mind 😃 

All the checks have passed - is the rebasing just a convention that you use?  In any case, I'll do that soon.

**Comment by AaronVanGeffen** [comment]
It's mostly because of GitHub not allowing us to merge with one click if there's a conflict. It often happens when string ids have been usurped in the mean time, for example.

Cheers for taking it up, anyway. In case you need any technical assistance, feel free to ask on Gitter, of course.

**Comment by AaronVanGeffen** [comment]
Rebased and tested. Was able to complete Forest Frontiers early with little effort, so the guests objective is working, at least.

**Comment by thyeggman** [comment]
Sorry for my inactivity... Work has been killer the last few weeks.  What's left for me to do?

**Comment by AaronVanGeffen** [comment]
You could add yourself to the contributors.md file, I guess.

Please note you'll have to update your local branch first, to account for the rebase. (NB: fetch and reset, do not merge.)

**Comment by thyeggman** [comment]
Sorry again for the slowness, I've rebased onto develop.  Let me know if it looks good.

**Comment by AaronVanGeffen** [comment]
> I've rebased onto develop. Let me know if it looks good.

Unfortunately, it reverted several changes. I've rebased to compensate.

**Pull request merged**
