### PR TITLE
Allow building on-ride photo elements underground

### PR DESCRIPTION
**Pull request by Gymnasiast**
Several rides have their on-ride photos underground. (One of them is Pepsi Max Big One in Blackpool Pleasure Beach, for which CS even had to circumvent this limitation when he included it with RCT1.)
For this reason, this PR allows building them underground.

### CODE REVIEW

**Comment by IntelOrca** [comment]
So you know what `TRACK_ELEM_FLAG_0200` means now?

**Comment by LinusU** [comment]
Seems like it when looking where it's used as well:

https://github.com/OpenRCT2/OpenRCT2/blob/d8a2ee47b8cc7ba858fc629f720f7255a6c4be59/src/ride/track.c#L1140-L1145

https://github.com/OpenRCT2/OpenRCT2/blob/d8a2ee47b8cc7ba858fc629f720f7255a6c4be59/src/ride/track.c#L1148-L1153

**Comment by Gymnasiast** [comment]
@IntelOrca I already knew weeks ago, because of the exact code segments Linus has pointed to. I put in a comment on one of Marijn's PRs, but it wasn't picked up back then.

**Comment by duncanspumpkin** [comment]
Yeah name them so it's not forgotten again

**Pull request merged**
