### PR TITLE
Fix #2750 invalidate top toolbar when toggling the use of money.

### LINKED ISSUE #2750: Toggling "No money" causes toolbar drawing glitch
Toggling "No Money" in Cheats -> Park parameters -> Financial causes the toolbar button layout to change, but the toolbar doesn't get completely invalidated

### PR DESCRIPTION
**Pull request by Broxzier**
~~Whoops, I messed something up, only the last commit should be here.~~ Fixed now.

### CODE REVIEW

**Comment by IntelOrca** [comment]
You probably want to close the finance window and and windows that are on finance tabs.

**Comment by Broxzier** [comment]
@IntelOrca: Right, there are a lot of windows that have a tab for money that also need to be solved. Park, guests, rides, ride list.

**Comment by IntelOrca** [comment]
It might be easier to check if money is enabled in the invalidate or update event for all those windows, and if its not enabled, change tab.

**Comment by Broxzier** [comment]
@IntelOrca: That's exactly what I am doing at the moment :P

**Pull request merged**
