### PR TITLE
Restore removed coaster colour presets

### PR DESCRIPTION
**Pull request by ZeeMaji**
Restores some default coaster colour presets from vanilla RCT2 that were removed in #20119, going by the comment from gymnasiast there it seems like these were not intended to be removed and the discussion in #20311 suggests they shouldn't have been removed.

A few of these are similar to some of the new color presets added to the same ride types (the ones i've highlighted with purple tiles in the screenshot below) but i've included them anyways for now.

This also removes some colors from the inverted impulse coaster that were accidentally copied from the inverted hairpin coaster in https://github.com/OpenRCT2/OpenRCT2/pull/11987

Screenshot_select-area_20231014101303

### CODE REVIEW

**Comment by SpartanFrederic104** [comment]
Wasn't there also another track color preset for the Inverted Impulse Coaster from RCT2 vanilla that got removed too? If I remember correctly, it consisted of bright purple track and bordeaux red supports.
Fred's Workbench 2023-10-13 14-55-43

**Comment by ZeeMaji** [comment]
> Wasn't there also another track color preset for the Inverted Impulse Coaster from RCT2 vanilla that got removed too? If I remember correctly, it consisted of bright purple track and bordeaux red supports. Fred's Workbench 2023-10-13 14-55-43

I just went by what was removed in #20119, however if you can confirm that this is a preset colour in vanilla then i can go ahead and add it to this PR.

**Comment by ZeeMaji** [comment]
I just checked for my self in RCT classic and this indeed appears to be a color that was missed somehow, how interesting. I wonder how that happened? I'll work on adding it to my PR shortly.
Screenshot_select-area_20231014093058

**Comment by ZeeMaji** [comment]
There also appears to have been a red and yellow one that was missing too! I'll add these as well.
Screenshot_select-area_20231014093756

**Comment by ZeeMaji** [comment]
Hmm this is strange, it appears the following colors were accidentally added to the inverted impulse coaster in #11987 which replaced the original colors, as seen by a very early version of the ride data file in #6984 (ctrl + f impulse)

        { COLOUR_BRIGHT_YELLOW, COLOUR_BRIGHT_YELLOW, COLOUR_BRIGHT_RED },
        { COLOUR_BLACK, COLOUR_ICY_BLUE, COLOUR_BLACK },
        { COLOUR_WHITE, COLOUR_WHITE, COLOUR_YELLOW },

It seems as though these colors were accidentally copied from the inverted hairpin coaster to the inverted impulse coaster during #11987 and left the original colors from vanilla lost. 

Screenshot_select-area_20231014095707

Since this definitely appears to be a mistake i will remove the hairpin colors from the impulse coaster

**Comment by tupaschoal** [comment]
Thoughts @karst and @Gymnasiast ?

**Comment by karst** [comment]
Per my statement on #20311 I removed them initially at keeping the coats of paint fresh, there were some subjectively ugly paints that we voted out. If people really miss them I don't mind getting them back in.

**Comment by ZeeMaji** [comment]
While i was initially creating this PR i got some generally positive thoughts in the discord from a few people. so there are a few other people who miss them.

**Comment by Gymnasiast** [comment]
I remember the discussion about the colour schemes revealing that what I considered ugly-as-hell styles were liked by others. As such, I think keeping the old ugly ones and just adding to them (what this PR is about) is, on balance, probably better.

I agree the Inverted Impulse schemes are probably a mistake - frutiemax and I created those styles essentially by just manually copying things over, so it’s not surprising the occasional mistake slipped in.

I hope that answers all outstanding questions here (as the conversation is quite long) - if I left anything unclear please say so.

**Comment by tupaschoal** [comment]
It does, thanks @Gymnasiast . @ZeeMaji would you please rebase it so we can merge it, then?

**Comment by ZeeMaji** [comment]
Hopefully that did the trick, it's been a long while since i last did this.

**Review by tupaschoal — APPROVED** [review]

**Pull request merged**
