### PR TITLE
Invention List Window Class Refactor

### LINKED ISSUE #13794: Refactor window to class: Research
See #13737 for more details.

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Close #13794

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Works correctly, save for one thing. When dragging a name, the horizontal bar that shows where the item will end up does not move.

See this example. I am dragging “Plonsboten” from the bottom to the top. The horizontal bar should be between “Informatiekiosk” and “Frisdrankkraam”, but instead it remains below “Compacte omgekeerde achtbaan”.

afbeelding

**Comment by duncanspumpkin** [comment]
> Works correctly, save for one thing. When dragging a name, the horizontal bar that shows where the item will end up does not move.
> 
> See this example. I am dragging “Plonsboten” from the bottom to the top. The horizontal bar should be between “Informatiekiosk” and “Frisdrankkraam”, but instead it remains below “Compacte omgekeerde achtbaan”.
> 
> afbeelding

I believe that is how it currently works. I tested it before i made the changes because i was surprised as i thought the line used to move

**Comment by Gymnasiast** [comment]
I’m quite sure it did move, but apparently this broke at some point. 

Would you be able to fix it?

**Comment by duncanspumpkin** [comment]
> I’m quite sure it did move, but apparently this broke at some point.
> 
> Would you be able to fix it?

I'll investigate but if the error is elsewhere or its going to take a while I'll make it a separate pr

**Comment by Gymnasiast** [comment]
I created https://github.com/OpenRCT2/OpenRCT2/issues/17544 for the dragging issue.

**Pull request merged**
