### PR TITLE
Strip all whitespace

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by danidoedel** [comment]
Most of the whitspaces in the language files are needed. I think you should exclude all the language files.

**Comment by janisozaur** [comment]
is it? can you explain why? @IntelOrca can you confirm?

**Comment by danidoedel** [comment]
A sign would look like "Closed - -Closed - -Closed - -" and not "Closed - - Closed - - Closed" or in shortcut keys it would look like "CTRL + ALT +C" and not "CTRL + ALT + C" ... for example.

**Comment by janisozaur** [comment]
Well enough, updated.

**Pull request merged**
