### PR TITLE
Change max loan interest from 80% to 255%

### PR DESCRIPTION
**Pull request by 733737**
this increases the cap in the scenario editor on max loan interest to 255% from the stock 80%
https://github.com/OpenRCT2/OpenRCT2/discussions/17999

### CODE REVIEW

**Comment by 733737** [comment]
I am being blocked from forking into two PRs, how do I separate into two PRs by commit? can I single out commits and branch them (need help with creating a branch I guess?)

**Comment by Gymnasiast** [comment]
Please wait with creating PRs until you actually get a few replies from people saying that they would like such a change. It saves you from putting effort into creating a PR that might not get merged.

**Comment by 733737** [comment]
Your refactor makes this PR deprecated, so either I should redo the changes on top of your refactor (not sure how) or you could do it for the 1 file in question

**Comment by 733737** [comment]
I copied over your refactor and modified it

**Comment by rik-smeets** [comment]
As said by @Gymnasiast , I'm not sure this is a feature the community wants or needs adding. 

You also shouldn't copy and commit changes from the develop branch into your own, this doesn't resolve merge conflicts and is very confusing. You can read how to rebase your branch [here](https://stackoverflow.com/a/7244456/14145045).

**Comment by Broxzier** [comment]
When making changes, always branch off of develop first. Working directly on develop can get you into tricky situations where your history is not in sync anymore.

**Comment by 733737** [comment]
I'm learning that now, sorry for the mess

**Pull request closed without merging**
