### PR TITLE
Fixes for upcoming GCC6 & Clang 3.8

### PR DESCRIPTION
**Pull request by janisozaur**
New GCC is much more strict about type punning, while Clang complains about ambiguous expression.

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
Why the ride.h change?

**Comment by janisozaur** [comment]
This struct is being used in various places (like here: https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/windows/new_ride.c#L696) and it is being treated like int16. Making it a union lets the compiler know it can do so safely. The other solution is to fix all the other places that access it, but this way it is more concise and still valid.

**Comment by duncanspumpkin** [comment]
Should use a different name instead of ride_id as that is almost exclusively used as a uint8 so it could cause confusion. I was surprised that only the header file was changed surely we should use the variable if its used like that, no?

**Comment by janisozaur** [comment]
That's not required, since a union already forces compiler to guarantee proper access modes. I can change the other uses though for sake of clarity.

What name would you suggest for that field then?

**Comment by janisozaur** [comment]
```
[  4%] Building C object CMakeFiles/openrct2.dir/src/ride/ride.c.o
/OpenRCT2/src/ride/ride.c: In function 'ride_create_ride':
/OpenRCT2/src/ride/ride.c:886:2: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  edx = *((uint16*)&listItem);
  ^~~
/OpenRCT2/src/ride/ride.c: In function 'vehicle_create_car':
/OpenRCT2/src/ride/ride.c:4358:30: warning: overflow in implicit constant conversion [-Woverflow]
   vehicle->current_station = (mapElement->properties.track.sequence & 0x70) << 4;
                              ^
cc1: some warnings being treated as errors
CMakeFiles/openrct2.dir/build.make:1375: recipe for target 'CMakeFiles/openrct2.dir/src/ride/ride.c.o' failed
make[2]: *** [CMakeFiles/openrct2.dir/src/ride/ride.c.o] Error 1
[  4%] Building C object CMakeFiles/openrct2.dir/src/windows/new_ride.c.o
/OpenRCT2/src/windows/new_ride.c: In function 'window_new_ride_scrollmousedown':
/OpenRCT2/src/windows/new_ride.c:696:2: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  w->new_ride.selected_ride_id = *((sint16*)&item);
  ^
/OpenRCT2/src/windows/new_ride.c: In function 'window_new_ride_scrollmouseover':
/OpenRCT2/src/windows/new_ride.c:716:2: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  if (w->new_ride.highlighted_ride_id == *((sint16*)&item))
  ^~
/OpenRCT2/src/windows/new_ride.c:719:2: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  w->new_ride.highlighted_ride_id = *((sint16*)&item);
  ^
/OpenRCT2/src/windows/new_ride.c: In function 'window_new_ride_paint':
/OpenRCT2/src/windows/new_ride.c:768:3: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   ride_list_item item = *((ride_list_item*)&w->new_ride.highlighted_ride_id);
   ^~~~~~~~~~~~~~
/OpenRCT2/src/windows/new_ride.c: In function 'window_new_ride_select':
/OpenRCT2/src/windows/new_ride.c:937:2: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  ride_list_item item = *((ride_list_item*)&w->new_ride.selected_ride_id);
  ^~~~~~~~~~~~~~
cc1: some warnings being treated as errors
CMakeFiles/openrct2.dir/build.make:2433: recipe for target 'CMakeFiles/openrct2.dir/src/windows/new_ride.c.o' failed
make[2]: *** [CMakeFiles/openrct2.dir/src/windows/new_ride.c.o] Error 1
[  5%] Building C object CMakeFiles/openrct2.dir/src/world/map.c.o
/OpenRCT2/src/world/map.c: In function 'map_element_insert':
/OpenRCT2/src/world/map.c:3946:2: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  *((uint32*)&newMapElement->properties) = 0;
  ^
```

**Comment by duncanspumpkin** [comment]
Shouldn't we change the selected_ride_id to be `ride_list_item*` and then this wouldn't occur?

**Comment by janisozaur** [comment]
But `sizeof(ride_list_item*) == 4` while `sizeof(ride_list_item) == 2`, wouldn't that cause problems?

**Comment by duncanspumpkin** [comment]
sorry i mean `ride_list_item` not a pointer to it.

**Comment by janisozaur** [comment]
It doesn't help for there are many places where it is being treated as int16 anyways:
```
/home/janisozaur/workspace/OpenRCT2/src/windows/new_ride.c:513:36: error: incompatible types when assigning to type ‘ride_list_item {aka struct <anonymous>}’ from type ‘sint16 {aka short int}’
    w->new_ride.highlighted_ride_id = RCT2_GLOBAL(0x00F43523, sint16);
```

**Comment by janisozaur** [comment]
I amended the change, can you look again?

**Comment by duncanspumpkin** [comment]
Yeah i see. Thats better.

**Comment by IntelOrca** [comment]
@duncanspumpkin Shall we merge this now?

**Comment by duncanspumpkin** [comment]
Change it to `map_get_station` even though its always going to be 0.

**Comment by janisozaur** [comment]
Done

**Pull request merged**
