### PR TITLE
updated RIDE_ID_NULL value and changed return types

### PR DESCRIPTION
**Pull request by zahramakki**
Hello. We made some changes related to issue #13305 . Not sure if this handles everything in the issue-- is there anything we missed? Did we want to update functions that return uint8_t or just functions that ended with ..._ride_index()?

### CODE REVIEW

**Review by tupaschoal — COMMENTED** [review]
There are some things to deal with first:
- Make sure you reword the commit title to have at most 72 characters
- Most of the compilations are failing due to truncation. Probably requires either casting or reworking.

**Comment by myounus99** [comment]
Is there a way to mark this PR as a draft? We still want to keep working on it and don't want yall to read over it if we already know that it's not ready to be merged.

**Comment by tupaschoal** [comment]
Done

**Comment by zahramakki** [comment]
Running issues with commit message. Will create a new PR.

**Comment by tupaschoal** [comment]
Don't do that, we can make it work here, you just need to do `git rebase -i develop` and do `reword`

**Pull request closed without merging**
