### PR TITLE
Shrink PNG Files

### PR DESCRIPTION
**Pull request by mic-max**

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
I'm not sure this is worth doing at this point, since the original binaries are already in the repository anyway. `git would be storing both copies.`

As is, this *increases* the file size for several files, by the way. (distribution/windows/top.png, distribution/windows/welcome.png)

**Comment by IntelOrca** [comment]
Something to consider though if we ever move the files into another repository.

**Comment by duncanspumpkin** [comment]
What about moving these files to OpenGraphics repo?

**Comment by Gymnasiast** [comment]
I thought @janisozaur already ran `pngoptimize` or something like that on the PNGs.

**Comment by janisozaur** [comment]
Apparently not on these. I usually check PRs introducing new pngs for optimization, that must've slipped.
As already mentioned, at this point it will only bloat the repo by storing images twice for little to no benefit in resulting artifact size (I haven't checked, just my assumption).

**Comment by Gymnasiast** [comment]
Since this does not save a great deal of space (most of the saving are expressed in _bytes_) and will cause the repo size to increase, I'm afraid I'll have to close this PR.

Don't let this keep you from trying to help the project, we appreciate the effort nonetheless. :-)

**Pull request closed without merging**
