### PR TITLE
Installer version update

### PR DESCRIPTION
**Pull request by JarnoVgr**

### CODE REVIEW

**Comment by IntelOrca** [comment]
You might as well rebase this again so its just one commit.

**Comment by JarnoVgr** [comment]
I've been fighting this monster called Git for the past 30 minutes, without success. I'll give it a shot tomorrow.

**Comment by IntelOrca** [comment]
You do not need to close and re-open the pull request. The pull request will always take the current state of your source branch. When you update your branch, the PR will automatically update.

**Comment by duncanspumpkin** [comment]
Also you should really do this in a feature branch then it is easier to rebase/squash.

**Comment by JarnoVgr** [comment]
I'm aware of not needing to re-open a PR. Git just keeps frustrating me, so I just decided to update my build server to support dynamic installer versioning and get rid of this PR.

**Comment by wolfreak99** [comment]
By any chance are you trying to update your code without pushing your changes to this server? I'm starting to feel a similar pain when you say "Fighting this monster called git for the past 30 minutes". it's why i haven't pushed much stuff to it, i would work on something lengthy, and be stuck 240 commits behind.

**Comment by JarnoVgr** [comment]
I know the basics of Git and pushing changes to Github. But for whatever reason the more advanced stuff is just a pile of stackoverflow answers that doesn't work for my situation. And I don't want to spend so much time at a simple change like this one. :-1:

**Comment by janisozaur** [comment]
@JarnoVgr It looks like you bumped the wrong number and warped us straight to 0.4.0 ;)

**Comment by JarnoVgr** [comment]
I'm just a few years ahead of you guys. Everything has been decompiled already!

(I will fix it)

**Pull request closed without merging**
