### PR TITLE
Fix #3561: Tunnels drawn incorrectly

### LINKED ISSUE #3561: Tunnels drawn incorrectly
**OS:** win10
**Version:** 0.0.5 develop
**Commit:** 8efdf4e

Tunnels should be raised 1 unit if the track entering it is not flat (if possible), allowing the track to be drawn inside the tunnel. This currently does not happen.
How it should be (screenshot from 15th april):
scr87
What it looks like now:
scr106
Look at the tunnels on the right and top-left.

### PR DESCRIPTION
**Pull request by marijnvdwerf**

### CODE REVIEW

**Comment by Gymnasiast** [comment]
I found one little glitch:

canary mines 2016-10-19 21-14-38

(The terrain under the water is as high as the column next to it.)

**Comment by marijnvdwerf** [comment]
How does this render in the original?
Op wo 19 okt. 2016 om 21:17 schreef Michael Steenbeek <
notifications@github.com>

**Comment by Gymnasiast** [comment]
... exactly the same. I wasn't aware of this bug, to be honest.

**Comment by marijnvdwerf** [comment]
Can you add that image to the existing water drawing bug?

**Pull request merged**
