### PR TITLE
Fix #21690: Muting ride music doesn't mute title music

### LINKED ISSUE #21690: Disabling ride music doesn't disable title screen music
### Operating System

Windows 11

### OpenRCT2 build

OpenRCT2 V0.4.9 also latest devel v0.4.9-b6fdcf9

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

_No response_

### Describe the issue

When changing the ride music slider in the options menu on the title screen it does change the volume of the title screen music, but if you disable the ride music with the checkbox it doesn't disable it. Changing the slider whilst having the checkbox marked off it still changes the volume.

In parks it does work as intended with ride music.

### Steps to reproduce

See video
Uploading 2024-03-29 22-50-30.mp4…
https://www.youtube.com/watch?v=sdm8lPvaFpY

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by ayvaak**
Slightly modifies the Audio.cpp and Options.cpp files to make the "mute ride audio" checkbox affect the title music.

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
I'm not sure about this approach. The title screen music can be disabled from the same tab already. The ride music volume doesn't affect the title screen music, either, so this might cause more confusion than it solves.

@ayvaak Could you elaborate on the rationale?

**Comment by jkapi** [comment]
Because I'm the one who made the issue, my rationale is that if the Ride Music slider is able to lower the title screen music, the mute button next to it should also mute the title screen music.

**Comment by AaronVanGeffen** [comment]
we won't be merging this for the reasons outlined earlier.

**Comment by AaronVanGeffen** [comment]
Internally, the title music is using a channel separate from the ride music. A solution could be to expose volume settings for this channel as well. However, I'm not sure the added clutter would be worth it, to be honest.

As is, however, we won't be merging this PR for the reasons outlined earlier. Sorry.

**Pull request closed without merging**
