### PR TITLE
Start moving track place into GameAction framework

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Track place game action

### CODE REVIEW

**Comment by tomlankhorst** [comment]
https://github.com/duncanspumpkin/OpenRCT2/pull/18

**Comment by AaronVanGeffen** [comment]
Is this deliberately not removing the old code path yet?

**Comment by duncanspumpkin** [comment]
Yes i need to get the callbacks working then I can start dismantling the old code. Its a messy function this one.

**Comment by duncanspumpkin** [comment]
Currently there is an issue with networked games. When placing the first piece the game is closing the construction window and destroying the ride. Likely due to checking for track piece before the piece has been placed.

**Comment by pizza2004** [comment]
I see the commit about preventing ghost pieces from showing up in multiplayer and I was wondering if it would be possible now with game actions to instead synchronize the display of ghost pieces across the network?

**Comment by duncanspumpkin** [comment]
No that would not be possible. Ghosts are drawn and removed multiple times a game tick it would clog the network. All of the saving us designed around removing ghosts as well. On top of all that I don't think people would want that.

**Pull request merged**
