### PR TITLE
Disable chain button on steep slopes that cannot have one

### LINKED ISSUE #1873: Lift Chains on Steep Hills shouldn't work but does.
scr18
scr19

If this could be kept as a cheat, that would be awesome... :)

### PR DESCRIPTION
**Pull request by LRFLEW**

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Does this prevent 25-to-60 pieces from getting chain?

**Comment by IntelOrca** [comment]
If this isn't an original bug, I need to cross-check the original disassembly to see what I missed.

**Comment by LRFLEW** [comment]
@sjoerddebruin added a comment to the issue with a variant of this issue that this patch doesn't fix. With both of those issues and #1854 happening, it seems like something might have broken recently. I don't know how to check the assembly, but I will check the stable branch and look through the commit history to see if I see anything questionable.

**Comment by IntelOrca** [comment]
@LRFLEW The last stable was released before this code was written - so it will work. Its likely I made a mistake somewhere given the complexity of the function. But I have already fixed a few issues awhile ago if you look at the history.

**Comment by IntelOrca** [comment]
The cause of #1873 was something else which I have now fixed. However this PR is still fine in that it actually disables the button as well making it more UX friendly. It however doesn't work if you are constructing in reverse though... perhaps make it handle that too?

**Comment by LRFLEW** [comment]
Just realized this was still open. Is there any use for this? I can make the improvement if wanted, or I can just close this.

**Comment by janisozaur** [comment]
If this is supposed to be merged, can you please name the commit properly, so it says what it changes? You can still reference github issues in the extended description, but makes checking history much easier without having to cross-reference github. Remember about one line of vertical space between the oneline description and extended description. Thanks.

**Comment by Gymnasiast** [comment]
@LRFLEW : Yes, considering it improves UX. You will need to look into IntelOrca's comment though.
As for janisozaur's comment, a commit message along the lines of `Disable chain button on steep slopes that cannot have one` would be more descriptive.

**Comment by janisozaur** [comment]
And while at it, also update `changelog.txt` :)

**Comment by LRFLEW** [comment]
Ok, I've rename the commit and PR to better match what's actually being done. @IntelOrca I looked into the issue you described, but couldn't find anything. The original game allows for chain lift on steep **down**, which this allows as well. It's the steep **up** slopes that are stopped, which this PR appears to do going backwards as well. If there's something I'm missing, just let me know.

**Comment by Gymnasiast** [comment]
@LRFLEW : What you describe is the correct behaviour. A steep backwards lift is used for boomerang-type coasters.

**Pull request merged**
