### PR TITLE
Use libraries v37

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Review by Gymnasiast — APPROVED** [review]

**Comment by janisozaur** [comment]
I'd still like to get confirmation from @AaronVanGeffen that it works correctly

**Comment by AaronVanGeffen** [comment]
Thanks. Yes, I'd like to check this out myself. It's likely that I can do so tonight.

**Comment by Gymnasiast** [comment]
> I'd still like to get confirmation from @AaronVanGeffen that it works correctly

I figured that, yeah. I would have merged it immediately otherwise.

**Comment by janisozaur** [comment]
obraz
well the windows libraries were updated as well

**Comment by AaronVanGeffen** [comment]
It's working great!
 


> well the windows libraries were updated as well

Oops, how did I miss that... Sorry!

**Review by AaronVanGeffen — APPROVED** [review]
It's working great!
 
Screenshot 2024-09-07 at 18 02 11

> well the windows libraries were updated as well

Oops, how did I miss that... Sorry!

**Pull request merged**
