### PR TITLE
Fix: Financial Options Widget

### PR DESCRIPTION
**Pull request by adakitesystems**
This pull request is to fix issue #6945.

### CODE REVIEW

**Comment by adakitesystems** [comment]
Yes. I briefly tried to use the `MAIN_WIDGETS` macro to reduce some redudancy, but I still encountered issues with the research tab which is why I fully reverted the macro introduction. I understand there is still some redudancy with this commit. Possibly the `WWT_TAB` entries can be converted into a macro? But, `WWT_FRAME`, `WWT_CAPTION`, and `WWT_RESIZE` seem to have different values amongst certain tabs.

**Comment by Gymnasiast** [comment]
> But, WWT_FRAME, WWT_CAPTION, and WWT_RESIZE seem to have different values amongst certain tabs.

Well, they shouldn't have. All tabs result in a window of the same size, so logically these should be the same. If changing them to different values is needed, that signifies a problem somewhere else in the Finance window code.

**Comment by AaronVanGeffen** [comment]
Thanks for your pull request. It looks like you're aiming to fix a regression from #6932? In doing so, you are reverting most of the code deduplication that PR aimed to do, however. 

A better approach would be to split the tab widgets and main widgets into two defines. You could then reuse both these defines for the main (financial) tabs, and define them manually for the research tab.

>> But, WWT_FRAME, WWT_CAPTION, and WWT_RESIZE seem to have different values amongst certain tabs.
>
> Well, they shouldn't have. All tabs result in a window of the same size, so logically these should be the same. 

This is true for the financial tabs, but not for the research tab. The latter should not be sharing the WWT_FRAME, WWT_CAPTION, and WWT_RESIZE widgets.

**Comment by Broxzier** [comment]
I assumed the tabs all had the same size, that explains why there was so much space left to the sides of the group boxes. I'd rather see a different solution for this that does not add almost identical code again.

Looking back at the original sizes, I found that both the summary and the research tab differ from the rest:

```
Width 	Height
529     288 	// SUMMARY
529     256 	// FINANCIAL_GRAPH
529     256 	// VALUE_GRAPH
529     256 	// PROFIT_GRAPH
529     256 	// MARKETING
319     206 	// RESEARCH
```

It looks like the width and height are still set here: https://github.com/Broxzier/OpenRCT2/blob/61dfb3dac7259f86f01a1327541c6b8ba4bb6e19/src/openrct2-ui/windows/Finances.cpp#L1353-L1363
Removing those lines makes all tabs have the same size (which I personally prefer. I dislike it when changing tabs resizes the window).
It also means that the graph and the research tab don't use the full size of the window. I'm up for changing those if you just want to keep this PR to be a fix for the rendering issue.

**Comment by AaronVanGeffen** [comment]
> It looks like the width and height are still set here: https://github.com/Broxzier/OpenRCT2/blob/61dfb3dac7259f86f01a1327541c6b8ba4bb6e19/src/openrct2-ui/windows/Finances.cpp#L1353-L1363
> Removing those lines makes all tabs have the same size (which I personally prefer. I dislike it when changing tabs resizes the window).

You're right, that's just the window size, not touching any of the widgets.

> It also means that the graph and the research tab don't use the full size of the window. I'm up for changing those if you just want to keep this PR to be a fix for the rendering issue.

The game does this all over, though. I'd much prefer the windows to resize over having a bunch of empty space.

Personally, I'd like you to fix the regression by going back to the previous behaviour, rather than changing the behaviour now, to remain consistent. We can re-evaluate the lot later, when we inevitably switch to a different widget system.

> One thing to note is that the research tab is an exact copy of the Research Funding window.

Ah, it's actually the other way around ­— it was made back into a window of its own, as some people preferred it from RCT1.

**Comment by Gymnasiast** [comment]
Hm, I hadn't realised that the Finance window uses different sizes per tab. If I had, I would have tested Broxzier's PR better.

I'm somewhat inclined to merge this, then, since it more or less reverses it to how it used to be.

**Comment by AaronVanGeffen** [comment]
> I'm somewhat inclined to merge this, then, since it more or less reverses it to how it used to be.

Hmm, it really doesn't have to revert the changes to the tab widgets, though. Just the main widgets, as outlined in an earlier comment.

**Comment by Broxzier** [comment]
@AaronVanGeffen You're right, but in most cases it only does for the height.
If we keep the windows as it is, with 3 different sizes, then I'd suggest using a const array with the window sizes for the different pages, and simply set `w->width` and `w->height` to those.

@Gymnasiast As did I :P

**Comment by adakitesystems** [comment]
The attached screenshots show that OpenRCT2 uses a vanilla RCT1-style for the top right toolbar but vanilla RCT2-styled tabs for the finances window. In vanilla RCT1, there is no "Research Funding" tab accessible via the finances window. In vanilla RCT2, the red liquid flask icon (aka Research Funding) is present in the finances window. In OpenRCT2, supporting both seems redundant but could be justified for nostalgia/convenience carried over from vanilla versions.

> Looking back at the original sizes, I found that both the summary and the research tab differ from the rest:

I agree. In both vanilla RCT1 and RCT2, the "summary", all graphs, and the "marketing" tabs in the finance window have the same size. In OpenRCT2, the graph tab sizes are different compared to the other tabs.

> Removing those lines makes all tabs have the same size (which I personally prefer. I dislike it when changing tabs resizes the window).

As @Broxzier points out, vanilla RCT1 windows seemed to never contain tabs that would resize their parent windows. However, in vanilla RCT2, tabs that resize windows is possible as seen with the finances window and "Research Funding" tab in the attached vanilla RCT2 screenshot.

> The game does this all over, though. I'd much prefer the windows to resize over having a bunch of empty space.

I agree.

> Personally, I'd like you to fix the regression by going back to the previous behaviour, rather than changing the behaviour now, to remain consistent. We can re-evaluate the lot later, when we inevitably switch to a different widget system.

I agree. Is this PR acceptable in its current state or does it still require changes?

**Attached screenshots**:
Vanilla RCT1:
rct1
Vanilla RCT2:
rct2
OpenRCT2:
openrct2

**Comment by AaronVanGeffen** [comment]
> In vanilla RCT2, the red liquid flask icon (aka Research Funding) is present in the finances window. In OpenRCT2, supporting both seems redundant but could be justified for nostalgia/convenience carried over from vanilla versions.

I agree, and personally, I would remove research from the finances window altogether. However, some people vetoed that at the time, so for now, it stays.

> Is this PR acceptable in its current state or does it still require changes?

While we don't doubt the behaviour you've reverted is the right one, in its current state, the PR reverts too much of the code refactored earlier this week. The regression is regrettable, but should be addressed directly instead of reverting this much code.

Please move the tab widgets back into a define, and re-use it for each of the window tabs widget definitions. With that out of the way, it should be good enough, for now.

**Comment by Broxzier** [comment]
After my last comment I started trying it out myself, and I do like the static array of window sizes over adding the duplicated code back: https://github.com/Broxzier/OpenRCT2/commit/fdaa8eb56c94768e9992c4a8f5f679582906c8f3
This doesn't include the window titles, it was mostly to test if the macro could be used like that, and to see if it actually works.

@adakitesystems do you want to work on the feedback or shall I make a PR? I don't want to ovethrow your fix with mine.

**Comment by adakitesystems** [comment]
@Broxzier It doesn't matter to me whose PR is merged. One of the reasons I wanted to revert the refactoring back to a working version was to give the original author (you) a chance to continue the refactoring. 

I have just started working on the feedback and maybe need some more time. I have attached my code as a sample (screenshot) because I am not finished. I think we have different ideas how to refactor this section of code. Personally, I dislike the static `WindowSizes` array because you have to be very careful to "align" the code such that you are referencing the correct size. It also appears you also altered the sizes in the `WindowSizes` array. However, I like your final result e.g. `MAIN_WIDGETS(WINDOW_FINANCES_PAGE_SUMMARY)` and addressing the additional "sizing code" (i.e. lines 1353-1363 in your new commit). BTW, does your code compile and run? I don't see the definitions for `WINDOW_FINANCES_PAGE_SUMMARY` and similar variables. I was not able to compile your code.

I am trying to do small incremental changes as I go along. Let me know if you dislike my current refactoring sample and I will withdraw my PR and we can run with yours.
refactor1
refactor2

**Comment by AaronVanGeffen** [comment]
> BTW, does your code compile and run? I don't see the definitions for `WINDOW_FINANCES_PAGE_SUMMARY` and similar variables. I was not able to compile your code.

They're defined in an enum at the top of the file:

```c++
enum
{
    WINDOW_FINANCES_PAGE_SUMMARY,
    WINDOW_FINANCES_PAGE_FINANCIAL_GRAPH,
    WINDOW_FINANCES_PAGE_VALUE_GRAPH,
    WINDOW_FINANCES_PAGE_PROFIT_GRAPH,
    WINDOW_FINANCES_PAGE_MARKETING,
    WINDOW_FINANCES_PAGE_RESEARCH,
    WINDOW_FINANCES_PAGE_COUNT
};
```

**Comment by adakitesystems** [comment]
Ah ok. I see them now. I still can't compile due to a `narrowing conversion` error.
nc_error

**Comment by Broxzier** [comment]
> Personally, I dislike the static WindowSizes array because you have to be very careful to "align" the code such that you are referencing the correct size.

Do you mean the length of the lines? If so I think for widget those are okay (they are kind of an exception , breaking them makes them unreadable). It could be made smaller by passing the X and Y from the array directly, instead of the page index.

> BTW, does your code compile and run?

Yes, it compiles and runs fine for me. Visual Studio didn't throw me an error message. I think your compiler threads `WindowSizes[PAGE].Width - 1` as a 32 bit integer instead of `sint16`. A cast should work, but makes the lines even longer.

```
#define MAIN_WIDGETS(PAGE) \
    { WWT_FRAME,    0,  0,                                      (sint16)(WindowSizes[PAGE].Width - 1), 0,  (sint16)(WindowSizes[PAGE].Height - 1), 0xFFFFFFFF,                 STR_NONE                                }, \
    { WWT_CAPTION,  0,  1,                                      (sint16)(WindowSizes[PAGE].Width - 2), 1,  14,                                     STR_FINANCIAL_SUMMARY,      STR_WINDOW_TITLE_TIP                    }, \
    { WWT_CLOSEBOX, 0,  (sint16)(WindowSizes[PAGE].Width - 13), (sint16)(WindowSizes[PAGE].Width - 3), 2,  13,                                     STR_CLOSE_X,                STR_CLOSE_WINDOW_TIP                    }, \
    { WWT_RESIZE,   1,  0,                                      (sint16)(WindowSizes[PAGE].Width - 1), 43, (sint16)(WindowSizes[PAGE].Height - 1), 0xFFFFFFFF,                 STR_NONE                                }, \
    { WWT_TAB,      1,  3,                                      33,                                    17, 43,                                     IMAGE_TYPE_REMAP | SPR_TAB, STR_FINANCES_SHOW_SUMMARY_TAB_TIP       }, \
    { WWT_TAB,      1,  34,                                     64,                                    17, 43,                                     IMAGE_TYPE_REMAP | SPR_TAB, STR_FINANCES_SHOW_CASH_TAB_TIP          }, \
    { WWT_TAB,      1,  65,                                     95,                                    17, 43,                                     IMAGE_TYPE_REMAP | SPR_TAB, STR_FINANCES_SHOW_PARK_VALUE_TAB_TIP    }, \
    { WWT_TAB,      1,  96,                                     126,                                   17, 43,                                     IMAGE_TYPE_REMAP | SPR_TAB, STR_FINANCES_SHOW_WEEKLY_PROFIT_TAB_TIP }, \
    { WWT_TAB,      1,  127,                                    157,                                   17, 43,                                     IMAGE_TYPE_REMAP | SPR_TAB, STR_FINANCES_SHOW_MARKETING_TAB_TIP     }, \
    { WWT_TAB,      1,  158,                                    188,                                   17, 43,                                     IMAGE_TYPE_REMAP | SPR_TAB, STR_FINANCES_RESEARCH_TIP               }
```

Again, can be shortened when passing widht and height directly:

```
#define MAIN_WIDGETS(W, H) \
    { WWT_FRAME,    0,  0,                (sint16)(W - 1), 0,  (sint16)(H - 1), 0xFFFFFFFF,                 STR_NONE                                }, \
    { WWT_CAPTION,  0,  1,                (sint16)(W - 2), 1,  14,              STR_FINANCIAL_SUMMARY,      STR_WINDOW_TITLE_TIP                    }, \
    { WWT_CLOSEBOX, 0,  (sint16)(W - 13), (sint16)(W - 3), 2,  13,              STR_CLOSE_X,                STR_CLOSE_WINDOW_TIP                    }, \
    { WWT_RESIZE,   1,  0,                (sint16)(W - 1), 43, (sint16)(H - 1), 0xFFFFFFFF,                 STR_NONE                                }, \
    { WWT_TAB,      1,  3,                33,              17, 43,              IMAGE_TYPE_REMAP | SPR_TAB, STR_FINANCES_SHOW_SUMMARY_TAB_TIP       }, \
    { WWT_TAB,      1,  34,               64,              17, 43,              IMAGE_TYPE_REMAP | SPR_TAB, STR_FINANCES_SHOW_CASH_TAB_TIP          }, \
    { WWT_TAB,      1,  65,               95,              17, 43,              IMAGE_TYPE_REMAP | SPR_TAB, STR_FINANCES_SHOW_PARK_VALUE_TAB_TIP    }, \
    { WWT_TAB,      1,  96,               126,             17, 43,              IMAGE_TYPE_REMAP | SPR_TAB, STR_FINANCES_SHOW_WEEKLY_PROFIT_TAB_TIP }, \
    { WWT_TAB,      1,  127,              157,             17, 43,              IMAGE_TYPE_REMAP | SPR_TAB, STR_FINANCES_SHOW_MARKETING_TAB_TIP     }, \
    { WWT_TAB,      1,  158,              188,             17, 43,              IMAGE_TYPE_REMAP | SPR_TAB, STR_FINANCES_RESEARCH_TIP               }
```

I do like your approach. It makes setting titles easy without the need to change those later on (like the width and height). This can be part of the MAIN_WIDGETS macro, so it takes `MAIN_WIDGETS(W, H, STR_TITLE)`.

I prefer having the window width and heights in an array over having them inside the `rct_widget` definitions. Many other windows use a `WW` and `WH` define that is used in the rest of the source file.

**Comment by adakitesystems** [comment]
I was able to compile and run @Broxzier's code. Now, there seems to be a weird white line under the finance window when the "Financial Summary" tab is selected but not when any other tab is selected. See screenshots.
whiteline1
whiteline2

**Comment by Broxzier** [comment]
That faint white line is also pressent in 94946ce. I think it's the background of the window, but I'm not sure.

**Comment by adakitesystems** [comment]
> Do you mean the length of the lines?

No. I mean requiring a developer to know the exact order and length of the `WindowSizes` array with respect to the enum. They have to be "lined up" in their definitions. For example, the developer is required to know that `WINDOW_FINANCES_PAGE_VALUE_GRAPH` is index=2 when defining its size in `WindowsSizes[2]` ([example line 85](https://github.com/Broxzier/OpenRCT2/blob/fdaa8eb56c94768e9992c4a8f5f679582906c8f3/src/openrct2-ui/windows/Finances.cpp#L85)). You also have a `WINDOW_FINANCES_PAGE_COUNT` at the end of the enum. What is this used for? What if you add more pages? Will that page count have to be repositioned or doesn't it have to be known that `WindowSizes[6]` holds the length of the array during the definition of the new page size?

> That faint white line is also pressent in 94946ce. I think it's the background of the window, but I'm not sure.

You're right. The faint white line is also present in 6336e8c. I'm not sure in which commit that showed up.

**Comment by adakitesystems** [comment]
~~What if you add more pages? Will that page count have to be repositioned or doesn't it have to be known that `WindowSizes[6]` holds the length of the array during the definition of the new page size?~~

Never mind. I see the intent of the page count now and how it can be modified.However, I still dislike it. :P In any case. Your PR seems to be headed in the right direction. I will close this PR and let you do your thing. Agreed?

**Comment by adakitesystems** [comment]
I have committed ccf03a0 as an alternative solution or to inspire ideas for handling the tabs' window titles in @Broxzier's solution. I dislike the heavy use of macros in my solution, but I dislike the static array usage in @Broxzier's solution albeit clever.

Please advise on whether we should use/modify my macro solution (inspired by the previous `MAIN_WIDGETS`) or if I should close this PR so that @Broxzier can submit a new PR.

**Comment by AaronVanGeffen** [comment]
Yeah, while I appreciate what you were trying to do, I think you might have over-engineered it a little. You see, the macros all merely a preprocessing step — in the end, they'll just be generating widget code to be compiled.

I do agree it fits better in the code base to just create new WWT_FRAME, WWT_CAPTION, and WWT_RESIZE widgets for each of the tabs, rather than making it more complicated with the proposed `WindowSizes` struct.

Whatever we end up merging, I hope it was a nice introduction to the code base for you — I noticed this was your first PR. Keep 'em coming!

**Comment by adakitesystems** [comment]
Thank you and the other contributors who spent time on this PR and most of all thanks for all contributions to this project. I was excited to learn of this project's existence, have had lots of fun so far playing the game, and will try to help in a timely fashion whenever possible.

**Pull request closed without merging**
