### PR TITLE
Define Git variables for CMake

### LINKED ISSUE #4140: No commit/build number in Mac version
**OS:** [Mac OS X 10.11.5]
**Version:** [0.0.5]
**Commit/Build:** [389ae72] (Pulling this from the Launcher, may be incorrect. However, this has been consistent with every update.

Mac version does not show build/commit number at bottom left corner. Makes reporting bugs with correct build number much more difficult.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Launch Mac Version
2. Observe bottom left corner.

**Screenshots / Video:**
screen shot 2016-07-19 at 5 17 48 pm

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
This defines git branch, commit hash, and short commit hash for builds using CMake.

Partially fixes #4140 — the XCode project will still needs similar adjustments.

### CODE REVIEW

**Comment by janisozaur** [comment]
Can you make version information gets stored as variables, as discussed in #4140?

**Comment by AaronVanGeffen** [comment]
Hmm, I can see the benefit in that, but I'm not sure I understand how you'd like it done.

If we have to stay compatible with the PS build scripts, we will have to keep using the defines in `version.h` before setting them to variables, right? Wouldn't that effectively nullify the potential benefit of using variables to begin with, that is, not having to recompile every object file?

The only way I see to avoid that, is to populate version.h externally, e.g. through `sed`, but that would break compatibility with the PS scripts for sure.

Thoughts?

**Comment by IntelOrca** [comment]
@janisozaur why? Wouldn't you just do:
```
const char gCommitSha1[] = OPENRCT2_COMMIT_SHA1;
```

**Comment by AaronVanGeffen** [comment]
Okay, I think I've tackled this with 6cbc545. Constants are now declared in `version.h`, with the definitions moved to `version.c`. This means recompilation isn't needed after doing a new commit.

Caveat: the resulting object file for version.c also isn't rebuilt automatically when HEAD changes, which means the information is outdated unless cleaning the object file manually first. Not a problem for build servers, but still less than ideal.

Another caveat: I haven't changed the way `crash.cpp` uses the compile-time version definitions, as doing so introduced more of a hassle with widechars. I'm relying on AppVeyor to check Visual Studio builds; I'd rather not change these blindly.

Thoughts?

**Comment by IntelOrca** [comment]
For MSVC, looks like you have to do some pre / post build tasks:
http://stackoverflow.com/questions/13497382/force-ms-vs2010-to-rebuild-one-cpp-file-on-every-build

But that would do it every time you compile even if you hadn't change commit... not ideal. Then again its really only for CIs anyway.

**Comment by AaronVanGeffen** [comment]
For Linux, I suppose we could let CMake touch version.c before compiling?

At the moment, AppVeyor seems to fail. I updated the VS project manually; I guess another change is needed?

The XCode project needs a change as well for Travis to pass its final test. @LRFLEW is already working on that, though.

**Comment by LRFLEW** [comment]
I added the file to the project, so the build should succeed. However, I don't know if I need to add something to the scripts in the project to get the macros to be defined. I can take a look at it later.

**Comment by AaronVanGeffen** [comment]
Builds are passing for all platforms now, for what it's worth.

**Comment by janisozaur** [comment]
@AaronVanGeffen seems to work OK on Linux :+1:

**Comment by IntelOrca** [comment]
All the CI builds need checking to see if they contain the correct information at bottom left title screen.

**Comment by AaronVanGeffen** [comment]
Is there a way to obtain these builds? I gather they are only published for develop.

**Comment by LRFLEW** [comment]
AaronVanGeffen/OpenRCT2#4 is my suggestion for getting the version number in the macOS builds. I couldn't really figure out a cleaner solution, but it works just fine as-is.

**Comment by AaronVanGeffen** [comment]
With that, I think this PR is ready for merging?

**Pull request merged**
