### PR TITLE
Replace Giga LIM Sprites With Improved Ones

### PR DESCRIPTION
**Pull request by xp4xbox**
Here are my improved giga LIM sprites. I originally made hydraulic ones based of Kingda Ka's launch, but as most of the community preferred LIM sprites, I decided to change them based off the preference of the New Element community.

My modifications, were improved track design more fitting for the the LIM fins and taller and more rectangle fins as in real life.

So here is what the triple-rail LIM sprites look in-game: (note the incorrect offset)

hack park 2017-04-27 17-57-00

For interest, here were the hydraulic ones:

81 test

82 test

hack park 2017-04-24 18-20-55

I also made more realistic LIM sprites on flat track, as based off Cheetah Hunts Launch:

cheetah_hunt_media_16

I would prefer theses to be incorporated, as its the most realistic type, but instead theses could be incorporated as the mini coaster booster track.

hack park 2017-04-27 16-47-28
(again note there is an incorrect offset)

**NOTE:** PNGs for all track image files are optimized.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
I have fixed the offsets. However, I think the LIM sprites look a bit oversized compared to the track and the train. It especially looks strange when the train passes over the sprites.

**Comment by marijnvdwerf** [comment]
Wouldn't the flat boosters also need new support offsets?

**Comment by xp4xbox** [comment]
@Gymnasiast Can you show me?

**Comment by xp4xbox** [comment]
So here are the updated ones:

hack park 2017-05-01 16-34-44

I made them smaller, so the offset can be reset to its original.

**Comment by Gymnasiast** [comment]
If you add the flat ones as well, I can add those to the Mini RC/Spiral RC.

**Comment by xp4xbox** [comment]
Ok, would I just upload them as 91.png and 92.png?

**Comment by Gymnasiast** [comment]
Yes, indeed.

**Pull request merged**
