### PR TITLE
Close #16933: Rename car_visual to PaintStyle

### LINKED ISSUE #16933: Rename `rct_vehicle_entry.car_visual` to `rct_vehicle_entry.PaintStyle`
rct_ride_entry_vehicle.car_visual is an enumeration of the paint code used to paint the vehicle. "Car visual" does not speak to this reality. I think "PaintMode" or "DrawMode" is a better representation of this value.

### PR DESCRIPTION
**Pull request by navitux**
variable "car_visual" was renamed as "PaintStyle"

### CODE REVIEW

**Comment by spacek531** [comment]
Do you plan to change the name in json in this PR or a future one?

**Comment by navitux** [comment]
> Do you plan to change the name in json in this PR or a future one?

Where ?

**Comment by spacek531** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/5ecb7a6c6ab71d21f9251a5b4665414944d87bf4/src/openrct2/object/RideObject.cpp#L757

If you plan to change it, it would probably be a good idea to have both carVisual and paintStyle valid in the json to allow everyone to update their rides.

**Comment by navitux** [comment]
I think that I could do that but, by now, I think that this project is not for me since: I don't ave the game installed and I'm using Fedora it doesn't work on my machine XD, if it's ok I just want to make this change alone, I'm more a Python/C lang/web front-end person

**Review by tupaschoal — APPROVED** [review]

**Pull request merged**
