### PR TITLE
Update objects version to v1.0.2

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by Gymnasiast** [comment]
> Needs update for Android as well

How?

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2-android/app/build.gradle#L94

**Comment by Gymnasiast** [comment]
Ok, updated Android.
I have no clue as to why the CIs fail. @IntelOrca ?

**Comment by AaronVanGeffen** [comment]
> Edit: it looks as if the ZIP has botched rights.

This does appear to be the case, yes.

**Pull request merged**
