### PR TITLE
Added a delay to the tooltip

### LINKED ISSUE #3809: Tooltip delay
Currently the tooltips are appearing instantly, a (slight) delay should be a great improvement.

### PR DESCRIPTION
**Pull request by Bubba**
Fixes #3809 🤔 I'm not quite sure what the actual value of the original delay is though

### CODE REVIEW

**Comment by IntelOrca** [comment]
1000 was the original value, not sure how / why it got changed. Maybe it was just for testing it but never got reverted.

**Comment by wolfreak99** [comment]
This feels like it could be on topic as well as off topic, but now that you mention this, i actually remember a while back skimming the code and stumbled across this line, https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/windows/error.c#L142
this event might be an update event that should be fired off every second. and that var_480 might be a timer that is stored to see how long it's been open..

maybe the original switch to 1 was meant to be in this per-second-update and not the per-frame-update that it was in? (that is if that trigger_death update was meant to reflect the assembly code value "1" or something (if it was this way, that is, no clue what the assembly line looked like so pure speculation here))

**Comment by Bubba** [comment]
So `input_update_tooltip` was only supposed to be called once per second? That would make sense. Originally gTooltipNotShownTicks wasn't incremented at all. Also not sure what was up with `gTooltipNotShownTicks <= 1000` being switched around to `>= 1`

**Comment by Nubbie** [comment]
I'm getting a lot of 'Access Denied' warning boxes pop up without a reason, this didn't happen before, this might fix that issue by having a delay to it, I presume 1000 (1 sec) would be the best?

**Comment by IntelOrca** [comment]
Committed as c05eef02d66e6359b282a83010b8b40861b5f672.

**Pull request closed without merging**
