### PR TITLE
Add discord-rpc support to Linux

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by janisozaur** [comment]
Depends on https://github.com/discordapp/discord-rpc/pull/31

**Comment by janisozaur** [comment]
Other than two PRs mentioned above, there are two other things remaining (mostly my brain dump so that I don't forget):

* [ ] I will need to update dockerfile for mingw toolchain, the issue right now is the custom user I created there does not have permissions to create a directory for a temporary download. I'd rather fix this in docker than have to pre-create the directory manually. The problem is AUR helper refuses to work as default root user. I will see if I can use some better AUR helper (`yaourt` is a bit lacking`) which allows running as root or if I can map the new user to have appropriate permissions.

* [ ] the `-m32` architecture flag is set too late for building `discord-rpc`. I will have to move setting it from the leaf `CMakeLists.txt` to top-most one or see if splitting the discord support (the change in this patch) to after `include (src/openrct2/CMakeLists.txt)` will help.

**Comment by IntelOrca** [comment]
Rather than using `add_subdirectory`, can you not just run `cmake && make` separately beforehand in the `discord-rpc` directory?

**Comment by janisozaur** [comment]
It would achieve the same effect at higher maintenance cost, at least in my opinion – I would have to pass additional flags to another cmake project from shell, still modify ours to use the new library. With current approach it should be using pretty much all the configuration we already have.

**Comment by Krutonium** [comment]
>The problem is AUR helper refuses to work as default root user. I will see if I can use some better AUR helper (yaourt is a bit lacking`)

That's by design, considering yaourt `source`s the build script... You can see where that might be dangerous. I would suggest instead pacaur (not sure if it will run as root), or if you are looking for somthing with a UI, perhaps pamac? 

https://wiki.archlinux.org/index.php/AUR_helpers#Comparison_table

**Comment by janisozaur** [comment]
Depends on https://github.com/discordapp/discord-rpc/pull/37

**Comment by janisozaur** [comment]
OK, upstream is fixed, I cleaned up history here and moved cloning of discord-rpc into the `install.sh` script, together with a brief comment.

Unless there are any concerns raised, I would like to merge this later today.

**Comment by IntelOrca** [comment]
Does the readme need updating with information about building `discord-rpc`?

**Comment by janisozaur** [comment]
I will update the wiki page when this is in

**Pull request merged**
