### PR TITLE
Update title sequence for 0.0.3

### PR DESCRIPTION
**Pull request by Gymnasiast**
I kept the best of the 0.0.2 and added some new parks. Also fixed the rogue tile in PFCKrutonium's Electric Fields.

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
Can you rebase please. I had to muckup the history sorting out develop

**Comment by duncanspumpkin** [comment]
that language load fail commit just never seems to die. Your going to have to remove that commit.

**Comment by Gymnasiast** [comment]
What would be the best way to do that?

**Comment by duncanspumpkin** [comment]
rebase -i and just remove that commit from the rebase.

**Pull request merged**
