### PR TITLE
Implement ride create vehicles

### PR DESCRIPTION
**Pull request by duncanspumpkin**
This was mainly done by Ted all i've done is fix the bugs and get it rebased onto the latest develop. Requires testing.

### CODE REVIEW

**Comment by LRFLEW** [comment]
It looks like `src/ride/track.c` and `src/world/map.c` had the newline at the end of the file removed. Could you re-add those?

**Comment by IntelOrca** [comment]
image

1. Open Six Flags MM
2. Stop Revolution (twice) and then click test.
3. Wait for first train to ascend lift hill.

**Comment by IntelOrca** [comment]
image

Tidal wave, vehicles are too left of the track.

**Comment by IntelOrca** [comment]
image

River rapids.

**Comment by IntelOrca** [comment]
image

Sometimes when I start the elevator ride, it does not start at the bottom.

**Comment by duncanspumpkin** [comment]
@IntelOrca I think you might have used an older version those bugs aren't happening for me.

**Comment by duncanspumpkin** [comment]
Okay that should fix your issues @IntelOrca and readded the missing new lines

**Comment by IntelOrca** [comment]
I tested quite a lot of different rides and found nothing out of the ordinary, so I will merge.

**Pull request merged**
