### PR TITLE
Update readme.md to make it consistent with itself

### PR DESCRIPTION
**Pull request by ITAYC0HEN**
Edited the `readme.md` with a horizontal rules whenever is needed in order to make it consistent with other parts of the readme file which was already there.

In general, splitting between headers with a horizontal rule (`---`).

### CODE REVIEW

**Comment by Omaranwa** [comment]
looks good for my i hope it get merged

**Comment by Gymnasiast** [comment]
This would make it more consistent, indeed. However, I think readme.md contains far too many horizontal rules, and they're not really adding anything IMO.

**Comment by ITAYC0HEN** [comment]
Well, horizontal rules are making it easy to read and separate sections from one another. I'd agree tho, that we might have too many rules and maybe should consider to reduce it.
Anyway, no matter what we'll choose, it should be consistent for the readability. Because our brain is seeking for what it recognizes as a separator of paragraphs and sections.
I think that as for now, this is a good start.

**Comment by Gymnasiast** [comment]
Yeah, it is more consistent, as I said.
I have merged it, might revisit it at a later date.

**Pull request merged**
