### PR TITLE
Fix: Crash when plug-in attempt to set invalid property

### PR DESCRIPTION
**Pull request by Broxzier**
This fixes the crashes caused by the scenery manager plug-in. The steps to reproduce the crash are quite simple:
1. Open any park
2. Build a ride
3. Copy part of the ride with the scenery manager plug-in
4. Delete the ride
5. Set paste mode to 'raw'
6. Attempt to paste the copied ride

Instead of crashing, it now simply acts like a no-op.

The additional commits are to sanitize the input and give feedback to the user with a console message. These are no hard exceptions, so plug-ins will still behave the same (except for no longer crashing).

In a later PR, we could make these properties more strict (and stay backwards-compatible by only throwing if `OPENRCT2_PLUGIN_API_VERSION` >= API-version-when-changed).

### CODE REVIEW

**Comment by IntelOrca** [comment]
Do not use `std::puts`, you will need to use our own console functions which handle the REPL interface better.
Do not use our own console functions either, go via the scripting engine (`LogPluginInfo`, or interactive console, see the implementation for console.log).
I think throw an error instead of logging to console if API version is now later than current target.

**Comment by Broxzier** [comment]
Alright, thought there was be a better alternative, I just picked `std::puts` because that was already being used for other warnings in the same file:

https://github.com/OpenRCT2/OpenRCT2/blob/f47c1b9f96472c26233453a566aec40d22998b06/src/openrct2/scripting/bindings/world/ScTileElement.cpp#L83

As for throwing instead of logging, I'd prefer to get this fix in first, and then introduce stricter properties afterwards.

**Comment by Broxzier** [comment]
From cli:

image

From plug-in:

image

**Review by IntelOrca — APPROVED** [review]

**Comment by ZehMatt** [comment]
> Why was this implemented only for some of the properties? For example, tertiaryColour only exists for scenery and walls, but does not have any warnings.

Does that crash the game?

**Comment by Sadret** [comment]
No, the crash is because of how a particular property was implemented. I.e. a switch with proper default handling vs a straight up cast to the expected element type.
But from the view of plugins, there is no reason why one of the properties should yield a warning and another one not.

**Comment by ZehMatt** [comment]
Then there is your answer to why this PR did not handle this. Also from JS perspective if an object is missing a field then its simply undefined, the warning makes only sense for polymorphic types.

**Comment by Sadret** [comment]
I don't see the difference (from JS perspective).
`hasOwnership` only exists on SurfaceElement and gives a warning.
`footpathObject` only exists on EntranceElement and does not give a warning.

**Comment by ZehMatt** [comment]
Having those warnings was probably a mistake, in JS accessing fields that do not exist will simply result in undefined, to cover all the fields based on tile element type would add a bunch of extra code just to cover every possible combination.

**Comment by Sadret** [comment]
Okay. (Btw I strongly agree that the warnings are a mistake and more annoying than helpful, but that has already been discussed on Discord multiple times.)

**Pull request merged**
