### PR TITLE
Rewrite Platform::GetInstallPath

### PR DESCRIPTION
**Pull request by IntelOrca**
Would someone be able to help fix the macOS code? I do not really know what I am doing and am not able to compile or test it.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
@ibara Could you check if this doesn't break compilation/running on OpenBSD?

**Comment by ibara** [comment]
```
libopenrct2.a(PlatformEnvironment.cpp.o): In function `OpenRCT2::CreatePlatformEnvironment()':
../src/openrct2/PlatformEnvironment.cpp:(.text+0xd9): undefined reference to `Platform::GetInstallPath()'
../src/openrct2/PlatformEnvironment.cpp:(.text+0x15b): undefined reference to `Platform::GetFolderPath(SPECIAL_FOLDER)'
../src/openrct2/PlatformEnvironment.cpp:(.text+0x203): undefined reference to `Platform::GetFolderPath(SPECIAL_FOLDER)'
../src/openrct2/PlatformEnvironment.cpp:(.text+0x29b): undefined reference to `Platform::GetFolderPath(SPECIAL_FOLDER)'
../src/openrct2/PlatformEnvironment.cpp:(.text+0x330): undefined reference to `Platform::GetDocsPath()'
c++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

**Comment by ibara** [comment]
Attached is the diff to fix the build and runtime on OpenBSD (and coincidentally on FreeBSD as well).
[fix.txt](https://github.com/OpenRCT2/OpenRCT2/files/1673952/fix.txt)

**Comment by Gymnasiast** [comment]
@ibara Great, I'll apply it.

**Pull request merged**
