### PR TITLE
Feature #7682: Lock camera to vehicle in main window

### PR DESCRIPTION
**Pull request by seifer7**
Pressing the "Locate" button in the Ride window when selected on a "Vehicle/Train" will now have the main viewport track the vehicle.

**Still to complete:**
- [x] Drop-down selection for Locate or Follow
- [x] While following, automatically toggle underground view on/off as required
- [x] Implement tracking for Staff & Guests
- [x] More testing

### CODE REVIEW

**Review by Gymnasiast — DISMISSED** [review]
> Pressing the "Locate" button in the Ride window when selected on a "Vehicle/Train" will now have the main viewport track the vehicle.

~~This is not a good idea. People are used to this button just scrolling and not following. Checking if CTRL is pressed would be a better idea.~~

**Comment by seifer7** [comment]
> > Pressing the "Locate" button in the Ride window when selected on a "Vehicle/Train" will now have the main viewport track the vehicle.
> 
> This is not a good idea. People are used to this button just scrolling and not following. Checking if CTRL is pressed would be a better idea.

Maybe you missed the "Still to complete:...  _Drop-down selection for Locate or Track (currently replaces locate)_"

**Comment by ocalhoun6** [comment]
Once this is done, it would be really great to see the same done for peep/staff windows.

**Comment by ZehMatt** [comment]
I sort of feel like this can be probably achieved with a plugin, if not it would be good to implement the required API to do it.

**Comment by ZehMatt** [comment]
> > I sort of feel like this can be probably achieved with a plugin, if not it would be good to implement the required API to do it.
> 
> I'll have a look at the APIs and see if it's possible. I did have an alternate implementation idea that I may be well suited for a plugin.
> 
> Where do you draw the line between something that should be implemented in the main game, and what should be a plugin?
> I thought things that are obscure would be for plugins, this feature however seems like it should have been included in the game to start with (imo.)

That depends highly on the feature and the benefits and how much code it would add that needs to be maintained, thats my personal opinion on that matter I also think there is no definite answer to your question.

**Comment by Broxzier** [comment]
The moment the user attempts to move the camera, the sprite following should stop immediately. Rotating the view should not. This same feature could also be used to follow guests, though with them entering rides it can become a bit more complicated.

**Comment by seifer7** [comment]
Video preview of the feature working so far:

[OpenRCT2 Development: Follow ride in main window](https://www.youtube.com/watch?v=KuXKicHo6d4)

**Comment by IntelOrca** [comment]
> I sort of feel like this can be probably achieved with a plugin, if not it would be good to implement the required API to do it.

I think this is okay, particularly when we have no API yet for modifying existing windows. This seems similar in functionality to the isolate sound from window viewport mechanism.

**Comment by seifer7** [comment]
Implemented the staff & guest following too now!

Unless someone has some suggestions, I think this is about ready for a review!

**Comment by AaronVanGeffen** [comment]
What happens when the sprite id becomes invalid? For instance, when a vehicle crashes. I remember we had to handle that particular case for OpenLoco as well.

**Comment by seifer7** [comment]
> What happens when the sprite id becomes invalid? For instance, when a vehicle crashes. I remember we had to handle that particular case for OpenLoco as well.

I did testing on all sorts of scenarios and couldn't find any problems.
As pointed out by @Broxzier, the `viewport_smart_follow_sprite` function is really... smart... and takes care of loads of different scenarios. It's the same function that is used to follow peeps etc in the Guest/Ride Window viewports.

**Comment by seifer7** [comment]
Sorry about 3 commits to do the changelog entry... it's 3:45am here. I think I should go to bed.

**Comment by Broxzier** [comment]
Since OP has not responded for a while, I'll squash and rebase this.

**Review by ZehMatt — APPROVED** [review]

**Review by Broxzier — APPROVED** [review]

**Pull request merged**
