### PR TITLE
Linux: use zenity or kdialog to show user dialogs

### PR DESCRIPTION
**Pull request by anyc**
With this pull request, the external applications kdialog (KDE/QT) or zenity (GTK) are used to display user dialogs under Linux. As these are external applications, we avoid the hassle of including QT or GTK in the source code and build system.
This PR includes the commits of #2826 and if neither kdialog nor zenity would be installed, the SDL message box would be shown.
Instead of specifying if we want an "open" or "save" dialog via a boolean, my first commit defines an enum which improves readability.

### CODE REVIEW

**Comment by janisozaur** [comment]
Hi, sorry it took so long to test it.

I eventually got down to it and found this to crash:
```
#0  0xf7949bce in __strncpy_sse2 () from /usr/lib32/libc.so.6
#1  0x014881c0 in platform_open_common_file_dialog (type=FD_OPEN, title=0x1659639 "Load Game", filename=0xffffd338 "/home/janisozaur/.config/OpenRCT2/save/autosave_2016-02-01_23-17-09.sv6", filterPattern=0xffffd43c "", filterName=0x15f05a0 <_extension> ".sv6") at /home/janisozaur/workspace/OpenRCT2/src/platform/linux.c:299
#2  0x014bcf84 in window_loadsave_mouseup (w=0x0, widgetIndex=0) at /home/janisozaur/workspace/OpenRCT2/src/windows/loadsave.c:322
#3  0x00000000 in ?? ()
```

```
>>> p filename
$1 = (utf8 *) 0xffffd338 "/home/janisozaur/.config/OpenRCT2/save/autosave_2016-02-01_23-17-09.sv6"
>>> p result
$2 = "/home/janisozaur/.config/OpenRCT2/save/autosave_2016-02-01_23-17-09.sv6", '\000' <repeats 325 times>...
```

This is using `zenity` on my system (Arch), there's also a message available:
```
executing "/usr/bin/zenity --file-selection  --title="Load Game" / --file-filter=".sv6 | *.sv6""...
```

I noticed you used `PATH_MAX` instead of `MAX_PATH`, as we use throuhgout the rest of the project, which is perhaps the root cause of this problem. Can you please change to `MAX_PATH`? I realise `PATH_MAX` may be more standard on Linux, but this would have to get changed in the platform file. I'd rather stick to current 260 char limit until we can drop the exe and possibly migrate filesystem stuff to C++.

**Comment by anyc** [comment]
Good point, I didn't notice the different name. The new commit uses MAX_PATH.

**Comment by Gymnasiast** [comment]
Loading a game via Zenity failed.

**Comment by anyc** [comment]
Yes, here too but the segfault happens here:
```
#0  0x015382f6 in gfx_draw_sprite_palette_set (dpi=0xffffc3bc, image_id=324290, x=36, y=3, palette_pointer=0x0, unknown_pointer=0x0) at github/OpenRCT2/src/drawing/sprite.c:643
#1  0x01537e5f in gfx_draw_sprite (dpi=0xffffc3bc, image_id=324290, x=36, y=3, tertiary_colour=0) at github/OpenRCT2/src/drawing/sprite.c:479
#2  0x014bf547 in window_top_toolbar_paint (w=0x1420538, dpi=0xffffc3bc) at github/OpenRCT2/src/windows/top_toolbar.c:808
#3  0x014994ba in window_event_paint_call (w=0x1420538, dpi=0xffffc3bc) at github/OpenRCT2/src/interface/window.c:1981
#4  0x01498688 in window_draw (w=0x1420078, left=0, top=0, right=1199, bottom=768) at github/OpenRCT2/src/interface/window.c:1547
#5  0x01538cf8 in gfx_redraw_screen_rect (left=0, top=0, right=1199, bottom=768) at github/OpenRCT2/src/drawing/drawing.c:328
#6  0x01538b94 in gfx_draw_dirty_blocks (x=0, y=0, columns=19, rows=96) at github/OpenRCT2/src/drawing/drawing.c:297
#7  0x01538a4e in gfx_draw_all_dirty_blocks () at github/OpenRCT2/src/drawing/drawing.c:273
#8  0x014959cd in window_update_all () at github/OpenRCT2/src/interface/window.c:177
#9  0x01543e74 in game_load_init () at github/OpenRCT2/src/game.c:956
#10 0x01543cce in game_load_save (path=0x25762b9 "/home/test/.config/OpenRCT2/save/toast.sv6") at github/OpenRCT2/src/game.c:901
#11 0x014ad690 in window_loadsave_select (w=0x1421838, path=0x25762b9 "/home/test/.config/OpenRCT2/save/toast.sv6") at github/OpenRCT2/src/windows/loadsave.c:707
#12 0x014ac4c2 in window_loadsave_scrollmousedown (w=0x1421838, scrollIndex=0, x=15, y=11) at github/OpenRCT2/src/windows/loadsave.c:400
#13 0x014992a7 in window_event_scroll_mousedown_call (w=0x1421838, scrollIndex=0, x=15, y=11) at github/OpenRCT2/src/interface/window.c:1917
#14 0x0153fc3b in input_scroll_begin (w=0x1421838, widgetIndex=7, x=449, y=257) at github/OpenRCT2/src/input.c:599
#15 0x01540e3b in input_widget_left (x=449, y=257, w=0x1421838, widgetIndex=7) at github/OpenRCT2/src/input.c:1028
#16 0x0153f376 in game_handle_input_mouse (x=449, y=257, state=1) at github/OpenRCT2/src/input.c:315
#17 0x0153ee28 in game_handle_input () at github/OpenRCT2/src/input.c:153
#18 0x0154579c in title_update () at github/OpenRCT2/src/title.c:549
#19 0x0153ad2e in rct2_update () at github/OpenRCT2/src/rct2.c:453
#20 0x01448c4a in openrct2_loop () at github/OpenRCT2/src/openrct2.c:454
#21 0x014486b3 in openrct2_launch () at github/OpenRCT2/src/openrct2.c:321
#22 0x0144f470 in main (argc=1, argv=0xffffca34) at github/OpenRCT2/src/platform/posix.c:64
```

**Pull request merged**
