### PR TITLE
Add spinning tunnel to dinghy slide, then log flume

### PR DESCRIPTION
**Pull request by 733737**
this allows spinning tunnel to be drawn on log flume, currently doesn't work correctly
saddsadasasdasdsaas

### CODE REVIEW

**Review by Gymnasiast — CHANGES_REQUESTED** [review]
This looks quite weird, with the boat going over the Car Ride track.

I would accept a PR that actually draws the water channel+spinning tunnel properly.

**Comment by 733737** [comment]
that would require new spritework, this implementation only works with cheats on and by changing the ride type back and forth, it's not adding the element to the drop down

**Comment by spacek531** [comment]
Even if it is completely hidden, it should still have good sprites.

**Comment by 733737** [comment]
my sprites don't look very good, but I'm going to be busy, don't know if I can fix them :| the spinning tunnel part works but the water clips out of it and isn't lined up correctly

**Comment by Gymnasiast** [comment]
You shouldn’t need to add sprites for this. Try taking a look at how the ghost train and car ride draw their tunnels.

**Comment by 733737** [comment]
whatever floats your log

**Comment by 733737** [comment]
if you do it for me i will analyze code since I'm curious

**Pull request closed without merging**
