### PR TITLE
Fix music style check for ‘niceness’

### PR DESCRIPTION
**Pull request by Gymnasiast**
Requires an objects release.

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
Is there perhaps a better name. Overbearing instead of not nice.

**Comment by Gymnasiast** [comment]
It would be fine by me. @IntelOrca what do you think?

**Comment by IntelOrca** [comment]
Maybe something like `musicalAppreciation` or `musicality` or `melodiousness`?

**Comment by Gymnasiast** [comment]
@IntelOrca I think Duncan is specifically talking about renaming `MusicNiceFactor::NotNice` to `MusicNiceFactor::Overbearing`.

**Comment by duncanspumpkin** [comment]
Yeah i was more about `not nice` as I think its not that its nice or not its more that it drowns out anything else.

**Comment by Broxzier** [comment]
I can understand the reasoning for 'not nice' having a value of -1 and 'nice' having a value of 1, though I'm not sure if that's the best approach. The previous implementation had values 1 and 2 as flags (2 was never really checked). This new implementation makes them mutually exclusive, while that doesn't have to be the case for all music.

**Review by duncanspumpkin — APPROVED** [review]

**Pull request merged**
