### PR TITLE
[Linux] Implement platform_get_locale_language.

### PR DESCRIPTION
**Pull request by Smeat**
A simple implementation of `platform_get_locale_language` using the environment variable `LANG`.

I don't know if this variable is present in all distributions (testet on Debian, Ubuntu and Gentoo), but if it's not the old behaviour is unchanged.

### CODE REVIEW

**Comment by PFCKrutonium** [comment]
So if getting lang from LANG fails, it falls back to original?

**Comment by AaronVanGeffen** [comment]
Before the call to `STUB` is removed, the function should implement detection for all languages available in OpenRCT2, I think.

**Comment by janisozaur** [comment]
:-1: that's not the proper way to query locale.

See http://man7.org/linux/man-pages/man7/locale.7.html

**Comment by Smeat** [comment]
Yes, it falls back to original.

It iterates through `LanguagesDescriptors` in `language.cpp`, so all supported Languages are detected.

Sorry, if this is not the proper way. I made a new commit with querying locale. If it's still not okay, this PR can be closed an I will put it to my local patches ;)

**Comment by Gymnasiast** [comment]
Well, as @AaronVanGeffen already remarked, some languages are missing. It shouldn't be too difficult to add support for those. `nl_*` can be connected with `dutch`, for example.

Otherwise, this is a very welcome PR to get Linux closer to feature parity with windows. So please don't close the PR. :)

**Comment by Smeat** [comment]
Those aren't missing. I iterate through `LanguagesDescriptors` to compare the locale on the system with all available languages in OpenRCT2. Tested this with a bunch of languages. This way this code don't have to be changed if new languages are added.
Or am I missing something?

I am relatively new to contributing on GitHub, so I am rather careful and don't want to contribute bad code or something like that :)

**Comment by Gymnasiast** [comment]
What happens when a user has his system set to nl_BE then? The Dutch translation is marked as nl_NL. A similar thing applies to Korean - marked as `ko`, not `ko-KR`.

Generally, for most languages, only the first part is relevant. The only current exceptions are English and Chinese.

**Comment by HaasJona** [comment]
Generally we should try to match the whole language first and if that fails only match the first 2 chars and if that fails fall back to en_uk

**Comment by Smeat** [comment]
That's why I am only comparing the first part of the string. So for nl_NL, nl_BE or nl_whatever the search pattern is nl*, which matches `nl-NL` in `language.cpp#L83`.

**Comment by Gymnasiast** [comment]
Good, in that case this PR is fine as far as I'm concerned.

**Comment by janisozaur** [comment]
You should not use `fnmatch` comparison in this case, as it can match anywhere in the string without telling us where exactly.
You should check first two characters from `pattern` against first two characters of locale from `LanguageDescriptors`, if this succeeds, you should then proceed to check the second part (country) of locale. This would also get rid of the hacks that you put in place to support simplified versions of Chinese and GB vs US, more of which would surely come.

**Comment by HaasJona** [comment]
@smeat but then we would need to special case things again in case we add a nl_BE translation. Better follow the general algorithm I outlined above.

**Comment by janisozaur** [comment]
I agree with @HaasJona, that's basically what I wrote in my comment

**Comment by Smeat** [comment]
Thanks for the input. That would indeed be a way better solution. I just tested if it works with the current version and didn't think much about future changes, sorry.

I will look into that later or tomorrow.

**Comment by Smeat** [comment]
Updated my version.
First I strip of the unnecessary parts and replace the '_' with a '?' (? in case the delimiter in language.cpp changes).
Then I try to find the full language string (e.g. nl_BE) in `LanguagesDescriptors`.
If that fails the pattern is changed to `language*` (e.g. nl*).
If everything fails the language is set to `LANGUAGE_ENGLISH_UK`.
I hope my code isn't too ugly. I have never really worked with C strings before.

One problem with this solution might be a wrong match. For example I get traditional Chinese, but need simplified Chinese (zh_CN).

@janisozaur `fnmatch` will only match the beginning of the string, because there is no asterisks at the beginning of the pattern.

**Comment by Gymnasiast** [comment]
You would need to handle special cases after the exact match but before the 'half-match' part.
As far as I can see these are the following:
`en-CA` should load `en-US`.
`zh-CN` should load `zh-HANS`
`zh-TW`(?) should load `zh-HANT`

**Comment by Smeat** [comment]
Sorry, forgot to comment.
I have implemented all Linux and locale specific functions.
I hope they are okay this way. For measurement the only solution I could find, was to make some special cases.

**Comment by Gymnasiast** [comment]
Seems ok to me.

**Comment by janisozaur** [comment]
It crashes when I set `LANG` without coding part, which I believe is a valid value. Anyway, even if `LANG` is not valid, it should not crash.

```
$ echo $LANG
pl_PL.UTF-8
$ LANG=nl_NL gdb ./openrct2
(…)
(gdb) r
Starting program: /home/janisozaur/workspace/OpenRCT2/build-clang/openrct2 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
WARNING[/home/janisozaur/workspace/OpenRCT2/src/platform/posix.c:55 (main)]: Function int main(int, const char **) at /home/janisozaur/workspace/OpenRCT2/src/platform/posix.c:55 is a stub.

WARNING[/home/janisozaur/workspace/OpenRCT2/src/openrct2.c:534 (openrct2_setup_rct2_segment)]: mmapped file to 0xf6bb9000
WARNING[/home/janisozaur/workspace/OpenRCT2/src/util/util.c:209 (safe_strncpy)]: Truncating string  to 48 bytes.

Program received signal SIGSEGV, Segmentation fault.
0xf7a80bb1 in __strlen_ia32 () from /usr/lib32/libc.so.6
(gdb) bt
#0  0xf7a80bb1 in __strlen_ia32 () from /usr/lib32/libc.so.6
#1  0xf7ac7d1c in fnmatch@GLIBC_2.0 () from /usr/lib32/libc.so.6
#2  0x081c34e9 in platform_get_locale_measurement_format () at /home/janisozaur/workspace/OpenRCT2/src/platform/posix.c:724
#3  0x080b5e31 in config_set_defaults () at /home/janisozaur/workspace/OpenRCT2/src/config.c:337
#4  0x081c3b27 in openrct2_initialise () at /home/janisozaur/workspace/OpenRCT2/src/openrct2.c:197
#5  0x081c3dfb in openrct2_launch () at /home/janisozaur/workspace/OpenRCT2/src/openrct2.c:267
#6  0x081c0a74 in main (argc=1, argv=0xffffd734) at /home/janisozaur/workspace/OpenRCT2/src/platform/posix.c:59
(gdb) up 2
#2  0x081c34e9 in platform_get_locale_measurement_format () at /home/janisozaur/workspace/OpenRCT2/src/platform/posix.c:724
724		if(!fnmatch("*_US*", langstring, 0) || !fnmatch("*_MM*", langstring, 0) || !fnmatch("*_LR*", langstring, 0)){
(gdb) p langstring 
$1 = 0x0
(gdb) 
```

**Comment by Smeat** [comment]
If you specify an unsupported language (aka locale not installed on your system), setlocale returns a null pointer, so the default value should be returned.
Sorry, forgot to test for a null pointer in the last three functions I implemented, shouldn't happen.

**Comment by janisozaur** [comment]
It looks ok now, detected Polish on my system properly.

I think it's ready now.

**Pull request merged**
