### PR TITLE
Read title sequence from ZIP files

### PR DESCRIPTION
**Pull request by IntelOrca**
Currently work in progress.

Changing it so that title sequences are now zip files containing script.txt and the save files. Using zip makes them much easier to distribute and zip is the most widely used archive format across platforms.

I choose libzip for the zip library, it looked like it was more available as a package than minizip. Its only dependency is zlib which we already use.

After completing this, I will move the script format to JSON (#4575). You can't put comments in JSON, but instead all comments and credits etc can be bundled in the zip file as separate files.

### CODE REVIEW

**Comment by janisozaur** [comment]
This fails on Travis' Ubuntu jobs, because it is using ancient version of libzip, 0.10.1 http://packages.ubuntu.com/trusty/libzip-dev

Docker (Arch Linux) builds work just fine, as it has libzip 1.1.3

Either a backported package or modifying sources to match libzip 0.10.1 is needed.

While I hate being stuck with old versions of libraries, Travis has just started offering Trusty (14.04) images on their container based infrastructure, which brings a lot of improvements, so it may be worth investigating what would be required.

For the record: Xenial (16.04) is [planned for around 2017Q2](https://github.com/travis-ci/travis-ci/issues/5695#issuecomment-259221773)

**Comment by marijnvdwerf** [comment]
Can't this be modified to support both folders and zip archives? Requiring _yet another_ library will make it harder to port to new platforms.

```
Title Sequences
  |-Folder1
  |   |-script.txt
  |   |-park.sv6
  |
  |-Folder2
  |   |-Unrelated.xsls
  |
  |-Default.zip
```

So Folder1 would be listed, along Default.zip (if it includes the required files), and Folder2 will be ignored.

**Comment by janisozaur** [comment]
I'd like to see it `#ifdef`-guarded, for reasons I stated above. Also, I assumed support for unpacked title sequences stays, if it isn't I vote huge 👎 on this.

**Comment by IntelOrca** [comment]
I would like to use zip for many other things so its something we need to resolve.

**Comment by janisozaur** [comment]
Sure, but requiring zip over unpacked things? That doesn't sound good.

**Comment by IntelOrca** [comment]
Why is it such a big deal?

**Comment by PFCKrutonium** [comment]
Depending on your storage solution, ZIP may be faster or slower to load. Not to mention, what if we port it to a platform that doesn't have that library available, see @marijnvdwerf 's comment.

**Comment by janisozaur** [comment]
@IntelOrca I wouldn't enjoy having to re-pack whatever I'm working on over and over again for the tiniest of changes. Would you? Isn't that enough of a reason?

**Comment by IntelOrca** [comment]
What like having to recompile the game every time you change something?
There is a built in editor anyway.

**Comment by PFCKrutonium** [comment]
Most people making title sequences are likely not developers - and I guarantee someone will complain at some point.

**Comment by janisozaur** [comment]
Maybe for title sequences, but even then it's a stretch. What about all the "many other things" that you mentioned?

**Comment by IntelOrca** [comment]
objects is another idea

**Comment by janisozaur** [comment]
This is precisely what I want to avoid: having to zip all the things. That's just a useless additional step in my way I now need to perform. I agree this can be beneficial distribution-wise, but not at a cost of dropping support for unpacked assets.

**Comment by marijnvdwerf** [comment]
Chrome also uses zip for plugins etc, but still allows you to directly load a folder for development.

Anyhow, I'm not directly opposed to this, mostly the hard dependencies on the library. For the Android version I'd rather have an implementation that uses `java.util.zip.ZipFile`. I'd also like to have an additional iterator/whatever for `android.content.res.AssetManager` next to the filesystem, so stuff doesn't have to be copied outside the APK.

**Comment by IntelOrca** [comment]
I tried to find a library that was most widely available. But if you can find a better one, then that's fine. I don't see how its any different from any of our other dependencies that we have. For Android that's fine, I also suggested doing that for HTTP.

**Comment by marijnvdwerf** [comment]
The specific library really isn't an issue, but a more pluggable implementation would be welcome (Something like https://flysystem.thephpleague.com/api/. So `IFileSystem` with `LocalFileSystem`, `ZipFileSystem` and `AssetFileSystem` or something along those lines.)

**Comment by spacek531** [comment]
My 2c on the zip thing: if it's going to remove the capability to load title sequences from folders, I give it a big thumbs down. I do not want to have to manipulate zip files when things get awry while I'm making title sequences.

**Comment by janisozaur** [comment]
https://github.com/fgenesis/ttvfs is small and encourages static linking.

https://icculus.org/physfs/ is written by Ryan Gordon himself and packaged properly (http://packages.ubuntu.com/trusty/libphysfs-dev)

http://avf.sourceforge.net/ supports plethora of formats and has packages too: http://packages.ubuntu.com/trusty/avfs

There are surely more out there, but one of these should fit the bill. Both of them allow for transparent access (as far as I can tell from quickly skimming the docs) inside archives, so we could even use it for accessing RCT2's assets.

I'd like to pursue such path, so we can replace SDL's `SDL_RWops`, as even for headless server we need to pull in SDL package, which in turn requires GL and you end up with a whole X11 installed for what was supposed to be headless.

**Comment by IntelOrca** [comment]
I have reinstated folder support for title sequences.
I have extracted the zip handling to an interface so the implementation can be inter-changed.

**Comment by LRFLEW** [comment]
@janisozaur How is libarchive support on Ubuntu 14.04? It might be a good idea to add that as an alternative interface implementation if the support for it is better than lib zip.

**Comment by janisozaur** [comment]
@LRFLEW I'll check it soon, I haven't had much time lately.

@IntelOrca check Travis builds please.
```
[  1%] Building C object CMakeFiles/openrct2.dir/src/audio/audio.c.o
In file included from /work/openrct2/src/audio/../interface/viewport.h:23:0,
                 from /work/openrct2/src/audio/audio.c:18:
/work/openrct2/src/audio/../interface/window.h:710:46: error: ‘struct TitleSequence’ declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
 void window_title_command_editor_open(struct TitleSequence * sequence, int command, bool insert);
                                              ^~~~~~~~~~~~~
```

**Comment by LRFLEW** [comment]
@janisozaur I had fixed that issue in the commit that @IntelOrca added, but he rebased it to remove that fix. You can see what I did at [IntelOrca/OpenRCT2#38](https://github.com/IntelOrca/OpenRCT2/pull/38/commits/80df35bd6ff1ffad7918a9363896cac840470caf).

**Comment by janisozaur** [comment]
Now that travis jobs got updated to ubuntu 16.04, this should pass. I only need to provide libzip to mingw.

@IntelOrca can you rebase? You'll have to drop 2c92213

**Comment by janisozaur** [comment]
all 🍏 now :)

**Pull request merged**
