### PR TITLE
Add cheat to show all drawable track elements

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by janisozaur** [comment]
network version…

**Comment by Nubbie** [comment]
I can't see any changes in-game, 
what does the cheat do as an example? (translation purpose)

**Comment by Gymnasiast** [comment]
Well, the Corkscrew and Hypercoaster use the same track style. If you build a Corkscrew, you can build loops and corkscrews. If you build a Hypercoaster, you cannot.
If you turn this cheat on, you can build loops and corkscrews on both.

Basically, it will make all elements that track style can handle available in the construction window.

**Comment by Liampie** [comment]
How would this work for the twister coaster? There are two types of flat-to-steep (and steep-to-flat): a compact one tile version from the vertical drop coaster, and a three tile long version with a large radius.

**Comment by Gymnasiast** [comment]
The vertical drop coaster is a distinct type with its own ID. So the vertical drop coaster will use the small flat-to-steep piece and the twister rc will use the large piece.

**Pull request merged**
