### PR TITLE
Speedrunning

### PR DESCRIPTION
**Pull request by thyeggman**
An attempt at implementing speedrunning in OpenRCT2.

**Overview**
This implementation of speedrunning is opt-in.  Currently the option resides in its own tab in the options menu.

image

Turning on speedrunning mode changes how the game evaluates scenario completion.  For each objective type, the completion requirements are evaluated at the end of each day.  For some types of scenarios this doesn't change anything, but for date-based scenarios, they are considered completed when you meet all the requirements before the target date.

This is the UI on the Scenario Select page (see below for thoughts on improving it):

image

The first option is only available on the first scenario in each group, and will prompt on the scenario objective screen for each level to advance to the next one in the group.  The  other option (Start IL (individual level) Run) will run only one scenario and then report the time at the end.

Here is the UI for a completed scenario:

image

The player's time in both days and minutes/seconds are reported.  These scores are saved to files under the same root as the current highscores.dat.  If cheats have been used, the warning will be shown and the highscores will not be recorded into files (but will still be displayed).  The "Next Level" button will go to the next scenario in that group if the player is doing a full speedrun.

Clicking anything in the cheats menu or opening the console are considered cheats, and both invalidate the run.  Multi-segment runs are not supported, because the time calculation relies on system time.  Supporting multi-segment runs also likely requires a new save file type.  Loading a scenario from anywhere other than the main menu will mark the run as invalid.

**Open Issues and Questions**

- [ ] The UI on the front page may be somewhat unintuitive.  Looking for suggestions.  I'm thinking of removing the buttons and defaulting to IL speedruns, except for the first scenario in a group, which would give a prompt asking if the player wants to do a full run.
- [ ] Still need to display highscores somewhere.  Was considering replacing the company value & name display on scenario select.
- [ ] Should speedrunning be disabled in multiplayer?  Currently I don't think it will break anything but there are likely many scenarios surrounding multiplayer that I didn't account for.
- [ ] There's a todo for a load scenario call, for which I don't know if the speedrun should be invalidated to prevent multi-segment speedruns.
- [x] I haven't done a full speedrun yet to see if running all the way through a category works.
- [ ] There's a invalidate check commented out for testing that needs to be uncommented.
- [ ] Speedrunning option should be combined into another tab.
- [ ] I don't know how to initialize the days and time highscores files if they don't exist in the user's Documents folder or equivalent.  I added them manually for testing.
- [ ] A full speedrun is supposed to record final times instead of one time per level.  Need to fix this and create a highscores for it.
- [ ] For some reason the full run category loops from the last in a category (e.g. Thunder Rock) to the first in the next category (e.g. Whispering Cliffs).

### CODE REVIEW

**Comment by Patrik356b** [comment]
The text "cheats has been used" is kinda hard to read due to colour, but otherwise this is looking good.

**Comment by thyeggman** [comment]
@Gymnasiast I'm not sure what you had in mind, could you elaborate?

**Comment by jensj12** [comment]
TBH, I'd say that RCT should have used completion time (IL speedrun) instead of company value right from the start (without the full run option).

**Comment by Krutonium** [comment]
@thyeggman @Gymnasiast is referring specifically to the Plugin API that will allow plugins to be written to add features to the game. The problem being that said API afaik does not yet exist in a usable fashion.

**Comment by thyeggman** [comment]
That's cool; we can talk about moving the functionality after the plugin API is complete, but if it doesn't exist yet it would be a shame not to merge something that is totally optional in the first place.  

I'm completely willing to do the work to move it once the plugin functionality/API is finished (and well-documented!).

**Comment by Gymnasiast** [comment]
My gripe with this is that is complicates the code base for something that will appeal to an incredibly small amount of players. The whole point of the Plugin API will be to make stuff like this easy to add without affecting other players. As for merging now and splitting later: we already have stuff we want to strip out, most of it lighter than this.

**Comment by LRFLEW** [comment]
@Gymnasiast I get your point, but I'm not sure I entirely think this should wait for the plugin API. In particular, having a built-in IL timer can help grow a speedrunning community. Just look at how the timer in A Hat in Time has helped foster that game's speedrunning community. Having such a timer be a plugin has two problems. One, most speedrun record sites have strict rules against modifications of the base game, and plugins are generally included with that. Making the timer an "optional plugin" removes a lot of its validity. And second, having it in the game directly makes it more enticing. Just showing a player a timer can make them gain interest in trying to speedrun. I think creating a speedrunning community would be a great thing for this community, and this feature would help foster it.

That being said, as a core feature, this may be simplify-able. Instead of this being a strictly "speedrunning" feature, this could be more simply a game timer, and the speedrunning aspect could branch off of it, with a future plugin adding UI elements to complement a core timer feature.

**Comment by Gymnasiast** [comment]
How many of our players would genuinely be interested in a speedrunning feature, though? I doubt there will be that many.

As for speedrunning sites not accepting plug-ins: that's too bad, but I don't think it's our job to solve a problem that other people have created.

**Comment by wolfreak99** [comment]
I would honestly love a speed run option. I've been wanting to play through the game for a while to see how fast I can beat it, but am stuck fast forwarding most of the time, which significantly impacts speedrun times. 

As far as the looks of it, I have not tested this yet, but the idea of a "next level" option is REALLY pleasing, even outside of speedrun mode. I'd like that to definitely be a feature. Definitely switch the text to "Next scenario". Maybe where it displays the next level name in the tooltip when hovering over it? 

For streaming sake, it would be cool to have an option that displays the elapsed IRL time, similar to the text for the FPS or the version shown on the title, maybe in the bottom right, or alongside the fps counter. somewhere that doesn't interfere too much with game screen estate.

I think the "cheats have been used" text should appear below the "congratulations" days/time portion (if the text is visible, otherwise the current spot is fine). Something like https://i.imgur.com/bHME03F.png would work.

I have to leave for a bit but I may or may not edit my comment later and add more once I get back.

**Comment by thyeggman** [comment]
@Gymnasiast I think the arguments you're making could be applied retroactively to multiplayer as well... "People played RCT without multiplayer for 15 years, why would they play now?" or "Even if we implemented it, how many people would use it?"... But that feature turned out to be very successful.  I don't understand why speedrunning is any different.

**Comment by Gymnasiast** [comment]
Oh, I do. Multiplayer has a far, far wider appeal than speedrunning. Not to mention that CS already laid the groundwork for it. Also, OpenRCT2 is not a game that lends itself very well to speedrunning in the first place. Often, having to fulfil the criteria at the specified date is harder than just fulfilling them at any earlier point.

**Comment by Gymnasiast** [comment]
I'm going to close this, for the following reasons:
- Too limited in appeal
- Code quality is bad:
  - Adds code all over the place (acceptable when you have a wider appeal, which this hasn't)
  - Does not adhere to code guidelines at all - you even used tabs.
  - Interface does not match either (adding a separate tab just for this option is... odd)
  - Does not compile
- Checking the objective every day alters the objective - the goal isn't to have 600 guests or whatever, but to have them at a fixed point in time. Check every day and you have basically changed the goal.

I'm going to give you a lifeline though. If you manage to post a PR with better code, residing mostly in one place, I'm willing to give it another think. (No guarantees, but I will not dismiss it out of hand.)

**Comment by AaronVanGeffen** [comment]
In cases like these, it is difficult to decide when to dismiss a PR, especially when the author has obviously spent quite some time on it. For the record, I would like to stress we've talked about this extensively in our team chat.

We really do appreciate the enthusiasm with which you've been developing this feature. If nothing else comes from it, I do hope you'll be able to enjoy it as a fork of the main game.

**Comment by thyeggman** [comment]
Before I go and rethink everything, it would be nice to know what would be acceptable.  You've already outlined a few things, namely: code in fewer places and following guidelines.  Here are my are questions:

- Where are your code guidelines listed?
- Would these features be acceptable by themselves, e.g. would a "Next scenario" button be accepted?  Would an "early completion" option be accepted?
- If all a speedrunning feature was accepted full stop, what things would constitute a minimum bar?  I'm thinking of high scores in particular, which add a lot of repetetive code.  Are those necessary?

Also, to defend myself, my latest commit is marked as WIP and I know it didn't compile.  The speedrunning option being its own tab is specifically called out as something that needs to be fixed in the open issues.  Lastly, I am aware that the early completion change fundamentally changes how scenarios are completed, in the effort of giving people more ways to speedrun (days versus time).

**Comment by thyeggman** [comment]
As long as I'm thinking of things which would make it more acceptable, I could also prevent normal completions from being recorded at all in speedrunning mode, so neither the company value nor the check mark would appear when not in speedrunning mode.

**Comment by LRFLEW** [comment]
>Checking the objective every day alters the objective - the goal isn't to have 600 guests or whatever, but to have them at a fixed point in time. Check every day and you have basically changed the goal.

Sure, but it's not like this PR changed it universally. Personally, I'd be **all for** a setting that changed the behavior in this way. People who prefer the original system still have it their way (and by default), but people who'd rather just try to hit the goal quickly have the *option* to do so.

I said before in the team chat and to @thyeggman personally that I think that there are multiple core features that could be salvaged from this and made into separate PR's. The way I see it, the features that I think could be implemented without being too narrow in appeal would be:

* An option to have scenarios trigger immediately when the target is achieved before the deadline (instead of only when the deadline arrives)
* A day counter for how long it took in game time to achieve the goal on the results screen. (For either scenarios that don't have a fixed time (like build 10 rollercoasters) or with the above option enabled)
* A real-time counter for how long it took to achieve the goal on the results screen. (Might be limited to single-session plays until we have our own save format)
* A "Next Scenario" button on the results screen.

Each of these features on their own can have a wider appeal, and would take significantly less code changes than this as a whole. While some of these may still be more "plugin" style features, they would still be simple enough to reconsider on their own.

**Comment by thyeggman** [comment]
Thanks @LRFLEW.  I think the main question for me is if these feature should be hidden behind options (of course it would be required for the early completion feature), or because they're just stats, to include them by default.  I think for a fully-fledged speedrunning mode, high scores should be included, but for now I'll leave those out.  

I'll keep an eye on any comments in this thread so please let me know if you have any ideas or suggestions.

**Comment by wolfreak99** [comment]
I would definitely consider creating a PR with the next scenario option. I would say create a variable for gGameScenarioNextPath in game.h that is stored upon loading a scenario file (make sure this is done in the load scenario code, and not from the scenarioselect callback), otherwise you may have to go through a bit of hoops in order to find the next scenario file. You *may* be able to get away with using gCurrentLoadedPath, but i'm not sure if it's stored when loading a scenario from the scenario select.

If you would like any help, or would like my assistance, I could give porting it a go.

**Comment by thyeggman** [comment]
@wolfreak99 Thanks for the offer, I think I'll give it a shot myself first.  I made it this far, may as well see it through :)

**Pull request closed without merging**
