### PR TITLE
Fix vehicles appearing separate in the research tree, fixes #3198

### LINKED ISSUE #3198: Debug tools, changing available objects splits rides with different vehicles in research tree
**Version:** Current dev build

Changing available objects via the debug tools has a bug that splits rides with multiple vehicle types, such as Car Ride and Mini Roller Coaster, into separate items in the research tree. Upon researching the first vehicle type in a scenario, that ride will have every vehicle available to choose from even though they are still yet to be researched, thereby wasting time and money when they start being researched later. This does not happen when using the scenario editor.

**Steps to reproduce:**
1. Open objects menu in debug tools
2. Close objects menu, research tree is reset and splits all rides with multiple vehicles into separate researchable items

**Screenshots / Video:**
scr6

### PR DESCRIPTION
**Pull request by marcovmun**
Fix bug what is described in issue #3198

### CODE REVIEW

**Comment by janisozaur** [comment]
@marcovmun could you please make the commit message just a little bit shorter?

**Comment by marcovmun** [comment]
I have altered the commit message.
is it so good?

**Comment by janisozaur** [comment]
yeah, much better now, me likes :)
thanks

**Comment by Gymnasiast** [comment]
It's good AFAIC, but (next time) it's better to do your commit message like:

Fix vehicles appearing separate in the research tree__, fixes #3198__

This makes it easier to close the bug you solved.

**Comment by janisozaur** [comment]
Tested, working. :+1:

**Comment by Gymnasiast** [comment]
Confirmed.

**Pull request merged**
