### PR TITLE
Added input to add kick-messages for issue #3248

### PR DESCRIPTION
**Pull request by Mijago**
Added Input to add Kick-Message for issue #3248

**This is still WIP**, but I searched for over an hour now how to send the text correctly and it just won't work for me.. So please have a look on it.
I marked it with `// Here is still an error.. Only the first four Bytes are copied; If I try "Cookie", it only sends "Cook?"` in `network.cpp`, so you should be able to find the position.

Everything except the display of the message works like a charm.

I hope it is okay that i ask you for tips, but you know the source better than I and that will save me a bit of time (also, I want to sleep now).

The current problem is, that if I want to use the message "Cookies or so" (or similar), it only sends "Cook?" (yes, it displays a questionmark). I know that has to do with the pointers, but you might have some specific hints for me.

### CODE REVIEW

**Comment by zsilencer** [comment]
game commands are limited to a few 4 byte registers so they do weird things to set strings like storing 4 bytes of the string separately in each param or calling it multiple times to set different parts of the string.  Look at the ones to set ride or guest names for example, this is an issue with game commands that needs to be done differently at some point but right now that's how it is.

**Comment by IntelOrca** [comment]
Game commands should only be used for... game logic, anything else should be their own type of packet or sub packet in network.cpp. You then have more freedom in this respect.

**Comment by Mijago** [comment]
Orca, you know the source much better than I do, do you have any specific hint or declaration? 
It's just about saving time :D

**Comment by Nubbie** [comment]
Use @Nubbie to contact people, will tell them about it so they dont miss it ;p

**Comment by IntelOrca** [comment]
Have a look at how send chat is done.

**Comment by Nubbie** [comment]
Yeah, the way the chat works might give you a clue :o 

Also, like I said in another PR off yours, I see you're giving out 'string ids' in 'string_ids.h' but you're not adding any new strings, you should add strings in your PR and you can find the language file to do so in `OpenRCT2/data/language/en-GB.txt` _(en-GB is the original file new strings are going into, the other language files are used for translations made by people in [Localisation repo](https://github.com/OpenRCT2/Localisation))_ :)

**Comment by wolfreak99** [comment]
Wait why was I tagged? 
To add text string IDs to the game, you will want to put the string at the bottom of the data/language/en-gb.txt (following the format and string numbers of the previous lines, so if you want "hello world" at the bottom, you'll want
STR5000    :some text here
STR5001    :some text there
STR5002    :some text everywhere
STR5003    :hello world
At the bottom right above the scenario details.
After you paste it into that file, you then assign it a string in src/localisation/string_ids.h
So you scroll to the bottom of that file and, following our previous example, you would put (above the str_count line)
STR_SOME_TEXT_HERE = 5000,
STR_SOME_TEXT_THERE = 5001,
STR_SOME_TEXT_EVERYWHERE = 5002,
STR_HELLO_WORLD = 5003,

(One thing I personally am not sure about is if you need to increment the str_count at the bottom, so if someone can follow up on this id appreciate it. Otherwise, ID say increment it just to be safe)

After you have added the appropriate things to en_GB.txt and string_ids.h, you will want to run the script "build". I would read the " compilation" instructions for compiling the game originally. You know how you have to do the power shell stuff with /setenv.ps1 and install and build? You basically need to run the build command again in order for the data to be copied over, otherwise it will still show up as "(undefined string)". To make it short ID run it with the syntax " build data" that way it only builds the strings and not the entire game, that is if you've already built /compiled the game in visual studio.

**Comment by Nubbie** [comment]
@wolfreak99 Tagged you as I know you have some experience with his question:

> The current problem is, that if I want to use the message "Cookies or so" (or similar), it only sends "Cook?" (yes, it displays a questionmark). I know that has to do with the pointers, but you might have some specific hints for me.

**Comment by wolfreak99** [comment]
I remember having this problem.. You know I'm actually gonna try to make a pull request for my current version. But when I get home in like 3 or 4 hours I'll check out this repo and find out why it is doing the question mark.

Though I just wanna put my opinion out there, I feel like writing a kick message for someone is a waste of time when they can get back in in just 2 seconds. I just feel like It would take more time to write it out than the person to rejoin, which i think would be a waste of time. 

But if people really want this feature despite this concern, i'll help. I want to help provide the best experience / features I can for the online community I can provide.

My approach will likely be a dropdown/context menu from the kick button that has like
"Vandalism
Spam
Hate speech
Innapropriate content
Illegal content
Other"

Possibly have 3 or 5 slots that would store the most recent custom messages.

That would at least make it a little quicker than manually writing out each time the person rejoins.

**Comment by IntelOrca** [comment]
I agree that pre-defined options would be better because then they can be localised.

**Comment by wolfreak99** [comment]
Predefined and custom input, with maybe an option from the server host to disable custom inputs or have custom messages. "silly reasons" is from one owns perspective, i look at it like this: if someone is willing to set up and host their own server, they should have some freedom. if a server host wants to write silly reasons, you know.. let them...

**Comment by Nubbie** [comment]
Thought I had my say about this PR but it didn't get posted it seems :U 

I heavily supports the pre-made options, I'm not the biggest fan off the custom one just because it can be used as a harassing tool and doesn't add much benefits if you consider the negative effects, with some really efficient strings being added instead, there will not be any needs for custom messages
I dont want to be kicked from a guy with the message 
`Kicked: **** OFF U ****** , HAHAHAHA UR BANDD!`

Like Wolfmod suggested with a drop list sounds the best and his options are some that would be great. Some options might be:

- Greifing
- Harassment
- Spam
- Breaking this servers rules
- Inappropriate behaviour
- Other

**Comment by wolfreak99** [comment]
Hey nubbie thanks for pointing out the break coaster button, I was actually wanting to do something exactly like that but didn't wanna redesign it from scratch myself, now I could just copy and modify the break ride into the window . thanks!

**Comment by Nubbie** [comment]
So is this being worked on or should we switch to a 'localisation based' option? :o

**Comment by Nubbie** [comment]
@Mijago Still working on this?

**Comment by wolfreak99** [comment]
Guys, just wanna give a heads up on my progress, I have got this implemented and (partially) working in a branch I have not yet committed or anything. All I gotta do is get it to show the kick message when the user is kicked (right now it's showing "connection closed" without any relavence to being kicked so I gotta look into that), and then I'll just tidy up the code a bit and do a pull request.

In the meantime, help me brainstorm some predefined reasons (keep it short).
Right now I have
No reason (which shows get out of the server)
Vandalism
Spam
Harassment
Inappropriate content
Illegal content
Other reason (whixh allows a custom msg)

**Comment by Nubbie** [comment]
@wolffreak99 I really don't like the custom menu idea, it will never be used for good like pre defined strings, dont think you need anything else than some good predefined strings

Have some examples further up

**Comment by wolfreak99** [comment]
I've had many times I've needed custom messages, such as "Discussing packet jamming", "Renaming ride credits", etc. I feel ultimately that should be up to the server host. If someone is willing to donate their bandwidth to run a server for this game, should they be told how to run their server? Maybe an option that allows only the server host to use custom messages (that way other users couldn't abuse it) . That can be left for discussion once i post this pull request, as i fixed the problem and all i have to do now is tidy up the code and then rebase it.

**Comment by IntelOrca** [comment]
Superseded by #3964

**Pull request closed without merging**
