### PR TITLE
contributors.md - New name on Github (Nubbie)

### PR DESCRIPTION
**Pull request by Nubbie**

### CODE REVIEW

**Comment by Wirlie** [comment]
Suggestion: Because this is a minimal change (and it not affect the code of the project) you can add `[ci skip]` in your commit message xP this prevents that the CI systems rebuilds the entire project.

**Comment by Nubbie** [comment]
@Wirlie Oh.. never knew about that, but I've fucked up plenty today with all sorts of things so don't want to mess up more xD
Thanks

**Comment by Nubbie** [comment]
AND IT STILL FAILED xD
Well.. guess it doesn't really matter

**Comment by Wirlie** [comment]
At some times AppVeyor fails (dont worry for that xP you can see the AppVeyor log for this build: https://ci.appveyor.com/project/IntelOrca/openrct2-ject9/build/0.0.4.1791, this is a problem before the build process, not after).

**Comment by Nubbie** [comment]
Ooh, never seen it do that but as it just changes my name on a list, it doesn't matter :)

**Comment by Wirlie** [comment]
Yep, that's the real point haha xP

**Pull request merged**
