### PR TITLE
Object repository improvements: "force-scan" command, add conflict counter.

### PR DESCRIPTION
**Pull request by wolfreak99**
Just a couple of minor tweaks to help, should a user decide to go through and clear out the conflicting objects.

### CODE REVIEW

**Comment by IntelOrca** [comment]
Braces always go on separate lines in C++ files

**Comment by Gymnasiast** [comment]
@IntelOrca Does that apply to the command definitions as well? The current ones have braces on the same line.

**Comment by IntelOrca** [comment]
@Gymnasiast I don't quite know what you mean. I mean braces of methods, if statements, for loops, but not switch statements. Basically just make it look like the code in the same file.

**Comment by wolfreak99** [comment]
@IntelOrca I believe he is meaning the ones on line 82 of RootCommands. But I did fix the implied braces.

**Comment by IntelOrca** [comment]
I think it would be better to just have an action to rescan the objects, but not start the game. E.g. like `set-rct2`

**Comment by wolfreak99** [comment]
@IntelOrca I'm not entirely sure how I would go about doing that. Like i see the way set-rct2 is handled within rootcommands.cpp with the exit code, but im not sure how I would call just initializing the scan directly from rootcommands, or if it would be okay to, instead of checking the force_scan_flag and disabling it before scanning, check after the scan and then close the game if it's enabled. I'd like to just call the scan from rootcommands but im not sure how to do that without using object_list_load which will load the repository but unload object manager (which I'm unsure if it will throw an error or not, have not had time yet to experiment).. how do you think I should approach this?

**Comment by IntelOrca** [comment]
You should be able to just call the ObjectRepository directly from RootCommands, no other files need to be modified.

**Comment by wolfreak99** [comment]
@IntelOrca I just tried and it said unresolved external symbol _GetObjectRepository() (and then tried to move the include to outside of the "extern c" includes and it said "unknown external symbol int * _log_levels" (?_log_levels@@3PAHA)").. but i should be able to though, i'm just not sure what that log levels thing would have to do with it.

**Comment by IntelOrca** [comment]
You must have the include statement for ObjectRepository outside of the extern C block.

**Comment by Gymnasiast** [comment]
CI shows an error:
```
 /Users/travis/build/OpenRCT2/OpenRCT2/src/object/ObjectRepository.cpp:309:13: use of undeclared identifier 'object_repository_force_scan_flag'

        if (object_repository_force_scan_flag)

            ^

❌  /Users/travis/build/OpenRCT2/OpenRCT2/src/object/ObjectRepository.cpp:313:13: use of undeclared identifier 'object_repository_force_scan_flag'

            object_repository_force_scan_flag = false;

            ^
```
Otherwise, it looks good to me.

**Comment by wolfreak99** [comment]
@IntelOrca  @Gymnasiast  I fixed the CI error, rebased, and fixed the merge conflict

**Pull request merged**
