### PR TITLE
Fix incorrect formatting of input and output of g2.dat

### PR DESCRIPTION
**Pull request by duncanspumpkin**

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Does not build:
```
/home/michael/Programma's/Code/CLionProjects/OpenRCT2/src/openrct2/CmdlineSprite.cpp: In member function ‘bool SpriteFile::Save(const utf8*)’:
/home/michael/Programma's/Code/CLionProjects/OpenRCT2/src/openrct2/CmdlineSprite.cpp:164:111: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
  164 |                 entry32bit.offset = static_cast<const uint32_t>(reinterpret_cast<const uintptr_t>(entry.offset));
      |                                                                                                               ^
/home/michael/Programma's/Code/CLionProjects/OpenRCT2/src/openrct2/CmdlineSprite.cpp:164:112: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
  164 |                 entry32bit.offset = static_cast<const uint32_t>(reinterpret_cast<const uintptr_t>(entry.offset));
      |                                                             
 ```

**Comment by duncanspumpkin** [comment]
still an issue with this. offsets still incorrect

**Comment by duncanspumpkin** [comment]
This is working now.

**Review by Gymnasiast — APPROVED** [review]
Appears to work.

**Pull request merged**
