### PR TITLE
Improve native file dialog

### LINKED ISSUE #2992: Load landscape does not show SC4/SV4 files
Neither the built-in nor the system dialog shows these files, as they are set to only show SC6. After circumventing this (only possible on system dialogs) the landscape will load correctly (as fixed in https://github.com/OpenRCT2/OpenRCT2/commit/c31941c6dc329e18b2b15dc7128fa16ab435e8d5).

### PR DESCRIPTION
**Pull request by IntelOrca**
Work in order to fix #2992.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
The pattern names should be translatable. For some of them, there are already strings in the language file:
```
STR_1043    :OpenRCT2 Saved Game
STR_1044    :OpenRCT2 Scenario File
STR_1045    :OpenRCT2 Landscape File
STR_1046    :OpenRCT2 Track Design File
```

**Comment by IntelOrca** [comment]
@Gymnasiast Yeah, its on the todo list - thanks for identifying what we have currently.

**Comment by Gymnasiast** [comment]
A list of issues it should fix:
- #2992
- #3062
- #3112
- (potentially) #3114

**Comment by IntelOrca** [comment]
@Gymnasiast not #3114, and that will require changes to network rather than this.

**Pull request merged**
