### PR TITLE
Feature: "Follow Sprite" title sequence command (cont.)

### PR DESCRIPTION
**Pull request by trigger-death**
Sprites can now be followed with title sequence commands. This is continued from the unfinished PR  #5930

Also added framework for extended following of sprites without the need to handle exceptions when peeps are on a vehicle and such. This is used in both main window and the command editor.

Added a global list of litter names arranged based on litter type. `const rct_string_id litterNames[]` in `sprites.c`.

### Strings Added

```
STR_TITLE_EDITOR_COMMAND_FOLLOW = 6159
STR_TITLE_EDITOR_COMMAND_FOLLOW_NO_SPRITE = 6160
STR_TITLE_EDITOR_COMMAND_TYPE_FOLLOW = 6161
STR_TITLE_COMMAND_EDITOR_SELECT_SPRITE = 6162
STR_TITLE_COMMAND_EDITOR_FOLLOW_NO_SPRITE = 6163
STR_TITLE_COMMAND_EDITOR_FORMAT_SPRITE_NAME = 6164
STR_LITTER_VOMIT = 6165
STR_DUCK = 6166
```

### Selectable Sprites

* Guests
* Staff
* Vehicles
* Ducks
* Balloons
* Litter (why not, let's say it's an Easter egg)

### Preview

Preview

### CODE REVIEW

**Comment by janisozaur** [comment]
This is extending the title sequence script with new commands.  What happens when a user loads a title sequence using `FOLLOW` command in an older build, which does not support it? Should we consider versioning of the script engine?

**Comment by Broxzier** [comment]
An issue that I was unable to solve in a nice way is that when the camera rotates or when the window gets resized, it stops following the sprite.

**Comment by trigger-death** [comment]
@janisozaur Any unsupported command is just ignored when loading a script.

@Broxzier I'm surprised but apparently it still happens with my smart follow functionality, I'll have to fix that.

**Comment by trigger-death** [comment]
This also fixes #4869

**Comment by trigger-death** [comment]
Can you guys let me know when you're interested in getting this merged. I've been busy so I don't have the time to maintain the branch everytime a conflict arises. Instead, I'd prefer to fix it up once it's in the queue for merging.

**Comment by AaronVanGeffen** [comment]
With #6598 merged, I have rebased this PR on top of develop. However, I can't seem to select a sprite to follow in the command editor window — the button is always disabled.

@Broxzier or @trigger-death, could either of you have a look? I'd really like to see this merged for v0.1.2.

**Pull request merged**
