### PR TITLE
disable_clearance_checks and disable_support_limits in console

### PR DESCRIPTION
**Pull request by wolfreak99**
These can be considered useful inside the scenario editor / track designer, but due to the cheat menu not being available, they are unable to be utilized.

### CODE REVIEW

**Comment by Margen67** [comment]
Wouldn't it be better to unhide the cheat button in the scenario editor?

**Comment by Gymnasiast** [comment]
@wolfreak99 Could you make it check for cheat permission first?

@Margen67 Why not both? ;) It's useful to have a console command in any case, and I think it's better to prevent scope creep, as we have too many PRs waiting as it is already.

**Comment by wolfreak99** [comment]
It actually doesn't link to the game command that toggles the cheat via network, but more less a local only. Should I make it network compatible? If so, should i throw the sandbox mode (also in the cheats drop down menu) in as well?

**Comment by wolfreak99** [comment]
I didn't make it network only cause not much else in the console is network synced

**Comment by Gymnasiast** [comment]
Yes, please make it network compatible. Eventually the whole console should be network compatible (where applicable).
You can add sandbox mode if you like.

**Comment by Margen67** [comment]
Should the cheats button be unhidden in the scenario editor in this PR or a seperate one?

**Comment by Gymnasiast** [comment]
@Margen67 In a separate one. It's scope creep, and PRs take too much time to be merged as it is already.

**Comment by wolfreak99** [comment]
What do you mean by scope creep?

**Comment by Gymnasiast** [comment]
Scope creep is when you keep adding things to a plan, which has a high risk of getting it stuck in development hell forever. And we currently have 47 pull requests open, with a lot of them taking far too long to be reviewed/improved/rebased etc. Since that is unsatisfactory, I try to get the time each one takes down, and it's important to keep focus in order to do so.

**Comment by wolfreak99** [comment]
I have a few of my own I believe in development hell right now, i actually kinda quit updating / rebasing them and figured i'd wait until someone was to get around to saying they're ready to check it, like the money cheats i made a while back i believe.. is this okay to wait until people get to it? i try to update and respond as quick as i can but sometimes it takes a bit.. also would there be any way i can help out with reviewing PRs? even if it's just crash testing them out or something i'd be more than happy to help.

**Comment by Gymnasiast** [comment]
@wolfreak99 Well, exactly, many of your PRs are in development hell. The main problem is that reviewing and testing takes time and isn't particularly fun, but important to do. It's okay not to rebase until we get around to reviewing it.

Testing other people PRs and notifying them of the results is a good way to help.

**Comment by wolfreak99** [comment]
if you wish, any of the ones that are from me, you can comment and say to have me rebase it and then test it.. i usually test the heck out of my code to make sure it works exactly as intended. if it doesn't, i usually mention somewhere in the post that it doesn't do it. when i test the code i test for these (in order of priority) 1) it doesn't crash the game. 2) it does as intended without any weird glitches occurring, 3) if it's a multiplayer feature, it works across both network server and client properly and doesn't cause any desyncs. and that it works with the proper permissions.

**Comment by wolfreak99** [comment]
@Gymnasiast

**Comment by Gymnasiast** [comment]
Ok, the code looks good to me. What remains is testing it myself.

**Comment by Gymnasiast** [comment]
Ok, it seems to work properly.

@IntelOrca or @duncanspumpkin : could you merge this if the network safety looks good to you?

**Comment by wolfreak99** [comment]
That is inconsistent with the other set parameters and would result in unexpected behaviour, wouldn't it? Everything else takes a value, including books such as "no_test_crashes" and "test_unfinished_tracks", so it would throw someone off not needing a value. We are developers working with the code, we know it doesn't take a value, but the average user doesn't. The reason I have the second bit is so the get command shows the new value (otherwise it will show it not enabled right before it gets enabled)

**Comment by wolfreak99** [comment]
If it's synced prior to my command, the "if (gCheatsDisableClearanceChecks != (int_val[0] != 0))" should check the value that is already the same across any other client, wouldn't it? 
But anyway, would you care if i was to modify the game command to take a parameter? maybe have it take a signed int that way 0 = false, 1 = true, -1 to just toggle it from whatever it is?

**Comment by Gymnasiast** [comment]
Yeah, if you would modify the game command, that would be best. I don't think it needs to take -1 to toggle, just an unsigned int that is either 0 or 1 would suffice. You would need to find existing usages of the game command and look at other game commands to see how they take a parameter.

Don't hesitate to ask if you need help.

**Comment by Gymnasiast** [comment]
Seems to work well. :+1: 
@wolfreak99 Could you rebase this?
@IntelOrca @duncanspumpkin Could one of you verify the game command call is used correctly?

**Comment by Gymnasiast** [comment]
Why did you do the last commit? do_game_command already sets the value, no need to set it again. In my test it worked correctly.

**Comment by wolfreak99** [comment]
Oh shoot I didn't see that it was okay to just rebase , I'll revert it gimme a moment

**Comment by wolfreak99** [comment]
wait the previous also set it locally as well. but i'll still revert it.

**Comment by wolfreak99** [comment]
@Gymnasiast  okay it's rebased, but i'd like to keep the newest commit and the reversion for the moment to see if the newest was properly handling it (or if the previous was okay) when @IntelOrca  or @duncanspumpkin  checks this out.

**Comment by Gymnasiast** [comment]
What I mean is that you don't need to set it locally at all. Game_do_command does it for you.

**Comment by wolfreak99** [comment]
Not when I test it. if i remove the local assignments, it will return that the amount is whatever it previously once (as if the game_do_command sets effect AFTER the select frame). This is when in a client mode on a network.

**Comment by Gymnasiast** [comment]
Hm... it could be that the network delay causes that. In that case leave it for now; I'll leave it to @IntelOrca or @duncanspumpkin then.

**Comment by wolfreak99** [comment]
"The thing is the game_command for cheating always flips the bit: 
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/cheats.c#L397
So it doesn't matter what parameter you include with it, it will flip. But then you set the global to the value the user typed in manually. This is unnessary at best, but can result in weird behaviour when you do the following in the current state of your code:

set disable_clearance_checks 1
set disable_clearance_checks 1
it will result in having clearance_checks on locally, but off on other clients.

So you need to get rid of the assignments by any means.
And if you don't want to get rid of the parameter in the set instruction, the game_command has to be changed to take a parameter."

Wait, that part of the code it checks if the value is the same as the value it's being asked to be set to. Would I be able to just revert back to that? that "network version" label is kinda concerning, and in my opinion, this shouldn't need an update to the network or game commands at all considering it already said "user wants disableSupportLimits to be true. is disableSupportLimits true? no? okay, flip it through the through the game command so that it is true, and set it to true locally to bypass network delay issues" or "user wants disableSupportLimits to be true. is disableSupportLimits true? yes? okay ignore this and just show that it is currently true."
i don't know where you got the idea that it flips it reguardless of the if check really.

**Comment by Gymnasiast** [comment]
Why did you change this?! It was fine as it was, it even just got approval of Duncan.

**Comment by wolfreak99** [comment]
i was rewriting it to use the older verison where it wouldn't need the network to be updated or modified. i didn't know what the label "network version" was about. i got scared.

**Comment by Gymnasiast** [comment]
Why though? No need to be, we put a label on it when it touches network code, just to be sure.
I still have the version of an hour ago in my local Git.

**Comment by wolfreak99** [comment]
reread the code please, it might work this way. i feel it's more appropriate this way too. i can go ahead and add the portion of it setting to the passed parameter instead of flipping it if really necessary.

**Comment by wolfreak99** [comment]
i'd also like a response to my previous portion of if you want me to add the flipping the bit, although this already works. i feel having it directly set the value could benifit to a degree, but i could also just make another PR and refactor the cheat commands to take values as well, that way it keeps these seperate. it also allows me to change the rest of the cheats to take a parameter as well, instead of some flipping automatically, and some not, which could also help in the future as well so you won't have to think "okay so i know some cheat booleans flip automatically and some require a value, which ones are they again?".

**Comment by Gymnasiast** [comment]
I have read the code, but I want the game_command to take a parameter rather than flipping. And since your code did that and worked, there was no need to revert that. It was even nearly merged until you reverted the thing.

Obviously, it's better if all the cheats take a parameter where appropriate. You can open a PR for that if you want to and leave this one until that it merged.

**Comment by wolfreak99** [comment]
okay so just rewrite the 3 specific cheats to have direct parameters for now?

**Comment by Gymnasiast** [comment]
Yes, please.

**Comment by wolfreak99** [comment]
i'd also like to add more cheats to the cheats menu, so would i be able to prefix the console variables with "cheat_" so it's "cheat_sandbox_mode", "cheat_disable_support_limits", "cheat_disable_clearance_checks"? i feel it'd also explicitly imply that those still are cheats being modified

**Comment by Gymnasiast** [comment]
Yes, that's okay.

**Pull request merged**
