### PR TITLE
Fix #8585: Part of track missing on air powered vertical coaster (#8635)

### LINKED ISSUE #8585: Part of track missing on air powered vertical coaster
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** 746feaa

I think the picture explains it all. A reverse freefall coaster put next to it for comparison:
image

### PR DESCRIPTION
**Pull request by janisozaur**
@deurklink as original reporter of #8585, can you please check?

This work addresses a possible regression found by testpaint and tracked in https://github.com/OpenRCT2/OpenRCT2/issues/10204

### CODE REVIEW

**Comment by Gymnasiast** [comment]
I might be missing some background, but why this change? The resulting code is messier, IMO. 

If it is to address TestPaint failing: it wouldn't be the first time TestPaint is failing while the drawing is correct. That has happened in https://github.com/OpenRCT2/OpenRCT2/pull/6526 , for example.

**Comment by janisozaur** [comment]
If you vouch for the fix that's already present in the repo, feel free to close this PR. I made it as I noticed one of my commits caused an increase in testpaint's failing tests

**Comment by Gymnasiast** [comment]
I can vouch that my fix fixed #8585. I don't know if my fix also satisfied TestPaint, but the _drawing_ is correct, at least. 

If my fix fails TestPaint and your PR does not, I don't mind this going in.

**Comment by AaronVanGeffen** [comment]
Can this be closed?

**Pull request closed without merging**
