### PR TITLE
Add cheat option to show all operating modes; cleanup

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by IntelOrca** [comment]
Is it something you would change frequently enough for it to appear on the toolbar menu?

**Comment by Gymnasiast** [comment]
Hm, possibly not. You use it when merging tracks, to create a transfer track (for 'spare trains') or simply to use modes that are not available for the type of ride you're building - like using powered launch block sectioned mode on mine trains. Also, it's something one would switch on at the beginning of a session and not turn off when he/she is done.

I'll move it to the cheats menu.

**Comment by IntelOrca** [comment]
Perhaps when we add other hacks like switching track type during construction, we can make a menu item which toggles them all together.

**Comment by Gymnasiast** [comment]
Wasn't it in the plans to create a separate Hacks window/menu anyway?

Regarding the track type switching: I have rough plans for a better system, but I want to properly work them out first.

**Comment by IntelOrca** [comment]
Well that was before I thought this convenient menu. If we have a lot though, we probably should have a separate window from cheats. Just because cheats are more user friendly to novice players where as hacks aren't.

Track merging is different from switching track type. Merging is just something you have to do right now to switch track. For actual track merging, e.g. railways or crossing go karts - we need to add additional code in vehicle update to support it. For track switching without the need for dummy rides, we have to wait until we can increase the size of map_element so that it stores the track sprite type as well as the ride index (which we would want bigger too (2 bytes instead of 1)).

**Pull request merged**
