### PR TITLE
shadows for fonts

### PR DESCRIPTION
**Pull request by janisozaur**
This changes how outline is drawn for TTF fonts.

Original sprite fonts use an outline that can be achieved using following convolution matrix:
```
0 1 0
1 1 1
0 1 0
```

The TTF font rendering we have now provides a shadow that can be represented with matrix:
```
0 0 0
0 1 0
0 0 1
```

This change adapts the TTF fonts' outline to the one used by original.

Following screen shows some investigation, enlarged 5x.

First item was obtained directly from the game (title bar of guest window)

Second item shows the shadow using matrix
```
1 1 1
1 1 1
1 1 1
```

Third item shows amount of differences between the original and item 2

Fouth item shows the shadow as obtained using matrix
```
0 1 0
1 1 1
0 1 0
```

erode

Some screens from before the change:
en-GB: selection_090
pl-PL: selection_089
jp-JP: selection_088

And after:
selection_091
selection_093

This commit also highlights a bug that is present already in the game, namely there are some lines of pixels, static in the screen, that get missing shadow. To see this missing shadow it's best to use surface scaling set to 2 or 3 and hover mouse over peeps on screen. You should notice in some places the outline is missing.

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Seems like a good change! Having it consistent is a good thing, too. Come to think of it, maybe we should use Arial in bold face, too? It's more in line with the original sprite font.

On a side note, your screenshots also highlight a problem that is prevalent for the Japanese localisation — the *kanji* look a bit rubbish in OpenRCT2 using Japanese; a problem not found in Chinese. Unfortunately, changing the font doesn't seem to help. Should probably create a separate issue about that...

**Comment by Gymnasiast** [comment]
:+1:

**Comment by janisozaur** [comment]
There seems to be specific font required for Japanese, I'm not sure if I was using right one or not.

I have some plans for doing highdpi font rendering at some point, we'll see how it goes.

**Comment by AaronVanGeffen** [comment]
> There seems to be specific font required for Japanese, I'm not sure if I was using right one or not.

I set it to use MS PGothic the other day — the popular sans-serif variant. Even on OS X, where the font is present if you have Office installed, it looks off, unfortunately. I'll have to look into it.

> I have some plans for doing highdpi font rendering at some point

I implemented a very crude anti-alias system the other day. It'll be much easier to do when we're on full 32-bits colours, but as we're limited to 8-bits colours, I had to kind of hack it in. Fonts look a bit better overall, though. It's been a while, so I guess I'll rebase that and PR it, I guess.

**Comment by janisozaur** [comment]
@AaronVanGeffen 
> I implemented a very crude anti-alias system using SDL_ttf functions the other day.

Was it for OpenRCT2? Have you got any code?

**Comment by AaronVanGeffen** [comment]
> Was it for OpenRCT2? Have you got any code?

Yes, I've got it locally. I'm not satisfied quite yet, but I'll send you the patch on Gitter.

**Comment by IntelOrca** [comment]
When we go 32-bit we can use DirectWrite to draw text on Windows which renders text very nicely on high DPI screens.

**Pull request merged**
