### PR TITLE
Fix #14682: Crash when painting Swinging Ships with invalid sub type

### LINKED ISSUE #14682: [2ae172] openrct2.exe: paint_swinging_ship_structure, paint_swinging_ship, track_paint, sub_68B3FB, PaintSessionGenerate, win...
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/2ae172260a9ffdfb6c70ff58f1edcbfe2cba104f059ae7ed7e6e3145cd04d72f">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>
<tr>
    <td><strong>Attributes</strong></td>
    <td>
<strong>dummy</strong> &mdash; 1
        <ul>
                <li><code>0</code> &mdash; 1</li></ul><br>
<strong>attachment_replay.sv6r</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_park.sv6</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_config.ini</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\Lenovo\Documents\OpenRCT2\2838d15f-d007-457f-bba9-f8a1f55f73a1.ini</code> &mdash; 1</li></ul><br>
<strong>assert_failure</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_park.sv6.gz</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\Lenovo\Documents\OpenRCT2\2838d15f-d007-457f-bba9-f8a1f55f73a1.sv6.gz</code> &mdash; 1</li></ul><br>
<strong>attachment_screenshot.png</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\Lenovo\Documents\OpenRCT2\screenshot\Six Flags Magic Mountain 2021-05-16 21-29-58.png</code> &mdash; 1</li></ul><br>
<strong>commit</strong> &mdash; 1
        <ul>
                <li><code>0123a3d</code> &mdash; 1</li></ul><br></td>
    </tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>invalid-read</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
paint_swinging_ship_structure
paint_swinging_ship
track_paint
sub_68B3FB
PaintSessionGenerate
window_main_paint
window_draw_single
window_draw_core
window_draw
std::_Func_impl_no_alloc&lt;&lt;lambda_c473010a115fad0b591ee375722aa838&gt;,void,rct_window *&gt;::_Do_call
window_visit_each(std::function&lt;void __cdecl
window_draw_all
TitleSequencePlayer::SetViewLocation
TitleSequencePlayer::ExecuteCommand
TitleSequencePlayer::Update
OpenRCT2::TitleScreen::Update
OpenRCT2::Context::Update
OpenRCT2::Context::RunGameLoop
OpenRCT2::Context::Launch
OpenRCT2::Context::RunOpenRCT2
NormalisedMain
wmain</code>
        </td>
    </tr></table>

### PR DESCRIPTION
**Pull request by ZehMatt**
Closes #14682

### CODE REVIEW

**Review by duncanspumpkin — APPROVED** [review]

**Comment by duncanspumpkin** [comment]
Should probably changelog this

**Comment by Gymnasiast** [comment]
@duncanspumpkin We never put issues from Backtrace in the changelog. We could start doing this, though.

**Comment by IntelOrca** [comment]
@Gymnasiast we do, we just rename them to something more meaningful first.

**Comment by Gymnasiast** [comment]
@IntelOrca I was asked a few times to remove changelog entries when I fixed a Backtrace issue with that being given as the reason. So no, we _don't_ do that. Again, we can _start_ doing that, though.

**Comment by IntelOrca** [comment]
@Gymnasiast I think I have done it in the past, I don't see why we wouldn't put them on the changelog... unless they are a regression since last release.

**Comment by Gymnasiast** [comment]
Ok, let’s do that from now on, then.

**Pull request merged**
