### PR TITLE
Close #15630: Refactor TrackDesign

### LINKED ISSUE #15630: Refactor TrackDesign code
The track design code is currently passing the error results by global variables. Considering how complex the code is it should be cleaned up first.

The track design placement has multiple operating modes and based on that it returns different things. Currently the results are either passed via return or static variables.

Following modes currently exist:
```
    PTD_OPERATION_DRAW_OUTLINES,
    PTD_OPERATION_PLACE_QUERY,
    PTD_OPERATION_PLACE,
    PTD_OPERATION_GET_PLACE_Z,
    PTD_OPERATION_PLACE_GHOST,
    PTD_OPERATION_PLACE_TRACK_PREVIEW,
    PTD_OPERATION_REMOVE_GHOST,
```

As an example, if the mode is using PTD_OPERATION_GET_PLACE_Z then place_virtual_track would result the z coordinate in the money32 return value, which makes things really hard to understand.

A better way to solve this is to give each operating mode its own function, so PTD_OPERATION_GET_PLACE_Z  would be something like TrackDesignGetPlacementZ, PTD_OPERATION_REMOVE_GHOST would become TrackDesignRemoveGhosts and so on. Those functions should return the specific data for the query/action, for TrackDesignGetPlacementZ the result type could be:
```cpp
struct TrackDesignPlacementZ
{
   rct_string_id ErrorMessage = STR_NONE;
   Formatter ErrorArgs;
   int32_t z{};
};
```
Since those functions call game actions, the error message and its arguments should be copied when something is wrong. When ErrorMessage is STR_NONE we can use z.

### PR DESCRIPTION
**Pull request by ZehMatt**
Initially I just wanted to get rid of the statics but I ended up fixing it all.

Closes #15630, #15620

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Notes for testing:
- SV4 and SV6
- Placing on ground with only construction rights (e.g. Barony Bridge)
- Placing in parks with height limitations
- Placing in parks where trees may not be removed
- Placing when intersecting with large scenery
- Placing when intersecting with park entrance
- Placing when intersecting with other ride

**Comment by ZehMatt** [comment]
> Notes for testing:
> 
> * SV4 and SV6
> * Placing on ground with only construction rights (e.g. Barony Bridge)
> * Placing in parks with height limitations
> * Placing in parks where trees may not be removed
> * Placing when intersecting with large scenery
> * Placing when intersecting with park entrance
> * Placing when intersecting with other ride

Having the track design collide with the park entrance results in "Land not owned" because its technically not inside the Park, given this is checked prior to tile elements this is something to keep in mind, I don't think that we need a specific error for this case, it would make the code a bit more complicated. As for the other tests I do get all the expected error messages and behavior now, I haven't tested any SV4 things.

**Comment by Gymnasiast** [comment]
What happens if you make the land under the park entrance owned? This is what is often done by cheats.

**Comment by ZehMatt** [comment]
image

**Review by Broxzier — APPROVED** [review]
Tested and works as expected.

**Comment by Gymnasiast** [comment]
I will review this and merge it into v0.3.5 if I find no bugs.

**Review by Gymnasiast — APPROVED** [review]
Will merge it once you added a changelog entry.

Edit: added one myself: https://github.com/OpenRCT2/OpenRCT2/commit/b78908caa20310452340769a9ec050ae70756e66

**Pull request merged**
