### PR TITLE
Fixes #996

### LINKED ISSUE #996: Scrolling gets stuck on some rotations and maps
1. Choose scenerio "Prehistoric - After the Asteroid" (i.e. Crater Carnage).
2. Rotate view 90 degrees clockwise.
3. Scroll the view all the way to the bottom.
4. Try to scroll up again.

This bug exists in vanilla RCT2 too.

### PR DESCRIPTION
**Pull request by kmdreko**
The checks weren't done quite right

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
Suffers from #772

**Comment by kmdreko** [comment]
Sorry to say @duncanspumpkin, but the develop branch suffers from #772

**Comment by Nubbie** [comment]
There is a lot of issues about the camera sliding against corners, if this fixes it, it maybe could close 5 issues

**Comment by Nubbie** [comment]
Update: Notice this bug is one most maps! Not just the one mentioned in the issue,

**Comment by mrtnptrs** [comment]
As #772 is fixed now, can't this be rebased and merged to fix the issue?

**Comment by mrtnptrs** [comment]
Anyone?

**Comment by Gymnasiast** [comment]
I have put a rebased version here: https://github.com/OpenRCT2/OpenRCT2/commit/30390f436065cc0bab6a4fa09f63906b8049a423

However, it doesn't solve the issue for me, unfortunately.

**Comment by Nubbie** [comment]
I can take another look at it

**Comment by Gymnasiast** [comment]
This is now merged. It doesn't fully solve the issue, but it slightly improves it.

**Pull request closed without merging**
