### PR TITLE
Fix staff statistics overflow

### LINKED ISSUE #16561: Staff statistics overflow
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (45debee on develop) provided by GitHub

### Describe the issue

The "lawns mown" (presumably other staff statistics) will overflow to a negative number after enough lawns have been mown. (At the very least, maybe this should be an unsigned value?)

image

### Area(s) with issue?

_No response_

### Steps to reproduce

1. Hire handyman and set to only mow lawns.
2. Wait a very long time.
3. Eventually, the lawns mown statistic will overflow.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by skdltmxn**
This PR fixes #16561.
I will work on Localisation repo after merge.

### CODE REVIEW

**Review by tupaschoal — COMMENTED** [review]
Seems like replays will need to be re-recorded

**Comment by duncanspumpkin** [comment]
You will need to bump the network version and the park file version as it will not be forwards compatible with previous versions. After that I can rerecord the replays.

**Comment by duncanspumpkin** [comment]
Technically this doesn't fix the issue just pushes it out to a much larger value but that isn't really a problem.

**Comment by skdltmxn** [comment]
> You will need to bump the network version and the park file version as it will not be forwards compatible with previous versions. After that I can rerecord the replays.

Should park file version be bumped?
There was no change in save file format.

**Comment by ZehMatt** [comment]
I believe the park file currently encodes each field as uint32_t when even when its smaller so it should be fine I think.

**Comment by skdltmxn** [comment]
Bumped up network version!

**Comment by duncanspumpkin** [comment]
> I believe the park file currently encodes each field as uint32_t even when its smaller so it should be fine I think.

Although true it does check the limits on import so the save created in this version will crash the older version so it still needs a bump.

**Comment by duncanspumpkin** [comment]
> Should park file version be bumped? There was no change in save file format.

The staff entity structure is saved directly to the park file so any change to it changes the park file.

**Comment by skdltmxn** [comment]
> > Should park file version be bumped? There was no change in save file format.
> 
> The staff entity structure is saved directly to the park file so any change to it changes the park file.

I see. Also bumped up park file version!

**Comment by ZehMatt** [comment]
Should this have a changelog entry?

**Comment by duncanspumpkin** [comment]
Argh network version needs another bump. No i don't think it needs a changelog as it's all part of the nsf

**Comment by duncanspumpkin** [comment]
Ffs rebase failure due to vs stashing a file change

**Comment by skdltmxn** [comment]
oops just accidentally rebased develop and reverted back.

**Pull request merged**
