### PR TITLE
Fixes for launchpad

### PR DESCRIPTION
**Pull request by janisozaur**
These changes should let us re-enable builds on Launchpad, now for all supported platforms (amd64, arm64, armhf, i386).

The caveat here is I had to switch code hosting on Launchpad from bzr to git, which does not feature auto-import.

zaznaczenie_146

### CODE REVIEW

**Comment by janisozaur** [comment]
It still does not generate the segment files required for non-i386 builds, I intend to address that at some point in future.

**Comment by marijnvdwerf** [comment]
Does that meant that most people who attempt to install will automatically get the x64 build?

**Comment by janisozaur** [comment]
No, why would it mean that?

**Comment by marijnvdwerf** [comment]
Seemed logical to me that the 'best fitting' version would be picked automatically when installing something. So was afraid this might lead to even more people accidentally installing the x64 version.

**Comment by janisozaur** [comment]
I intend to have two PPAs to solve that: one that only has i386 version and the other which has all four.

**Comment by Gymnasiast** [comment]
This PR is OK AFAIC.

**Comment by janisozaur** [comment]
Ok, it will conflict with #4376 , so once it is merged, I will update this branch and merge it.

**Pull request merged**
