### PR TITLE
Ready copyright notice for clang-format

### PR DESCRIPTION
**Pull request by Broxzier**
Clang-format sees the text behind `#pragma region` as code and formats it. Instead of stating the copyright and date there, it's now in the comment block right below it. The text "Copyright" is left in the `#pragma region` line, as clang-format sees it as a single identifier. It now reads:

```cpp
#pragma region Copyright
/*****************************************************************************
 * Copyright (c) 2014-2018 OpenRCT2 Developers
 *
 * OpenRCT2, an open source clone of Roller Coaster Tycoon 2.
 *
 * OpenRCT2 is the work of many authors, a full list can be found in contributors.md
 * For more information, visit https://github.com/OpenRCT2/OpenRCT2
 *
 * OpenRCT2 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * A full copy of the GNU General Public License can be found in licence.txt
 *****************************************************************************/
#pragma endregion
```

I took the opportunity to normalize the dates and spaces before the `*`, and add the copyright notice to the source files where it was missing them (except for third-party and the generated resources.h file).

### CODE REVIEW

**Comment by IntelOrca** [comment]
In this case I think the pragma should be removed altogether and a smaller notice be used.

**Comment by Broxzier** [comment]
Agreed, the description of what OpenRCT2 is seems unnecessary, a link to the github page may be nice to keep in. Should the mention of GNU stay?

**Comment by IntelOrca** [comment]
Perhaps just:
```cpp
/*****************************************************************************
 * OpenRCT2 is the work of many authors, a full list can be found in contributors.md
 * For more information, visit https://github.com/OpenRCT2/OpenRCT2
 *****************************************************************************/
```

**Comment by AaronVanGeffen** [comment]
Hmm. I'm fine with shortening the notice a little, but I think the lines about the GNU licence should stay.

**Comment by Broxzier** [comment]
@AaronVanGeffen I've been looking around and there are many people asking if these notices are mandatory, and everywhere there is someone who says it is only adviced, but can't be made mandatory by law. The page you link to only states that you "should" include them.

Even so I do think a licence notice is good to have, but then a shorter version. What about:

```cpp
/*****************************************************************************
 * OpenRCT2 is the work of many authors, a full list can be found in contributors.md
 * For more information, visit https://github.com/OpenRCT2/OpenRCT2
 * OpenRCT2 is licensed under the GNU General Public License version 3
 *****************************************************************************/
```

**Comment by AaronVanGeffen** [comment]
I suppose I really like the canonical whitespace the current copyright notice brings. A copyright line —the most important bit!— followed by some whitespace, then some details. I'd hate to see it reduced to just one blob of text.

**Comment by Broxzier** [comment]
Now rebased and applied to `Http.h` which seemed to cause issues when checking out on Windows. Probably because the file `http.h` (lowercase) did exist and was edited too.

**Comment by Gymnasiast** [comment]
Perhaps we should point to the license.txt file in the copyright header. Just specifying it is released under the GNU GPL 3 is not enough, I think.

**Comment by Broxzier** [comment]
@Gymnasiast I think it's enough.

> **Why should I put a license notice in each source file? ([#NoticeInSourceFile](https://www.gnu.org/licenses/gpl-faq.en.html#NoticeInSourceFile))**
>
> You should put a notice at the start of each source file, stating what license it carries, in order to avoid risk of the code's getting disconnected from its license. If your repository's README says that source file is under the GNU GPL, what happens if someone copies that file to another program? That other context may not show what the file's license is. It may appear to have some other license, or no license at all (which would make the code nonfree).
>
> Adding a copyright notice and a license notice at the start of each source file is easy and makes such confusion unlikely.
>
> This has nothing to do with the specifics of the GNU GPL. It is true for any free license.

**Comment by Broxzier** [comment]
@AaronVanGeffen Yes, that's the plan. It's just easier to spot mistakes with GitHub's diff viewer.

**Pull request merged**
