### PR TITLE
change openrct2/ride methods to UpperCamelCase, part 1

### PR DESCRIPTION
**Pull request by Sadret**
Most files finished. Todo:
- JuniorRollerCoaster
- WoodenRollerCoaster
- RideRatings
- TrackPaint
- Ride get_ride_entry (clashes with Ride::GetRideEntry)

### CODE REVIEW

**Review by Gymnasiast — APPROVED** [review]
Looks good, could you rebase?

**Comment by Sadret** [comment]
> Looks good, could you rebase?

Will do, I actually had to fix some compiler issues first (cf Discord and updated comment).

**Comment by Sadret** [comment]
wrong button ><

**Comment by Sadret** [comment]
Should be fine now.

**Comment by Sadret** [comment]
Pressed the wrong button for the second time now.
I am tired and should go sleep now.

**Comment by Sadret** [comment]
Code formatting fixed.

**Pull request merged**
