### PR TITLE
Add three colours to Flying RC

### PR DESCRIPTION
**Pull request by karst**
Split of #17782
as requested. I don't know how much ask there is to add more presets but I thought it was a nice addition to have these to give new inspiration to people while building the Flying RC.

image

These color schemes are inspired by F.L.Y at Phantasialand, Manta at SeaWorld Orlando and Tatsu (old scheme) from Six Flags Magic Mountain.

--------

### CODE REVIEW

**Comment by Basssiiie** [comment]
While F.L.Y. is not a B&M, if you're still adding the colours anyway, I'd go with bordeaux red and dark brown instead of saturated red and dark yellow.

**Comment by karst** [comment]
Yea, I know it's not but there's currently no way to recreate FLY and B&M track is the closest. It's also the reason why I decided to make sprites for the booster. No B&M flying coaster has a launch but FLY (new gen vekoma) does. This is what it would look like with Bordeaux and Brown. 
image

I personally feel this colour scheme is too dull which is why I went with the saturated red and dark yellow instead. The colour scheme is somewhere in between the two so I decided for the one that gives more of a pop. Beside this gives people a way to think about another way to use their colours as I don't see this scheme used.

**Comment by Basssiiie** [comment]
What about bordeaux red for the spine and saturated red for the edges? For the supports maybe saturated brown is an option as well. At least more similar and better fitting than dark yellow I think. 😛

**Comment by karst** [comment]
I feel that the most similar track is the suspended swinging coaster track, but it doesn't have inversions.

image

Also this is what that would look like which also feels a tad off to me ^^;

**Comment by Gymnasiast** [comment]
Looking at photos, bordeaux red + dark brown might look dull, but it _is_ accurate. Nevertheless, I would be okay with bordeaux red + dark yellow too.

**Review by Gymnasiast — APPROVED** [review]

**Pull request merged**
