### PR TITLE
Fix desync if "Handyman mow grass by default" is checked.

### PR DESCRIPTION
**Pull request by ZehM4tt**
Fix desync if "Handyman mow grass by default" is checked.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
IMO, the entire option should be cut from the game. It's completely useless.

**Comment by IntelOrca** [comment]
Rather than cut it, there should be a better solution. For example, a clone button so you can make many handymen that have the same attributes.

**Comment by pizza2004** [comment]
I love this option.  I don't want to have to manually worry about copying a handyman or turning on grass mowing every time I hire a guy.

**Comment by Gymnasiast** [comment]
@pizza2004 This is getting old. Your comments are always about how we to add x or keep y. You don't have to maintain it. Also, you can apparently handle interfaces full of buttons and options. Good for you, but this does not apply to everyone. Far from it.

And if the majority of your handymen mow grass, then you're probably the only person who does this.

**Comment by janisozaur** [comment]
@Gymnasiast @IntelOrca I've decided to merge it for now, as we already have this option in the game and this PR fixes it for multiplayer. Feel free to submit code to remove it altogether, if you feel it's not worth having and we'll be done with it.

**Comment by pizza2004** [comment]
@Gymnasiast Alright, what /would/ you have me comment about?  I honestly agree with you most of the time from a purely design standpoint.  I just feel like it's nice to have opinions.

**Comment by Gymnasiast** [comment]
Did you mean ' I just feel like it's nice to have _options_'?

I'm okay with people expressing opinions about features, as long as it's not the only thing they do. Most other people also report issues or help out on other issues. You (and some other people) only appear to comment if you want us to add a feature requests and when one of us proposes removing one. Basically, that comes across as if you only comment on what we're doing wrong. I'm sure that's not your intention, and you at least seem to stay calm about it.

For every feature we add, everyone pays in complexity and a more cluttered interface. The first is mostly noticeable for the devs (though not exclusively, as it can cause more bugs), the latter for everyone. It's why I try to be critical: do our users need/want this? Does it justify the complexity? For a feature with such a limited application my answer has always been 'no. It's unavailable that _someone_ does not want to see the feature go, though. ([obligatory XKCD](https://imgs.xkcd.com/comics/workflow.png))

**Comment by rwjuk** [comment]
For the record, I'd also much rather see a clone button along the lines of @IntelOrca 's suggestion rather than options in the menu for things like this. I recognise this is somewhat off-topic, but I wanted to mention it while the topic has come up.

**Comment by pizza2004** [comment]
@Gymnasiast No no, I meant opinions.  While I like options you've made me realize many times in the past why options aren't actually a great idea unless they add something significant.  I've actually played around and tried to make improvements or changes several times to the codebase but I just don't /quite/ know what I'm doing and I usually end up not being able to make it work.

I honestly agree that this is one option that's just /completely/ needless clutter.  All it really does is keep a person from checking a single box each time they hire a handyman.  The cloning tool is a much better idea.  I just don't like the extra effort is all. XD

**Comment by Gymnasiast** [comment]
> keep a person from checking a single box each time they hire a handyman

Um, you're the first person (and I mean this literally) I met who has all (or most) of their handymen mow grass. It was very often complained about in the RCT1 days and a change that RCT2 was praised for.

**Comment by pizza2004** [comment]
I personally didn't care for most of the changes in RCT2.  I'd rather play RCT1 90% of the time. :D

**Pull request merged**
