### PR TITLE
Fix overflow in ride_mode_tweak

### PR DESCRIPTION
**Pull request by PurpleMadness**
Fixes issues #3424 and #2529. Would be nice if we eventually could increase it beyond the uint8 max but this will fix the overflow at least.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
I find this a bit hard to read. I'd prefer the following:
```
-	uint8 newValue = ride->operation_option + increment;
-	if (newValue <= maxValue) {
-		window_ride_mode_tweak_set(w, newValue);
-	}

+	uint8 newValue = min(ride->operation_option + increment, maxValue);
+	window_ride_mode_tweak_set(w, newValue);
```

**Comment by PurpleMadness** [comment]
No, that would still cause an overflow in the first parameter of min. `ride->operation_option + increment` would overflow to 0 if `operation_option` is 255 and `increment` is 1. So that wouldn't solve the issue.

**Comment by duncanspumpkin** [comment]
Yes that wouldn't work as there is no promotion to int in that calculation. Personally I think the current version is fine and would merge as is

**Comment by Gymnasiast** [comment]
I still think it's hard to read this way.

**Comment by IntelOrca** [comment]
@Gymnasiast no, but its two lines of code - however if you still feel strongly against this, I can only suggest you change it to cast to an int or something first and then clamping it, and then casting back to int8.

**Comment by PurpleMadness** [comment]
I agree that it could be better readability-wise, but it's hard to do so while taking care that it doesn't overflow while performing checks. Casting it to an int would help, but I figured that would allocate unnecessary memory for only two lines that aren't impossible to read, and that it's not worth the tradeoff. 

Like I said in the original post, it would be best if we could just fix the origin of the overflow and make it an int16 or int32 but I don't know if that's possible at the moment. So I wouldn't worry too much about readability since I'm sure it's going to be rewritten in the future anyway.

**Comment by IntelOrca** [comment]
> Casting it to an int would help, but I figured that would allocate unnecessary memory for only two lines

Not sure what you mean by allocate, compilers work with registers at this level, it will probably just use a ```movzx``` instruction on itself.

**Comment by PurpleMadness** [comment]
Ah okay, I don't know enough about low level stuff.

**Pull request merged**
