### PR TITLE
Fixed filenames being cut off when there's a dot in them

### PR DESCRIPTION
**Pull request by Broxzier**
Fix for #2241

### CODE REVIEW

**Comment by janisozaur** [comment]
@Broxzier can you please name commits properly, as in something like "Fix first dot truncating save file name" instead of "Fix for #2241"? makes it much *much* easier to browse through commits with git only without having to resort to github

**Comment by janisozaur** [comment]
Oh wait, i typed too fast, sorry

**Comment by Broxzier** [comment]
Oh sure, but I saw other pull requests doing the same so I thought it was how things are done.

**Comment by janisozaur** [comment]
Sorry, I removed my comment as I judged too quickly. Sorry about that :)

I now see you named your commits properly and it was only name of pull request.

Also a hint: https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by Broxzier** [comment]
Alright, I'll try to do that next time. I'm still relatively new to git and hithub, and this is the first PR I made from a branch.

**Pull request merged**
