### PR TITLE
Fix client not resuming when server toggles pause. (Issue #5686)

### PR DESCRIPTION
**Pull request by ZehM4tt**
Fixes game commands being no longer processed once the client entered pause state.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
@janisozaur Would this require a network version bump?

**Comment by ZehM4tt** [comment]
Damn I keep forgetting to increment it, can't we find a way to not do that per hand.

**Comment by janisozaur** [comment]
There are two possibilities:

1. Enforce everyone to be on the same commit
2. Prove that introduced changes do/do not affect any network interactions.

You can read that as "no".

**Comment by janisozaur** [comment]
Actually, I tested the wrong build. It works as intended.

**Pull request merged**
