### PR TITLE
Refactor cursors to C++ and improve isolation

### PR DESCRIPTION
**Pull request by IntelOrca**
Can someone update the xcode project? E.g. @marijnvdwerf @LRFLEW 
Thanks.

### CODE REVIEW

**Comment by janisozaur** [comment]
```
/home/travis/build/OpenRCT2/OpenRCT2/src/platform/shared.c:61:20: error: ‘_cursors’ defined but not used [-Werror=unused-variable]
 static SDL_Cursor* _cursors[CURSOR_COUNT];
                    ^
```

**Comment by LRFLEW** [comment]
IntelOrca/OpenRCT2#31

**Comment by LRFLEW** [comment]
On a related note to cursors:

I noticed that the cursors are designed to match the Windows cursor, which is a white cursor with a black outline. MacOS has a sort-of inverted cursor, which is black with a white outline. I'm wondering if a (toggleable) alternative color scheme for the cursor might be nice to have to help the game match the aesthetic of the platform. I tried just inverting the colors of the existing cursors, but it didn't look right, both because the images (the tree, bench, etc. in the cursor) don't work inverted, and MacOS actually uses a "white cursor with black outline" for their more detailed cursors, such as the one used for `CURSOR_HAND_POINT`.

**Comment by marijnvdwerf** [comment]
What about cursors for retina/high-dpi screens?

**Comment by LRFLEW** [comment]
A retina cursor would require both redrawing the cursors (or at least semi-manually scaling them), and would likely require OS-dependent code to implement as `SDL_CreateCursor` doesn't have a means of setting the DPI for cursors. I think color-matching is a higher priority if we're going to mess with this.

**Pull request merged**
