### PR TITLE
Add RCT1 edge styles

### PR DESCRIPTION
**Pull request by Gymnasiast**
SV6 reserves 4 bits for the terrain edge. This means that it can actually save 16 different land types.

This PR uses the remaining 12 slots to add the RCT1 terrain edge styles.

Things to note:
- It only adds edge styles, not surface styles
- For people who don't have RCT1, there is no visual difference, it will just draw rock.

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
If you don't have RCT1 linked, this happens:
screenshot_20180112_141429

**Comment by IntelOrca** [comment]
This is adding new data to SV6. It would be something we'd have to support forever more when importing SV6 when we have a new save format which will use objects for wall textures.

**Comment by Gymnasiast** [comment]
Hm, I thought I removed the images from the drop down. Hold on.

**Comment by JeroenDStout** [comment]
@IntelOrca Wall styles would always require some bits to be used, this just uses all of them (which I understand are already allotted). Does that really add new data to the SV6 or just use the existing data more thoroughly? It is not unlike using unused peep/ride data, like flags for paths to reserve them at crossings.

**Comment by Gymnasiast** [comment]
Quoting IntelOrca from private chat:
"its only going to just be a larger array which we already have anyway for SC4. I'd just thought I'd mention it."

What I think he means is that we will need to take it into account when importing S6 files.

**Comment by rwjuk** [comment]
What happens if you load an SV6 with an extra style in RCT2, or RCTC? Will it just show rock?

**Comment by Gymnasiast** [comment]
It will either show corrupted sprites or crash.

**Comment by Lastorder-DC** [comment]
pr
OpenRCT2 with this patch

without_pr
OpenRCT2 without this patch

rct2
Vanila RCT2

**Pull request merged**
