### PR TITLE
Horizontal Clipping

### PR DESCRIPTION
**Pull request by Broxzier**
Images can tell what this feature does better than words.

The updated window:
image

And how it is used:

### CODE REVIEW

**Comment by jensj12** [comment]
Awesome!
As with the vertical clipping, it would be nice to have a way to adjust your selection by one tile, instead of selecting the entire area again. A shrink/grow that works in all 4 directions simultaneously would work fine.

**Comment by Broxzier** [comment]
@jensj12 I thought of doing that, but I think that'll clutter the window too much. You'll need 2 buttons for each side, so 8 buttons in total. I've tested this way of selecting with multiple parks, and haven't gotten in a situation where I couldn't get the side I was interested in to be exactly where I wanted.

I do agree that the UX can be improved by showing at least the area of the last selection, to make it easier to select the next.

**Comment by janisozaur** [comment]
How does that work if user starts building outside of the boundaries? Or hover a ghost?

**Comment by AaronVanGeffen** [comment]
This is cool, but I think it'd be more useful if a horizontally clipped surface would also render the ground underneath — as though it were on the map edge, so to speak. Could be useful for underground ride construction or inspection thereof and what not, perhaps.

**Comment by Broxzier** [comment]
> @janisozaur How does that work if user starts building outside of the boundaries? Or hover a ghost?

It just won't show the elements outside of the area, much like when you build something above the clip-height that already existed.

@AaronVanGeffen I'm not familiar with the paint code, but I'd like to try. I expect for surface elements it just has to check wether or not its neighbour is in view, and if not then assume it has a baseheight of 2, like the outer ring of the map.

**Comment by Broxzier** [comment]
I've got the drawing of edges mostly working, this makes the clipped land looks much more solid now:
dynamite dunes 2018-05-15 00-28-06

Except for a few 'edge' cases:
image

@janisozaur This is how it looks while placing a ghost track:
dynamite dunes 2018-05-15 00-29-26

**Pull request merged**
