### PR TITLE
Consistently use literal suffix L in upper-case and u in lower-case

### PR DESCRIPTION
**Pull request by Broxzier**
The majority of our codebase uses upper-case integral suffixes, this PR makes them more consistent. The main reason for wanting them upper-case is to avoid confusion the digit `1` with the letter `l`:

image

Clang-tidy even has a check, plus automatic fix for this:
https://releases.llvm.org/11.0.0/tools/clang/tools/extra/docs/clang-tidy/checks/readability-uppercase-literal-suffix.html

### CODE REVIEW

**Comment by Gymnasiast** [comment]
I find this decreases legibility for anything that just uses a `u` suffix. `1u` is just easier to read at a glance than `1U`, which looks like a two-digit number at first glance.

**Comment by Broxzier** [comment]
Alright, I've added a second commit that makes all unsigned `u` suffixes lowercase: bf9b61fd6be685f41f3cd999c6cf0fef12abe28b

Including `ULL` -> `uLL`, to at least be consistent with its usage. I'm not sure if I really like this mixed usage of cases, though. FWIW there's nothing about it in the C++ Core Guidelines.

**Review by tupaschoal — COMMENTED** [review]
This seems fine to me. I don't really mind the lowercase `u`, maybe we just need getting used to. I searched and though people generally consider uppercase for all numeric literal suffixes, it seems like they're mostly only worried about lowercase `L`.

This needs rebasing to be merged.

**Comment by Broxzier** [comment]
Rebased.

> I searched and though people generally consider uppercase for all numeric literal suffixes

That's what I found too, I'm still not convinced this mixed usage is really better, but the main point of this PR is the uppercase L anyway.

**Review by tupaschoal — APPROVED** [review]

**Pull request merged**
