### PR TITLE
Move formatter to seperate file. Rework GetMeasurement

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Trying to get the tooltip functions to be a bit more sensible lead me off on a little detour.

### CODE REVIEW

**Review by tupaschoal — COMMENTED** [review]
This looks fine, though I wonder how all other files are getting the `Formatter.h` include if they are not including it themselves, I guess it's all through the `Ride.h`

**Comment by duncanspumpkin** [comment]
Yeah i was a bit disappointed that I didn't need to include anywhere. We really need to break up the big include files

**Comment by tupaschoal** [comment]
Maybe define the OpenRCT2String in a tiny separate file? So you don't need to draw the Formatter into the headers just for it (as most of the functions will have `Formatter&` and thus will be forward declarable)

**Comment by duncanspumpkin** [comment]
The OpenRCT2String takes a Formatter not a reference so can't be split from the file.

**Review by ZehMatt — APPROVED** [review]

**Pull request merged**
