### PR TITLE
Fix sound music mixing

### LINKED ISSUE #1270: Make sound volume only control sound.
The sound volume slider controls both game sounds and ride music. It should just control the sound volume. I don't think there is a need for a master volume control as you can just set both the sound and music sliders to 0.

### PR DESCRIPTION
**Pull request by IntelOrca**
Closes #1270 and #2487.

### CODE REVIEW

**Comment by janisozaur** [comment]
Title screen music disregards globally disabled sound.

**Comment by IntelOrca** [comment]
@janisozaur either I can't reproduce or I don't understand what you mean

**Comment by janisozaur** [comment]
zaznaczenie_107

Both `Sound` and `Music` are disabled, but the title screen music selection other than `None` causes music to get played.

**Comment by IntelOrca** [comment]
That is expected behaviour... that is why you can set title music to none and why it specifically says "ride music"

**Comment by janisozaur** [comment]
Is it really? :(

I find it quite strange and I assumed `Sound` means any noises the program makes, so disabling it here would cause no audio at all to get rendered.

**Comment by IntelOrca** [comment]
@janisozaur yes this seems to vary depending on country or something. Would it be clearer if it says "sound effects"?

**Comment by janisozaur** [comment]
Perhaps… I feel like I'm not the best person to ask. Perhaps someone else can comment?

**Comment by janisozaur** [comment]
@IntelOrca are you sure this is the proper way to do things? I've recently watched few streams on twitch where I guided people over to OpenRCT2 (from vanilla) and each one of them complained about music in the intro being too loud and they found it confusing how to change it.

**Comment by IntelOrca** [comment]
@janisozaur Why don't they just turn down their volume?

**Comment by janisozaur** [comment]
no idea. I'm just pointing out they are trying to do what I'd done, few comments above.

**Comment by IntelOrca** [comment]
You can still set the global volume in the config file, there is just no UI for it.

**Comment by Patrik356b** [comment]
Can we get a separate volume slider for the title screen?

A few other very minor things to consider too:
* Add the option to play a custom0.wav file (because 1 and 2 is for ride music)
* Random title screen music option

**Comment by IntelOrca** [comment]
> Can we get a separate volume slider for the title screen?

Yes

Custom music however will be once we have a new object format. Hopefully not long now.

**Comment by IntelOrca** [comment]
I said yes to having a third slider for global volume but no one has submitted a PR for it yet.

**Comment by Gymnasiast** [comment]
Oh ok, must have misremembered then.

**Pull request merged**
