### PR TITLE
Set branch/sha1 defines only for specific files

### PR DESCRIPTION
**Pull request by nafest**
This should fix the problems reported in #6370

### CODE REVIEW

**Comment by IntelOrca** [comment]
Don't commit commented out code, just remove it.

**Comment by nafest** [comment]
I removed the dead code in CMakeLists.txt

**Comment by AaronVanGeffen** [comment]
Doesn't #6409 cover this as well?

**Comment by janisozaur** [comment]
@nafest we have a large refactor of CMake files going on in #6409, it's likely to get merged once it's all reviewed. That PR likely already has taken it into account or will likely do that soon, so I'm afraid I will have to reject your PR.

I'd welcome help with reviewing #6409.

**Pull request merged**
