### PR TITLE
Fix #6106: Changelog file cannot be loaded on macOS

### LINKED ISSUE #6106: Changelog window does not work on macOS
**OS:** macOS 10.12
**Version:** 0.1.1
**Commit/Build:** 2f3a30f22bec866c2ee9512b1607154cf8a85887

Upon loading the window, it displays an error:
`
ERROR[/Users/michael/Privé/OpenRCT2/OpenRCT2/OpenRCT2/src/openrct2/windows/changelog.c:210 (window_changelog_read_file)]: Unable to read changelog.txt
`
Examination of openrct2.org builds shows there is there is no changelog.txt in the .app. Neither is there one if you build one yourself with Xcode 8.

### PR DESCRIPTION
**Pull request by rwjuk**

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Does this not break Windows or Linux (testing one of those will suffice, I think).

**Comment by rwjuk** [comment]
Good point - I'll test it. If it does, we can just move the `changelog.txt` file to the data path.

**Comment by IntelOrca** [comment]
It should be fine, OpenRCT2 data path defaults to exe path on Windows. And this will also fix it for Linux which was also broken.

**Comment by rwjuk** [comment]
@IntelOrca Didn't seem that way when I tested it - if you'd rather move the file, let me know and I'll revert the last commit.

**Comment by Gymnasiast** [comment]
To be sure: you tested it on macOS and Linux?
@IntelOrca Could you test on Windows?

**Comment by rwjuk** [comment]
@Gymnasiast Sorry, wasn't clear - I tested on Windows, with my platform-specific functions Windows works as well. Haven't tested Linux, but I assume from Ted's comment that it was broken in the same way as macOS. Will test later.

**Comment by rwjuk** [comment]
@IntelOrca @Gymnasiast Okay, so Linux is broken because `changelog.txt` ends up in the `doc/` folder, not `data/`. I'm not sure whether we should move the changelog to the data dir, or write a function to locate the `doc/` dir... thoughts?

**Comment by Gymnasiast** [comment]
It does not belong in the `data` dir. So I think the latter option would be better.

**Comment by rwjuk** [comment]
Retested on macOS after latest changes - still works as intended.

**Pull request merged**
